### ISSUE TITLE
evil-search-forward highlights the last instance of a given word

### ISSUE THREAD

**Issue by danieljaouen** [syl20bnr/spacemacs#10004]
#### Description :octocat:
evil-search-forward highlights the last instance of a given word

#### Reproduction guide :beetle:
- Start Emacs
- Open a new buffer (SPC b N)
- Input the following into the new buffer:

    test
    test
    test
    test
    test
    test
    
- Search (`/`) for the word "test"
- Hit Enter
- The first "test" is highlighted
- Now hit `SPC SPC` and type in `fundamental-mode`
- Now search again for the word "test" (with `/`)
- Hit Enter

*Observed behaviour:* :eyes: :broken_heart:
The last instance of "test" is highlighted

*Expected behaviour:* :heart: :smile:
The next instance of "test" is highlighted

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible auto-completion c-c++ clojure colors common-lisp django elixir emacs-lisp emoji erlang git github gnus go helm html javascript latex markdown nginx org osx python ruby ruby-on-rails scheme shell-scripts spell-checking syntax-checking tmux version-control vimscript yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by duianto** [comment]
Confirmed on the master branch. But it works as expected on the develop branch.

#### Possible cause on the master branch
The issue seems to depend on if the `M-x` `evil-search-highlight-persist` variable is enabled.

A new buffer `SPC b N` is in fundamental mode, but `evil-search-highlight-persist` is disabled, and 
`/text` `RET` both selects and highlights the next occurrence of "text".

Calling `M-x` `evil-search-highlight-persist` enables it, and `/text` `RET` selects the next occurrence, but highlights the last occurrence of "text".

#### Research
`M-x` `fundamental-mode` calls these two commands:
```
  (kill-all-local-variables)
  (run-mode-hooks)
```
source: `SPC j f` `fundamental-mode`

These commands show a buffers local variables:
```
M-x pp-eval-expression RET (buffer-local-variables) RET
```
source: The last answer on this page: https://stackoverflow.com/questions/6493331/how-to-print-all-the-defined-variables-in-emacs

Searching for the word `search`, when comparing the local variables in a new buffer and one where `fundamental-mode` has been called, only finds the entry `(evil-search-highlight-persist)` in the buffer where `fundamental-mode` has been called.

#### Develop branch
On the develop branch the `evil-search-highlight-persist` variable is also disabled in a new buffer 
`SPC b N n`, and it becomes enabled when `fundamental-mode` is called.

But `/text` `RET` selects and highlights the next occurrence of "text", both before and after 
`fundamental-mode` has been called.

The value of the `evil-search-module` variable:
- develop: `evil-search`
- master: `isearch`

might be the reason why it works on the develop branch but not on the master branch.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 00925c82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
 emacs-lisp git haskell helm html markdown org treemacs spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES
