### ISSUE TITLE
Helm microstate is still stuck with holy-mode

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1003]
And it has Vim key bindings by default. We should disable it when in `holy-mode`.

**Comment by syl20bnr** [comment]
Having Vim key bindings does not equal necessarily to "remove it in holy-mode". Since the micro-state does not get in the way I don't see a good reason to remove it, this is very similar to `normal state` accessible on `ESC`, the holy-mode does not remove it because it does not get in the way, better yet, it enables hydrid style for anyone.

See spacemacs not as a Vim only or Emacs only distribution but as an hybrid distribution with the moto:
You edit with Vim style ? You can use spacemacs.
You edit with Emacs style ? You can use spacemacs.

The helm microstate does not prevent this, the normal state does not prevent this. I see them as more options available to the user.

**Comment by tuhdo** [comment]
But it shadow 'C-SPC' binding. And even if we keep the microstste, it still uses j amd k to move up and down.

**Comment by syl20bnr** [comment]
The fact that it uses `j` and `k` is not an issue, see my remark above about the normal state. The micro-state falls in the exact same category.

Now I can agree to change `C-SPC` to `M-SPC` for instance if it is also available in ido.

**Comment by tuhdo** [comment]
Yes and it would be nice if Emacs people can use the microstate, but adapting for them. That is, remove `jk` and replace it with `np`. This is a problem with `evil-lisp-state` as well. 

We need to replace `jk` with `np` everywhere.

**Comment by CestDiego** [comment]
Emacs users are accoustumed to `C-n` and `C-p` aren't they? At least that was what I would use before. But I agree that maybe having `np` could be beneficial somehow but it would shadow stuff in more complex micro-states or layers.

**Comment by syl20bnr** [comment]
I know this is a problem but unfortunately I won't make such move because it can be very tough to support and maintain, moreover as explained before, `hjkl` map semantically to arrow keys which is not the case for `npbf`. It will complicate things too much and this is an open door for other requests touching other keys and the risk to lose control is very high.

I'm open to propose the arrow keys as well whenever `hjkl` are involved.

**Comment by syl20bnr** [comment]
@CestDiego `C-n` and `C-p` already works in helm in holy-mode, no need for a micro-state.

**Comment by tuhdo** [comment]
I don't think `hjkl` map to arrow keys. Maybe some outdated keyboard but not modern ones. If you cannot change the microstate, at least in `holy-mode` don't make it easy to get into something unexpected from Vim world without knowing. Currently, `C-SPC` is expected to mark candidates but unfortunately it switches into the microstate. As you said earlier, it's better be on `M-SPC` (if empty, hopefully).

**Comment by syl20bnr** [comment]
I verified for helm and `M-SPC` is the same as `C-SPC` so the move is easy for helm :-)
What I meant by maping the arrows is to define the arrow key bindings whenever there are `hjkl` key bindings.
