### ISSUE TITLE
Use elscreen-fr to truely emulate Vim tabs

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#10048]
[elscreen-fr](https://github.com/rocher/elscreen-fr)

With this package, you will finally can get something similar to vim Tab without being limited by an Emacs buffer. The original elscreen uses the header line (the top line of a buffer) to display tab information. Unfortunately, this approach has the following disadvantages:

- It is limited by buffer width. The more buffers you split, the less tab space you have.

- It looks distracting having a tab at the top of every buffer.

**Comment by quicknir** [comment]
It seems like a relatively minor win, and it will be quite a bit of work I think because it means digging out all of the workspace-eyebrowse stuff and giving the option for elscreen. Since workspaces integrate into layouts (are correctly persisted) this raises additional issues. Unless I'm misunderstanding and elscreen-fr can somehow be adapted to work with eyebrowse, or eyebrowse and elscreen are extremely similar, this seems like a huge amount of work.

**Comment by tuhdo** [comment]
You're right. I think if eyebrowse can support this feature, it will be better. elscreen also seems buggy, so I close for now.
