### ISSUE TITLE
c-c++ layer on develop c-c++-enable-clang-format-on-save is t, but not working

### ISSUE THREAD

**Issue by Jackson-soft** [syl20bnr/spacemacs#10041]
![image](https://user-images.githubusercontent.com/3928114/34410565-278d238c-ec0c-11e7-8298-72b1b1719d9b.png)

**Comment by Jackson-soft** [comment]
The problem lies in this function ：

(defun spacemacs//clang-format-on-save ()
  "Format the current buffer with clang-format on save when
`c-c++-enable-clang-format-on-save' is non-nil."
  (when c-c++-enable-clang-format-on-save
    (spacemacs/clang-format-buffer)))

Invoked a non-existent command "spacemacs/clang-format-buffer",and This command should be called
"clang-format-buffer"

**Comment by myrgy** [comment]
@delaanthonio, could you please take a look?

**Comment by delaanthonio** [comment]
@Jackson-soft Thanks for catching this error. I've submitted a pull request fixing this issue.

**Comment by syl20bnr** [comment]
@delaanthonio Thank you!

Should be fixed in develop.

**Comment by rdeterre** [comment]
Hi, I'm trying this with spacemacs' development branch (commit d4017b1c) and `c-c++-enable-clang-format-on-save` does not seem to have any effect.

The C/C++ layer is loaded with clang support:

```
     (c-c++ :variables
            c-c++-default-mode-for-headers 'c++-mode
            c-c++-enable-clang-support 't)
```
Also, `c-c++-enable-clang-format-on-save` is set to `t` in my `dotspacemacs/user-config()`.

When I open a C++ file, the `before-save-hook` does not contain "enable-clang-format-on-save". Its value on my machine is `(delete-trailing-whitespace spacemacs//python-sort-imports)`, because the python layer is active and `dotspacemacs-whitespace-cleanup` is set to `trailing`.

I tried removing both the Python layer and the `dotspacemacs-whitespace-cleanup` but `before-save-hook` becomes empty.

Is there something I'm not doing right ?

Thanks

**Comment by vegansk** [comment]
My `before-save-hook` doesn't contain `spacemacs//clang-format-on-save`  too:

```
before-save-hook’s value is
(tide-format-before-save spacemacs//python-sort-imports gofmt-before-save)
Original value was nil
```

**Comment by crazymousethief** [comment]
@delaanthonio Haven't merged into the develop branch yet? Format on save is a very useful feature, I can't wait😘

**Comment by delaanthonio** [comment]
@crazymousethief I don't have permission to merge the fix into develop. Furthermore, there's another pull request (#10439) that fixes this issue. It looks like someone else may merge this fix soon.

**Comment by delaanthonio** [comment]
@crazymousethief A fix was just merged into the develop branch!

**Comment by crazymousethief** [comment]
@delaanthonio Wow, that‘s great! Now we can close this issue👻

**Comment by ncihnegn** [comment]
Using lsp backends will void c-c++-enable-clang-format-on-save.

**Comment by gagbo** [comment]
I use lsp backends too and clang-format doesn't work anymore :(

**Comment by olishmollie** [comment]
In develop, clang-format-on-save only works the second time I open a c/c++ buffer, or if I use SPC-h-M to reload the major mode.

**Comment by dhanjit** [comment]
I am facing this issue, is there a work around for this untill it is fixed?

**Comment by johhnry** [comment]
Hi,

I am also facing this issue on develop (commit 5fcd84d8456581c50448bebe00bedee3432cc566), is it still in development?

**Comment by lebensterben** [comment]
@dhanjit @johhnry 
Try `M-x spacemacs/clang-format-region-or-buffer` and see whether it works manually.

**Comment by wujiang** [comment]
Make sure you have a `~/.clang-format` file.
