### ISSUE TITLE
Fatal error 11: Segmentation fault

### ISSUE THREAD

**Issue by kerak19** [syl20bnr/spacemacs#10076]
I was just fooling around with neotree and files when this happened:

```
$ fg ; /usr/bin/emacs --resume-layouts -nw
emacs -nw
Fatal error 11: Segmentation fault
Backtrace:
/usr/bin/emacs[0x50908f]
/usr/bin/emacs[0x4eefcc]
/usr/bin/emacs[0x50772f]
/usr/bin/emacs[0x5078f9]
/usr/bin/emacs[0x507985]
/usr/lib/libpthread.so.0(+0x11da0)[0x7f93233e6da0]
/usr/bin/emacs[0x4ab0e0]
/usr/bin/emacs[0x4afd79]
/usr/bin/emacs[0x419ce5]
/usr/bin/emacs[0x41c608]
/usr/bin/emacs[0x41df1f]
/usr/bin/emacs[0x451465]
/usr/bin/emacs[0x4f925d]
/usr/bin/emacs[0x4fc0b0]
/usr/bin/emacs[0x4fdb54]
/usr/bin/emacs[0x562a23]
/usr/bin/emacs[0x4ef3f5]
/usr/bin/emacs[0x5629a2]
/usr/bin/emacs[0x4ef347]
/usr/bin/emacs[0x4f3d7c]
/usr/bin/emacs[0x51d352]
/usr/bin/emacs[0x51db38]
/usr/bin/emacs[0x5635fc]
/usr/bin/emacs[0x59bf64]
/usr/bin/emacs[0x56343b]
/usr/bin/emacs[0x59bf64]
/usr/bin/emacs[0x56343b]
/usr/bin/emacs[0x55fb4c]
/usr/bin/emacs[0x56366b]
/usr/bin/emacs[0x564c1c]
/usr/bin/emacs[0x560f72]
/usr/bin/emacs[0x5635c6]
/usr/bin/emacs[0x59bf64]
/usr/bin/emacs[0x56343b]
/usr/bin/emacs[0x56374a]
/usr/bin/emacs[0x4fdd54]
/usr/bin/emacs[0x562a23]
/usr/bin/emacs[0x4ef3f5]
/usr/bin/emacs[0x5629a2]
/usr/bin/emacs[0x4ef38d]
/usr/bin/emacs[0x4f3d7c]
...
Segmentation fault (core dumped)
```

I unfortunately have no idea what caused it. I can add additional info, but i don't know what could be useful.
OS: Arch Linux.
Emacs Version: 25.3.1.

**Comment by sdwolf** [comment]
Unfortunately that stack trace is of no use since it does not contains any debug symbols (function names for every one of those hex addresses). You might try installing Emacs from source and debug like detailed [here](https://github.com/syl20bnr/spacemacs/wiki/Debugging#debugging-segmentation-faults-with-gdb).

But I suspect that just by installing a newer version of Emacs from source might fix your problem, since there is a [known bug](https://github.com/syl20bnr/spacemacs/issues/8654) that still causes segfaults, which was fixed on both Emacs master and version 26.
