### ISSUE TITLE
Friendly key binding to go back to evil-normal-state for holy-mode

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1013]
It's useful to get into insert mode for executing already available commands in Evil, such as `*` and `#`, so Emacs users won't have to waste key bindings and can reuse Evil key bindings. However, currently the `evil-escape` shadows `fd` key binding, which is frequently used for naming file descriptor variable. This can be avoided in Evil because `C-o` binds to another essential command for Vim users.

However, for Emacs users, the default of `C-o` is `open-line` and its variant, `split-line` which is bound to `C-M-o`. The difference between the two is that `open-line` splits the current line without indenting the next line, while `split-line` splits the current line and indent the next line. Essentially, both are almost the same but `C-M-o` is more useful. We can replace `C-o` with `evil-normal-state` for Emacs users to occasionally execute Evil commands.

Another solution is to rebind `fd` to something less intrusive. Probably we can replace `C-j`, since `C-j` is redundant with `RET` anyway.

**Comment by syl20bnr** [comment]
The `fd` thing is highly subjective, I never had troubles with it for instance but I understand that for some users it can be a trouble, this is why it is customizable.
`C-o` is very tempting but I don't feel comfortable to change this Emacs key binding because I feel that it is used by a lot of users to space their code blocks.
All in all there is already `ESC` and `fd` (or what you choose for it), it seems ok for me.

The less we modify the default Vim and Emacs the best it is so we have to think carefully about it, if an action is already available via another non overlapping key binding I'm not favorable to modify the default layouts, the value is not enough to be in stock spacemacs.

Now anybody can customize the key bindings but the scope will only affect him/her self.

**Comment by tuhdo** [comment]
But then, this time it's about Emacs users who never have a need for normal mode. They are used to non-modal editing. Imagine that they are in the middle of typing something, and suddenly they type `fd` and subsequent key presses don't insert anything anymore but do weird things, potentially wiping out their text. As another Emacs user said in the chatroom a while ago, he tried but cannot get into Vim way of editing.

At least make this escape to normal mode the Emacs way. That is, use chording for anything not involving inserting text. As you said, the less we modify the default, the better it is. The escape `fd` is quite intrusive to Emacs default, since it switches mode unexpectedly.

**Comment by tuhdo** [comment]
@syl20bnr We should disable `evil-escape` in `holy-mode` and put it in the documentation. You must remember people who use this mode are Emacs users, so they may not even now how to get into insert mode when they accidentally switched to normal mode. If Emacs users somehow want to use a few Vim commands, then ESC is good enough.

Then, we can add documentations about useful commands that can be used with ESC for Emacs users such as text objects (however this can be replaced with `expand-region`), or `*` and `#` or scroll up/down one line...

**Comment by TheBB** [comment]
I'm closing this, since this is a relatively simple customization for Emacs-style users, although I tend to agree with @tuhdo that it can be unexpected.
