### ISSUE TITLE
How to customize a property in a plist?

### ISSUE THREAD

**Issue by AmaiKinono** [syl20bnr/spacemacs#10147]
I am using Org layer, and I wrote my `post-init-org` function to get a bigger size when previewing LaTeX fragments:

``` lisp
(defun kinono/post-init-org ()
  (setq org-format-latex-options '(:foreground default :background default :scale 1.3
                                   :html-foreground "Black" :html-background "Transparent"
                                   :html-scale 1.0 :matchers ("begin" "$1" "$" "$$" "\\(" "\\[")))
  )
```

This works well. But I just want to specify the `:scale` property. So I rewrite it like this:

``` lisp
(defun kinono/post-init-org ()
  (plist-put org-format-latex-options :scale 1.3)
  )
```

This didn't work. Spacemacs told me this at startup:

```
An error occurred while post-configuring org in layer kinono (error: (void-variable org-format-latex-options))
```

I found [this page](https://stackoverflow.com/questions/11272236/how-to-make-formule-bigger-in-org-mode-of-emacs) so I tried to rewrite it again:

``` lisp
(defun kinono/post-init-org ()
  (setq org-format-latex-options (plist-put org-format-latex-options :scale 1.3))
  )
```

This didn't work either, and Spacemacs shows the same error message.

I wonder why this happens. I thought by the time Emacs calls the `post-init` function, the `org` package should already be load so that every variable is ready for being modified. And what should I do if I want to modify the `:scale` property without touching the others?

**Comment by nixmaniack** [comment]
From my understanding, `:init` sets up the ground before `load`ing the package. So variables are not available in any of `pre/post` `:init` stages. 
You can use `with-eval-after-load` or `spacemacs|use-package-add-hook` with `:post-config` block which will allow you to modify variables once they're loaded with package loading.

The `setq` in your example works because *you* are creating that variable and setting its value. In case of `plist-put` the plist isn't there yet (because package isn't loaded) hence it fails.

**Comment by AmaiKinono** [comment]
Thanks for your solution! It works like a charm!

**Comment by nixmaniack** [comment]
👍 You can close the issue then.
