### ISSUE TITLE
Is there any ways to open help message horizontally from frame-root-window?

### ISSUE THREAD

**Issue by Ailrun** [syl20bnr/spacemacs#10164]
Original emacs with enough `window-width` can split help buffer horizontally,
but in spacemacs it's not the case.

I tried https://github.com/syl20bnr/spacemacs/issues/5140 but it didn't work. What I tried is following.

```elisp

(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration.
This is the place where most of your configurations should be done. Unless it is
explicitly specified that a variable should be set before a package is loaded,
you should place your code here."
  (setq-default
   split-width-threshold 0
   split-height-threshold nil
   )
  )
```

Even with above code, help message splitted vertically in (and only in) frame-root-window.
What did makes this difference between pure emacs and spacemacs? Could anyone please help me....?

**Comment by Ailrun** [comment]
For additional information, I use spacemacs with `emacs` editing style.

**Comment by nixmaniack** [comment]
What do you mean by `help message`? Is it `*Help*` buffer or `*Messages*` buffer? 

If you can provide sequence of commands that you're executing and the desire layout expected, it'd be easy to reproduce and provide a solution.

**Comment by Ailrun** [comment]
@nixmaniack I mean `*Help*`. Sorry for misselected word.

What I did is

1. Install pure emacs (25.3.1)
2. Install spacemacs by `git clone`
3. Do initial settings as `emacs` editing mode
4. Type `C-h v exec-path`
5. Help buffer is splitted vertically.
6. Add above settings
7. Restart emacs
8. Repeat 4, and get the same result.

**Comment by nixmaniack** [comment]
First of all `*Help*` buffer is a special case and it's handled through `popwin`. The relevant piece of code that configures this is [here](https://github.com/syl20bnr/spacemacs/blob/4c231ae28220d28ae0a63634683b171b96c8444d/layers/%2Bspacemacs/spacemacs-visual/packages.el#L74).

Secondly, if you're on `develop` branch, there was a regression in how these new help windows are arranged. If you are on latest code it's already fixed. Related PR https://github.com/syl20bnr/spacemacs/pull/10140.

And lastly, I often get confused in emacs parlance with the words horizontal/vertical split because of how `split-window-vertically` and `split-window-horizontally` behave visually. So just want to make sure you mean following when you're saying `can split help buffer horizontally`

```
   +-----------+       +-----+-----+
   |           | -->   |     |     |
   |           |       |     |     |
   +-----------+       +-----+-----+
```
If yes, it works as expected on latest `develop` for me. 

If helps if you use `SPC h I` to create issue which includes the basic information(branch/commit, editing style, layers used etc) required to debug issues. For now, could you add that information with `SPC h d s`.

**Comment by Ailrun** [comment]
@nixmaniack Yes. What I mean by `horizontally` is just the same thing what `split-window-horizontally` means.
I will try `develop` branch and add comments!
Thank you for your detail comment!

**Comment by Ailrun** [comment]
@nixmaniack Can I ask one more thing?
What is the elegant way in spacemacs to change
```elisp
(push '("*Help*" :dedicated t :position bottom :stick t :noselect t :height 0.4) popwin:special-display-config)
```
into
```elisp
(push '("*Help*" :dedicated t :position right :stick t :noselect t :width 0.5) popwin:special-display-config)
```
?

**Comment by nixmaniack** [comment]
>Could I ask one more thing?

Indeed! 
>What is the elegant way in spacemacs to change

This was answered by bmag for exactly similar ask sometime back. I'll find and add the source. 

```elisp
(setcdr (assoc "*Help*" popwin:special-display-config)
        '(:dedicated t :position right :stick t :noselect t :width 0.5))
```

**Comment by Ailrun** [comment]
It looks like I should close this. My problem is solved.

**Comment by ericsolomon** [comment]
For anyone stumbling upon this like me, if you are using an lsp backend, the buffer is call `*lsp-help*` rather than `*Help*`
