### ISSUE TITLE
Treemacs and Neotree use different keybindings to open

### ISSUE THREAD

**Issue by myrgy** [syl20bnr/spacemacs#10165]
To open  neotree we can use `SPS p t`, while treemacs offer to use `SPS f P`
It might be great to have some keybinds for both layers.

**Comment by nixmaniack** [comment]
The convention here should be 

Key Binding | Description 
---------------|--------------
SPC f t | open file **t**ree window with current directory
SPC p t | open file **t**ree window in the **p**roject's root directory

**Comment by myrgy** [comment]
Then treemacs dont have` sps p t` its binded to `sps f P`

**Comment by Alexander-Miller** [comment]
The convention is wrong then. `SPC p t` is bound to `projecilte-find-tag`, and for me it stays that way even if I enable the neotree layer. As such I think the neotree layer is in the wrong for interfering with projectile. After all projectile has more than enough features to make the `SPC p` prefix quite crowded and trying to box my way in there will just annoy someone else.

ft/fT & fp/fP are a consistent binding scheme, and it's not like the keys should be similar across layers because you'll be using both.

**Comment by nixmaniack** [comment]
> The convention is wrong then. `SPC p t` is bound to `projecilte-find-tag`, and for me it stays that way even if I enable the neotree layer

Something's wrong then. It should be bound to `neotree-find-project-root` by default even if you don't select neotree layer as it's one of the native layers that comes with `spacemacs` distribution. 

As far as the convention goes, `SPC f` is for functions operating at file-system/file level and `SPC p` operating at project level. It(`SPC p`) has nothing to do with projectile per se. 

> it's not like the keys should be similar across layers because you'll be using both.

The point of having convention is to have consistent bindings across layers which provide "similar" functionality(completion - ivy/helm, filetree - neotree/treemacs etc). Whether it is `ft/pt` or `ft/fp` - it should be consistent.

**Comment by Alexander-Miller** [comment]
My bad, I had forgotten that `pt` is defined in my own config,. It's been a while since I touched that part.

That still leaves us with `pT` being occupied by `projectile-test-project`.

**Comment by nixmaniack** [comment]
> That still leaves us with `pT` being occupied by `projectile-test-project`.

Not sure I understand this as I don't use `treemacs` daily. If this binding provides something new, we'll have to refine the convention and/or come up with new bindings.

**Comment by Alexander-Miller** [comment]
`treemacs-projectile` vs `treemacs-projectile-toggle`. We need a key for both.

**Comment by nixmaniack** [comment]
These commands seems to cover what you need. 

Key Binding | Description 
---------------|--------------
`SPC f t` | toggle file tree 
`SPC f T` | show file in file tree with current directory 
`SPC p t` | toggle file tree with project root directory 

Based on the description of `treemacs-projectile-toggle` it seems sufficient enough command to not need `treemacs-projectile` on a separate binding as `treemacs-projectile` is doing what `treemacs`(`SPC f T`) does. YMMV. 

This certainly requires a community feedback though!

**Comment by sdwolfz** [comment]
Since the topic of filetree keybindings came up, I want to tell you a few of my frustrations related to them:

1. Toggling the file tree is an action I pretty much never want to do, yet it is available by default at very convenient keybindings `SPC f t` and `SPC p t`. What I always intend to do is navigate to the filetree with the current file highlighted, never closing the tree.

2. Toggling is a wrong term to describe the action because the buffer is being killed. What I would expect is the window to be closed but the buffer to remain open, so that when I open the filetree again, it retains it's previous state (the root and all expanded/collapsed directories being the same). Or if the buffer is killed then maybe it's state should be saved and reloaded once it is open. Right now they all open again with different root locations, every directory collapsed and I have to open them up again manually. This happens accidentally when I use a mac and press `fn` instead of `shift` and end up doing a `SPC f t` instead of a `SPC f T` (with time I get used to the keyboard but it still happens occasionally, when the pressure of being watched by a colleague while pairing makes me mistype, ending up in an even more frustrating situation, him watching me reopen the filetree and all directories).

3. Navigating to a file in a directory not under the current root changes the root directory to that file's parent. That means all my previously expanded directories are closed, which is point 2. all over again. A better way this should work would be changing the root to the common grandparent and expand until it reaches that file. This way the state is preserved.

4. Navigation keys in `neotree` and `treemacs` do different things. Using `h` and `l` changes the root directory up/down in `treemacs` which makes using it difficult when transitioning from `neotree`. I really like the fact that in `neotree` I can navigate up/down/next/previous with only one hand, using `hjkl`, never loosing visibility since the root is never changed, and also being able to open files with 'l'. 

5. It would be great if the filetree window could be resized interactively, say by pressing `<` and `>`. I looked into how this could be implemented in `neotree` an I was not able to do it, don't know about `treemacs`. Also if this functionality exists/ is possible it would be great if it persisted between restarts. 

NOTE: my experience and frustration is mostly skewed towards `neotree` since it's the one I've been using the most, I only gave `treemacs` a try for a few minutes the first time it became available in spacemacs.

Let me know if the points I raised make sense to you as well, I can help with the implementation but It's not likely I can do all of this alone.

**Comment by Alexander-Miller** [comment]
> What I always intend to do is navigate to the filetree with the current file highlighted, never closing the tree.

On treemacs that's `f C-t`. Not quite as convenient, but you can easily swap them. Or you can enable follow-mode and your current file is focused automatically.

> Toggling is a wrong term to describe the action because the buffer is being killed.

Not in treemacs, it isn't. Toggling does just what you describe, it toggles the *view* and hides/shows the buffer.

>  then maybe it's state should be saved and reloaded once it is open

Treemacs integrates with desktop-mode, though as of now it does not save expanded dirs. This area will see extensive additions once I move to a multi-root view.

> him watching me reopen the filetree and all directories).

Don't need to do that in treemacs. See `treemacs-follow-mode` & `treemacs-find-file/tag` & `treemacs-follow-after-init`.

> That means all my previously expanded directories are closed, which is point 2. all over again

Shouldn't happen on treemacs. If it does open an issue.
If you're working on files in multiple projects consider spawning multiple frames.

> I can navigate up/down/next/previous with only one hand, using hjkl

Going up is just u in treemacs, though it will also change root, when you are at the top (and that was a feature request). There's also M-j/k.
I explicitly set out to be different than neotree, which doesn't have an easy option go move your root up. That was years ago, and it's still a spacemacs extension today.

> , and also being able to open files with 'l'.

In treemacs there's half a dozen different ways to open files. I also have a mostly done feature branch that greatly expands on TAB/RET configurability and the mouse interface.

> I was not able to do it, don't know about treemacs. Also if this functionality exists/ is possible it would be great if it persisted between restarts.

That's an easy one. Open an issue in treemacs, and I'll put it on my todo list.

> I only gave treemacs a try for a few minutes the first time it became available in spacemacs.

You should try again. Treemacs is actively developed and there's an growing list of features and options. Nowadays I can say with full confidence that treemacs has more/better feaures, better looks, and better performance that neotree.

**Comment by piotrpalek** [comment]
@Alexander-Miller sorry to hijack this but I also have some issues with treemacs. Even though treemacs may have better features, performance and looks, the defaults are _REALLY_ frustrating.

For eg. when I want to open a nested file in a project. Let's say I have `root/tests/name_of_file` opened in a buffer. I use `SPC f P` to open treemacs, it properly shows the whole tree of my project up until the file I've selected. Now I want to select another file and have the buffer focused. So to switch back to the tree I use `SPC 0`, and now I've got treemacs focused, but the whole view changed to only show the current directory, I don't see my whole project anymore.

Also while changing directories is a nice feature to have, it works totally different then any file tree implementation I've seen yet. In neotree (or any other file tree I've used for that matter) when I want to navigate the tree I can use hjkl as mentioned before. But in treemacs when I want to use `l` to open a subdirectory it changes to display _only_ the subdirectory, this is not what I expect to happen at all. A better implementation would be to for eg. select the directory I want to change the view into and press a key to do it, or have the shortcuts use some modifier like CTRL while navigating.

Generally speaking I have to fight Treemacs if I want to use it, it changes views, root directiories etc and random times instead of keeping the view steady and letting me navigate it. Which is a shame because I think it works better then neotree.

**Comment by Alexander-Miller** [comment]
> So to switch back to the tree I use SPC 0, and now I've got treemacs focused, but the whole view changed to only show the current directory, I don't see my whole project anymore.

There's been a recent change in treemacs & neotree (not made by me). SPC 0 is now seems dedicated to *creating* a file tree. For treemacs that means rebuilding it with the current dir as root. You select it with M-0.

>  if I want to use it, it changes views, root directiories etc at (what seem to be) random times instead of keeping the view steady and letting me navigate it.

The only parts changing the root should be h & l, and optionally u (and the latter was a feature request). If you have a situation where the root changes when it shouldn't you should open an issue in treemacs.

Most of the keybinds you're talking about very implemented quite early, when treemacs was barely public and had no users other than myself. Right now I have built enough infrastructure to soon be working on the Next Big Thing, namely a multi-root view, including non-file roots (like open buffers or bookmarks or whatever). Many parts of treemacs will need a redesign then, especially the root navigation (if only for technical reasons). I'll be opening an issue in spacemacs to get community feedback on the resign, I suggest you make a list of the things you'd like to see changed then. Of course I also wouldn't want to push such a redesign directly to master and it'd be great if I had someone to actually test such a redesign. Hint Hint Wink Wink.

Until then you can always just rebind the parts you don't like.

**Comment by piotrpalek** [comment]
> There's been a recent change in treemacs & neotree (not made by me). SPC 0 is now seems dedicated to creating a file tree. For treemacs that means rebuilding it with the current dir as root. You select it with M-0.

Isn't Spacemacs supposed to be sane? How is this sane? :D For eg. `SPC 1` selects a window and doesn't recreate it.

@Alexander-Miller feel free to ping me over here or DM https://twitter.com/piotrpalek when you need some beta tester I'll try to help out if time permits.

**Comment by bmag** [comment]
> Isn't Spacemacs supposed to be sane?

Yes, it's supposed to. Continuing this side discussion in https://github.com/syl20bnr/spacemacs/pull/9917 (well, not much discussion to be had really, I'm just gonna fix it).

**Comment by piotrpalek** [comment]
@bmag don't take me wrong I very much enjoy spacemacs and thank you for the time you and others dedicate :) It was more or less said in jest but reading it I realized it could come off the wrong way. Hope I can carve out a bit of time and help out a bit in the future instead of only complaining. I feel like I'm only using 0.1% of Emacs ;) I couldn't configure it manually to save my life :joy:

**Comment by bmag** [comment]
Actually I thought it was fair criticism. No offense taken, so don't worry about it 😄

**Comment by nixmaniack** [comment]
The original issue was fixed with this PR https://github.com/syl20bnr/spacemacs/pull/11249. I think this issue can be closed.

**Comment by duianto** [comment]
@nixmaniack Thanks for the update.
