### ISSUE TITLE
Install from behind a restrictive firewall that does not allow emacs to connect to MELPA to get archives

### ISSUE THREAD

**Issue by longtomjr** [syl20bnr/spacemacs#10179]
Good day, The title pretty much sums it up. Any advice is welcome
What I have tried 
- Changing user agent
    - It fails to download any archives if I do this, and if I manually add the archives, it does not download the files correctly 
- Manually getting the archives and downloading them, and placing them in the correct location
   - (spacemacs just overides them with the html files on startup though)
- Setting a GitHub mirror up (still tries to get package archives from melpa)

Any pointers or help will be appreciated, I will try to contact my nework admin to see if it cannot be whitelisted, since it is blocked as (freeware or shareware)

Thanks in advance
Longtomjr

**Comment by casouri** [comment]
Have you tried ssh port forwarding?

**Comment by longtomjr** [comment]
Ok, my sollution was to download the repo onto a hard drive using @d12frosted 's elpa mirror https://github.com/d12frosted/elpa-mirror

Then I just pointed to that. For anyone with a similar issue. They way I got the link change to work was by adding this to my init.el file inside of the emacs.d directory (removing the gc-cons-threshold line)
```lisp
(let ((gc-cons-threshold (* 25 1024 1024)))
  (require 'package)
  (setq package-enable-at-startup nil)
  (setq package-archives '(("melpa" . "~/.emacs.d/elpa-mirror/melpa/")
                           ("org"   . "~/.emacs.d/elpa-mirror/org/")
                           ("gnu"   . "~/.emacs.d/elpa-mirror/gnu/")))
  (package-initialize)
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))

(garbage-collect))
```
This code is modified from @ninrod's init.el found here https://github.com/ninrod/dotfiles/blob/master/emacs/init.el

Hope this will help someone looking for a sollution

**Comment by ninrod** [comment]
Hi @longtomjr. I've written a small manual to circumvent firewalls __[here](https://github.com/ninrod/emacs-antiproxy)__, Hope people find it useful. Enjoy.

**Comment by longtomjr** [comment]
@ninrod Thanks a bunch, will check it out :), Thanks for the script as well!

**Comment by xeijin** [comment]
@ninrod Question here -- Doesn't Spacemacs also download a few of its packages directly from github? If so this is only a partial solution ...

Is there a way to get spacemacs to install the packages it needs via command line switch? I'm trying to get this working on Windows using AppVeyor CI and a few install scripts (with the end goal being to package everything generated -- including the packages spacemacs downloads -- into a single github release artifact). The bit I'm stuck on is the need to actually start emacs to get spacemacs to install fetch the relevant packages...

**Comment by casouri** [comment]
You can use emacs —eval “expression”

**Comment by xeijin** [comment]
@casouri Do you know what the expression would be to initiate the spacemacs package download?

**Comment by ninrod** [comment]
@xeijin you're absolutelly right. It works for me because I don't use spacemacs anymore; I'm rolling my own [configuration](http://github.com/ninrod/dotfiles) for a year now. 

As spacemacs uses things from github and stuff, see #7103 and related pull #6828. I am not really sure why pull #6828 was not merged in yet but @syl20bnr should have some thoughts. Also, I hear that the pr author @d12frosted went inactive on spacemacs so there's that. 

In any case that pr's patch, if you are felling adventurous,  should give you a base hack to work with.

**Comment by xeijin** [comment]
@ninrod Lord, that config is beautifully themed 😍 

And thanks for the background, I'm still attempting a CI-based solution, but may come back to these PRs should I fail... @casouri (or indeed @syl20bnr or anyone else that might know) if there is a specific expression I can feed emacs on the command line to get spacemacs to download its packages, please let me know...

**Comment by casouri** [comment]
@xeijin ```emacs --eval "(configuration-layer/update-packages)"``` should work

**Comment by xeijin** [comment]
@casouri Thank you. Do you know any way to force it through the prompts? (just tried it now and it gave me a y/n prompt on whether I wanted to update).

**Comment by casouri** [comment]
I don’t have my computer now. But one way to do that is to find that function by SPC h f, copy it to your user-configuration, rename it and modify it so it doesn’t prompt you. Then you can call it after —eval flag

**Comment by xeijin** [comment]
@casouri Thanks. Turns out the prompt is only for updating, rather than a first time install. Have now managed to get this working.

Therefore, for anyone who comes here interested, the following works to force spacemacs to install packages via the command line (be sure to point your home variable to wherever you cloned .spacemacs & provide the path to emacs as-necessary):

`emacs --daemon --eval "(progn (configuration-layer/update-packages) (save-buffers-kill-emacs))"`

xeijin/propositum will have my .ps1 script shortly (definitely not thoroughly tested).
