### ISSUE TITLE
MELPA mess aftermath: Minimize dependencies on unmaintained packages

### ISSUE THREAD

**Issue by quicknir** [syl20bnr/spacemacs#10253]
The removal of wiki packages from melpa caused some packages that are basically unmaintained (and thus, did not heed warnings about wiki packages being removed) to fail to build and is causing fresh installs of spacemacs to fail. Because the core of spacemacs is obviously common to everyone, and it's harder to hack on, and it's easy to add more packages to it, we should IMHO try to restrict spacemacs core to packages that are at least reasonably maintained, or at any rate too intrinsic to remove (e.g. helm-ag doesn't seem to be highly maintained which is worrying but I think that die is cast).

Being specific, I suggest removing `eval-sexp-fu`. This small package doesn't even seem to have any bindings associated with it and probably isn't being used by 99.9% of spacemacs users, and doesn't seem maintained at all.

In addition, I opened an issue to get the evil persistent search package (https://github.com/juanjux/evil-search-highlight-persist/blob/master/evil-search-highlight-persist.el) merged into evil: https://github.com/emacs-evil/evil/issues/1017. This one does provide useful functionality, but functionality that is present in core vim so IMHO it should get merged into core evil.

More generally we should IMHO consider an audit of the core spacemacs layers and consider moving packages outwards into layers where reasonable. Some other candidates just in say the spacemacs-editing-packages layer (where eval-sexp-fu is located; I'm trying to be impartial and suggest things even if happen to use them):

 - origami (I use this, but it can probably just be a layer that overrides evil folding. That said, orgami dependency is at least toggled, so at least package is not even being installed if you don't use it)
 - smartparens (the core functionality of generating matching paren is provided by emacs, more advanced stuff like strict mode is not used much outside of lisp developers)
 - password-generator
 - uuidgen
 - lorem-ipsum
 - hexl (editor for binary files; this should IMHO be a language layer as well)

Most of these are very niche. The others provide alternate/better functionality of things that already exist that probably only a small subset of spacemacs users really care about. There's a lot of small, mostly unmaintained emacs packages out there. We should try to avoid depending on them in core and be more picky so that users that don't tinker too much can get the most stable experience possible.

**Comment by Alexander-Miller** [comment]
> This small package doesn't even seem to have any bindings associated with it and probably isn't being used by 99.9% of spacemacs users

You sure? AFAIK the sexp flashing is default behaviour. At any rate [eros](https://github.com/xiongtx/eros) is a reasonablly same-ish replacement. Last commit was in 2016, may be it's also undermaintained, maybe theres not much more to do.

And since we're on the topic of lib cleanup: should there really be an old version of ht.el in core/libs?

**Comment by quicknir** [comment]
Looks like  I made a mistake with the evil-search-highlight-persist, it has been forked and is maintained, I'll open an issue to try to encourage the maintainer to remove the highlight dependency.

**Comment by syl20bnr** [comment]
> we should IMHO try to restrict spacemacs core to packages that are at least reasonably maintained.

The list of packages is constantly evolving so if there are good reasons to remove/replace a package, we can do it. But unmaintained is not enough because we can import the code of those packages if needed. The package has to be unmaintained and broken/not useful for us to remove it. Broken state is relative though.

For `password-generator`, `uuidgen` and `lorem-ipsum` packages, yes they are niche but they are also very useful, even unmaintained it is unlikely they get broken. It add some unique feature to Spacemacs, they are great combos coupled with the discoverability offered by `which-key`.

`hexl` can be a layer indeed.

`smartparens` is a core package of Spacemacs and an essential one, I don't think that vanilla Emacs is enough here.

`origami` is another engine for folding which I don't feel should be a layer. We want to avoid the multiplication of solo-package layers, layers are not really intended for this. We should instead provide options and `origami` is exactly that.
