### ISSUE TITLE
Proposal: Change Spacemacs layer loading system

### ISSUE THREAD

**Issue by CeleritasCelery** [syl20bnr/spacemacs#10260]
I recently gave a talk to a Emacs users group about Spacemacs. While they thought it was very cool, by far the biggest pain point was trying to understand the Spacemacs loading system via layers. This was particularly clear when I read [this](http://dsdshcym.github.io/blog/2018/01/22/compare-doom-emacs-spacemacs-vanilla-emacs/) article and the ensuing [reddit](https://www.reddit.com/r/emacs/comments/7svwsc/compare_doomemacs_spacemacs_and_vanilla_emacs/) discussion. 

Spacemacs loading system was built before `use-package` was added. When originally designed, the load order looked like this 
- spacemacs pre-init
- spacemacs init
- spacemacs post-init

However after `use-package` was added, the `init` function was split into `use-package` `:init` and `use-package` `:config`, with the `:config` actually loaded last. This means that the current load order is

- spacemacs pre-init
- use-package `:init`
- spacemacs post-init
- (lazy loaded)
- use-package `:config` 

This causes confusion as the Spacemacs `init` function is really split across the load order. So what do you do if you want your personal layer config to have the last word? You need to create a `spacemacs|use-package-add-hook` `:post-config`. But where to put it? Seems obvious that is should go in `post-config` because you want it **after** the init code. But you can't do that, because your code has to be called **before** the call to `use-package` which happens in Spacemacs `init` So that it can be **after** the lazy loaded config.

I started thinking about this, and it seemed like there had to be a better paradigm. Here are my thoughts:

Get rid of `pre-init`, `init`, and `post-init` methodology and embrace `use-package`. Create two new macros called something like `spacemacs|use-package` and `spacemacs|extend-package`. Both would create functions similar to what we have now in the layers so that packages could be excluded. But now the load order is very clear. 

- `:pre-init`
- `:init`
- `:post-init`
- (lazy loaded)
- `:pre-config`
- `:config`
- `:post-config`

The layer that "owns" the package would be the one to call `spacemacs|use-package` (which calls `:init` and `:config`) and all other layers would use `spacemacs|extend-package` (which could call the rest). I think this will make creating your own layers far more intuitive and easier for people to integrate with their existing code.

Want to get other peoples thoughts and ideas. This would be no small change.

**Comment by syl20bnr** [comment]
Thank you for taking the time to formulate this issue but to make it quick: nope. You are inverting how Spacemacs should be introduced. 

From start use-package should not be talked about. It should be introduce after the layer system.

Spacemacs underlying loading system is decoupled from use-package and always will be. The configuration layer system has been made after use-package was already used everywhere in Spacemacs.

What is missing in Spacemacs is a tutorial on layers. With a good tutorial that starts simple and adds the concepts of the system one by one there will be no ambiguity at all. 

I tried to change the vocabulary used by the layer system to prevent overlapping but the current wording is the best if you see it like this: `:init` in use-package is executed right away, there is no lazy-loading involved. So does the init functions in Spacemacs. But I don’t like to present things like his because we should not explain Spacemacs with use-package.

**Comment by syl20bnr** [comment]
I’m open to macros that will encapsulate the idomatic usage of `use-package` in the layer system, coupled with a tutorial that starts in a first part without the macros using the `pre-init / init / post-init` and `use-package` and in a second part introduces the macros. So people have a full understanding of the system. The tutorial should be 1h max in size.

I don’t know yet the design for the macros, proposals are welcome. `doom-emacs` can be an inspiration, we could change the `!` prefix by something else like `:` ? 

We can leverage org babel to build such a tutorial. Some inspiration for such a tutorial: 

https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/emacs-lisp/README.org#debugging-elisp (to be opened in Emacs)

**Comment by quicknir** [comment]
Here's what I suggest (and am prepared to start working on ). I'll simply show the old followed by the new interface in each case; the implication is that the macro used in the new code will transform it to look like the old code (so no changes have to be made beyond writing and (optionally) using the macros).

```
(defun python/init-yapfify ()
  (use-package yapfify
     :defer t
 ...
 ))
```
Becomes just:
```
(spacemacs|use-package yapfify
   :defer t
...
)
```
Everything gets fed directly into use-package. Note that the layer name can be deduced from the filename. @CeleritasCelery suggested that having to specify the layer name in the first place was redundant.

```
 (defun python/pre-init-xcscope ()
  (spacemacs|use-package-add-hook xcscope
    :post-init
    (spacemacs/set-leader-keys-for-major-mode 'python-mode
      "gi" 'cscope/run-pycscope))
```
This pattern is common right now, pre-init (in the spacemacs sense) -> use-package-add-hook :post/pre-init/config.
```
(spacemacs|use-package-extend xcscope
    :post-init 
       (spacemacs/set-leader-keys-for-major-mode 'python-mode
      "gi" 'cscope/run-pycscope)))
```
That's it.

`use-package-extend` accepts pre/post-init/config. Actually, this example is a bit weird because adding a hook for post-init in use-package, seems pretty much the same as just running in spacemacs post-init. The mapping that I had in mind for use-package-extend is that pre-init and post-init will simply define spacemacs pre-init and post-init functions. pre-config and post-config will both define pre-init functions that add a pre/post config hook into use-package. 

If you only use the new macros for a package, run order is simple:

spacemacs|use-package-extend pre-init
spacemacs|use-package init
spacemacs|use-package-extend pre-init
package gets lazy loaded
spacemacs|use-package-extend pre-config
spacemacs|use-package config
spacemacs|use-package-extend pre-config

Of course, multiple layers can define pre/post-init/config with use-package-extend; as now the relative run order of things in the same category is unspecified. I did a quick skim through and it seems to me the vast majority of spacemacs layer functions can be converted to these macros without any problem, and they are not doing anything too complex. @syl20bnr if the interface seems reasonable to you, I can take a crack at the implementation, and I can also write some docs.

**Comment by quicknir** [comment]
Here's a tentative implementation of the first (simpler) macro:

```
  (defmacro spacemacs|use-package (package-name &rest args)
    (let* ((parent-dir (file-name-directory load-file-name))
           (layer-dir (file-name-nondirectory (directory-file-name (file-name-directory parent-dir)))))
      `(defun ,(intern (concat layer-dir "/init-" (symbol-name package-name))) ()
         (use-package ,package-name ,@args))))
```

**Comment by CeleritasCelery** [comment]
One thing that we can do to make this simpler is just use the variable `layer-name` (which gets set by `configuration-layer/make-layer` before loading the layer.) So it would become 
```common-lisp
(defmacro spacemacs|use-package (package-name &rest args)
  (declare (indent 1))
  `(defun ,(intern (concat layer-name "/init-" (symbol-name package-name))) ()
     (use-package ,package-name ,@args)))
```

and for the second 

```lisp
(defmacro spacemacs|extend-package (package-name &rest args)
  (declare (indent 1))
  `(defun ,(intern (concat layer-name "/pre-init-" (symbol-name package-name))) ()
     (spacemacs|use-package-add-hook ,package-name ,@args)))
```

**Comment by quicknir** [comment]
@CeleritasCelery Good point. I would still leave "use-package" in the name of the second macro to make it clear that this is still going through use-package. For the implementation of the second macro, that is definitely clever. I had envisioned however that for pre-init and post-init, it would just generate spacemacs pre-init and post-init functions, and not use the use-package-add-hook mechanism at all.

This may actually be important, now that I think of it. I think spacemacs has tightened up its ordering guarantees so that all pre-init are executed before *all* init, before *all* post-init. If the extend-package macro is just adding hooks into use-package, which is exechuted with init, that ordering guarantee is lost: e.g. if you have two packages, A and B, you would get pre-init A, init A, post init A, pre init B, etc. If you generate spacemacs pre-init and post-init functions and don't use use-package hooks for init, then you will get pre-init A/B (any order), init A/B (any order), etc. Since Sylbain added this recently and it seems like a much more useful ordering guarantee, we should probably try to maintain it.

**Comment by CeleritasCelery** [comment]
> I had envisioned however that for pre-init and post-init, it would just generate spacemacs pre-init and post-init functions, and not use the use-package-add-hook mechanism at all.

That will not work for the `:post-init` because If a package is not deferred, both the `:init` and `:config` will be called in `layer/init-package`, before `layer/post-init-package`, which means that the load order will now be 
- `:pre-init`
- `:init`
- `:pre-config`
- `:config`
- `:post-config`
- `:post-init`

Which is obviously not correct. And `:pre-init` is already in the `layer/pre-init-package` (Though it isn't evaluated till later). I don't think it would be prudent to make one of the properties behave different then all the rest. 

As far as the "*all* pre-init are executed before *all* init, before *all* post-init" guarantee, I can't speak to the reasoning behind that. But I if you are thinking in the context of a package loading, knowing that `:pre-init`, `:init`, and `:post-init` will be called together without any interleaving code seems like a much stronger and more useful guarantee then "all pre-inits called together" (which are unrelated to each other). I feel calling all of a packages code together would remove an extraneous factor that would've made debug more difficult.

**Comment by myrgy** [comment]
If we define rule only or one package, then theres no sense in that functions. At least we can use 2 of them - pre-init and post-init. Main reason is to have some "global" loading order. It allows to detect other packages and configure system based on that.

**Comment by CeleritasCelery** [comment]
> a) how many non deferred packages there are in spacemacs.

I ran an anecdotal test. Of my 279 Spacemacs packages, 220 were lazy loaded and 59 were not. So it not an insignificant number. 

> b) how many cases there are where it is important that post-init/pre-init run after/before other packages than the one they are configuring.

If you are requiring that your package runs after another package, just use `use-packages` `:after` keyword. You also have `with-eval-after-load`. Those should be the mechanisms used to control interpackage load order (and you should try to minimize that as much as possible).  If package A requires some preemption of package B, just create an `spacemacs|extend-use-package :pre-init` for that package B. Any scenario where your `:pre-init` can run **after** their `:pre-init` but must run **before** their `:init` (et al.) seems like bad design that could be handled in a cleaner and more explicit way.

**Comment by syl20bnr** [comment]
Running all the `pre-init` first is new (maybe one month old). It is required to properly setup the `use-package` hooks. If we run the `pre-init/init/post-init` together then we cannot _always_ set `use-package` hooks on a package before `use-package` is ran on it.

This is due to an important property of the layer system which is that it loads the package configurations in alphabetical order. This is deterministic and tangible so it is easier to reason about. This is an important design choice and this property dictates where we need to use `with-eval-after-load` (on a side note I would like that we don't use `:after` keyword from `use-package` because it is really not necessary, `with-eval-after-load` is already an explicit macro).

Another property to take into account is from Emacs. Setting a value or adding a hook does not require to load a package. This is what we do 99% of the time in pre-init. The rest of the time we have to check the load order and add proper code to ensure the proper loading of the configuration. All in all we maintain isolation thanks to the `pre-init` function as it won't be executed for a given package if no owner is declared for this package.

I like @quicknir's proposition for `spacemacs|use-package` macro macros to abstract the idiomatic construct of spacemacs `init` functions and `use-package`.
I don't like `spacemacs|use-package-extend` as its meaning is a bit off, let's just improve `spacemacs|use-package-add-hook` macro to encapsulate the spacemacs `pre-init` function.

**Comment by CeleritasCelery** [comment]
For the last little bit I have been using the following two functions when writing my personal layers
```lisp
(defmacro spacemacs|use-package (package-name &rest args)
  (declare (indent 1))
  (if (boundp 'layer-name)
      `(defun ,(intern (concat (symbol-name layer-name) "/init-" (symbol-name package-name))) ()
         (use-package ,package-name ,@args))
    (error "`spacemacs|use-package' must be called from a layers pacakages.el")))

(defmacro spacemacs|extend-package (package-name &rest args)
  (declare (indent 1))
  (if (boundp 'layer-name)
      `(defun ,(intern (concat (symbol-name layer-name) "/pre-init-" (symbol-name package-name))) ()
         (spacemacs|use-package-add-hook ,package-name ,@args))
    (error "`spacemacs|extend-package' must be called from a layers pacakges.el")))
```

I have found some issues with this methodology. 

First is a scenario that I have encountered more then once. Lets say you want to add a keybinding to a package. The place to put it would be after the package is loaded so we would add it to `:post-config`. However this will not work if the original call to use package does not have a `:config` section. Your hook will be completely ignored and there is no way of telling expect for your code not working. This means that you still have to use a non `use-package` construct like `with-eval-after-load` to add your code. 

This can to extrapolated to the scenario where the `use-package` call has no `:init` and no `:config` (`(use-package foo :defer t`). In which case no `use-package` hooks can be used at all.

For me, this means two things. First is that using the `use-package` hooks does not cover all common cases as I had supposed. Second is that using the hooks has its own unintuitive caveats that require you to look at the original `use-package` call to determine what will work and what won't.
