### ISSUE TITLE
[mu4e layer] Erratic behavior when enabling async operations

### ISSUE THREAD

**Issue by dschrempf** [syl20bnr/spacemacs#10262]
Hi,

I posted a bug report at djcb/mu#1182 today, because sending emails asynchronously did not work and emails just got lost.

I realized that this is because the layer variable `mu4e-enable-async-operations` just sets `send-mail-function` to `'async-smtpmail-send-it`.

However, when using `sendmail` together with `msmtp`. Emails get lost without a warning or an error (the `async-smtpmail` process just hangs).

**Comment by zzjjzzgggg** [comment]
Is there a way to resolve this issue?

**Comment by Miciah** [comment]
The issue has been reported multiple times upstream, both for mu and emacs-async:

* https://github.com/djcb/mu/issues/314
* https://github.com/jwiegley/emacs-async/issues/64
* https://github.com/djcb/mu/issues/870
* https://github.com/jwiegley/emacs-async/issues/74
* https://github.com/djcb/mu/issues/1182 (already mentioned in this report)

The mu author closed the first two issues against mu, saying that "this bug is really for asyc-smtpmail" (https://github.com/djcb/mu/issues/314#issuecomment-28586711), "for now I would simply not recommend using smtpmail-async" (https://github.com/djcb/mu/issues/314#issuecomment-28627419), and, "I don't think mu4e can do much about this" (https://github.com/djcb/mu/issues/870#issuecomment-231852775).

The emacs-async issues remain open, and the maintainer writes, "At the moment, this is just an experimental package to show proof of concept. I would recommend not using it in light of this problem" (https://github.com/jwiegley/emacs-async/issues/64#issuecomment-227523902).

This feature is disabled by default in Spacemacs.  Given that (1) the author of emacs-async characterizes the feature as "experimental" and "proof of concept", (2) both the mu and emacs-async authors recommend against its use, and (3) multiple people report lost E-mail due to this feature, I suggest we remove the option from Spacemacs.
