### ISSUE TITLE
Enriched face doesn't work in plain text

### ISSUE THREAD

**Issue by hrzboy** [syl20bnr/spacemacs#10314]
I have tested. It works in Emacs but not Spacemacs.

**Comment by CeleritasCelery** [comment]
More info?

**Comment by dudelson** [comment]
I also experienced this problem. I verified that calling `text-mode` on a correctly displayed enriched text buffer causes the text properties to no longer be displayed. My best guess is `font-lock-fontify-buffer` is being called at some point during the evaluation of the call to `text-mode`, but honestly I don't know. I did not look into the cause any further, but instead developed this work-around: Separate enriched text buffers from normal text buffers by using the `.txte` file extension for the former, and configure emacs to enable `enriched-mode` but not `text-mode` for these files. I did this by adding this line to my configuration:

      (setq auto-mode-alist (cons '("\\.txte" . 'enriched-mode) auto-mode-alist))

The major mode for enriched text buffers defaults to `fundamental-mode`. This does not seem like a loss in any way, since spacemacs doesn't have any special keybindings for `text-mode`.

Hopefully that helps.
