### ISSUE TITLE
Keyboard layout layer is missing a lot of rebindings

### ISSUE THREAD

**Issue by JonathanReeve** [syl20bnr/spacemacs#10358]
#### Description :octocat:
The Keyboard Layout layer doesn't work as universally as it could. 

#### Reproduction guide :beetle:
- Start Emacs
- Notice that `hnei` (or whatever you set you nav keys to be) don't work in some contexts

*Observed behaviour:* :eyes: :broken_heart:
- Navigation keys like `hnei` that are meant to replace `hjkl` don't actually replace `hjkl` in a lot of contexts. 

*Expected behaviour:* :heart: :smile:
- Navigation keys like `hnei` should work in more contexts 

Here's a running list of areas where the keyboard layout layer could improve. I'll try to keep this updated as I find more. 

 - `SPC w n` should navigate to the window below, but instead it's still mapped to `SPC w j`. Same for all of those commands (`evil-window-right`, etc)
 - in PDFView mode, provided by the PDF layer, remapped navigation keys don't work. Pressing `n` should scroll down in the PDF, but it looks for the next occurrence of a search item.  
 - in org mode, `gn` and `ge` (or whatever the remapped keys are) should be assigned to `org-forward-element` and `org-backward-element`, but they're still mapped to `gj` and `gk`, as in QWERTY.
 - All the navigations listed in `SPC N` seem still to be mapped to `hjkl`, for instance `evil-scroll-down`.
 - In Neotree help, `hjkl` keys are still listed instead of the remapped keys.
 - `which-key` seems to report the old `hjkl` keybindings instead of the new ones
 - Pressing `j` (remapped from `n`) should go to the next search match, but itstead it just navigates one line down. Strangely, `J` works for finding the previous search match, but `j` only navigates down. 

There are probably many more of these. There's probably a more procedural way of discovering them, too. (Grepping the code for `hjkl`?) 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c130014f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby csv shell-scripts javascript yaml html helm haskell
      (keyboard-layout :variables kl-layout 'colemak-hnei)
      (auto-completion :variables spacemacs-default-company-backends
                       '(company-files company-capf ein:company-backend))
      emacs-lisp google-calendar bibtex ipython-notebook
      (mu4e :variables mu4e-account-alist t)
      git markdown python pdf-tools org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      themes-megapack spell-checking syntax-checking vinegar)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD JSON LCMS2

#### Backtrace :paw_prints:
```

```

**Comment by Somelauw** [comment]
If it helps, in evil-org there's a variable `evil-org-movement-bindings` that makes it easy to remap keybindings in evil-org that follow the hjkl pattern.
You just need to set this before evil-org is loaded.

**Comment by Somelauw** [comment]
evil-collection is working on [a mechanismn to automatically translate key bindings](https://github.com/jojojames/evil-collection/pull/61). Perhaps that mechanismn can also be used in this layer.

**Comment by JonathanReeve** [comment]
I've just added a new one I've noticed. Any thoughts about this so far?

**Comment by JonathanReeve** [comment]
If someone fixes this for neotree, at the very least, that would be awesome. The keyboard layout layer has so much going on in it that I can't really understand it, myself.

**Comment by CharlesHD** [comment]
I'll add a look to neotree and your other requests. 

I'm doing PR each time I encounter such a case where keyboard-layout does not provides expecting remaps. But ultimately I do it only for packages that matters to me. 
Automatic remapping is a mess. Keyboard-layout is really pretty sane, but I guess it lacks a tutorial.

**Comment by JonathanReeve** [comment]
Awesome. Thanks for all your work. It's much appreciated. Neotree can be very frustrating to use with Colemak. It's not just the labeling of the keys in the hint section, but their behavior. On Colemak, it's that typing `K` doesn't take me to the parent directory, like one would expect, (just says that `K` is undefined`) but typing `?` for help, then with the help buffer open, then `K` works as expected. Also, `J` and `K` seem like they should be `N` and `E` on Colemak.

**Comment by SimonForest** [comment]
Hi ! Frustrated bépo user here.
I have investigated a bit to understand why keybindings for alternate layouts are not working properly. I have isolated two problems.

First, I think that there is a bug affecting `kl/correct-keys`: this functions takes as argument a number of bindings in the default layout that should be rebinded in the alternate layout. For example, to rebind the character movements in normal state, `(kl/correct-keys evil-normal-state-map "h" "j" "k" "l")` should do the work. Then, `kl/correct-keys` needs to retrieve the keys that represent "h" "j" "k" "l" in the alternate layout. For this purpose, it calls `kl//guess-rebindings`. But I have noticed that `kl//guess-rebindings` behaves in the other way around: `kl//guess-rebindings "h"` consider that "h" is a key in the alternate layout and finds to which keys it is equivalent in the default layout. A fix is given by an inverse to `kl//guess-rebindings`:
```emacs-lisp
(defun kl//guess-revrebindings (key)
  "Tries to guess the rebindings needed to correct the given
key."
  (let* ((key1 key)
         (prefix nil)
         (rebinding-map (cdr (assoc kl-layout kl--rebinding-maps))))
    ;; If key not existing as-is in the kl--rebinding-maps, try on last letter.
    (when (not (rassoc key1 rebinding-map))
      (setq key1 (substring key -1))
      (setq prefix (substring key 0 -1)))
    (let* ((key2 (car (rassoc key1 rebinding-map)))
           (bind1 (rassoc key1 rebinding-map))
           (bind2 (rassoc key2 rebinding-map)))
      (when prefix
        (defun kl//guess-prefixit (bind)
          `(,(concat prefix (car bind)) . ,(concat prefix (cdr bind))))
        (setq bind1 (kl//guess-prefixit bind1))
        (setq bind2 (kl//guess-prefixit bind2)))
      `(,bind1 ,bind2))))
```
and by correcting `kl/correct-keys`:
```emacs-lisp
(defun kl/correct-keys (map &rest keys)
  (declare (indent 1))
  (let* ((bindings (mapcan #'kl//guess-revrebindings keys))
         )
    (kl//remap-key-as map (remove-if #'null bindings))))
```
The second problem is due to the loading order and affects window bindings (among others I guess). The window bindings are made in `keyboard-layout/pre-initi-evil`:
```emacs-lisp
(defun keyboard-layout/pre-init-evil ()
...
  (kl|config evil-window
    :description
    "Remap `evil-window' bindings."
    :loader
    (with-eval-after-load 'evil-commands BODY)
    :common
    ;; FIXME: Not working
    (progn
      (kl/leader-correct-keys
        "wh"
        "wj"
        "wk"
        "wl"
        ;;
        "wH"
        "wJ"
        "wK"
        "wL")
      ))
...
)
```
As can be observed through debugging, when `kl/leader-correct-keys` is called to make the changes for the window keybinding for `spacemacs-default-map`, the initialization code for `spacemacs-default-map` (found in `keybindings.el` of the layer `spacemacs-base`) has not yet been called. So 1) this call to `kl/leader-correct-keys` rebinds empty bindings 2) anyway, these modifications are overwritten by the initialization code of `spacemacs-default-map` called later. I do not see an elegant solution for this since, as far as I am knowledgeable about spacemacs, there is no nice way to ask a code to execute after a layer has been completely initialized (`keybindings.el` included). However, putting the call to `kl/leader-correct-keys` in `dotspacemacs/user-config` should make it work.
