### ISSUE TITLE
ws-butler is unavailable

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#10436]
On Ubuntu 17.10 with Emacs 25 I get during install procedure

```
Package ws-butler is unavailable. Is the package name misspelled?
```

I chose the default option for each of the three questions.

**Comment by noelyang** [comment]
i have the same problem on macos
also tried ivy rather than helm, i got some other errors:

`Found 2 new package(s) to install...
--> refreshing package archive: gnu... [1/1]
--> installing package: org-plus-contrib@spacemacs-org... [1/2]
Package org-plus-contrib is unavailable. Is the package name misspelled?
--> installing package: paradox@spacemacs-ui... [2/2]
Package paradox is unavailable. Is the package name misspelled?
`

**Comment by seemsindie** [comment]
I am also getting this, what can i do to fix it?

**Comment by duianto** [comment]
This seems to be a duplicate of:
--> installing package: ws-butler@spacemacs-editing... [97/97] Package ws-butler is unavailable. Is the package name misspelled? #9256

The solution seems to be to start Emacs with the `--insecure` argument.

**Comment by duianto** [comment]
Another possible solution:

brownstyler said the following in the gitter chat:
>I am trying to get spacemacs working on a new windows computer running windows 10, I created the home environment variable, downloaded emacs and put it in the home environment directory. When I start emacs, it loads with the spacemacs theme, but it is unable to download any packages, it keeps spitting out "is X package misspelled?"
finally it gives an error about not being able to load the init.el file

source: https://gitter.im/syl20bnr/spacemacs?at=5aa03180888332ee3a0ea071

>ahh figured my problem out, I had to download gnutls and put it in the same folder as emacs.exe

source: https://gitter.im/syl20bnr/spacemacs?at=5aa03749c3c5f8b90d458da1

**Comment by qizwiz** [comment]
I was able to fix it by rolling back emacs as mentioned here:
