### ISSUE TITLE
Helm pops out instead of using mini buffer when there are 3 or more columns/rows

### ISSUE THREAD

**Issue by carloscheddar** [syl20bnr/spacemacs#10456]
#### Description :octocat:
Helm pops out instead of using mini buffer when there are 3 or more columns/rows

This started happening after updating packages. I've been able to reproduce it in both master and develop branches.

#### Reproduction guide :beetle:
- Start Emacs
- Set triple column layout `SPC w 3`
- Open any helm prompt `SPC f f`

*Observed behaviour:* :eyes: :broken_heart:
The helm buffer pops out.

*Expected behaviour:* :heart: :smile:
Helm should stay in the mini buffer regardless of the amount of columns/rows.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql helm emacs-lisp
     (osx :variables osx-use-option-as-meta nil)
     git html markdown ruby org javascript yaml themes-megapack csv syntax-checking
     (version-control :variables version-control-diff-side 'left))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by duianto** [comment]
The Helm package has changed the default behaviour, so that helm opens in a frame when there's more than two windows open.

This seems to be the commit, where the change occurred:
Use frame when more than two windows https://github.com/emacs-helm/helm/commit/221b6ad8351c9529a1755b830bd8c4fbf1838e90

Setting the new variable to `nil`, restores the previous behaviour.
```
(setq helm-use-frame-when-more-than-two-windows nil)
```

**Comment by carloscheddar** [comment]
Thanks! Adding that to my user-config fixes the issue but it was a pretty big change considering I was using the stable branch. Maybe there should be a dotspacemacs config option for this since I assume a lot of people will encounter this once they update helm.

**Comment by OrBaruk** [comment]
I just added the variable to helm layer to revert back the previous behavior

```
dotspacemacs-configuration-layers '(
   (helm :variables
             helm-use-frame-when-more-than-two-windows nil))
```

**Comment by kyren** [comment]
If you are using macos and a graphical emacs in fullscreen mode, this actually can result in an emacs *segfault* due to it handling opening new frames so poorly in fullscreen mode.

This is unrelated to spacemacs or even helm obviously, I just wanted to mention it because that was the symptom I was experiencing until I was able to figure out what was happening.

This may be dependent on the specific graphical emacs you're using, I'm not sure.  I'm using the `emacs` cask from homebrew, aka https://emacsformacosx.com/ for reference.

**Comment by duianto** [comment]
There's also some issues with the new helm frame, but I'm not sure if it's caused by a helm configuration in Spacemacs.

For example:
- With a single Emacs frame, and one window, that's showing the Spacemacs home buffer `SPC b h`
- After `SPC w s` splitting the window twice
- And opening the `SPC f f` helm find files buffer

#### Observed
Two new overlapping (the same x and y position) frames open.

The visible frame has `3` windows, the top two windows show the scratch buffer, and the bottom window shows the HELM Find Files buffer.

When the visible frame is mouse dragged away, then one can see that the second frame also has `3` windows. The top two windows show the scratch buffer, and the bottom window shows the spacemacs home buffer.

When the HELM Find Files buffer is selected, and `C-g` is pressed to cancel the helm buffer. Then only the helm find files frame closes. The 3rd frame remains open.

A similar thing happens, if instead of pressing `C-g`, when the HELM Find Files buffer is selected, if a file is opened, for example `.gitignore`. Then the file opens in the first window of the initial Emacs frame (expected, since the cursor was in that frame/window, when `SPC f f` was pressed), the frame with helm find files closes. The 3rd frame remains open.

#### Expected
A single frame should open, with only one window, showing the helm buffer.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey helm auto-completion emacs-lisp git org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by carloscheddar** [comment]
@OrBaruk that also worked for me and it's a cleaner approach in my opinion. Thanks for that.

**Comment by carloscheddar** [comment]
I also found that if you restart emacs and have it set to restore windows the helm pop out will have the same amount of windows rendering it unusable. 
![screen shot 2018-03-08 at 2 54 19 pm](https://user-images.githubusercontent.com/3360539/37170272-c5b84702-22e0-11e8-8c82-e51e342c604d.png)

**Comment by duianto** [comment]
The `helm-use-frame-when-more-than-two-windows` variable has been changed to `nil` by default, in this commit: https://github.com/emacs-helm/helm/commit/87dae7cbdda0695a9425ebf1880b19ce10741520
