### ISSUE TITLE
Deleting lines with <D> in visual selection not behaving the same as in Vim

### ISSUE THREAD

**Issue by tsoernes** [syl20bnr/spacemacs#10478]
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml javascript python latex bibtex helm auto-completion better-defaults emacs-lisp git markdown org spell-checking syntax-checking imenu-list
      (haskell :variables haskell-process-type 'stack-ghci)
      (python :variables python-enable-yapf-format-on-save t)
      (latex :variables latex-build-command "LatexMk")
      (python :variables python-sort-imports-on-save t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

*Observed behaviour:* :eyes: :broken_heart:

Given the buffer
```
one
two
```
Put the cursor ow the `o` in `one` and start a selection with v, then move to the end of the line with `<$>`, so that `one` is visually selected.
Now press `<D>` and both line one and two are deleted.

*Expected behaviour:* :heart: :smile:
This is different than vim, where only line one is deleted.

**Comment by duianto** [comment]
This is not caused by Spacemacs, since it happens with just Emacs and the Evil package.

You've already reported it on the evil package:
Deleting lines with <D> in visual selection not behaving the same as in Vim https://github.com/emacs-evil/evil/issues/968
And it's been labeled as a bug.

You should probably ask on that issue, if there has been any progress. If there are other issues that have higher priority, then maybe you could investigate what's causing the issue, and either fix it, or at least report your findings.

**Comment by smile13241324** [comment]
@tsoernes please update your issue following the official issue template you can access from Spacemacs with SPC h l. This contains important information about your installation.

I can then have a look into your issue.

**Comment by tsoernes** [comment]
@smile13241324 
Done, thanks! It happens on two different computers, even in scratch buffers, so I think perhaps the issue is not related to my setup.

**Comment by smile13241324** [comment]
@tsoernes I am sorry but as dubianto already wrote this is no Spacemacs issue but an issue of the `evil` package.

If you want to speed up their fix I think it would help if you would add a link to the official vim documentation to your evil bug ticket to prove that this is a vanilla vim behaviour you are requesting.

I also had a quick look into the evil package but I did not find an obvious reason for the error, it is somewhere buried in evil-commands.el#evil-delete.

So your issue is not related to Spacemacs and can therefore not be fixed here. Please refer to the evil project instead.

**Comment by tsoernes** [comment]
Okay. Appreciate that you took a look anyway.
