### ISSUE TITLE
Warning for "org-projectile": "Symbol's function definintion is void ... "

### ISSUE THREAD

**Issue by hersh-verthun** [syl20bnr/spacemacs#10483]
I just updated the Spacemacs packages and on restarting the following warning popped up.

> `Error (use-package): org-projectile/:config: Symbol's function definintion is void: org-projectile:per-repo`

How do I resolve this?

**Comment by tko** [comment]
As far as I can tell this is fixed in `develop` but if switching is not an option you may want to try adapting the changes from 6063466231ce5e209aacd2de612e53390a25c442 to master.

Duplicate of #10434 and [several closed](https://github.com/syl20bnr/spacemacs/issues?q=is%3Aissue+org-projectile%3Aper-repo+is%3Aclosed) issues.

**Comment by hersh-verthun** [comment]
@tko Thank you for replying. I am not very adept at merging changes using Git. If I were to exclude the projectile package, would this issue be fixed for me?

**Comment by tko** [comment]
If you exclude projectile I suspect all projectile related functionality (<kbd>SPC p</kbd>, maybe others) will stop working. Might be too much of functionality to lose. Excluding `org-projectile` could be sufficient, but haven't tried. (Just switched to develop myself, partially because of the per-repo error.)

**Comment by trcoffman** [comment]
I am experiencing this issue as well.

**Comment by qazwsxpawel** [comment]
Hi, 
for the time being, do you guys know if there maybe a way to silence this/an error ;)? 
Cheers!
