### ISSUE TITLE
proposal - external layer support

### ISSUE THREAD

**Issue by myrgy** [syl20bnr/spacemacs#10494]
Hello @syl20bnr,

currently it's possible to to specify package location.
I think it would be awesome to have same possibility for layers. It should make spacemacs more agile, since some users will have ability to develop there own layers and share it among other users in a convenient way. Spacemacs will behave a core.

https://github.com/syl20bnr/spacemacs/blob/develop/doc/LAYERS.org#packagesel

Thanks!

**Comment by ezchi** [comment]
Is this what you want?

`
   ;; If non-nil layers with lazy install support are lazy installed.
   ;; List of additional paths where to look for configuration layers.
   ;; Paths must have a trailing slash (i.e. `~/.mycontribs/')
   dotspacemacs-configuration-layer-path '()
`

**Comment by myrgy** [comment]
Not exacly, my idea is to provide github locations and allow spacemacs do pull it.
'''
;; A package recipe (some-package :location (recipe :fetcher github :repo "some/repo"))
'''

**Comment by gdkrmr** [comment]
great Idea, I would really love that!

**Comment by syl20bnr** [comment]
I'm opposed to it in this exact form, instead I would like to provide support for installing layers from PRs.

Why ?

One of the _raison d'être_ of Spacemacs is to break the package ecosystem scheme in order to provide both consistency and curation, i.e. good packages that behaves similarly.  

With an ever growing package ecosystem it becomes longer and harder to configure Emacs because there are a lot of options and all packages have their own ergonomics.

If I open the door to external layers then we will just replicate the same ecosystem just with one level of abstraction higher.

At some point we have to break this ecosystem to be able to design a beautiful system that can serve people directly.

While Spacemacs won't support officially these external layers, it is still possible to use them easily: this clone the git repository in your private layer directory.

But there is one kind of hybrid layers that are both external and official: the Pull Request layers. It would be awesome to provide facilities in Spacemacs to install them, test them, why not propose PR for this PR etc...

**Comment by myrgy** [comment]
hence closed. Thanks!

**Comment by gdkrmr** [comment]
so, if I am on the develop branch plus some changes I made and want to try out the changes someone else made, is there a way to do this without doing all the merging myself?

**Comment by fiveNinePlusR** [comment]
you can clone a repo, copy the folder for the layer to `~/.spacemacs.d/layers/` if you are using the .spacemacs.d method. otherwise you'd need to add the folder under your `~/.emacs.d/private/layers/` folder. both ways you need to add the layer to the .spacemacs file or the init.el file depending on your config.

**Comment by gdkrmr** [comment]
I wanted to try the `julia` layer (#10444), but this layer modifies other stuff outside the `layers` directory, I have some personal changes to the `ess` layer therefore simply cloning the branch is complicated for me, but I guess that there is no way around it.

**Comment by myrgy** [comment]
You can branch from develop, comit your changes and merge checkout pr and merge  it...
