### ISSUE TITLE
Newb question, can't scroll/navigate the help overlay. <SPC h k>

### ISSUE THREAD

**Issue by quangv** [syl20bnr/spacemacs#10509]
#### Description :octocat:
Newb question, but Google has let me down. Can't figure out how to scroll/page the help overlays?

![screenshot](https://i.stack.imgur.com/cDyeT.png)

There's 13 pages right? I can't seem to navigate/scroll to them.

I also posted the question on stackoverflow but so far no replies, so thought I'd try here. https://stackoverflow.com/questions/49287757/spacemacs-how-to-navigate-help-paging

#### Reproduction guide :beetle:
- Start Emacs
- `<SPC> h k`
- help overlay pops up on the bottom, showing the 1st page.
- I can't go to any other pages on the help overlay

*Observed behaviour:* :eyes: :broken_heart:
almost any thing I press closes the help overlay on the bottom.

*Expected behaviour:* :heart: :smile:
It should be possible, maybe even simple, to get to navigate to the other pages.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html javascript markdown clojure helm emacs-lisp neotree
      (keyboard-layout :variables kl-layout 'colemak-hnei)
      themes-megapack)
```
- System configuration features: JPEG SOUND GPM DBUS NOTIFY LIBSELINUX GNUTLS LIBXML2 ZLIB MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

Thanks for the help!

**Comment by tpearson1** [comment]
If you type C-h some information is displayed, showing which characters to type to display the next/previous page or other actions. You can type C-h n to display the next page.

**Comment by quangv** [comment]
I guess I can't go to the `If you type C-h some information is displayed` step... `C-h` is `Ctrl-h`? Sorry this might sound like dumb questions, but I've been trying everything...

I'm using Windows 10, and have switched my left Alt & Ctrl keys (to mimick OSX), however both `Ctrl+h` and `Alt+h` doesn't do anything but exits the dialog that popped up on the bottom...

**Comment by tpearson1** [comment]
Yes, `C-h` is`Ctrl-h`. I wasn't aware of your key remappings. Does `C-h`/`Alt-h` work in other programs in the guest box?

**Comment by smile13241324** [comment]
@quangv do you still have this problem? 

If you do, lets find out what `C-h` calls in your setup. First make `SPC h d k` then press `C-h` this should show you the function and binding that is called on your setup. Please post that information.
With this we can make sure that the right key events are triggered within emacs when you do `C-h`.

Also to rule out that your issue comes from `Colmac-bindings` please deactivate them for now and try again to press `C-h` => `Ctrl-h` in the menu opened by `SPC h k`, this should change the prompt to `Top level binding ....`, now you should be able to page once with `n`. Please verify that this works in your setup and post the results.

**Comment by quangv** [comment]
@smile13241324 Thanks for the help!

![63](https://user-images.githubusercontent.com/1171187/37939631-dc3096a6-3131-11e8-9e4f-a5db74f7cbfe.PNG)

🤔 maybe it **is** related to Colemak keybindings...
