### ISSUE TITLE
Readme.md Title Bars option issue

### ISSUE THREAD

**Issue by frankjonen** [syl20bnr/spacemacs#10571]
It's listed as: `--with-natural-title-bars` but needs  to be `--with-natural-title-bar` according to https://github.com/d12frosted/homebrew-emacs-plus which fails when used, causing a warning:

`Error: --with-natural-title-bars is unnecessary on --HEAD or --devel, try (setq default-frame-alist '((ns-transparent-titlebar . t) (ns-appearance . 'nil)))`

Going with just --HEAD installs and works, yet does nothing to give natural title bars.

This might be an issue with macOS High Sierra or with the formula maintainer. Maybe add a note to the readme to spare people some frustration.

**Comment by duianto** [comment]
The typo was fixed on the `develop` branch.

But the Emacs Plus repository has since removed the --natural-title-bar command.

Therefore the Spacemacs develop branch readme also removed it:
https://github.com/syl20bnr/spacemacs/blob/develop/README.md#macos

The Emacs Plus repository has instructions for duplicating that flags behavior:
https://github.com/d12frosted/homebrew-emacs-plus#upgrade-from-emacs-25x

The Spacemacs master branch readme will be updated when the next version is released
(I don't have any insight into when that is)
