### ISSUE TITLE
Pressing `C-x C-z` freezes Spacemacs

### ISSUE THREAD

**Issue by xyproto** [syl20bnr/spacemacs#10619]
#### Description :octocat:

I'm using the graphical version of spacemacs and am following the emacs tutorial (long time ViM user, checking what emacs might have to offer).

When I come to the part about suspending emacs , I press `C-x C-z` and emacs freezes completely. I can't find any keypress to bring it back to life.

#### Reproduction guide :beetle:
- Start Emacs (GUI, not `-nw`)
- Press `C-x C-z`

*Observed behaviour:* :eyes: :broken_heart:
- Everything freezes

*Expected behaviour:* :heart: :smile:
- To not freeze
- Alternatively, that the tutorial could include the correct keybinding to unfreeze emacs

Not sure what this from the template is supposed to be, but I'm on 64-bit Arch Linux, running the latest version of emacs and spacemacs:

```
(%LAST_KEYS%)
%SYSTEM_INFO%
```

#### Backtrace :paw_prints:

No backtrace.

**Comment by CeleritasCelery** [comment]
well since `C-x C-z` is bound to `suspend-frame` it sounds like that is the expected behavior. What are you expecting it to do? Have you tried `keyboard-quit` (`C-g`)?

**Comment by Miciah** [comment]
`C-x C-z` should be bound to `suspend-frame`.  If you are running Emacs in X, `suspend-frame` should invoke `iconify-or-deiconify-frame` instead of `suspend-emacs`.  If I press `C-x C-z`, it does indeed iconify the window, and my window manager lets me switch back to it.  If I invoke `suspend-emacs` directly, Emacs tells me, "Cannot suspend Emacs while an X GUI frame exists".  So the reported behavior does seem strange.

Is it possible that Emacs really is iconifying and your window manager does not handle iconification properly? What window manager are you using?

What happens if you run `iconify-or-deiconify-frame` or `suspend-emacs` directly? (Press `SPC SPC` and enter the command at the prompt.)

What is the value of the `suspend-hook` variable? (To check, `SPC h d v` and enter `suspend-hook` at the prompt.) For me, the value is `(x-win-suspend-error)` (which is the hook that checks whether Emacs is running in X and prints the "Cannot suspend Emacs while an X GUI frame exists" message that I see).

**Comment by xyproto** [comment]
I'm using Sway + Wayland. Sorry for forgetting to include this information. I will try to answer the rest of the questions later today.

**Comment by Miciah** [comment]
Are you using holy mode (traditional Emacs bindings)? You can try `C-h v` instead of `SPC h d v`.  (`M-m h d v` should also work; `M-m` generally works as an alternative to a leading `SPC` in Spacemacs bindings.)  Based on what you are seeing though, I'm already pretty sure `suspend-hook` is set to `(x-win-suspend-error)`.

It appears Emacs believes it is running in X, which means `C-x C-z` should iconify the window.

Are you using Emacs compiled with GTK+? If so, do you know what version? (`M-x version` should report this information.) There used to be a problem with iconifying GTK+ applications on Wayland, but it was fixed way back in GTK+ 3.15.7 ([commit](https://github.com/GNOME/gtk/commit/6886f479fee4c855823a2adcc84bf23e74b2305f)).

If you are not using GTK+, maybe there is a problem in whatever toolkit you are using.  Else it is probably a problem in Emacs or Wayland.

It is probably not a problem with Spacemacs specifically, but it is worth checking whether you see the problem with plain Emacs.  To run plain Emacs, without loading the init file (which is what loads Spacemacs), run `emacs -q`.

**Comment by xyproto** [comment]
Thanks for the response.

Yes, I'm apparently using holy mode (traditional Emacs bindings).

I am using: GNU Emacs 25.3.1

Emacs seems to be using gtk3:

```
ldd /usr/bin/emacs | grep -i gtk
        libgtk-3.so.0 => /usr/lib/libgtk-3.so.0 (0x00007f4d662ed000)
```

GTK3 is at version: 3.22.30

Both emacs and gtk3 are the standard official packages from the Arch Linux package repository.

I will try to provide the rest of the information you ask for as soon as possible.

It is likely that it's a problem with emacs + wayland and not specifically with spacemacs, but I guess the tutorial could skip the part about suspending emacs if the current windowmanager were using wayland? 

It could be a feature request for spacemacs, until the problem is fixed with emacs+wayland.

**Comment by sdwolfz** [comment]
Try installing emacs from source, maybe your problems go away if you use emacs 26:
```bash
git clone https://github.com/emacs-mirror/emacs.git ~/emacs
cd ~/emacs
git checkout emacs-26
./autogen.sh
# The `--program-transform-name` flag ensures you don't screw your current ctags package.
CFLAGS='-O2 -g3' ./configure --program-transform-name='s/^ctags$/ctags.emacs/'
make
sudo make install
```

**Comment by xyproto** [comment]
I will try building Emacs manually.

**Comment by xyproto** [comment]
I built emacs manually, but `GDK_BACKEND=1 ./emacs` does not launch the newly built executable under Sway/Wayland.

Oh well.
