### ISSUE TITLE
No changelog feature

### ISSUE THREAD

**Issue by CarlQLange** [syl20bnr/spacemacs#1067]
We should be able to show the changelog in the \*spacemacs\* buffer. This appears to be a blocker for the next release (according to https://github.com/syl20bnr/spacemacs/issues/1046#issuecomment-89477055)

**Comment by syl20bnr** [comment]
I agree but don't forget that we _have_ change log for all releases [here](https://github.com/syl20bnr/spacemacs/releases).
So for me it is not a high priority feature because:
- we have a release note as stated above
- the feature must be integrated with github release so it is not as trivial as it may look

My feeling about it is that, no matter where the release notes are, there will be always users that don't look at them.

Now the action to take for the future release:
- I will put an explicit message about the release and the breaking change inside the startup buffer with a link to the release page.
- this message will be backed by a light system of release message like the one we get when installing Magit 1.4.

For the full blown change log mechanism here what I want in the end:
- I write the change log in spacemacs.
- I have a command to export the change log to github which do:
  - bump release version
  - merge develop in master
  - create a maintenance branch
  - post the change log on github with the corresponding tag (the tag is the trigger for update notifications in spacemacs).

**Comment by StreakyCobra** [comment]
This is an old issue that is already solved in master. Closing it, but feel free to open a new one in any case :relaxed:
