### ISSUE TITLE
frames-only-mode and compile

### ISSUE THREAD

**Issue by weidtn** [syl20bnr/spacemacs#10694]
Not sure if this is the right place to ask:

Im pretty new to spacemacs. I use i3wm. I found the `frames-only-mode` and this is exactly what i need. magit opens its status in a new frame, just like I want it to. My problem is: When running my python scripts `, c c` the shell does not open a new frame. It's still in the same frame, under my code buffer.

**Comment by io12** [comment]
I can reproduce this.

**Comment by robertfw** [comment]
May be related to https://github.com/davidshepherd7/frames-only-mode/issues/28

**Comment by davidshepherd7** [comment]
Hi, maintainer of `frames-only-mode` here, do you know what `, c c` runs in vanilla emacs terms? I don't use spacemacs but `run-python` in plain emacs opens in a new frame and that sounds like the vanilla equivalent.

**Comment by io12** [comment]
`, c c` runs `spacemacs/python-execute-file`, which internally calls `compile` with the shell command to run the file.

**Comment by davidshepherd7** [comment]
Hmm, compile definitely works with vanilla emacs so it's probably a
configuration issue. I'll have a look at the spacemacs when I get a chance.

**Comment by davidshepherd7** [comment]
When I copy the definition of `spacemacs/python-execute-file` into my config and run it, it works as expected (opens a new frame for the compilation). I had a quick look around spacemacs to see if it is modifying any of the obvious settings but I can't find anything.

Some more questions which might help:

* What version of emacs are you using?
* Does the same thing happen when using similar spacemacs functions for other languages?
* Do you have any other packages installed that might be modifying either python compilation or frame settings? (can you reproduce it with only spacemacs and frames-only-mode installed?)
* What happens if you call `compile` manually (e.g. evaluate `(compile "true")`)? Does it do different things in different major modes?

**Comment by io12** [comment]
I just tried (for the first time since my initial comment), and I can't reproduce the bug anymore. Something must've fixed it since then.

@davidshepherd7 Thanks for `frames-only-mode` and trying to look into the issue.

@weidtn This issue seems fixed now so you can probably close it.
