### ISSUE TITLE
default spacemacs config has bound C-c C-w keybinding to eyebrowse rather than org-mode refile.

### ISSUE THREAD

**Issue by rnwolf** [syl20bnr/spacemacs#10729]
#### Description :octocat:
The default spacemacs config has bound C-c C-w to eyebrowse rather than org-mode refile.

I tried azzamsa suggestion in defun dotspacemacs/user-config () section of .spacemacs but it has not worked. 

In order to get org-refile working I excluded it with.

   dotspacemacs-excluded-packages '(eyebrowse)

#### Reproduction guide :beetle:
- Start Emacs
- open and org file.
- Navigate to heading
- press C-c Cw
- The command menu for eyebrowse opens up 
- Expected rather than helm navigation for org-refile

*Observed behaviour:* 

- The command menu for eyebrowse opens up 

*Expected behaviour:*

- helm navigation for org-refile

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html python helm emacs-lisp asciidoc git markdown org
      (org :variables org-enable-github-support t org-enable-reveal-js-support t)
      spell-checking yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by Compro-Prasad** [comment]
You can probably override it in your `dotspacemacs/user-config` too.

**Comment by bmag** [comment]
We already have `org-refile` under <kbd>, s r</kbd>, by the way. ("s" stands for "subtree")

**Comment by Miciah** [comment]
`C-c C-w` is the same key as `C-c C-W` (at least on Emacs with GTK; I'd be surprised if it weren't the case on other platforms), so setting `eyebrowse-keymap-prefix` to the latter makes no difference.

Ideally, I want to disable eyebrowse's binding entirely.  I tried setting `eyebrowse-keymap-prefix` to `nil` in `dotspacemacs/user-init`, but eyebrowse doesn't check for a `nil` value, so it gave the following error:
```
Error (use-package): eyebrowse/:init: Wrong type argument: arrayp, nil
Error (use-package): eyebrowse/:catch: Wrong type argument: arrayp, nil
```

Ultimately I found a solution based on some information on Stack Overflow ([Disabling minor mode key bindings](https://stackoverflow.com/questions/6480983/disabling-minor-mode-key-bindings)), namely  putting the following in `dotspacemacs/user-config`:
```emacs-lisp
(assq-delete-all 'eyebrowse-mode minor-mode-map-alist)
```
That removed the eyebrowse binding for me.

---

In my case, I want to be able to use `C-c C-w` in rcirc, which binds it to the `rcirc-cmd-whois`.  Because Spacemacs puts all eyebrowse functions under `SPC l w`, it seems unnecessary to keep its `C-c C-w` binding.  Since it interferes with multiple minor modes, would it be reasonable to disable it by default?

**Comment by bmag** [comment]
> `C-c C-w` is the same key as `C-c C-W`

Right, `C-c C-S-w` does what I meant.

> would it be reasonable to disable it by default?

We have to remember also users of emacs editing style, but I think even so it's reasonable to change the prefix to something less used. Disabling it entirely will be more complicated. without real advantages over just changing it. (the change will need to be mentioned in the documentation, of course)

**Comment by syl20bnr** [comment]
My suggestion is to use the corresponding key bindings defined in
Spacemacs via its leader keys.

It is virtually impossible to resolve conflicts between all the packages
as authors choose their key bindings as they want. Only the Spacemacs key
bindings can be reasonably set to limit conflicts to _almost_ null.

So better use the Spacemacs bindings, if a binding does not exist yet
then please open a PR and propose a binding that makes sense, ideally
under the major mode prefix.

I prefer we don't vanilla Emacs key bindings and package key bindings.

**Comment by alwyn** [comment]
> We already have `org-refile` under , s r, by the way. ("s" stands for "subtree")

When using Holy mode, how do I access the equivalent of the , leader key?

It sometimes feels, at least to me, like Holy users are treated like 2nd class citizens just because people assume most users use evil mode.

**Comment by Miciah** [comment]
> When using Holy mode, how do I access the equivalent of the , leader key?

I believe it's <kbd>M-m m</kbd>.

**Comment by alwyn** [comment]
> > When using Holy mode, how do I access the equivalent of the , leader key?
> 
> I believe it's M-m m.

Seems to be configured as C-M-m in the .spacemacs, but that doesn't seem to do anything except in org-mode where it seems to behave like M-Ret.

**Comment by alwyn** [comment]
Ok, it seems that C-M-m works on the develop branch, but not master.  I'll just use develop on all my machines, Thanks.

Sorry for the rant.
