### ISSUE TITLE
How to open powershell?

### ISSUE THREAD

**Issue by helson73** [syl20bnr/spacemacs#10749]
OS: windows 10 home
emacs: 25.3
spacemacs: full + ivy

I saw other threads said spc a s p can open powershell. But doesn't work for me.
error: spc a s is undefined. 

How can I open PS in spacemacs?

thanks.

BTW, powershell is included in PATH, and when I was using normal emacs, M-x powershell works fine for me. But why not for spacemacs?

**Comment by Compro-Prasad** [comment]
You can discuss these kind of problems first in https://gitter.im/syl20bnr/spacemacs . If you get no answer to your question then you can open an issue here.

**Comment by smile13241324** [comment]
First of all Compro-Prasad is right, normally it is good style to first ask in the chat before opening an issue when you have a question rather than a bug in the application.

However when you open an issue you should always use Spacemac's own issue template to provide necessary information for the maintainers to actually answer your question. You should have seen the notice when you try to create an issue by hand. As a reminder it is

>  If you are posting about a *bug* please close this issue and open a new one
using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs. If the
bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template)
You can delete this message to start typing.

So first start emacs, than press `SPC h I` or `M-m h I` enter your issue description in the template, than update your issue description with the filled in error template, notice that the template contains information about the config you are using.

As to your problem, when you are getting `SPC a s is undefined`, this means that the keybinding is not even bound. Therefore your issue has nothing to do with emacs not finding your powershell executable but your package is not properly configured. I guess that you have not installed the `windows-scripts` layer causing the respective `powershell-mode` package not being loaded and configured.

Spacemacs is not package centric, in contrast to vanilla emacs, but rather layer centric. This means you need to define layers in your dotfile you wish to load and install. The layers can be configured with simple variables and will trigger package configuration and installation for you.

If you don't know what I am talking yet, I strongly recommend to stop now and read the master [manual](http://spacemacs.org/doc/DOCUMENTATION.html#dotfile-configuration) or the develop [manual](http://develop.spacemacs.org/doc/DOCUMENTATION.html#dotfile-configuration).

**Comment by bmag** [comment]
@helson73 I can only guess that you didn't enable the `windows-scripts` layer, which owns the `powershell` package.

**Comment by helson73** [comment]
It works, thanks a lot!
Just add "windows-scripts" to dotspacemacs-configuration-layers, so simple!
