### ISSUE TITLE
neotree-open-file-in-system-application failed under Mac

### ISSUE THREAD

**Issue by htc502** [syl20bnr/spacemacs#10744]
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>
neotree-open-file-in-system-application does not work. it uses xdg-open instead of open under mac.

#### Reproduction guide :beetle:
- Start Emacs
- SPC f t
- navigate to a file and invoke neotree-open-file-in-system-application

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>
helm-M-x: Searching for program: No such file or directory, xdg-open

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>
should open a file with system setting application

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a3debe157)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html osx ruby search-engine perl5 markdown themes-megapack helm auto-completion colors emacs-lisp git
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control ess python r-pipeline-manager)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
Does `(setq neo-default-system-application "open")` in user-config help?

**Comment by bmag** [comment]
Putting "report upstream" label because this issue also affects upstream.

**Comment by htc502** [comment]
@bmag it did. Thanks. 
Would be great if spacemacs can do this automatically for me.

**Comment by Alexander-Miller** [comment]
Neotree hasn't seen commits in over a year, so I doubt reporting upstream will do any good, I went ahead and opened a PR for this at https://github.com/syl20bnr/spacemacs/pull/10757.

@htc502 You are on develop so I recommend you try the treemacs layer.

**Comment by bmag** [comment]
@Alexander-Miller yeah, I know, and was going to open a PR upstream and also fix it on our side until the PR is merged.

**Comment by Alexander-Miller** [comment]
At this point (and on the danger of tooting my own horn) I think neotree should be removed as the default. It is unmaintained and there are bugs, like the eyebrowse issues, that require a hard refactoring of its internals and cannot be fixed with simple monkey patches in spacemacs. And to the best of my knowledge there is nothing that it would offer over treemacs anyway.

Having choice is good of course, but right now we have a strict subset as the default, while there are other file tree implementations that do offer novel features: [sidebar.el](https://github.com/sebastiencs/sidebar.el) can also show buffers and mu4e mails, while [dired-sidebar](https://github.com/jojojames/dired-sidebar) gives you all the power of dired in your side window.

**Comment by sdwolfz** [comment]
I don't see any place where neotree is treated as a default. If you find any places in the documntation where neotree is given preferential treatment please flag them or submit a PR with a fix :smile_cat: . 

Also I agree that we should not encourage people to use an unmaintained package but transitioning from neotree to treemacs took some days of acomodation on my part... and transitioning from treemacs 1 to treemacs 2 took even more, until I got used to it at home enough to update packages at work (about 2 weeks) so I understand why people might want to keep using neotree.

**Comment by bmag** [comment]
I'm not particularly tied to neotree, but I'd like to see a comparison between it and any proposed replacement, if we are seriously going to pursue that direction.

> I don't see any place where neotree is treated as a default.

It's included in the default `spacemacs` distribution (see `layers/+distributions/spacemacs/layers.el`)

**Comment by sdwolfz** [comment]
@bmag ups, I just noticed that now when trying to install a fresh spacemacs :smile_cat:. You beat me to it by 1 minute.

**Comment by Alexander-Miller** [comment]
> but I'd like to see a comparison between it and any proposed replacement, if we are seriously going to pursue that direction.

I am not saying we should just replace it with treemacs, offering a choice à la helm vs ivy and see how things go from there is also an option. It's not about wanting my own stuff at the front, but about the spacemacs project taking on the burden of maintaning an abandoned package when there's already 1,8k issues and 170 PRs around. The limited resources there are could be used better than working around upstream bugs like this one.

As for a comparison, just going off my [feature list](https://github.com/Alexander-Miller/treemacs#detailed-feature-list) treemacs has, and neotree lacks, the following features:

 * a bunch of pretty icons
 * display of multiple filetrees
 * workspace persistence
 * frame-local buffers
 * tag view, including automated and manual goto-current-tag functionaliy
 * a mouse interface
 * git status highlighting (neotree's is very slow)
 * collapsing of single-child directories
 * a follow mode to always focus the current file
 * a filewatch mode (treemacs reacts to actual file system changes, neotree offers a periodic hard refresh)
 * integration with evil & projectile
 * good performace, whatever delay you see is mostly a *constant* cost for forking python/waiting for git
 * a butt-load of config options and small useful stuff like commands like `magit-status` and `helm-ag-project-root` being run based on the nearest path at point

>  and transitioning from treemacs 1 to treemacs 2 took even more

If you prefer the old single-tree mode you can now (mostly) use h & l  the same way as in treemacs v1 when you only have a single project in your workspace. I'll document this later, the change was only pushed as a trial due to popular demand, but I haven't heard any complaints about it yet.

**Comment by fiveNinePlusR** [comment]
I don't think neotree is very good software and has been painful to use from day one of my spacemacs use until treemacs was added to spacemacs. I would say that spacemacs should be the opinionated collection of packages and configurations and when there is a clear standout that does everything that the other does and more it should be the default. I vote for treemacs being the only filetree manager or at the very least the default option.

**Comment by sdwolfz** [comment]
There are still some features I would like to be ported from neotree to treemacs, and a few bugs/quirks that annoy me, I will open an issue about them upstream (so far @Alexander-Miller seemed to read my mind and released fixes right before I got a chance to open the issues themselves :sweat_smile:). 

But overall `treemacs` seems to be a better filetree (don't get me started on using `neotree` with multiple layouts and how the content of the buffer vanishes when typing in another winow).

**Comment by syl20bnr** [comment]
> I think neotree should be removed as the default

I was thinking about this even before reading this issue.

We can replace `neotree` by `treemacs` as the default file tree in the
dotfile template and in the general documentation (DOCUMENTATION.org).

treemacs can slowly absorb the useful additional feature of neotree.
