### ISSUE TITLE
evil mode C-a and C-x do not iterate and decrement (resp.)

### ISSUE THREAD

**Issue by eedahl** [syl20bnr/spacemacs#10786]
In vim when I hit C-a or C-x with the cursor on an integer the number iterates. This is useful for generating data with macros, etc., but does not seem to work in Spacemacs' evil mode.

**Comment by Compro-Prasad** [comment]
Please consult the gitter channel @eedahl for these discussions. You will probably get an answer there.

**Comment by eedahl** [comment]
Which "discussions"?

**Comment by eedahl** [comment]
This would ammount to something like this in the evil layer
````
(defun spacemacs-evil/init-evil-numbers ()
  (use-package evil-numbers
    :config
    (progn
      (spacemacs|define-transient-state evil-numbers
        :title "Evil Numbers Transient State"
        :doc "\n[_+_/_=_] increase number  [_-_] decrease  [0..9] prefix  [_q_] quit"
        :bindings
        ("+" evil-numbers/inc-at-pt)
        ("=" evil-numbers/inc-at-pt)
        ("-" evil-numbers/dec-at-pt)
        ("q" nil :exit t))
      (spacemacs/set-leader-keys
        "n+" 'spacemacs/evil-numbers-transient-state/evil-numbers/inc-at-pt
        "n=" 'spacemacs/evil-numbers-transient-state/evil-numbers/inc-at-pt
        "n-" 'spacemacs/evil-numbers-transient-state/evil-numbers/dec-at-pt)))
      (define-key evil-normal-state-map (kbd "C-a") 'evil-numbers/inc-at-pt) ; incr
      (define-key evil-normal-state-map (kbd "C-A") 'evil-numbers/dec-at-pt) ; decr)

**Comment by Compro-Prasad** [comment]
`SPC n +` and `SPC n -` is already too good for the purpose and you can use `C-a` for better purposes like jumping to the beginning of the line.

**Comment by eedahl** [comment]
That's what 0 does in evil mode

**Comment by Miciah** [comment]
Evil mode is amazingly and tantalizingly close to feeling exactly like Vim; this deviation from Vim is one of surprisingly few deviations that bothered me and disrupted my flow when I switched from Vim (and it still does bother me on occasion).

**Comment by eedahl** [comment]
Same @Miciah. The fix is very simple, and I don't believe this takes anything away from the emacs bindings as it is. If you want to fix this locally, add this under `dotspacemacs/user-config`:
```lisp
  (define-key evil-normal-state-map (kbd "C-a") 'evil-numbers/inc-at-pt)
  (define-key evil-normal-state-map (kbd "C-S-a") 'evil-numbers/dec-at-pt)
```
In my opinion people shouldn't have to do that, especially since `C-a` and `C-S-a` are adequately covered by other Evil commands and adding it would not interfere with anything fundamental (aside from places where the symmetry is already broken and Evil mode already has several great alternatives, like `C-a`).

You could of course say that if you want it this particular way you can just change it, but that is true for pretty much everything, and in my opinion if the Spacemacs evil layer is to deviate fundamentally from Vim in a certain aspect that someone hasn't found a use for counting shouldn't weigh particularly highly.

**Comment by sdwolfz** [comment]
I think `C-a` could be easily hijacked in normal mode since it's functionality is not that crucial, but `C-x` is a very important emacs prefix that could be used as an emergency fallback in case something wrong happens (`C-x C-f` to find file and `C-x C-c` to close emacs for example are some very useful emacs keys I've used in some occasions when everything broke apart). 

Personally I would like to leave these two alone and maybe improve the usability of the current `Evil Numbers Transient State`. I also felt that 3 key presses was way to much for this functionality the first time I encountered it but I sort of got used to it with time.

Some potential improvements we could do is:
- Allow `_` to do the same as `-` just as `=` does the same as `+` so when you forget you're still pressing `Shift` you don't get thrown out of the transient state.
- Switch the keybindings to be under `SPC` instead of `SPC n` so they are easyer to type (`SPC +` / `SPC -`).
- Enable some small subset of evil style navigation while inside the transient state (I think this was proposed before and dropped since it had to many edge cases).
- Document that you can use `.` to repeat the same command multiple times after you increased/decreased a number, so after you exit the transient state you can actually use normal vim motion to get to the next number you want to alter and `.` would get you into back in the transient state and repeat the last modification (with only one keystroke).
- Document how you can change the keybindings inside your `.spacemacs` so `C-+` and `C-x` do what you want, with a big warning sign that `C-x` could have unforeseen consequences.

**Comment by eedahl** [comment]
@sdwolfz I could certainly see someone object that `SPC` is already too cluttered to put this directly under `SPC`, but `C-a` and `C-S-a` would not have to deal with the same dilemma. At the same time, it would bring the Vim functionality naturally into the emacs setting where `X` does something and `S-X` frequently does the opposite.  You bring up some good points though. Your final point is a partial solution I'd find quite agreeable: A heads-up that this is a deviation from Vim bindings but that you can change it with
```lisp
  (define-key evil-normal-state-map (kbd "C-a") 'evil-numbers/inc-at-pt)
  (define-key evil-normal-state-map (kbd "C-S-a") 'evil-numbers/dec-at-pt)
```
or with a big warning
```lisp
```lisp
  (define-key evil-normal-state-map (kbd "C-a") 'evil-numbers/inc-at-pt)
  (define-key evil-normal-state-map (kbd "C-x") 'evil-numbers/dec-at-pt)
```
If that was the case it is unlikely that I would have made this issue to begin with.

**Comment by syl20bnr** [comment]
This can be documented in this section: https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#differences-between-vim-evil-and-spacemacs with the coded snippet for people to define `C-a` and `C-x` in their dotfile, with a warning.

We won't set them by default Spacemacs though,  we try to put key bindings behind leader keys only.

**Comment by eedahl** [comment]
Very well @syl20bnr. Do you want me to submit a PR, or? I'll have to read up on the  protocol but shouldn't be much of a problem. I'd like to suggest `C-S-a` as an alternative to `C-x` as well.

**Comment by sdwolfz** [comment]
@eedahl It would be awesome if you submitted a PR!

**Comment by Compro-Prasad** [comment]
Are we going for documentation or changing the keybinding itself?

**Comment by eedahl** [comment]
Docs. Any way to mention it under the layer on the web page?

**Comment by eedahl** [comment]
I have an exam coming up btw., so I'll get this done after that.

**Comment by syl20bnr** [comment]
> Any way to mention it under the layer on the web page?

Which layer ?

Good luck for the exams :-)
