### ISSUE TITLE
Please consider moving the project elsewhere. 

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#10800]
I will be closing my account here following the purchase by Microsoft as I’m sure many other will as well. 

https://monitor.gitlab.net/dashboard/db/github-importer?orgId=1

**Comment by syl20bnr** [comment]
No issue with Google though ? If they acquire GitLab it is still OK ?
:-)

**Comment by syl20bnr** [comment]
More seriously, we have lots of valuable information contained in the
issues. How good is the GL importer ?

**Comment by innerout** [comment]
![image](https://user-images.githubusercontent.com/11080614/40903265-834df256-67df-11e8-99c5-0d2fe02ef4b6.png)

**Comment by MatthewRock** [comment]
What would be the reason to move, what can the project gain from migrating to other platform?

**Comment by sdwolfz** [comment]
The peace of mind that your presence and participation on a platform during your free time is not endorsing a corporation historically known for leeching off of smaller players, anti-competitive behavior, and sabotage of open source technologies for their own personal gain at the detriment of consumers and the technology industry as a whole.

While I am not in a rush to push for a change but I have to say my spirit was broken yesterday when I read about this. I was expecting that GitHub would remain an independent player and their business would be an example for people that try to build a company and grow a community around it that benefits us all. But I was not aware that they were not able to make a profit out of it... so I'm not mad that they sold out... just disappointed that it did not work out in the end. I imagine a lot of GitHub employees feel the same, but they are required by corporate etiquette to keep a smile on their face and deny the disappointment, until they find an opportunistic window to get out.

While GitLab is a "quick fix" for this, you can't know if in 1-2 years we'll she same story unfolding again: *Oracle announcing that they agreed to purchase Gitlab, bla bla adventure, bla bla emposer, bla bla open source*.

The rear "fix" I see for this is self hosting a git server (GitLab/Gitea/Gerrit/a normal linux server with ssh access for example) but that requires extra costs (servers, backup, deployment) and mirroring it to Git Hub/Lab for availability. I do have some automated setup in place for Gitea servers that I built, but not open sourced yet since it was an internal project for a company, it still requires non trivial amount of work to maintain properly.

So while I understand why people are furious and want to push for a change, please let a few days/weeks pass so the dust settles and we can think clearly about the situation.

This is just a rant to take things off my chest... It's not meant to mean anything... just some random toughs that plagued my mind. Feel free to ignore.

**Comment by syl20bnr** [comment]
Yes let's see what happens, the public presentation seems to put in
front that GitHub will remain an open platform for service integration.

If we ever move away from GitHub it will be to a self-hosted solution.

**Comment by robbyoconnor** [comment]
GitLab Importer gets wonky if all users don't migrate to GitLab. I did a migration from GitHub to GitLab and it was a HUGE headache. 

Everyone needs to cool it with the FUD. Calm down and relax and see how things go.

**Comment by fiveNinePlusR** [comment]
I agree as well. Github is not going to become awful overnight. lets give microsoft a chance to be a good steward of the opensource community before migrating off.

**Comment by jbernsie** [comment]
I am currently thinking about if im going to be jumping off the github ship myself. I could see nothing short of major issues trying to move over a project with this kind of scale. It would be a massive job

**Comment by fiveNinePlusR** [comment]
> It would be a massive job

Though it would be like declaring email bankruptcy and starting fresh... a lot of those issues are not valid anymore anyway.

**Comment by robbyoconnor** [comment]
Jesus Christ -- everyone needs to calm down. You leaving GitHub is unlikely to do shit. Give Microsoft a chance. Moving a project of our scale would be a huge pain as I mentioned already. By leaving GitHub -- you lose the ability to participate in so many communities where it is simply not feasible to move easily.

**Comment by robbyoconnor** [comment]
Jesus Christ -- everyone needs to calm down. You leaving GitHub is unlikely to do anything. Give Microsoft a chance. Moving a project of our scale would be a huge pain as I mentioned already. By leaving GitHub -- you lose the ability to participate in so many communities where it is simply not feasible to move easily.

**Comment by usharf** [comment]
Sad to read some of the comments as they do show how lock-in works. Of course it’s going to be painful, and self hosting is probably a better option if possible, but regardless, you should expect reduced participation, at least from ethical contributors and participants in open source projects. 

I doubt it many new open source projects (and by open I mean free software, the confusion the non-movement and the movement was not accidental) will be opened in the future here, and this Weill indirectly have an aeefect. Same way source forge lost it standing with the free software community. 

Microsoft has been given many chances. That not even the issue. The issue is using a neutral platform where users are happy to participle. Using any Microsoft product is not that.

**Comment by usharf** [comment]
This might analysis paper by the GNOME project might be helpful. Mind you, GitHub was no even a candidate.

https://wiki.gnome.org/Initiatives/DevelopmentInfrastructure

**Comment by MatthewRock** [comment]
GitHub wasn't a candidate because it has never been an open source project. Paradoxally, I could see it becoming open source after MS's acquisition.

Ethical contributors should have left when (a) GitHub had sexual harassment controversy, or (b) when the project started using PayPal for donations. Since now we're stuck with unethical contributors that only care about providing the best experience to the users and shipping great code, I think we should be fine.

**Comment by usharf** [comment]
You made your point already couple of times. Got it. Your not adding any new information to support your point, other than it’s inconvenient and that Microsoft might surprise us all. 

I can t help you with the last one, but yes it is inconvenient  and yes, GitHub was tolerated. 

But Microsoft’s purchase changes everything  as far as the community that contributes to this project is concerned and it’ll lead to reduced participation, contribution and big reporting, forking of the project etc... 

I don’t even want to have an account with my personal data with Microsoft, nor use their  tools or platforms.

**Comment by braineo** [comment]
Already forgot GitLab `rm -rf` their database, found all backups failed and ran live on YouTube broadcasting how they recovered data while still losing comments and issues?

**Comment by bmag** [comment]
Folks, I know this is a discussion about possibly ditching Github, but don't turn it into a Github vs. Gitlab bashing contest. This is not the place for it. Please keep the discussion civil and to-the-point.

There certainly is fear that following Github's purchase by Microsoft, it will become a worse place for Spacemacs. However, that isn't certain, and for now nothing practical has changed. **I'd like to use this issue to discuss our options, their pros and cons, and what any migration entails.**

Remember that Spacemacs is purely based on volunteer effort, and it will take some time until any migration happens. I expect several migration stories of other projects to appear in the following weeks and months, and that could also affect our decision.

Here is a list of pros/cons I thought of so far:

Staying at Github:
Pros:
- large community, contains all of our contributors (for now)
- already set up - doesn't require migration
- website and git access is fast
- we also GH Pages for the spacemacs.org website, right? (don't remember)
- has gitter
- free (as in beer)

Cons:
- a portion of contributors will leave Github (reasonable assumption: usharf isn't the only one)
- fear that service becomes worse in the future
- closed-source nature is detested by a portion of contributors (this isn't the best wording)

Moving to Gitlab (as example, other hosts can be suggested as well):
Pros:
- opened-source nature is appreciated by a portion of contributors
- has CI built-in, instead of as integration with 3rd party? (heard it does) 
- free (as in beer)

Cons:
- need to port the code repo, all our issues, PRs (and keep them in merge-able
  state), the wiki, Github projects (which isn't used much)
- website not as fast as Github (when I last used it a few months ago)
- is git access as fast as Github?
- I'm anticipating many of our contributors won't bother opening a Gitlab profile

Questions:
- how does issue and PR management compare to Github?
- does it have a GH Pages equivalent for spacemacs.org?
- what to do with the gitter channel? (there's a few unofficial IRC channels,
  but I find the browser interface convenient - is there similar for IRC?)

Migrating to a self hosted solution:
Pros:
- ?

Cons:
- ?


A list of stuff we have and will need to migrate is also be useful. Please add more. Off the top of my hat:
- code repo (obviously)
- all issues (with labels, with Github links replaced?)
- all PRs (and keep them in merge-able state)
- the wiki
- Github projects (though not used much)
- spacemacs.org website
- the Spacemacs docker images?
- gitter
- CI (we use CircleCI now)

**Comment by sdwolfz** [comment]
A large factor of our "vendor lock in" and reason for why it's unwise to rush moving to another platform now it the huge number (1800+) of issues open that might or might not still be relevant due to all the changes we've done on develop since the last release, including the support for emacs 26+ features and removal of emacs 24 support. Right now, if we want to engage with people that opened/commented on those PRs, GitHub is the best platform to do so since they will receive notifications without loosing anyone that might be interested to give feedback or clarifications; if we migrate to any other platform we will loose that feedback loop.

This is something we should tackle regardless of the decision to move or not, maybe in the same spirit as the [Autumn Cleanup 2015](https://github.com/syl20bnr/spacemacs/wiki/Autumnal-Cleanup-2015) effort. The idea is to minimize the damage done in case we do decide to move.

I'm imagining something like the following:
- Set up some goals for the next Spacemacs release and focus to get it through.
- Clear up all the issues that are `Fixed in develop` right now.
- Iterate through all the remaining issues and see which ones are still relevant or not. We can have a `Spacemacs Summer Jam` event similar to the autumn cleanup.
- Merge is as many of the currently open PRs as we can.
- Prepare another Spacemacs release with all the cleanup work.

At this point we can asses the migration effort again and hopefully be in a situation where our choice does not impact the community to much, so we can focus on the technical side of it more.

Here are some points related to migrating to a self hosted Gitea instance:
Pros:
- I have an automated setup for it that I can open source and we can use it to easily install/upgrade/backup (some more work needed for this but I am going to do it anyway).
- It consumes really few resources so we can run on a cheap server.
- we have complete control over every aspect of the service
- no tracking/telemetry
- the Gitea community is amazing and really active
- it's relatively simple to extend in case we have bugs or need some extra functionality.  

Cons:
- Costs extra, depending on how many people use it at the same time we might need beefier machines.
- We have to be careful about people that will abuse out service (bandwith, registering 1000s of accounts, DDoS)
- Backups... we'll need to manage these together with the service.
- GDPR... while I don't fear the trolls and am willing to fight them till' the end of time, we have to be careful here not to upset legitimate users that actually care about their data (I'm one of them and I expect my GDPR enquiries to receive competent responses, it would be hypocritical of me if I did not treat others with the same respect I desire).
- Gitea is not very feature rich, so we'll be missing some functionality that Git Hub/Lab have.

**Comment by casouri** [comment]
I suggest to give MIcrosoft a chance. The company has changed since past few years.

**Comment by robbyoconnor** [comment]
> Already forgot GitLab `rm -rf` their database, found all backups failed and ran live on YouTube broadcasting how they recovered data while still losing comments and issues?

@braineo -- This could happen to _ANYONE_ and they learned from it. In fact, they had a Google doc during the whole incident which was publicly available explaining where they failed and how they could do better. So please, spare me. It's not the first time it happened, it's the first time it might have been publicly visible...This shows your maturity level.

**Comment by robbyoconnor** [comment]
@usharf your comments are quite frankly sad. I'm sorry you feel this way...please go ahead and delete your GitHub account...This whole issue comment thread is toxic.

**Comment by robbyoconnor** [comment]
> Already forgot GitLab `rm -rf` their database, found all backups failed and ran live on YouTube broadcasting how they recovered data while still losing comments and issues?

@braineo -- This could happen to _ANYONE_ and they learned from it. In fact, they had a Google doc during the whole incident which was publicly available explaining where they failed and how they could do better. It's not the first time it happened, it's the first time it might have been publicly visible...GitLab isn't perfect, nobody is. Mistakes happen.

**Comment by robbyoconnor** [comment]
I opted to delete some comments which were not constructive -- Keep in mind that GitLab uses GCP for their CI runners in some cases. Do you have an aversion to Google? Let's stop with the FUD and instead wait and see how things go...it's not even finalized yet. 

As I mentioned prior -- moving to GitLab gets wonky if the original issue creator isn't on GitLab, and Merge Requests become useless in the instance that the source branch doesn't exist on GitLab since the user hasn't forked Spacemacs yet...

**Comment by syl20bnr** [comment]
There is no practical reason to move Spacemacs repo for now. If I get enough demand I can consider to subscribe to a bronze tier in GitLab and open a mirror for people that don't want to log in GitHub. 

As an aside I'm not found of the all-in approach of GitLab to be honest, they are growing their services ala Amazon to vendor-lock their users. I much prefer the openness of GitHub regarding integration with the marketplace.

I'm more in favor of self-hosting but let's be realistic, this is not for tomorrow.

**Comment by seagle0128** [comment]
Didn't you want Oracle acquire github?  Joke, but wait and give a chance to MS...

**Comment by jaimehrubiks** [comment]
I'd also give a chance to MS. They've done many things wrong but in terms of open source related stuff they are doing a great job and making good moves IMO. Anyway, apart from people leaving Github for no reason other that knowing that MS bought it, there is not a single reason for moving to gitlab. And a self hosted git platform is also way too excessive for a project like this one.
