### ISSUE TITLE
Loading racket-mode breaks company in all buffers

### ISSUE THREAD

**Issue by trishume** [syl20bnr/spacemacs#1081]
On every commit after https://github.com/syl20bnr/spacemacs/commit/769d54da026d60cb3d9d3c33e213604c2b6a46 simply loading `racket-mode` and then typing enough to activate company in *any* buffer will cause company to go into an infinite error loop crash.

### Steps to reproduce:
- Checkout any commit after and including 769d54da026d60cb3d9d3c33e213604c2b6a46 with the `auto-completion` and `racket` layers enabled.
- Open any buffer with company completion, a random spacemacs elisp file will do.
- Type a few characters, company pops up.
- Split window, open a racket file, don't type anything in it.
- Switch back to other buffer, type a few characters. Emacs freezes and error messages flash in the mode line.

I have deleted my `elpa` directory and even gone into the `racket-mode` source and deleted every reference to company (remembering to delete the elc) and the problem still occurs. Worse, @cpaulik can't reproduce it.

Have I found a bug in my Emacs or is some super freaky stuff going on?

The error:
![screen shot 2015-04-06 at 5 06 30 pm](https://cloud.githubusercontent.com/assets/887610/7012451/55add896-dc7f-11e4-8739-b03376011ea8.png)

**Comment by syl20bnr** [comment]
@cpaulik and you have the same version of racket-mode ?
I'll try to reproduce it on my side tomorrow.

**Comment by cpaulik** [comment]
I had used the latest one as of yesterday `racket-mode 20150405.716`

**Comment by dgutov** [comment]
With recent enough Emacs (24.4+, IIRC), you should be able to `M-x toggle-debug-on-error`, and then see `M-x company-complete-common` result in a backtrace window.

**Comment by greghendershott** [comment]
I just stumbled across this while searching for something unrelated.

Although I don't immediately have any insight what is happening, please don't hesitate to let me know if there is something you think I should change on my end.

**Comment by greghendershott** [comment]
I reviewed my code. Maybe the way I'm using `(eval-after-load "company" ...)` is making it harder for spacemacs to do whatever it is doing? I'd followed the example of how Geiser mode handles this. 

Looking at company-mode again, now, it seems another approach is to enhance the return value of the standard completion-at-point-function with some extra properties. I'm not sure what disadvantages that might have (performance, maybe?), but it seems like a much more straightforward way to glue things together.

I think I'll try that out, because it seems like it would be cleaner anyway. And maybe it will help with this issue.

**Comment by greghendershott** [comment]
I just [pushed this to a topic branch](https://github.com/greghendershott/racket-mode/commit/7557b1cd7582be6fb9a9f5cbec601a7262f55a33).

@trishume if you're comfortable trying it that way, great and please let me know. Otherwise, I plan to merge this to master after some more testing, because it's so much cleaner. At which point you could try from MELPA.

**Comment by trishume** [comment]
@greghendershott note above that I already tried commenting out that entire section in my local copy (and confirming it wasn't being used) and it still crashed. Also nobody else can replicate it.

Given that @dgutov noted that your changes may be slower and not as nice it might not be a good idea.

I might give it some more testing soon with @dgutov's debugging tip (thanks!) but in the mean time I don't think there's any reason to take action on this yet. Just not enough information.

**Comment by trishume** [comment]
Actually I just tested again and I can no longer reproduce the issue. Probably some change to the spacemacs `auto-completion` layer or some other package fixed whatever weird thing was being triggered.

**Comment by hujianxin** [comment]
#4945

**Comment by hujianxin** [comment]
#4945 [Loading Racket will destroy company](https://github.com/syl20bnr/spacemacs/issues/4945)

**Comment by hujianxin** [comment]
Actually, I met this problem again... @greghendershott
