### ISSUE TITLE
more themes

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#10868]
I came across a very large theme package, what about adding this?
https://github.com/emacs-jp/replace-colorthemes

**Comment by afcady** [comment]
spacemacs needs *fewer* themes -- most of the themes are broken.  Are these also mostly broken?

**Comment by gdkrmr** [comment]
I can simply add them by adding them to the `   dotspacemacs-additional-packages` variable. I haven't tried them extensively, but you are right, a good selection of working themes would be great. I did this mostly because I wanted the `cobalt` theme which is not part of the `themes-megapack`.

**Comment by syl20bnr** [comment]
What can we consider a broken theme ?

**Comment by gdkrmr** [comment]
Some themes leave "residuals" behind, I don't have an example at hand, but this happens for example when the `themes-megapack` layer is installed.

**Comment by afcady** [comment]
I also consider the themes broken when they include any foreground/background color combinations that make text unreadable.  I've found at least one unreadable color combo somewhere in most themes I've tried.

**Comment by gdkrmr** [comment]
@afcady I agree, but themes are a bit more complex and I think that there is a large gray area between universally usable and completely unusable. What you describe often depends on the syntax highlighting of a specific mode, I imagine that such themes just work fine in other modes. I found that even with big and well designed themes highlighting of searches often is ugly or suboptimal in Spacemacs.

**Comment by afcady** [comment]
@gdkrmr Very true, there is a gray area.  Most of the unreadable text bugs occur in obscure places that understandably wouldn't be tested by the author (e.g. in some panel within `magit` which the author might not use).

But a surprising fact is that many themes in the megapack aren't in the gray area at all in my opinion.  The search highlighting is a good example because it is absolutely unacceptable to break the search function.  *I* certainly would never use such a theme.  It hurts the usefulness of the megapack layer itself, for me to have to search through and filter out such themes.
