### ISSUE TITLE
commit "Lazy load evil-surround" results "setq: Symbol’s value as variable is void: evil-surround-pairs-alist"

### ISSUE THREAD

**Issue by winsphinx** [syl20bnr/spacemacs#10895]
#### Description :octocat:
After `commit 03786aa94 Lazy load evil-surround`, when start Emacs, it reports `setq: Symbol’s value as variable is void: evil-surround-pairs-alist`.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:

*Expected behaviour:* :heart: :smile:

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d28990537)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm

**Comment by cormacc** [comment]
Yep - this appears to break org-mode.

**Comment by fiveNinePlusR** [comment]
all this lazy loading stuff is going to require people to refactor their dotfiles to include the proper `(with-eval-after-load 'packagename (setq ...))` unfortunately.

**Comment by Miciah** [comment]
The problem in this case though is that the org layer adds a hook on `org-mode-hook` to set `evil-surround-pairs-alist`.  Because the variable is buffer-local, using `with-eval-after-load` in the hook would not work properly.  And wrapping the `add-hook` with `with-eval-after-load` would mean the hook would not take effect in org-mode buffers opened before evil-surround got loaded.

**Comment by fiveNinePlusR** [comment]
can you do a `(defvar evil-surrount-alist ())` and run the code the same after that since it's a per buffer thing?

**Comment by Miciah** [comment]
You'd also want to do a `make-variable-buffer-local` on it.  However, if you did use a `defvar` in order to declare the variable before loading evil-surround and then set some value, then loading evil-surround after loading an org-mode buffer would overwrite `evil-surround-pairs-alist` with the default value, I think.  Worse, if `evil-surround-pairs-alist` were already buffer-local when evil-surround were loaded, evil-surround would only set the local buffer variable rather than a default value (if I understand `defcustom` correctly).

**Comment by summaminutiae** [comment]
This Works For Me(TM):  I tried putting (require 'evil-surround) at the top of dotspacemacs/user-config, sometime before I load orgmode stuff.  This has eliminated the evil-surround-pairs-alist error I was seeing and nothing else has exploded yet.

**Comment by syl20bnr** [comment]
Pushed a fix in develop: https://github.com/syl20bnr/spacemacs/commit/71da17e96

**Comment by sutram** [comment]
Seems to be no longer a problem. Thanks @syl20bnr
