### ISSUE TITLE
`projectile-find-other-file-other-window` opens new window instead of using existing window

### ISSUE THREAD

**Issue by skebanga** [syl20bnr/spacemacs#10923]
#### Description :octocat:
`projectile-find-other-file-other-window` opens new window instead of using existing window

Prior to pulling the head of develop, I could open a new vertically split window (`SPC w v`).
Executing `projectile-find-other-file-other-window` (`, g A`) would use that existing vertivally split window I just created.
Now I new window is created, using a horizontal split.

#### Reproduction guide :beetle:
- Start Emacs
- Open file in project
- Execute `projectile-find-other-file-other-window` (`, g A`)

*Observed behaviour:* :eyes: :broken_heart:
New window is created

*Expected behaviour:* :heart: :smile:
Existing window is used

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f1f8db002)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp html javascript go lua octave csv git markdown neotree
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
      imenu-list version-control
      (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
      (ranger :variables ranger-show-literal nil)
      python yaml lori-cpp
      (smart-tabs :variables smart-tabs-default-insinuations
                  '(c c++))
      protobuf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
Should be fixed by https://github.com/syl20bnr/spacemacs/commit/6b4a79d3981419526a84956161b0e639c1a3d5a9, please confirm.

`projectile-find-other-file-other-window` uses `find-file-other-window`, which consults `split-width-threshold` and `split-height-threshold` to decide if it can create a new window or use an existing one. When `purpose-mode` is enabled, the display logic is different and doesn't have this "bug" (it's more of a cumbersome built-in feature). We just had a bug that prevented Spacemacs from enabling `purpose-mode` anymore - fixed now.

Also, the repro guide is incomplete, I had to guess some extra steps:

- start Emacs
- maximize Emacs frame (i.e. `SPC T M`)
- open a .c/.h/.cpp file in a C/C++ project (for example `buffer.c` in Emacs' source code)
- split window vertically (`SPC w v`)
- Execute `projectile-find-other-file-other-window` (`, g A`)

When the frame was small, or when I had a horizontal split, then `, g A` would reuse the other window as expected.

**Comment by skebanga** [comment]
That worked perfectly, thanks!! 

Also, apologies for the poor repro guide.
