### ISSUE TITLE
OrgMode: Request for wrapper for `org-goto` that will automatically switch to insert mode

### ISSUE THREAD

**Issue by swaroopch** [syl20bnr/spacemacs#1094]
When I run `C-c C-j` in an org mode file, I have to remember to press `i` to switch to insert mode and *then* type the actual search term, otherwise the cursor just keeps bouncing around and I get confused and then realize that I'm in normal mode (not insert mode) and evil is interpreting what I'm typing as movement keys.

If anybody is willing to guide me, I can code this.

**Comment by swaroopch** [comment]
Just learned that `SPC s l` (helm-semantic) is a much better replacement for `C-c C-j`!

via @tuhdo 's https://tuhdo.github.io/helm-intro.html

**Comment by sindikat** [comment]
I propose to reopen this issue, regardless of how low-priority it is. Dropping into insert state immediately indeed makes `org-goto` more usable, but also `org-goto` is buggy in Spacemacs right now, as it maximizes the `*Org Help*` window, instead of having it as a tiny window below, with `*org-goto*` window taking most of the space.

**Comment by mroll-idiomatic** [comment]
I'd love to get this working. I've tried adding advice to `org-goto` like this:

```
(defadvice org-goto (around enter-insert-mode activate compile)
  ad-do-it
  (evil-insert-state))
```

But that doesn't seem to work.

**Comment by duianto** [comment]
@mroll-idiomatic This might be what your looking for:
https://emacs.stackexchange.com/questions/883/using-evil-mode-with-a-function-that-does-not-work-well-with-evil-mode

**Comment by mroll-idiomatic** [comment]
@duianto that is exactly what I was looking for. Thank you!
