### ISSUE TITLE
 Markdown: alt+enter (in holy mode) does not insert a new list item

### ISSUE THREAD

**Issue by aguadopd** [syl20bnr/spacemacs#10949]
#### Description :octocat:

Markdown: alt+enter (in holy mode) does not insert a new list item

#### Reproduction guide :beetle:

- Start Emacs with Markdown layer enabled

- Create a new Markdown (.md) file

- Start writing a list item (* text or - text or 1. text)

- Press M+Enter to insert a new list item easily. This executes `spacemacs-markdown-mode-map-prefix`.

*Observed behaviour:* :eyes: :broken_heart:

Error: `(wrong-type-argument commandp spacemacs-markdown-mode-map-prefix`

*Expected behaviour:* :heart: :smile:

A new list item is inserted. Just like when executing `markdown-insert-link`

(%LAST_KEYS%)

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((markdown :variables markdown-live-preview-engine 'vmd)
 helm auto-completion better-defaults emacs-lisp markdown org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

#### Backtrace :paw_prints:

```

Debugger entered--Lisp error: (wrong-type-argument commandp spacemacs-markdown-mode-map-prefix)
  call-interactively(spacemacs-markdown-mode-map-prefix)
  (let (orgtbl-mode) (call-interactively (or (key-binding [(meta return)]) (key-binding "\215") (quote orgtbl-error))))
  (if (org-at-table-p) (call-interactively (quote org-table-wrap-region)) (let (orgtbl-mode) (call-interactively (or (key-binding [(meta return)]) (key-binding "\215") (quote orgtbl-error)))))
  orgtbl-hijacker-command-106(1)
  funcall-interactively(orgtbl-hijacker-command-106 1)
  call-interactively(orgtbl-hijacker-command-106 nil nil)
  command-execute(orgtbl-hijacker-command-106)


```

**Comment by Miciah** [comment]
This issue is caused by an interaction between Markdown Mode and Orgtbl mode.  Markdown Mode binds <kbd>M-RET</kbd> to a key map. Orgtbl mode tries to hijack <kbd>M-RET</kbd> to do something Orgtbl-ish if point is in an Org table, and otherwise Orgtbl mode tries to honor the original binding for <kbd>M-RET</kbd>.  However, Orgtbl mode assumes that the original binding is a command, not a key map.

To work around the issue, you can disable Orgtbl mode in your current buffer:
```emacs-lisp
(orgtbl-mode -1)
```
You can also remove the hook that enables Orgtbl mode in Markdown Mode by adding the following to the `user-config` definition in your `.spacemacs` file:
```emacs-lisp
(spacemacs|use-package-add-hook markdown-mode
  :post-config
  (remove-hook 'markdown-mode-hook 'orgtbl-mode))
```
I believe this is really an upstream issue: Orgtbl is hijacking keys, in doing so, it harms an innocent victim, as often happens with hijackings.

**Comment by dato** [comment]
To be really sure, I commented out all the orgtbl bits in `layers/+lang/markdown/packages.el`. But it still doesn't work.

Now `M-RET` seems to be bound to `spacemacs-markdown-mode-map-prefix`, and I don't know how to disable it. But, in fact, it seems `M-RET` is a thing in every buffer, popping up the major mode's prefix actions—so it might be a good idea to leave it alone.

On the other hand, I'd be equally happy to have `C-RET` insert a new list item; I believe `M-RET` is just what used to do it in vanilla Emacs. So I added to my user-config:

```elisp
(spacemacs|use-package-add-hook markdown
 :post-config
 (evil-define-key 'insert markdown-mode-map (kbd "<C-return>") 'markdown-insert-list-item))
```

but it didn't seem to work; so I ended up with this working version (which I'm slightly less happy about, because it binds `C-RET` in normal mode too):

```elisp
(add-hook 'markdown-mode-hook
          (lambda ()
           (local-set-key (kbd "<C-return>") 'markdown-insert-list-item)))
```

**Comment by duianto** [comment]
Confirmed.

Pressing `M-RET` in a `markdown-mode` buffer, shows:
>let: Wrong type argument: commandp, spacemacs-markdown-mode-map-prefix

The help info for `SPC h d k` `M-RET` shows:
> <M-return> runs the command orgtbl-hijacker-command-106 (found in
> orgtbl-mode-map), which is an interactive Lisp function.
> 
> It is bound to <M-return>.
> 
> (orgtbl-hijacker-command-106 ARG)
> 
> In tables, run ‘org-table-wrap-region’.
> Outside of tables, run the binding of ‘<M-return>’ or ‘M-RET’.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ac1703200)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm markdown multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by aguadopd** [comment]
Still valid using develop branch, 0.300.0@26.3
