### ISSUE TITLE
Why is Spacemacs starting in the terminal?

### ISSUE THREAD

**Issue by cinjon** [syl20bnr/spacemacs#10998]
I just got a new computer and did a fresh install of Spacemacs. I am used to doing `emacs -nw <path/to/file>` in order to open spacemacs in the terminal and `emacs <path/to/file>` to open it in its own window. However, the latter is now doing the former. Is there a setting that I can change to fix this?

**Comment by bmag** [comment]
@cinjon what you describe is what happens when your system has only a terminal-based Emacs installed and without a graphical-based Emacs. That could happen if you installed `emacs-nox` package, for example ("nox" means without X11 support - which means a terminal-based Emacs).

It is most likely not a Spacemacs issue. You can verify it by running `emacs -Q -nw` and see if that also opens Emacs in the terminal.

The solution is to insall a graphical-based Emacs. Usually that would be the normal `emacs` package of your Linux distribution.

**Comment by bmag** [comment]
I guess the issue is resolved, or at least confirmed as not related to Spacemacs, so closing.
