### ISSUE TITLE
Emacs package development with spacemacs

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#11007]
What is the best work flow to develop an emacs package with spacemacs that is part of a layer and where the installation is handled by spacemacs?

**Comment by robbyoconnor** [comment]
What do you mean?

**Comment by robbyoconnor** [comment]
This is how you do a new layer: https://github.com/syl20bnr/spacemacs/pull/4958

**Comment by robbyoconnor** [comment]
http://develop.spacemacs.org/doc/LAYERS.html

**Comment by Compro-Prasad** [comment]
@gdkrmr Making an Emacs package means solving your own problem. If it is a general problem for others too then you can for sure distribute it on MELPA(its very easy to add there). Then you can create your own layer and include your own package or extend an existing layer in Spacemacs. Finally, make a PR to include the package in Spacemacs.

**Comment by gdkrmr** [comment]
I am not talking about a spacemacs layer, I am talking about the work flow of developing an emacs package using spacemacs. Especially if the package itself it is already installed by a layer.

**Comment by Compro-Prasad** [comment]
It is a bit of setup. You will have to clone the actual package, put it in a separate location, remove the package from spacemacs and update the load-path. This is easier if we use straight.el but spacemacs currently doesn't support it. We will need to wait for another year to see what happens with straight.el.

**Comment by gdkrmr** [comment]
ok, thanks. There is the `dotspacemacs-excluded-packages` variable, can I just add my package here, clone it somewhere and add the location to the `load-path`?

**Comment by gdkrmr** [comment]
@robbyoconnor if the package is already published on melpa, how would I make spacemacs prefer the local/quelpa/forked version?

**Comment by bmag** [comment]
@gdkrmr I think the best option for developing a package is using it as a local package. It'd be easier to help if you can tell us what package you are developing.

Pros:
- no need to commit changes for Spacemacs to pick them up (with quelpa you need to commit and update the package via regular update packages mechanism)
- faster to test changes because you don't need to reinstall the package every time you make a change

Cons:
- Spacemacs doesn't handle package dependencies automatically for local packages IIRC
- if the package has a complicated installation process or a complicated file structure, things get more complicated (with quelpa it shouldn't matter, as long as you use the correct recipe)

To develop the package as a local package, you can create a private layer and add the package you are developing as a local package. If it has dependencies on other packages, you need to add them to the new layer's list of packages (and also add init functions), since Spacemacs doesn't detect dependencies for local packages IIRC. If the dependencies are also part of Spacemacs, you could rely on the official configuration instead of adding them to the new layer.

If the package you are developing is part of Spacemacs, you will want to copy its init function to the new layer. That will make the new layer own the package instead of the original official layer, and override the original init function IIRC.

When testing your changes, you need to be aware if Spacemacs alters the package behavior in some way - that really depends on the package. If the package has automatic tests (e.g. `make test`) it is much easier.

**Comment by gdkrmr** [comment]
I am using the julia layer #10444, I simply copied the files to my `private layer` directory and disabled `ess` manually, everyting works fine without the changes below.

I have played around with this a little bit and was not really successful, I tried the following:

1. The .spacemacs comment for `dotspacemacs-additional-packages` tells to add this:
```
(dotspacemacs/layer
  ...
  dotspacemacs-additional-packages '((julia-repl :location "~/progs/julia/julia-repl/"))
  ...)
```
which does not work: `(void-function julia-repl-mode)`

2. changing the `package.el` of the julia layer:
```
(defconst julia-packages
  '(...
    (julia-repl :location ~/julia/julia-repl/")
    ...))
```
does not work either: `(void-function julia-repl-mode)`

3. The closest I have come is:
```
(dotspacemacs/layers
  ...
  excluded-packages '(julia-repl)
  ...)
(defun dotspacemacs/user-init
  (add-to-list 'load-path "~/progs/julia/julia-repl/")
  (require julia-repl))
```
which works, but the key bindings are not loaded from the julia layer.

**Comment by gdkrmr** [comment]
The spacemacs documentation tell you to put local packages in `/layer/local/package/`, I tried that and changed
```
(defconst julia-packages
  '(
    ...
    (julia-repl :location local)
    ...))
```
without success: `(void-function julia-repl-mode)`

**Comment by bmag** [comment]
Right, I forgot to add that local packages don't generate autoload files, so anything that is autoloaded will cause void-function or void-variable errors. The hard way to handle it is via the `:commands` parameter of use-package declarations. Another way is to manually generate autoload files (Emacs has built-in commands for that) and load them via `load` function in init, pre-init or config.el. Can't give you a detailed guide on this right now, but I think it's doable.

**Comment by gdkrmr** [comment]
@bmag thanks, I figured it out, I did the following changes in the `package.el` and cloned the `julia-repl` package into `/path/to/layers/julia/local/julia-repl/`:
```
(defconst
    ...
    (julia-repl :location local)
   ...)
(defun julia/init-julia-repl ()
    (use-package julia-repl
        ...
        :commands (julia-repl-mode julia-repl))
```
