### ISSUE TITLE
Develop: Yank path outputs nil

### ISSUE THREAD

**Issue by vbauerster** [syl20bnr/spacemacs#11065]
#### Description :octocat:
Yank path outputs nil

#### Reproduction guide :beetle:
- Start Emacs
- Open any file, then hit `SPC f y y`

*Observed behaviour:* :eyes: :broken_heart:
Although path has been copied, but status bar shows `nil`.

*Expected behaviour:* :heart: :smile:
Status bar suppose to show path just copied.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d9eecb760)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp org
      (git :variables git-magit-status-fullscreen t)
      (version-control :variables version-control-diff-side 'left)
      (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle auto-completion-enable-help-tooltip 'manual)
      (syntax-checking :variables syntax-checking-enable-by-default nil)
      (spell-checking :variables enable-flyspell-auto-completion t spell-checking-enable-by-default nil)
      html markdown neotree yaml python java javascript
      (rust :variables rust-format-on-save t)
      (go :variables go-tab-width 4 gofmt-command "goimports" go-use-gometalinter t godoc-at-point-function 'godoc-gogetdoc)
      protobuf docker themes-megapack dash semantic
      (ranger :variables ranger-show-preview t ranger-show-literal t)
      (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
      shell-scripts
      (c-c++ :variables c-c++-enable-clang-support t c-c++-enable-rtags-support t))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by mcg** [comment]
I can confirm this behavior. This hit me after updated `develop` recently.

**Comment by duianto** [comment]
@mcg Are you also on a mac?

The issue might be mac specific, because `SPC f y y` is working as expected for me in Windows 10 and Ubuntu.

For example in `.spacemacs`, both the minibuffer (status bar) and the clipboard shows:

In Windows 10 Version 1803:
`c:/Users/username/.spacemacs`

In Ubuntu 18.04.02:
`/home/otaje/.spacemacs`

On the latest `develop` branch with updated packages.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 23df5aa55)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm markdown multiple-cursors
            (org :variables org-enable-org-journal-support t)
            spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 23df5aa55)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

**Comment by mcg** [comment]
Yup on a Mac.

* OS: Darwin 10.14.5
* Emacs: 26.1
* Spacemacs: 15548734145b27d981192d1844d32911be9c2bbe
