### ISSUE TITLE
`fancy-battery` displays `No Battery` when laptop is plugged in and fully charged.

### ISSUE THREAD

**Issue by tariqk** [syl20bnr/spacemacs#11104]
#### Description :octocat:
`fancy-battery` displays `No Battery` when laptop is plugged in and fully charged. However, when unplugged, will show percentage of battery and time to fully discharge... until it hits 100% again, in which case we're back to `No Battery`.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC t m b`

*Observed behaviour:* :eyes: :broken_heart:
- When battery is less than 100%: as expected (i.e. it will show battery percentage & time to discharge)
- When battery is equal to 100%: `No Battery`.
- Checking `fancy-battery-last-status` via `SPC h d v` provides the following value:

```elisp
((76 . "on-line")
 (66 . "high")
 (98 . "")
 (112 . "100")
 (115 . "N/A")
 (109 . "N/A")
 (104 . "N/A")
 (116 . "N/A"))
```

`battery-status-function` is defined as `w32-battery-status`. Running `w32-battery-status` on `ielm` as a test provides the same alist as above.

Of note, is the cons cell `(76 . "on-line")`. This is what `w32-battery-status` provides when my laptop's power cable is plugged in. When it's not plugged in it looks something like this:

```elisp
((76 . "off-line")
 (66 . "high")
 (98 . "")
 (112 . "100")
 (115 . "N/A")
 (109 . "N/A")
 (104 . "N/A")
 (116 . "N/A"))
 ```

*Expected behaviour:* :heart: :smile:

I... actually don't know. Based on the definition used for the `fancy-battery` segment in `spaceline-segments.el`, this is what I see in the function `spaceline--fancy-battery-mode-line`:

```elisp
(defun spaceline--fancy-battery-mode-line ()
  "Assemble a mode line string for Fancy Battery Mode."
  (when fancy-battery-last-status
    (let* ((type (cdr (assq ?L fancy-battery-last-status)))
           (percentage (spaceline--fancy-battery-percentage))
           (time (spaceline--fancy-battery-time)))
      (cond
       ((string= "on-line" type) " No Battery")
       ((string= type "") " No Battery")
       (t (concat (if (string= "AC" type) " AC" "") percentage time))))))
```

Correct me if I'm wrong, but is this expected behavior? I was hoping for something like `Fully Charged` or `Running on AC`. Seeing it as `No Battery` confused me a little, making me think `fancy-battery` was not detecting my battery. I would prefer use `No Battery` that for when, say, my battery is removed from my laptop, or when the device I'm using literally does not have a battery (i.e. a desktop).

Honestly, I'm not exactly sure if this is a problem with `fancy-battery` itself, or this is specific to `w32-battery-status` being unusual. Do any other platforms have this inconsistency?

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c1bde286e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html helm auto-completion emacs-lisp git markdown neotree
      (org :variables org-enable-bootstrap-support t org-enable-reveal-js-support t)
      (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom shell-enable-smart-eshell t)
      windows-scripts spell-checking syntax-checking
      (erc :variables erc-server-list
           '(("chat.freenode.net" :ssl t :port 6697 :nick "[REDACTED]" :password "[REDACTED]")
             ("irc.gitter.im" :ssl t :port 6697 :nick "[REDACTED]" :password "[REDACTED]"))))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

#### Backtrace :paw_prints:

Not applicable, since this doesn't generate an error.

**Comment by Miciah** [comment]
The logic in `spaceline--fancy-battery-mode-line` was introduced into Spacemacs with https://github.com/syl20bnr/spacemacs/commit/db55268e793afd0d0dc306979a1ee0ba93e20d74 and was incorporated into upstream spaceline with https://github.com/TheBB/spaceline/commit/3990442b0b1f4f5975ae1bba3248fd89d4b5dff8.  So this is an upstream issue, but the code in question originated from Spacemacs.

`battery-status-function` is generally going to be set to one of six functions defined in upstream Emacs.  These functions return alists describing the current battery status.  Unfortunately, the values in these alists are loosely defined.  In particular, the possible values for `?L` ("AC line status (verbose)") are not defined.

As best I can tell, "No Battery" is supposed to mean "Running on AC".  I never noticed the issue because for me, `battery-status-function` is `battery-linux-sysfs`, which converts `?L` to one of "AC", "BAT", or "N/A", so `spaceline--fancy-battery-mode-line` always prints a percentage, no matter whether my system is running on battery or AC.

Because the set of possible values for `?L` is basically undefined and determined by `battery-status-function`, it would be simplest to use the value without trying to interpret it.  If it is desired to interpret it, I suggest changing the text "No Battery" to "AC" and changing `(string= "on-line" type)` to something like `(member type '("on-line" "AC" "connected"))` to account for the various values that these functions return that appear to mean "running on AC".

**Comment by tariqk** [comment]
I see. Okay, that makes sense. What this means is that the way out for this would be to amend the way `fancy-battery` is used, but outside from throwing out the entire default spaceline theme (which I'm pretty satisfied with) and using a `custom` spaceline theme, is there a way to _just_ amend the `fancy-battery` segment's logic?
