### ISSUE TITLE
Layer: rust: "cargo search" does not work

### ISSUE THREAD

**Issue by aurabindo** [syl20bnr/spacemacs#11110]
#### Description :octocat:
Rust mode: Cargo search does not work

#### Reproduction guide :beetle:
- Start Emacs
- Open a rust project
- Hit <Space> <M-C-S>
- Input any search term and hit enter

*Observed behaviour:* :eyes: :broken_heart:

Fails with message:
```
/home/aj/.cargo/bin/cargo search tokia --manifest-path /media/aj/Buffer/git-clones/gitlab/aurabindo/sinsight/Cargo.toml 
error: Found argument '--manifest-path' which wasn't expected, or isn't valid in this context

USAGE:
    cargo search [OPTIONS] [--] [query]...

For more information try --help
```
*Expected behaviour:* :heart: :smile:

Show search results

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1ae5463)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust helm auto-completion emacs-lisp git markdown neotree spell-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by jamartin9** [comment]
I believe this issue is upstream and in `cargo.el` due to the error message:
```
error: Found argument '--manifest-path' which wasn't expected, or isn't valid in this context
``` 
I have submitted a PR attempting to address it here: https://github.com/kwrooijen/cargo.el/pull/70

You can probably monkey patch it in your local layer/user config with the changes in the pr or invoke the cargo search command from outside of a project until the changes propagate.
