### ISSUE TITLE
Older Emacs Support

### ISSUE THREAD

**Issue by ylluminate** [syl20bnr/spacemacs#11124]
I maintain several servers with CentOS 7.x and they only have `emacs` 24.3.1. Is there a way to install and run with an older version of Spacemacs that supports these older installations?  I'd very much like to run these as-is without having to worry about `emacs` versions from box to box.  Same is true with some older Ubuntu servers I also maintain.  Spacemacs would be great to know I have a standard config in place on each one, but...

**Comment by ylluminarious** [comment]
I am interested in this as well. Spacemacs is a nice "standard" config; good for servers and foreign machines where one doesn't want to fiddle around with getting their own config to work. But since some systems like CentOS, old Ubuntu, etc. only have old Emacs versions, using the standard package manager is out of the question. The options then become compiling from source or using Linuxbrew.

Either of these is quite disruptive to the whole "standard" thing. Homebrew's per-user packages are pretty bad for a server, where root access is often necessary. Compiling from source is likewise flaky and unstable at best, especially when having to duplicate this per-machine. Is there a way to use an old Spacemacs version or turn on some kind of "legacy" mode to use older Emacs versions?

**Comment by delaanthonio** [comment]
I doubt running an older spacemacs would work. Sometimes upstream package updates cause Spacemacs to break. This happens occasionally in the master branch. 

While you may be able to use an older Spacemacs, you might have to disable broken packages. Otherwise, compiling Emacs from source is probably your best bet.

**Comment by ylluminarious** [comment]
@delaanthonio I'm a little confused... why would package updates break Spacemacs? Are you referring to dependencies? Wouldn't rolling back the whole repository solve such issues? Moreover, which packages might need to be disabled? Sorry, I'm not super familiar with the internals of Spacemacs hence my confusion.

**Comment by delaanthonio** [comment]
@ylluminate yes, I'm referring to package dependencies. As of now, most packages that Spacemacs depends on are hosted on Melpa. Spacemacs downloads these packages when it first loads up and when you add a new layer. 

You will always get the latest packages from Melpa regardless of which version of Spacemacs you're using. The issue is that sometimes the creators of these packages push out updates that rename a variable or function. These updates break the initialization code in spacemacs since it references an outdated variable or function name.

I can't tell you all the packages that you need to disable. That depends on the version of Spacemacs that you're using. However, you can look at the hotfixes in the master branch to see which packages have caused issues.

**Comment by ylluminarious** [comment]
@delaanthonio Hmm, what you describe is certainly a problem. It seems that [Spacemacs has already discussed this issue](https://github.com/syl20bnr/spacemacs/issues/2057) in the past. Nevertheless, there seems to be no consensus on how to work around this problem for the time being. [The most recent comment](https://github.com/syl20bnr/spacemacs/issues/2057#issuecomment-403746268) suggests that this can be worked around by using MELPA stable. Is this good advice? Or perhaps a better question, would it apply satisfactorily in the current situation?

**Comment by delaanthonio** [comment]
@ylluminarious That comment is using the pinned packages feature which is in Emacs 24.4+ according to this [blog post](https://www.lonecpluspluscoder.com/2014/11/25/using-elpa-pinned-packages-gnu-emacs-24-4/). I believing using pinned packages does fix the issue, but it won't for Emacs 24.3.

**Comment by ylluminarious** [comment]
@delaanthonio Hmm, well that's a shame. Not exactly sure what to do now.

**Comment by smile13241324** [comment]
Would be using a dockerized version of spacemacs a solution for your older servers?

There are some finished dockerized spacemacs solutions out there notably [spacemacs own docker distribution based on ubuntu](http://develop.spacemacs.org/layers/+distributions/spacemacs-docker/README.html) or there are also lots of unofficial solutions on docker hub like [mine based on manjaro](https://hub.docker.com/r/smile13241324/spacemacs-installerandconfig/).

You could build your own based on one of the existing solutions including your packages in the image and always mount a folder in your respective server.

**Comment by ylluminarious** [comment]
@smile13241324 That is a very interesting suggestion, I think it is worth trying out.

@ylluminate Any thoughts?

**Comment by ylluminate** [comment]
Very interesting @smile13241324 & @ylluminarious. The idea of having a very easy to install AND update emacs that essentially could happen during login (eg `oh-my-zsh` auto updating) could be the key here.  The problem for admins is we never want to do any kind of manual updates due to usually popping in for urgent or planned issues.  Last thing you want to do is to check everything like this and update your regular tools.  I could see this working...

**Comment by Miciah** [comment]
I'd like to throw https://flathub.org/ out as an option.

**Comment by ylluminarious** [comment]
@Miciah How does Flatpak compare to Linuxbrew with the aforementioned problems and so forth?

**Comment by Miciah** [comment]
I had not heard of Linuxbrew before you mentioned it here.  Looks like it is a system for building from source or installing pre-built binaries, right? Flatpak is more similar to Docker—indeed, both Flatpak and Docker use the OCI container image format, and both are based on Linux containers (kernel namespaces, cgroups, and seccomp).  What this means is that a Flatpak application bundles pre-built executables and any required libraries in a self-contained package that runs in an isolated, controlled environment.

**Comment by ylluminarious** [comment]
@Miciah Thanks, that makes a lot more sense now.
