### ISSUE TITLE
Can't contact other hosts, besides https://elpa.gnu.org/

### ISSUE THREAD

**Issue by ExarKunFan** [syl20bnr/spacemacs#11171]
#### Description :octocat:
Can't contact other hosts, besides https://elpa.gnu.org/
If i'll delete /elpa folder from .emacs.d, spacemacs will install all needed packages as usual, but after that i can't install any other package.

#### Reproduction guide :beetle:
- Start Emacs
- Execute "package-install"

*Observed behaviour:* :eyes: :broken_heart:
Can't see packages from other hosts, like melpa or orgmode

*Expected behaviour:* :heart: :smile:
All packages will be available

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(python helm
        (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
        (auto-completion :variables auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
        better-defaults emacs-lisp git org
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        spell-checking syntax-checking
        (wakatime :variables wakatime-api-key "f3e797ec-8c23-415b-adf1-130500e4c987" wakatime-python-path "/usr/local/bin/python3")
        shell-scripts)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by Compro-Prasad** [comment]
This has been a problem with me. I do a `package-refresh-contents` every time I need to install or checkout a package.

**Comment by smile13241324** [comment]
Is this problem also happening on develop for you?

**Comment by ExarKunFan** [comment]
I didn't tried develop

**Comment by smile13241324** [comment]
I am bit confused now, I have used `package-install` to install `company-lsp` from melpa with latest master and it worked like a charm. However the whole operation makes no sense, spacemacs is using a declarative packaging concept that means all packages are installed based on lists from layers or your dotfile.

All packages which are not part of these lists are removed automatically. So if you install these manually the packages will be removed with the next spacemacs boot.

If you want to manually install packages, you should definitely know what you are doing in this case, you need to add them to the list of additional packages in your dotfile instead. I.e.
```elisp
   ;; List of additional packages that will be installed without being
   ;; wrapped in a layer. If you need some configuration for these
   ;; packages, then consider creating a layer. You can also put the
   ;; configuration in `dotspacemacs/user-config'.
   ;; To use a local version of a package, use the `:location' property:
   ;; '(your-package :location "~/path/to/your-package/")
   ;; Also include the dependencies as they will not be resolved automatically.
   dotspacemacs-additional-packages '(Your-package-goes-here)
```

This will cause spacemacs to install your package during boot as well as update your package with spacemacs package update.

More information about this can be found in .emacs.d/doc/DOCUMENTATION.org.

@ExarKunFan Please install an officially supported emacs version, the latest would be 26.1. Then update your master to the latest version and try again. If this doesn't work try it again with develop.
If it's still not working please provide some more information about what you are doing exactly i.e. which packages you are not seeing in `package-install`, what are you trying to achieve...

PS: You can also play a bit around with timeouts for package sources in your dotfile. Below you can find my default settings as I am getting timeouts otherwise:
```elisp
   ;; If non-nil ELPA repositories are contacted via HTTPS whenever it's
   ;; possible. Set it to nil if you have no way to use HTTPS in your
   ;; environment, otherwise it is strongly recommended to let it set to t.
   ;; This variable has no effect if Emacs is launched with the parameter
   ;; `--insecure' which forces the value of this variable to nil.
   ;; (default t)
   dotspacemacs-elpa-https t

   ;; Maximum allowed time in seconds to contact an ELPA repository.
   ;; (default 5)
   dotspacemacs-elpa-timeout 60
```

**Comment by ExarKunFan** [comment]
Actually, i decided to configure Emacs for myself, and i don't have this issues, so this bug is not actual for me now.

**Comment by smile13241324** [comment]
Then please close this issue @ExarKunFan
