### ISSUE TITLE
Install `with-editor` as a default package?

### ISSUE THREAD

**Issue by CarlQLange** [syl20bnr/spacemacs#1118]
I'd love to use the `with-editor` package to be able to edit remote files in my local emacs without using `SPC f f`. This is my workflow:

1. Use the `vagrant` layer to bring a vagrant box up with `SPC V V`
2. SSH into that box using `vagrant-tramp-term` `SPC V t`
3. Now I want to edit a file on that box. If it were my local machine, I would use `emacsclient`. Apparently, the `with-editor` package solves this problem. http://melpa.org/#/with-editor

**Comment by syl20bnr** [comment]
Seems really handy, so the box does not need any emacs ?
You can try it by making a private layer, if it works well for you a PR is welcome. The layer name could be `remote` and we would put all the stuff related to tramp, ssh etc...

**Comment by zachlatta** [comment]
:+1:

**Comment by kvelicka** [comment]
Bump. @zachlatta have you made any progress on this?

**Comment by TheBB** [comment]
`with-editor` should be installed alongside magit. Is there any other configuration needed?

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
