### ISSUE TITLE
Why do we need "SPC b $" and "SPC b 0"

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1121]
In Evil, we can just press `G` and `gg`, which is much shorter. In Emac, we press `M-<` and `M->` which is also shorter. Should we remove it to avoid confusion?

**Comment by CarlQLange** [comment]
Yep, I agree, these seem pretty superfluous.

**Comment by cheezy64** [comment]
In the documentation it says that "gg" should always go to the thing at point regardless of major mode.  So, that's probably why they have this.  I'd personally prefer that they keep the G and gg behavior that you mentioned instead of that.  Maybe "go to thing at point" shoudl be remapped to "gt" or something

**Comment by syl20bnr** [comment]
Well spotted, I never used these key bindings, seems that it was just to put more stuff behind `SPC b` :-)
I have not problem with removing them.
