### ISSUE TITLE
C-x C-f doesn't working

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#11270]
When I start Emacs, type C-x C-f to open a file, The Emacs report the error:
![spacemacs bug](https://user-images.githubusercontent.com/20458813/45064092-76fb1a80-b0e4-11e8-86db-bb7bd191b0ee.PNG)

**Comment by wareslacker** [comment]
about this?
[#10882 ](https://github.com/syl20bnr/spacemacs/issues/10882)

**Comment by bmag** [comment]
Thank you, this was a regression caused at some point when we Helm's deferred loading has changed. Should be fixed by https://github.com/syl20bnr/spacemacs/commit/044237139b66058322e3824e7219f5741a0dd0ed, this new fix should be more resistant to regressions than the old one.

**Comment by bet4it** [comment]
@bmag This commit can certainly solve the problem, but I don't think the _Found work-around_ lable marked by @syl20bnr was do something like this. **This** commit was created just to solve **this** bug, like #9869.
There are two `spacemacs/helm-find-files` bindings in `helm/packages.el`:
https://github.com/syl20bnr/spacemacs/blob/044237139b66058322e3824e7219f5741a0dd0ed/layers/%2Bcompletion/helm/packages.el#L79-L86
One solved with `spacemacs||set-helm-key`,  which is some kinds of hook, I think @syl20bnr want to solve another with similar methods.

By the way, as what I have discussed in #10424, I don't want to hook and hook again with `helm` which is used so frequently by most people who enable `helm` layer. Just set it free, don't care the little start time it costs.

**Comment by bmag** [comment]
This commit solves the problem, and solves it the correct way. What "found work-around" label are you talking about?

`spacemacs||set-helm-key` is not a hook, it just wraps the function in a command that runs `(require 'helm)` before calling the function. There is no "hook and hook again", and besides a `require` call does nothing if the library is already loaded.

Since the discussions you link, @syl20bnr has made significant changes to how we defer packages, and we care more about start time now (and Helm's load time isn't small). Those discussions aren't as relevant as they used to be.

**Comment by bet4it** [comment]
The _found work-around_ label was marked in  #10882.


If we can solve this problem with only a `(require 'helm-files)`, why should we use `spacemacs||set-helm-key` to wrap it, which will `(require 'helm)` totally?
And why should we use all the other `spacemacs||set-helm-key`? We can just find the needed subset of `helm` and require it in the corresponding functions like your commit.

What @syl20bnr want to do in e24be2186adcbf1bafafd3ca2ea4e31d8919c760 was loading all the `helm` related functions in a unified method, requiring the whole `helm` even it only needs a subset of it.
So he changed all the `spacemacs/set-leader-keys` to `spacemacs||set-helm-key`, but he lost `global-set-key`, which causes this bug.
It's better to solve this bug in a similar way, rather than simply patch it somewhere.


I have explained in #10424 that, `(require 'helm-mode)` will only load some parts of `helm`, which won't cost too much time. And even if we make an effort to delay it, most people will still activate it after they start `spacemacs`, which doesn't like other modules. It's the start time displayed so important, so we can't increase it only 0.1 seconds or so?
