### ISSUE TITLE
Buffers aren't saved in non-default perspectives with helm-projectile-find

### ISSUE THREAD

**Issue by pcesar22** [syl20bnr/spacemacs#11282]
Using latest develop branch on Emacs 25.3 
Running Mac OS 10.13.3

Started trying out perspectives, can't use `<SPC> b p` and `<SPC> b n` to navigate buffers when on a non-default perspective.

To reproduce:

1. Go to root folder of any project and open any file.
2. Open a new layout `<SPC> l l` , type any new name to assign the new layout.
3. Find and open a new file using `<SPC> p f`
4. Try going back to the previous buffer using `<SPC> b p`

Step 4. doesn't work with the new perspective for me. It just stays in the current buffer or nothing happens. Sometimes it does return if there is a previous buffer, but I can never go back to the buffer opened in 3. 

The only way to add a buffer that "sticks" is to use `<SPC> l a` and add a buffer, which is annoying.

I'd really love to use persp-mode. Does any one have any workarounds or alternatives?

**Comment by Miciah** [comment]
The following should resolve this issue:
```emacs-lisp
(defun spacemacs//add-project-buffers-to-persp (persp _persp-hash)
  (if-let ((buffers (projectile-project-buffers)))
      (persp-add-buffer buffers persp nil nil)))

(add-hook 'persp-created-functions #'spacemacs//add-project-buffers-to-persp)
```
If it does not cause any problems, I can make a PR for the same.

**Comment by pcesar22** [comment]
Awesome, this seems to work nicely now! I don't see why this wasn't already like this. Thanks a ton!

A quick question if I may. How did you figure this out? Does this require deeper knowledge of how emacs works or could I trace this myself? Curious as to how you came up with this.

**Comment by Miciah** [comment]
> How did you figure this out? Does this require deeper knowledge of how emacs works or could I trace this myself?

Not so much about Emacs per se (the issue here revolves around the persp-mode and Projectile packages), and not _very_ deep knowledge (I've been using Spacemacs for under 2 years).  I did have prior knowledge of persp-mode, Projectile, and how Spacemacs configures the two in its spacemacs-layouts layer.  I have noticed general quirkiness with layouts before, but your concise statement of the issue here was helpful in identifying the specific problem—thanks for that! That helped me to realize that the issue was caused by the project's buffers not being added to the new layout (perspective). 

From there, I figured that resolving the problem would involve hooking into persp-mode when it creates a new perspective/layout, finding buffers that belonged to the project, and adding these to the perspective.  With some searching, I found the `persp-created-functions` variable to add the hook, the `projectile-project-buffers` function to get the relevant buffers, and the `persp-add-buffer` function to add them to the perspective.  With that and a little Emacs knowledge, it was straightforward to come up with a solution.

**Comment by pcesar22** [comment]
Awesome, thanks for the explanation! persp-mode is so useful, glad I was able to add it to my workflow.

**Comment by pcesar22** [comment]
Actually there is one issue that I found.. sorry!

This worked when I reloaded it from emacs, but when I restarted emacs, I started running into an issue in which I couldn't access M-x with SPC SPC anymore, having the message "SPC : is undefined". Uncommenting your code solves this issue.

Then I realized that, on start-up, I get the message: "projectile-project-buffers" is Null.

`Symbol’s function definition is void: projectile-project-buffers`

So I'm thinking it has to do with that variable only being set afterwards? I'm not sure. Do you have any idea on how to fix this?

**Comment by Miciah** [comment]
Does the following definition resolve the problem?
```emacs-lisp
(defun spacemacs//add-project-buffers-to-persp (persp _persp-hash)
  (if-let ((buffers (and (projectile-project-p)
                         (projectile-project-buffers))))
      (persp-add-buffer buffers persp nil nil)))
```

**Comment by pcesar22** [comment]
I no longer see the error message, but buffers are not saved anymore, for some reason.

Any other ideas?

**Comment by Miciah** [comment]
I have been using the suggested solution for a couple of months now, and it works well for me, so I have submitted a PR with the change: https://github.com/syl20bnr/spacemacs/pull/11642

**Comment by duianto** [comment]
The following PR is now on the `develop` branch:
spacemacs-layouts: Add project buffers to new persp #11642
