### ISSUE TITLE
spacemacs/search-ag with ivy does not work

### ISSUE THREAD

**Issue by melito00** [syl20bnr/spacemacs#11292]
#### Description
spacemacs/search-ag does not work with ivy.
It works fine when I select helm instead of ivy.

#### Reproduction guide
- Install spacemacs(git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d)
- Start Emacs
- Initial Setup(vim, standard, ivy)
- execuite spacemacs/search-ag (SPC s a f)
- Enter target directory (~/)

*Observed behaviour:*

show error on mini-buffer : (wrong-number-of-arguments (0 . 0) 1)

*Expected behaviour:*

Show prompt for entering search word.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace

```
Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 0) 1)
  counsel-more-chars(3)
  (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory counsel--git-grep-dir) (args (if (string-match-p " --
 " string) (let ((split ...)) (prog1 (car-safe ...) (setq string ...))) "")) (regex (counsel-unquote-regex-parens (setq ivy--old-r
e (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-com
mand spacemacs--counsel-search-cmd) nil))
  (lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory cou
nsel--git-grep-dir) (args (if (string-match-p " -- " string) (let (...) (prog1 ... ...)) "")) (regex (counsel-unquote-regex-parens
 (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//
counsel-async-command spacemacs--counsel-search-cmd) nil)))(--base-cmd-- "")
  apply((lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directo
ry counsel--git-grep-dir) (args (if (string-match-p " -- " string) (let (...) (prog1 ... ...)) "")) (regex (counsel-unquote-regex-
parens (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (space
macs//counsel-async-command spacemacs--counsel-search-cmd) nil))) --base-cmd-- "")
  (lambda (&rest --cl-rest--) "Grep in the current directory for STRING." (apply (quote (lambda (G0 string &optional _pred &rest _
unused) (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory counsel--git-grep-dir) (args ...) (regex ...))
(setq spacemacs--counsel-search-cmd (format ... args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil)
))) (quote --base-cmd--) --cl-rest--))("")
  ivy--reset-state([cl-struct-ivy-state "%-4d ag from [/home/kyamada/]: " (lambda (&rest --cl-rest--) "Grep in the current directo
ry for STRING." (apply (quote (lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (
let* (... ... ...) (setq spacemacs--counsel-search-cmd ...) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil))
)) (quote --base-cmd--) --cl-rest--)) nil nil "" counsel-git-grep-history nil (keymap (3 keymap (5 . spacemacs//counsel-edit)) (f3
 . spacemacs//counsel-save-in-buffer)) nil nil #<frame emacs@ubuntu1804-mac 0x12ffc30> #<window 3 on *spacemacs*> #<buffer *spacem
acs*> nil (1 ("o" counsel-git-grep-action "default") ("i" #[257 "\211;\203
```

**Comment by jason--liu** [comment]
I have the same problem.

**Comment by TienNguyenEH** [comment]
Same isssue :(

**Comment by duianto** [comment]
If everyone with the issue is on the master branch, then this might have been fixed on the develop branch. Because I don't get any errors when pressing `~`, `//` or navigating to a parent/child directory with `C-h` or `C-l` at the `SPC s f` prompt.

Tested in Ubuntu 18.04 and Windows 10 v1803.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ec01b4574)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(emacs-lisp git ivy markdown multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP


#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ec01b4574)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(autohotkey colors emacs-lisp git ivy markdown multiple-cursors org syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by wolfv6** [comment]
Me too.

#### Description :octocat:
All searches are broken:
- spacemacs/search-ag
- spacemacs/search-ack
- spacemacs/search-grep

#### Reproduction guide :beetle:
- Start Emacs
- Initiate search any of the above searches:
    SPC s f
- Enter directory:
    start from directory: [default/path] Ent

*Observed behaviour:* :eyes: :broken_heart:
- Message in mini buffer:
    Wrong number of arguments: (0 . 0), 1

*Expected behaviour:* :heart: :smile:
- Mini buffer asks for search term.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 8c0b8c344)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(rust html csv c-c++ git shell spell-checking ivy emacs-lisp markdown org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2
