### ISSUE TITLE
Active window number in doom mode-line is too dark

### ISSUE THREAD

**Issue by goofansu** [syl20bnr/spacemacs#11305]
#### Description :octocat:
Active window number in doom mode-line is too dark 

#### Reproduction guide :beetle:
- Start Emacs
- set `dotspacemacs-mode-line-theme '(doom :separator wave :separator-scale 1.5)`

*Observed behaviour:* :eyes: :broken_heart:
Active window number in doom mode-line is too dark, can not catch it easily.

*Expected behaviour:* :heart: :smile:
Should use a light color

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. be93ed91a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(auto-completion ivy better-defaults ibuffer neotree org react coffeescript csv elixir elm emacs-lisp erlang go html javascript markdown
                 (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rbenv ruby-test-runner 'rspec)
                 scheme shell-scripts typescript yaml osx git github version-control dash docker nginx systemd wakatime)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

<img width="1680" alt="screenshot of emacs 2018-9-10 10-35-35 am" src="https://user-images.githubusercontent.com/1143191/45273552-d93d8c00-b4e5-11e8-8e8b-4953e182e870.png">

**Comment by duianto** [comment]
A quick workaround is to add this to the `dotspacemacs/user-config` section of your `.spacemacs`:
```
    (set-face-attribute 'doom-modeline-bar nil :background "#51afef")
```

The color `#51afef` is defined as blue in the doom-one theme:
https://github.com/hlissner/emacs-doom-themes/blob/1aca1b45c8052f1a6452a63a3c0955d8d55864e7/themes/doom-one-theme.el#L56

And it's the same blue color that's used at the left end of the modeline, in the first 4 doom-modeline screenshots https://github.com/seagle0128/doom-modeline
(for some reason the 6 bottom screenshots of the window number and evil states, have a slightly different blue color `#56B0ED`)

#### Should the inactive window number segment color also be changed?
Maybe the inactive window number segments background color also should be changed from the current bright orange:  `#dc752f`, to a darker color?

A possible issue could occur when only two windows are open, then two bright window number segment background colors might make it unclear which window is the active one.

#### Where should the fix be applied?
Should this be fixed in the Spacemacs theme https://github.com/nashamri/spacemacs-theme ?

Or by adding:
```
:config
(progn
    (set-face-attribute 'doom-modeline-bar nil :background "#51afef"))
```
(and possibly a new color to the `doom-modeline-inactive-bar` face as well)
to the end of the function: https://github.com/syl20bnr/spacemacs/blob/ba933169392cee174ad0794fca73ba83a31bc4d9/layers/%2Bspacemacs/spacemacs-modeline/packages.el#L35


#### Cause
The active window number segment has a dark background because the doom-modeline theme gets the colors by:
- First: inheriting from the `doom-modeline-bar` face, which in turn inherits from the `highlight` face, which in Spacemacs has these colors:
Foreground: `#b2b2b2`
Background: `#444155`

- Second: it overwrites the inherited foreground color `#b2b2b2` with the background color of the `default` face, which in Spacemacs is define as:
Background: `#292b2e`

This results in the active window number segment having these colors: 
Foreground: `#292b2e`
Background: `#444155` 

The inactive window number segment gets the `doom-modeline-inactive-bar` face, which inherits the inverse of the `warning` face, which only has one face attribute:
Foreground: `#dc752f`

A face that's inversed seems to flip the foreground and background colors, which means that the inactive window number segment gets the background color `#dc752f`.

source:
https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline.el#L959

**Comment by duianto** [comment]
The `doom-modeline` package recently updated the window and workspace number faces.
The background and foreground colors of both sections now match the rest of the modeline in Spacemacs.

![emacs_2018-10-05_14-55-59](https://user-images.githubusercontent.com/13420573/46543385-fdac3e80-c8c0-11e8-9488-987a8891d921.png)

**Comment by goofansu** [comment]
@duianto Thanks, that's great. Closed.
