### ISSUE TITLE
How to leverage the Directory location already saved in Helm Bookmark to quickly populate the Helm Basic Save mini buffer?

### ISSUE THREAD

**Issue by MilooHub** [syl20bnr/spacemacs#11335]
**Problem Background:**
For certain workflow, one might need to first compose some text in the scratch buffer, then later need to save it by pressing SPC-f-s to save it as a file on the local file system for persistent usage.

Then Helm Basic Save Buffer would appear at the bottom, starting from there,  normal operation would be to input the Destination Directory path one level by one level, with a few keystrokes followed by TAB to autocomplete, and so forth. Until the complete Destination Directory is displayed on path navigation bar of Helm Basic Save Buffer. Well, this could get the job done...

But it is too time-consuming & tedious if the Destination Directory has a long path, say Directory root/sub-directory-1/sub-directory-2/sub-directory-3/sub-directory-4/sub-directory-5/sub-directory-6...

**Expected Operation:**
Wouldn't that be much nicer, when Helm Basic Save mini buffer appears, instead of inputting directory name one level by one level, one could just 
1. Summon Helm Bookmarks(or even Helm Locate) user interface, then one could just pick a frequently accessed Directory(Helm Bookmarks scenario) or any needed Directory at the moment(Helm Locate scenario) for the buffer to save. 
2. Select the Directory to use and confirm by pressing Enter key. 
3. then the Destination Directory selected above would be used to automatically populate the path navigation bar in Helm Basic Save mini buffer.( then user could just input the file name and press Enter to get file saving operation done!)

This would be a much much faster and smoother Buffer/File Saving operation workflow!!

**One picture worth a thousand words**
![screenshot on selecting directory for helm basic save mini buffer using helm bookmarks](https://user-images.githubusercontent.com/22869482/45602973-ae10ea80-ba59-11e8-8477-83d0dce277ec.jpg)

**Question**
Is the expected operation above possible in Spacemacs?

- Use Helm Bookmark to quickly populate the Helm Basic Save mini buffer's navigation path;
- Use Helm Locate to quickly populate the Helm Basic Save mini buffer's navigation path;

if so, how to achieve it? (if it involves writing elisp scripting, please enlighten with source code)

**Comment by Miciah** [comment]
I think it would involve writing a new Helm command to get the behavior you describe.  However, would using a recursive search suit your needs? Next time you're in a Helm session, try entering `root/..sub-directory-6` and pressing <kbd>C-l</kbd>.  Alternatively, frequently used paths should be in the input history, so you might try pressing <kbd>M-p</kbd> (repeat as necessary) in a Helm session to go backwards through history items to find the item that you want.

**Comment by MilooHub** [comment]
@Miciah thanks for the quick response.

- as for `M-p` & `M-n` trick, wow, I did not know this trick, it is definitely a neat trick for certain scenario working with helm buffer for quick recent path input history toggle!
- as for `C-l`, I tried it in Helm basic save mini buffer, but nothing happens. could you tell me which Emacs command this keybinding is supposed to trigger, so I could look it up later.
- as for using a recursive search, I did not know this notion before and feel like this might be what I need. Could you provide a bit more of your insight on this recursive searching. (I don't know if recursive editing is the same thing of what you are talking about. )
- Another thing that has just occurred to me, do you think Helm Projectile may be another option I could use to achieve what I want, in that to just to a frequently used project folder and use it as new working directory, then trigger Save Buffer, and hope the working directory of Projectile Project will be populated into path navigation area as I want.(I have not used Helm projectile, so just a thought now)

**Comment by Miciah** [comment]
> as for `M-p` & `M-n` trick, wow, I did not know this trick, it is definitely a neat trick for certain scenario working with helm buffer for quick recent path input history toggle!

You might also like <kbd>C-c C-l</kbd>, which gives you a new Helm session with history for your current Helm session.  (Recursive Helm!)

> as  for `C-l`, I tried it in Helm basic save mini buffer, but nothing happens. could you tell me which Emacs command this keybinding is supposed to trigger, so I could look it up later.

<kbd>C-l</kbd> is bound to `helm-execute-persistent-action`; Spacemacs binds the same command to <kbd>TAB</kbd>, so you can alternatively use that key.  (In case you are curious, which-key will show these key bindings if you press <kbd>C-c</kbd>, then wait a moment for which-key to appear, then press <kbd>C-h u</kbd> for `undo-key` to get back to the root map; from here, you can read the listing at the bottom of the screen, or use <kbd>C-h h</kbd> to get a new Helm session that will let you scroll or search through key bindings.)

> as for using a recursive search, I did not know this notion before and feel like this might be what I need. Could you provide a bit more of your insight on this recursive searching. (I don't know if recursive editing is the same thing of what you are talking about. )

My suggestion of using `root/..sub-directory-6` <kbd>C-l</kbd> is using recursive search.  This feature is documented, but Helm's documentation is a little obscure: use <kbd>SPC f f</kbd> to start a Helm Find Files session, then press <kbd>C-c ?</kbd> to open the Helm Help buffer, and then type <kbd>C-s</kbd> `Recursive completion` <kbd>C-s</kbd> <kbd>RET</kbd> to find the specific section.  In the Helm Help buffer, use standard Emacs navigation keys: <kbd>C-n</kbd>/<kbd>C-p</kbd> for next/previous line, <kbd>C-v</kbd>/<kbd>M-v</kbd> for next/previous page, etc.  (Perhaps I should make a to-do item about evilifying Helm Help.)  Alternatively, I found a Git issue in which the author describes usage and provides screenshots: https://github.com/emacs-helm/helm/issues/1635#issuecomment-257135818

> Another thing that has just occurred to me, do you think Helm Projectile may be another option I could use to achieve what I want, in that to just to a frequently used project folder and use it as new working directory, then trigger Save Buffer, and hope the working directory of Projectile Project will be populated into path navigation area as I want.(I have not used Helm projectile, so just a thought now)

That seems like a big change to your workflow, but I do use Projectile and vouch for its niftiness.  Tip: If you have a directory that you would like to turn into a project, but you don't want to create a Git repository or the like, just add an empty `.projectile` file to the directory.  This will cause Projectile to recognize the directory as a project's root.

I do have two more ideas: You can use something like <kbd>SPC f L</kbd> to open a Helm Locate session, then type in the name, then select the file you want, and then press <kbd>C-c C-k</kbd> to kill (copy).  _Then_ when you press <kbd>SPC f s</kbd> to save a file, you can use <kbd>C-y</kbd> to yank (paste) the item you copied from the Helm Locate session.  (Tip: Use <kbd>M-y</kbd> to cycle through kill ring if the first item yanked is not the one you want.)

The same almost works with bookmarks: <kbd>SPC f b</kbd>, then select a bookmark, and then <kbd>C-c C-k</kbd>.  Unfortunately, this copies the _name_ of the bookmark rather than the _path_.  You could use <kbd>SPC f b</kbd>, then select, then <kbd>C-c C-y</kbd> to yank into the minibuffer, then move to the beginning of the path name, then press <kbd>M-k</kbd> for `kill-sentence`, then <kbd>ESC</kbd> to close the Helm Bookmarks session, then <kbd>SPC f s</kbd>, then <kbd>C-y</kbd>. This is a bit tedious though, and I know it is much less straightforward than your original request, so I apologize if it isn't helpful.
