### ISSUE TITLE
Auto-evilification could not remap these functions in map ‘elfeed-search-mode-map’

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#11342]
#### Description :octocat:

elfeed run , give the message:

Auto-evilification could not remap these functions in map ‘elfeed-search-mode-map’:
   - ‘elfeed-search-fetch’ originally mapped on ‘G’

#### Reproduction guide :beetle:
- Start Emacs
- SPC a f to start elfeed

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9865e7731)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp neotree elfeed)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2

**Comment by santiyounger** [comment]
Hey, thanks for asking this question I understand it's been closed due to inactivity, I have the exact same problem. 
Is anyone aware of how to solve it?

**Comment by duianto** [comment]
Is something broken?

Or is it just that the message makes it sound like somethings broken?

I'm able to open an elfeed buffer with `SPC a r e`.

And with the default feeds from the elfeed readme configured
https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Breaders/elfeed#manually

Pressing: `gr` calls `(elfeed-update)` which updates the list.

If the issue is that `G` doesn't call the `elfeed-search-fetch` command, then it's bound to: `C-S-g`
source:
https://github.com/syl20bnr/spacemacs/blob/76301564c5fa6fbd4a9a07ef35529d931aecd367/layers/%2Bdistributions/spacemacs-bootstrap/local/evil-evilified-state/evil-evilified-state.el#L301

The default evil behavior of pressing `G`, moves the cursor to the bottom of the buffer, that's probably why the elfeed fetch command is rebound.

I'm not familiar enough with how auto evilification works, to say if that message could be prevented from appearing.

**Comment by thyeun** [comment]
still facing this, anyone have a solution on?

![2022-07-23T17:39:58,188244201+08:00](https://user-images.githubusercontent.com/1939446/180599948-568909dc-6c99-4681-ac28-79e6a355646d.png)

**Comment by lebensterben** [comment]
@thyeun 
Not a bug.

**Comment by thyeun** [comment]
@lebensterben yup, notice it is not a bug, just want to know any solution to remove it since it still happen after so many years.

**Comment by lebensterben** [comment]
I don't care about this message showing up.

**Comment by thyeun** [comment]
@lebensterben if you dont care, than no point to make a PR. And commented here is to let others know this error still appear.

**Comment by lebensterben** [comment]
@thyeun 

You probably are not familiar with how open source collaboration works.

This is not a bug so it has very low priority. Thus I don't care about this message keep showing up.

If anyone else is interested in this, they can devote their time investigating it and making PRs.

I will review PRs as a maintainer.

**Comment by thyeun** [comment]
@lebensterben i think you are not familiar with how open source collaboration works,  i already mentioned it is not a bug and i know it is low priority, that why no need to open PR for this, i just want to notify that it still happen, you get the point? 

a solution not mean need to be solve due to that it is bug or not a bug, because there might an alternative solution that i cant figure out, that why i mentioned is there a solution. if you want to open PR to make an investigation, than it is up to you, and if you dont care this message it is still up to you, nobody ask you to make change or to get a solution from you too.  

Remind you, an open source collaboration works mean that everyone have the right to contribution, and a contribution can be raise a issue that appear on the open source application too and it is not necessary to get an attention for a solution, it can be just a notify to the maintainer that this message/issue still appear, you understand that or not? dont try to tell me how open source works, i been doing that more than 25years.

**Comment by lebensterben** [comment]
@thyeun 

your reply is hilarious.

25 years of open source development and you've no record of any open source contribution?

I saw that you've used Clear Linux for a period, which means my work is running on your computer and yours is not on mine.

**Comment by thyeun** [comment]
@lebensterben sorry not even using clear linux for a second before, dont try assume something that is not true. many record like you, but still totally no ideal how open source collaboration works and not even know how open source contribution workflow. You sound hilarious to me, it that record even true?

**Comment by lebensterben** [comment]
Stop lying.

You begged Erik Dubois to make a distribution of Clear Linux with i3 on Twitter. Even though he's the developer of Arco Linux not Clear Linux.

You begged Clear Linux team to include Polybar into desktop-i3 bundle. Even though Polybar is not a part of i3 and i3 itself is removed from Clear Linux.

You changed the line on Spacemacs home buffer from
 `Made with love by the community` to `Made with love by Thomas Yeun` and you renamed it to Pacman Emacs and made a silly Youtube upload. Are you kidding me?

The closest time you are to open source development is when you begged Manjaro to give you a free set of sticker.

It's pathetic that you can only make comments based on what I said before and whenever you added anything you make the entire sentence in-cohesive.

**Comment by thyeun** [comment]
@lebensterben Stop lying to yourself and stop be pathetic or hilarious, your eyes problem it is? see my previous post, is that a clear linux to you?

for Erik Dubois, i saw he done so many good things on the arch linux, that why i mentioned why not try it using clear linux? i even ask him to create Swaywm too many years ago (pls and try check it back. i know you can) hahahaha

and i never ever want to using clear linux, because it is not my cup of tea.  You are so hilarious. or are you mentally have some issue that like to assume everythings?.

And try and please double check back my dotfile and my youtube, old and new, it that a clear linux to you? or your eyes having an issue?

For the emacs, nothing wrong with that by modify it or customize it according to what i want, i even can put your name inside to, if i want to? is that a problem? or is that just yours problem?

Do you know that every emacs users have it name for it customize emacs name workspace, and it is prove that your so call record are doubt from me. you just like a chinese people said a fog in the well. 

For manjaro, it is for fun, do you know what is call fun? Manjaro sticker is nice but sadly i miss it.

For you extra info i even ask Eclipse che to remake the t-shirt too, you can google it or try to ask Tyler, the t-shirt are so nice, i still keep it until today

You are pathetic that just see the half of the comment, but not even know/understand the behind story.
