### ISSUE TITLE
Cann't use anzu with spaceline-all-the-icons-theme

### ISSUE THREAD

**Issue by ArchCST** [syl20bnr/spacemacs#11395]
#### Description :octocat:
Cann't use anzu on spaceline-all-the-icons-theme

#### Reproduction guide :beetle:
- Start Emacs
- press `/`

*Observed behaviour:* :eyes: :broken_heart:
If using:
```
dotspacemacs-mode-line-theme '(spacemacs :separator wave :separator-scale 1.5)
```
when press `/` can find there is `(0/0)` on the left of mode-line, but when useing:

```
dotspacemacs-mode-line-theme '(all-the-icons :separator wave :separator-scale 1.5)
```
when press `/` con NOT find `(0/0)` on anywhere of the mode-line.

Tried add:
```
(defun dotspacemacs/user-config ()
  (spaceline-all-the-icons--setup-anzu))
```
Doesn't work either.

*Expected behaviour:* :heart: :smile:
Use anzu with spaceline-all-the-icons-theme

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9865e7731)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(python html yaml sql javascript
         (chinese :packages youdao-dictionary fcitx :variables chinese-enable-fcitx t chinese-enable-youdao-dict t)
         osx helm
         (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/" :disabled-for org markdown)
         (better-defaults :variables better-defaults-move-to-beginning-of-code-first t better-defaults-move-to-end-of-code-first t)
         emacs-lisp git markdown neotree
         (org :variables org-want-todo-bindings t org-enable-github-support t org-src-preserve-indentation t)
         (shell :variables shell-default-height 30 shell-default-position 'bottom)
         (spell-checking :variables spell-checking-enable-by-default nil)
         syntax-checking)
```

**Comment by duianto** [comment]
Confirmed: I'm not seeing the `/` search segment either, on the `all-the-icons` mode-line:
```
   dotspacemacs-mode-line-theme '(all-the-icons :separator wave :separator-scale 1.5)
```

#### But I'm seeing another stranger behavior with `/`, `?` and `:`

When the `vim` editing style is used, and the Emacs frame only has one window and either `/`, `?` or `:` is pressed, then the window number segment (second icon from the left) appears and it disappears when the prompts are canceled (`Esc` or `C-g`).

When the `hybrid` editing style is used, then only `:` makes the window number segment appear/disappear, but nothing changes on the mode-line when `/` or `?` is pressed.

The window segment is hidden when there only is one window, this is probably by design since the window segment doesn't have to be visible when there only is one window. The window segment does appear as expected when the Emacs frame is split into two or more windows.

The workspace number segment (third from the left) is shown all the time, even when there only is one workspace. It might be because the workspace segment seems to be made up of two icons with a vertical bar between them:
- On the left side: An eye icon that shows the minibuffer message "Create new Eyebrowse window config" on mouse over.
- On the right side: The workspace number shows "Switch Eyebrowse window config" on mouse over.

Adding:
```
    (spaceline-all-the-icons--setup-anzu)
```
to the user-config with the `vim` or `hybrid` editing style, doesn't seem to change anything.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2ac7ee8f9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey emacs-lisp git helm html markdown org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by ArchCST** [comment]
> When the `hybrid` editing style is used, then only `:` makes the window number segment appear/disappear, but nothing changes on the mode-line when `/` or `?` is pressed.

Exactly the same issue here
