### ISSUE TITLE
Refactor: Auto-save

### ISSUE THREAD

**Issue by dijonkitchen** [syl20bnr/spacemacs#11453]
Instead of what was done in https://github.com/syl20bnr/spacemacs/commit/cd70f04, use the `auto-save-visited-mode` in Emacs 26.1+: https://www.emacswiki.org/emacs/AutoSave#toc4

Or perhaps even better, auto-save with the `'focus-off-hook`: https://www.emacswiki.org/emacs/AutoSave#toc7

**Comment by d12frosted** [comment]
I use `focus-out-hook` to `(save-some-buffers t)` and it works great in most situations, however since  I have aggressive trailing whitespace cleaning I have to put space after switching back to Emacs.

**Comment by dijonkitchen** [comment]
For future reference, I've put these in my `user-config`; it seems a lot simpler than writing custom functions and stuff:

```
(setq auto-save-timeout 2)
(add-hook 'focus-out-hook 'do-auto-save)
```

**Comment by BobCromwell** [comment]
Maybe you could use this code https://github.com/manateelazycat/auto-save/blob/master/auto-save.el and focus hook

**Comment by blaa** [comment]
I have a long-term problem with autosave with a setting:
dotspacemacs-auto-save-file-location 'original

Sometimes (not too often, but when it happens for a buffer it keeps repeating) the emacs mangles buffer-file-name and buffer-auto-save-file-name to have `#` (`#file#`) - only the buffer-file-truename stays the same. After it happens, my further manual saves go to the `#file#` instead. 

I'm trying to chase the cause of this, but maaaybe it's caused by using obsolete (since 26) method for auto-save 'original. I'm on 28.0.50 (27 had this issue too).

**Comment by blaa** [comment]
Another hint on the mechanics of the issue: 
After issue happens once and I move the file back from #file# to `file`, the buffer-file-name is changed back, buf buffer-auto-save-file-name is still `#file#` and during the next auto-save cycle in this configuration the buffer-file-name is changed another time.
