### ISSUE TITLE
Error while opening IPython Notebook List

### ISSUE THREAD

**Issue by david-morris** [syl20bnr/spacemacs#11465]
While trying to load the ipython-notebook with `SPC a i n` I got the error, `Cannot open load file:  No such file or directory, ein`.  I looked at #4663 and added `ein` to my dotspacemacs-additional-packages and reloaded, but that did not fix the problem.

I don't really know how to use the emacs debugger.  Is this a full backtrace, or did I miss a step? Here's what I got:
    ```Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "ein")
  autoload-do-load((autoload "ein" nil t nil) ein:notebooklist-open)
  command-execute(ein:notebooklist-open)```

This bug happens every time I try to open ipython-notebook on my windows laptop.

**Comment by bmag** [comment]
Sounds like the ein package wasn't installed properly. I'd suggest you delete the ein directory from your elpa directory (the directory where installed packages are placed) and let Spacemacs reinstall the ein package (also remove it from `dotspacemacs-additional-packages`).

This indeed looks like a full backtrace, even though it's just shorter than most backtraces I've seen. (and line breaks were lost in the formatting, but it's still readable)

**Comment by david-morris** [comment]
Thanks bmag!  I think I'm making progress now, since I have a different error.  I scrubbed ein from my rc and packages, then invoked the layer by opening an .ipynb.  Then `SPC a i n` didn't work, but I got the following messages:

> Establishing session.
> Contacting host: 127.0.0.1:8888
> Establishing session..
> ein: [error] Login to http://127.0.0.1:8888 failed
> ‘ein:notebooklist-open’ is an obsolete command (as of 0.14.2); use ‘ein:notebooklist-login’ instead.

Running that command resulted in the following

> Establishing session... failed
> Auto-evilification could not remap these functions in map ‘edebug-mode-map’:
>    - ‘edebug-Go-nonstop-mode’ originally mapped on ‘G’
> Establishing session.
> Contacting host: 127.0.0.1:8888
> ein: [error] Login to http://127.0.0.1:8888 failed
> Establishing session... failed

**Comment by bmag** [comment]
Sorry, don't think I can help you much further. FWIW, I've started using ipython-notebook layer recently on develop branch and it's been smooth sailing for me so far, except for some rough edges around `ein:open-console`.

The "obsolete command" warning is fixed in develop; the "auto-evilification" message is not relevant; the failure to establish a session is the real issue here, and it could be either a problem with the layer in Spacemacs (possibly fixed in develop), a problem upstream in the package, or something in your setup that isn't exactly right.
