### ISSUE TITLE
wrong-type-argument (perspective "Default")

### ISSUE THREAD

**Issue by sebhahn** [syl20bnr/spacemacs#11615]
#### Description :octocat:
New layout cannot be created after a predefined custom layout has been created (in my case the custom layout shows either mu4e or org-agenda)

#### Reproduction guide :beetle:
- Start Emacs
- Start predefined custom layout `SPC l o m`
- Create a new layout `SPC l 2`

*Observed behaviour:* :eyes: :broken_heart:
New layout cannot be created

*Expected behaviour:* :heart: :smile:
New layout should be created

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. db0dd6d94)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/" auto-completion-complete-with-key-sequence "jk" auto-completion-enable-help-tooltip nil)
 bibtex c-c++ colors csv custom-org-config dash
 (deft :variables deft-directory "~/ownCloud/org/deft/")
 emacs-lisp
 (elfeed :variables rmh-elfeed-org-files
         (list "~/ownCloud/org/elfeed.org")
         elfeed-db-directory "~/ownCloud/org/.elfeed")
 elixir erc erlang ess games
 (git :variables git-gutter-use-fringe t)
 github gnus helm html ipython-notebook
 (latex :variables font-latex-fontify-script nil latex-enable-auto-fill t latex-enable-folding t)
 lua markdown mu4e-config
 (org :variables org-enable-reveal-js-support t)
 (orgwiki :variables org-wiki-location "~/ownCloud/org/wiki/")
 pandoc plantuml
 (python :variables python-enable-yapf-format-on-save nil python-auto-set-local-pyenv-version 'on-project-switch python-test-runner 'pytest)
 python-config ranger research-config ruby search-engine semantic
 (shell :variables shell-default-shell 'term shell-default-term-shell "/bin/zsh")
 speed-reading spell-checking syntax-checking tmux version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument perspective "Default")
  signal(wrong-type-argument (perspective "Default"))
  safe-persp-hidden("Default")
  #[(u) "	!?\207" [clause u] 2]("Default")
  cl-delete(nil ("Default" "code" "@Start") :if-not #[(u) "	!?\207" [clause u] 2])
  apply(cl-delete nil ("Default" "code" "@Start") :if-not #[(u) "	!?\207" [clause u] 2] nil)
  delete-if-not(#[(u) "	!?\207" [clause u] 2] ("Default" "code" "@Start"))
  persp-read-persp("to switch(in frame)" nil nil nil nil t)
  persp-frame-switch(nil #<frame emacs-25.3@shahn-7490 0x11e5c30>)
  persp-switch(nil)
  (cond (generated-name (persp-switch generated-name)) ((y-or-n-p (concat "Layout in this position doesn't exist. " "Do you want to create one? ")) (persp-switch nil) (spacemacs/home-delete-other-windows)))
  (let ((persp-reset-windows-on-nil-window-conf t) (generated-name (and dotspacemacs-auto-generate-layout-names (spacemacs//generate-layout-name pos)))) (cond (generated-name (persp-switch
```

**Comment by sebhahn** [comment]
Could someone help me understanding the backtrace? I'd really like to understand the problem here?

**Comment by orialb** [comment]
I encountered a similar problem. The scenario is not exactly the same as yours but from looking at the backtrace I think it's the same issue. 

It seems that the issue is that the call to `(persp-switch nil)` results in an error. I'm not sure  whether it is a bug in perspective mode (as it seems that calling `(persp-switch nil)` should be allowed) or whether it's a problem only in spacemacs .

I found the following workaround:
1. set `dotspacemacs-auto-generate-layout-names` to `t`
2. now when I generate a new layout with `SPC l NUM` it will generate some (weird) name automatically for example "elephant". This means that spacemacs will call `(persp-switch "elephant")` instead of `(persp-switch nil)`. 
3. rename the new layout to a name of my choice with `SPC l R` .

by the way- so far I was mainly using `SPC p l` which calls `helm-persp-switch-project` and allows you to generate new layout from a projectile project (it will get the name of the project).
