### ISSUE TITLE
Can't install org-trello

### ISSUE THREAD

**Issue by LucaMarconato** [syl20bnr/spacemacs#11633]
I am using the `develop` branch and I am trying to install `org-trello`. If I use `package-install` I can install it and configure it (for loading the package I have also to evaluate `(require 'org-trello)`, as stated in the [official guide](https://org-trello.github.io/install.html)), but when I reopen Spacemacs, even if I added `org-trello` to `dotspacemacs-additional-packages` and even if I changed `dotspacemacs-install-packages` to `used-but-keep-unused`, I can't use `org-trello` anymore.
In fact, when reopen Spacemacs and evaluate `(require 'org-trello)`, I get the error: "No such file or directory".

I tried using the built-in `org-trello` support, which should be available in the `develop` branch as stated here https://github.com/syl20bnr/spacemacs/pull/11244. Using `(org :variables: org-enable-trello-support t)` does not give me errors but does not actually install `org-trello`! I simply don't see the `org-trello` functions when pressing `M-x`. Again, if I evaluate `(require 'org-trello)` I get the same error as before.

How can I install `org-trello` in Spacemacs? In normal Emacs the installation with `package-install` + `require` would just work.

**Comment by undergroundquizscene** [comment]
I had the same problem with `dotspacemacs-additional-packages` not seeming to do anything, but when I use `(org :variables org-enable-trello-support t)` in `dotspacemacs-configuration-layers`, everything works correctly. I notice you have written `:variables:` where I have `:variables` – could that be your problem? If not, then I'm not sure why it works for me but not for you.

I do think there should be an error message if you add `org-trello` to `dotspacemacs-additional-packages` though, as it was not clear what the problem was. (Had a similar problem with `org-jira`, gonna go check if it's the same problem.)

**Comment by undergroundquizscene** [comment]
There is an open issue about this (#11382), so I think this issue should probably be closed (assuming the problem is that you wrote `:variables:` instead of `:variables`).
