### ISSUE TITLE
Splash screen is only partially visible.

### ISSUE THREAD

**Issue by hhirsch** [syl20bnr/spacemacs#11697]
#### Description :octocat:
The splash screen is only partially visible. It is scrolled out of the right of the screen
![space-spacemacs-splash](https://user-images.githubusercontent.com/2451426/49683164-79dd2100-fac0-11e8-93c8-e261a0520f37.png)
#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
The whole splash screen is only partially visible. It is scrolled out of the right of the screen

*Expected behaviour:* :heart: :smile:
Splash Screen Centered

#### System Info :computer:
- OS: gnu/linux
- WM: awesomewm
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa45)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(graphviz ruby typescript sql python yaml php haskell vimscript lua javascript csv html nginx auto-completion emacs-lisp syntax-checking git markdown org php javascript yaml spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by hhirsch** [comment]
I assure you, it is a fresh delicious issue. Nothing stale about it.

**Comment by duianto** [comment]
Could it be awesomewm related?

I've never used it, but from the screenshot it looks like the Emacs frame had twice the width when Spacemacs drew the splash screen and then the Emacs frame was reduced to half of it's width.

For me the splash screen behaves as follows, depending on the state of these two variables:
`dotspacemacs-fullscreen-at-startup` and `dotspacemacs-maximized-at-startup`

#### PopOS, on both the Spacemacs master and develop branch
- fullscreen `t`, left aligned while loading, centered when finished loading
- maximized `t`, centered while and when finished loading

#### Windows 10, on both the Spacemacs master and develop branch
- fullscreen `t`, left aligned while loading, centered when finished loading
- maximized `t`, left aligned while loading, centered when finished loading

In both OS's:
- fullscreen and maximized variables: `nil` (default value), splash screen centered while and after loading, because the Emacs frame doesn't change size.

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.200.13, (develop: 0.300.0)
- Spacemacs branch: master (rev. 26b8fe0c3), develop (rev. d17c6e1e9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 pdf
                 (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.200.13, (develop: 0.300.0)
- Spacemacs branch: master (rev. 26b8fe0c3), develop (rev. d17c6e1e9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion c-c++ command-log emacs-lisp git github
            (gnus :variables gnus-summary-thread-gathering-function 'gnus-gather-threads-by-subject)
            go helm imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org pdf
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by hhirsch** [comment]
I don't recall this ever happening with recent builds.
