### ISSUE TITLE
auto-fill not working in org-mode (maybe fixed)

### ISSUE THREAD

**Issue by mkleehammer** [syl20bnr/spacemacs#11749]
#### Description :octocat:
auto-fill no longer works in org-mode.  I don't have date when it stopped
since I ignored it for quite a few weeks or months.

This problem has been reported twice, but nothing came of them.

Also note that this has occurred with several versions over the last couple of months.

#### Reproduction guide :beetle:
- Start Emacs
- Open any org-mode file.  Keep typing beyond the fill-column (95 in my case).
- Note that the line does not wrap when space is pressed beyond the fill column.

*Observed behaviour:* :eyes: :broken_heart:
The typing continues without wrapping.

*Expected behaviour:* :heart: :smile:
The line should wrap, which it does in other modes.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1 
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5b2e969b3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(csv emacs-lisp
     (git :variables git-magit-status-fullscreen t)
     html
     (ibuffer :variables ibuffer-group-buffers-by 'projects)
     ivy
     (javascript :variables javascript-backend
                 (if this-box-is-fast 'tern nil))
     markdown
     (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
     (python :variables python-fill-column 95)
     spell-checking sql
     (syntax-checking :variables syntax-checking-enable-tooltips nil)
     yaml
     (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t)
     graphviz yaml systemd deft org)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
There are no errors and no unusual messages in the Messages buffer.
```
```

**Comment by shoover** [comment]
I have the same problem with stock Emacs 26.1 on Windows and org mode 9.2.1. The problem seems to be limited to org mode. Evaluating (org-auto-fill-function) works as expected, it just doesn't run automatically while typing. I'm reverting to Emacs 26.0.50.

**Comment by redpanda1234** [comment]
I have the same problem as well on Arch Linux. `M-q` likewise doesn't seem to do anything until after manually breaking the once line.

**Comment by duianto** [comment]
Confirmed.

`auto-fill-mode` is disabled in `org-mode`

`M-x auto-fill-mode` reports:
>Auto-Fill mode enabled in current buffer

This could be used as a workaround from the `dotspacemacs/user-config` section of `.spacemacs`.
```
    (add-hook 'org-mode-hook 'turn-on-auto-fill)
```
source: https://www.gnu.org/software/emacs/manual/html_node/efaq/Turning-on-auto_002dfill-by-default.html

It sounds like it used to work:
>auto-fill no longer works in org-mode. I don't have date when it stopped
since I ignored it for quite a few weeks or months.

but there's no mention of `auto-fill` in the `org` layer docs:
https://github.com/syl20bnr/spacemacs/tree/develop/layers/+emacs/org

and `SPC /` searching in the Spacemacs `.emacs.d` project for `auto-fill`, finds entries for `auto-fill` in the `latex` layer but not in the `org` layer.

<details>
<pre>
CHANGELOG.org:2844:59:  in the current project. ~SPC /~ is similar but does not auto-fill the search
CHANGELOG.org:4337:8:- Use =auto-fill-mode=, with an environment-aware auto-fill function, you
CHANGELOG.org:4337:51:- Use =auto-fill-mode=, with an environment-aware auto-fill function, you
CHANGELOG.org:4338:15:  can enable =auto-fill= support by setting the layer variable
CHANGELOG.org:4339:17:  =latex-enable-auto-fill= to =t=. You can also inhibit it in some environments
CHANGELOG.org:4562:19:  - ~SPC t F~ for auto-fill
doc/DOCUMENTATION.org:1536:37:| ~SPC t F~   | =Ⓕ=     | F     | auto-fill mode                                                       |
layers/+lang/latex/config.el:19:22:(defvar latex-enable-auto-fill t
layers/+lang/latex/config.el:20:19:  "Whether to use auto-fill-mode or not in tex files.")
layers/+lang/latex/config.el:34:40:  "List of environment names in which `auto-fill-mode' will be inhibited.")
layers/+lang/latex/funcs.el:32:13:  (let ((do-auto-fill t)
layers/+lang/latex/funcs.el:35:20:    (while (and do-auto-fill (not (string= current-environment "document")))
layers/+lang/latex/funcs.el:38:16:            do-auto-fill (not (member current-environment latex-nofill-env))))
layers/+lang/latex/funcs.el:39:14:    (when do-auto-fill
layers/+lang/latex/funcs.el:40:11:      (do-auto-fill))))
layers/+lang/latex/funcs.el:42:14:(defun latex/auto-fill-mode ()
layers/+lang/latex/funcs.el:43:11:  "Toggle auto-fill-mode using the custom auto-fill function."
layers/+lang/latex/funcs.el:43:43:  "Toggle auto-fill-mode using the custom auto-fill function."
layers/+lang/latex/funcs.el:45:4:  (auto-fill-mode)
layers/+lang/latex/funcs.el:46:9:  (setq auto-fill-function 'latex//autofill))
layers/+lang/latex/packages.el:44:26:      (when latex-enable-auto-fill
layers/+lang/latex/packages.el:45:43:        (add-hook 'LaTeX-mode-hook 'latex/auto-fill-mode))
layers/+lang/latex/README.org:14:8:  - [[#auto-fill][Auto-fill]]
layers/+lang/latex/README.org:14:19:  - [[#auto-fill][Auto-fill]]
layers/+lang/latex/README.org:70:4:** Auto-fill
layers/+lang/latex/README.org:71:11:To enable auto-fill set the variable =latex-enable-auto-fill= to =t=.
layers/+lang/latex/README.org:71:52:To enable auto-fill set the variable =latex-enable-auto-fill= to =t=.
layers/+lang/latex/README.org:74:2:=auto-fill-mode= will be inhibited.
layers/+lang/latex/README.org:78:36:    (latex :variables latex-enable-auto-fill t))
layers/+spacemacs/spacemacs-defaults/config.el:91:21:(spacemacs|diminish auto-fill-function " Ⓕ" " F")
layers/+spacemacs/spacemacs-defaults/keybindings.el:344:23:(spacemacs|add-toggle auto-fill-mode
layers/+spacemacs/spacemacs-defaults/keybindings.el:345:11:  :status auto-fill-function
layers/+spacemacs/spacemacs-defaults/keybindings.el:346:8:  :on (auto-fill-mode)
layers/+spacemacs/spacemacs-defaults/keybindings.el:347:9:  :off (auto-fill-mode -1)
layers/+spacemacs/spacemacs-defaults/local/help-fns+/help-fns+.el:2031:52:                ;; Can be both risky and safe, eg `auto-fill-function'.
layers/+spacemacs/spacemacs-defaults/local/help-fns+/help-fns+.el:2304:89:                (when (risky-local-variable-p variable) ; Can be both risky & safe, eg `auto-fill-function'.
layers/+tools/rebox/README.org:25:3:- Auto-fill correctly in comments,
tests/doc/dotspacemacs.el:12:60:                                              latex-enable-auto-fill t
</pre>
</details>

<br />

@redpanda1234 `M-q` which calls `fill-paragraph` works for me.

#### System Info :computer:

`Org mode version 9.2.2 (9.2.2-elpaplus @ ~/.emacs.d/elpa/26.1/develop/org-plus-contrib-20190304/)`

- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm markdown multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by dorianr666** [comment]
bump

**Comment by mkleehammer** [comment]
To clarify, my problem is not that auto-fill was not enabled -- I know how to turn it on and off.  When enabled, it does not actually work.  The fill function is not called.

**Comment by duianto** [comment]
The line wraps as soon as I type something past the fill column and press `space` when 
`M-x` `auto-fill-mode` `RET` is enabled manually in a `org-mode` buffer. In both Ubuntu 18.04 and Windows 1903 on the `develop` branch with updated packages.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a500662a6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm markdown multiple-cursors org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a500662a6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git helm javascript markdown multiple-cursors
            (org :variables org-want-todo-bindings t)
            shell spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by mkleehammer** [comment]
I figured out what is going on in my case - I had added `(setq comment-auto-fill-only-comments t)` globally which, as the name suggests, disables auto-fill unless you are in a comment.  Turning this off using the org-mode hook and turning it off globally both fixed it.

Since there are other people reporting this, I don't know if I should close it or not.  I'll leave it open, but others that have reported, please try this and chime in.

**Comment by shoover** [comment]
Great find! Disabling `comment-auto-fill-only-comments` in an org-mode-hook fixed it for me, too.

In the hook, I made the variable local to retain the global setting for programming modes. `(set (make-local-variable 'comment-auto-fill-only-comments) nil)`.

**Comment by mkleehammer** [comment]
Excellent point.  I assume `setq-local` would do the same?

I'll close this for now - anyone else reporting on it can reopen if there are other issues.

**Comment by giansegato** [comment]
Hi! I cannot find a solution to this problem... I tried several things outlined in this thread, with no luck. I still have Org mode that doesn't wrap lines longer than 80 chars.

I have Spacemacs 0.300.0, Emacs 26.3, vanilla installation with only the `git`, `markdown` and `org mode` layers installed. 

This is my `user-config`:

```elisp
  (with-eval-after-load 'org
    (setq-default org-pretty-entities t
                  evil-org-key-theme '(textobjects navigation additional insert todo)
                  org-hide-leading-stars t
                  org-pretty-entities-include-supersubscripts t) 

    ;; Auto reload
    (global-auto-revert-mode t)

    (defun my-org-settings ()
      (spacemacs/toggle-auto-fill-mode-on)
      (setq fill-column 80)
      (abbrev-mode)
      (org-indent-mode)
      (setq comment-auto-fill-only-comments t)
      )

    (add-hook 'org-mode-hook #'my-org-settings)

   )
```

I also tried disabling `comment-auto-fill-only-comments` globally as well, as suggested (at the top of `user-config`) with no effect.

**Comment by duianto** [comment]
This works for me:
```elisp
(add-hook 'org-mode-hook 'turn-on-auto-fill)
```
source: https://emacs.stackexchange.com/questions/50667/org-mode-auto-fill-mode

I noticed that I had already suggested it in a [previous comment ☝️ ](https://github.com/syl20bnr/spacemacs/issues/11749#issuecomment-470034949), but I rediscovered it again.

Just make sure that you don't have:
```elisp
      (setq comment-auto-fill-only-comments t)
```
defined in your `my-org-settings` function.
```elisp
      (defun my-org-settings ()
        ;; any of these work
        ;; (turn-on-auto-fill)
        ;; (auto-fill-mode)
        (spacemacs/toggle-auto-fill-mode-on)
        ;; but not when this is enabled
        ;; (setq comment-auto-fill-only-comments t)
        )
      (add-hook 'org-mode-hook 'my-org-settings)
```

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6d024e789)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion c-c++ command-log emacs-lisp git github
            (gnus :variables gnus-summary-thread-gathering-function 'gnus-gather-threads-by-subject)
            go helm imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>
