### ISSUE TITLE
company-dabbrev should be removed from org-mode company-backends variable

### ISSUE THREAD

**Issue by betaprior** [syl20bnr/spacemacs#11743]
Out-of-the-box behavior of the autocompletion layer in org files includes expanding words using company-dabbrev. The resulting experience, particularly in large org files, is that a completion pops up for nearly every word the user types. Even worse, the completion is also triggered for numbers. You see users asking [again](https://emacs.stackexchange.com/questions/35345/how-to-turn-off-autocompletion-for-numbers-and-numbers-only-in-company-mode-in) and [again](https://emacs.stackexchange.com/questions/27502/stop-company-mode-from-completing-dictionary-words) and [again](https://emacs.stackexchange.com/questions/9835/how-can-i-prevent-company-mode-completing-numbers) how to turn this off.

Ideally, this behavior needs to be changed (probably by removing company-dabbrev from list of org-mode company-backends), and at the very least documented with suggestions on how to perform the fix by hand.

**Comment by hyiltiz** [comment]
This is not stale. Please re-open. I can reproduce this and is very annoying (I was digging up solutions for this and ended up here).

**Comment by dhawangayash** [comment]
I found this useful this tip useful. I don't know if this was done to resolve this issue, but this solves the problem. Essentially disabling auto-complete in org and git layers.

https://www.spacemacs.org/doc/DOCUMENTATION.html#disabling-layer-services-in-other-layers

```
(defun dotspacemacs/layers ()
  ;; List of configuration layers to load.
  (setq-default dotspacemacs-configuration-layers
    '(org git
      (auto-completion :disabled-for org git))))
```

**Comment by hyiltiz** [comment]
Can we close this as there is a workaround (though not a real solution)?

**Comment by lebensterben** [comment]
This should be removed. I will keep it open.

**Comment by real-or-random** [comment]
I simply have this in my `dotspacemacs/user-config`:
```
(setq spacemacs-default-company-backends (delq 'company-dabbrev spacemacs-default-company-backends))
```

This removes company-dabbrev everywhere (except if a layer adds it explicitly). Now that I think about it, perhaps disabling it everywhere (and not just in org-mode) is the more sensible default?! If people don't want it in org-mode, they probably generally don't want it in text-mode, and since it is currently at the end of `spacemacs-default-company-backends`, it only appears in these modes anyway (in prog-modes, other backends will kick in).

*edit: Ah, it is often active in code comments in prog-modes ... But I don't think a different reasoning applies there, and it could be disabled there as well.*

Do you think it's reasonable to remove it entirely from `spacemacs-default-company-backends`? Maybe with a hint in the docs that the user can append it if desired.

**Comment by smile13241324** [comment]
This sounds like it has been solved please reopen or tag me if it has not and I will come back to this issue.
