### ISSUE TITLE
spacemacs markdown-preview failed with exit code 127

### ISSUE THREAD

**Issue by kenardes** [syl20bnr/spacemacs#11806]
#### Description :octocat:
spacemacs markdown-preview failed with exit code 127

#### Reproduction guide :beetle:
- open markdown file with .md extention via terminal emulator
- SPC m c p

*Observed behaviour:* :eyes: :broken_heart:
- not result anything but just show error message "markdown failed with exit code 127"

*Expected behaviour:* :heart: :smile:
- automically open default internet browser then preview the markdown

#### System Info :computer:
- OS: arch linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html
 (markdown :variables markdown-live-preview-engine 'vmd)
 vimscript helm
 (auto-completion :variables auto-completion-enable-sort-by-usage t)
 emacs-lisp git spell-checking
 (haskell :variables haskell-completion-backend 'intero)
 themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
```

#### fix
I follow the suggestion from https://stackoverflow.com/questions/50452924/markdown-preview-in-emacs-fails-pandoc-error-127, by creating symlink of pandoc to markdown then reboot pc:

$ ln -s /usr/bin/pandoc ~/.local/bin/markdown

now it fix.

**Comment by Asalle** [comment]
Had the same issue, didn't reboot, just opened a new tab in terminal and started emacs from there. It works!

**Comment by da-edra** [comment]
You can also solve this by installing [discount](https://github.com/Orc/discount).

**Comment by siegy22** [comment]
`brew install markdown` worked for me 😄

**Comment by samyakbhuta** [comment]
`sudo apt install markdown` worked for me.

**Comment by oouxx** [comment]
`sudo pacman -S discount` worked for me.

**Comment by duianto** [comment]
As others have stated, the issue seems to be that a markdown executable needs to be installed.

#### This is what I saw in Windows:

On the Spacemacs `develop` branch with the `markdown` layer installed.

Opened an example markdown file: `markdown_example.md`
pressed: `SPC m c p` (which calls `markdown-preview`)
it showed the message:
>user-error: markdown failed with exit code 1

The comments in this issue suggested installing `markdown`
Wasn't able to find a `markdown` executable for windows.

Read the Spacemacs markdown layer documentation:
https://github.com/syl20bnr/spacemacs/tree/develop/layers/+lang/markdown
which suggests installing: `vmd`
```
npm install -g vmd
```

Added the layer variable:
```elisp
(markdown :variables markdown-live-preview-engine 'vmd)
```

Opened the markdown example file and pressed `SPC m c p` again, with the same error:
>user-error: markdown failed with exit code 1

Read the markdown-mode documentation:
https://jblevins.org/projects/markdown-mode/
which states:
>After installing the Emacs package, be sure to configure `markdown-command` to point to the preferred Markdown executable on your system.

After setting:
```
(setq markdown-command "vmd")
```

`SPC m c p` opens a `vmd` window outside Spacemacs
with the file: `default.html`
The vmd application shows the text:
>Welcome to vmd.
>
>Open a Markdown file through the
menu or drag and drop a file to
open it.

Closed the vmd window (top right X)
Now a Google Chrome tab opened: `*markdown-output*`
with the address: `file:///C:/Users/username/AppData/Local/Temp/burleYAdPV.html`
but the page was blank.

The Spacemacs markdown documentation showed that there's another preview key binding: `SPC m c P` (uppercase p) (which called `vmd-mode`)
The minibuffer showed:
>Vmd mode enabled in current buffer

and a new `vmd` application window opened,
with the file: `markdown_examples.md.temp`
and it showed a preview of the markdown text.

Any change that was made in the Spacemacs markdown buffer, updated the preview in the vmd window.

The `markdown-command` could be defined as a layer variable.
```elisp
     (markdown :variables
               markdown-live-preview-engine 'vmd
               markdown-command "vmd")
```

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 840b431cf)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git github helm imenu-list
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>
