### ISSUE TITLE
Windows: File error: Searching for program, No such file or directory, /usr/bin/zsh

### ISSUE THREAD

**Issue by gerroon** [syl20bnr/spacemacs#11957]
Hi

I just installed this for the first time on Windows 10 x64, Emacs 25 . I removed the .emacs.d from ~/appdata/roaming which is where Emacs on Win loads the profile. I Clone it there. It worked, I chose my profile, vim etc but it throws the error below. I do not know why it is looking for a Linux like application.

```
Warning (initialization): An error occurred while loading ‘c:/Users/USER/AppData/Roaming/.emacs.d/init.el’:

File error: Searching for program, No such file or directory, /usr/bin/zsh

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

```

thanks

**Comment by yunjianyang** [comment]
I have the same issue here...

**Comment by nnungest** [comment]
@gerroon and @yangguang760 could you start emacs with a --debug-init please

**Comment by gerroon** [comment]
This was caused by HOME set iun the Windows env, which was recommended by the Spacemacs setup. I deleted it from the env now it works fine.

**Comment by lexxish** [comment]
In my case, I _had to_ set HOME as an environment variable to C:/Users/user. Also, otherwise emacs uses C:/Users/user/AppData/Roaming by default which is not ideal. However, when I start emacs from a cygwin terminal I still get this error - not sure why.

**Comment by WMaxZimmerman** [comment]
Does anyone know what are the best things to check for this issue? I tried both of the comments that contradict each other and neither worked.

**Comment by salehmu** [comment]
Same issue with doom

**Comment by rople380** [comment]
Had this issue, was due to not setting the zsh path for shell command correctly in some environment variables, discovered by using at command line:

`emacs --debug-init`

got error message:

```
Debugger entered--Lisp error: (file-missing "Searching for program" "No such file or directory" "/usr/bin/zsh")
  call-process("/usr/bin/zsh" nil t nil "-c" "/opt/homebrew/bin/timeout --help")
  call-process-shell-command("/opt/homebrew/bin/timeout --help" nil t)
  shell-command("/opt/homebrew/bin/timeout --help" t)
```

Fixed by setting:

`  (setq shell-file-name "/path/to/your/zsh")`

whose path can be found by executing at command line:

`which zsh`

in this section:

```
(defun dotspacemacs/user-env ()
  "Environment variables setup.
This function defines the environment variables for your Emacs session. By
default it calls `spacemacs/load-spacemacs-env' which loads the environment
variables declared in `~/.spacemacs.env' or `~/.spacemacs.d/.spacemacs.env'.
See the header of this file for more information."
  (spacemacs/load-spacemacs-env)
  (setq shell-file-name "/path/to/your/zsh")
 )
```

of the main config file:

`~/.spacemacs`

**Comment by nnungest** [comment]
Wow cant believe this is still open after 5 years. This should be closed as these are user path issues. Not an issue with Spacemacs in my opinion.

**Comment by larrasket** [comment]
Nick Nungester ***@***.***> writes:

> Wow cant believe this is still open after 5 years. This should be closed as these are user path issues. Not
> an issue with Spacemacs in my opinion.

It's already closed.
--
Regards,
Salih

**Comment by rople380** [comment]
> Wow cant believe this is still open after 5 years. This should be closed as these are user path issues. Not an issue with Spacemacs in my opinion.

If multiple normal users are having the issues, the debug was not trivial to solve for non-experts over multiple years and no resolution was given, and it totally borks in non-intuitive ways the entire spacemacs and emacs stack; it should probably stay open until solved for the average user.

But that's just me, someone who wants normal users to use things, YMMV if you don't care.

I am a pretty sophisticated user, but not in emacs, and this was not trivial to identify where exactly my path was being pulled from, so I gave up and used this.

This solves it regardless of the environment since you just need one line, the location of the bash, and a reload.

**Comment by nnungest** [comment]
> > Wow cant believe this is still open after 5 years. This should be closed as these are user path issues. Not an issue with Spacemacs in my opinion.
> 
> If multiple normal users are having the issues, the debug was not trivial to solve for non-experts over multiple years and no resolution was given, and it totally borks in non-intuitive ways the entire spacemacs and emacs stack; it should probably stay open until solved for the average user.
> 
> But that's just me, someone who wants normal users to use things, YMMV if you don't care.
> 
> I am a pretty sophisticated user, but not in emacs, and this was not trivial to identify where exactly my path was being pulled from, so I gave up and used this.
> 
> This solves it regardless of the environment since you just need one line, the location of the bash, and a reload.
> 

Apologies, we should document then. Issues are problematic because things are dynamic, but issues can represent broken functionality of the project. I thought this issue was still open and was very surprised when i got the bump, but it's not. 

Glad it's all working for you and thanks for contributing your solution!
