### ISSUE TITLE
Remap `run-pandoc` from SPC-P-/ to SPC-p-/

### ISSUE THREAD

**Issue by hyiltiz** [syl20bnr/spacemacs#12032]
`run-pandoc` is the only (well, in my setup with quite a lot of layers activated) command bound to `SPC-P` that shows `+projects` just like `SPC-p`. It would have been much cleaner user interface to move it to `SPC-p-/` as that binding has not been used by anything anyways.

**Comment by Compro-Prasad** [comment]
This isn't happening anytime soon. Better close this if it isn't a serious problem.

**Comment by duianto** [comment]
@hyiltiz `SPC P` has been given the prefix name `pandoc` on the `develop` branch:
Declares the pandoc prefix https://github.com/syl20bnr/spacemacs/commit/20d444335241ec96bf2b77bcd17e6651f54a85ee

Since Pandoc seems to be a document converter, then it wouldn't make sense to add it among the projects bindings.
