### ISSUE TITLE
v0.101.2: rcirc: "let: Symbol's function definition is void: auth-source-search"

### ISSUE THREAD

**Issue by fotoetienne** [syl20bnr/spacemacs#1203]
When starting rick via SPC-a-i-r, I get the following message:

    let: Symbol's function definition is void: auth-source-search

It worked before upgrading to v0.101.2

Thoughts?

**Comment by nwolfe** [comment]
@fotoetienne Yeah I get this too now, though I was assuming it was something I did with my local GPG stuff that caused this rather than Spacemacs itself.

Either way, I've found that I can `SPC : auth-source-forget-all-cached RET` before launching IRC and it get's around this problem.

**Comment by fotoetienne** [comment]
nwolfe, that did the trick. Still not sure what the underlying problem was, but that worked, thanks!

**Comment by TheBB** [comment]
This is from an old version of Spacemacs, but I did find that we call this function at one point in rcirc, and there's no check to ensure that the package that defines it is loaded, so hopefully this is fixed by https://github.com/syl20bnr/spacemacs/commit/69298f06718304e669a2711d3d7d709cb69f4065, if it was still a problem at all.
