### ISSUE TITLE
Permintaan fitur

### ISSUE THREAD

**Issue by agusbuhori** [syl20bnr/spacemacs#12037]
If you are posting about a *bug* please close this issue and open a new one
using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs. If the
bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template)
You can delete this message to start typing.

**Comment by duianto** [comment]
Corrections needed:
- Write a short description of what the your issue/request is, in the title. That makes it possible to see what it's about from the list of issues, without having to open it first.
- Write a description of the feature request, in the message area.
- Remove the issue instruction text.
- Try to write in English, because that's what most people will understand.

("Permintaan fitur" translates to "Feature request" from Indonesian)
