### ISSUE TITLE
Unable to install spacemacs with recommended emacs distribution for windows 10 from README

### ISSUE THREAD

**Issue by velxundussa** [syl20bnr/spacemacs#12041]
#### Description :octocat:
Spacemacs initial install fails and is unusable with some of those error messages during installation:

`Failed to verify signature archive-contents.sig:
No public key for <HASH> create at <DATE> using DSA
Command output:
gpg: keyblock resource '/c/Users/velxundussa/emacs/bin/c:/Users/velxundussa/.emacs.d/elpa/gnupg/pubring.kbx': No such file or directory
gpg: Signature made <Current datetime>
gpg:                           Using DSA key <Key>
gpg: Can't check signature: No public key`

During the installation of packages step there is multiple failures and spacemacs then throws the following error:
`Fore error: Cannot open load file, No such file or directory, evil`

#### Reproduction guide :beetle:
- Use the recommended build of emacs for windows from the README ( http://emacsbinw64.sourceforge.net/ )
- Start Emacs using runemacs.exe

I attempted the same process with the latest build from https://www.gnu.org/software/emacs/download.html and everything seems to work fine!
Recommending this build may be the way to go.

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs theme loads, but none of the functionalities seem available.

*Expected behaviour:* :heart: :smile:
Spacemacs goodness when following README

**Comment by DanLanglois** [comment]
'recommended emacs distribution for windows 10'

This is ambiguous. What distribution? And then, what were the steps you followed for 'initial install'? Did you run a script? Whether you clicked on a .exe with your mouse vs. running a script is a relevant distinction, especially in the sense that we can't assume it isn't a relevant distinction. If you ran a script, what script? If you followed instructions, what instructions? I might have you wondering if I'm even trying to help, and I admit I'm not the biggest spacemaces expert, but we're trying. I will say on my own authority that if you took 'the recommended' emacs distrution to be off of the master branch, then you might try the develop branch, which is all of 2574 commits ahead. And if you say 'in answer to your query I ran a script', then I'll come back with 'which script'. And if you say the filename of the script, then I'll come back with 'ran it with what command? Ran it where?' If you ran it in a terminal, I'll ask 'what terminal'? It's okay to anticipate such questions. I might ask you if you plugged your computer in, try not to take it personally, you're the one installing on Windows. I would quibble about whether there  could possibly be, by definition, an recommended installation for Windows. Not to digress, the point is about ambiguity. 

You give an interesting piece of info here:

''/c/Users/velxundussa/emacs/bin/c:/Users/velxundussa/.emacs.d/elpa/gnupg/pubring.kbx': No such file or directory'

Broadly, there is at least one issue, of some sort, with shell - Emacs and command line $PATH disagreements. This is progress, so I think it's important that we know exactly what you do if I say 'go to the shell'? Are you using the git bash shell, or cmd, or do you remember what you did last time, or does this mean anything? This may take a bit of patience. 

What if I ask you to 'echo $PATH'? Your issue is an issue of getting some different things to agree on the same PATH. So I want to know what's controlling where your emacs installer (this is ambiguous) is being loaded from. Again, what are you using as your login shell? This might not mean anything, if you say you are not sure what I am asking, that's fine, I can slow down. 

Summary:
We're looking at two things:
-- How do you set or change the PATH system variable? The PATH is the system variable that your operating system uses to locate needed executables from the command line or Terminal window. For example, there might be, as it were, your shell's startup file. Though on Windows, the idea generally, is that the PATH system variable can be set using System Utility in control panel. You may not remember making changes to the system PATH variable, but we can narrow our focus on these kinds of steps:

--In Search, search for and then select: System (Control Panel)
--Click the Advanced system settings link.
--Click Environment Variables. In the section System Variables, find the PATH environment variable and select it. Click Edit. If the PATH environment variable does not exist, I'll be surprised.
In the Edit System Variable (or New System Variable) window, you can specify the value of the PATH environment variable. The point here is just to tell me what it says in there. You'll probably see a great deal, a long line of stuff that you don't know how it got in there.


--If we have to make changes of some sort, then next you will reopen Command prompt window, or such. But what exactly will you do? There are different ways to open a terminal in windows. Such as:

--press "Win-R," type "cmd" and press "Enter" to open a Command Prompt session using just your keyboard. 
-- or, alternatively, click the "Start >> Program Files >> Accessories >> Command Prompt" to open a Command Prompt session using just your mouse. 
-- or, click the "Start" button and type "cmd."
-- but also, some people install and use the linux bash shell on windows 10. You can now run Ubuntu and openSUSE on Windows. I you are doing this, it's good to know. If you aren't, then it may be somesuch alternative that 'works'. 

--Understand, the common wisdom is that Windows is really horrible system for developers and especially for devops. It doesn't even have a usable terminal and shell. I'm not trying to be opinionated, just pointing out that you generally don't need a Windows terminal to get things done on the Microsoft operating system, so this is, I expect, more than you bargained for. 

Final point, most importantly, the shortcut, is to focus on what is the 'recommended ' installation. Upon review, I might have started with this, what emac are you running? Did you install it separately? hooboy, here we go again, what version? In no sense is installation of emacs on windows 'recommended'. I don't mind personally, but this is what you sign up for, it's par for the course.

**Comment by velxundussa** [comment]
Sorry, recommended install wasn't clear, you're right.

I am referring to the recommended installation from spacemacs README file at https://github.com/syl20bnr/spacemacs#windows :

> You can download good quality builds from the emacs-w64 project. It is recommended to install the most recent stable build.

Specifically, this build doesn't seem to work anymore when it did before.

'Initial install' was referring to the first run of emacs after the clone of spacemacs git repo to home folder.

Again, I want to specify that this specific build of emacs isn't working but the GNU one is out of the box with the exact same machine and setup.
In both cases emacs is started with the provided executable for both builds which is "runemacs.exe"

I can say confidently that the same setup worked out of the box with the reccomended buid ~1 month ago as I set it up on another machine then.

I also think that some recent change broke things as there's other peoples encountering similar issues:
https://www.reddit.com/r/emacs/comments/aug9in/failed_to_verify_signature_archivecontentssig/
https://www.reddit.com/r/emacs/comments/apr9b2/bad_signature_from_gnu_elpa_signing_agent/

Sorry, honestly your whole spiel on windows being bad is more confusing than anything I'm not even sure what's your actual question. I do work with both windows and Linux and am familiar with concepts such as environment variables and shells... I don't see anything in my bug report that lead you to think I'm trying to "learn linux" or anything having to do with devops...

**Comment by smile13241324** [comment]
@velxundussa thanks for reporting the issue, as you said before there are many sources to obtain emacs from and as generic applications like emacs tend to be quite complicated it can always happen that certain elisp commands do not behave as expected on certain builds, causing all cases of issues with spacemacs packages.

To cut a long story short there is no clear way to have a fully functional emacs ready on windows. You may end up with a build able to fulfil certain jobs but not all packages will work as expected. This comes from the fact that emacs is actually heavily based on linux only features and libraries.

From my experience running native emacs on windows from the gnu source is very slow and only works for basic packages. Running emacs in cygwin will run all packages but it will be unstable and very slow.

From my experience the only full featured solution is to run emacs in a linux docker container forwarding your screen to a local xserver running from cygwin.

You can find the official container solution in `layers/+distribution/spacemacs-docker` or you can use one of the many user container solutions out there i.e. [here](https://hub.docker.com/r/smile13241324/spacemacs-installerandconfig/builds/) is mine using ssh-x for safe screen transfer.

**Comment by alexanderchiu** [comment]
For what it's worth, I was getting the same error using git bash:

> '/c/Users/${user}/emacs/bin/c:/Users/${user}/.emacs.d/elpa/gnupg/pubring.kbx': No such file or directory gpg: Signature made <Current datetime> gpg: Using DSA key <Key> gpg: Can't check signature: No public key

I managed to get around the issue by explicitly creating a HOME environment variable and using cmd.

**Comment by jvrdev** [comment]
Try the latest 64-bit one at http://ftp.snt.utwente.nl/pub/software/gnu/emacs/windows/emacs-26/

**Comment by velxundussa** [comment]
Leaving this here, mostly in case someone googles and gets the same issue:

the most compatible and hassle-free way I was able to find:

- Install Windows Subsystem for Linux: https://docs.microsoft.com/en-us/windows/wsl/install-win10
- In your Linux layer, ensure to `export DISPLAY=localhost:0.0` (I put mine in my .bashrc file)
- Install an X server ( I use https://sourceforge.net/projects/vcxsrv/ )

Then start emacs from a Linux prompt, you'll get an actual X powered emacs.

You should install the spacemacs repo in your ~/ of your Linux instance.

This comes with the added benefit of perfect compatibility for all Unix-oriented features, while still retaining access to your windows drives under /mnt/<drive_letter>

I'm not sure this should be the "official" way of doing things, but having it written here cannot hurt!

**Comment by sdwolfz** [comment]
@velxundussa do you think you can add those instructions to the Spacemacs Wiki (with as many details as you can)? Seems usefull for may things that people might want to run.

**Comment by liarchgh** [comment]
I use scoop to install emacs in win10 and also have this error.
Its [script](https://github.com/lukesampson/scoop-extras/blob/master/bucket/emacs.json) to install emacs.
It download emacs zip from [here](https://ftpmirror.gnu.org/gnu/emacs/windows/emacs-27/emacs-27.1-x86_64.zip).
