### ISSUE TITLE
clangd (8.0.0) support

### ISSUE THREAD

**Issue by sunlin7** [syl20bnr/spacemacs#12084]
The clangd-8.0.0 release with llvm-8.0.0, and it seems clangd is ready for find-reference and goto-definition.
Full features are list in
[clangd Features](http://releases.llvm.org/8.0.0/tools/clang/tools/extra/docs/clangd/Features.html).
Can any one add clangd to be a candidate of c-c++-backend please?

**Comment by yyoncho** [comment]
@sunlin7 if you set the backend to lsp-cquery but you do not have cquery lsp will pick up clangd language server.

**Comment by sunlin7** [comment]
@yyoncho Thank you for your information, I'll try it in my local, then update my result.

**Comment by sunlin7** [comment]
@yyoncho It NOT work for me, and it seems `clangd` always removed when init `lsp-cquery` with remhash.
There is a new c-c++-backend for clangd maybe more reasonable.

**Comment by yyoncho** [comment]
@sunlin7 - yeah, you are right - there is one remhash that is removing the client. I agree with you that we need a fix in spacemacs what I am suggesting is temporary workaround so you could use clangd in spacemacs until the fix is in. 

If you do that:

```
(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection
                                   'lsp-clients--clangd-command)
                  :major-modes '(c-mode c++-mode objc-mode)
                  :priority 1
                  :server-id 'clangd8))
```

lsp layer will pick clangd in case `lsp-clients-clangd-executable` is on the path. 

The code above regiters clangd with highest priority and with different name to avoid the remhash.

**Comment by sunlin7** [comment]
@yyoncho The code clip in your last comment work like a charm. 
Thank you so much.
Look forward it be in the official release.

**Comment by kvaneesh** [comment]
I guess we need proper clangd support in spacemacs c-c++ layer.  ie, we should be able to say 
c-c++-lsp-backed 'lsp-clangd and we should disable those ccls/cquery based extra commands when the backend is clangd.
