### ISSUE TITLE
how to show hint that one buffer has changed in spacemacs's status bar ?

### ISSUE THREAD

**Issue by qbai** [syl20bnr/spacemacs#12083]
how to show hint that one buffer has changed in spacemacs's status bar ?

**Comment by duianto** [comment]
@qbai You got the answer from `@markryall` in the gitter chat yesterday: 
>do you mean when there are unsaved changes? I see a '-' change to a '*' in that situation
(and then back to '-' after save)

https://gitter.im/syl20bnr/spacemacs?at=5c9342d6a21ce51a2096de44

Other modeline themes use other methods of indicating a modified buffer, for example:

The doom-modeline shows a modified buffers filename/path with red text. If your on the Spacemacs `develop` branch, then you can switch to the doom modeline theme by changing the 
`dotspacemacs-mode-line-theme` variable in you `.spacemacs` to:
```
   dotspacemacs-mode-line-theme '(doom)
```

Here's the repository page for the `doom-modeline` package: https://github.com/seagle0128/doom-modeline


And here's something to think about in the future.

When you ask a question somewhere. If you get the answer somewhere else, then it's helpful to post the answer everywhere that you've asked the question, so that when someone else wonders the same thing and they find your question, they'll also get the answer.

You can close this issue, since it seems like it has been resolved.
