### ISSUE TITLE
Unexpected transient directory blocking spacemacs update

### ISSUE THREAD

**Issue by zabbal** [syl20bnr/spacemacs#12128]
#### Description :octocat:
There's 'transient' directory in spacemacs folder (symlinked to .emacs.d) with single 'history.el' file. This makes spacemacs directory unclean (because it's not mentioned in .gitignore) and prevents spacemacs from updating. Removing it is of no use because it's recreated again after some time.

#### Reproduction guide :beetle:
- Start Spacemacs
- Do something: nothing special was done, just some init.el editing because it's afresh spacemacs install
- Quit Spacemacs and run 'git status'

*Observed behaviour:* :eyes: :broken_heart:
The 'transient/history.el' with 'nil' string inside is created in '.emacs.d'

*Expected behaviour:* :heart: :smile:
The '.emacs.d' should stay clean, all the files should appear in .spacemacs.d

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git github markdown jabber semantic ibuffer mu4e emoji c-c++ csv emacs-lisp ess go graphviz haskell scala shell-scripts org themes-megapack command-log finance pandoc pdf-tools restclient systemd search-engine
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by duianto** [comment]
This has been fixed on the develop branch: 

[Transient and magit-svn fixes](https://github.com/syl20bnr/spacemacs/commit/b364cd3c61f1221ca7433e1f4951052205852b04)
- magit-svn-popup renamed to magit-svn (more fallout of Transient)
- more reliable placement of Transient cache files

**Comment by zabbal** [comment]
Great to know. Shall I close this ticket or wait till it reaches master?

**Comment by duianto** [comment]
Sure.
You can also switch to the develop branch. Just make a backup of your current setup, then you'll be able to easily switch back.

You don't have to update often, some people don't update for months when everything is working for them.

The latest 3 or 4 breaking issues over the last few years, have occurred on both the master and develop branch, because an upstream package changed something. But the fix is applied sooner to the develop branch.

There is work being done for the master branch to use spacelpa (a mirror of the packages). Then Spacemacs won't be effected by a breaking upstream package update.

**Comment by yuhan0** [comment]
@duianto It would also be good to tag these and other such issues with the `Fixed in develop` tag, so they can be easily identified and closed all at once when the new release comes out :) 

There are currently 183 issues under that tag and at least few dozen more that were never tagged. 
(I'd be happy to help but it looks like only maintainers can edit issue tags.)

**Comment by duianto** [comment]
@yuhan0 Good suggestion. Thanks.

**Comment by zabbal** [comment]
> There are currently 183 issues under that tag and at least few dozen more that were never tagged.

Out of curiosity, is there some sort of guideline like "we make new release after 200 fixed-in-development bugs" or perhaps a rough roadmap to guesstimate next release time more precise than "when it's ready"?

**Comment by duianto** [comment]
There's no release time specified. The release notes preparation was recently finished: 
Help needed to prepare the 0.300 release #11741
so it's probably getting closer.

**Comment by monga** [comment]
As a temporary workaround for the stable release I added `transient` to my `.git/info/exclude`.

**Comment by zabbal** [comment]
The issue is fixed in dev branch according to comments but I think it's premature to close it before there is an actual release which contains the fix.
