### ISSUE TITLE
All babel block key commands missing in spacemacs?

### ISSUE THREAD

**Issue by vlurgio** [syl20bnr/spacemacs#12187]
Just downloaded latest spacemacs and all the [SPC m b _] commands aren't showing up in org mode did these change in code but not the documentation?

**Comment by duianto** [comment]
When posting an issue, it helps if you post your system info.

Press `SPC h d s` in Spacemacs, then your system info is copied to your clipboard.

If your on the `develop` branch, then these that have been made to the `org` layer: https://github.com/syl20bnr/spacemacs/blob/develop/CHANGELOG.develop#org

On the `develop` branch.
`SPC m b` shows lots of `org-babel-*` bindings, but there's no entry for `_`.

Since you mentioned block you might be referring to for example:
```
#+begin_src 
#+end_src
```
Those are under `SPC m i b`, which calls: `org-insert-structure-template`
which opens an `*Org Select*` buffer with these options:
>a | ‘#+BEGIN_EXPORT ascii’ … ‘#+END_EXPORT’
c | ‘#+BEGIN_CENTER’ … ‘#+END_CENTER’
C | ‘#+BEGIN_COMMENT’ … ‘#+END_COMMENT’
e | ‘#+BEGIN_EXAMPLE’ … ‘#+END_EXAMPLE’
E | ‘#+BEGIN_EXPORT’ … ‘#+END_EXPORT’
h | ‘#+BEGIN_EXPORT html’ … ‘#+END_EXPORT’
l | ‘#+BEGIN_EXPORT latex’ … ‘#+END_EXPORT’
q | ‘#+BEGIN_QUOTE’ … ‘#+END_QUOTE’
s | ‘#+BEGIN_SRC’ … ‘#+END_SRC’
v | ‘#+BEGIN_VERSE’ … ‘#+END_VERSE’

I found that list here: https://orgmode.org/manual/Structure-Templates.html

The org select buffer shows the same options, they are just formatted differently.
