### ISSUE TITLE
recentf "Warning (emacs): recentf mode: Wrong type argument: hash-table-p, nil"

### ISSUE THREAD

**Issue by zxcvbn97** [syl20bnr/spacemacs#12258]
Spacemacs prints this message everytime I open it.

Warning (emacs): recentf mode: Wrong type argument: hash-table-p, nil
Using spacemacs development branch.
Emacs 26.2 on MacosX

**Comment by dominiquedevriese** [comment]
I have the exact same problem.

Emacs 26.1 on Debian

**Comment by duianto** [comment]
Make a backup by renaming `recentf` in `~/.emacs.d/.cache/` and restart Spacemacs to create a new one.

If it works, compare them to see what was broken.

**Comment by dominiquedevriese** [comment]
Thanks for the tip.  The problem went away after I did the following:
* stop emacs
* rename recentf to recentf.backup
* starting emacs
* write a random test file using emacs (so that it generates a new recentf)
* stop emacs
* catting the contents of recentf.backup back over the new recentf
* restarting emacs

Fingers crossed that it doesn't come back...

Thanks!
