### ISSUE TITLE
helm-show-kill-ring does not replace current selection

### ISSUE THREAD

**Issue by MarcoIeni** [syl20bnr/spacemacs#12328]
#### Description :octocat:
helm-show-kill-ring does not replace current selection

#### Reproduction guide :beetle:
- Start Emacs
- yank something
- select a text in visual mode
- run helm-show-kill-ring and select an entry

*Observed behaviour:* :eyes: :broken_heart:
selected text is not replaced, but the entry from the kill ring is simply pasted after the cursor

*Expected behaviour:* :heart: :smile:
selected text is replaced with the entry from the kill ring

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. bf75b9d89)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html python markdown javascript vimscript epub
      (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-sort-by-usage t auto-completion-private-snippets-directory nil)
      (syntax-checking :variables syntax-checking-enable-tooltips nil)
      (c-c++ :variables c-c++-enable-clang-support t c-c++-backend 'rtags c-c++-default-mode-for-headers 'c++-mode)
      gtags helm emacs-lisp
      (git :variables git-magit-status-fullscreen nil magit-diff-refine-hunk 'all)
      java markdown multiple-cursors neotree
      (org :variables org-enable-bootstrap-support t)
      shell semantic cscope spell-checking
      (version-control :variables version-control-diff-side 'left version-control-diff-tool 'diff-hl))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
This seems to be unrelated to Spacemacs, because it happens with:
- `emacs -Q` 
- add melpa to the packages-archives:
```
(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  (when no-ssl
    (warn "\
Your version of Emacs does not support SSL connections,
which is unsafe because it allows man-in-the-middle attacks.
There are two things you can do about this warning:
1. Install an Emacs version that does support SSL and be safe.
2. Remove this warning from your init file so you won't see it again."))
  ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives (cons "gnu" (concat proto "://elpa.gnu.org/packages/")))))
(package-initialize)
```
source: http://melpa.org/#/getting-started
- `M-x` `eval-buffer`
- `M-x` `package-install` `helm`
when it's done installing, follow this issues reproduction steps, the entry gets pasted before the cursor.

**Comment by MarcoIeni** [comment]
If delete-selection-mode is enabled then it works as expected.
Do you think it is a good idea to create a spacemacs function that enables this mode before calling helm-show-kill-ring and before exiting the function disables the mode again if it was not enabled at the beginning?

**Comment by duianto** [comment]
There seems to be an issue when the selection end is at the end of a line.

With this example:
```
    (defun spacemacs/helm-show-kill-ring ()
      (interactive)
      (let ((delete-selection-mode t))
        (helm-show-kill-ring)))

    (spacemacs||set-helm-key "ry" spacemacs/helm-show-kill-ring)
```

After evaluating the code above.
Type: `abc`
Delete it to the kill-ring: `diw`
Type: `123`
Select the `3` with `v`
After inserting from the helm kill-ring `SPC r y` with `RET`
it ends up with: `1abc2`

The cursor seems to move back one character before inserting the kill-ring item.

Because with `23` selected it ends up with `abc1`.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 155487341)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm markdown multiple-cursors
            (org :variables org-enable-org-journal-support t)
            spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by MarcoIeni** [comment]
Yes, I was able to reproduce your behavior.
Of course this also happens if you don't evaluate yuor function and you just use helm-show-kill-ring with delete-selection-mode enabled.

I think we should open an issue on [https://github.com/emacs-helm/helm](helm).

**Comment by MarcoIeni** [comment]
I also noticed that the selection is not replaced also if from the menu bar you go to `Edit -> Paste from Kill menu`. 
While if you use `Edit -> Paste` the text is replaced.
This is not helm related I think.

**Comment by duianto** [comment]
It might just be an issue in Spacemacs, because it works as expected when starting `emacs -q` with evil and helm loaded.

**Comment by MarcoIeni** [comment]
I did some testing and there are still issues with `helm-show-kill-ring`

**Comment by lebensterben** [comment]
I just tested on latest develop branch. And I'm not able to reproduce the bug.

First, start a new buffer, for example a scratch buff with `SPC b s`.
Then, insert some text, e.g.
```txt
foo
bar
baz
```
I deleted the third line with `dd`, then it looks like
```txt
foo
bar
```

With `delete-selection-mode` enabled. Selecting the first line, i.e. `foo`, and then press `SPC r y` to run `lazy-helm/helm-show-kill-ring` and select the entry containing `baz`, it works as expected. ( it added a trailing new line because `dd` implicitly deleted a newline)
```txt
baz

bar
```

**Comment by lebensterben** [comment]
@MarcoIeni 
Please verify whether this is still an issue.

**Comment by MarcoIeni** [comment]
I was able to reproduce [this](https://github.com/syl20bnr/spacemacs/issues/12328#issue-445738758) with delete-selection-mode disabled.

I was also able to reproduce [this](https://github.com/syl20bnr/spacemacs/issues/12328#issuecomment-493743956).

**Comment by lebensterben** [comment]
@MarcoIeni 
I know that you were able to reproduce it before.
But the question is are you still able to reproduce it now.

**Comment by MarcoIeni** [comment]
Yes, sorry, that's what I meant. I just reproduced the issues yesterday again.

**Comment by lebensterben** [comment]
@MarcoIeni 
Can you repeat what I did here
https://github.com/syl20bnr/spacemacs/issues/12328#issuecomment-920360214

And let me know from which step things doesn't work properly.

**Comment by MarcoIeni** [comment]
What you did works for me. But the comments I linked are still valid.

**Comment by lebensterben** [comment]
> I was able to reproduce [this](https://github.com/syl20bnr/spacemacs/issues/12328#issue-445738758) with delete-selection-mode disabled.

This is not a bug.

> I was also able to reproduce [this](https://github.com/syl20bnr/spacemacs/issues/12328#issuecomment-493743956).

This one is and I can reproduce it.

**Comment by MarcoIeni** [comment]
Ok, we can close this if you want
