### ISSUE TITLE
Allow local theme to be placed in .spacemacs.d/local

### ISSUE THREAD

**Issue by rgb-24bit** [syl20bnr/spacemacs#12333]
I refer to the way in #7373 to put the local theme in `~/.emacs.d/private/local`, and it succeeded.

But I would like to be able to put the theme in the` ~/.spacemacs.d/local` directory. Is there any way to do this?

If I set `custom-theme-load-path`, then the theme will be downloaded from melpa, which is not what I want.

**Comment by rgb-24bit** [comment]
I tried to use the local theme as a package of a layer, it succeeded, but will load the spacemacs theme at startup, can i avoid this behavior?

![](https://user-images.githubusercontent.com/26481411/57981735-4be80980-7a6e-11e9-9f38-3fb3b3a1c5a8.gif)

**Comment by duianto** [comment]
This seems to work:
- Copy the url to a theme, for example:
https://github.com/WJCFerguson/emacs-faff-theme
- Clone it's repository: `SPC g c`
- At the prompt: `Clone from [u]rl or name, [p]ath, or [l]ocal url`
Press: `u`
- At the prompt: `Clone from url or name:`
paste the url: `C-y`
- Choose the location: `~/.spacemacs.d/local/emacs-faff-theme`
- In the `dotspacemacs/user-init` section of `~/.spacemacs/init.el` (or `~/.spacemacs`)
Add:
```elisp
(add-to-list 'custom-theme-load-path "~/.spacemacs.d/local/emacs-faff-theme/")
```
- In `dotspacemacs-themes` add the following as the first item:
```elisp
(faff :location local)
```

#### Multiple themes in one repository
It also works with a themes repository that contains multiple themes.
For example: https://github.com/hlissner/emacs-doom-themes

The path needs to be added to the `load-path` instead of to the `custom-theme-load-path` (as we did in the single theme repository, above).

And it needs the `require` line from the installation instructions:
https://github.com/hlissner/emacs-doom-themes#install

In `dotspacemacs/user-init`:
```elisp
  (add-to-list 'load-path "~/.spacemacs.d/local/emacs-doom-themes/")
  (require 'doom-themes)
```
In `dotspacemacs-themes`:
```elisp
(doom-city-lights :location local)
```

#### Notes
It also works when there is a doom-themes package in:
`~/.emacs.d/elpa/26.3/develop/doom-themes-20190929.505/`
(it's part of the `themes-megapack` layer)
I changed the background color of the local version to green, and with the settings above, the local version still loads on startup.

If: `doom-city-lights` or `faff` is used instead of:
`(doom-city-lights :location local)` or `(faff :location local)`
in `dotspacemacs-themes`, then the melpa package is downloaded on startup, but the local version still loads, as long as both the load-path and require lines (for `doom-themes`) or the `custom-theme-load-path` (for the `faff` theme) are in `dotspacemacs/user-init`.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. fdd38eec9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion
            (dart :variables dart-server-sdk-path "c:/src/flutter/bin/cache/dart-sdk/" dart-server-enable-analysis-server t)
            emacs-lisp ess git helm html
            (lsp :variables lsp-clients-dart-server-command "~/AppData/Roaming/Pub/Cache/bin/dart_language_server" lsp-dart-analysis-sdk-dir "c:/src/flutter/bin/cache/dart-sdk/")
            multiple-cursors org php spell-checking syntax-checking treemacs version-control vinegar)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by rgb-24bit** [comment]
I can refer to the [solution](https://github.com/syl20bnr/spacemacs/issues/7373#issuecomment-276867188) here to create a repository on github to save my own theme.

This can solve my problem. :smile:
