### ISSUE TITLE
Deer travel popup changes to Helm

### ISSUE THREAD

**Issue by polothy** [syl20bnr/spacemacs#12363]
#### Description :octocat:

While in `ranger` or Ranger's `deer` the `f` key will display a different travel interface depending on if I have used `SPC f f` (Helm Find Files) yet.

_Might_ be related to https://github.com/syl20bnr/spacemacs/issues/7645 which may have been resolved in https://github.com/hlissner/evil-snipe/issues/48#issuecomment-328877034 but likely something has to be changed in Spacemacs for it to work.

#### Reproduction guide :beetle:
- Start Emacs
- Go to `deer`: `SPC a d`
- Press `f` - observe popup
- Quit
- Activate Helm Find Files, `SPC f f`
- Quit
- Go to `deer`: `SPC a d`
- Press `f` - observe popup, it is now Helm File Completions

*Observed behaviour:* :eyes: :broken_heart:

The `ranger` travel popup changes to Helm File Completions.

*Expected behaviour:* :heart: :smile:

The `ranger` travel popup should not change to Helm File Completions.

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8671362aa)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(php html csv deft docker rust groovy lsp yaml
     (go :variables go-use-golangci-lint t godoc-at-point-function 'godoc-gogetdoc gofmt-command "goimports" go-format-before-save t go-tab-width 4)
     helm
     (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-help-tooltip t)
     emacs-lisp git markdown multiple-cursors treemacs
     (org :variables org-want-todo-bindings t)
     osx
     (terraform :variables terraform-auto-format-on-save t)
     (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/usr/local/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
     (ranger :variables ranger-show-preview t ranger-override-dired-mode t)
     (spell-checking :variables spell-checking-enable-by-default nil)
     syntax-checking version-control)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by polothy** [comment]
If it matters, I have this config too:

```lisp
(defun dotspacemacs/user-config ()
  ;; Tell ranger to do fully formatted previews.
  (setq ranger-show-literal nil)
  ;; Tell emacs to use ranger over dired.
  (ranger-override-dired-mode t)
  )
```

**Comment by polothy** [comment]
I'm starting to wonder if this is expected behavior and I'm only seeing this because Helm is lazy loaded?

**Comment by duianto** [comment]
You are correct, helm hasn't been loaded yet.

In a `deer` buffer, `f` calls `(ranger-travel)`
https://github.com/ralesi/ranger.el/blob/c3f349e52f5c50926dc0f285c97676934f50bc18/ranger.el#L1552
which checks if helm is a feature `(featurep 'helm)` and it returns `nil` before a helm buffer has been opened. Then it checks if `ivy` is a feature, and if it also returns `nil`, then it shows an ido prompt.

After opening a helm buffer, for example `SPC SPC`, then helm is a feature and `f` shows a helm prompt.
And it continues to show the helm prompt until Spacemacs is restarted.

>Expected behaviour: ❤️ 😄
>
> The ranger travel popup should not change to Helm File Completions.

If the expectation is to open the ido prompt by default, then you might have to open an upstream issue in the ranger repository, suggesting that they include a variable to always use the ido prompt.

Because currently `ranger-travel` uses the prompts in this order if they have been loaded:
- `helm`
- `ivy` (if helm hasn't been loaded)
- `ido` (if neither helm nor ivy has been loaded)

In Spacemacs the expected behavior probably is to use the current completion layer (`helm` or `ivy`) everywhere.

**Comment by polothy** [comment]
Hey! Thanks so much for the detailed breakdown, really appreciated! I think I was just surprised by the ido interface and then it going away later in the same session. Going to close since things are working as expected.

**Comment by duianto** [comment]
You were right, it is surprising that the prompt changes, and that's not how it's supposed to work.

I've opened a PR with a possible fix:
[ranger] load helm before ranger/deer #12372

It takes a couple of seconds (at least in windows) before ranger opens the first time after starting Spacemacs, because it loads helm, but the rest of the session it opens instantly.

**Comment by smile13241324** [comment]
@polothy say I have just tried to reproduce your issue to merge @duianto fix but I cannot reproduce the issue on current develop. Everytime I run ranger I am getting the helm prompt, can you still reproduce it on develop?

**Comment by polothy** [comment]
Just updated to latest in develop branch, Emacs 26.3 and all plugins.  Still could reproduce it.

Are you doing quitting emacs, starting emacs and then from the startup screen doing `SPC a d` and then pushing `f`?

**Comment by polothy** [comment]
Updated, reverted duianto's changes,  reproduced problem.
Reset branch to restore duianto's changes, problem fixed!!! ❤️ 

Thanks so much for taking time to address this! 🍺 

I have never used Ivy... is that as simple as changing `helm` to `ivy` in layers?

**Comment by smile13241324** [comment]
@polothy yes just deactivate `helm` layer and load `ivy` layer, the rest of the configurations are handled by spacemacs and the various layers.

**Comment by polothy** [comment]
Looks like it is the same issue when using Ivy.
