### ISSUE TITLE
Key binding not working for `enh-ruby-mode`

### ISSUE THREAD

**Issue by LilyMGoh** [syl20bnr/spacemacs#12394]
I have my custom key bindings with `global-set-key` which work for all the modes that I've worked with except the `enh-ruby-mode`. I have also tried all the possible ways of [key bindings](http://develop.spacemacs.org/doc/DOCUMENTATION.html#binding-keys) but none of them seems to be working.

**Comment by duianto** [comment]
This might be what your looking for:
https://stackoverflow.com/questions/5500035/set-custom-keybinding-for-specific-emacs-mode

The accepted answer suggests:
```elisp
   (eval-after-load 'latex 
                    '(define-key LaTeX-mode-map [(tab)] 'outline-cycle))
```

The next answer suggests using a hook:
```elisp
(add-hook 'LaTeX-mode-hook
          (lambda () (local-set-key (kbd "C-0") #'run-latexmk)))
```

The Emacs manual might also be helpful:
https://www.gnu.org/software/emacs/manual/html_node/efaq/Binding-keys-to-commands.html

**Comment by LilyMGoh** [comment]
@duianto 

Thank you for the help! I put both at the beginning of `user-config` and it still doesn't seem to be working.

```emacs-lisp
  (add-hook 'enh-ruby-mode-hook
            (lambda ()
              (local-set-key (kbd "C-;") #'comment-line)))
  (eval-after-load 'enh-ruby
    '(define-key enh-ruby-mode-map (kbd "C-;") 'comment-line))
```

Did I miss anything?

**Comment by duianto** [comment]
This seems to work:
```elisp
    (with-eval-after-load 'ruby-tools
      (define-key ruby-tools-mode-map (kbd "C-;") 'comment-line))
```

#### Discovery process:
The help information for the key `C-;` can be viewed with: `SPC h d k C-;` 
(or with the default Emacs key binding `C-h k C-;`):
>C-; runs the command ruby-tools-clear-string (found in ruby-tools-mode-map),
which is an interactive compiled Lisp function in ‘ruby-tools.el’.
> 
> It is bound to C-;.
> 
> (ruby-tools-clear-string)
> 
> Clear string at point.

specifically `(found in ruby-tools-mode-map)`.

When `eval-after-load` is used, then Spacemacs shows this message on startup:
>Error in dotspacemacs/user-config: Symbol’s value as variable is void: ruby-tools-mode-map

Because `ruby` and a lot of of other things are lazy loaded (they load when they are called).

Similar lazy loading issues have been reported before and the solution was to use `with-eval-after-load`.

And after `with-eval-after-load`
`'enh-ruby` didn't work, neither did `'ruby`, but `'ruby-tools` works.

**Comment by LilyMGoh** [comment]
@duianto That works!

For future reference, how do I know that `C-;` is defined in `ruby-tools` and not  `enh-ruby` or `ruby`?

I really appreciate your help and thorough explanation. Thank you so much!

**Comment by duianto** [comment]
It was just a guess since the other once didn't work and the mode map where `C-;` was defined started with `ruby-tools`, I just tried it and it happened to work.
