### ISSUE TITLE
`spacemacs/copy-file-path` no longer prints file path to minibuffer

### ISSUE THREAD

**Issue by actionshrimp** [syl20bnr/spacemacs#12426]
#### Description :octocat:

`SPC f y y` used to print the file path which was very useful for finding out where you were (as suggested in this issue https://github.com/syl20bnr/spacemacs/issues/2140).

This stopped working, and it seems that `kill-new` inside the spacemacs/copy-file-path function no longer returns the killed string and instead seems to return 0, which is what gets printed (perhaps due to an emacs version upgrade)?

I was seeing this on emacs 26.1_1 (from homebrew), so upgraded to 26.2 to see if the issue persisted and it does.

#### Reproduction guide :beetle:
- Start Emacs
- navigate to any file
- press `SPC f y y`

*Observed behaviour:* :eyes: :broken_heart:
The string "0" appears in the minibuffer.

*Expected behaviour:* :heart: :smile:
The file path should appear in the minibuffer.

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 51b04beb2)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((osx :variables osx-right-command-as 'meta)
 tmux my-evil auto-completion helm emacs-lisp rust treemacs git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (syntax-checking :variables syntax-checking-enable-tooltips nil)
 (version-control :variables version-control-diff-tool 'diff-hl)
 spell-checking javascript
 (node :variables node-add-modules-path t)
 shell-scripts html sql
 (elm :variables elm-format-on-save t elm-sort-imports-on-save t)
 yaml ruby
 (python :variables python-backend 'anaconda)
 ocaml ipython-notebook docker markdown terraform my-clojure my-evil-lisp my-sql my-js-json my-haskell my-python lsp reason imandra xclipboard)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB MODULES THREADS

#### Backtrace :paw_prints:
```

```

**Comment by duianto** [comment]
`SPC f y y` returns the current files path for me in both Ubuntu 18.04.02 and Windows 10 Version 1803 both in the Gui and terminal/windows command prompt.

On the latest develop branch with updated packages.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 51b04beb2)
- Graphic display: t (and nil)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm markdown multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 51b04beb2)
- Graphic display: nil (and t)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm markdown multiple-cursors org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by antonalekseev** [comment]
`SPC f y y` works as expected for me on macOS with clean configuration:

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9aaef2a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs osx)
```
- System configuration features: RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP

But doesn't (displays `nil` in minibuffer, kills nothing) with my regular setup:

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b5027f8f2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(aaa-lispyville ansible
                (auto-completion :variables spacemacs-default-company-backends
                                 '(company-yasnippet
                                   (company-gtags company-etags company-keywords)
                                   company-files company-dabbrev)
                                 auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip 'manual auto-completion-enable-sort-by-usage t)
                bm common-lisp csv dap
                (dash :variables helm-dash-docset-newpath
                      (concat
                       (getenv "HOME")
                       "/Library/Application Support/Dash/DocSets/"))
                docker emacs-lisp fzf
                (gtags :variables gtags-enable-by-default nil)
                git github
                (go :variables go-tab-width 4 godoc-at-point-function 'godoc-gogetdoc go-use-gometalinter t)
                (html :variables web-fmt-tool 'prettier)
                aaa-ipython-notebook ivy
                (json :variables json-fmt-tool 'prettier)
                (lsp :variables lsp-ui-sideline-enable nil lsp-ui-doc-enable nil lsp-ui-flycheck-enable nil lsp-auto-guess-root t)
                (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
                neotree
                (javascript :variables javascript-fmt-tool 'prettier javascript-backend 'lsp js2-basic-offset 2 js-indent-level 2)
                (org :variables org-confirm-babel-evaluate nil org-bullets-bullet-list
                     '("■" "◆" "▲" "▶"))
                (python :variables python-backend 'lsp python-test-runner 'pytest python-formatter 'black)
                racket restclient aaa-rmsbolt
                (shell :variables shell-default-shell 'eshell shell-default-term-shell "zsh")
                (syntax-checking :variables syntax-checking-enable-tooltips nil)
                theming
                (version-control :variables version-control-diff-tool 'diff-hl)
                yaml)
```
- System configuration features: RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP

In my case the culprit was variable `select-enable-clipboard` set to `nil` in my `init.el` (I don't like contents of `kill-ring` ending in my clipboard, thus prefer to copy to clipboard register explicitly). After setting it back to `t`, `SPC f y y` returned to its expected behaviour.

**Comment by duianto** [comment]
Confirmed

Setting `select-enable-clipboard` to `nil`, causes all ten key bindings under the prefix: `SPC f y`
to show `nil` in the minibuffer.

As you said, it's from the `kill-new` command, because calling it directly:
```elisp
(kill-new "test")
```
returns `nil`.

The issue is caused by the `spacemacs/(projectile-)copy-*` commands calling:
https://github.com/syl20bnr/spacemacs/blob/47f83609d5c23b2c5f4dc82a0fed3cae356117cf/layers/%2Bspacemacs/spacemacs-defaults/funcs.el#L586

Six of the functions are in that file, and four projectile functions are in this file:
https://github.com/syl20bnr/spacemacs/blob/47f83609d5c23b2c5f4dc82a0fed3cae356117cf/layers/%2Bspacemacs/spacemacs-project/funcs.el#L69

**Comment by duianto** [comment]
A possible solution that seems to work, is to split the `message` and `kill-new` commands apart:

Before:
```elisp
      (message "%s" (kill-new directory-path))
```
After:
```elisp
      (progn
        (kill-new directory-path)
        (message "%s" directory-path))
```

**Comment by duianto** [comment]
PR submitted:
Fix copied dir not in minibuffer, clipboard disabled #12435

**Comment by smile13241324** [comment]
PR merged and tested locally. I could not longer reproduce the issue on linux. @actionshrimp please have a look and if it is ok, close the ticket.

Thanks.

**Comment by actionshrimp** [comment]
Works great, thanks!

**Comment by mmcnl** [comment]
Does anyone know a way to get `spacemacs/copy-file-path` to also copy to the system (eg macOS) clipboard?

**Comment by smile13241324** [comment]
@mmcnl this should already happen if you running emacs in gui mode at least. I am on linux however so I cannot test this on apple. Maybe someone with an apple background can help here.

**Comment by mmcnl** [comment]
@smile13241324 Ah, thanks for the reply. I'm using `simpleclip-mode` so I think that overrode it. I ended up just rebinding `fyy` to a function that manually adds it to both kill ring and system clipboard.
