### ISSUE TITLE
strange behaviour with helm when graphical frame is large enough on windows

### ISSUE THREAD

**Issue by mohkale** [syl20bnr/spacemacs#12421]
#### Description :octocat:
Okay, this is a weird problem and I haven't really encountered it before yesterday, but I've encountered it after:

* deleting my .spacemacs file.
* deleting my .emacs.d directory and then reinstalling spacemacs.
* deleting both my .spacemacs file and .emacs.d directory and then reinstalling spacemacs and running without my regular config.

so I think it's safe to say that it's either my emacs install that's broken or spacemacs.

##### The Problem
1. emacs helm popup (the window that shows up to give hints at the bottom of the screen after pressing space or space space or any incomplete keybinding) has a slight lag in which I can actually see my introductory spacemacs buffer horizontally split and then be replaced by the window. This only happens the first time I do it after starting the frame, any other attempt and it does not happen.
2. and more disconcertingly line numbers then show up in the spacemacs buffer. I've set dotspacemacs-line-numbers to 'relative but I don't think it's supposed to show up in the spacemacs buffer.

What should also be of note, is this only seems to happen if I do it after enlargening the frame I'm on by a certain amount. I'm not sure what this amount is, but making the frame as tall as my screen (1080p) and about half as wide (1920p / 2) seems to do the trick. If I do it at any smaller scale, I don't seem to have any problem, but the second it becomes large enough the above troubles creep in.

#### Reproduction guide :beetle:
- set dotspacemacs-line-numbers in your .spacemacs file to 'relative
- Start Emacs
- make your emacs full screen or large enough (1920/2p * 1080p) without using helm.
- use some key combination to make helm show up. I've been using \<space\> \<space\> \<escape\>.

*Observed behaviour:* :eyes: :broken_heart:
  * line numbers show up in introductory *spacemacs* buffer
  * slight lag in helm showing up, during which I can see a buffer split.

*Expected behaviour:* :heart: :smile:
  * no lag in buffer showing up.
  * line numbers also not showing up in spacemacs buffer

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 8c0b8c344)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python c-c++ helm emacs-lisp git markdown)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

#### Update
I just tried copying over my .spacemacs files to my laptop (running arch) and I haven't encountered this problem there at all. I think this means:
* This isn't a configuration issue on my part (hopefully)
* This is a problem on the windows OS (and maybe Mac OS).

**Comment by duianto** [comment]
I'm not seeing line numbers in the Spacemacs buffer on the Spacemacs `develop` branch, this might only be a `master` branch issue.
 
Probably because the `develop` branch uses the built-in Emacs 26 line numbers.

The Spacemacs buffer delay when opening helm is also visible on the `develop` branch.

This seems to be occurring because the Spacemacs home buffer needs to be redrawn when the Emacs width has changed.

This can seen every time helm is opened after resizing Emacs, either by dragging the left or right edges. Or if Emacs is maximized or unmaximized `SPC T M` before opening helm `SPC SPC`.

As you said the delay only happens the first time, probably because the Spacemacs buffer doesn't need to be regenerated to fit the Emacs frame again.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 17c4219d0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey colors emacs-lisp git helm markdown multiple-cursors org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by mohkale** [comment]
I've switched to using my own config and seeing as no-ones been able to reproduce (as of yet) I feel this issue can be closed down now.
