### ISSUE TITLE
Org mode leader keys aka "no previous search"

### ISSUE THREAD

**Issue by srgkoshelev** [syl20bnr/spacemacs#12447]
#### Description :octocat:
Org mode leader key are not working.
Pressing `,` gives `no previous search`
`SPC m` --> `SPC m is undefined`
Unfortunately, the issue is hard to reproduce as it is not consistent.
The usual root of deleting .emacs.d and re-downloading didn't help this time.
Usually the issue appears after an update/git pull --rebase.
Running `rm -v .emacs.d/elpa/26.2/develop/org*/*.elc` didn't help.

I'm heavily reliant on org-mode for work and this issue paralyzes it completely.

#### Reproduction guide :beetle:
- Start Emacs
- Open .org document
- Press `,` or `SPC m`

*Observed behaviour:* :eyes: :broken_heart:
`,` --> `no previous search`
`SPC m` --> `SPC m is undefined`

*Expected behaviour:* :heart: :smile:
Key bindings work.

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1554bdda9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp multiple-cursors treemacs finance python git org spell-checking)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by RCIIIcm** [comment]
What happens if you run org-mode? i.e. type SPC SPC org-mode RET

**Comment by srgkoshelev** [comment]
Thank you for your advice! The issue seems to have disappeared after ~4
full re-installations of spacemacs. I will try this next time the issue
comes up.

**Comment by RCIIIcm** [comment]
That's great. I came here because I had the same issue, and after searching the cryptic error message "(json-readtable-error 47)", it turned out to be related to Jupyter, bizarrely. I hadn't noticed it before, probably because I opened Emacs after activating a Python environment where Jupyter was installed. Installing Jupyter globally solved the problem for me.

Possibly related: #12070, #9941

**Comment by tamasgal** [comment]
I also get `"no previous search"` when I hit the leader key in org mode. Any news about this issue?

**Comment by srgkoshelev** [comment]
I haven't encountered the issue for a while, especially I have switched to the develop branch. My notes match my comment above - multiple reinstalls of spacemacs resolved the issue.

**Comment by tamasgal** [comment]
I am using the dev branch. Not sure how multiple installs would solve it, maybe it’s a sign that it is related to the layers which are installed asynchronously (are they?)...

**Comment by acwatkins** [comment]
Ran into this today when enabling the C++ layer. I tried moving the C++ layer around and it still happens.

**Comment by jonas-hagen** [comment]
For everyone landing here, not necessarily related to org-mode (but google seems to lead here anyways):

- The "no previous search" can be caused by errors happening in the mode activation
- Check the `*Messages*` buffer (`SPC b` -> `*Messages*`), look for errors
- Search for these errors, sometimes it is just a binary that is missing and has to be installed separately
- If applicable, file an issue for the specific layer
