### ISSUE TITLE
emacs 26.2.1 - with spacemacs

### ISSUE THREAD

**Issue by asteriosos** [syl20bnr/spacemacs#12449]
hi there,

i am using latest spacemacs on manjaro xfce with emacs 26.2.1 and got a little graphical issue.
is there a way to fix that ?

thank you.

![spacemacs](https://user-images.githubusercontent.com/44438259/59621906-8e196f00-9130-11e9-8ad1-c65c7be228a9.png)

**Comment by duianto** [comment]
There's an entry in the documentation for this issue, at the end of the font section:
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#font

>The special property :powerline-scale is Spacemacs specific and it is for quick tweaking of the mode-line height in order to avoid crappy rendering of the separators like on the following screenshot (default value is 1.1).

![](https://github.com/syl20bnr/spacemacs/raw/master/doc/img/crappy-powerline-separators.png)

It can be fixed by changing the `:powerline-scale` property in the existing `dotspacemacs-default-font` variable in your `.spacemacs` file:

```elisp
(setq-default dotspacemacs-default-font '("Source Code Pro"
                                          :size 13
                                          :weight normal
                                          :width normal
                                          :powerline-scale 1.1))
```

**Comment by asteriosos** [comment]
This fixed it for me. Thank you very much.
