### ISSUE TITLE
Tab Completion Crashes Eshell When multiple options present. Only effects Emacsclient. [Develop]

### ISSUE THREAD

**Issue by clayscode** [syl20bnr/spacemacs#12442]
#### Description :octocat:
Emacsclient crashes when using tab completion in Eshell

#### Reproduction guide :beetle:
- Start Emacs in Daemon Mode
- Start Emacsclient
- Launch Eshell
- Type a partial filepath and tab to autocomplete 

*Observed behaviour:* :eyes: :broken_heart:
- Emacsclient crashes

*Expected behaviour:* :heart: :smile:
- Tab should complete the statement and not crash Emacsclient

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 17c4219d0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv helm auto-completion better-defaults docker emacs-lisp git go
     (go :variables go-use-gometalinter t)
     (go :variables godoc-at-point-function 'godoc-gogetdoc)
     (go :variables go-tab-width 4)
     markdown multiple-cursors org python ipython-notebook
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     shell-scripts spell-checking syntax-checking vagrant version-control)
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by equwal** [comment]
I've reproduced this issue, and I get a core dump.
I've reproduced this issue, and I get a core dump.

#### Description :octocat:
Core dump from opening Eshell.

#### Reproduction guide :beetle:
- Start Emacs
- Run eshell
- ???
(once I crashed instantly, suggesting it might not be completion)
- Segfault
- Core dump

*Observed behaviour:*

Crash :1st_place_medal: , catch fire :fire: , burn , dump (:poop:).

*Expected behaviour:* :fire_engine: 
Do not crash.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 11d07d9c7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(evil-cleverparens evil-snipe boilerplate cursed init kmacro reader rectangle register slurp superparens timeclock auto-completion better-defaults c-c++ clojure common-lisp csv emacs-lisp erc finance floobits git github gnus graphviz gtags haskell helm html jabber markdown markdown org pandoc pdf-tools prodigy python ranger scheme search-engine shell shell-scripts spell-checking spotify syntax-checking systemd version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS PDUMPER LCMS2 GMP

**Comment by equwal** [comment]
Here are our shared packages:
```
Completion: helm
Layers:
auto-completion
better-defaults
csv
emacs-lisp
git
helm
markdown
org
python
shell-scripts
spell-checking
syntax-checking
version-control

System configuration features 
ACL
GLIB
GNUTLS
JPEG
LCMS2
LIBXML2
RSVG
THREADS
TIFF
TOOLKIT_SCROLL_BARS
ZLIB

**Comment by clayscode** [comment]
@equwal And that happens when you're using Emacsclient? Eshell and tab completions work fine with not running Emacs in daemon mode. Instead, it just pops open the tab completions in another window.

**Comment by equwal** [comment]
@clayscode I can't make it happen on demand, but it did happen a few times when opening eshell. It also messes up the unicode in the modeline.
