### ISSUE TITLE
deprecate ensime for lsp and metals

### ISSUE THREAD

**Issue by brettgilio** [syl20bnr/spacemacs#12462]
Since ensime is no longer maintained, and Scala is working on the in progress metals language server with official lsp-mode support I think we should move the Scala layer toward that.

**Comment by fabianhjr** [comment]
Merge request: #12234

**Comment by syl20bnr** [comment]
Let's move to Metals.

**Comment by htimur** [comment]
As Ensime is now encouraging to use metals on their website https://ensime.github.io, it's probably the way to go.

**Comment by Kazark** [comment]
What's the status of this? I see #12234 was merged, but the talks still refer to Ensime.

**Comment by liewhite** [comment]
@Kazark  It seems scala layer on develop branch  can use metals as backend.
Just add 
`(scala :variables scala-backend 'scala-metals)` to your dotspacemacs-configuration-layers.

**Comment by Kazark** [comment]
@liewhite thank you, will try it.

**Comment by Kazark** [comment]
I've got it up and running successfully. However, it seems that `SPC m s` (REPL commands) are unavailable with Metals. What's the recommended way to easily launch a Scala REPL (perhaps [Ammonite](https://github.com/zwild/ammonite-term-repl))? Currently I am launching a `*shell*` buffer and then just running `scala` or `amm`. That's not too onerous if I don't care to load the current buffer/region into the REPL, but I've just come to anticipate such a high level of polish and integration between all my tools in Spacemacs that it feels off. 😄 Recommendations?

**Comment by fabianhjr** [comment]
I guess it depends, at least from my end at my daily job if we want to load a REPL with production code we use `mill -i [project].repl` since it will take care to build and load everything (external and internal dependencies, the project, resources, etc) that would be an opinionated answer that only works if the project is already using mill as a build tool and it launches an ammonite shell anyways so it might be possible to write a script on top of ammonite.

**Comment by Kazark** [comment]
@fabianhjr Thanks for your response. I'm new to this job and to Scala; we use SBT; I am ignorant of Mill. Important to realize though that there are a bunch of different angles on this.

**Comment by Kazark** [comment]
I see [Metals 0.8.0](https://scalameta.org/metals/blog/2020/01/10/cobalt.html) has been released, with some desirable new features, like "import missing symbol" and "completion to add all abstract members". Is it reasonable to think that if I get a new `metals-emacs` binary, this will just work because of LSP? Or is an update potentially needed on the Elisp side?

**Comment by pismute** [comment]
Hi, ensime is gone from MELPA.

**Comment by brunosmmm** [comment]
I think that the last comment must be referring to an issue that I have been encountering since updating my spacemacs installation to a newer commit in the develop branch (currently running 58279f89ead4dceb): even though I have metals selected as the backend, spacemacs still tries to install ensime at startup, and fails because the package is not available anymore on MELPA. This leads to an annoying increase in startup time. Anyone else seeing this?

**Comment by Kazark** [comment]
@brunosmmm same here.

**Comment by Kazark** [comment]
@brunosmmm thanks for the note on how to exclude the error for now. Wish I had better context on how to fix this; I might take a shot at it.

**Comment by smile13241324** [comment]
@brunosmmm I have made a fix for this, would you mind having a look if this solves the issue.

Btw the default for the scala layer is now metals. The documentation warns new users about using ensime now. Would be great if you could quickly double check the layer for any other issues with using metals.

If all works please close this issue.

**Comment by brunosmmm** [comment]
@smile13241324 This fixes emacs wanting to install ensime at startup, however, this is quite a harsh breaking change. Since I pulled from the repository and didn't remove the backend variable for the scala layer in my .spacemacs, I opened up spacemacs with the old configuration and it was unusable.

**Comment by smile13241324** [comment]
Hmmm you are right I have restored the default backend for now so that old
configs still work however the documentation clearly states to use metal
instead.

Thanks for the constructive feedback.

**Comment by brunosmmm** [comment]
@smile13241324 I just pulled my .emacs.d from github, and I had to go back to putting ensime in the excluded-packages again, otherwise spacemacs still wants to install it at startup.

**Comment by smile13241324** [comment]
@brunosmmm have you explicitly selected a backend i.e.
```elisp
     (scala :variables
            scala-backend 'scala-metals)
```
Otherwise the default one is loaded which is still `ensime` as I do not want to break existing configs.

**Comment by 108anup** [comment]
Even after explicitly specifying the backend, I need to exclude ensime. (I'm on master branch).

**Comment by smile13241324** [comment]
Master branch is really out of date as of today, please switch to develop, there it should be fixed.

**Comment by 108anup** [comment]
Same issue on develop branch. I get the error: ```Package ensime is unavailable. Is the package name misspelled?

Error in dotspacemacs/user-config: Cannot open load file: No such file or directory, ob-scala```

I have not added anything in the user-config, when I remove the scala layer, I don't get the ob-scala error.

I instead used the scala-lsp private layer (https://github.com/zheli/scala-lsp), that seems to work, I do get some other errors in that too.

**Comment by smile13241324** [comment]
@108anup, can you confirm that you explicitly selected a non ensime backend in your dotfile?
The situation as of today is that the default for the scala backend is still ensime as it seems to still being used in existing configs.

If you set a specific backend as of below it works on my side:
```elisp
     (scala :variables
            scala-backend 'scala-metals)
```

**Comment by 108anup** [comment]
Sorry for this, I just realized that I needed to pull from upstream as well after checking out develop. Things are working now. Thanks for the response.

**Comment by smile13241324** [comment]
Your welcome :)
