### ISSUE TITLE
ruby-toggle-block inserting a trialing whitespace

### ISSUE THREAD

**Issue by d3mash** [syl20bnr/spacemacs#12548]
#### Description :octocat:
Ruby toggle block not chomping trailing whitespace in block

#### Reproduction guide :beetle:
- Start Emacs
- Create a ruby file
- Write a block such as
```
(1..10).map { |number| number * 2 }
```
- Use ruby-toggle-block `, - T - {`

*Observed behaviour:* :eyes: :broken_heart:
- Command inserts a whitespace after line as follows
```
(1..10).map do |number|
  number * 2 
end
```
*Expected behaviour:* :heart: :smile:
- No trailing whitespace

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2bef3f67e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python erlang sql ansible csv racket clojure php javascript html yaml ruby helm auto-completion emacs-lisp git
        (markdown :variables markdown-live-preview-engine 'vmd)
        org
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        spell-checking syntax-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by duianto** [comment]
Confirmed, a whitespace remains after the `2` when following the reproduction steps.

It doesn't seem to insert the whitespace, it just doesn't remove it after the `2`.

Because when there's no space after the 2:
`(1..10).map { |number| number * 2}`
(it doesn't seem to matter if there's a space between the open curly bracket and the vertical bar)

Then the result of `,T{` (`ruby-toggle-block`) doesn't have a whitespace after the `2`:
```ruby
(1..10).map do |number|
  number * 2
end
```

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a69323fb3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git helm javascript markdown multiple-cursors org ruby spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by duianto** [comment]
`ruby-toggle-block` is defined in the `ruby-mode.el` version that's included with Emacs:
https://github.com/emacs-mirror/emacs/blob/45fc6f203e2fef528cb2bb0d7c0140e160c974e2/lisp/progmodes/ruby-mode.el#L1749

There's also a version that seems to be almost identical, in the `enhanced-ruby-mode` package:
https://github.com/zenspider/enhanced-ruby-mode/blob/f334c42986e93c60fba144d732becfcbdb13bb7d/enh-ruby-mode.el#L733

`,T{` uses the `enh-ruby-toggle-block` version when `enh-ruby-mode` is enabled in the ruby buffer, and it behaves the same as the `ruby-toggle-block` version.

It seems like `ruby-mode.el` is handled by the ruby maintainers:
>It’s included in Emacs 23 and is also available via ELPA. However, those copies have no guarantees of backwards-compatibility, so if you’re having trouble with it on an older Emacs version or XEmacs, you can use the copy that’s included with Ruby, which attempts to be highly compatible.

specifically the last sentence which states that a copy is included with Ruby.
source: https://www.emacswiki.org/emacs/RubyMode

It needs to be reported upstream.

**Comment by d3mash** [comment]
Hello @duianto , thanks for your time. I tried to file an issue @ https://github.com/emacs-mirror/emacs , but could not find a form. Could you walk me through the process of reporting it upstream, so I can do it and close this issue?

**Comment by duianto** [comment]
I just found the link to the github mirror repository when searching for `ruby-toggle-block`.
But it seems to just be a read only copy.

This seems to be the source of the Emacs git repository:
http://git.savannah.gnu.org/cgit/emacs.git

Here's the direct link to the `ruby-toggle-block` definition:
http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/progmodes/ruby-mode.el?id=2a05c5dbd3eca91ef4b843d45f3e6868d28cdb33#n1749


Searching for `ruby-mode.el` in the top right search box, shows that the latest commit occurred 2019-06-10:
http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=2a05c5dbd3eca91ef4b843d45f3e6868d28cdb33

So it might be updated directly in the Emacs repository, and not by the ruby maintainer(s) as I first thought.

This seems to be the instructions for reporting bugs in Emacs:
https://www.gnu.org/software/emacs/manual/html_node/efaq/Reporting-bugs.html

Before reporting bugs to the Emacs team, it's probably best to eliminate Spacemacs as a source.

Here are the reproduction steps in Emacs without Spacemacs:
- Start Emacs without loading any configurations: `emacs -q`
- Open a new buffer: `C-x b` `test` `RET`
- Switch to ruby mode: `M-x ruby-mode RET`
- Copy the following:
```ruby
(1..10).map { |number| number * 2 }
```
- Paste it in the test buffer: `C-y`
- Move the cursor backwards so that it's on expression: `C-b`
- Press `C-c {` or call `M-x ruby-toggle-block RET`

Observed:
```ruby
(1..10).map do |number|
  number * 2 
end
```
A space remains after the `2`.

This does not happen if the initial code doesn't have a space between the `2` and the closing curly bracket.
```ruby
(1..10).map {|number| number * 2}
```

**Comment by dgutov** [comment]
Now fixed in Emacs master.

**Comment by d3mash** [comment]
That's great to here. Closing this, because ⬆️
