### ISSUE TITLE
ediff-mode buggy keybindings

### ISSUE THREAD

**Issue by NightMachinary** [syl20bnr/spacemacs#12541]
#### Description :octocat:
ediff-mode is buggy in the evil (I'm note sure what mode this is called, the one other than the holy and the hybrid) mode (I need to focus the help buffer for the keybinding to work correctly, and even then 'j' and 'k' don't work.). Things work as expected if I turn on the holy mode before ediffing.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: added-dvorak-right-handed-to-keyboard-layout-layer (rev. 5bcbe1826)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(octave csv sql asciidoc yaml fsharp windows-scripts javascript ocaml idris fasd xclipboard gpu epub xkcd spotify twitter search-engine vimscript
        (elfeed :variables rmh-elfeed-org-files
                (list "~/.emacs.d/private/feeds/elfeed1.org"))
        (rust :variables rust-format-on-save t)
        (haskell :variables haskell-enable-hindent t)
        lsp
        (c-c++ :variables c-c++-enable-clang-support t)
        html
        (python :variables python-backend 'anaconda)
        chrome
        (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
        (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
        autohotkey kotlin helm
        (auto-completion :disabled-for ocaml :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
        emacs-lisp
        (ibuffer :variables ibuffer-group-buffers-by 'modes)
        coq emoji
        (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
        git markdown org
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        spell-checking
        (syntax-checking :variables syntax-checking-enable-tooltips t)
        (elm :variables elm-sort-imports-on-save t elm-format-on-save t)
        version-control osx scheme
        (clojure :variables clojure-enable-fancify-symbols t))
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
Tested on the latest develop branch with updated packages

`M-x ediff`
`c:/Users/username/Temp/a.txt`
`c:/Users/username/Temp/b.txt`

The Ediff navigation key bindings have been limited to when the cursor is in the Ediff control panel  (bottom by default in Spacemacs) since I started using (Spac)Emacs 3'ish years ago. Because that buffer is in `ediff-mode`.

With the cursor in the Ediff Control Panel buffer:
- With the `dotspacemacs-editing-style` set to `'vim`:
`j`/`n` moves to the next difference and `k`/`p` moves to the previous difference.
- With the `dotspacemacs-editing-style` set to `'emacs`:
`n` moves to the next difference and `p` moves to the previous difference.

When the cursor is moved to the A: (1) or B: (2) windows, then the mode in those buffers determines the key bindings. In this case they are in `text-mode`.

With the `'vim` (evil) editing style:
- `j` moves to the next line and `k` moves to the previous line.
- `n` tries to jump to the last searched pattern.
- `p` pastes.

With the `'emacs` (holy) editing style, the keys insert the typed letter.

How are you opening an Ediff session?
Maybe there's an issue with another Ediff command.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a69323fb3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey dash emacs-lisp git helm javascript markdown multiple-cursors org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by NightMachinary** [comment]
No, my results are the same as what you have described. (Except that in
holy mode the buffers themselves act as ediff control panel.)

 I suggest automatically focusing the ediff control buffer, and adding a
line to it saying you should use this buffer for control; It’s not
intuitive.

**Comment by duianto** [comment]
For me:
- With the Emacs (holy) editing style. Pressing `n` and `p` insert the characters `n` and `p` when the A or B buffers are selected.
- The Ediff control panel buffer is selected by default.

The Ediff feature comes with Emacs, if you request that they add an instruction message at the source, then it also would help non Spacemacs users.
