### ISSUE TITLE
How to load a layer without internet

### ISSUE THREAD

**Issue by EvergreenHZ** [syl20bnr/spacemacs#12569]
Hi, I want to use spacemacs on my company's computer(windows 7) with no network connected; So I just copy the whole .emacs.d directory from my Majora to C:/Users/my_account; Then I try to activate markdown-mode (the layer has already been in the layers/+lang/), however, spacemacs try to install a new one, but failed because no internet, Leaving Fundamental mode. 
So my Question is how to load the local packages? (I've been searching for a while, but still not solved the problem). Thanks for Help.

**Comment by duianto** [comment]
In the `.spacemacs` file, the variable: `dotspacemacs-install-packages`
has the default value: `'used-only`

This means that when a layer is commented or removed from the layers list,
then all of the layers packages will be deleted.

If the variable is changed to: `'used-but-keep-unused`
Then the packages won't be deleted, they will remain in the directory:
- `.emacs.d/elpa/` (on the Spacemacs `master` branch)
- `.emacs.d/elpa/develop/` (on the Spacemacs `develop` branch)


I'm not sure if it will work automatically to copy the `.emacs.d` directory from one OS to another,
maybe some layers/packages sets up some OS specific paths, the first time Spacemacs is started.

If something isn't working then a possible fix might be to backup/rename the `.emacs.d/.cache/` directory,
it's probably best to keep a backup in case one want to retrieve a bookmark, file history or some other setting.

You only mentioned copying the `.emacs.d` directory. But if your using the Spacemacs `develop` branch, then there's also a `.spacemacs.env` file (in the same directory as the `.emacs.d` directory).

It might contain some OS specific paths or settings, but it might not be important to copy it over, because if Spacemacs doesn't find a `.spacemacs.env` file, then it creates a new one when Spacemacs is restarted.
