### ISSUE TITLE
dotspacemacs-line-numbers :disabled-for-modes does not work

### ISSUE THREAD

**Issue by Da-Va** [syl20bnr/spacemacs#12560]
Title self-explanatory. This is mostly a problem with the pdf-view mode which is unusable with linum.

**Comment by duianto** [comment]
### Master branch
With the `pdf-tools` layer enabled and the `dotspacemacs-line-numbers` variable set to: `t`

When a `.pdf` file is opened, then a warnings buffer opens with the message:
>Warning (pdf-view): These modes are incompatible with `pdf-view-mode',
	please deactivate them (or customize pdf-view-incompatible-modes): linum-mode

And the .pdf buffer shows line numbers.

But when the `dotspacemacs-line-numbers` variable is set to:
```
   dotspacemacs-line-numbers '(:disabled-for-modes
                               dired-mode
                               doc-view-mode
                               markdown-mode
                               org-mode
                               pdf-view-mode
                               text-mode
                               :size-limit-kb 1000)
```

Then there's no warnings buffer, error messages (in the messages buffer) or line numbers in the `.pdf` buffer.

### Develop branch

With the `pdf` layer (it's been renamed from `pdf-tools`) enabled.

When opening a `.pdf` file. Then there are no line numbers or warnings with the `dotspacemacs-line-numbers` variable set to either `t` or the `:disabled-for-modes` list.

Possibly because the develop branch uses the built in Emacs 26 line numbers.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b68610954)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp pdf git helm javascript markdown multiple-cursors org python spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by Lqp1** [comment]
As said by @SadFoxDave the issue is that all modes specified in `:disabled-for-modes` are ignored; this just more annoying with pdf tools.
For example, on master with:
```
   dotspacemacs-line-numbers '(:relative t
                               :disabled-for-modes dired-mode
                                                                doc-view-mode
                                                                pdf-view-mode
                               :size-limit-kb 5000)

```
I have relative numbers for all modes, included `dired-mode`, `doc-view-mode` and `pdf-view-mode`.
My current workaround for `pdf-view-mode` is to add this in `user-config`:
```
(add-hook 'pdf-view-mode-hook (lambda() (linum-mode 0)))
```
