### ISSUE TITLE
[Evil] yanking / pasting in macro definition doesn't work

### ISSUE THREAD

**Issue by xanuthatusu** [syl20bnr/spacemacs#12562]
#### Description :octocat:
When defining a macro using `q` (`evil-record-macro`), I would like to be able to yank and paste words / lines as part of the macro.

#### Reproduction guide :beetle:
With a file that looks like
```
[p]ath
inputs
output
id
```
where `[]` is the cursor, type `qqyypRETq@q`

*Observed behaviour:* :eyes: :broken_heart:
Resulting file looks like
```
path
path
[i]nputs
output
id
```

*Expected behaviour:* :heart: :smile:
Resulting file looks like
```
path
path
inputs
inputs
[o]utput
id
```

#### Backtrace :paw_prints:
The only error I get is in `*Messages*` buffer.
`evil-record-macro: Invalid register`
`q` is a valid register and I can make any macros in that register that don't yank or paste

**Comment by duianto** [comment]
I'm getting the expected behavior on both the `master` and `develop` branches with updated packages, when reproducing the steps in a new empty buffer:
`SPC b N` (master)
`SPC b N n` (develop)

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b68610954)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp pdf git helm javascript markdown multiple-cursors org python spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by xanuthatusu** [comment]
Upon further testing, I do get the expected behavior in a new empty buffer, but get the behavior I described above when I have `lsp-mode` active.

**Comment by duianto** [comment]
I'm also getting the expected behavior in a python (.py) file with lsp-mode (mspyls) enabled.

<details><summary>
Windows 1903, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 04b80d610)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git helm imenu-list lsp multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            (python :variables python-lsp-server 'mspyls python-backend 'lsp)
            (shell :variables shell-default-shell 'eshell shell-default-height 30)
            spell-checking syntax-checking themes-megapack treemacs typescript version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>
