### ISSUE TITLE
`Winner mode is turned off`

### ISSUE THREAD

**Issue by jonasws** [syl20bnr/spacemacs#12582]
Has anyone else recently experience the message `Winner mode is turned off` when runnning window-stack commands, such as `SPC w u`? I managed to solve it by putting `(winner-mode)` in my `spacemacs/user-config`,but this strictly should not be necessary.

Am I missing some "obvious" configuration change somewhere, as to how to dictate Spacemacs to actually enable winner interaction? Running on `develop` branch.

**Comment by duianto** [comment]
agzam noticed the same thing in the gitter chat:
>Can someone tell me why winner-mode is disabled by default now in develop? Are there any known problems?
I think specifically this commit changed the way how it used to work syl20bnr/spacemacs@0e2935b

source: https://gitter.im/syl20bnr/spacemacs?at=5d40e21c4ba6af0b025e53cc

And I also noticed it when exiting from an ediff session. The minibuffer shows:
>winner-undo: Winner mode is turned off

We have not heard a response from @syl20bnr yet.

**Comment by duianto** [comment]
Maybe `:defer t` wasn't supposed to be removed, and only the `:commands` keyword should have been added?

For example the Treemacs layer, uses both:
https://github.com/syl20bnr/spacemacs/blob/56ae091b62af9b9d2da1d429700cc9fbce6b1720/layers/%2Bfiletree/treemacs/packages.el#L29-L31

The `:commands` are available on startup, before opening Treemacs.

**Comment by duianto** [comment]
Nope it wasn't that simple. Even reverting that commit didn't help.
Now it shows:
>command-execute: Wrong type argument: commandp, winner-undo

**Comment by duianto** [comment]
It's one of these commits:
b7266b38b * [dump] Add functions to save and restore load-path
32f6f07f9 * [dump] Move more dump specific init code to dump-init.el
08dc9567b * [dump] Delay holy and hybrid config after dump is loaded

But there's an error on startup which prevents a lot/most Spacemacs features from working.
The commit after b7266b38b fixes the error:
e07478423 * @ Fix regular loading of Emacs (i.e. without a dump file)

**Comment by duianto** [comment]
It's probably this one:
32f6f07 * [dump] Move more dump specific init code to dump-init.el

It moved and changed:
`(winner-mode t)` from `init.el`
to: `(winner-mode 1)` in `dump-init.el`

It doesn't work to change it back to `(winner-mode t)` in `dump-init.el`
nor does it work without an argument `(winner-mode)` as the docstring suggests:
>Toggle Winner mode on or off.
With a prefix argument ARG, enable Winner mode if ARG is
positive, and disable it otherwise.  If called from Lisp, enable
the mode if ARG is omitted or nil, and toggle it if ARG is ‘toggle’.

#### Side note
The docstring sounds a bit crazy by stating that a `nil` argument enables it.

**Comment by duianto** [comment]
`dump-init.el` isn't called by default.
It's probably related to this:
https://github.com/syl20bnr/spacemacs/blob/develop/EXPERIMENTAL.org

**Comment by smile13241324** [comment]
The issue is related to lazy loading `winner-mode`. The point is `winner-mode` must be activated before `winner-undo` and `winner-redo` have any effect. I have pushed a hotfix which eagerly loads `winner-mode` and solves the issues described here.

Ediff was broken as it internally relied on winner-mode recording the changes done to the current window configuration which it did not when it was lazy loaded.

When you pull the latest version from develop all should work again.

**Comment by smile13241324** [comment]
@jonasws can you double check and if all works close your ticket please?

**Comment by duianto** [comment]
Confirmed `winner-mode` is now enabled on startup. Thanks smile13241324

**Comment by yqu212** [comment]
Enable winner-mode on startup will break dumping process. 

> unsupported object type in dump: window configuration

**Comment by smile13241324** [comment]
@yqu212 Thanks for pointing this out. I am still on emacs 26.2 and did not notice that this affected dumping. I have moved the initialisation code into spacemacs/setup-startup-hook which is only called in the non-dumping case.

Hope this solves the issue for both worlds.
Can you check whether dumping does work again for you? Non-dumping I have tested already and works well.

**Comment by yqu212** [comment]
Confirmed successful dumping process. Thank you.

**Comment by smile13241324** [comment]
@jonasws would you mind having another look at the issue and close it when it is solved on develop please?

**Comment by jonasws** [comment]
Fixed by 85fca8f32367cbcf64a8176ad8314363edf94249.
