### ISSUE TITLE
Light Color Themes are broken

### ISSUE THREAD

**Issue by MrMic** [syl20bnr/spacemacs#12635]
Hi,

I try many light themes and also installed the themes-megapack package, but 
they all are bad display.

Something is wrong with light themes.  At first glance, dark themes seem OK.

Thanks for fixing it. My eyes will thank you :)

Rgds,

**Comment by duianto** [comment]
Could you provide some screenshots. And a description of what the problem is?

"Something is wrong with light themes" is not enough information.

And your system information would also help, if you press `SPC h d s` then the system info will be copied to your clipboard, which you can paste in a comment.

**Comment by MrMic** [comment]
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust javascript yaml helm auto-completion better-defaults emacs-lisp clojure git ansible terraform docker vagrant python scala markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control themes-megapack html javascript react erlang elixir colors twitter
      (go :variables go-tab-width 4 go-use-gometalinter t gofmt-command "goimports")
      (ranger :variables ranger-show-preview t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

===== 8< ----------------------------------------------------------------
And with the theme: spacemacs-light, here is the image:
![Capture du 2019-08-18 18-47-38](https://user-images.githubusercontent.com/5823264/63227804-d3b6ee80-c1ea-11e9-9edf-35b7daf87fa2.png)

**Comment by duianto** [comment]
That does look broken.
For me the `spacemacs-light` theme looks fine on both the `master` and `develop` branches.

![emacs_2019-08-18_20-27-51](https://user-images.githubusercontent.com/13420573/63228693-cef83780-c1f6-11e9-9e71-a9bcc39b0786.png)

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 8c0b8c344)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git helm html javascript markdown
            (org :variables org-want-todo-bindings t)
            python shell spell-checking syntax-checking themes-megapack version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by MrMic** [comment]
I do NOT care what you have.
My issue is why is this broken now on me?
Just answer if you have the answer otherwise let someone else will answer.
Do NOT make me lose my time.
Thanks.

**Comment by duianto** [comment]
An important part of debugging is to find out where the issue doesn't occur.
It also demonstrates that it is not happening for everyone.

The latest Emacs version is 26.2. If your able to upgrade, then you can eliminate that as a possibility.

To eliminate any of your configurations, you could backup your current setup and clone a fresh copy.

It's not a linux specific issue, because it's also working as expected in Ubuntu on both the `master` and `develop` branch, with updated packages.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 8c0b8c344)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm markdown multiple-cursors org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

**Comment by syl20bnr** [comment]
@MrMic He was posting his screenshot to be able to compare with yours. It is valuable information.

More often than not it is cause by a customized background face in your `.spacemacs` dotfile which overwrite the color for _any_ theme. Since the customized color for you seems to be dark and you don't see the difference with dark themes.

**Comment by MrMic** [comment]
You gave me the clue.
I had to remove some custom configuration for Org mode :(

Thank you.
Rgds,

**Comment by duianto** [comment]
@MrMic I haven't tried this but here's a tutorial for changing the background color based on the file name extension:
http://ergoemacs.org/emacs/emacs_set_theme_on_mode.html
