### ISSUE TITLE
Got a warning when trying to insert YASnippet.

### ISSUE THREAD

**Issue by pietrodito** [syl20bnr/spacemacs#12648]
#### Description :octocat:
Got a warning when trying to insert YASnippet.

#### Reproduction guide :beetle:
- Start Emacs
- Create a new empty buffer | M-x spacemacs/new-empty-buffer
- Optional : select Org mode | M-x org-mode
- Insert a snippet                   | M-x helm-yas

*Observed behaviour:* :eyes: :broken_heart:
New window appears with buffer *Warnings* containig the following line of text :
Warning (defvaralias): Overwriting value of ‘helm-c-yas-space-match-any-greedy’ by aliasing to ‘helm-yas-space-match-any-greedy’

*Expected behaviour:* :heart: :smile:
No warnings.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. dcb4da02a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(ess auto-completion emacs-lisp git helm multiple-cursors org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM THREADS PDUMPER GMP

#### Backtrace :paw_prints:
```
```

**Comment by pietrodito** [comment]
What is wrong with my question ?

**Comment by duianto** [comment]
You did nothing wrong, no one has had time to review this yet. There are very few people reviewing issues/prs.

This might be an Emacs 27.0.50 issue, because There's no warning with Emacs 26.2.

With 27.0.50 when `SPC SPC spacemacs/helm-yas RET` is called (or the bound key `SPC i s` for the same command is pressed), then:
- A helm buffer with a yasnippet section opens
- And a warnings buffer opens with the message:
>Warning (defvaralias): Overwriting value of ‘helm-c-yas-space-match-any-greedy’ by aliasing to ‘helm-yas-space-match-any-greedy’

It isn't `org-mode` or new empty buffer related, because it also happens in `.spacemacs`.

It works to add snippets and the warning doesn't seem to return if the warning buffer is closed. So it seems to just occur the first time yasnippet is called.

I wonder if https://github.com/emacs-jp/helm-c-yasnippet doesn't have support for Emacs 27.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 48ffd3759)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm markdown multiple-cursors org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2 and 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 48ffd3759)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm html multiple-cursors org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by gliderproarc** [comment]
This doesn't get at the root of the problem, but for those using Emacs 27 and YASnippet I found adding this to my dotspacemacs/user-config to get the warnings to stop:

`(defvaralias 'helm-c-yas-space-match-any-greedy 'helm-yas-space-match-any-greedy "Temporary alias for Emacs27")`

**Comment by duianto** [comment]
The issue was caused because Spacemacs was using the obsolete variable.
It's now been replaced with the current variable: `helm-yas-space-match-any-greedy`

[auto-completion] Fix obsolete: helm-c-yas-space-match-any-greedy https://github.com/syl20bnr/spacemacs/commit/3fe675d588889c2afa5bd0494d2497b626250495

The workaround isn't needed anymore, just pull the latest develop branch.
