### ISSUE TITLE
Treemacs taking over half the frame

### ISSUE THREAD

**Issue by jnordwick3x** [syl20bnr/spacemacs#12641]
#### Description :octocat:
Treemacs and `SPC w 3` don't work like they used to. Treemacs now takes over half the frame.

#### Reproduction guide :beetle:
- Start Emacs
- Start Treemacs `SPC f t`
- resize for 3 columns `SPC w 3`

*Observed behaviour:* :eyes: :broken_heart:
Treemacs will now take up the left half of the frame while the other three fames will take up 1/6th each.

*Expected behaviour:* :heart: :smile:
Before my recent git pull, treemacs would take up a small left column (~1/10th of the frame) and the remainder of the frame would be split equally by the 3 new windows

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ae51fd7a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp better-defaults auto-completion themes-megapack emoji helm markdown multiple-cursors git syntax-checking semantic rust python
            (go :variables go-tab-width 2 go-use-gometalinter t)
            (c-c++ :variables c-c++-backend 'rtags c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
            markdown shell-scripts sql
            (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LCMS2

#### Backtrace :paw_prints:
```
```

**Comment by duianto** [comment]
Confirmed, it happens with all the split commands:
  - spacemacs/window-split-grid
  - spacemacs/window-split-triple-columns
  - spacemacs/window-split-double-columns
  - spacemacs/window-split-single-column

**Comment by cbillowes** [comment]
I am having the same issue. Mine is not isolated to treemacs though. The widths aren't equal when I split the frame into multiple windows and I can't even resize them by dragging them with my mouse or using the shortcut keys. [StackOverflow question](https://stackoverflow.com/questions/57675647/why-cant-i-resize-my-windows-to-be-the-same-width). Do you think it could be related?

**Comment by cbillowes** [comment]
I got an answer on my question and it was because of golden-ratio (http://github.com/roman/golden-ratio.el) or zoom (http://github.com/cyrus-and/zoom). I was using Zoom. I toggled the [golden-ratio](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#golden-ratio) using `SPC t g`

**Comment by jjforsythe** [comment]
I have also managed to reproduce this issue on the `develop` branch. This issue appears to have been introduced since the treemacs v2.6 release, as when I tested this version the treemacs window maintains its size after a call to one of the `window-split-` functions @duianto mentions above, https://github.com/syl20bnr/spacemacs/issues/12641#issuecomment-523563064. However this sometimes requires a second resize via `(treemacs-set-width :reset)` (see below).

It looks like a recent treemacs commit (https://github.com/Alexander-Miller/treemacs/commit/507da48d84d61759b8d96c56d0920a815b1e2915) removed a call to `(treemacs-set-width :reset)` which was called regularly enough that this issue was not so noticeable before. However this was itself part of a workaround for what appear to be separate issues concerning integrating with which-key.

It appears that each of the `window-split-` functions call the `balance-windows` Emacs function. This function appears to resize the treemacs window if it is not set to have a fixed width. Therefore a workaround, which I have tested, is to set the `treemacs-lock-width` variable in your configuration as described in the treemacs layer documentation [here](http://develop.spacemacs.org/layers/+filetree/treemacs/README.html#locking-width). You can also toggle this setting within the treemacs window as required with the `t w` key binding.

It looks like this may be resolved in the future within treemacs and I have commented on the associated issue to find out further details (https://github.com/Alexander-Miller/treemacs/issues/514).

**Comment by Alexander-Miller** [comment]
I'd be happy to solve this, but we need to come up with a solution first. Now here's the status quo:

When width is locked - which means `(setf window-size-fixed 'width)` - it will and can not be changed by anything other than interactively calling `treemacs-set-width`.

When width is unlocked treemacs is treated as any other window. Its width can be changed by the usual interactive functions or the mouse, but also stuff like resizing the frame. I assume it's the last part that people do not want, and unlocking the width should only make it changeable by something like `evil-window-decrease-width` or similar spacemacs commands. Is that right?

**Comment by jjforsythe** [comment]
Thanks @Alexander-Miller , it would be great to have your help on this. I am also happy to do more if I can be useful.

When the width is unlocked the window should probably continue to be resizable, as you say, by some interactive functions (e.g. `evil-window-decrease-width`), the mouse or resizing the frame. However when you call the interactive `window-split-` functions, referenced above, the window size should not change. So, unless I misunderstood your comment, the current behaviour for resizing when the width is unlocked (via the mouse etc.) appears to be as expected and we only need to address the case when the `window-split-` functions are used.
