### ISSUE TITLE
desktop-save-mode blocks startup of spacemacs

### ISSUE THREAD

**Issue by seschwar** [syl20bnr/spacemacs#1265]
When `desktop-save-mode` is enabled spacemacs stops after initialization with the prompt `Buffer "*emacs*" has a running process; kill it? (y or n)`.  The "running process" is spacemacs checking its repository for updates.

While I can easily answer `n` and continue when launching Emacs with a frame attached, it's a problem when using `emacs --daemon`.  Due to the question the daemon blocks and doesn't fork.  This breaks scripted Emacs startup, both with shell scripts and systemd.  The daemon doesn't fork and therefore the script can't continue past `emacs --daemon`.

This can be easily reproduced by appending the following lines onto the default `~/.spacemacs`.

    (custom-set-variables
     '(desktop-save-mode t))

**Comment by syl20bnr** [comment]
Thank you for the report, can you try to delay the first check and see if it allows the process to fork ?
https://github.com/syl20bnr/spacemacs/tree/develop/core/core-spacemacs.el#L366
```elisp
(run-at-time 20 nil
                  (lambda () (spacemacs/check-for-new-version
                              spacemacs-version-check-interval)))
```

**Comment by person808** [comment]
@seschwar Do you still encounter this issue? I want to know if I can recommend this in #1565

**Comment by StreakyCobra** [comment]
@seschwar Do you still have this issue with last spacemacs release?

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
