### ISSUE TITLE
How to use Ansible layer?

### ISSUE THREAD

**Issue by abitrolly** [syl20bnr/spacemacs#12661]
I am trying to understand how to write Ansible roles and test them using [this layer](http://spacemacs.org/layers/+tools/ansible/README.html). I added `ansible` to `dotspacemacs-configuration-layers`, restarted Spacemacs and checked Messages to see what is loaded.
```
Loading /home/anatoli/.emacs.d/layers/+tools/ansible/packages.el (source)...done
Loading /home/anatoli/.emacs.d/layers/+tools/ansible/layers.el (source)...
Loading /home/anatoli/.emacs.d/layers/+lang/yaml/packages.el (source)...done
Loading /home/anatoli/.emacs.d/layers/+tools/ansible/layers.el (source)...done
...
Loading /home/anatoli/.emacs.d/layers/+tools/ansible/funcs.el (source)...done
...
Loading /home/anatoli/.emacs.d/layers/+tools/ansible/config.el (source)...done
```
I still don't see anything. `SPC m h` a from documentation doesn't work - resulting in SPC m is undefined. Spacemacs shows `/YAML\` at the bottom near the filename. I don't see that Spacemacs detected YAML file as an Ansible playbook - I don't get any hints or errors displayed on the screen. Do I need to change mode from YAML to Ansible somehow?

---

I also asked here https://emacs.stackexchange.com/questions/50357/how-to-use-ansible-layer-in-spacemacs and got not replies.

**Comment by duianto** [comment]
It seems to depend on the name and location of the files your opening.

Spacemacs is using the ansible playbooks best practices.
https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#directory-layout

https://github.com/syl20bnr/spacemacs/blob/c7a103a772d808101d7635ec10f292ab9202d9ee/layers/%2Btools/ansible/config.el#L19-L22

If I'm reading it correctly is looking for files called:
- main.yml
- site.yml
- encrypted.yml

Or for files stored in directories called:
- roles/
- group_vars/
- host_vars/


I had an `ansible-test` file containing an example I found somewhere:
```ansible
- name: create user groups
  group:
    name: "{{ item }}"
  loop:
    - postgresql
    - nginx-test
    - admin
    - dbadmin
    - hadoop
```
And `SPC m` was undefined because Spacemacs doesn't know what the file is intended for. Therefore the buffer opens in `fundamental-mode`. When I dug into how ansible is enabled and saw that list of file names. I renamed the file to `main.yml` and now when the file is opened, it's in `ansible-mode` and `SPC m` has two entries:
- `b -> buffer`
- `h -> help`

**Comment by abitrolly** [comment]
Thanks for the extensive info. It is more clear now, and I've got more questions.

1. Is it possible to force `ansible-mode` manually?

2. What the `SPC m` convention is for?

3. Is it possible to detect mode by matching YAML structure?

**Comment by abitrolly** [comment]
I tried to simplify file matching `re` and now tests are failing for some reason. https://github.com/syl20bnr/spacemacs/pull/12671

**Comment by duianto** [comment]
1. Ansible mode with yaml syntax can be enabled manually by calling:
- `M-x yaml-mode RET`
- `M-x ansible RET`
2. `SPC m` or `,` (comma) are prefixes for the major mode key bindings.
3. I don't know how structure detection works.

The failing tests are unrelated to your PR. They are related to the work being done on the spacelpa verification.
>2 unexpected results:
   FAILED  test-stable-elpa-verify-archive--verification-failed
   FAILED  test-stable-elpa-verify-archive--verification-ok

https://github.com/syl20bnr/spacelpa will be a stable set of packages for the next version of Spacemacs, so that a change in an upstream package won't break Spacemacs.

**Comment by patrick-motard** [comment]
yaml-mode provides a hook you can use to enable ansible-mode whenever yaml mode is used. 

Here's an example of how I do that: https://github.com/patrick-motard/dotfiles/blob/master/.emacs.d.han/init.el#L171
(The example above is in my non spacemacs config, but it's the same modes and hooks. You can put it in your .spacemacs user configs section) 
This approach is also documented in the brief readme of ansible-mode https://github.com/k1LoW/emacs-ansible

**Comment by abitrolly** [comment]
@patrick-motard link drifted. Do you mean this block?

https://github.com/patrick-motard/dotfiles/blob/5f4825de372ade6db025420236a19cb7a48ef43c/.emacs.d.han/init.el#L220-L228

I don't know that `:ensure t` means here.
```
(use-package yaml-mode
  :ensure t)
```

**Comment by abitrolly** [comment]
Are there two separate Ansible layers?

1. https://github.com/syl20bnr/spacemacs/tree/master/layers/+tools/ansible
2. https://github.com/k1LoW/emacs-ansible

**Comment by patrick-motard** [comment]
@abitrolly `:ensure t` is parameter in the use-package function. Use-package is one of the more recommended ways to declare/use packages in your emacs configuration: https://github.com/jwiegley/use-package
:ensure t means "please ensure that this package is installed on the system, you have my permission to install it for me if it is not."

As for your second question, the spacemacs layer is a wrapper around several packages that installs them and configures them with sane defaults. Many layers are like this.

You can see in the layer's code that it's actually using use-package to install the ansible package i mentioned: https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Btools/ansible/packages.el#L20

It also goes on to install other packages like ansible-doc, and configures it, much like what is recommended by the ansible packages readme https://github.com/k1LoW/emacs-ansible

In most cases, when trying to figure out what a layer is doing, here's what i do:
- read the layers documentation
-- note which packages it depends on
-- note what settings i can configure through the layer itself
- read the documentation for the packages it depends on so that
-- i can configure the package itself if the layer doesn't provide a way of doing so

**Comment by abitrolly** [comment]
That clarifies things a lot. I will get back to it for testing next time I need to fix my playbooks.
