### ISSUE TITLE
Key binding conflict in org layer with previous-line-first-non-blank

### ISSUE THREAD

**Issue by frankieliu** [syl20bnr/spacemacs#12663]
#### Description :octocat:
Binding of '-' in org layer.
org layer rebinds '-' to org-cycle-list-bullet

Unfortunately this overides evil modes '-'
evil-previous-line-first-non-blank

Could you please suggest a way to unbind '-' in org layer?
i.e. something I can use in the .spacemacs

#### Reproduction guide :beetle:
- Start Emacs
- Open a .org buffer
- C-h k -
- You will see that it is bound to org-cycle-list-bullet

*Observed behaviour:* :eyes: :broken_heart:
Binding of '-' overides evil's binding of the same

*Expected behaviour:* :heart: :smile:
Keep evil's binding and reserve - to layer binding with leader key.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 8c0b8c344)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((go :variables go-tab-width 4)
 python helm
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil)
 emacs-lisp git org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by duianto** [comment]
Try updating your packages.

Because a Ubuntu VirtualBox guest:
- The `master` branch `-` called `org-cycle-list-bullet`.
but after updating the packages: `-` now calls `evil-previous-line-first-non-blank`.
- The `develop` branch `-` calls `evil-previous-line-first-non-blank`.

On a Windows machine:
`-` calls `evil-previous-line-first-non-blank` on both the Spacemacs `master` and `develop` branch.

The packages was probably already updated in the instances that already called `evil-previous-line-first-non-blank`.

`SPC m -` calls `org-ctrl-c-minus` which seems to cycle list bullets.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0906b24e3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion
 (dart :variables dart-sdk-path "/usr/bin/dart/" dart-enable-analysis-server t)
 emacs-lisp git helm markdown multiple-cursors org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 48ffd3759)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm html multiple-cursors org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
