### ISSUE TITLE
add spacemacs launch command

### ISSUE THREAD

**Issue by alanauckland86** [syl20bnr/spacemacs#12692]
I think of Spacemacs as Spacemacs. 

I understand that it is is a configuration for emacs. 
That being said I still feel that when I want to open Spacemacs and not Emacs.

I should be typing Spacemacs to open/search for this application.  

e.g in the application search menu, same again in terminal I would like to say   `spacemacs file.txt`

I have added an alias in my bash profile to this affect. 
I do not know if this would be deemed the correct way to do this. 
I feel that maybe it should be part of the installation. 
Or instructions given on recommended ways to install. 

This would also inadvertently help brand recognition.

**Comment by Asalle** [comment]
The only (stupid) idea that I can think of is to create a package that will add the alias line to your .profile file. 
Then again, I don't know if it makes sense from the "ideological" point of view (brand recognition, etc).

**Comment by alanauckland86** [comment]
I do not know much about creating these things. I know on Linux and Mac it can be done this way. 
I have no idea how you would achieve for Windows. 

I don't get why it wouldn't make sense.
I really don't like the notion of having to type emacs every time I actually to use spacemacs. 
maybe think this way. 
how would you feel typing Vim to open spacemacs every time you wanted to use spacemacs? 

I feel everytime you type emacs, emacs is getting the brand recognition. 

You want people to install and use spacemacs right?
So people should call Spacemacs when they want to use Spacemacs. 
I feel its dumb to call emacs when you want to use Spacemacs. 

I don't ring Domino's for  a pizza and expect to see a Pizza from Pizza hut everytime! Where does that make sense?

**Comment by Asalle** [comment]
You're right about windows, forgot about that. Generally speaking, spacemacs has no power over things outside emacs, that includes creating aliases for commands or installing windows executables I guess. But let's see, maybe contributors have other opinions on that.

**Comment by pankajbhanu** [comment]
1. Lets not forget spacemacs is first and foremost a community driven "configuration" aimed at providing a polished and sophisticated experience of "Emacs". Emacs is the editor here and not spacemacs and that is how most users see spacemacs. 
2. Adding an alias in xprofile for using spacemacs instead of emacs looks like the trivial solution here. IMHO Tying `emacs file.txt` instead of `spacemacs file.txt` is shorter and more intuitive to a regular emacs user. Changing launch command doesn't look as attractive to an emacs coming from other configurations which are a lot by the way, see https://github.com/emacs-tw/awesome-emacs#starter-kit.

**Comment by Asalle** [comment]
@alanauckland86, what do you think about closing the issue and re-opening it if somebody else finds it useful?

**Comment by alanauckland86** [comment]
Sure do you need me to do that?

**Comment by Asalle** [comment]
I think only the author and the maintainers (owners) of the project can close issues, I sure can't :)
