### ISSUE TITLE
Regex bug

### ISSUE THREAD

**Issue by troublescooter** [syl20bnr/spacemacs#12741]
#### Description
Applying a regex substitution to a file leads to different results than expected. The regex should replace the first character in the current line not equal to '$' with 'a' afaik. Vim behaves as expected when performing the substitution.

#### Reproduction guide
- Start Emacs
- :s/[^$]/a/ on a file just containing the character 'A'. 

*Observed behaviour:*
Spacemacs reports: Replaced 1 occurrence
File still only has character 'A'.

*Expected behaviour:*
'A' should be replaced by 'a'.

*System Info*
OS: gnu/linux
Emacs-nox: 26.3
Spacemacs: 0.300.0
Spacemacs branch: develop
Graphic display: nil
Distribution: spacemacs
Editing style: vim
Completion: helm
Layers:
html
haskell
auto-completion
 better-defaults
(c-c++ :variables c-c++-enable-clang-support t)
git
(latex :variables latex-enable-folding t)
org
python
rust
(spell-checking :variables
            enable-flyspell-auto-completion t
            spell-checking-enable-by-default nil
            spell-checking-enable-auto-dictionary t)
syntax-checking
version-control

**Comment by Trapez** [comment]
It does work. The replace is case insensitive.

**Comment by duianto** [comment]
Adding the case sensitive flag: `I` (upper case i) works.
```
s/[^$]/a/I
```
It seems to happen because the variable: `evil-ex-substitute-case` is set to `nil` by default.
The variables doc string says:
>Documentation:
The case behaviour of the search command.
Smart case means that the pattern is case sensitive if and only
if it contains an upper case letter, otherwise it is case
insensitive. If nil then the setting of ‘evil-ex-search-case’ is
used.

and the variable `evil-ex-search-case` is set to `smart` by default.
It's doc string says:
>Documentation:
The case behaviour of the search command.
Smart case means that the pattern is case sensitive if and only
if it contains an upper case letter, otherwise it is case
insensitive.

The following enables the behavior your after.
```elisp
(setq evil-ex-substitute-case t)
```

The variables default values are not changed by Spacemacs, because the same thing happens with just Emacs and Evil.

Open an issue upstream to change the default behavior to match Vim.
https://github.com/emacs-evil/evil
