### ISSUE TITLE
How to replace package with forked version?

### ISSUE THREAD

**Issue by ezchi** [syl20bnr/spacemacs#12756]
How to replace package like `lsp` with my forked version?

**Comment by yyoncho** [comment]
I do the following:

```
(async-shell-command "ln -s ~/Sources/lsp/lsp-mode/*el ~/.emacs.d/elpa/27.0/develop/lsp-mode-*/ -fv")
```

I used to change the `:location` of `lsp-mode` in the lsp layer but this was inconvenient when I wanted to do spacemacs PR.

**Comment by ezchi** [comment]
Thanks @yyoncho for the solution. Is it possible to get the path like "~/.emacs.d/elpa/27.0/develop" programmatic? And it will be good if there's some hooks for after package update.

**Comment by simonfxr** [comment]
Another option is to add the package to override to `dotspacemacs-additional-packages` with an explicit `:location`, e.g:

```elisp
(setq-default dotspacemacs-additional-packages
                     ...
                     (lsp :location local)
                    'lsp-dependency1
                    ...)
(add-to-list 'load-path "/path/to/lsp")
```
If you do this you also have to add all direct dependencies of `lsp` to `dotspacemacs-additional-packages`, since it won't look at the elpa package to install dependencies.
If your fork is on Github, you can use quelpa recipes:

```elisp
(setq-default dotspacemacs-additional-packages
                     ...
                     (lsp :location (recipe :fetcher github :repo "user/repo"))
```
If using this option, dependencies should be taken care of by quelpa. The checkout can then be found in `spacemacs-cache-directory`/quelpa/build/lsp.
