### ISSUE TITLE
golang readme on develop.spacemacs.org is outdated

### ISSUE THREAD

**Issue by Asalle** [syl20bnr/spacemacs#12796]
gometalinter's [repo](https://github.com/alecthomas/gometalinter/blob/master/README.md) has been archived, all support has been stopped, let's remove it as an option in [readme](http://develop.spacemacs.org/layers/+lang/go/README.html)? Or at least let's make it less visible and not the first option. Instead, let's make golangci-lint more visible.

**Comment by Asalle** [comment]
it turned out, the readme on develop has already been updated. But somehow, develop.spacemacs.org does not have those changes. this issue looks a lot like #12718.

**Comment by jr0cket** [comment]
It seems that develop.spacemacs.org website (the website for those using the `develop` branch of Spacemacs) is a little behind, last update was 8th July 2019.  There is a bot that manages (at least some of) the deployment process and has a newer version of the website (15th September) at https://emacspace.github.io/develop.spacemacs.org/

It seems like the process to update the develop.spacemacs.org website either requires a manual step or the automated bot has failed.  From what I can tell, there is some process that generated all the html content for develop.spacemacs.org from the org-mode files

https://github.com/syl20bnr/develop.spacemacs.org/pull/84 is a pull request from July 2019 that failed due to errors in the Travis build.  Since then there have been no further pull requests to update the content at develop.spacemacs.org

So the most up to date source of info is in the https://github.com/syl20bnr/spacemacs/ repository readme files

**Comment by duianto** [comment]
It's the bot that isn't working.

travisci reported:
>/tmp/emacs-26.1-travis/bin/emacs: error while loading shared libraries: libgnutls.so.26: cannot open shared object file: No such file or directory

source: https://next.travis-ci.org/syl20bnr/spacemacs/builds/605099474

I pushed a suggested possible fix: https://github.com/syl20bnr/spacemacs/commit/f6cdec168e92b33bcd3a76f94f375dd7abdca486

It doesn't show that error anymore, but it now shows:
>Cannot open load file: No such file or directory, evil

source: https://next.travis-ci.org/syl20bnr/spacemacs/builds/605206548

It's the same error as in this issue: Unable to install Spacemacs #12545

The suggested fix was to add the following to the top of `init.el`:
```elisp
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
```

I know very little about travisci. So I don't know where or if it should be added in:
https://github.com/syl20bnr/spacemacs/blob/develop/.travis.yml
