### ISSUE TITLE
Org mode seems active even if org layer is not installed

### ISSUE THREAD

**Issue by gutsle** [syl20bnr/spacemacs#12804]
Opening a ".org" file shows "Org" in the statusbar even when the org layer is not installed. In that case SPC m won't be defined. It's kind of confusing to newbies. It would be nice to get a message that org-mode is not available and be asked if it should be installed like it works for HTML.

**Comment by duianto** [comment]
`org-mode` comes with Emacs, that's why it works by default.

But as you said, if the Spacemacs `org` layer isn't enabled, then the major mode key binding prefix `SPC m` doesn't work.

The prompt asking to install the `org` layer appears when a `.org` file is opened when the following:
```elisp
;; org
(configuration-layer/lazy-install 'org :extensions '("\\(\\.org$\\)" org-mode))
```
is added to `c:/Users/username/.emacs.d/layers/auto-layer.el`

But one issue might be if someone that doesn't use the Spacemacs `org` layer, opens a `.org` document, for example from `SPC h SPC`, then the prompt opens asking to install the `org` layer every time.

**Comment by gutsle** [comment]
@duianto So, it should have asked me to install it?

**Comment by duianto** [comment]
Currently it doesn't ask to install the org layer.

A possible solution to the prompt appearing every time a `.org` file is opened when the org layer isn't installed and someone doesn't want to install it, might be to have another choice that could say something like:
`No, and don't ask again.`

I don't know how easy/hard it would be to implement.

**Comment by Apromixately** [comment]
@duianto I'm not sure we're talking about the same thing.

I've tried in develop and master to launch spacemacs with a vanilla configuration and opening a org file.
It displays fine since org-mode is included but `SPC m` doesn't work because the layer is missing.
In neither case have I gotten a warning or a prompt to install the layer.

**Comment by duianto** [comment]
We're talking about the same thing.

That there is no prompt to install the `org` layer when a `.org` file is opened.

In my second comment I stated:
>Currently it doesn't ask to install the org layer.

In my initial comment I stated why there is no prompt. It's because the `lazy-install` line for `.org` mode files isn't present in the `~/.emacs.d/layers/auto-layer.el` file.

If that line is added, then the prompt will ask to install the `org` layer.

But my question was, if the prompt was added and someone isn't using the org-mode packages/features that are part of the `org` layer. And they don't want to install the `org` layer.

Then they would have to dismiss the prompt to install the `org` layer every time a `.org` file was opened, for example if they just want to read any of the `SPC h SPC` Spacemacs or layers documentation.

I'll as what the maintainers think.

**Comment by Apromixately** [comment]
@duianto Okay, sorry, I apparently couldn't follow. :)

I agree that for such a prompt there should probably be an option to "not ask again". But is it even necessary to provide a prompt? I'm not sure what the costs are of installing a layer that people don't necessarily want. Won't it just be a few KB of disk space?

**Comment by duianto** [comment]
Each layer defines some number of packages, that will be downloaded/configured.

In this case, the `org` layer uses these packages:
https://github.com/syl20bnr/spacemacs/blob/6556cfc80d4ba070c7385f44f932fbe2b97c0663/layers/%2Bemacs/org/packages.el#L12-L48

(A lot of them are only downloaded if the toggle layer variable is enabled.)
