### ISSUE TITLE
evil-window not properly mapped with keyboard-layout layer

### ISSUE THREAD

**Issue by gvannoye** [syl20bnr/spacemacs#12811]
#### Description :octocat:
evil-window keys are not changed with the keyboard-layout layer

#### Reproduction guide :beetle:
- Start Emacs
- Activate the keyboard-layout layer with the Dvorak or Bépo layout
- Try to use evil-window-left with SPC w <key of the home row>

*Observed behaviour:* :eyes: :broken_heart:
evil-window uses the default qwerty keys: hjkl

*Expected behaviour:* :heart: :smile:
evil-window should use the keys of the homerow (ctsr in Bépo layout)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(csv ivy
     (auto-completion :variables auto-completion-enable-snippets-in-popup t)
     emacs-lisp git org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     (keyboard-layout :variables kl-layout 'bepo kl-disabled-configurations
                      '(magit))
     (latex :variables latex-enable-auto-fill nil)
     python finance)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by gvannoye** [comment]
#10358

**Comment by duianto** [comment]
Confirmed, the evil-window configuration keys, at least in the `:common` section are marked as:
https://github.com/syl20bnr/spacemacs/blob/ef1cecce0104a07577ee71d220065e9b09c2c5e5/layers/%2Bintl/keyboard-layout/packages.el#L177

On both the `master` and `develop` branches (that link is to the `develop` branch).

With the `kl-layout` layer variable set to: `'dvorak`
The Vim like right hand navigation keys also seem to be shifted to the right once, compared to the standard vim navigation keys.

I'm not using the `dvorak` layout, so I'm probably not of much help.

In this thread:
Navigation keys in Dvorak layout #2443
At least two people mention that they have used dvorak for 10 years, and vim for several years (the second comment said more than 10 years). And they seem to be using the default dvorak locations for `j`, `k`, `h` and `l`.

https://github.com/syl20bnr/spacemacs/issues/2443#issuecomment-125745503
https://github.com/syl20bnr/spacemacs/issues/2443#issuecomment-126060959

So that might be an option.
