### ISSUE TITLE
Spacemacs themes not working

### ISSUE THREAD

**Issue by anihm136** [syl20bnr/spacemacs#12833]
#### Description :octocat:
Spacemacs themes are not working as expected. All themes default to a light background, with the expected dark color only on the current line. Tried with themes from themes-megapack, as well as the default spacemacs dark theme.

#### Reproduction guide :beetle:
- Start Emacs
- Change theme

*Observed behaviour:* :eyes: :broken_heart:
Background remains a light color for all themes

*Expected behaviour:* :heart: :smile:
Background should change to selected theme color

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5785f1788)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp python c-c++ csv java javascript html helm markdown org treemacs themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by it-is-wednesday** [comment]
How did you change the themes? If simply by smacking a `(load-theme 'theme-name)` line in you `.spacemacs`, then you can try using this instead:
```emacs-lisp
(spacemacs/load-theme 'theme-name :disable t)
```
The trick here is that Emacs themes stack [by design](https://www.gnu.org/software/emacs/manual/html_node/emacs/Custom-Themes.html). Try running `M-x customize-themes`; you'll probably see that more than one theme is applied. It can, as expected, cause some fuckery :)

The `:disable` parameter for `spacemacs/load-theme` "un-applies" all currently applied themes, then applies yours. Hope this was the problem ;)

**Comment by anihm136** [comment]
Right. This solved the issue for me. Thanks a lot!

**Comment by charlag** [comment]
i have the same issue but I didn't do `load-theme` manually and I checked `customize-themes`, there's only one applied.

**Comment by it-is-wednesday** [comment]
@charlag hmmm... mind sharing some more details? do you have the *exact* same issue?

**Comment by charlag** [comment]
I commented under another issue but i can't find it now.
I removed `custom-set-faces` from `custom-set-variables` and it worked. I am not sure how it got there in the first place.

**Comment by charlag** [comment]
Basically whatever light theme I selected had wrong background because it was stacked on top of weird background/foreground colors
