### ISSUE TITLE
Some org shortcuts are just ridiculously bad

### ISSUE THREAD

**Issue by gutsle** [syl20bnr/spacemacs#12858]
There is `SPC m h i` aka `, m i` for adding a new headline in org.

That means when I want to type a few headlines it goes like this:
* headlinetext
* `ESC , h i a`
* next headline text
* `ESC , h i a`
* third headline
and so on.

This is very cumbersome and I don't understand how this could be a good default for something that should probably be the default behavior of pressing RET.

**Comment by xuan-w** [comment]
You could press C-RET to start a new headline when in insertion mode no matter the current line is a headline or just normal text.

**Comment by it-is-wednesday** [comment]
It's a discoverability issue I guess. Any ideas for making it more easily discoverable, without people having to look at the layer documentation? Maybe print a message at the bottom messages panel for the first couple of times a user hits `, h i a`? Something like "you can also use `C-RET` for inserting new headlines".

**Comment by Apromixately** [comment]
@it-is-wednesday Is it necessary to have the involved keybindings? Why not just remove everything but C-RET?

**Comment by jr0cket** [comment]
Evil state has `, RET` for creating a heading in org-mode, which it the convenience shortcut. 

This keybinding is the 2nd in the list in the which-key menu. It's the 3rd keybinding from the top in the layer docs, so it should be easy to find.

`, h i` is the mnemonic keybinding that is grouped with other header activities. It follows the core Spacemacs approach to keybindings.   Removing that would be breaking the well thought out Spacemacs conventions.

`C-RET` is the classic Emacs keybinding that comes with org-mode.  Classic Emacs keybinding are not typically document in Spacemacs as they are covered in the documentation for upstream packages.

`RET` by itself is needed for creating new lines, such as for new paragraphs.  Replacing this so that it inserts a heading instead would cause confusion.

**Comment by Apromixately** [comment]
Hi jr0cket! :)

1. So `, RET` does something different.
Since you cannot navigate to the end of the line in normal mode this always cuts of at least one character. (This is a problem for multiple org shortcuts, try inserting a timestamp at the end of a line.) This could be fixed and then this might be an okayish shortcut but `ESC , RET i` will never be as good as `C-RET`.
2. I think it is counterproductive to have too many bindings for the same thing. They clutter up the lists in the transient mode window that helps finding useful things as well as the other lists which you have cited. You're saying it should be easy to find but if that was true this issue wouldn't exist. ;)
3. To me Spacemacs is about sane defaults and discoverability. I think the best shortcut should come first and now we can argue what that is if you want. :crossed_swords: 
4. Indeed my suggestion to use `RET` was a bad one. I tried that for a while and it turned out to be more annoying than useful.

**Comment by Apromixately** [comment]
Oh, btw, if you actually want to insert a timestamp at the end of a line the shortcut is
`C-u M-m m d t RET` ;)

**Comment by jr0cket** [comment]
`, RET` in normal mode works without cutting any characters from the current line in Spacemacs `develop` branch.  I can only assume you are using an older version of Spacemacs, or perhaps the `master` branch.  If that is the case, then I recommend you upgrade to `develop`.

All changes are pushed to Spacemacs `develop`, so if you are using master you would need to wait for a release before getting any keybinding changes.

I dont see any duplication of characters in the major modes I use and do not share your view that the are issue with the org-mode keybindings.  In org-mode there are 6 short-cuts surfaced at the top level in which-key, from approximately 130 keybindings across nearly 30 packages in the layer.  That seems really effective to me.

If you have any specific keybinding changes then I am sure the maintainers would be happy to receive a pull request for review.

You are also able to add your own custom keybindings in dotspacemacs/user-config.  I had many of these to start with and with in few months they had mostly become redundant.
 
The Emacs keybindings are not removed from packages, so you can always use them if you prefer (assuming a package comes with keybindings).  There is no requirement to use Evil (vim style editing) for Spacemacs, however, I moved to Evil after a month of using Spacemacs as its much more efficient and consistent.

Your comments suggest you do not prefer using the keybindings to switch between Evil normal and insert states. In that case you may find it preferable to use the Holy mode rather than Evil.  Having moved from Emacs to Evil / Vim style editing myself, it was a challenge at first, but now I am far more productive than I ever was with Emacs keybindings and editing style.

**Comment by jr0cket** [comment]
I am afraid this is become a general conversation and not a specific issue, therefore I recommend the issue be closed and conversation continued on Gitter.

**Comment by Apromixately** [comment]
@jr0cket That's strange. I am on develop and I definitely get this behavior. To illustrate, I have create a new file and added this line:
`* some headline`
Pressing `, RET` anywhere on the line splits it at that position. Moving past the end is not possible with the standard config. Nor is `org-insert-heading-respect-content` set. Maybe you have something like that?
