### ISSUE TITLE
Update keyboard layout on master?

### ISSUE THREAD

**Issue by kittipatv** [syl20bnr/spacemacs#12872]
#### Description :octocat:
Update keyboard layout on master

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Workman keyboard layout is not available

*Expected behaviour:* :heart: :smile:
Keyboard layouts from develop branch should be merged to master. Last code change was 9 months ago.

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 0ad12701f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp
     (keyboard-layout :variables kl-layout 'workman))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
I suspect that individual layers won't be updated before the next version is released.
(I don't have any insight into when it will be released, but it's being worked on).

The suggestion until then is to use the `develop` branch as stated in this issue:
Change web page to install develop instead of master https://github.com/syl20bnr/spacemacs/issues/12672

If you have a current setup on the `master` branch, then back it up first, then make sure that there isn't a `.emacs.d` dir or a `.spacemacs` file in your home directory and clone directly to the `develop` branch:
```
git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
```
