### ISSUE TITLE
Error with flycheck package

### ISSUE THREAD

**Issue by bepolymathe** [syl20bnr/spacemacs#12871]
Hello,

I have a problem withcheck-package. How can i reinstall it or solve the problem ?

```
(Spacemacs) --> installing package: flycheck-package@emacs-lisp... [1/1]
Contacting host: elpa.gnu.org:443
(Spacemacs) Error: 
An error occurred while installing flycheck-package (error: (file-error https://elpa.gnu.org/packages/let-alist-1.0.6.el Bad Request))

```

**Comment by duianto** [comment]
Could you press `SPC h d s` in Spacemacs to copy your system info to the clipboard, and update your initial comment with it.

I'm getting the same error for different packages when I update the packages.

The latest occurred about 30 minutes ago.
>(Spacemacs) --> installing package: dotenv-mode@spacemacs-bootstrap... [2/7]
Contacting host: melpa.org:443
(Spacemacs) Error: 
An error occurred while installing dotenv-mode (error: (file-error https://melpa.org/packages/dotenv-mode-20191027.2129.el Bad Request))

Six other packages including `flycheck` were installed without any errors.

`dotenv-mode` was installed without any errors when I restarted Spacemacs.

This thread mentions a `Bad Request` error:
https://www.reddit.com/r/emacs/comments/cdei4p/failed_to_download_gnu_archive_bad_request/

It's supposed to have been fixed in Emacs 26.3 (which I'm using).
For older Emacs versions or for `libgnutls-version` versions greater or equal to `30600`.
(for me it shows: `libgnutls-version’s value is 30518`)
the solution was to add this to the `init.el` (or it might work in spacemacs from `dotspacemacs/user-init` in `.spacemacs`.
```elisp
(if (and (version< emacs-version "26.3") (>= libgnutls-version 30600))
    (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3"))
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 57721d8e7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm markdown multiple-cursors org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by bepolymathe** [comment]
Thanks for reply. The 

> space h d s

 command return : 

```
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d6c8df3d0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html helm
      (keyboard-layout :variables kl-layout 'bepo)
      (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
      better-defaults emacs-lisp markdown search-engine
      (org :variables org-protocol t)
      pandoc
      (shell :variables shell-default-height 45 shell-default-position 'bottom)
      spell-checking twitter syntax-checking
      (version-control :variables version-control-diff-tool 'diff-hl)
      ranger
      (elfeed :variables rmh-elfeed-org-files
              (list "~/.emacs.d/private/elfeed.org"))
      emoji graphviz deft bibtex gnus
      (latex :variables latex-build-command "latex" latex-enable-auto-fill t latex-enable-folding t)
      (mu4e :variables mu4e-enable-notifications t mu4e-enable-mode-line t mu4e-account-alist t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2

```

**Comment by bepolymathe** [comment]
Are you inspired @duianto  ?

**Comment by duianto** [comment]
In this Melpa issue: Bad Request error https://github.com/melpa/melpa/issues/6091#issuecomment-477328950

There's a comment:
>I've heard of melpa.org becoming unresolvable if using Google's DNS resolvers (8.8.8.8 and 8.8.4.4).

I was using googles dns' as primary: `8.8.4.4` and secondary: `8.8.8.8`
I switched to Cloudflares dns: `1.1.1.1` as primary
and IBMs dns `9.9.9.9` as secondary.

Here's an article that describes some differences between them.
https://roguemedia.co/2019/10/25/how-and-why-to-re-rout-dns-through-your-computer-or-phone/

I just updated the Spacemacs packages in the Linux vm and there were no issues with any of the 5 packages.

But I'm not sure if I've gotten the bad request error every time, so it might be intermittent.

I'll use these dns' for a while to see if it happens again.

**Comment by duianto** [comment]
This might be a duplicate of this issue:
Package undo-tree is unavailable and Failed to download 'gnu' archive. Bad request. (Solution included) #12535

**Comment by bepolymathe** [comment]
Thanks for your help, but I don't think it came from there. I have `gnutls-utils` installed well.

**Comment by bepolymathe** [comment]
I still have this message... grrr
`
File mode specification error: (file-missing Cannot open load file Aucun fichier ou dossier de ce type flycheck-package)
`

**Comment by duianto** [comment]
It seems to be this issue:
https://stackoverflow.com/questions/58202993/emacs-failed-to-verify-signature-archive-contents-sig

The signature expired on sept 23.
It's supposed to have been fixed in Emacs 26.3.

You can check the current signature by calling `gpg package-keyring.gpg`
from the `emacs/etc/` directory.

For Emacs versions older than 26.3, it might work to install the package:
http://elpa.gnu.org/packages/gnu-elpa-keyring-update.html

or by trying one of the instructions from the linked page above:
>If your keys are already too old, causing signature verification errors when
installing packages, then in order to install this package you can do the
following:

- Fetch the new key manually, e.g. with something like:

      gpg --homedir ~/.emacs.d/elpa/gnupg --receive-keys 066DAFCB81E42C40

- Modify the expiration date of the old key, e.g. with something like:

      gpg --homedir ~/.emacs.d/elpa/gnupg \
          --quick-set-expire 474F05837FBDEF9B 1y

- temporarily disable signature verification (see variable
  `package-check-signature').

**Comment by bepolymathe** [comment]
Ok, thanks... i discover the let-alist folder missed in .emacs.d/elpa 
Maybe this is the problem too... how can reinstall this ?

**Comment by duianto** [comment]
Check if the `let-alist` directory has an empty file (size `0`).

I've seen packages that have been installed like that.
Removing that package directory and restarting should reinstall the package correctly.

Maybe it's caused when multiple packages are being installed. I might only have observed it while installing all packages the first time after cloning Spacemacs.

**Comment by bepolymathe** [comment]
No, the folder is not empty :thinking: 

![image](https://user-images.githubusercontent.com/29939805/68391713-7fc40200-0168-11ea-89b9-b16cc0fee7fd.png)

**Comment by bepolymathe** [comment]
Donc je supprime l'ensemble du dossier "let-alist-1.0.6" ?

**Comment by duianto** [comment]
`let-alist.el` `0 octet` <--- problem
Yes, deleting the whole directory should reinstall the package on restart.

**Comment by bepolymathe** [comment]
Well then I don't have any more error messages but it didn't recreate this folder for all that.... 

Spacemacs seems to start normally... but I guess things don't work anymore without a package... how to check?

**Comment by duianto** [comment]
If your not getting any errors and everything seems to work then it it works 😄 

Your system info said that your using Emacs 26.2. If your able to install/compile 26.3 then it shouldn't need the package installation workarounds.

**Comment by bepolymathe** [comment]
Ok, thanks a lot. I will check for that.
