### ISSUE TITLE
Spacemacs freezes on initial launch when window is maximized on Windows 10

### ISSUE THREAD

**Issue by avggeek** [syl20bnr/spacemacs#12882]
#### Description :octocat:
I am seeing an extremely odd behaviour with spacemacs when I try to launch it as a maximized window, if I have an emacs daemon running. The window will launch but will be frozen for up to 2 minutes before it recovers. Once it recovers, the status message will say it was launched in 11 seconds but this is really only the daemon start time. Even more puzzling, subsequent invocations of spacemacs are extremely fast as is expected with a running daemon.

#### Reproduction guide :beetle:
- Install Emacs25.3 using Chocolatey
- Install spacemacs and create spacemacs dotfile
- Add following snippet to .spacemacs
`
(setq default-frame-alist
             '((fullscreen . maximized)))
`
- Launch emacs daemon using the following command `%ChocolateyInstall%\lib\emacs64\tools\emacs\bin\runemacs.exe --daemon`
- Once emacs daemon has completed loading, run `emacsclientw.exe` using the following command `%ChocolateyInstall%\lib\emacs64\tools\emacs\bin\emacsclientw.exe -n -e "(raise-frame)" -a "%ChocolateyInstall%\lib\emacs64\tools\emacs\bin\runemacs.exe"`

*Observed behaviour:* :eyes: :broken_heart:
Since this is very hard behaviour to describe in text, I have attempted to take a (very poor) movie capture of the entire process. It can be seen in this Youtube video (apologies again for the poor quality of video):

[![](http://img.youtube.com/vi/y9PotTRDYpg/0.jpg)](http://www.youtube.com/watch?v=y9PotTRDYpg "Spacemacs")

*Expected behaviour:* :heart: :smile:
- Spacemacs will launch with minimal delay and be responsive from first invocation

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by duianto** [comment]
It should not take that long to start.

I'm using the latest version Emacs 26.3 in Windows 1903:
https://www.gnu.org/software/emacs/

Spacemacs starts within 10 seconds on both the `master` and `develop` branches.

But the suggestion until the next version of Spacemacs is released is to use the `develop` branch.
Source: Change web page to install develop instead of master https://github.com/syl20bnr/spacemacs/issues/12672

Backup your current setup, then make sure that there isn't a `.emacs.d` dir or a `.spacemacs` file in your home directory and clone directly to the `develop` branch:
```
git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
```

You can copy over your configurations when everything is up and running.

**Comment by avggeek** [comment]
@duianto Thank you for the suggestions! I did the following steps:

- Backed up, then deleted the existing `.spacemacs` and `.emacs.d` directory
- Cloned the spacemacs develop branch as you suggested above.
- Installed emacs 26.3 on Windows 10 1903 using MSYS2.
- I then launched the existing emacs 25.3 to re-initialize spacemacs.

Here is the behaviour I saw:
- I did see improved start-up times on emacs 25.3 
- emacs 26.3 seemed to re-download all the spacemacs layers and did not display the spacemacs graphic on the `spacemacs` buffer.

Next I added the snippet `(setq default-frame-alist '((fullscreen . maximized)))` to my `.spacemacs`. The behaviour I now saw was:
- After I launch emacs 26.3 in `--daemon` mode, `emacsclient` starts immediately and correctly maximises to full-screen.
- After I launch emacs 25.3 in `--daemon` mode, `emacsclient` continues to freeze for up to 2 minutes at time.

Unfortunately, installing MSYS2 seems to be breaking other MINGW apps that I have installed so I may have to drop back to emacs 25.3 😞

**Comment by duianto** [comment]
The MSYS2 version of Emacs might not have image support.
The startup image is a `.png`. To check if your Emacs version has png support, evaluate:
```elisp
(image-type-available-p 'png)
```

The packages are re-downloaded because the develop branch puts them in a Emacs version sub-directory.

I've installed the/some packages that Emacs uses through https://www.cygwin.com/
If you haven't tried it already and there aren't issues with it, then it might be something to try.

I think I've also installed MSYS2 since then, there might have been some package instructions that suggested.

**Comment by avggeek** [comment]
I was seeing some very inconsistent behavior and decided to start afresh by doing the following:

- Deleted my existing `.spacemacs` and `.emacs.d` files/folders
- Uninstalled MSYS2/Emacs 26.3
- Cloned the spacemacs develop branch
- Ran Emacs 25.3 with a stock `.spacemacs` configuration first as a baseline.
- Next I added `(setq default-frame-alist '((fullscreen . maximized)))` to my `.spacemacs` config.
This resulted in a freeze on launch as before.

- Removed the `default-frame-alist` setting and instead used `dotspacemacs-maximized-at-startup t`
