### ISSUE TITLE
Modeline bug when changing font size.

### ISSUE THREAD

**Issue by equwal** [syl20bnr/spacemacs#12966]
Changing a font size after loading Spacemacs messes up the mode line, since it is not able to resize itself dynamically. So upsizing your font requires restarting Emacs (and it should not).

A workaround is to scale it up to the largest font size you might use in a session (expanding the mode-line's height), then downsize after load.

![image](https://user-images.githubusercontent.com/13551856/69205651-6f643d80-0aff-11ea-8fb6-507701064d00.png)

# Reproduction
```emacs-lisp
;;; Run this after loading your Spacemacs
(set-face-attribute 'default nil :height (* 24 10))
```
# Workaround
```emacs-lisp
;;; Put this in a config.el somewhere in your layers.
(set-face-attribute 'default nil :height (* 24 10))
;;; Make sure that this thing runs after the mode line loads (eg. by keybinding it).
(set-face-attribute 'default nil :height (* 12 10))
```
**Edit: improved workaround**
Use:
```emacs-lisp
(defun spacemacs/set-face-attribute (face frame &rest attributes)
  "Set the FACE (eg. 'default) for the FRAME (eg. nil). See `set-face-attribute'.
ATTRIBUTES should be valid entries in `set-face-attribute'."
  (apply #'set-face-attribute face frame attributes)
  (powerline-reset))

;; point * 10
;; Fix bug with mode line: Scale it up before we scale down the font.
(spacemacs/set-face-attribute 'default nil :family "Hack"
                              :height (* 24 10))
```

**Comment by duianto** [comment]
It might not be relevant, but when I searched for `refresh font` in Spacemacs I found this entry:
https://github.com/syl20bnr/spacemacs/blob/8fcc9d849044dca6e69ff3f7bda89f82abf848b7/layers/%2Bthemes/colors/funcs.el#L33-L44

**Comment by equwal** [comment]
> It might not be relevant, but when I searched for `refresh font` in Spacemacs I found this entry:
> 
> https://github.com/syl20bnr/spacemacs/blob/8fcc9d849044dca6e69ff3f7bda89f82abf848b7/layers/%2Bthemes/colors/funcs.el#L33-L44

Well just running the code does not fix the modeline. Maybe calling the right `font-lock` function on the modeline could do it. Or it may be a red herring.

**Comment by equwal** [comment]
Another interesting fact is `(spacemacs/compute-powerline-height)` is modified. However, I cannot find anything for powerline _width_ which looks more like the problem.

**Comment by equwal** [comment]
After some poking around, running `(spacemacs//restore-powerline (current-buffer))` has desirable behaviour (formats the powerline without modifying font size).

**Comment by duianto** [comment]
The fix doesn't seem to be working for me.

The modeline looks the same (to short wave separators) as in your screenshot.
In both Linux and Windows.

With that suggested `spacemacs/set-face-attribute` function.
And calling the function with the same values as in your suggestion.

Except with another font family, I don't have the Hack font installed.

The issue was tested and observed with these font's:
Linux:
DejaVu Sans Mono, Fira Mono, FreeMono, liberation Mono

Windows:
Arial, Consolas, Courier New, Lucida Console

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cab1e6958)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 python
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cab1e6958)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence "jk")
 (colors :variables)
 command-log emacs-lisp git helm json java javascript markdown multiple-cursors
 (org :variables)
 python react shell spell-checking syntax-checking treemacs typescript version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>
