### ISSUE TITLE
Spacemacs keeps removing ccls

### ISSUE THREAD

**Issue by kangjianbin** [syl20bnr/spacemacs#12968]
#### Description :octocat:
Spacemacs keeps removing ccls when starts.
I had set c-c++-backend to lsp-ccls.

I tried to add ccls into list dotspacemacs-additional-packages, but seems it didn't work either.

#### Reproduction guide :beetle:
- Start Emacs
- Install ccls with package-install
- Restart emacs

*Observed behaviour:* :eyes: :broken_heart:
ccls is removed.
```
(Spacemacs) --> deleting ccls... [1/1]
Package ‘ccls-20190414.402’ deleted.
```

*Expected behaviour:* :heart: :smile:
Spacemacs shouldn't remove ccls

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a2fbb3d94)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(graphviz yaml windows-scripts org html javascript typescript python markdown
          (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-adopt-subprojects t)
          auto-completion
          (go :variables go-format-before-save t go-backend 'lsp)
          git better-defaults csharp html ivy syntax-checking emacs-lisp lsp cmake)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS

#### Backtrace :paw_prints:
No backtrace. But I can see this message:
```
(Spacemacs) --> deleting ccls... [1/1]
Package ‘ccls-20190414.402’ deleted.
```

**Comment by cormacc** [comment]
Why not add via c-c++ layer, by setting backend to lsp-ccls? Or had you tried this already and were trying to work around sn issue?

**Comment by kangjianbin** [comment]
Yes, I had tried this. Please see my layers in my previous note:
```
(graphviz yaml windows-scripts org html javascript typescript python markdown
          (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-adopt-subprojects t)
          auto-completion
          (go :variables go-format-before-save t go-backend 'lsp)
          git better-defaults csharp html ivy syntax-checking emacs-lisp lsp cmake)
```

**Comment by cormacc** [comment]
Hmmm just opened a C project after a few days in python and running into issues with ccls myself. Not what you describe, but stalls, and repeated `LSP :: Not indexed` messages.

I've just dropped back to clangd for now. Will take a look again when I've time, but it'll be a few weeks  before I've the time -- one man software dept with a looming deadline.

**Comment by kangjianbin** [comment]
After git bisect, I find that this commit introduces the problem: 06cf8e384215156f070ccfc1ec3fc983e5eb3509

```
diff --git a/layers/+tools/lsp/packages.el b/layers/+tools/lsp/packages.el
index 63db7fac9..a0fc2bc16 100644
--- a/layers/+tools/lsp/packages.el
+++ b/layers/+tools/lsp/packages.el
@@ -11,7 +11,7 @@

 (defconst lsp-packages
   '(
-    lsp-mode
+    (lsp-mode :requires yasnippet)
     lsp-ui
     (company-lsp :requires company)
```

It requires yasnippet package for lsp-mode; however I don't use yasnippet and exclude this package.

Is it a bug that we force user to install yasnippet when lsp-mode is enabled?

**Comment by kangjianbin** [comment]
After enable yasnippet, I find another bug. When c-c++-backend is set to lsp-ccls, I get this error message when emacs starts:

```
Error (use-package): ccls/:config: Symbol’s function definition is void: spacemacs/dap-bind-keys-for-mode
```
Don't know what is the problem. My workaround is remove c-c++backend and configure ccls myself.

**Comment by duianto** [comment]
A similar error message `spacemacs/dap-bind-keys-for-mode` can be found here:
Error (use-package): cquery/:config: Symbol’s function definition is void: spacemacs/dap-bind-keys-for-mode #12784

The issue was posted before the `c-c++` refactoring changes were pushed to the develop branch.

The last comment says:
>Thanks. I think this issue is now moot since spacemacs/dap-bind-keys-for-mode no longer exist anywhere.

**Comment by emacs18** [comment]
Near the top the spacemacs version in question is reported as being a2fbb3d94 on develop branch.
This version does not have spacemacs/dap-bind-keys-for-mode symbol anywhere, so I don't understand how one could run into "definition is void" error regarding this symbol.  The symbol was removed on Nov 9.  The version mentioned in this issue is from Nov 18.

**Comment by emacs18** [comment]
Regarding automatic removal of packages ...

I personally change the default value 'used-only to 'used-but-keep-unused for
dotspacemacs-install-packages variables to prevent spacemacs from deleting packages it thinks are not used.  This is so that I can start emacs with or without spacemacs enabled.
