### ISSUE TITLE
`P` wants to paste in magit buffer

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#12961]
In a magit buffer: Since a couple of days when I want to push a commit (via `P`), magit complains that the buffer is readonly. Checking the binding says that `P` in the magit buffer is bound to `spacemacs/evil-mc-paste-before`. I cannot find any related configuration in my `.spacemacs`. What works is pressing `?` in the magit buffer and then `P` from the popup buffer with all the possible commands.

**Comment by leezu** [comment]
https://github.com/syl20bnr/spacemacs/commit/6556cfc80d4ba070c7385f44f932fbe2b97c0663 is at fault here. Please revert it

**Comment by duianto** [comment]
Strange.
`p` or `P` in a magit buffer opens the Push transient popup for me in both Linux and Windows on the latest develop branch with updated packages.
With or without the `multiple-cursors` layer enabled.

I've pushed a couple of commits since the multiple-cursors improvements commit without getting any errors.

`evil-mc` is not listed as a minor mode in the magit buffer `SPC h d m` for me.

Do both of you have any evil-mc user configurations?
And could you post your system info (`SPC h d s` copies it to the clipboard).

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e96b899da)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 python
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e96b899da)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence "jk")
 (colors :variables)
 command-log emacs-lisp git helm markdown multiple-cursors
 (org :variables)
 python shell spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by leezu** [comment]
Thanks @duianto. I used `(global-evil-mc-mode 1)` in my user-config. Disabling global mode fixes the issue.

**Comment by duianto** [comment]
@gdkrmr Are you using the same command?

**Comment by duianto** [comment]
The commit that caused the issue, might have fixed the need for using:
`(global-evil-mc-mode 1)`.

The PR author said:
>Fix evil-mc-mode won't start automatically

Improve multiple-cursors layer #12934

**Comment by gdkrmr** [comment]
> @gdkrmr Are you using the same command?

yes indeed and removing it fixed the issue! Thanks :+1:
