### ISSUE TITLE
What happened to the Coq layer?

### ISSUE THREAD

**Issue by qcfu-bu** [syl20bnr/spacemacs#12985]
From the Coq layer website it says that adding coq to dotspacemacs-configuration-layers is enough to install it. Is that site outdated? If so, is it possible to get the elisp files and restore coq layer functionality manually?

**Comment by duianto** [comment]
The `coq` layer is added as a new layer in the changelog.develop:
https://github.com/syl20bnr/spacemacs/blob/develop/CHANGELOG.develop#languages

So it's only be available on the `develop` branch at the moment:
https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/coq

The suggestion in the following issue, is to use the `develop` branch until the `master` branch is updated.
Change web page to install develop instead of master https://github.com/syl20bnr/spacemacs/issues/12672

If you have a current setup on the `master` branch, then back it up first, then make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
```
