### ISSUE TITLE
ESC not mapped in magit commit buffer

### ISSUE THREAD

**Issue by arnar** [syl20bnr/spacemacs#12980]
#### Description :octocat:
When I open a magit commit buffer (e.g. with `SPC g c c` or `SPC g c w`), it starts in insert mode and `ESC` does not work to go to normal mode.

`ESC` seems to be unmapped (`C-h k ESC` asks for further input).

`M-x evil-normal-state` does work, and after that evil mappings work fine, i.e. I can enter insert mode with `i` and get back to normal with `ESC`. `C-h k ESC` shows that it's correctly mapped to `(evil-force-normal-state)`.

#### Reproduction guide :beetle:
- Make an empty directory and `git init` (or use an existing repo)
- Start Emacs
- Open or create a file in the git repo and stage it.
- `SPC g c c` to open a commit message buffer.
- Hit `ESC`

*Observed behaviour:* :eyes: :broken_heart:
`ESC` is unmapped, asks for next key in chord.

*Expected behaviour:* :heart: :smile:
`ESC` escapes to normal mode.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3407ecde6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git markdown org spell-checking syntax-checking version-control themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON LCMS2

**Comment by duianto** [comment]
Do you have any Magit related user customizations?

I think `COMMIT_EDITMSG` buffer has opened in normal state for me ever since I started using Spacemacs 3+ years ago.

When I was first learning the evil bindings I thought that it might be better if it opened in insert state so that one could start typing.

But I've gotten used to it opening in normal state. It might have become a reflex to press `i` before starting to type. And `Esc` to start editing or confirming the commit message.

I just tested the issues reproduction steps in both Linux and Windows. And the commit buffer opens in normal state.

---

Did you mean to state the key bindings as `SPC g m c c`?

Because `SPC g c` calls `magit-clone`.

`SPC g m` calls `magit-dispatch` which opens the Magit transient buffer
With the key bindings sections:
- Transient and dwim commands
- Applying changes
- Essential commands

Where `c` calls commit.
And `c` (in the `Create` section) calls `Commit`, which opens the `COMMIT_EDITMSG` buffer.

### System Info

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cab1e6958)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 python
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cab1e6958)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence "jk")
 (colors :variables)
 command-log dap debug emacs-lisp git ivy json java
 (javascript :variables javascript-backend 'lsp)
 markdown multiple-cursors
 (org :variables)
 (python :variables)
 react shell spell-checking syntax-checking treemacs typescript version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by arnar** [comment]
Thanks! Turns out this bug shows up only on my employer's custom emacs distro, which is based on 26.3. Using debian's 26.1 distribution does not have this bug. So I'll file a bug internally.

But to answer:

I have no Magit related custom config. I just tried with a vanilla .spacemacs file on the dev branch, with the only change of enabling the git layer, and am able to reproduce (starts in insert mode, ESC not mapped).

Indeed I had a typo, I meant `SPC g s c c` (staging a change in the status buffer, if needed).
