### ISSUE TITLE
[Proposal] Spacemacs key bindings for regular users

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1298]
So, first we have `evil-mode` for Vim users; then we have `holy-mode` for Emacs users. Next, I propose a key binding layout for users of common editors out there, using ErgoEmacs keyboard layout: https://ergoemacs.github.io/gradual-adoption.html. 

Let's call this `mortal-mode`, the mode in between `evil` and `holy`.

**Comment by trishume** [comment]
Interesting idea, might also base the keybinds off of Sublime Text.
That thought also reminds me that #101 could be realized in holy-mode as well as mortal-mode since they won't use evil.

**Comment by syl20bnr** [comment]
Seens we have key bindings organized in layers with the leader, we have indeed the freedom to throw any layout in an evil state. We can call it `sublime state` or `cua state` or `ergoemacs state`. And then the `xxxxxx-mode` would basically do what holy mode does.
At this point we have to think about the generalization of `holy-mode`.

**BUT** I want to keep things simple so no fancy `(cond (xxxxxxx-mode) (holy-mode)` or anything like this outside the `holy-mode` and `xxxxxxxx-mode`, never ever. We will find compromises instead, like we did for Helm buffers.

**Comment by syl20bnr** [comment]
BTW, nice idea @tuhdo :-)

**Comment by boykov** [comment]
I tried to use my own config, based on ErgoEmacs, with Spacemacs. I removed all unnecessary stuff from the base spacemacs layer and left the solarized extension and few packages only, see https://github.com/boykov/spacemacs , spacecore branch. So, it turned to minimal Spacemacs config, which supports spacemacs core features.

**Comment by Immortalin** [comment]
Any progress on this or plans for official integration?

**Comment by boykov** [comment]
I note that instead of hypothetical `mortal-mode` one can use `core-mode` (in addition to his own emacs config with ErgoEmacs or something else). And I have mentioned how to easily create such minimalistic `core-mode`. I consider it as bootstrapping and organizing Spacemacs features that I can adopt to my own config.

**Comment by Foucl** [comment]
@boykov as far as I can see, your fork does no longer contain a spacecore branch and the eab-draft branch looks like a regular emacs-/holy-mode configuration (to my very untrained eye). Would you mind briefly pointing in the direction how such an integration (of ergoemacs and spacemacs) would work? Should this be realized as a [layer](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#configuration-layers) and adding ergoemacs as a package? Or should one rather somehow extract the ergoemacs keybindings and use those?

(I'm returning to emacs after being disappointed by Atom & Co)

**Comment by boykov** [comment]
@Foucl I've fixed the link in my comment. There is no spacecore branch now, I use [spacemacs-core layer](https://github.com/boykov/spacemacs/tree/eab-draft/layers/%2Bdistribution/spacemacs-core) instead of it.

The main idea of my integration of ergoemacs and spacemacs is to use  **bootstrapping and organizing Spacemacs features** only. As you know spacemacs is "community driven" distribution with two main options for keybindings: emacs and vim. As far as there is no ergoemacs community (or another one with non-standart keybindings) yet, I use my personal emacs config as [spacemacs private layer](https://github.com/boykov/eab-spacemacs).

**Comment by ryukinix** [comment]
Haha this is really funny and a great idea. Mortal-mode is really a great name

**Comment by d12frosted** [comment]
Related: #5429.

**Comment by PhilipDaniels** [comment]
I have been working on my own set of keybindings to bring Emacs more in line with Windows defaults. The attempt is here https://github.com/PhilipDaniels/windows-defaults, it is structured as a Spacemacs layer. Feedback welcome.

**Comment by MarcusE1W** [comment]
@PhilipDaniels 
Works great for me. Is there a plan to make this an official layer ?
Mortal-mode sounds super cool

**Comment by PhilipDaniels** [comment]
@MarcusE1W There is no plan to integrate it into Spacemacs, at least, nobody has ever asked me. I actually stopped using Emacs/Spacemacs for all but vanilla editing about 6 months ago because I felt I was spending too much time configuring it and learning lisp compared to getting on with more productive things. The killer was when I built a new machine about 7 months later, installed Spacemacs, and found lots of packages I was using in my layers gave errors :-(

So I am not actively updating this package; if someone else wants to try and integrate it they are of course free to base their work on this. With Emacs 26 coming out, now might be a good time.

**Comment by MarcusE1W** [comment]
@PhilipDaniels 

Hmm, sorry to hear that Spacemacs was frustrating for you.
I only use your layer a few days but so far am quite happy with it.
No errors neither on Emacs 26.1

Currently I can't help with the layer as I have no idea about elisp, but maybe that improves.

Sometimes I change editors as well, so maybe on another day you give Spacemacs another try :wink: . 
Thanks for your effort with this layer.

**Comment by Renzix** [comment]
Would be cool to see simple keybinds based on something like micro. I also like the idea of mortal mode however we would just need people to do the work

**Comment by shaund** [comment]
It would be nice to have this implemented in Spacemacs by default.

**Comment by syl20bnr** [comment]
Let's keep this open, we could do something nice here by implementing a new evil state like we did with `holy-mode`.

**Comment by lunarfyre7** [comment]
+1! As someone who has been using spacemacs off and on for a little while now, I think having something like an ergoemacs layer would be great! Having "normal" bindings would be nice especially for new users transitioning from other editors like VSC, Sublime, etc.
