### ISSUE TITLE
documentation: `--with-natural-title-bars` isn't an option for `brew install emacs-plus`

### ISSUE THREAD

**Issue by camhashemi** [syl20bnr/spacemacs#12994]
this command in the installation section for macOS, but the option isn't found when running it
<img width="485" alt="Screenshot 2019-11-27 at 11 30 32" src="https://user-images.githubusercontent.com/8929238/69715911-5a903700-1109-11ea-8062-d805b37d65c1.png">

**Comment by duianto** [comment]
The `s` at the end was a typo.

But the Emacs Plus repository has since removed the `--natural-title-bar` command.
Therefore the Spacemacs `develop` branch readme also removed it:
https://github.com/syl20bnr/spacemacs/blob/develop/README.md#macos

The Emacs Plus repository has instructions for duplicating that flags behavior:
https://github.com/d12frosted/homebrew-emacs-plus#upgrade-from-emacs-25x

The Spacemacs `master` branch readme will be updated when the next version is released 
(I don't have any insight into when that is)
