### ISSUE TITLE
use of undefined 'result' within spacemacs/window-state-walk-windows-1

### ISSUE THREAD

**Issue by emacs18** [syl20bnr/spacemacs#13001]
layers/+spacemacs/spacemacs-layouts/funcs.el on develop branch has the following function which refers to 
'result' variable on the last line.  This is not defined anywhere.  Thus if 'SPC b W' command
were to be executed, the result is "setq: Symbol’s value as variable is void: result" error.

```
(defun spacemacs/window-state-walk-windows-1 (window fn)
  "Helper function for `spacemacs/window-state-walk-windows'."
  ;; WINDOW is a misleading name. WINDOW is a list that can represent a window,
  ;; or a concatenation of several windows. window-state objects are weird.
  (let ((child-windows
         (-filter #'spacemacs/window-state-window-p window))
        (bare-window
         ;; if WINDOW contains more than one window, take only the first window
         (--take-while (not (spacemacs/window-state-window-p it))
                       window)))
    (--each child-windows
      (spacemacs/window-state-walk-windows-1 it fn))
    (push (funcall fn bare-window) result)))
```

**Comment by duianto** [comment]
Confirmed, `SPC b W` shows the `void: result` message.

Adding a `result` let binding (4th line from the bottom) seems to stop the void warning.
```elisp
(defun spacemacs/window-state-walk-windows-1 (window fn)
  "Helper function for `spacemacs/window-state-walk-windows'."
  ;; WINDOW is a misleading name. WINDOW is a list that can represent a window,
  ;; or a concatenation of several windows. window-state objects are weird.
  (let ((child-windows
         (-filter #'spacemacs/window-state-window-p window))
        (bare-window
         ;; if WINDOW contains more than one window, take only the first window
         (--take-while (not (spacemacs/window-state-window-p it))
                       window))
        result)
    (--each child-windows
      (spacemacs/window-state-walk-windows-1 it fn))
    (push (funcall fn bare-window) result)))
```

But I'm not sure how it's supposed to work.

`result` seems to only push `(funcall fn bare-window)` to it once.

Maybe the push expression is supposed to be inside the `--each` expression so that it might be called several times.

If it's only supposed to be called once, then the `result` variable and the `push` call seems like they could be removed.
Leaving only `(funcall fn bare-window)` as the last call.

I'm also not sure what the purpose is, of the `result` let binding and call to it at the end of the following function:
```elisp
(defun spacemacs/window-state-walk-windows (state fn)
  "Execute FN once for each window in STATE and make a list of the results.
FN is a function to execute.
STATE is a window-state object."
  (let (result)
    (spacemacs/window-state-walk-windows-1 (cdr state) fn)
    result))
```
Because `result` is `nil` at the end, therefore it seems like it would be the same to just call `nil` as the last call.

**Comment by emacs18** [comment]
If dynamic binding was in use, then I think all should work.
Typically this kind of problem is introduced when a file is converted to lexical binding by editing 
the first line of the file.

**Comment by emacs18** [comment]
I submitted PR #13012 to fix this by forcing use of dynamic binding for "result".

**Comment by emacs18** [comment]
This is now fixed after PR was checked in.
