### ISSUE TITLE
Docker tramp + lsp-clangd

### ISSUE THREAD

**Issue by maingoh** [syl20bnr/spacemacs#13018]
Is it is possible to use `lsp-clangd` inside a container using docker tramp and without installing anything inside the containers (and if possible without mounting files) ?

**Comment by yyoncho** [comment]
IIUC you want project to be in the container and the language server running on the local machine?

**Comment by maingoh** [comment]
Yes, I would like clangd to be able to analyze correctly the source files inside the containers, and to avoid adding extra dev tools inside the container (I can eventually add volumes)

**Comment by yyoncho** [comment]
@maingoh the only way to achieve that is to mount docker files locally(e. g. via sshfs). In order clangd to work, it has to have access to the file system containing the files.

**Comment by maingoh** [comment]
Any idea on how to achieve this ? Why sshfs ?
Currently, either I mount the files and edit them without docker tramp but clangd is not able to resolve the dependencies installed in the container, or I use docker tramp to edit the files but clangd is not working :/

**Comment by yyoncho** [comment]
@maingoh you should somehow make the files accessible to the server - they must be running on the same machine. This is how language servers work.

**Comment by KorribanMaster** [comment]
One possibility is to install clangd inside your container then add this to your `user-config` 
````
  (with-eval-after-load 'lsp-mode (lsp-register-client
  (make-lsp-client
    :new-connection (lsp-tramp-connection "clangd")
    :major-modes '(c-mode c++-mode)
    :remote? t
    :server-id 'clangd)))
````
If clangd is not on you path add this to `user-init`
````
(setq tramp-remote-path "path/to/clangddir"))
````

**Comment by maingoh** [comment]
@yyoncho The thing is, my app sources files are on the host. I mount them in the container that has the dependencies. Then I can compile everything inside the container using cmake/make. I would like clangd to do the same, but it doesn't have the dependencies. So maybe I should mount `/usr/include` from my container to the host and somehow tell clangd where to look for the includes ?
Would https://clang.llvm.org/extra/clangd/Installation.html#compile-commands-json help ?

@KorribanMaster Yes I could install dev things in the container but the goal was to avoid installing dev tools in the container image.

**Comment by yyoncho** [comment]
@maingoh something like that might work.

**Comment by erichlf** [comment]
@maingoh Have you figured this out? I am trying to do the same thing. I have seen lsp-docker as one solution, but the documentation seems a bit lacking in my mind.

**Comment by maingoh** [comment]
Unfortunately I didn't have time to dig into it and I am not so much an expert on this field .. But If you find something let me know :smile:

**Comment by maingoh** [comment]
lsp-docker is probably the good solution but seems to be young, maybe open an issue there ?

**Comment by erichlf** [comment]
Unfortunately, they don't have issues enabled over there, but I do see that @yyoncho is a developer on that project. 

@yyoncho Could you help me translate the settings from the README into what I would do in .spacemacs?

**Comment by maingoh** [comment]
It is because it's a fork, you might be able to create an issue on the main repo https://github.com/emacs-lsp/lsp-docker

**Comment by erichlf** [comment]
ha! I didn't notice that. Maybe that was why I had multiple tabs open to lsp-docker. :)

**Comment by yyoncho** [comment]
> @yyoncho Could you help me translate the settings from the README into what I would do in .spacemacs?

What do you want to achieve?

**Comment by erichlf** [comment]
I would like to accomplish the same thing maingoh was trying, but when I read the README at lsp-docker it doesn't make much sense to me. That is my code base is mounted in a docker container at `/checkout/src` which corresponds to the host location `~/<path to my source>`. This would be easy if that was all there was too it, however the docker container has its own `/usr/include` which is separate from the host machine, so that makes things more complicated. So in the end I would like auto-completion and code jumping to work for such a setup. 

The README doesn't really seem to give me a clue to how to set things up, such that this works within spacemacs. I think mostly because I am pretty new to spacemacs and have no real knowledge of emacs. So to accomplish what I want, what would that look like using lsp-docker or is lsp-docker even the right tool? Additionally, It seems like the most useful thing would be to have lsp-docker specific to a project (not all my projects are docker based after all).

**Comment by erichlf** [comment]
So in this case `clangd` is running in the docker client not the host machine?

**Comment by yyoncho** [comment]
yes.
