### ISSUE TITLE
autocomplete + yasnippet ... with help-tooltip ?

### ISSUE THREAD

**Issue by err0r500** [syl20bnr/spacemacs#13035]
Hello,
Is it possible to have help-tooltip with yasnippet ? 
It works fine with other packages, like lisp for example (ie tooltips are displayed when I edit .spacemacs file) but I'm unable to get it working with yasnippet : the autocomplete shows the `key` field of the snippets but nothing else.

I use the develop branch.
Someone has been able to get it working ? 
Best,
Matthieu

**Comment by duianto** [comment]
It seems like you solved it by using company instead of autocomplete.
https://www.reddit.com/r/emacs/comments/e88k1c/autocompletionenablehelptooltip_with_yasnippets/

For future reference, it helps to update questions/issues with any solutions/workarounds you've found, to help the next person that finds it and wonders if you found a solution.
