### ISSUE TITLE
Zooming while the line numbers enabled messes up lines

### ISSUE THREAD

**Issue by gerroon** [syl20bnr/spacemacs#13031]
maximized window - spc-t-n ->  spc-z-x -> ++++++

`dotspacemacs-maximized-at-startup t`

This above combination makes the workspace totally useless , please see the image to see what is going on when done.

I am using Emacs  on Win x64 10
`GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29`

Bwt I cant file a bug in Emacs because it has no internet access so filing it here.

![raw](https://user-images.githubusercontent.com/8519469/70369662-ae75eb00-1882-11ea-994d-84bcf4864988.jpeg)

**Comment by duianto** [comment]
This is a known issue with the linum package. The Spacemacs `develop` branch uses the built in line numbers that are included with Emacs 26.

This issue has a possible workaround on the `master` branch.
Weird behaviour when changing font size with line numbering turned on #12401

Or if you could switch to the `develop` branch then a lot of things have been fixed.

Here's the changelog:
https://github.com/syl20bnr/spacemacs/blob/develop/CHANGELOG.develop

The `develop` branch is the recommended branch to use until the next version is released, as discussed in this issue:
Change web page to install develop instead of master https://github.com/syl20bnr/spacemacs/issues/12672

Backup your current setup, then make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
```

**Comment by gerroon** [comment]
Thanks for the reply with solutions. I will try those.
