### ISSUE TITLE
'gq' is inconsistent

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#1304]
In vim <kbd>gq{motion}</kbd> reformats the lines {motion} moves over, it's handy to reformat function call when the list of arguments grows too long to fit the line. In vim, possibly due to language-specific plugins, that takes care of indentation as well so the next line is properly aligned with parenthesis and whatnot. In spacemacs it leaves the second line badly hanging which in some cases is syntax error, e.g.

```
call(one, two, three)
```
vim:
```
call(one, two,
     three)
```
spacemacs:
```
call(one, two,
three)
```

I noticed that while python and haskell files get badly reformatted the indentation is properly applied in javascript, ruby and .c files. Of the previous languages I only have python, haskell, and javascript layers loaded which makes the inconsistent behaviour seem rather strange.

**Comment by swaroopch** [comment]
Perhaps this issue should be reported upstream to evil-mode? https://bitbucket.org/lyro/evil/wiki/Home

**Comment by syl20bnr** [comment]
Thank you for the report, as @swaroopch wrote.
@tko can you post a reference to the upstream issue here so we can track it ?

**Comment by TheBB** [comment]
This appears to be a difference between `fill-region` and `fill-paragraph`. Note that `fill-paragraph` behaves as expected. Since this issue has been open for a while and no upstream report has happend, I will close it.

Note, however, `M-q` (`fill-paragraph`) does work as desired. It just doesn't accept a region.
