### ISSUE TITLE
Add evil-rails to the ruby layer

### ISSUE THREAD

**Issue by naliwajek** [syl20bnr/spacemacs#1308]
Hey,

If I see correctly, [evil-rails](https://github.com/antono/evil-rails) isn't yet in the layer for Ruby language (yes, it doesn't work only in Rails but in other rake projects as well, AFAIR, at least the `:A` command described later does so).

I know those normal mode commands (like `:Rcontroller`, `:Rmodel` etc.) are pretty much covered by Spacemac's key-bindings, but maybe it'd be still OK to add them as an alternative? They are heavily used in the Vim world. 

At very least we should consider adding support for `:A` in _enh-ruby-mode_ since it's the most handy command from them all and I was really surprised when I saw a warning in my Rails repo that such command doesn't exist.

Thoughts?

**Comment by matDobek** [comment]
:+1:

**Comment by haerde** [comment]
:+1:

**Comment by naliwajek** [comment]
Thank you, people from my office :cat:

Maybe I will try to write a PR with some changes and then other folks will comment ;)

**Comment by trishume** [comment]
PRs are the best way to get your stuff into Spacemacs. Writing layers isn't hard.

**Comment by naliwajek** [comment]
@trishume will do so on a weekend. Thanks.

**Comment by syl20bnr** [comment]
PR welcome :-)
You don't have to write a new layer, add it to the ruby layer by adding `evil-rails` to `ruby-packages` in `contrib/lang/ruby/packages.el` then create a function `ruby/init-evil-rails`. Don't bother with making it lazy loaded, I can add it after merging your PR and I'll explain you what I did.

On a side note, this is a funny package, it is the first time I see a package focused on adding ex-commands, it makes sense but people in the emacs community don't think a lot about this because you can already call any interactive elisp function.
