### ISSUE TITLE
Turn off evil-lisp-state

### ISSUE THREAD

**Issue by frankiesardo** [syl20bnr/spacemacs#1309]
For of all thanks for all the effort you're putting in this great kit. I imagine maintaining it is not exactly a walk in the park now.

My only complain/source of confusion is about `evil-lisp-state`. As a user far from being power I find having to manage yet another state quite difficult, especially since the distinction between normal-state and lisp-state is so blurred. 

I would actually like to make evil-lisp-state replace normal state when editing a lisp file (by this I mean normal state disappears). Would it be possible? If it is, would you recommend it? I fail to understand why normal-state and lisp-state should coexist together, or what you actually miss from the normal state while in lisp state that can you cannot use. When I picked up this kit I expected the lisp part interaction behave more like [this](https://github.com/expez/evil-smartparens), sort of redefining the vi deletions/movements to play nice with sexps.

Maybe some more documentation or a quick rationale could help me and others understand why it's set up the way it is (especially coming from a fellow lisper).

**Comment by syl20bnr** [comment]
`evil-lisp-state` is at the version 7 and the first versions were about what you described: replacing totally the normal state. I tried a lot of different configurations for it and the conclusion was that it is impossible to replace normal state because there is always something missing. If you are interested you can clone the [repo](https://github.com/syl20bnr/evil-lisp-state) and throw [git timemachine](https://github.com/syl20bnr/spacemacs/tree/master/contrib/git#git-time-machine) at it in the `README.md` file (`SPC g t`), you'll be able to see the various approaches that was tested.

**Comment by syl20bnr** [comment]
By the way, to turn off evil-lisp-state, add it to `dotspacemacs-excluded-packages` variable in your dotfile.

**Comment by frankiesardo** [comment]
Thanks for your explanation. Have you also considered having the smartparens trigger a micro-state? It would be nice to chain sexp manipulation without the additional cognitive load of another state.
