### ISSUE TITLE
Helm M-x, Recent Files not fuzzy matching

### ISSUE THREAD

**Issue by FelipeCortez** [syl20bnr/spacemacs#13100]
#### Description :octocat:
Fuzzy mode not enabled for Helm M-x, Helm Recent Files. In another computer with the same version of Emacs / Spacemacs it works as expected. Fuzzy matching is enabled and works as expected for Helm Find Files, Helm Apropos, Helm Projectile. I've tried switching to Ivy and I get the same behavior. I've also tried deleting `~/.emacs.d`, `~/.spacemacs` and reinstalling to no avail.

#### Reproduction guide :beetle:
- Start Emacs
- Open a new buffer with `SPC b N`
- Open Helm M-x with `SPC SPC`
- Try to select `org-mode` by typing `orgmode`

*Observed behaviour:* :eyes: :broken_heart:
No command is found. "org mode" does match "orgmode", but that is not the behaviour I was used to and how Helm Find Files, Helm Projectile, etc work.

*Expected behaviour:* :heart: :smile:
Lots of commands are found, including `org-mode`.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
I'm seeing the same thing on the latest develop branch with updated packages.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 473d019b4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm markdown multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/notes.org"))
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by duianto** [comment]
The variable `helm-completion-style` is set to `emacs` by default.

Setting it to `helm-fuzzy`:
```elisp
(setq helm-completion-style 'helm-fuzzy)
```
highlights `org-mode` when typing `orgmode` in the `Helm M-x` prompt.

**Comment by FelipeCortez** [comment]
Not in 0.200.13, apparently:

![2019-12-19-115511_372x599_scrot](https://user-images.githubusercontent.com/718515/71183284-7c876000-2256-11ea-9e03-a967a8e9c6b5.png)

Let me try 0.300

**Comment by duianto** [comment]
This is what it looks like for me:

![emacs_2019-12-19_15-59-16](https://user-images.githubusercontent.com/13420573/71183761-d7ca4a00-2278-11ea-89ae-0d9937007f7a.png)

**Comment by FelipeCortez** [comment]
Just tried the develop branch and could not reproduce :(

**Comment by duianto** [comment]
Have you updated the packages?
The latest version of helm is:
`helm-20191217.1347`

**Comment by duianto** [comment]
I'm seeing the same/similar outcome as you without Spacemacs, with just Emacs and helm.

![helm-completion-style helm-fuzzy, without spacemacs](https://user-images.githubusercontent.com/13420573/71185201-427c8500-227b-11ea-895f-c3885dd7bf62.png)

**Comment by duianto** [comment]
I commented out everything in my user-config and am still getting `org-mode` as a result.

**Comment by FelipeCortez** [comment]
Just checked and that's the version of helm I have on my machine. I still can't get it to work

**Comment by duianto** [comment]
It might be a Linux vs Windows difference. I tested it in a virtualbox VM: `Pop!_OS 19.10`

Typing `orgmode` in the `HELM M-x` (`SPC SPC`) buffer, with the variable:
`helm-completion-style` set to:
- `emacs`, shows no candidates
- `helm-fuzzy`, there's a 12 second delay after typing `orgmode`, then it shows the same results as in your screenshot. The candidates start with `5x5`, `2C-split`, etc.

**Comment by FelipeCortez** [comment]
I'm going to try to roll back helm and see if any previous version fixes it

**Comment by duianto** [comment]
There's not a difference between the OS's.

While testing in Emacs 27.0.50, I didn't get `org-mode` as a candidate.

I realized that the first helm section for me is `Emacs Commands history` meaning that it lists recent commands. That's the same first section I saw in the Emacs 26.3 screenshot above https://github.com/syl20bnr/spacemacs/issues/13100#issuecomment-567524590

When I scroll to the next section `C-o`, that's called: `Emacs Commands`, then it lists the same commands as in your screenshot and in the Linux VM, `5x5`, `2C-split`, etc.

**Comment by duianto** [comment]
>If you are using emacs-27, you should try instead
>
>(setq helm-completion-style 'emacs)
>(setq completion-styles '(flex))

source: https://github.com/emacs-helm/helm/issues/2234#issuecomment-557902806

It seems to work:

![emacs_2019-12-19_20-16-39](https://user-images.githubusercontent.com/13420573/71202572-cb57e880-229c-11ea-821e-d9324a4cea5d.png)

**Comment by FelipeCortez** [comment]
Yes! This works! And it also seems to fix Helm Recentf. Thanks!

**Comment by smile13241324** [comment]
If this issue is still present we should make sure that spacemacs configures it properly for emacs 26.3 and emacs 27.x.

**Comment by smile13241324** [comment]
@duianto this could become a problem, basically the setting in `completion-styles` is used by company as well. Setting it to `'(basic partial-completion emacs22 helm-flex)` will break auto completion, i.e. `(meks)` will match a random set of functions. With `'(basic partial-completion emacs22)` it will match nothing.

Have you found a variable we could set without affecting company?

**Comment by duianto** [comment]
At the end of the docstring ([Full docstring](https://github.com/emacs-helm/helm/blob/84c67a83abef9962b346398030fc13aecb10bd66/helm-mode.el#L235)) for `helm-completion-style`, it says:
>For a better experience, if you don’t know what to use, set
‘completion-styles’ to ’(flex) if you are using emacs-27 or to
’(helm-flex) if you are using emacs-26 and keep ’emacs as default
value for ‘helm-completion-style’.  Advanced users can also have a
look to ‘completion-category-overrides’ to set styles according to category.

The last sentence says that `Advanced users` can use: `completion-category-overrides`
it might be something to look into.

### Limit the styles change to helm-M-x
Another option might be to only change the `completion-styles` when the `helm-M-x` buffer is opened.

Maybe something like this:
```elisp
  (defun custom/helm-m-x-completion-style (orig-fun &rest args)
    (let ((completion-styles
           `(,(if (version< emacs-version "27") 'helm-flex 'flex))))
      (message "helm-M-x: completion-styles: %s" completion-styles)
      (apply orig-fun args)))
  (advice-add 'helm-M-x :around 'custom/helm-m-x-completion-style)
```
While testing the advice can be removed with:
```elisp
  (advice-remove 'helm-M-x 'custom/helm-m-x-completion-style)
```
It seems to at least fix the issue authors example of searching for: `orgmode`

Tested in Windows 1903 with the same result in both:

<details><summary>
Emacs: 26.3
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c3f13d039)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm html imenu-list
            (java :variables java-backend 'meghanda)
            javascript latex lsp
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (syntax-checking :variables syntax-checking-enable-by-default nil)
            treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

<details><summary>
Emacs: 27.0.90
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.0.90
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c3f13d039)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm html imenu-list
            (java :variables java-backend 'meghanda)
            javascript latex lsp
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (syntax-checking :variables syntax-checking-enable-by-default nil)
            treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS PDUMPER LCMS2 GMP

</pre>
</details>

#### Before
![emacs_2020-04-04_15-37-27](https://user-images.githubusercontent.com/13420573/78452214-51e8d800-768a-11ea-8711-0b7a71ae89bd.png)

#### After
![emacs_2020-04-04_15-33-37](https://user-images.githubusercontent.com/13420573/78452218-56ad8c00-768a-11ea-85d0-d527ae533fba.png)


#### Question
Should the default styles also be included: `(basic partial-completion emacs22)`
instead of just `helm-flex` or `flex` (27)?

### HELM Recent files
The issue author mentioned that fuzzy matching wasn't working in HELM Recent files, but that might have been fixed.

Because when searching in `SPC f r`, for: `conlay` then it finds these:

![emacs_2020-04-04_15-59-24](https://user-images.githubusercontent.com/13420573/78452739-5662c000-768d-11ea-844c-10b971fea0ad.png)

Which seems to be working as expected.

**Comment by smile13241324** [comment]
@duianto I like your second solution, I have put it in helm-layer's func.el and replaced all references to Helm-M-x with the new function name.

This works pretty good on my side.

It introduces one small side effect though that is when Helm-M-x is open and the user switches to another buffer with `m-1` for example, the changed binding is visible to the rest of emacs. Looks like Helm-M-x forwards the commands through which causes our let to become parrent for all subsequent commands until the helm buffer is closed.

I think nobody will mind as I don't see any reason why would one work with an open helm command buffer in the background, but still for the record this is coming from this change.

Here is the function I have put to use:
```elisp
;; Command search ---------------------------------------------------------------------

(defun spacemacs/helm-M-x-fuzzy-matching ()
  "Helm M-x with fuzzy matching enabled"
  (interactive)
  (let ((completion-styles completion-styles))
    (add-to-list 'completion-styles `,(if (version< emacs-version "27") 'helm-flex 'flex) t)
    (command-execute 'helm-M-x)))
```

**Comment by smile13241324** [comment]
@FelipeCortez I think we finally have a global fix for this, would you mind having another look on this issue and close it if all is working now without setting the completion styles manually?

**Comment by FelipeCortez** [comment]
Seems to be working as expected for `Helm M-x`, but not for `Helm Recentf`: 

![2020-05-11-161756_334x329_scrot](https://user-images.githubusercontent.com/718515/81602867-be4ea980-93a3-11ea-9efb-e3480cdd0cde.png)

![2020-05-11-161924_364x153_scrot](https://user-images.githubusercontent.com/718515/81602875-c0186d00-93a3-11ea-906f-2e9a9b77bd34.png)

![2020-05-11-161942_401x124_scrot](https://user-images.githubusercontent.com/718515/81602881-c3abf400-93a3-11ea-8358-f55651ed33dc.png)

**Comment by smile13241324** [comment]
@FelipeCortez that's strange, can you give me some more context how you call helm-recentf? When I do `spc spchelm-recentfreturn` and enter `space` I am clearly getting fuzzy search. I am on emacs 26.1, hmm can be that this only happens with emacs 27?

Some more information, when I start helm-recentf and I leave the minibuffer with `m-1` and then check the content of `completion-styles` I am seeing: `(basic partial-completion emacs22 helm-flex)`. 

What do you see on your emacs session?

**Comment by FelipeCortez** [comment]
wow, I have no idea of what may have happened, but now it seems to be working. I see `(basic partial-completion emacs22 helm-flex)`

**Comment by smile13241324** [comment]
That's good news, then I will just close that ticket as done.
