### ISSUE TITLE
Elxiri tab background color wrong

### ISSUE THREAD

**Issue by sahina** [syl20bnr/spacemacs#13118]
When opening Elixir files (elixir layer installed) the Elixir tab background does not have the color of the bar as shown in the attached screen shots. i tried all the themes and always similar.

How can this be fixed?

![Screen Shot 2019-12-23 at 9 51 01 PM](https://user-images.githubusercontent.com/2219825/71390561-d7aab100-25ce-11ea-9d9d-db1c70424f23.png)

![Screen Shot 2019-12-23 at 9 57 35 PM](https://user-images.githubusercontent.com/2219825/71390681-41c35600-25cf-11ea-96a9-74d94e00fe3b.png)

**Comment by duianto** [comment]
It seems to be caused by `alchemist-mode`.

When it's toggled off: `M-x alchemist-mode`

Then the `Elixir` text on the modeline gets the same background color as the surrounding wave separators. The same color that's shown for other modes, like `Emacs-Lisp` (`SPC f e d`) and `Spacemacs buffer` (`SPC b h`).

Toggling on `M-x alchemist-mode` again changes the `Elixir` text background color again.

It doesn't seem to be caused by the modeline text `alchemist`. Because if it's hidden (at least manually) from the `Eval:` (`S-M-;`) prompt with:
`(spacemacs|hide-lighter alchemist-mode)`

Then the modeline text `alchemist` disappears during the current Emacs session.

I don't know how to hide it automatically when a `.ex` file is opened.

I've tried adding the hide-lighter command to the `elixir/init-alchemist` functions `:init` and `:config` sections.
https://github.com/syl20bnr/spacemacs/blob/71d4e15e67feda18692ee35d50f3d98216cd90aa/layers/%2Blang/elixir/packages.el#L30

But the `alchemist` text in the modline remains when opening a `.ex` file.
