### ISSUE TITLE
Opening deer sometimes breaks emacs

### ISSUE THREAD

**Issue by DvdMgr** [syl20bnr/spacemacs#13129]
#### Description :octocat: 
Opening deer sometimes breaks emacs, making editing the current file impossible.
In particular, it seems like Deer does not behave very well when the window it was previously on was closed.

#### Reproduction guide :beetle:
- Make sure the ranger layer is activated
- Start Emacs
- SPC f e d
- SPC w /
- SPC w l
- SPC a d
- SPC w d
- SPC w / 
- SPC w l
- SPC a d
- Get a strange message about how .spacemacs changed on disk
- Try opening .spacemacs, get stuck in a file was modified / do you want to revert loop

*Observed behaviour:* :eyes: :broken_heart:
Opening deer causes a strange message about how a file was changed on disk, and makes accessing the file impossible.

*Expected behaviour:* :heart: :smile:
Opening deer just opens deer, causing no modifications to files

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b0d15851d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm ranger emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
No error is generated by this behavior

**Comment by duianto** [comment]
Confirmed.

There's definitely something strange going on with the `ranger` layer/package.

I'm seeing multiple issues.

In addition to the scary message when following the steps above:
>.spacemacs changed on disk; really edit the buffer? (y, n, r or C-h)

### Issue 2
Another issue already occurs when the deleting the `ranger-mode` window: `SPC w d`.

Now any window change shows the message:
>All ranger frames have been killed, reverting ranger settings and cleaning buffers.

It seems to be caused by the `window-configuration-change-hook` variable still containing: `ranger-window-check`

Possibly because the ranger mode buffer only removes the function from the hook in the function `ranger-revert`, which is called from `ranger-disable`, which is called from `ranger-close` (key binding `q`).

### Issue 3
Sometimes `q` doesn't close the `Deer:name` buffer, even though `M-x view-lossage` (`F1 l` (l = lowercase L)) shows: `q [ranger-close]`


### Issue 4
Another issue also occurred while testing. Spacemacs a state where no helm buffers or even minibuffer prompts (`S-M-;`) appeared. Instead this message was shown:
>run-hooks: Selecting deleted buffer

I'm not sure about the exact reproduction steps, but I was deleting a ranger window with `SPC w d`.

Restarting Spacemacs: `SPC q R` seems to be the only way to fix it.

Restarting with `SPC q r` shows a startup message:
>Making window-configuration-change-hook buffer-local while locally let-bound!

And a ranger buffer opened.

Navigating up and down in the buffer showed these kinds of messages:
>evil-line-move: End of bufferError during redisplay: (eval (ranger-header-line)) signaled (args-out-of-range #(" username@COMPUTER : c:/Users/username/.emacs.d/assets                                                                                                 [1]__  +  " 1 18 (face font-lock-keyword-face) 48 54 (face font-lock-constant-face) 151 156 (face font-lock-comment-face) 157 160 (face (:inherit font-lock-builtin-face :background "#787878" :foreground "black") pointer hand local-map (keymap (header-line keymap (mouse-1 . ranger-new-tab) (down-mouse-1 . ignore))))) 217 nil)
Error during redisplay: (eval (ranger-header-line)) signaled (args-out-of-range #(" username@COMPUTER : c:/Users/username/.emacs.d/assets                                                                                                 [1]__  +  " 1 18 (face font-lock-keyword-face) 48 54 (face font-lock-constant-face) 151 156 (face font-lock-comment-face) 157 160 (face (:inherit font-lock-builtin-face :background "#787878" :foreground "black") pointer hand local-map (keymap (header-line keymap (mouse-1 . ranger-new-tab) (down-mouse-1 . ignore))))) 217 nil) [3 times]
Error during redisplay: (eval (ranger-header-line)) signaled (args-out-of-range #(" username@COMPUTER : c:/Users/username/.emacs.d/auto-save-list                                                                                         [1]__  +  " 1 18 (face font-lock-keyword-face) 48 62 (face font-lock-constant-face) 151 156 (face font-lock-comment-face) 157 160 (face (:inherit font-lock-builtin-face :background "#787878" :foreground "black") pointer hand local-map (keymap (header-line keymap (mouse-1 . ranger-new-tab) (down-mouse-1 . ignore))))) 217 nil)

There's an open issue with `selecting deleted buffer` in the title:
"Selecting deleted buffer" error upon common commands #8729

But I'm the only one there that mentions `ranger`, but the comment has one up vote so someone else seems to also have seen the same or similar issue.

My comment in the comment following that one: https://github.com/syl20bnr/spacemacs/issues/8729#issuecomment-303436215

Still applies now, the reproduction steps in the first comment do not cause the issue.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9d379e4ff)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion clojure command-log emacs-lisp git helm markdown multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/notes.org"))
            ranger rust
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

### Notes
DvdMgr A suggestion for improving the readability in future comments.

The key bindings with the lowercase L:
- SPC w l

Can be confused with: SPC w |
Because the lowercase L and the vertical bar are very similar: l|

In Spacemacs `SPC w |` (| = vertical bar) calls: `spacemacs/maximize-vertically`

It can help to write possibly confusing key bindings like this:
- SPC w l (l = lowercase L)

Or in this case the action of these two key bindings:
- SPC w /
- SPC w l

can be performed with the Spacemacs key binding: `SPC w V`
which calls: `split-window-right-and-focus`

It might also be useful to know that there's an equivalent key binding:
`SPC w S` for `split-window-below-and-focus`

**Comment by DvdMgr** [comment]
Thanks for the tips!

I don't know if this is of any help, but I've had the chance to play with this a little bit today - I've searched `ranger.el` for the line generating the `All ranger frames have been killed, reverting ranger settings and cleaning buffers.` message, and found that this line is followed by a call to the `ranger-revert` function. Commenting that line and recompiling elpa makes the bug vanish, and does not seem to alter functionality in my limited testing.
