### ISSUE TITLE
Add priority setting to agenda keymap

### ISSUE THREAD

**Issue by mirkov** [syl20bnr/spacemacs#13143]
I propose that the org-agenda-mode should have `p' bound to `org-agenda-priority' by default.

I accomplished this by issuing `(spacemacs/set-leader-keys-for-major-mode 'org-agenda-mode "p" 'org-agenda-priority)` in my startup file.

**Comment by nixmaniack** [comment]
IMO, this should go under `org-agenda -> insert -> priority` similar to what we have for effort, tags and property.
But since `p` keybinding is already taken for `property` something else should be chosen.

**Possible Options**:

key| reason
---|------
`P`| mnemonic based
`,` |  default org binding `C-c ,` based 

On another note, org-agenda also provides `+` and `-` keybindings to change priorities in either direction.

**Comment by mirkov** [comment]
I was not aware of the `+/-` keybindings. Thanks for pointing them out.
I'm OK with any of the two options:

- do nothing, leaving `+/-`
- insert under `org-agenda -> insert` using either `P` or `,`, leaving also `+/-` binding

I'm OK with closing this request - I leave it to you to decide on best course of action.

**Comment by smile13241324** [comment]
I have added a binding for the setting priority to `SPC i P`, this should allow new users to explore the various agenda features without having to read through the original agenda bindings.
