### ISSUE TITLE
php-extras package only available from marmalade

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#1314]
The `php-extras` package fails to install since it seems that it is only available from marmalade. At least it says so on [its github](https://github.com/arnested/php-extras)

**Comment by reed1** [comment]
Yep, better extract them manually and wait untill it's available on ELPA (hopefully)

**Comment by cpaulik** [comment]
There is already [one special case](https://github.com/syl20bnr/spacemacs/blob/d56a2b0ef51abe5c5d216f6e201c4eda3d160a1e/core/core-configuration-layer.el#L28) for which marmalade is added to the package archives.

**Comment by syl20bnr** [comment]
I feel that marmalade clashes with MELPA, this is also true with MELPA stable and MELPA. I took the route of the "bazaar" and want to embrace it for the best and the worst :-)
So what @reed1 suggested is what I would do.

**Comment by nikhgupta** [comment]
In my opinion, since `php-extras` is included within a contrib layer `php`, we should either remove it from that layer or provide the user with an appropriate message for the actions to take.

My point being that layers are meant to be either enabled or disabled without worrying about the configuration inside. They should just work. That's what I think is the primary benefit of a layer, and which is what makes Spacemacs, so pleasant to use. Please, correct me if I am wrong.

So, if a package is included in a contrib layer, it should just work, and not throw out an error, or at least let the user know how to solve this or maybe, mark it as a bug till a solution exists?

**Comment by nikhgupta** [comment]
In my opinion, since `php-extras` is included within a contrib layer `php`, we should either remove it from that layer or provide the user with an appropriate message for the actions to take.

My point being that layers are meant to be either enabled or disabled without worrying about the configuration inside. They should just work. That's what I think is the primary benefit of a layer, and which is what makes Spacemacs, so pleasant to use. Please, correct me if I am wrong.

So, if a package is included in a contrib layer, it should just work, and not throw out an error, or at least let the user know how to solve this or maybe, mark it as a bug till a solution exists?
