### ISSUE TITLE
dev branch: Emacs freezes when opening .spacemacs

### ISSUE THREAD

**Issue by jonathanunderwood** [syl20bnr/spacemacs#13156]
#### Description :octocat:
Loading the .spacemacs file (M-m f e d) the first time takes forever as it seems to kick off contacting melpa.org

#### Reproduction guide :beetle:
- Start Emacs
- M-m f e d
- Emacs hangs, contacting melpa.org 

*Observed behaviour:* :eyes: :broken_heart:
Emacs crawls, contacts melpa.org for unknown reasons

*Expected behaviour:* :heart: :smile:
Emacs opens .spacemacs

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7636811b7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(rust auto-completion better-defaults emacs-lisp git ivy markdown
      (org :variables org-enable-reveal-js-support t)
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking treemacs
      (python :variables python-enable-yapf-format-on-save t python-formatter 'black python-format-on-save t)
      yaml groovy javascript html nginx csv osx docker semantic-web
      (theming :variables theming-headings-same-size 'all))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
N/A
```

**Comment by duianto** [comment]
It might have been related to this PR:
Add flycheck-elsa #13130

After it was applied I noticed that one or more packages were installed when I opened `.spacemacs` the first time (it might have happened for any `.el` file).

It stopped for me while it downloaded and installed the packages, but it never froze completely.

<details><summary>
System Info: Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 461b949c4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm imenu-list ipython-notebook
            (javascript :variables javascript-backend 'lsp)
            markdown multiple-cursors notmuch
            (org :variables org-agenda-files
                 '("c:/Users/username/org/notes.org"))
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control
            (xclipboard :variables))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

An issue was opened shortly afterwards about issues caused by `flycheck-elsa`:
recently added flycheck-elsa breaks many things #13151

Since then the `flycheck-elsa` package removed the dependency on `cask`:
Remove cask dependency https://github.com/emacs-elsa/flycheck-elsa/pull/10

And the issue #13151 author reported that the issues were solved.

Could you update your packages and try again.

**Comment by jonathanunderwood** [comment]
I am unable to reproduce the issue now, so I think that might have been it. I'll close this, and file a new issue if it occurs in the future. Thanks for looking at it.
