### ISSUE TITLE
Enabling python layer without auto-completion leads to install/delete loop

### ISSUE THREAD

**Issue by mcfarljm** [syl20bnr/spacemacs#13162]
#### Description :octocat:
Enabling `python` layer without `auto-completion` leads to install/delete loop.

#### Reproduction guide :beetle:
- Start with clean spacemacs distribution
- Add `python` configuration layer
- Run `SPC-f-e-R` to synchronize
- Run `SPC-f-e-R` to synchronize again
- Restart emacs

*Observed behaviour:* :eyes: :broken_heart:
The first synchronization after enabling `python` installs the `@python` packages as expected.  The second synchronization installs `@auto-completion` packages, which wasn't completely expected.  What's more, upon restarting, spacemacs thinks that the `auto-completion` packages are orphaned, and it uninstalls them.  It is now in a cycle where running `SPC-f-e-R` will trigger `auto-completion` packages to get re-installed, but they get removed again upon restart.

I think part of the issue is that `+lang/python/layers.el` declares a dependency on `dap`, but only when `python-backend` is set to `lsp` (which is the default).  Upon first enabling `python`, `python-backend` is not defined, so this dependency is not triggered.  That seems to be why the second synchronization then adds additional packages, since the `dap` dependency triggers a dependency on the `auto-completion` layer.  What I don't understand is why it then sees all of the `auto-completion` packages as orphaned and deletes them on the next startup.

*Expected behaviour:* :heart: :smile:
Expected behavior was (1) all packages needed by `python` layer would be installed upon first synchronization, and (2) spacemacs would not treat as orphaned and delete packages that it will then install automatically on the next synchronization.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7636811b7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors
            python
            treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by Trapez** [comment]
The simplest possible python layer [configuration](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/python) is just `python`. There is no `:package` keyword used to configure layers.

**Comment by mcfarljm** [comment]
> There is no `:package` keyword used to configure layers.

Section 7.6.3 of the manual shows the `:packages` keyword; is that outdated?

By the way, I'm actually getting this error even without that keyword, and even with the main distribution as opposed to spacemacs-base.  I think the trigger is enabling the `python` layer but not `auto-completion`, and leaving `python-backend` at the default value of `lsp`.  This seems to trigger a dependency on the `auto-completion` layer, but spacemacs seems to be confused as it then deletes those installed packages on next startup.

**Comment by mcfarljm** [comment]
(Note I edited the title and description to provide a simpler description of the steps involved to reproduce the issue -- it does not appear to be specific to `spacemacs-base`.  I've also added some notes to the description about what I think might be happening, due to how the dependency of the `python` layer on `auto-completion` is implied through a variable `python-backend` that isn't initially defined.)

**Comment by Trapez** [comment]
You're right about what's happening as far as I can see. Some layers, like autocomplete and syntax-checking, are necessary for functionality in other layers. They shouldn't be uninstalled if they are still needed.

**Comment by smile13241324** [comment]
@mcfarljm  @Trapez I may be able to explain whats going on here. Basically when you load python layer we are declaring a dependency on `dap` layer if the lsp backend is used. This however is only done if the config variable `python-backend` is bound and equals `lsp`.

So what is happening now. When you make your first sync, the config variables are set to its default values. At the time of testing the default was `lsp`.

When you did your second sync the config variables were already set and the backend was `lsp` triggering the layer dependency on `dap` which includes `lsp` which includes `auto-completion` as well as `syntax-checking`. These layers are autoloaded but not auto installed this is they are not added to your dotfile and would therefore be removed when you restart emacs.

This kind of problem happens whenever a layer declares a conditional layer dependency which is not a tautology. Right now I would prefer to avoid this situation by cleverly declaring layer dependencies rather than to extend the core to install the layer and all of its recursive layer dependencies during the auto install step.

Now back to the problem at hand. For the python layer the install loop should be gone for the default backend is `nil` today which results in the `anaconda` backend and no additional layer dependencies.

Please retry on latest develop @mcfarljm and close this ticket when it works.

**Comment by mcfarljm** [comment]
Confirmed fixed on develop.  Thanks for the help!
