### ISSUE TITLE
spacemacs/alternate-buffer fails in spacemacs-base

### ISSUE THREAD

**Issue by mcfarljm** [syl20bnr/spacemacs#13163]
#### Description :octocat:
The `spacemacs/alternate-buffer` command fails due to missing `(require 'cl)` in core-funcs.el with spacemacs-base

#### Reproduction guide :beetle:
- Start Emacs
- Use spacemacs-base distribution with no changes to config
- Press SPC-f-e-d to go to the dotfile
- Press SPC-tab to try and change to previous buffer

*Observed behaviour:* :eyes: :broken_heart:
Symbol's function definition is void: destructuring-bind

*Expected behaviour:* :heart: :smile:
The command `spacemacs/alternate-buffer` executes.

I can resolve the issue by adding a `(require 'cl)` to core-funcs.el, but I'm not sure exactly where it should go.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7636811b7)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
The `cl` package has been deprecated in favor of `cl-lib`:
`cl` Package Deprecated #12989
fix for #12989 to use cl-lib instead of obsolete cl #13059

This means that functions in the `cl` package, like `destructuring-bind`, need `cl-` as a prefix.

There's a pending PR:
Fix void destructuring-bind after cl pkg deprecation #13166

That fixes the issue with `spacemacs/alternate-buffer` showing:
>Symbol's function definition is void: destructuring-bind

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
Fix void destructuring-bind after cl pkg deprecation #13166
