### ISSUE TITLE
wrong indentation after typing { RET with indent-tabs-mode enabled

### ISSUE THREAD

**Issue by xabbu42** [syl20bnr/spacemacs#13172]
#### Description :octocat:
With indent-tabs-mode set to t, clean-aindent-mode eats the indentation after typing { RET.

#### Reproduction guide :beetle:
- Start Emacs
- Open a C code file SPC f f test.c
- Type { RET for the correct behaviour
- set-variable indent-tabs-mode t
- Type { RET for the wrong behaviour

*Observed behaviour:* :eyes: :broken_heart:
The cursor is in the first column, no indentation done.

*Expected behaviour:* :heart: :smile:
The cursor should be at the correct indentation one level down.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

**Comment by xabbu42** [comment]
This seems to be similar to issue #6520 and the workaround in https://github.com/jqmtor/dotfiles-legacy/commit/197349243aad0a79f4f9aa657521a26c55491db7 works in this case too. That is make sure the clean-aindent-mode hook is last with the following code in user-config.
```
(remove-hook 'post-command-hook 'clean-aindent--check-last-point)
(add-hook 'post-command-hook 'clean-aindent--check-last-point)
```

**Comment by smile13241324** [comment]
I have added a function to the spacemacs-editing layer which takes care that `clean-aindent--check-last-point` is called for every prog mode. This solved the issue you are reporting on my side when I reload the mode after manually activating `indent-tabs-mode`.

However it does not solve the go issue for me. This seems to be related to some weird cursor position thingy for when I put my cursor back on the opening `(` enter insert state and then go back to the original `)` and then insert the line above I am getting my indentation. When I just leave the cursor on the `)` I am not getting it.

Anyway, I hope at least your issue is solved now on develop. Please test and close this issue if it works for you.

**Comment by xabbu42** [comment]
This now works correctly for me on develop. Thanks!
