### ISSUE TITLE
Layout selection improvment

### ISSUE THREAD

**Issue by FabArd** [syl20bnr/spacemacs#13234]
I use more than 10 layouts and I am annoyed when I want to select them because the selection is limited from 0 to 9. Of course I have the possibility to select them by their names with SPC l l and select the name of the layout I want to activate : but it is not fast.
Here are the changes I made to spacemacs-layouts/funcs.el to resolve this problem :

;; switch to specific layout
(defun spacemacs/layout-switch-to (pos)
 (interactive "p")
 (spacemacs/layout-switch-by-pos (1- pos))
)

and this is the modification I made to spacemacs-layouts/packages.el
        ("<return>" spacemacs/layout-switch-to :exit t)
        ("RET" spacemacs/layout-switch-to :exit t)

Now when I want to select a layout I just type its number on the num pad of the keyboard and return : I am not limited from 0 to 9, I can select all my layouts without limitation.
I do not made the modifications in .spacemacs because I do not find how to retrieve the keyboard shortcut of the layouts TS : perhaps someone can give me the solution !

**Comment by smile13241324** [comment]
@FabArd I have added your function to the transient state, though I changed the key binding. Per convention `return` is bound to `nil` to close the transient state. I have bound your function to `e` instead.

The interactive specification I have changed to `N` this allows to take the content as prefix arg or if not available to ask in the minibuffer for the layout position.

If you would like to keep your original bindings you should be able to copy paste the transient state declaration to your user-config and change the bindings accordingly.

Please close this ticket when your issue is solved.
