### ISSUE TITLE
Flickering on fullscreen when changing workspaces in Gnome after opening a few buffers

### ISSUE THREAD

**Issue by Patriot720** [syl20bnr/spacemacs#13259]
#### Description :octocat:
Flickering on fullscreen when changing workspaces in Gnome after opening a few buffers
Can't reproduce in pure Emacs. Other fullscreen apps also work fine.
While screencapturing issue does not show itself.
Enabling transparency seems to help.

Video:https://imgur.com/a/yCWsWYI

#### Reproduction guide :beetle:
- Have Gnome
- Start Emacs (tried 2 different versions)
- F11 fullscreen
- Open a project
- Open a few buffers
- Change workspaces back and forth

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c9c5637ac) (same on master branch)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown yaml helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by duianto** [comment]
I tested it in a VirtualBox guest VM of PopOS 19.10 (with Windows 1903 as host).
The GNOME version is: `3.34.2`

With Spacemacs in fullscreen (`SPC T F`) on the first workspace,
and either of the following applications open on the second workspace:
- Pop!_Shop
- Terminal
- Text Editor (gedit)

Pressing `Super down` and `Super up` to switch between the workspaces, doesn't cause the application on the second workspace to flicker as it's shown in the video.

It might not happen for me because I'm running it in a VM and the graphics might be handled differently compared to a native Linux installation.

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 36230346e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
</pre>
</details>

**Comment by mphojele** [comment]
gnome-panel dude. Switch that guy off. I'm also on manjaro and I had the same issue as you. Your video doesn't demonstrate well enough though.

**Comment by mphojele** [comment]
at least you can opt for dash to dock

**Comment by mphojele** [comment]
Wait, i think I'm wrong. I think emacs 28 and 27 have this issue but not 26.3. I huge display change in these versions is the change from imagemagick (emacs 26) to cairo (emacs 27+). I'm also on manjaro gnome @Patriot720

**Comment by Patriot720** [comment]
> 
> 
> Wait, i think I'm wrong. I think emacs 28 and 27 have this issue but not 26.3. I huge display change in these versions is the change from imagemagick (emacs 26) to cairo (emacs 27+). I'm also on manjaro gnome @Patriot720

I've had it on both 26.3 and 28 (Tried updating to 28, thought maybe it would fix it). Also i don't think i had this problem before with my old graphics card and old nvidia driver 390.

**Comment by mphojele** [comment]
@Patriot720 I see, are you using gnome-panel extension?

**Comment by Patriot720** [comment]
> 
> 
> @Patriot720 I see, are you using gnome-panel extension?

I don't think i did. I've tried disabling all extensions as well. Anyway i've since then came back to Windows because of all the small annoyances like that.

**Comment by lebensterben** [comment]
please report it to upstream.
in the meantime, this might as well caused by Gnome. just search `gnome flickering` and you may find some complaints.
