### ISSUE TITLE
Evil-unimpaired halts update process

### ISSUE THREAD

**Issue by martijnjanssen** [syl20bnr/spacemacs#13286]
#### Description :octocat:
Updating spacemacs does not succeed due to `evil-unimpaired`

#### Reproduction guide :beetle:
- Start Emacs
- Update packages

*Observed behaviour:* :eyes: :broken_heart:
Update stops with the message `version-to-list: Invalid version syntax: ‘Creating directory: No such file or directory, /home/martijn/.emacs.d/.cache/quelpa/build/evil-unimpaired/’ (must start with a number)`, I disabled all my custom configuration to check this.

*Expected behaviour:* :heart: :smile:
The update succeeding

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f578e618a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
nil
```
- System configuration features: XAW3D XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
Skipping check for new version (reason: dotfile)
(Spacemacs) --> refreshing package archive: melpa... [1/3]
Contacting host: melpa.org:443
Importing package-keyring.gpg...done
Contacting host: melpa.org:443 [2 times]
Package refresh done
(Spacemacs) --> refreshing package archive: org... [2/3]
Importing package-keyring.gpg...done
Contacting host: orgmode.org:443
Package refresh done
(Spacemacs) --> refreshing package archive: gnu... [3/3]
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Package refresh done
Fetcher: file
Source: nil

version-to-list: Invalid version syntax: ‘Creating directory: No such file or directory, /home/martijn/.emacs.d/.cache/quelpa/build/evil-unimpaired/’ (must start with a number)
```

**Comment by duianto** [comment]
In both PopOS and Windows, the packages update without any issues when I click the `[Update Packages]` button in the Spacemacs home buffer.

I'm not sure why it's saying that that directory must start with a number. Because that's what the directory name looks like in both OSs for me:
```
/home/username/.emacs.d/.cache/quelpa/build/evil-unimpaired/
c:/Users/username/.emacs.d/.cache/quelpa/build/evil-unimpaired/
```

Your list of layers looks a bit suspicious:
```
elisp
nil
```
there is a `emacs-lisp` layer, but not a `elisp` layer.
The available layers are listed in `SPC h l` (l = lowercase L).

Could you post your `.spacemacs`, possibly as a link to a gist in your repo: https://gist.github.com/

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0a06c7ca6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 ranger
                 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0a06c7ca6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git github helm imenu-list
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org
            (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by martijnjanssen** [comment]
Sorry, I had disabled all layers and incorrectly formatted the elisp in the code block, it is now correct.

**Comment by duianto** [comment]
I just cloned a fresh copy of Spacemacs in both PopOS and Windows there were no errors in Windows, but in PopOS I got:
>- An error occurred while installing pcre2el (error: (file-error https://melpa.org/packages/pcre2el-20161120.2103.el Bad Request))

However I get that message for different packages every time I update packages.
Restarting installs the package without any errors.
I've tried different solutions to fix the bad request error but none have worked so far.

You could try starting over and copying over your configurations when you have a working setup.

Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

**Comment by martijnjanssen** [comment]
Fair enough, let's give that a go :+1:

**Comment by martijnjanssen** [comment]
My apologies for the wait, but is seems that that has fixed it! Interesting issue, but thanks :tada:

**Comment by ngm** [comment]
For me, 

```
mkdir -p ~/.emacs.d/.cache/quelpa/build/evil-unimpaired
```

before running the update sorted a similar issue out.

**Comment by thecocoa** [comment]
@ngm - tytyty.  
Making the directory resolved the problem.

**Comment by chrneumann** [comment]
Same here. Removing the .cache directory completely did not help.
