### ISSUE TITLE
Don't brutally delete orphan packages

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1330]
I think this is causing difficult for new users who just want to test the new packages. At best, just display a bold red warning message at start up saying there are orphan packages and it should be moved to a layer with `M-x configuration-layer/create-layer`.

We should also update the template for layer by adding boxed comments to draw users' attention to read the comments. This can be done with `artist-mode`; when in this mode, select a region and `C-c C-r` and you get a surrounding rectangle.

We should also add to the comment `Step 1`, `Step 2`... at each code region i.e. `Step 1` at the `(setq ...)`, `Step 2` at the init functions.

**Comment by syl20bnr** [comment]
It's part of spacemacs design. I won't lower it for just a starting issue that is clearly mentioned in the FAQ and maybe at other places.
There is also in develop the new variable `dotspacemacs-additional-packages`, see https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/.spacemacs.template#L27-31

**Comment by syl20bnr** [comment]
The docstring should be updated to mention orphan packages.

**Comment by tuhdo** [comment]
So there should be a tutorial in the quick help on how to create a layer. This should be accompanied with an Elisp tutorial.

**Comment by syl20bnr** [comment]
An item in [HOWTOs.md](https://github.com/syl20bnr/spacemacs/blob/develop/doc/HOWTOs.md) that mimic and improve [private layer README](https://github.com/syl20bnr/spacemacs/tree/develop/private) and a link on the README is sufficient. We can do the best documentation in he world, people won't read it.

But it should be a quick HOWTO item indeed.

**Comment by LysanderAkili** [comment]
+1 

It should be simple, and elegant. This is very confusing for newcomers, like myself. I never found private docs until it was pointed out. Even so, it still lacks info on how to install it properly.

The reason why people won't read it is because it is incredibly overwhelming, and long.  Due to the sheer amount of information, it takes awhile for users to jump in. I think a big fat bold red warning should be on homepage in emacs client, and documentation. 

The paradox-list-manager is a tricky one. I assumed it was a package manager, which is is, however it did not explicitly state that it is not technically installed, nor moved to the proper folder. When users restart their client, it loses all of that information. Users will be more frustrated than ever. Private docs talks about that issue to certain extend but I have no idea because it never said anything about it in the package manager, or homepage. I had to get on chat to find out. That indicate a problem. 

Put quick howto package item on top of the page right before the quick howto install item.  This is a good solution.
