### ISSUE TITLE
server pyls:11267 status:starging exited with status exit

### ISSUE THREAD

**Issue by wutianjun5858** [syl20bnr/spacemacs#13329]
server pyls:11267 status:starging exited with status exit.

**Comment by duianto** [comment]
Could you provide some more information, using the issue template:
https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template
```
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

%SYSTEM_INFO%
```

You can copy your system info to the clipboard by pressing `SPC h d s`.

**Comment by smile13241324** [comment]
I had a similiar issue some days ago, it was caused by outdated python setup packages installed at root on my arch instance. There have been a great merge between two forked repositories which is not backward compatible.

You can verify this by simply executing `pyls` on the terminal and check what the error message is.

If you still want some help from us please update your issue with the official issue template from within spacemacs so we have some information about your system. In addition please provide the installed pyls related package versions and the error message you see when you run it on the terminal @wutianjun5858
