### ISSUE TITLE
Parinfer layer tests failing 6/7

### ISSUE THREAD

**Issue by slifin** [syl20bnr/spacemacs#13350]
<img width="913" alt="Screenshot 2020-03-06 at 09 54 08" src="https://user-images.githubusercontent.com/198857/76072776-791b8f00-5f90-11ea-8215-1bcbf33072a2.png">
I'm commenting out the parinfer layer to try and use it but SPC t P is undefined when I try and run it in a Clojure file

SPC f e R yields the above results

**Comment by JackOddy** [comment]
Having the same thing happen when i try to add this layer to `.spacemacs`

**Comment by jr0cket** [comment]
On the latest `develop` commit, I can install the parinfer layer without an error being reported.   However, when using the `SPC t P` keybinding that the layer provides, I get the error message: 

"Toggle: parinfer-indent  
This toggle is not supported."

Emacs 26.3
Spacemacs `develop` 884afe138
Ubuntu Linux 19.10

**Comment by slifin** [comment]
Switching to the develop branch appears to have fixed this in so much as I can use parinfer

**Comment by duianto** [comment]
@jr0cket `SPC t P` seems to be working for me,
>parinfer-indent disabled.

>parinfer-indent enabled.

At least when testing with this example clojure file:
https://github.com/clojurebook/ClojureProgramming/blob/master/ch03-game-of-life/src/com/clojurebook/collections/life.clj

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0438c1ca5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey clojure command-log emacs-lisp ess git helm imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org parinfer pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

The same error message was reported in this issue:
parinfer-mode doesn't start when opening a clojure buffer #11940

And it was fixed in this PR:
Fix post-init of parinfer in the clojure layer #12138
