### ISSUE TITLE
Notmuch search bar behaves as normal and insert vim mode at the same time

### ISSUE THREAD

**Issue by MarcinWieczorek** [syl20bnr/spacemacs#13354]
#### Description :octocat:
Notmuch search bar behaves as normal and insert vim mode at the same time

#### Reproduction guide :beetle:
- Start Emacs
- open notmuch layer (:notmuch)
- navigate to the search bar
- type the alphabet

*Observed behaviour:* :eyes: :broken_heart:
hjkl keys navigate as in normal mode, v starts visual, some of the other letters just appear in the bar.

*Expected behaviour:* :heart: :smile:
Either stay in normal mode or start insert automatically (first option preferred)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. e0aee1554) (the branch is actually develop, is the nil a bug?)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs python notmuch hy)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by smile13241324** [comment]
From your description this sounds like the evilification has not been properly configured for the address bar. Normally either just normal mode is activated or the original bindings are kept and only the navigation commands are overloaded.

I think the later has been done but the former would have been better.
I will take a look.

**Comment by smile13241324** [comment]
Woa this was more complicated than expected, I have never thought that you could actually have native widgets in emacs buffers with independent keymaps. So this took me a while reading this up before I could attempt a fix.

The actual issue was as expected, `notmuch-hello` did just evilify its mode-map which is normally intended to be used in a non text buffer however as there is a search widget embedded this must be done by setting normal mode to be the default mode for this buffer and add the mode specific bindings manually to it, avoiding key conflicts.

This leaves you now with a fully functional insert mode in the search field but let you still have all the quick bindings you are used to in normal mode.

In addition I have made the not much message buffer closable via q and documented the new key bindings. I would have loved to do the same for the not much help buffer but I have noticed it doesn't use its own keybinding nor does it use its own mode so I don't see a place where to bind this.

@MarcinWieczorek could you have a look whether this solves your problem and if it does close this issue? If you have an idea for that help-buffer I would also be happy to hear it.

**Comment by MarcinWieczorek** [comment]
The search bar works now, thanks.
Help should allow to be closed with q and it seems to be named `*notmuch-help*`, isn't that enough to do the binding?

**Comment by smile13241324** [comment]
Not really we need to set the bindings for notmuch only, however this is difficult when global emacs modes are used instead. As it looks like "view-mode" is used which is not directly evilified. The original q binding is rebind to Q. I have now tried to bind q however this seems not to work properly, somehow it only works the second time it is used. I currently have no clue why this is not working, lets see what the other maintainers say.

Anyway I think your primary problem has been solved. If this is the case please close this issue.

**Comment by MarcinWieczorek** [comment]
Ok. Thank you for your help and a quick response.
