### ISSUE TITLE
M-RET no longer org mode prefix in GUI 

### ISSUE THREAD

**Issue by bebound** [syl20bnr/spacemacs#13374]
#### Description :octocat:
M-RET no longer org mode prefix in GUI, it will add headline.

`SPC h d k` shows `<M-return> runs the command org-meta-return (found in org-mode-map), which is an
interactive compiled Lisp function in ‘org.el’.
`

 I tried both emacs-mac and emacs-plus, neither of them works. But it works as expected in terminal.

#### Reproduction guide :beetle:
- Start Emacs
- create org file, press M-RET

*Observed behaviour:* :eyes: :broken_heart:
- Insert new headline

*Expected behaviour:* :heart: :smile:
- Show mode commands

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 710aa947b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html markdown javascript
      (python :variables python-backend 'anaconda)
      ivy
      (auto-completion :variables auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
      better-defaults git treemacs
      (org :variables org-enable-hugo-support t org-startup-indented t org-enable-sticky-header t)
      osx
      (shell :variables shell-default-shell 'vterm shell-default-term-shell "/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by emacs18** [comment]
I don't understand.  When was org-meta-return ever a prefix command?
Following is a quote of org manual which clearly says that this command inserts new heading.
So it seems like to me that there is nothing wrong.


‘M-<RET>’ (‘org-meta-return’)
     Insert a new heading, item or row.

     If the command is used at the _beginning_ of a line, and if there
     is a heading or a plain list item (see *note Plain Lists::) at
     point, the new heading/item is created _before_ the current line.
     When used at the beginning of a regular line of text, turn that
     line into a heading.

     When this command is used in the middle of a line, the line is
     split and the rest of the line becomes the new item or headline.
     If you do not want the line to be split, customize
     ‘org-M-RET-may-split-line’.

     Calling the command with a ‘C-u’ prefix unconditionally inserts a
     new heading at the end of the current subtree, thus preserving its
     contents.  With a double ‘C-u C-u’ prefix, the new heading is
     created at the end of the parent subtree instead.

**Comment by bebound** [comment]
M-RET should behave like leader key, like #9603.

**Comment by emacs18** [comment]
Sorry.  I've been used to vim style, that I forgot about emacs style.
So M-RET is to emacs style as comma is to vim style.
Got it.

**Comment by emacs18** [comment]
C-M-m seems to be my major mode leader key rather than M-RET.

What is puzzling to me is that "C-h k M-RET" says that this is <M-return> key sequence, and "C-h k C-M-m" is reported as being M-RET!  I just learned that I don't know emacs as good as I thought I did.

Good news is that I was able to get M-RET to be the major mode leader key setting dotspacemacs-major-mode-emacs-leader-key to "<M-return>" rather than to "M-RET".  Thus if you want to set "meta return" key sequence, then you say "<M-return>".  If you want to set "control meta return" key sequence, then  you say "M-RET".  This is utterly confusing to me.

**Comment by nixmaniack** [comment]
> Good news is that I was able to get `M-RET` to be the major mode leader key by setting `dotspacemacs-major-mode-emacs-leader-key` to `<M-return>` rather than to `M-RET`. Thus if you want to set "meta return" key sequence, then you say `<M-return>`. If you want to set "control meta m" key sequence, then you say `M-RET`. I understand that "control m" and "return" key sequences are equivalent in some cases. However this is utterly confusing to me.

Wow! That's some insightful discovery there. I have had this issue when I started using `hybrid` style but I accepted the bug as a feature and adapted my workflow.

This should be part of documentation.

**Comment by jr0cket** [comment]
I can confirm I have the same experience.  `M-RET` in Emacs Normal and Holy mode (switching with `C-z`) both output an org heading

OS: Ubuntu Linux
Emacs: 26.3
Spacemacs: 0.300.0
Spacemacs branch: develop (rev. 884afe138)
Graphic display: t
Distribution: spacemacs
Editing style: vim
Completion: helm

**Comment by emacs18** [comment]
Could someone try setting `dotspacemacs-major-mode-emacs-leader-key` to `<M-return>` and see if `M-RET` acts as a leader key?

**Comment by bebound** [comment]
@emacs18  `<M-return>`  works in GUI, but failed for terminal...

**Comment by emacs18** [comment]
Following value for `dotspacemacs-major-mode-emacs-leader` worked for me for both GUI and terminal:
```elisp
(if window-system "<M-return>" "C-M-m")
```

**Comment by bebound** [comment]
Great, this also works for me. Maybe you can create a PR for this.

Just out of curiosity, do you have any idea why `M-RET` is only overridden as `org-meta-return` in GUI?

**Comment by emacs18** [comment]
Sure I can do that.  However what puzzles me is that `C-M-m` worked at all in GUI mode, because I can't see any recent change in either emacs or spacemacs that could have impacted this area.

**Comment by emacs18** [comment]
@bebound Let me try to answer your question.  This is just my guess.  It appears that emacs distinguishes between M-RET and C-M-m key sequences, i.e., meta (or alt) and return key being pressed together verses control, meta (or lat), and m keys being pressed together.  That is the distinction is made when it can such as in GUI mode.  Also even if some keys are distinguished, they are translated as bing equivalent, e.g., C-m is often same as RETURN, C-i is same as TAB, C-[ is same as ESC, etc.  See https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Translation-Keymaps
for details.  I don't claim to understand this.

Thus if you really want M-RET to work in both GUI and terminal mode, spacemacs could have done what org mode did like this:

```elisp
(org-defkey org-mode-map (kbd "M-<return>") #'org-meta-return)
(org-defkey org-mode-map (kbd "M-RET") #'org-meta-return)
```

You see they bind both key sequences so that it would work the same in either GUI or terminal mode.  Unfortunately I don't think spacemacs is setup to map two key sequences to be major mode emacs leader key.

**Comment by smile13241324** [comment]
For the record you can make spacemacs distinguish between C-m and Return as well as C-i and Tab in your dotfile:
```elisp
   ;; These variables control whether separate commands are bound in the GUI to
   ;; the key pairs `C-i', `TAB' and `C-m', `RET'.
   ;; Setting it to a non-nil value, allows for separate commands under `C-i'
   ;; and TAB or `C-m' and `RET'.
   ;; In the terminal, these pairs are generally indistinguishable, so this only
   ;; works in the GUI. (default nil)
   dotspacemacs-distinguish-gui-tab t
```
This is especially useful to get complete vim bindings.

**Comment by smile13241324** [comment]
@bebound I have merged the PR of @emacs18 can you please retry and close this issue when this change solved your issue?

**Comment by bebound** [comment]
@smile13241324 
This commit fix the issue.

I'm more confused. By default, spacemacs doesn't distinguish `C-m` and `RET`. So the original `C-M-m` should work for all mode in GUI and terminal.

However, in other mode, `M-RET` works in GUI and terminal. But in `org` mode, it only works in terminal. 

So what overrides GUI's `M-RET` key binding in `org` mode?

**Comment by smile13241324** [comment]
Its org mode itself, the function bound by it creates a new headline or
task depending of the context. The original binding doesn't work in a guis
context for in most window managers this is already reserved and will be
handled by the OS.

**Comment by emacs18** [comment]
Let me define few terms first.  By `C-M-m` I mean key combination where control meta (i.e., Alt) and `m` keys are pressed together.  It appears that `(equal (kbd "C-M-m") (kbd "M-RET"))` is always true.  By `<M-return>` I mean meta and RETURN keys being pressed together.   Isn't it confusing that `M-RET` does not mean meta-return, but that it means `C-M-m`?  Anyways here are the ways in which you can bind `C-M-m` and `<M-return>` key sequences.

- the two can be bound to two different commands.  
- only `<M-return>` is bound.  In this case only this key sequence
  is bound, and `C-M-m` is left unbound.
- only `C-M-m` is bound.  If `<M-return>` is not also bound, then
  `<M-return>` is implicitly bound to whatever is bound to `C-M-m`.

You can easily verify this.  For example evaluate this in say scratch buffer:

```elisp
(defun hello () (interactive) (message "hello"))
(local-set-key (kbd "C-M-m") 'hello)
```

You should find that both `C-M-m` and `<M-return>` key sequences are bound
to this command.  Following behaves the same as above where `M-RET` is used rather than `C-M-m`:

```elisp
(defun hello () (interactive) (message "hello"))
(local-set-key (kbd "M-RET") 'hello)
```

Now if you set the binding to `<M-return>` only, then the story is different:

```elisp
(defun hello () (interactive) (message "hello"))
(local-set-key (kbd "<M-return>") 'hello)
```

You should now find that only `<M-return>` is bound, but `C-M-m` is not bound.

org mode is special  in that it binds both `C-M-m` and `<M-return>` to the same command.  That is why in org mode only, the implicit translation of `<M-return>` to `C-M-m` was disabled.

**Comment by emacs18** [comment]
Above applies to GUI mode.  In terminal mode, you have to set `C-M-m`.  You cannot distinguish between `C-M-m` and `<M-return>`.

**Comment by bebound** [comment]
@emacs18 Thank you so much, that makes sense now.
