### ISSUE TITLE
Fill paragraph has some weird issues

### ISSUE THREAD

**Issue by dschrempf** [syl20bnr/spacemacs#13384]
I am experiencing issues with fill paragraph, especially in Org mode (I can't come up with a non-Org mode example at the moment). So, let's suppose I have the following Org file containing two commented paragraphs; assume the cursor is at POINT:

    # Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec hendrerit
    # tempor tellus. Donec pretium posuere tellus. Proin quam nisl, tincidunt et,
    # mattis eget, convallis nec, purus. Cum sociis natoque penatibus et magnis dis
    # parturient montes, nascetur ridiculus mus. Nulla posuere. Donec vitae dolor.
    # Nullam tristique diam non turpis. Cras placerat accumsan nulla. Nullam rutrum.
    # Nam vestibulum accumsan nisl.POINT

    # Aliquam erat volutpat. Nunc eleifend leo vitae magna. In id erat non orci
    # commodo lobortis. Proin neque massa, cursus ut, gravida ut, lobortis eget,
    # lacus. Sed diam. Praesent fermentum tempor tellus. Nullam tempus. Mauris ac
    # felis vel velit tristique imperdiet. Donec at pede. Etiam vel neque nec dui
    # dignissim bibendum. Vivamus id enim. Phasellus neque orci, porta a, aliquet
    # quis, semper a, massa. Phasellus purus. Pellentesque tristique imperdiet tortor.
    # Nam euismod tellus id erat.

When I run `fill-paragraph`, I get

    # Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec hendrerit
    # tempor tellus. Donec pretium posuere tellus. Proin quam nisl, tincidunt et,
    # mattis eget, convallis nec, purus. Cum sociis natoque penatibus et magnis dis
    # parturient montes, nascetur ridiculus mus. Nulla posuere. Donec vitae dolor.
    # Nullam tristique diam non turpis. Cras placerat accumsan nulla. Nullam rutrum.
    # Nam vestibulum accumsan nisl. Aliquam erat volutpat. Nunc eleifend leo vitae
    # magna. In id erat non orci commodo lobortis. Proin neque massa, cursus ut,
    # gravida ut, lobortis eget, lacus. Sed diam. Praesent fermentum tempor tellus.
    # Nullam tempus. Mauris ac felis vel velit tristique imperdiet. Donec at pede.
    # Etiam vel neque nec dui dignissim bibendum. Vivamus id enim. Phasellus neque
    # orci, porta a, aliquet quis, semper a, massa. Phasellus purus. Pellentesque
    # tristique imperdiet tortor. Nam euismod tellus id erat.

Instead, I except to not see any change.

Do you also have this problem? There are other things such as code blocks not
correctly formated, and so on.

**Comment by duianto** [comment]
After pasting the separate paragraphs, into a `org-mode` buffer.

Confirmed.

There seems to be a difference when calling: `M-x fill-paragraph`
compared to when pressing the key binding: `M-q` (which calls `fill-paragraph`)

- The `M-x fill-paragraph` command combines both paragraphs as described by dschrempf.
- The key binding:
  - Does nothing when the cursor is in the first paragraph.
  - Only changes the second paragraphs last two lines, when the cursor is in the second paragraph:
#### from:
```
# quis, semper a, massa. Phasellus purus. Pellentesque tristique imperdiet tortor.
# Nam euismod tellus id erat.
```
#### to:
```
# quis, semper a, massa. Phasellus purus. Pellentesque tristique imperdiet
# tortor. Nam euismod tellus id erat.
```
because the word `tortor` extends past the 80 char fill column.
(The fill column indicator can be enabled with the key binding: `SPC t f`)

- In the scratch buffer (which is in `text-mode`), only the second paragraphs last two lines change with both the `M-x fill-paragraph` command and the key binding.

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. bb8ec23ec)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey clojure command-log emacs-lisp ess git helm imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by dschrempf** [comment]
For me, also `M-q` combines both paragraphs, so at least the behavior of `fill-paragraph` and `M-q`, which calls `unfill-toggle` is consistent. Actually, I checked the function `unfill-toggle`, and it just calls `fill-paragraph`. However, the strange behavior in Org mode is still on.

**Comment by dschrempf** [comment]
I found the problem. It appears that Org mode has its own `org-fill-paragraph` function which should be used, and is usually bound to `M-q`. I globally bound `M-q` to `unfill-toggle` not knowing this would break Org mode... I think this is actually a problem of Org mode. Filling a paragraph should not require a special function. I will ask on their mailing list.
