### ISSUE TITLE
Develop - completion ivy-hydra required even if not using hydra

### ISSUE THREAD

**Issue by j-martin** [syl20bnr/spacemacs#13395]
The support for ivy was modified here, but now forces the user to install `ivy-hydra` regardless if it used or not: https://github.com/syl20bnr/spacemacs/pull/13377/files#diff-570753425f7f850ae31f63faa65fbe33R139

It broke my setup after pulling from develop today. I am on bb8ec23ec1794fb94f1fb4c4459af20fa3620c9c

I worked around the issue by adding it to my `dotspacemacs-additional-packages`.

**Comment by nixmaniack** [comment]
The [functionality](https://github.com/abo-abo/swiper/blob/64f05f4735bba8b708bc12cfc2cbfb7fb7706787/ivy.el#L451) is part of `ivy` package.
The recent changes decided to use the upstream version instead of maintaining spacemacs version. 

Also, `ivy-hydra` was part of spacemacs `ivy` layer for a long time – just not used where it was deemed I think. 

It'd be better if you can describe how it broke your setup.

Finally, if I look back at the changes of that PR - I think we can get rid of that explicit `require` block since the function is [autoloaded](https://github.com/abo-abo/swiper/blob/64f05f4735bba8b708bc12cfc2cbfb7fb7706787/ivy.el#L467-L468). @dalanicolai Did you face any issues if explicit require was not there?

**Comment by nixmaniack** [comment]
But again, removal of that `require` won't bring you the functionality under `C-o` if you're using `helm` layer and installing `ivy` as an extra package. In essence, spacemacs considers these two completion frameworks mutually exclusive(or at least one shadowing the other) as far as I know hence that would be a non-issue.

**Comment by dalanicolai** [comment]
@nixmaniack Indeed removing that require block does not break ivy or ivy-hydra functionality. I just uncommented it when I removed  the custom ivy-hydra menu (that I removed in this PR), as it seemed it had been there before that custom menu was implemented. Anyway... I will just comment it out again, as it was before this PR which should fix this issue.

**Comment by j-martin** [comment]
@nixmaniack I should have been clearer. I am using `helm` (the default completion system) and not the `ivy`. When loading emacs/spacemacs, I get a missing `ivy-hydra` error because of the `(require 'ivy-hydra)` that was added. Because the error occurs fairly early in the loading process, it leaves spacemacs in a barely usable state.

@dalanicolai I can confirm that https://github.com/dalanicolai/spacemacs/commit/5d2429bfeba23fa92027780a658c98c423efec1d fixes the issue on my side.

**Comment by smile13241324** [comment]
@j-martin strange, I am using helm too but I have not got this issue. Anyway I have merged the PR #13395 which disables the above mentioned `require` block. Please retry and close this issue when this solved your problem.

**Comment by j-martin** [comment]
@smile13241324 I tried the upstream. It fixed the issue.
