### ISSUE TITLE
Xserver Error in Wsl: Device 1 is not a termcap terminal device.

### ISSUE THREAD

**Issue by hemanta212** [syl20bnr/spacemacs#13391]
#### Description :octocat:
I am using spacemacs in WSL2 (arch linux) in windows. While starting emacs in gui xserver (like vcxrv, xming), it errors out. I can use it in terminal with no problems however.

Emacs version : 26.3-1
windows version : 2004 (19041.84)

Note that this doesnot happen in vanilla emacs. 

#### Reproduction guide :beetle:
- Use the setup described above 
- Start Emacs in gui mode

*Observed behaviour:* :eyes: :broken_heart:
![2020-03-20-08-33-26](https://user-images.githubusercontent.com/25475894/77132697-6c1a9780-6a88-11ea-8dc4-c112295bbc2e.gif)

*Expected behaviour:* :heart: :smile:
- Spacemacs should start normally or atleast give detailed debug message

**Comment by hemanta212** [comment]
still relevant.

**Comment by VictorCabello** [comment]
I have the same issue

**Comment by kevindashgit** [comment]
Ironically, I'm hitting this too - but I'm on `Doom Emacs`.  I just updated a ton of packages after 2 months of stagnating.

**Comment by shth** [comment]
Not sure how this works, but setting
```
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0
```
in my zshrc like stated [here](https://emacsredux.com/blog/2020/09/23/using-emacs-on-windows-with-wsl2) works for me

FYR, The expression evaluates to
```
$ echo $DISPLAY
192.168.0.1:0.0
```

**Comment by lebensterben** [comment]
> Not sure how this works, but setting
> 
> ```
> 
> export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0
> 
> ```
> 
> in my zshrc like stated [here](https://emacsredux.com/blog/2020/09/23/using-emacs-on-windows-with-wsl2) works for me
> 
> 
> 
> FYR, The expression evaluates to
> 
> ```
> 
> $ echo $DISPLAY
> 
> 192.168.0.1:0.0
> 
> ```

This is NOT a robust solution.

'nameserver' is not unique and may appear in arbitrary order. You can change it by setting DNS servers.

It happens to be the case that '192.168.0.1' points to your host system. But this is easily breakable.

**Comment by HanshenWang** [comment]
It's a well known hack to get proper port forwarding on WSL, which changes
the address everytime the VM boots up.

https://github.com/microsoft/WSL/issues/4106

I guess in order to narrow it down, we'd have to establish its not a WSL2
networking issue.

So I've been using WSL2 Ubuntu with Spacemacs for about a year now with good
stability. For those who have no specific requirements for a particular distro,
Microsoft has partnered with Canonical, making Ubuntu the most well supported
distro.

2 things I hope helps:

- It's recommended to use KellyK's PPA of emacs, found here: https://launchpad.net/~kelleyk/+archive/ubuntu/emacs

It includes a couple of patches related to xinput related bugs. Might help?

- I did remember having to address shenanigans concerning the $WSL_INTEROP
variable which prevented the opening of GUI Windows applications through the WSL
terminal. The fix that worked for me was https://github.com/microsoft/WSL/issues/5065.

Hope that helps. If there are further details, let me know! You mentioned
vanilla emacs starts fine in GUI mode? Whereas Doom and Spacemacs are
struggling? It might be a specific package? Is `debug-on-error` while in
terminal mode returning anything useful? Stuff is moving fast
with regards to WSL as well. With WSLg (built-in X server) around the corner,
hopefully it'll make windows > linux interop more painless.

**Comment by joefromct** [comment]
FYI, I have the same issue _without_ wsl so thought it was worth reporting:
 
- emacs 28.0.50 (native comp) 
- doom
- Hardware/OS is a chromebook running chromeos, with a crostini container running Arch linux. 
- I generally run emacs in a GUI window... i'm a bit confused as to why the error references a terminal device.

Some other relevant information maybe: 

``` sh 
joefromct@penguin ➜  ~ echo $DISPLAY
:2
joefromct@penguin ➜  ~ uname -a 
Linux penguin 5.4.109-26094 #1 SMP PREEMPT Sat Jun 26 21:31:00 PDT 2021 x86_64 GNU/Linux
joefromct@penguin ➜  ~ 
```

After sending something like `company-lsp` i see this in `*Messages`:
``` sh 
Error processing message (error "Device 1 is not a termcap terminal device").

```

Another thing, not sure if it's related, but I often use `vterm` and I noticed that if i run `set -o vi` it doesn't seem to stick... not sure if thats related.  It  seems to do nothing.  


I'll post back if i come up with a fix, but I suspect it has to do with port forwarding, etc.

**Comment by gerrywastaken** [comment]
It looks like this might have been fixed in Doom just 6 days ago: https://github.com/peterhoeg/doom-emacs/commit/cd5a4a266d5801a5034dcc33f04fdfe20a208e44

Also linking the related issue in case it's helpful: https://github.com/hlissner/doom-emacs/issues/4849

**Comment by lebensterben** [comment]
@gerrywastaken 

https://github.com/syl20bnr/spacemacs/search?q=%22core-cli%22&type=code

Completely unrelated.

**Comment by tomc1998** [comment]
@gerrywastaken this fixes the error for me, on linux with doom emacs. I was getting it all the time, unsure why

**Comment by gerry-atlantis** [comment]
> @gerrywastaken
> 
> https://github.com/syl20bnr/spacemacs/search?q=%22core-cli%22&type=code
> 
> Completely unrelated.

@lebensterben Thanks for letting me know. I'm sure you realised this, but the link only proves that core-cli isn't used. It doesn't directly address the problem mentioned in the commit body "due to core-cli changing `debugger`". The name of the plugin that does this isn't all that relevant. But I was just passing on the info in case it helped. If not, so be it.

**Comment by lebensterben** [comment]
@gerry-atlantis 

https://github.com/hlissner/doom-emacs/blob/a2a128d3a56a96610fce261f4df256d289135c74/core/core-cli.el

How is this related?

**Comment by lebensterben** [comment]
After some research:
This is a long known bug that WSL isn't xterm-compatible while it pretends to be xterm. This is reported at least since 2016. And upstream developer recommend to use M$'s new Terminal, which is supposed to be more xterm-compatible.

But there are still bunch of complaints on the same sort of error. For example, https://github.com/microsoft/Terminal/issues/283#issuecomment-511475261, has well-described the behaviour. And a possible workaround is to set TERM to rxvt.

I'm closing this issue since this is not related to Emacs at all.
