### ISSUE TITLE
Missing zsh aliases when executing from shell commands from emacs

### ISSUE THREAD

**Issue by IgorGee** [syl20bnr/spacemacs#13401]
#### Description :octocat:
When opening a shell `SPC !`, I was was expecting to be able to use all of my zsh aliases.
When I do `which $SHELL`, it correctly points to /usr/bin/zsh.

#### Reproduction guide :beetle:
- \*Have some alias in your .zshrc\*
- Start Emacs
- `SPC !`
- Type your alias command

*Observed behaviour:* :eyes: :broken_heart:
- `zsh:1: command not found: <ALIAS>

*Expected behaviour:* :heart: :smile:
- Execution of alias command

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d7868dae2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(haskell helm auto-completion emacs-lisp evil-snipe git markdown lsp org
         (shell :variables shell-default-height 30 shell-default-position 'bottom)
         syntax-checking yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD

**Comment by duianto** [comment]
It seems to be because the variable: `shell-command-switch`
has the default value: `"-c"`

If it's changed to:
```elisp
(setq shell-command-switch "-ic")
```
then the alias is recognized at the `SPC !` shell command prompt.

Source:
https://stackoverflow.com/questions/12224909/is-there-a-way-to-get-my-emacs-to-recognize-my-bash-aliases-and-custom-functions


It worked when I tried it with this alias:
```zsh
alias l="ls"
```
added to the end of: `/home/username/.zshrc`

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b5f0eb5f7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log common-lisp emacs-lisp git helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 python
                 (shell :variables shell-default-shell 'term shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

**Comment by IgorGee** [comment]
That worked. Thank you!
