### ISSUE TITLE
No spacemacs logo anymore.

### ISSUE THREAD

**Issue by zendevil** [syl20bnr/spacemacs#13402]
I reinstalled emacs+spacemacs on macOS, and although before the spacemacs logo was shown for spacemacs, now the emacs logo is shown. How do I fix this? I want to see the spacemacs logo as before instead.

**Comment by nixmaniack** [comment]
Are you talking about the app icon or the banner that's shown after [spac]emacs starts up? [More details](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) would help to diagnose the issue. Repro steps, environment details etc.

**Comment by duianto** [comment]
A screenshot could also be helpful.

If your seeing the default Emacs welcome screen:

![emacs_2020-03-25_15-40-57](https://user-images.githubusercontent.com/13420573/77548614-0f1b4900-6eaf-11ea-8e27-cff387e345bc.png)

Then Spacemacs didn't load. This can happen if Emacs is started before Spacemacs is cloned, because Emacs creates a `.emacs.d` directory in your home directory.

You can try to move (if you have any settings you want to save) or delete the `.emacs.d` directory and `.emacs` file (if there is one) from your home directory.

Then clone a fresh copy.

**Comment by zendevil** [comment]
I'm talking about the app icon. macOS Catalina.

**Comment by nixmaniack** [comment]
Without much details, I would suggest to just install again with emacs-plus tap.
