### ISSUE TITLE
M-x scad-preview gets executed from org source block

### ISSUE THREAD

**Issue by DaAngus** [syl20bnr/spacemacs#13413]
#### Description :octocat:
It is possible to run scad-preview from a Org document in a non intendend way.
The command renders scad code in 3d in a new buffer.

#### Reproduction guide :beetle:
- Have openscad installed
- Start Emacs
- Have org layer installed
- Load scad-preview from melpa Version: 20160206.1336
- Open a org document and paste this code block: 
     #+begin_src scad-preview
     cylinder(h = 40, r = 9);
     #+end_src

*Observed behaviour:* :eyes: :broken_heart:
- We can not evaluate this block with C-c C-c because no babel layer is found 
- Every time we add or change text the command M-x scad-preview-mode is run which toggles the preview ->

     #+begin_src scad-preview *foo*
     cylinder(h = 40, r = 9);
     #+end_src

  the input of foo after scad-preview toggles on, off, on     

*Expected behaviour:* :heart: :smile:
- Nothing because this should not be supported
  or better:
- evaluation dialog "are you sure" and with a parameter like 
     #+begin_src scad-preview :file preview.png
  a valid output like it is done with the plantUML layer.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d7868dae2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(react html better-defaults emacs-lisp git python helm lsp markdown multiple-cursors org scad scad-mode
       (shell :variables shell-default-height 30 shell-default-position 'bottom)
       version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<backtrace if relevant>>
```

**Comment by duianto** [comment]
Maybe `scad` support for org babel needs to be added to org-mode.

Because:
Pressing `C-c C-c` in the code block shows the prompt:
>Evaluate this scad-preview code block on your system? (y or n)

Answering: `y`
shows:
>No org-babel-execute function for scad-preview!

Searching for:
`No org-babel-execute function for`

Found this suggestion:
https://emacs.stackexchange.com/questions/17673/no-org-babel-execute-function-for-c-and-no-org-babel-execute-function-for-c
```elisp
(org-babel-do-load-languages
 'org-babel-load-languages '((C . t)))
```
Changing it to:
```elisp
(org-babel-do-load-languages
 'org-babel-load-languages '((scad . t)))
```
And trying to evaluate it, shows:
>Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "ob-scad")

The same message is shown after adding:
```elisp
(org-babel-do-load-languages
 'org-babel-load-languages '((scad . t)))
```
to the `dotspacemacs/user-config` section of `.spacemacs`, and restarting Spacemacs.
When opening a `scad.org` file containing the code block:
```org
#+begin_src scad-preview
cylinder(h = 40, r = 9);
#+end_src
```
Then the minibuffer shows:
>File mode specification error: (file-missing Cannot open load file No such file or directory ob-scad)

The reason plantUML works might be because org-mode has this file:
https://code.orgmode.org/bzg/org-mode/src/master/lisp/ob-plantuml.el

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b5f0eb5f7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey command-log emacs-lisp git helm html imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>
