### ISSUE TITLE
Emacs hangs when C-o within calc's interactive tutorial buffer

### ISSUE THREAD

**Issue by nhmacuk** [syl20bnr/spacemacs#13428]
#### Description :octocat:
Emacs hangs when C-o within calc's interactive tutorial buffer

#### Reproduction guide :beetle:
- Start Emacs
- open calc with `SPC a c c`
- open the help-file The GNU Emacs Calculator with `i`
- open the interactive tutorial
- go to the answer of exercise 1 with `f` `1` `RET`
- press `C-o` to go back to exercise
- press `C-o` again 

*Observed behaviour:* :eyes: :broken_heart:
Emacs freezes

*Expected behaviour:* :heart: :smile:
Nothing to happen, maybe print out message: cannot go back?

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d7868dae2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(csv better-defaults
     (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t shell-default-height 64 shell-default-position 'right)
     helm
     (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t)
     gnus git version-control syntax-checking spell-checking
     (plantuml :variables plantuml-jar-path "~/plantuml.jar")
     extempore
     (exwm :variables exwm-custom-init
           (lambda nil
             (exwm/autostart-process "Unclutter " "unclutter --timeout 2")
             (exwm/autostart-process "Firefox " "firefox")
             (exwm/autostart-process "Xcape" "xcape -e 'Control_L=Escape'")
             (exwm/autostart-process "Dropbox " "dropbox")))
     pandoc pdf html markdown latex bibtex deft lsp dap emacs-lisp ruby scala racket haskell octave org javascript
     (python :variables python-backend 'lsp)
     (java :variables java-backend 'lsp))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

_Edited by Duianto:
Changed `<` and `>` around the key bindings to backticks,
because the angle brackets and their contents don't appear in the Github preview._

**Comment by duianto** [comment]
The reproduction steps seems to be missing a step.

Because after:
>open the interactive tutorial

It shows a page with the title: `2 Tutorial`
Pressing `f` shows:
>user-error: No cross-references in this node

Pressing `1` opens the page: `3 Tutorial`

Pressing `f` opens the buffer: `HELM Info Follow Reference` with the candidates:
```
Summary
About This Manual
Embedded Mode
Starting Calc
```
Closing the helm buffer: `C-g`
and opening the `Answers to Exercises` link at the bottom of the page: `3 Tutorial`

Opens the page: `3.7 Answers to Exercises`
Pressing `f` here, shows the same message as above:
>user-error: No cross-references in this node

Pressing `1` opens the page: `3.7.1 RPN Tutorial Exercise 1`
Pressing `C-o` from here navigates to the previous page,
additional presses, navigates back to the first page: `The GNU Emacs Calculator`

This was observed in both:

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2ca55e28e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm markdown multiple-cursors
								 (org :variables org-agenda-files
											'("~/org/notes.org"))
								 python
								 (shell :variables shell-default-shell 'term shell-default-height 30 shell-default-position 'bottom)
								 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

and

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2ca55e28e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm html imenu-list
            (java :variables java-backend 'meghanda)
            javascript lsp
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (syntax-checking :variables syntax-checking-enable-by-default nil)
            treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by nhmacuk** [comment]
Ah, sorry, bit careless of me. I meant:
-                                              open emacs
- <M-x> "calc" <ret>                           open calc
- <i>                                          go to calc's info 
- </> "interactive tutorial" <ret>             go to interactive tutorial
- <1 1 1>                                      go to 3.1.1 RPN Calculations and the Stack
- <f C-n C-n C-n ret>                          follow reference named 1 (to the answer section)
- <C-o>                                        go back to 3.1.1
- <C-o>                                        emacs freezes

**Comment by duianto** [comment]
Those reproduction steps don't freeze Emacs for me.

<details><summary>
PopOS 19.10, Emacs 26 (Virtualbox guest with Win10 as host)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c3f13d039)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm markdown multiple-cursors
								 (org :variables org-agenda-files
											'("~/org/notes.org"))
								 python
								 (shell :variables shell-default-shell 'vterm shell-default-height 30 shell-default-position 'bottom)
								 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

<details><summary>
Windows 1903, Emacs 26.3, (snapshots: 27 and 28)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c3f13d039)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm helpful html imenu-list
            (java :variables java-backend 'meghanda)
            javascript latex lsp
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (syntax-checking :variables syntax-checking-enable-by-default nil)
            treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS PDUMPER LCMS2 GMP

</pre>
</details>
