### ISSUE TITLE
Lisp error: (invalid read syntax ")" ) where doesn't have bracktes open.

### ISSUE THREAD

**Issue by lukaswilkeer** [syl20bnr/spacemacs#13424]
#### Description :octocat:
After adding some functions to .spacemacs starting emacs causes a bug where they ask to choose the editing style and disable some packages, like js2-mode and line-numbers.
[My config file](https://gist.github.com/lukaswilkeer/3bc5b587a488d21b0714d5b99d1de613)
   
#### Reproduction guide :beetle:
- Start Emacs

**Reproduce bug report**
emacs --debug-init

*Observed behaviour:* :eyes: :broken_heart:

Spacemacs initialization needs to choose the editing style (vim, emacs, hybrid) prompting an error message due to the load of .spacemacs.

This bug deactivate the js2-mode, don't know others packages. On the first visualization appear that the spacemacs downloads all layers again, therefore this doesn't happen anymore.

*Expected behaviour:* :heart: :smile:

Start fast and without need to choose the style (again).

#### Backtrace :paw_prints:
![Screenshot_20200327_163910](https://user-images.githubusercontent.com/1809628/77794543-da43f900-704a-11ea-848e-26e0e3995e51.png)

**Comment by lukaswilkeer** [comment]
Reinstalled the spacemacs/emacs and line-numbers doesn't work.
Configurated the functions past-to-system and copy-from-systme on ```dotspacemacs/user-config``` and crashes emacs again, needing to reinstall the javascript layer and reproducing the same behaviour.

**Comment by jr0cket** [comment]
I see some very unusual things in your .spacemacs file that likely to affect the correct working of Spacemacs.

Your own custom functions on lines 5-30 should be defined in the `dotspacemacs/user-config` section and called using `add-hook` code for the modes that they are used with.

Its unclear why you would redefine some of the layers in `dotspacemacs/user-config`, lines 351-357.

Suggest you move the .spacemacs file out of the way and only add layer names and :variables in the `dotspacemacs-configuration-layers` list.  Once that is working without error, add your custom code to `dotspacemacs/user-config`

An example of a Spacemacs configuration file with layers and variables and custom code in `dotspacemacs/user-config`
https://github.com/practicalli/spacemacs.d/blob/master/init.el

**Comment by lukaswilkeer** [comment]
Moved all my custom configs and functions to dotspacemacs/user-config, but still persists.
Maybe the the copy-from-system and paste-to-system is causing a problem when it calls the interactive method.

Don't know I can do, if you have any suggestions, please, touch me.

**Comment by duianto** [comment]
The issue is caused by the trailing single quotes after some symbols:
`clipboard-kill-ring-save` in the `copy-from-system` function:
```diff
-        (call-interactively 'clipboard-kill-ring-save'))
+        (call-interactively 'clipboard-kill-ring-save'))
```

and after `copy-from-system` and `past-to-system` assignments:
```diff
-  (setq interprogram-cut-function 'copy-from-system')
-  (setq interprogram-paste-function 'past-to-system')
+  (setq interprogram-cut-function 'copy-from-system)
+  (setq interprogram-paste-function 'past-to-system)
```

Here's what the single quote (apostrophe) means:
https://stackoverflow.com/questions/1539144/what-is-apostrophe-in-lisp-scheme
https://www.gnu.org/software/emacs/manual/html_node/elisp/Quoting.html

---

The comment in the function:
```elisp
  (defun js-identation-level (n)
    // search for .editorconfig
    (setq js2-basic-offset n))
```
isn't using the elisp comment syntax which are `;;` semicolons:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Comment-Tips.html

Emacs doesn't seem to complain about them (at least not in this case). But it's probably best to use the correct syntax.
```diff
-    // search for .editorconfig
+    ;; search for .editorconfig
```

---

In the `dospacemacs/user-config` section:
```elisp
	'(setq-default dotspacemacs-configuration-layers
		(syntax-checking :variables syntax-checking-enable-tooltip nil)
		(global-wakatime-mode)
    (editorconfig-mode 1)
		(wakatime :variables
			wakatime-api-key "53e44d0d-0ac3-44d2-b263-1c556194267c"
			wakatime-cli-path "/usr/bin/wakatime"))
  '(setq js2-strict-missing-semi-warning nil)
  '(setq js-offsetlevel-level 2)
```

Remove the leading single quotes before `(setq`, otherwise the expressions won't be evaluated. (I'm guessing that you added them because the expressions in the `custom-set-variables` section below have leading single quotes)

But the `custom-set-variables` function handles assigning the variables to their provided values, therefore it just expects a list containing the variable and it's value.

Your mixing the definitions of layers and their variables with enabling the modes.
Move:
```elisp
    (global-wakatime-mode)
    (editorconfig-mode 1)
```
below the expression:
```elisp
(setq-default dotspacemacs-configuration-layers
 ...
 )
```
It does work to declare layers and their variables from the user config section. But it's probably better to define all layers and their variables near the top of `.spacemacs`, in the existing 
`dotspacemacs-configuration-layers` section:
```elisp
   dotspacemacs-configuration-layers
   '(
     (syntax-checking :variables syntax-checking-enable-tooltip nil)
     (wakatime :variables
               wakatime-api-key "53e44d0d-0ac3-44d2-b263-1c556194267c"
               wakatime-cli-path "/usr/bin/wakatime")
     )
```
With your other layers and their variables defined above or below them.

**Comment by lukaswilkeer** [comment]
Make a fresh install and setting the custom variables to js-configs, and removing the offsetlevel, altougth I use spaces and js2 does the rest.

setting the js-semi-warning to nil causes the same.

**Comment by duianto** [comment]
Can you update your `.spacemacs` file:
https://gist.github.com/lukaswilkeer/3bc5b587a488d21b0714d5b99d1de613

and you might also want to fix the typo in the filename:
```
before: .speacemacs
after:  .spacemacs
```

There's a typo (the `m`) in the reload file key binding:
`SPC f e R` is bound to `dotspacemacs/sync-configuration-layers`.

Can you provide reproduction steps:
- Start Emacs
- ...

Observed behavior:
...
Expected behavior:
...

Copy and paste any error messages as they are written.

Include your system information, copy it to your clipboard with: `SPC h d s`

**Comment by lukaswilkeer** [comment]
There's already a copy/paste implemented. Does't need this. The apostrophe on the setq doesn't do nothing, therefore the behavior is the same.

Closed issue since I migrate to emacs and copy/paste is already implemented.
