### ISSUE TITLE
Documentation for the preconfigured custom layouts is inconsistent with actual behavior.

### ISSUE THREAD

**Issue by OrdoFlammae** [syl20bnr/spacemacs#13449]
#### Description :octocat:
The documentation for the @Spacemacs preconfigured custom layout is inconsistent with actual behavior.

#### Reproduction guide :beetle:
- Start Emacs
- Press `SPC l o e`

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs opens a custom layout in the `.spacemacs.d` directory.

*Expected behaviour:* :heart: :smile:
Spacemacs opens a custom layout in the `.emacs.d` directory.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: custom (rev. 463bbd536)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asm
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-backend 'lsp-ccls c-c++-enable-clang-support t c-c++-enable-clang-format-on-save t)
 (clojure :variables clojure-enable-linters 'clj-kondo clojure-enable-clj-refactor t clojure-enable-sayid t)
 (cmake :variables cmake-enable-cmake-ide-support t)
 common-lisp dash emacs-lisp erc
 (git :variables git-magit-status-fullscreen t)
 github helm
 (html :variables css-enable-lsp t less-enable-lsp t scss-enable-lsp t html-enable-lsp t)
 java javascript lsp markdown multiple-cursors neotree
 (org :variables org-enable-github-support t org-enable-org-journal-support t org-enable-trello-support t org-enable-epub-support t org-projectile-file "TODOs.org")
 (python :variables python-backend 'lsp python-lsp-server 'pyls)
 react
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking systemd tern typescript
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t git-gutter-use-fringe t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM THREADS

**Comment by OrdoFlammae** [comment]
I worded this the way I did because I'm not sure if the mistake is in the documentation or in the code. The code related is at https://github.com/syl20bnr/spacemacs/blob/c7a103a772d808101d7635ec10f292ab9202d9ee/layers/%2Bspacemacs/spacemacs-layouts/packages.el#L199-L202.

**Comment by duianto** [comment]
Do you mean this documentation?
https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#custom-layouts
>@Spacemacs | e | Custom perspective containing all buffers of ~/.emacs.d

You said that your observing:
>Spacemacs opens a custom layer in the .spacemacs.d directory.

I'm guessing that you meant `custom layout` instead of `custom layer`.
But I'm not sure what you mean by a layout opens in a directory.

Since you mention `.spacemacs.d`, then your probably using the `Alternative dotdirectory`:
https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#alternative-dotdirectory

I'm using the default `.emacs.d` directory and 
`SPC l o e` creates a new layout with the name `@Spacemacs`,
and the `~/.spacemacs` (dotfile) file is opened.

Your right that the DOCUMENTATION.org description doesn't match the behavior of `SPC l o e`.

It says that all buffers that are associated with `~/.emacs.d` (or `~/.spacemacs.d`) should be contained in the new layout.

But the new layouts buffer list (`SPC b b` or `SPC l b`) is empty (only the `recentf` section is shown).

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.0.90
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c3f13d039)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm helpful html imenu-list
            (java :variables java-backend 'meghanda)
            javascript latex lsp
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (syntax-checking :variables syntax-checking-enable-by-default nil)
            treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by OrdoFlammae** [comment]
Yes, I did mean custom layout. Sorry, I keep mixing up layer and layout.

I was expecting that `SPC l o e` would open a projectile layout that was based in the `~/.emacs.d` directory. Is that not how that works?

I am using `~/.spacemacs.d/` instead of `~/.spacemacs`, but I don't understand how that changes anything. My `~/.emacs.d/` still exists, and the function isn't replaced by `~/.spacemacs.d/`.

**Comment by duianto** [comment]
Ok, since I've never tried it, I've misunderstood how `.spacemacs.d` works.

I thought that it was an alternative to the `.emacs.d` directory, but I see now that it makes it possible to move and rename the `.spacemacs` file to `.spacemacs.d/init.el`.

---

This might have been the commit where the `SPC l o e` key binding (it used `SPC L o e` back then) was defined to find the dotfile:

Pimp perspectives layer (using persp-mode) https://github.com/syl20bnr/spacemacs/commit/50ceba2a6eee695364e5ff7302daafe93ab8196d#diff-9db228b4bfd82f6978ba62d2aba96b74R351-R354
>CestDiego authored and syl20bnr committed on Sep 30, 2015 

So it seems like the current behavior hasn't been changed since then.

But the description in that commit just said:
| Key Binding | Description                                              |
|-------------|----------------------------------------------------------|
| SPC L o e | Emacs custom perspective                                 |
| SPC L o E | ERC custom perspective (needs the erc layer enabled)     |
| SPC L o i | RCIRC custom perspective (needs the rcirc layer enabled) |
| SPC L o o | Org custom perspective                                   |

The current description seems to have been changed in this commit:

Move eyebrowse to spacemacs-layouts layer and add documentation https://github.com/syl20bnr/spacemacs/commit/944960daf836f333d0d04a518848371bdabd64d2
>Add toggle capability with ? for workspaces transient state
Remove the variable eyebrowse-display-help

### From:
| Key Binding | Description                                                                               |
|-------------|-------------------------------------------------------------------------------------------|
| e         | Emacs custom perspective                                                                  |
| E         | ERC custom perspective (needs the erc layer enabled - configurable, check ERC docs)       |
| i         | RCIRC custom perspective (needs the rcirc layer enabled - configurable, check RCIRC docs) |
| o         | Org custom perspective                                                                    |

### To:
| Name       | Key Binding | Description                                                                     |
|------------|-------------|---------------------------------------------------------------------------------|
| `@Spacemacs` | e         | Custom perspective containing all buffers of =~/.emacs.d=                       |
| `@ERC`       | E         | Custom perspective containing all ERC buffers (needs the erc layer enabled)     |
| `@RCIRC`     | i         | Custom perspective containing all RCIRC buffers (needs the rcirc layer enabled) |
| `@Org`       | o         | Custom perspective containing all the =org-agenda= buffers                      |

The current version has added entries for `@Mu4e` and `@Slack`.
https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#custom-layouts

@syl20bnr Was/Is the intention to implement the behavior in the description?
