### ISSUE TITLE
nim layer: indentation is broken on paste

### ISSUE THREAD

**Issue by yglukhov** [syl20bnr/spacemacs#13470]
#### Description :octocat:
nim layer: indentation is broken on paste

#### Reproduction guide :beetle:
- Start Emacs
- Open any test.nim file
- Type in the following
```
proc foo() =
  echo "foo"
proc bar() =
  echo "bar"
```
- Press gg to go to start and press y3j to yank
- Press 3j to to go to start of line 4
- Press p to paste. Observe the result.

*Observed behaviour:* :eyes: :broken_heart:
```
proc foo() =
  echo "foo"
proc bar() =
  echo "bar"
  proc foo() =
    echo "foo"
    proc bar() =
      echo "bar"
```

*Expected behaviour:* :heart: :smile:
```
proc foo() =
  echo "foo"
proc bar() =
  echo "bar"
proc foo() =
  echo "foo"
proc bar() =
  echo "bar"
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c3f13d039)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp org nim python git shell html restructuredtext)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
Confirmed.
After pasting: `p`, then the minibuffer shows:
>Indenting region...done

### Cause
By default Spacemacs advices the yank and evil-paste functions to call `spacemacs//yank-indent-region`:
https://github.com/syl20bnr/spacemacs/blob/0a7ab7873af1948125b8363a20d3a0cb8bee3fc9/layers/%2Bspacemacs/spacemacs-defaults/funcs.el#L1465-L1466

### Solution
The docstring for `spacemacs//yank-indent-region` says:
https://github.com/syl20bnr/spacemacs/blob/0a7ab7873af1948125b8363a20d3a0cb8bee3fc9/layers/%2Bspacemacs/spacemacs-defaults/funcs.el#L1445-L1447

Which means that if `nim-mode` is added to the `spacemacs-indent-sensitive-modes` variable, then it will be excluded from being indented when pasting.

It can be done now from the `dotspacemacs/user-config` section with:
```elisp
(add-to-list 'spacemacs-indent-sensitive-modes 'nim-mode)
```
or if the `nim` layer shouldn't indent by default, then that line can be added in a PR to the 
`nim/init-nim-mode` functions `:init` section:
https://github.com/syl20bnr/spacemacs/blob/0a7ab7873af1948125b8363a20d3a0cb8bee3fc9/layers/%2Blang/nim/packages.el#L32-L38

Currently `spacemacs-indent-sensitive-modes` contains these modes:
```
(asm-mode coffee-mode elm-mode haml-mode haskell-mode slim-mode makefile-mode makefile-bsdmake-mode makefile-gmake-mode makefile-imake-mode python-mode yaml-mode)
```

The docstring for the `spacemacs//yank-indent-region` function also says:
>(with universal arg don't indent)

which means that if one only want to stop the automatic indentation sometimes when pasting, then one can press: `SPC u p`

### Result
The expected behavior is observed when either:
- `nim-mode` is added to the `spacemacs-indent-sensitive-modes` variable
- or when pasting with `SPC u p`
```nim
proc foo() =
  echo "foo"
proc bar() =
  echo "bar"
proc foo() =
  echo "foo"
proc bar() =
  echo "bar"
```

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0a7ab7873)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 command-log dap emacs-lisp git helm helpful html imenu-list javascript
 (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
 multiple-cursors nim
 (org :variables org-agenda-files
      '("~/org/notes.org"))
 (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by yglukhov** [comment]
> Which means that if nim-mode is added to the spacemacs-indent-sensitive-modes variable, then it will be excluded from being indented when pasting.

Imho it makes sense to do this by default. But I'm just a newbie with spacemacs, so don't quote me.

**Comment by lebensterben** [comment]
I applied the fix of @duianto in the last commit.
