### ISSUE TITLE
org-tags-view broken.

### ISSUE THREAD

**Issue by acosmicjoke** [syl20bnr/spacemacs#13509]
None of the advanced search options in org-tags-view described in the manual https://orgmode.org/manual/Matching-tags-and-properties.html#Matching-tags-and-properties, like logical operators, excluding tags, searching for properties or todo states work.
This issue still persists if I use a fresh autogenerated .spacemacs file with only the org layer uncommented so it's not an issue with the settings in my own dotfile, it also persists using the develop branch. Everything works as expected in vanilla emacs.

Reproduction guide beetle
- Start Emacs
- M-x org-tags-view
- Search the contents of org-agenda-files with an expression that is more complicated than a list of tags divided with space.

Observed behaviour: eyes broken_heart
- Searching for a tag or a list of tags divided with space works.
- Anything more complicated, like +apple-orange, or work+TODO​="WAITING" doesn't.

Expected behaviour: heart smile
- Searching works as described in the org-mode manual.

System Info computer
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
      spell-checking syntax-checking version-control emacs-lisp shell-scripts python c-c++ html bibtex
      (latex :variables latex-build-command "LatexMk" TeX-view-program-list
             '(("Zathura"
                ("zathura %o"
                 (mode-io-correlate " --synctex-forward %n:0:%b -x \"emacsclient +%{line} %{input}\""))))
             TeX-view-program-selection
             '((output-pdf "Zathura"))
             TeX-source-correlate-mode t latex-enable-auto-fill t latex-enable-folding t latex-enable-magic t TeX-source-correlate-start-server t TeX-source-correlate-method 'synctex)
      pdf-tools evil-snipe evil-cleverparens themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by davidpiano** [comment]
If you temporarily deactivate helm-mode, do you get the org-tags-view functions that you need?
(You can toggle helm-mode by doing `<SPC> <SPC>` and searching for helm-mode.)

**Comment by acosmicjoke** [comment]
Yes, it seems to work without helm on. Temporarily switching to Ivy is one solution I suppose.

**Comment by davidpiano** [comment]
Yes, it feels less like a solution and more like a temporary work-around. I have no idea whether Helm can be made to handle org-tags in a more helpful/more correct way.

**Comment by duianto** [comment]
Could the issue be that helm selects the first existing tag that it finds.
And the selection needs to be moved up to the line that starts with: `[?]`

For example, when typing: `+apple-orange` or `work+TODO="WAITING"`
- In Spacemacs, the `work` tag is selected.

![emacs_2020-06-13_08-49-19](https://user-images.githubusercontent.com/13420573/84562373-57cafb80-ad54-11ea-93de-1abb440938cf.png)
![emacs_2020-06-13_08-50-50](https://user-images.githubusercontent.com/13420573/84562374-5a2d5580-ad54-11ea-989c-f39b46ebdba3.png)

- Without Spacemacs, just Emacs and Helm, the `apple` tag is selected.

![emacs_2020-06-13_08-53-12](https://user-images.githubusercontent.com/13420573/84562383-74673380-ad54-11ea-893b-aa15fc9df858.png)
![emacs_2020-06-13_08-54-00](https://user-images.githubusercontent.com/13420573/84562384-75986080-ad54-11ea-8a5e-c7f6c28dda2e.png)

If that's not the issue for you, then something might be different in your setup, because this is what I'm seeing in both Linux and Windows:
- Spacemacs (on both branches: `master` and `develop`) (updated packages)
- Emacs and just `helm` installed (only tested in `Windows`) (updated packages)
- Emacs without any packages (`emacs --quick`)

The org versions are:
- Spacemacs:
>Org mode version 9.3.7 (9.3.7-2-g706970-elpaplus @ c:/Users/username/.emacs.d/elpa/26.3/develop/org-plus-contrib-20200608/)
- Without Spacemacs:
>Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ c:/Users/username/Applications/emacs-26.3-x86_64/share/emacs/26.3/lisp/org/)

With this example org file: `org-tags-view_broken._13509.org`
```elisp
#+TODO: TODO WAITING | DONE CANCELED
* a                                                                   :apple:
* b                                                                  :orange:
* c                                                            :apple:orange:
* d                                                                    :work:
* WAITING e                                                            :work:
```

It's added to the `org-agenda-files` list:
```elisp
(setq org-agenda-files '("~/temp/org-tags-view_broken._13509.org"))
```

In the screenshots below:
- Spacemacs is to the left
- Emacs and `helm` in the middle
- and just `emacs --quick` to the right

### Opening `M-x org-tags-view` and searching for: `+apple-orange`

Finds the heading with the `apple` tag, but not the one with the `apple` and `orange` tags, as expected.

![+apple-orange](https://user-images.githubusercontent.com/13420573/84562400-a1b3e180-ad54-11ea-9ea6-22df5f6153dd.png)

### Opening `M-x org-tags-view` and searching for: `work+TODO="WAITING"`

Finds the heading with both the `work` tag and the `WAITING` state, but not the heading with only the `work` tag, as expected.

![work+TODO=(dblquote)WAITING(dblquote)](https://user-images.githubusercontent.com/13420573/84562404-a5dfff00-ad54-11ea-9411-cf219b41f08f.png)

---

>Searching for a tag or a list of tags divided with space works.

Adding a space between the tags doesn't work for me.

When `helm-mode` is enabled, then it's possible to add a space between the tags, but it only searches for the first word.

With `helm-mode` disabled, then `SPC` is bound to: `minibuffer-complete-word`
Pressing `SPC` shows `[Sole completion].

---

### System Info

<details><summary>
PopOS 20.04 (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5fcd84d84)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp fasd git helm lsp markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 ranger
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking themes-megapack treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

<details><summary>
Windows 1903 (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5fcd84d84)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 emacs-lisp git helm html javascript lsp
 (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
 multiple-cursors
 (org :variables org-agenda-files
      '("~/org/notes.org" "~/temp/org-tags-view_broken._13509.org"))
 (python :variables)
 ranger
 (shell :variables shell-default-shell 'eshell shell-default-height 30)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>
