### ISSUE TITLE
[Wishlist] Don't take over emacs.d, deprecate layers

### ISSUE THREAD

**Issue by benwbooth** [syl20bnr/spacemacs#1351]
I've been messing around with spacemacs for the last week, but I've decided to hold off switching over for the time being. I really like the idea of an emacs distro, where someone with the domain knowledge creates a good, well-integrated emacs experience, with well-configured curated list of emacs extensions. And I really like the space leader key approach to keyboard shortcuts. But there are several problems I have with spacemacs:

1. Spacemacs takes over emacs.d
I have a lot of custom configurations in my current emacs setup. Thankfully, with spacemacs's good defaults, I don't need most of it. But for the stuff I do need, it's a pain to add to spacemacs compared to my old config. I wish I could add spacemacs as an ELPA/Quelpa package, just like any other emacs package, and merge it with my current setup, instead of having to ditch my current config and go 100% spacemacs just to try it out.

2. I don't understand the value of layers
Maybe I'm just a spacemacs noob, but my current emacs config uses Quelpa to download all my packages, and it works great. The config layers approach seems to add a lot of complexity for little value. I guess with layers you can rollback your config to previous versions, but really, how often is that useful? If I install a package and then decide I don't like it, I can just uninstall it. I wish spacemacs took a more traditional approach to extensions (e.g. Quelpa) that was compatible with other emacs configurations. Then updating spacemacs and any of its extensions would use the same approach as with Quelpa.

Layers are a pain to set up and configure. With quelpa, I can load an emacs package from anywhere and configure in the same place. Adding extensions to layers requires using git submodules to update, then adding the package name to the layer list, then creating a config function just to run use-package. In my (admittedly short) experience, layers are a real pain in the ass and not worth whatever value they provide.

3. Some weird bugs
I've noticed a few glaring issues with spacemacs. Of course I realize this is beta software, but if I was using vanilla emacs I could probably hack around these problems. 

3a. The focus sometimes stays on the minibuffer after opening a file, and I have to use the mouse to click into the buffer window in order to get out of the minibuffer. Even C-g doesn't work. I see some message in the minibuffer about yasnippets after loading the file, not sure if that's related to the problem.

3b. Persistent highlight colors make the highlighted text unreadable on most of the themes-megapack themes. This doesn't apply to the solarized themes, but to about 90% of the dark themes from themes-megapack that I tried. If you use / to do a search with persistent highlighting using a dark theme, the background of the highlighted text will be yellow, and the foreground will be white, making the text unreadable on my screen. This is a minor quibble, but I was able to solve this in vanilla emacs using a custom face-remapping-alist to set the lazy-highlight and isearch colors to a custom defface. However, somehow this approach doesn't seem to work under spacemacs. It's a minor issue, but it hurts my productivity.

Sorry for the wall of text, I really like spacemacs, and I hope it improves to the point where I can just load the spacemacs package from ELPA/Quelpa and don't have to deal with all the customization hacks in my current init.el. Thanks for all your effort and hard work!

**Comment by syl20bnr** [comment]
Thank you for the feedbacks.

1. spacemacs would not be spacemacs if it was a MELPA package. The philosophy of spacemacs is to import a configuration into it by using layers. It is important because it is the foundation allowing to make so many package working together even with [heavily customized user configurations](https://github.com/chrisbarrett/.emacs.d/tree/master/private).

2. In `develop` there is a new variable `dotspacemacs-additional-packages` where you can list a package without the need to put it in a configuration layer: https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/.spacemacs.template#L27-31
So if a layer is not yet required you can add packages to this variable and put there configuration in `dotspacemacs/config` function.

The layer are to group related packages together or to group private packages under an unique layer, you are not compeled to do 1 layer per package. Using layers brings additional benefit like:
- quick enable/disable of a group of related packages.
- support for `helm-spacemacs` on `SPC f e h` to quickly navigate the configured packages
- defining soft dependencies between packages of other layers with `pre-init` and `post-init` function (see how flycheck is configured in python layer: `SPC f e h flycheck` then select `(python) flycheck` RET). A `post-init` will be executed only if a corresponding `init` function is found, so if you don't use the layer where the `init` function is defined your `post-init` won't be executed and the package would be marked as orphaned and uninstalled. Of course you can use `eval-after-load` for this but it would not be as integrated with spacemacs.

I don't think layers are a pain to configure, you can `SPC : configuration-layer/create-layer` or copy past an exisiting one then it is a matter of adding a symbol to a list and creating a function `<layer>/init-<package>`. How can it be a pain ? For the extensions submodule it is planned to support Quelpa and remove all the sub-modules see [here](https://github.com/syl20bnr/spacemacs/issues/143) and [here](https://github.com/syl20bnr/spacemacs/issues/5) (and yes this was the fifth issue of spacemacs :-), when the update mechanism is done I will tackle it).

**Comment by tuhdo** [comment]
@benwbooth the persistent highlight compatibility with theme is being fixed with this PR: https://github.com/syl20bnr/spacemacs/pull/1327

After that, you should be able to use persistent highlighting in any theme. It's just the default colour is yellow, which is annoying.

**Comment by benwbooth** [comment]
Thanks for your reply!

I really like the ```dotspacemacs-additional-packages``` option. Since you are adding quelpa capabilities to spacemacs, will it be possible to add a quelpa-like package configuration to the ```dotspacemacs-additional-packages``` option? For example, in my current init.el, I have:

```
(quelpa '(neotree :fetcher github :repo "jaypei/emacs-neotree"))
(quelpa '(switch-to-new-buffer :fetcher wiki :files ("switch-to-new-buffer.el")))
```

Would it be possible to add something like ```(switch-to-new-buffer :fetcher wiki :files ("switch-to-new-buffer.el"))``` as an item in the ```dotspacemacs-additional-packages``` list, instead of just a Melpa package name? Having that capability would allow users to avoid the complexity of layers completely for both packages and extensions if they don't need them.

I still think spacemacs would be an easier sell if it didn't take over the entire ```~/.emacs.d``` folder. What if spacemacs could be installed to ```~/.emacs.d/spacemacs```? And all the spacemacs-specific layers and folders were in that subfolder? Then users could keep their ```init.el``` files, and simply add a line or two to load all the spacemacs stuff? 

I think it would also be an improvement if spacemacs could be installed via package.el instead of using git, since package.el is the standard emacs packaging system. Couldn't spacemacs and all its layers just go in ```~/.emacs.d/elpa/spacemacs```? 

Thanks for your response, and thanks for moving the highlighting issue into a separate bug report.

**Comment by darkfeline** [comment]
@benwbooth Regarding spacemacs taking over `.emacs.d`: Have you tried copying your old configuration to, e.g. `~/.emacs.d/private` and then adding `(load-file "~/.emacs.d/private/init.el")` to `dotspacemacs/config`?  An Emacs configuration is just Elisp, it doesn't matter where it is as long as you load it, and nothing in Spacemacs stops you from loading your personal Elisp code.  The only thing Spacemacs interferes with is package installation, and you can easily disable Spacemacs's uninstalling your packages.

**Comment by TheBB** [comment]
This seems to be a wontfix, then.

**Comment by waffletower** [comment]
@darkfeline  Regarding spacemacs taking over .emacs.d: Have you tried copying your old configuration to, e.g. ~/.emacs.d/private and then adding (load-file "~/.emacs.d/private/init.el")

That is quite backwards, spaceemacs ought to be the load-file in the user's top level init file.
