### ISSUE TITLE
unable to navigate to "next" page in help menu (narrow/numbers comes up instead)

### ISSUE THREAD

**Issue by neuroradiology** [syl20bnr/spacemacs#13519]
#### Description :octocat:
unable to navigate to "next" page in help menu

when attempted, the narrow/numbers menu/command comes up instead

#### Reproduction guide :beetle:
- Start Emacs
- push [SPC] to enter main menu
- [C-h] for help
- read the UI shown in help menu, which suggests [n] for next page of help
- pushing [n] results in the narrow/numbers menu coming up

*Observed behaviour:* :eyes: :broken_heart:
the end result of [SPC C-h n] is 
the narrow/numbers menu

*Expected behaviour:* :heart: :smile:
UI implies that [SPC C-h n] should result in the "next" page of help menu

I also tried  [SPC C-h C-n] 

and [SPC C-h M-n] 

without success.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
If you forgot to mention in your reproduction steps that the `narrow/numbers` keys appear the second time `n` is pressed when trying to switch to the third page.

Meaning that `SPC C-h n` shows the next page as expected, but pressing `n` now shows the `narrow/numbers` keys.

Then the confusion might be that `C-h` has to be pressed before the paging/help keys.

Example:
With the default Emacs size (not maximized):
- Pressing: `SPC`
opens the menu with the following text in the minibuffer (at the bottom):
`Spacemacs root (1 of 3) [C-h paging/help]`
- Pressing: `C-h`
shows: `SPC-  n -> next-page, p -> previous-page, u -> undo-key,` (etc...)
- Pressing: `n` or `C-n` switches to the next page
Now the text in the minibuffer just shows: `SPC-`
the paging/help keys are not active, any key that's pressed here, is the same as pressing `SPC` followed by that key.
- Pressing: `n` in this state, is the same as pressing `SPC n`
and it shows: `SPC n- narrow/numbers  [C-h paging/help]`

To keep navigating to the next or previous page, `C-` (`Ctrl`) can be held down while first pressing `h` followed by `n` or `p`.

---

If nothing's missing in the reproduction steps and your getting the narrow/numbers key bindings on the first press of `n` when pressing: `SPC C-h n`

Then something might be broken in your setup.
Because the next page appears for me on both the `master` and `develop` branches of Spacemacs, with updated packages, in both PopOS and Windows.


<details><summary>
System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5fcd84d84)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 (colors :variables colors-enable-nyan-cat-progress-bar t)
 emacs-lisp git helm html javascript lsp
 (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
 multiple-cursors
 (org :variables org-agenda-files
      '("~/org/notes.org"))
 (python :variables)
 ranger
 (shell :variables shell-default-shell 'eshell shell-default-height 30)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

---

The key bindings menu is handled by the package `which-key`.

Here is the documentation for the paging/help keys:
https://github.com/justbur/emacs-which-key#paging-options

It's also possible to bind your own keys:
https://github.com/justbur/emacs-which-key#method-2-bind-your-own-keys

**Comment by neuroradiology** [comment]
Thank you for your assistance.

This is an excellent place to start debugging, but I don't have access to that machine at present.

Closing the issue unless it recurs.
