### ISSUE TITLE
Spacemacs Mode Line flickers

### ISSUE THREAD

**Issue by SreenivasVRao** [syl20bnr/spacemacs#13514]
#### Description :octocat:
Spacemacs Mode Line flickers (even on clean install with develop branch - emacs 27/ spacemacs 0.3)

#### Reproduction guide :beetle:
- Start Emacs
- Press meta-key repeatedly in any buffer.
- Current buffer mode line goes out of focus.

*Observed behaviour:* :eyes: :broken_heart:
Here's a video: https://i.imgur.com/9b4ov0x.mp4
I'm only pressing the Meta key repeatedly.
Mode line seems to go out of focus
automatically on each key-press.

*Expected behaviour:* :heart: :smile:
Mode line to retain focus and not change colours.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.91
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7f92a43)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(yaml markdown lsp python c-c++ ivy
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      syntax-checking git auto-completion ipython-notebook
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
      (c-c++ :variables c-c++-backend 'lsp-ccls)
      (python :variables python-test-runner 'pytest)
      (python :variables python-lsp-server 'mspyls)
      (java :variables java-backend 'lsp)
      neotree)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
What OS are you using, and does it use the Meta (Alt) key for something that makes Emacs lose focus?

Nothing happens to the mode line for me when Emacs has focus and the Alt key is pressed once or multiple times.

But if I hold down `Alt` and press `TAB` then Emacs loses focus, because PopOS (https://pop.system76.com/) shows a window with icons for the currently running applications.

The mode line text becomes gray, to indicate that the window is out of focus. (the same thing happens to the mode lines in the non-selected windows inside the Emacs frame)

When `Alt` is released then the selected windows mode line sometimes blinks twice (quickly) and the mode line text shows the default colors again.

<details><summary>
PopOS 19.10 with Emacs 26.3.50 and 27.0.91
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.91
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c6f47bd87)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(auto-completion command-log emacs-lisp git ivy lsp markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 (python :variables python-lsp-server 'mspyls)
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

</pre>
</details>
