### ISSUE TITLE
Theme requires changing and then back again

### ISSUE THREAD

**Issue by max-sixty** [syl20bnr/spacemacs#13532]
#### Description :octocat:

Spacemacs requires changing to a different theme and back to original theme in order to show the correct theme.

When I launch Spacemacs, it launches with a color scheme that doesn't match the one selected:

<img width="327" alt="image" src="https://user-images.githubusercontent.com/5635139/80530556-086c6f80-894e-11ea-8a67-c4190946a5cb.png">

When I select a different theme (`SPC T s`), and then revert to the original theme, it then shows the correct theme (you can see the background is a different color):

<img width="307" alt="image" src="https://user-images.githubusercontent.com/5635139/80530695-3fdb1c00-894e-11ea-944f-36a829307f42.png">

This is over an ssh (not `-X` / `-Y`) connection on CentOS6

Edit: after posting this I realize it looks extremely marginal. For whatever reason, it's much more impactful when using, to the extent that it's difficult to read some dark text. I can find better examples if helpful; hopefully this at least shows something is happening

#### Reproduction guide :beetle:

Unfortunately this is likely a connection-specific issue; I don't think this is easily reproducible. If it doesn't ring any bells for anyone, feel free to close.

The theme is `solarized-wombat-dark`, given that's the theme that seems to look best over an SSH connection.

Thanks for such a superb ~product!~ thing!

**Comment by charlag** [comment]
No matter what I do, I can't get background to be light, powerline, helm and buttons change, background doesn't. I'm lost.

(also Spacemacs if awesome but not really a "product" :wink:)

**Comment by charlag** [comment]
My `dotspacemacs/emacs-custom-settings` had `custom-set-faces` twice, I commented out both and it works now.

**Comment by jr0cket** [comment]
Please close this issue.

**Comment by max-sixty** [comment]
> Please close this issue.

?

**Comment by max-sixty** [comment]
In case the original issue seems overly specific, there seems to be a legitimate general issue: why would changing to a different theme and then back again cause colors to change? I have no other colors set in my dotfile.

**Comment by duianto** [comment]
I don't have centOS or a server to SSH to.

But in PopOS 20.04, when Spacemace is started in the terminal: `emacs -nw`
with the first theme in `dotspacemacs/themes` set to: `solarized-wombat-dark`

Then the background color becomes slightly darker after switching to another theme `SPC T s` and back to `solarized-wombat-dark`

Before

![image](https://user-images.githubusercontent.com/13420573/84741786-db345900-afaf-11ea-8cfc-4f893cd607d0.png)

After

![image](https://user-images.githubusercontent.com/13420573/84741816-ec7d6580-afaf-11ea-936c-999ea7d55e0f.png)

But I see no color changes with these five themes that I've tested:
```
zenburn
phoenix-dark-mono
twilight
solarized-dark
solarized-gruvbox-dark
```

You mentioned that there are better examples. But since it isn't happening with every theme. Then maybe the issue is theme specific.

<details><summary>
PopOS 20.04 (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5fcd84d84)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
‘‘‘elisp
(auto-completion command-log emacs-lisp fasd git helm lsp markdown multiple-cursors
                 (org :variables org-agenda-files
                      ’("~/org/notes.org"))
                 ranger
                 (shell :variables shell-default-height 30 shell-default-position ’bottom)
                 spell-checking syntax-checking themes-megapack treemacs version-control)
‘‘‘
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS
</pre>
</details>

**Comment by lebensterben** [comment]
Reopen in case anyone want to fix it.
