### ISSUE TITLE
Add confirmation options for kill-emacs commands

### ISSUE THREAD

**Issue by basus** [syl20bnr/spacemacs#13600]
It seems to be pretty easy to accidentally hit `SPC q q` and close Spacemacs, especially since `SPC w w` is used for navigation between windows. Emacs has a `confirm-kill-emacs` variable that can be set to prevent accidental closures. It would be good to have something similar for Spacemacs.

**Comment by jr0cket** [comment]
If an additional confirmation is added, please make it optional or document how it can be over-ridden so the additional conformation can be switched off easily.

Thank you.

**Comment by emacs18** [comment]
There are three key bindings starting with `SPC q` to kill emacs:
- `SPC q s`
- `SPC q q`
- `SPC q Q`

This seems to be overkill to me. I don't see the need for the second one since it can cause great harm for some folks who can accidentally kill emacs without any confirmation. One way to resolve this is to just remove the key binding by adding this line somewhere in your startup file late in the startup process:

```elisp
(spacemacs/set-leader-keys "qq" 'ignore)
```

This just removes `SPC q q` key binding.  In addition you can add this
```elisp
(custom-set-variables '(confirm-kill-emacs 'y-or-n-p))
```
so that `SPC q s` will ask for confirmation before killing emacs.
