### ISSUE TITLE
Merge the changes for the pdf-tools doc page from develop to master

### ISSUE THREAD

**Issue by treymerkley** [syl20bnr/spacemacs#13627]
It wasn't until I was about to open a pull request that I realized that this is already fixed and waiting on upstreaming. Can this be merged over on the off chance someone else is confused?

**Comment by duianto** [comment]
I suspect that individual documentation pages won't be merged to master before the next version is released (I don't have any insight into when that is). Since all of them probably will be included.

By:
>pdf-tools doc page 

do you mean the pdf layer documentation?
Master: https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Btools/pdf-tools
Develop: https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Breaders/pdf

I did a quick comparison and there doesn't seem to have been any major changes:
- the features section was slightly rewritten
- the configuration snippet uses the new layer name `pdf`
- keybindings were split into two words
- main difference seems to be that two key bindings were added two months ago:
[pdf] Add pdf-mode keybindings to scroll through history https://github.com/syl20bnr/spacemacs/commit/1f6e39ea8ab3e7b7cb0a89889dec307523dfc6b4
```
[	History back
]	History forward
```

**Comment by treymerkley** [comment]
It was the new name thing that threw me. For a while I didn't know there was a PDF layer that worked, and that pdf-tools was just deprecated. It's not a big deal, just thought I'd ask.
