### ISSUE TITLE
Most of ranger bindings are overriden by evil

### ISSUE THREAD

**Issue by olivierverdier** [syl20bnr/spacemacs#13626]
#### Description :octocat:
Most of ranger bindings are overriden by evil

#### Reproduction guide :beetle:
- Start Emacs
- Launch ranger with `SPC j d`
- Hit, for instance `RET`

*Observed behaviour:* :eyes: :broken_heart:
The cursor goes down one row...

*Expected behaviour:* :heart: :smile:
It should be bound to `ranger-find-file` instead

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0d9cea8e2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ranger
 (auto-completion :variables auto-completion-return-key-behavior nil)
 bibtex c-c++ cmake colors coq cscope csv dash deft emacs-lisp emoji evil-snipe fasd
 (git :variables git-magit-status-fullscreen t)
 graphviz gtags haskell html javascript markdown org
 (python :variables python-test-runner 'pytest)
 search-engine semantic shell-scripts spacemacs-layouts spell-checking syntax-checking systemd templates themes-megapack treemacs
 (latex :variables latex-enable-auto-fill nil latex-build-command "LaTeX" latex-enable-folding nil)
 (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
 (theming :variables theming-headings-inherit-from-default 'all theming-headings-same-size 'all theming-headings-bold 'all)
 version-control windows-scripts yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by olivierverdier** [comment]
I found the problem. It occurs after commit 25e96354027f05151fa23a0667649abded84765e which loads `helm-fasd`. It is this package that causes the problem. So, I guess the layers `fasd` and `ranger` should be considered incompatible with each other.
I have now removed the layer `fasd` and `ranger` now seems to work as it should.

**Comment by duianto** [comment]
Confirmed.

When the layers: `helm`, `fasd` and `ranger` are enabled, then `RET` is bound to:
>RET (translated from <return>) runs the command evil-ret (found in
evil-motion-state-map), which is an interactive compiled Lisp function in

Without the `fasd` layer:
>RET (translated from <return>) runs the command ranger-find-file (found in
ranger-mode-map), which is an interactive compiled Lisp function in ‘ranger.el’.

<details><summary>
System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 23976ab79)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm lsp markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 (python :variables python-lsp-server 'mspyls)
                 ranger
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

**Comment by a13ph** [comment]
Seems more logical to change binding for Enter in `fasd` rather than marking those two layers as incompatible. 
Unless there are more important conflicts in keybindings between those, @olivierverdier ?

**Comment by olivierverdier** [comment]
Oh yes, it’s the same with most of the `ranger` bindings (`l`, `h`, `zz`, etc.), they are all shadowed by `evil`, somehow.

**Comment by duianto** [comment]
It seems to be caused by the package: https://github.com/ajsalminen/helm-fasd

It's not limited to Spacemacs, because it also happens with just:
Emacs and the packages: `evil`, `helm` and `ranger`

The `helm-fasd` package was cloned, then loaded from `init.el` with:
```elisp
(add-to-list 'load-path "~/.emacs.d/helm-fasd/")
```

### A possible cause
It seems to be caused by the line:
https://github.com/ajsalminen/helm-fasd/blob/7053c6f351f8e0f4014e7dd6e222445593d6f50f/helm-fasd.el#L98
```elisp
(add-hook 'dired-mode-hook 'helm-find-fasd-add-file)
```

### A possible workaround
It might break the `helm-fasd` package, but for anyone that isn't using it.

Removing that command from the `dired-mode-hook` seems to work:
Add the following to the `dotspacemacs/user-config` section in `.spacemacs`:
```elisp
(remove-hook 'dired-mode-hook 'helm-find-fasd-add-file)
```

<details><summary>
System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.91
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 23976ab79)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp fasd git helm lsp markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 ranger
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by jsilve24** [comment]
I ran into this problem as well.
