### ISSUE TITLE
Add gotham-theme to default themes

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1363]
I must say, this theme is best for writing Lisp code. It actually knows how to use `rainbow-delimiters`. If you don't believe me, install and try it on any Lisp buffer.

**Comment by syl20bnr** [comment]
I recently removed all the themes from the spacemacs layer since they are now not garbage collected by spacemacs. I mean the themes defined in `dotspacemacs-themes` are lazy-installed and not garbage collected. So we have no need to add them to the spacemacs layer anymore, except those requiring some configurations like `leuven`.

**Comment by syl20bnr** [comment]
You are right about gotham theme. I use it from time to time depending on my mood and I love it.

**Comment by kendall** [comment]
Recently material theme started making spacemacs fail on startup with some
odd message about Aqua not being a color or something. I disabled it but it
would be nice if this couldn't happen.

Cheers,
Kendall

**Comment by sooheon** [comment]
On the subject of default themes, why does `solarized` still seem to get special treatment in spacemacs? It's the only theme with its own directory in `/extensions`.

**Comment by syl20bnr** [comment]
@sooheon sorry for the late reply. Solarized is the official theme for spacemacs and I like to be able to tweak it to my liking for the distribution. It might change if we get an official `spacemacs-theme`, @nashamri is trying to create one.

**Comment by nashamri** [comment]
Hopefully this won't take long :smile:
