### ISSUE TITLE
I cannot use helm after updating to b071baf25

### ISSUE THREAD

**Issue by v2okimochi** [syl20bnr/spacemacs#13654]
#### Description :octocat:
I cannot use helm after updating to b071baf25

#### Reproduction guide :beetle:
- Start Emacs
- `SPC f f` or `SPC b b`

on b071baf25 (https://github.com/syl20bnr/spacemacs/pull/13645)

*Observed behaviour:* :eyes: :broken_heart:
Not working and following error:

```
let: Symbol’s value as variable is void: helm-buffer-list-reorder-fn
```

*Expected behaviour:* :heart: :smile:
I can see files or buffers using helm.

#### System Info :computer:
- OS: Ubuntu18.04LTS on WSL2 on Windows10
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b071baf25)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emoji org git github version-control
       (helm :variables spacemacs-helm-rg-max-column-number 1024)
       syntax-checking
       (spell-checking :variables enable-flyspell-auto-completion nil)
       (shell :variables shell-default-height 30 shell-default-position 'current-buffer shell-apply-ansi-color t)
       vimscript emacs-lisp
       (lsp :variables lsp-file-watch-threshold 3500)
       php
       (python :variables python-backend 'lsp python-formatter 'yapf python-format-on-save t python-sort-imports-on-save t python-test-runner 'pytest)
       hy
       (scala :variables scala-backend 'scala-metals)
       (clojure :variables clojure-enable-clj-refactor t clojure-enable-linters
                '(clj-kondo joker)
                cider-repl-display-help-banner nil cider-repl-display-in-current-window t cider-repl-use-clojure-font-lock t cider-repl-use-pretty-printing t cider-repl-result-prefix ";;=> " cider-save-file-on-load t cider-font-lock-dynamically
                '(macro core function var)
                cider-overlays-use-font-lock t cider-prompt-for-symbol nil company-backends-cider-mode-raw
                '((company-capf :with company-dabbrev-code))
                company-backends-cider-repl-mode-raw
                '((company-capf :with company-dabbrev-code))
                :packages
                (not cider-eval-sexp-fu helm-gtags parinfer))
       (html :variables web-mode-attr-indent-offset nil web-mode-markup-indent-offset 2 web-mode-css-indent-offset 2 web-mode-code-indent-offset 2 web-mode-style-padding 2 web-mode-script-padding 2 indent-tabs-mode nil tab-width 2 css-indent-offset 2)
       (typescript :variables node-add-modules-path t typescript-backend 'tide typescript-linter 'eslint typescript-fmt-tool 'prettier typescript-fmt-on-save t typescript-indent-level 2)
       (javascript :variables node-add-modules-path t javascript-backend 'tern javascript-fmt-tool 'prettier javascript-fmt-on-save t js2-basic-offset 2 js-indent-level 2)
       (vue :variables node-add-modules-path t)
       prettier csv markdown
       (yaml :variables yaml-enable-lsp t)
       (json :variables json-fmt-tool 'prettier json-fmt-on-save t)
       (sql :variables sql-capitalize-keywords t sql-capitalize-keywords-blacklist
            '("name" "user"))
       (docker :variables docker-dockerfile-backend 'lsp)
       (terraform :variables terraform-auto-format-on-save t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
let: Symbol’s value as variable is void: helm-buffer-list-reorder-fn
```

**Comment by emacs18** [comment]
https://github.com/emacs-helm/helm/commit/68b02788214a6dc9c177ef5858dea0667b1aabac
introduced the symbol in question 8 days ago.  Perhaps you should update helm package to pick up this new code.

**Comment by v2okimochi** [comment]
I tried update packages (SPC f e U) and it worked  on the latest develop branch.
Thanks for your advice, and this is not bug. I would like to close issue.

**Comment by nertpinx** [comment]
Sorry for hijacking this issue, but shouldn't updating the packages (at least those affected by spacemacs update) be part of the initial setup/install? Even if it means listing minimal supported versions for packages somewhere. Or is there a consensus against this?

**Comment by emacs18** [comment]
If the following sequence of events occurred, then I don't see how spacemacs can prevent the problem:
- helm package is installed by spacemacs
- helm is updated to add new function
- a dependent package starts using the new function
- this dependent package is installed by spacemacs perhaps due to addition of new layers

How is spacemacs to know to update helm at this point?
Remember that MELPA uses universal time of the latest checked in version as the package version string.  For example my own package archive has helm-20200612.1437.entry.  (I have my own MELPA-like package archive.)  The version of helm is the date/time string.  However helm-ag-20200601.933.entry (note helm-ag, not helm) file says that helm-ag depends on helm version 2.0!
Is 20200612.1437 greater than 2.0?  Has the dependency been met?

One side effect of the way MELPA assigns time stamp (the universal time of the latest checked in file) as the package version means that package dependency information may not be exactly correct.  First the authors of dependent packages may not have updated dependency information in their own files.  Second even if dependency information is correct, that may not matter given how MELPA assigns version numbers.

Should spacemacs simply reinstall all dependent packages when installing any package even if it is not sure that such update is needed?  I think that will lead to many unnecessary updating of packages.

**Comment by nertpinx** [comment]
@emacs18 Sorry, you're right. I haven't thought of the more complex interactions. Updating or reinstalling everything all the time is definitely not something I want spacemacs to do. I'm also not in a position to suggest how to help other users to notice that they might try upgrading the packages as I now know to also update that. If that existed, however, I think it might help in the future so that the user-base happy and staying with spacemacs :wink: Thanks for the insights.

**Comment by taquangtrung** [comment]
Somehow, I couldn't use `(SPC f e U)` to update packages since there were some errors that occurred during this update.

My workaround is to delete all `helm-*` packages in elpa and run Emacs again to install their latest versions.

```
cd ~/.emacs.d/elpa/26.3/develop
rm -rf helm-*
```

Then run Emacs again.

**Comment by ezmiller** [comment]
I also saw this problem and was able to fix it by using @taquangtrung 's solution: https://github.com/syl20bnr/spacemacs/issues/13654#issuecomment-650981724
