### ISSUE TITLE
 persp-mode.elc failed to provide feature 'persp-mode'

### ISSUE THREAD

**Issue by rifoerster** [syl20bnr/spacemacs#13666]
#### Description :octocat:

persp-mode.elc failed to provide feature 'persp-mode'

#### Reproduction guide :beetle:

- Start Emacs

- Update packages

- Restart

*Observed behaviour:* :eyes: :broken_heart:

Error message pops up after restart (and on every start)

Error (use-package): persp-mode/:catch: Loading file c:/Users/.../AppData/Roaming/.emacs.d/elpa/persp-mode-20200222.1106/persp-mode.elc failed to provide feature ‘persp-mode’

"C-c C-c is undefined" when trying to post this bug

*Expected behaviour:* :heart: :smile:

no error

(%LAST_KEYS%)

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by emacs18** [comment]
This is likely a corrupt persp-mode.elc file on your system.
```elisp
(provide 'persp-mode)
```
is found at the end of persp-mode.el, i.e., this feature is provided.

This file has not been modified since Feb 22, i.e., many folks have used this over the past four months without reporting similar problem.  It is highly unlikely that there is anything wrong with this file.  I myself have been using this file for the past four months without any problems.

Please consider switching to using develop branch rather than master branch.  The master branch has not been updated for over two years, i.e., all development is on the develop branch.

**Comment by rifoerster** [comment]
Using the develop branch seams to have fixed it. Figures the package update on master just stepped into some version incompatibility issue.
