### ISSUE TITLE
Opening an org-mode file in a dumped instance crashes Emacs

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#13680]
I am observing a strangest bug that I have no idea how to circumvent. I have enabled pdumper. Created a dump. Starting emacs with a `--dump-file` option works. It starts Emacs almost instantly and I like it. However, whenever I try to open my main tasks.org file, it crashes Emacs. Every other .org file seems to be working fine, but this particular one, there's something wrong with it, and I can't figure out what.

Strangely, if I open any other .org file, or simple enable org-mode in any buffer, and only after that would try opening tasks.org - it works fine and doesn't crash Emacs.

I'm gonna try different things until I get to the bottom of this, but this also might be related to some other issue(s). 

Emacs version I have:
GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.5.0, NS appkit-1894.50 Version 10.15.5 (Build 19F101)) of 2020-06-16

**Comment by cmatzenbach** [comment]
You are using Spacemacs, correct?  Just checking because you only mentioned emacs.  Have you tried creating a new .org file, manually copying the content of the one you want to dump, and see if Spacemacs reports any syntax errors?  Although this might not be necessary if you were able to open that file through Spacemacs and it loads in org-mode.

Here's a very similar issue that was fixed - https://github.com/syl20bnr/spacemacs/issues/11923.  Did you follow the pdumper docs for Spacemacs _exactly_?  https://github.com/syl20bnr/spacemacs/blob/develop/EXPERIMENTAL.org
