### ISSUE TITLE
Bug in load-spacemacs-env behavior?

### ISSUE THREAD

**Issue by dparis** [syl20bnr/spacemacs#13689]
https://github.com/syl20bnr/spacemacs/blob/develop/core/core-env.el#L131

```elisp
(defun spacemacs/load-spacemacs-env (&optional force)
  "Load the environment variables from the `.spacemacs.env' file.
If FORCE is non-nil then force the loading of environment variables from env.
file."
  (interactive "P")
  (setq spacemacs--spacemacs-env-loaded t)
  (when (or force (display-graphic-p))
    (spacemacs//init-spacemacs-env force)
    (load-env-vars spacemacs-env-vars-file)))
```

Should this call to `load-env-vars` be outside the `when`? The way it's written now, `load-spacemacs-env` will only load the .env file the first time, or when `force` is true. This seems counter to the described intent of the function.

**Comment by emacs18** [comment]
Pardon me for hijacking this to ask a general question. This has been puzzling me for years.

Why would you want to save and restore shell environment variables? I cannot think of any reason why this would be useful.  I know that this is a disaster based on my experience, i.e., this adds no value and just causes problems.  At least that is the case for me.

I use emacs in a network with many different linux machines.  I could be using Red Hat 6 one day, then use Red Hat 7 the next day, or use yet other OS'es such as SUSE 12.  The shell environment that may have been valid for one OS is disaster for another OS!  My home directory and all my emacs related files are shared among hundreds of machines via networked file system.

So why would you want shell variables to be saved and restored?  Isn't your shell environment setup correctly by your start files such as `~/.bashrc`?  Is it something on Macbook (which I know nothing about) or some other OS where restoring shell environment is useful?  I re-read what documentation I can find within spacemacs on this topic.  However I could not find any explanation as to why this "feature" exists.

Assuming that this is useful for some users, I think the saved environment file names should include at least the hostname so that an environment saved on one machine is not loaded when emacs is launched on another machine.

**Comment by dparis** [comment]
You guessed it! I stumbled on this (potential) bug in trying to sort out some mac-specific issues. The homebrew packaging system bundles a systemd-like startup script for the emacs server daemon. This is a convenient way to launch the emacs server on login so that emacsclient can be used to speed app startup time. The problem is that launchd, the mac init system, doesn't source environment variables from the user shell, even when the daemon being launched is launched as a user-specific daemon.

My goal was to get spacemacs to sync the env on startup manually, circumventing the problem. I saw that the `spacemacs/load-spacemacs-env` function could be forced to re-init, and wanted to understand exactly how it worked. Investing the implementation lead me post this issue as a potential bug.

As to why you would want to cache ENV vars rather than load them each time, I can't really say. I tend to agree that it would cause more confusion than it's worth; you save a very small amount of time on load and gain reproducibility, at the expense of having to manually curate all of the env vars passed into emacs. The latter seems very error-prone and likely confusing.
