### ISSUE TITLE
Completion-at-point with helm in a python inferior REPL process causes flooding in REPL with autocompletion text

### ISSUE THREAD

**Issue by atreyasha** [syl20bnr/spacemacs#13688]
#### Description :octocat:
When executing `completion-at-point` using `helm` in a python inferior REPL, the shell (eg. ipython) gets flooded with autocompletion text when the user types or removes text from the `helm` window.

#### Reproduction guide :beetle:
- Start Emacs
- Open a python file
- Start a python inferior REPL process
- Import module(s)/object(s) which have potential autocompletions
- Execute autocompletion (for eg. using TAB) of a module/object in the python inferior REPL process
- In the `helm` `completion-at-point` popup window, remove some text and then type some extra text
- Observe the inferior REPL process for any flooding

*Observed behaviour:* :eyes: :broken_heart:
- The python inferior REPL gets flooded with autocompletion text/possibilities

*Expected behaviour:* :heart: :smile:
- The python inferior REPL should not get flooded with autocompletion text. It should look exactly the same.
- I tested out the inferior REPL with the ESS layer and this same behaviour is not observed there. So this might be something specific to the python layer.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 78b45b416)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(bibtex imenu-list ruby html yaml pdf python
        (ess :variables ess-use-flymake nil ess-indent-with-fancy-comments nil)
        helm emacs-lisp
        (markdown :variables markdown-live-preview-engine 'vmd)
        org
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
        (latex :variables latex-enable-auto-fill nil latex-enable-magic nil)
        themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

If it helps, I can also produce/upload a gif of the observed behaviour. Otherwise, below is a screenshot of what the autocompletion text flooding looks like:

![2020-06-19-180111_1920x1180_scrot](https://user-images.githubusercontent.com/35427332/85154172-684d0b80-b257-11ea-9c45-0a9a06139c5a.png)

**Comment by cmatzenbach** [comment]
This doesn't happen in SLIME (Common Lisp repl) either, so it does look specific to this layer.  Unfortunately I don;t know python, I can take a look at the layer files but it would seem to be some setting/bug from the auto-completion, maybe helm.  I think the quickest test you could run if to switch to ivy and see if it still happens - that should give us more info on where the bug is.

**Comment by alexey0308** [comment]
As I understand, ipython completion is treated differently in python.el emacs file. I observe the issue only if one types quickly in the helm window, i.e. add a new symbol while the suggestion-list is being updated. It seems to be an issue with the python-mode.
Does it help, if one removes "ipython" in python-shell-completion-native-disabled-interpreters by customize-variable, or if one uses python instead of ipython (SPC-u C-c C-p python)?

Alternatively, one may use helm-company instead of completion-at-point (bound to C-/ when company-mode is activated in the inferior-buffer and after company suggestion window has appeared).

**Comment by atreyasha** [comment]
Hi @cmatzenbach @alexey0308, thank you both for the quick responses. Regarding your suggestions:

1. @cmatzenbach, I tried switching to ivy and this problem goes away. So this must have something to do with an interaction between `python.el` and `helm`.

2. @alexey0308, removing `ipython` from `python-shell-completion-native-disabled-interpreters` and working directly in a `python` shell resulted in this issue going away. I am not entirely sure why this helps, any perspectives?

I disabled `company-mode` because it conflicts with some other private layers. But yes, `helm-company` could definitely be a workaround for users who use `company-mode` actively.

**Comment by alexey0308** [comment]
> I am not entirely sure why this helps, any perspectives?

I do not know, how all this functions, but the following [change](https://github.com/ipython/ipython/pull/9399) might be related to the reason, why ipython was added to the list. Although there was provided --simple-prompt flag for compatibility. But it is just a guess, and I can not say anything about downstream due to lack of knowledge.
Hope it helps.

**Comment by atreyasha** [comment]
@alexey0308 no worries at all, thank you for sharing this information, it is very much appreciated :heart: 

Just to conclude, I added the following under my `dotspacemacs/user-config` to resolve the issue (in case it is of help to other users who use `ipython` as their python inferior REPL):

```emacs
(eval-after-load 'python
  '(setq python-shell-completion-native-disabled-interpreters
         (delete "ipython" python-shell-completion-native-disabled-interpreters)))
```

With that, will close this issue.
