### ISSUE TITLE
How to deactivate highlighting of trailing whitespace by default?

### ISSUE THREAD

**Issue by bshanks** [syl20bnr/spacemacs#13729]
#### Description :octocat:
I cannot deactivate highlighting of trailing whitespace by default.

#### Reproduction guide :beetle:
- Put the following in the dotspacemacs/user-config section of init.el:
  (setq spacemacs-show-trailing-whitespace nil)
  (setq-default spacemacs-show-trailing-whitespace nil)
  (setq show-trailing-whitespace nil)
  (setq-default show-trailing-whitespace nil)
- Open a Python file in a buffer
- Close Emacs
- Start Emacs
- Go to the autoopened buffer with the previously opened Python file

*Observed behaviour:* :eyes: :broken_heart:
- Trailing whitespace is highlighted

*Expected behaviour:* :heart: :smile:
- Trailing whitespace should not be highlighted

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asciidoc html markdown helm emacs-lisp markdown org python)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
It seems to be working for me on both the `master` and `develop` branches, in both Linux and Windows.

- I added:
```elisp
(setq spacemacs-show-trailing-whitespace nil)
```
to the `dotspacemacs/user-config` section in `.spacemacs`.

- Opened this file:
```python
# python_example.py
# Example python file
# https://www.pythonforbeginners.com/code-snippets-source-code/game-rolling-the-dice/
import random
min = 1
max = 6

roll_again = "yes" 

while roll_again == "yes" or roll_again == "y":
    print "Rolling the dices..."
	print "The values are...."
    print random.randint(min, max)
	print random.randint(min, max)

    roll_again = raw_input("Roll the dices again?")


def poll2()
loop = asyncio.get_event_loop()
```

- Added a space after the line:
```python
roll_again = "yes" 
```
- Restarted Spacemacs by pressing: `SPC q r`
The Spacemacs home buffer is shown on startup, then:
  - on the `master` branch the `python_example.py` file opens and stays visible
  - on the `develop` branch the python file opens for a split second,
then the Spacemacs home buffer is shown again.
Pressing `r` moves the cursor to the first file in the `Recent Files` list: `python_example.py`
Pressing `RET` opens it.

The trailing space isn't highlighted.

![emacs_2020-06-29_08-29-54](https://user-images.githubusercontent.com/13420573/85980470-c2319c00-b9e2-11ea-9818-9567ecd9d866.png)

- Enabling whitespace mode: `SPC t w`
shows a trailing space (red highlight) after the line: `roll_again = "yes"`

![emacs_2020-06-29_08-30-40](https://user-images.githubusercontent.com/13420573/85980505-d4133f00-b9e2-11ea-9ef9-dd8083005a0e.png)

(when the cursor is moved away from that line, otherwise the cursor line highlighting hides the red highlight)


<details><summary>
PopOS 20.04, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c66342039)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm multiple-cursors org python
                 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
                 version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

<details><summary>
Windows 1903, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git helm html javascript
            (latex :variables latex-build-command "LatexMk" latex-enable-magic t)
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            python ruby
            (shell :variables shell-default-shell 'eshell shell-default-height 30)
            spell-checking
            (syntax-checking :variables syntax-checking-enable-by-default nil)
            themes-megapack treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by real-or-random** [comment]
No matter if `spacemacs-show-trailing-whitespace` is currently working or not, this I think the variable should be added to the `.spacemacs` template file with a proper description.

**Comment by duianto** [comment]
A PR has been opened to add a dotspacemacs variable:
[dotfile] new var: dotspacemacs-show-trailing-whitespace #14305

Feel free to suggest any improvements.

I couldn't think of anything more descriptive than:
```
   ;; Show trailing whitespace (default t)
   dotspacemacs-show-trailing-whitespace t
```

**Comment by duianto** [comment]
The PR has been merged into the develop branch.
[dotfile] new var: dotspacemacs-show-trailing-whitespace #14305

@bshanks if you haven't switched to the `develop` branch yet, then that's the recommended branch until the next version is released (I have no insight into when that is).

#### To try the `develop` branch:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

If you've switched, and/or if your able to confirm that the new variable works then, you can close this issue.
