### ISSUE TITLE
Terrible ESC key behaviour with company popup

### ISSUE THREAD

**Issue by trishume** [syl20bnr/spacemacs#1372]
Currently in `develop` since cdd1eddd3d9b88ed4c4be59b54e2906b723f8b97 pressing escape while a popup is open will abort the company popup but not exit insert mode. This is terrible user-unfriendly behaviour that kills the ability to use muscle memory. See more discussion in the comments on the commit.

The way that #1097 should be fixed is that pressing escape both exits company *and* exits to normal mode.

**Comment by syl20bnr** [comment]
I agree that a sane default for auto-completion is to use TAB.

`auto-complete` has a better UX in my opinion and I would like to replicate it in company but I'm not sure it is possible :-( I explain. In `auto-complete` pressing TAB while there are several candidates for the same prefix will auto-complete the prefix. Is this possible to do it in company ? I believe I saw an issue upstream where the maintainer said it is not the company philosophy (warning, I'm not sure at all about this) which would be really sad.
I never had issue with `auto-complete` which as natural way to do auto-complete, with company I struggle.
We even have inconsistent behavior with `esc` :-(

**Comment by sooheon** [comment]
I think autocompletion is a very personal thing, and there may be less benefits to having one person's customisations being the spacemacs default. That said, what you want @syl20bnr, can be done by setting:
```
      (define-key company-active-map [tab] 'company-complete-common)
```
Also I'll take a look at how it is in the auto-completion layer, but for me pressing `esc` with the company popup kills the popup *and* takes me to normal mode.

**Comment by syl20bnr** [comment]
@sooheon :heart: 
Yes this is what I want as default for spacemacs, looks natural to me because it follow the incremental nature of auto-completion.

**Comment by syl20bnr** [comment]
Ok what `auto-complete` does which is very good is that once TAB as complete the common prefix it will cycle between the candidates, THAT is good UX.
Can we do this with `company` ?

Ultimately if we can achieve consistency between `auto-complete` and `company` it would be perfect.

**Comment by syl20bnr** [comment]
It is pushed in `develop`. I also updated `evil-escape` to remove the support for company.

**Comment by syl20bnr** [comment]
Ok you'll find me weird but I put `RET` back to match `auto-complete` behavior.
So here it is:
- `tab` expand the prefix and cycle between candidates
- `S-tab` same thing but cycle backward
- `RET` actually does the auto-completion
I find this UX very good because it is symmetric and does not involve the hands to quit the home row.

soooo we still have the issue with `RET` but the behavior is the same in both completion engine.

I think the real issue with `RET` is to find why some users have https://github.com/syl20bnr/spacemacs/issues/1097 (including me).

**Comment by syl20bnr** [comment]
@mijoharas I removed the variable to use `tab` to complete instead of `RET` I will put it back, sorry for this.

**Comment by syl20bnr** [comment]
Spamming this issue :-)

An alternate proposal would be:
- `tab` perform completion
- `S-tab` complete up to common prefix and cycle
- `S-M-tab` complete up to common prefix and cycle backward

**Comment by syl20bnr** [comment]
Trying it now :-)

**Comment by syl20bnr** [comment]
Ok forget this, it is awful !

**Comment by sooheon** [comment]
What I have is `tab` perform complete common, and that's it. `RET` does nothing, because it can fuck with newlines. I also enable `company-show-numbers`, so if I ever want to put something in right away, it's `M-number`. I think this is the sanest because it doesn't mess with RETurn when I don't want it to.

**Comment by mijoharas** [comment]
@syl20bnr I also prefer not to have `RET` complete due to newline issues (like the stuff with `do` in ruby that @trishume got around with a bit of brilliant [hackery](https://github.com/syl20bnr/spacemacs/blob/master/contrib/auto-completion/config.el#L26-L30) :smile: ). Can I suggest `Shift-Ret` as default? or maybe just have an option to remove the `Ret` completion behaviour?

**Comment by mijoharas** [comment]
just to clarify, my suggestion is `tab` is complete common, `Shift-Ret` (or `C-Ret`?) would be complete and then just use `C-j` and `C-k` to scroll up and down like normal.

**Comment by mijoharas** [comment]
I also think we should swap `C-/` and `C-M-/` as I think filter is more useful than just search with the company dropdown, so should be the default option (was just thinking that the other day)

**Comment by trishume** [comment]
Definitely there should be an option to disable RET for full completion. Maybe it would use `Shift-TAB` for complete fully.

Also note that `TAB` has collision issues too (yasnippet, indentation, org) so using both RET and TAB is the worst of both worlds in that regard.

**Comment by syl20bnr** [comment]
Indeed TAB + RET is the worth :-)
It is easier to suppress the issue with TAB though:
- We can remove the collision with yasnippet by changing the key binding for it.
- it is less common to use tab for indent inside a sentence since space is generally used and we have auto-indentation when pressing RET

I like the single key to complete common prefix+cycle, feels natural. I propose the remove RET by replacing it with `C-l` or something on the home row. I can also experiment with something like `jl` pressed quickly.

**Comment by tuhdo** [comment]
We can already use `M-/` to expand snippets already.

**Comment by mijoharas** [comment]
I agree with you on the `complete-common`, now that I use it, I think it is a good feature. I also agree that we need a better way to complete than `RET`. 

My vote is for `C-RET` just because that feels somewhat natural to me. I don't have a strong opinion though. I think `Shift-Tab` might be confusing as people may try and do that to scroll back up the list, but it could be a solution. `C-l` could be ok, do we use it for anything else often?

I would probably not be too keen on `jl` as (since I'm on dvorak) I wouldn't find that too natural.

**Comment by syl20bnr** [comment]
I find it slow to move the finger from TAB to CTRL or even SHIFT.
The sequence `jl` can be customizable. This way it is really quick to `TAB TAB TAB jl` since it involves both hands without any combination.

**Comment by CestDiego** [comment]
@tuhdo  I dindn't know `M-/` was used to expand snippets! :O :( does this go into the doc? Anyway I think that `TAB` is more natural for expanding snippets ans whatnot. What is really awful though is when snippets get auto-completed and you get the name of the snippet expanded and not the snippet itself. 

@syl20bnr Please consider that in linux `S-TAB` ( that is `Shift+TAB` ) is interpreted as `<backtab>` in some linux, and also `Ctrl+shift+tab` is `<C-iso-lefttab>` and also `M-S-TAB` is `<M-iso-lefttab>` this is very weird..but...it's emacs! :D

**Comment by CestDiego** [comment]
@syl20bnr  just to for the sake of discussion. Also, what's wrong with having `C-j` and `C-k` to navigate the current candidates of completion I used to have to select with this guys. and then to `TAB` to expand the completion.

**Comment by mijoharas** [comment]
hmmm... still not sure on `jl`, my vote would still be for `C-Ret` or `C-l` (having the key-chord in addition to both of those would still be good for me). Obviously it's something I could easily rebind in my setup so not a big deal either way.

@CestDiego what you're suggesting is exactly what I had, but after playing around with `complete-common` and thinking about it a bit today, I quite like binding that to tab. (I assume we'd still keep the `C-j` and `C-k` binding regardless of what's decided on, right @syl20bnr ). Obviously it's a matter of preference, but I think it works quite nicely.

**Comment by CestDiego** [comment]
@mijoharas  ye I really didn't try the complete-common, but now I see it's value. if we have the tab/shift+tab and C-j/C-k combo that would be so awesome. But also have in mind @syl20bnr that in linux <C-RET> is <C-return>

**Comment by mijoharas** [comment]
Now that I think about it, `C-l` does make sense to fit in with the `C-j` and `C-k`.

**Comment by syl20bnr** [comment]
The pinky navigating between TAB and CTRL is not efficient :-(

**Comment by CestDiego** [comment]
not if you have caps lock switched :P. @syl20bnr it should be an alternative, for people using `C-j` and `C-k` `C-l` is SO much better.

For people using the tab thing. RET doesn't seem as bad.

**Comment by mijoharas** [comment]
it is if your CTRL is where your caps is :smile:

**Comment by syl20bnr** [comment]
To be clear I won't remove `C-j` `C-k`. I am thinking about how to complete efficiently after TAB TAB TAB.

**Comment by CestDiego** [comment]
@syl20bnr I just had this happen. Try this:

1. Go into elisp buffer
2. def<TAB> to expand snippet
3. You are now in a defun snippet expanded. try typing a function, let's say `space`
4. Wait for it.....Completion shows
5. Let's say you want to go to next candidate, or just complete the first one or use complete-common, w/e. you press <tab>
6. PAM you are transported to the next part of the snippet.

**Comment by mijoharas** [comment]
@syl20bnr yep, of course, and you have got a good point. I think we should include both `C-l` and some kind of keychord (whatever you thinks best) like `jl`. that way you have two complementary sets of operations, one for people who like tabs and key-chords and another for people who like C-vim-keys.

**Comment by tuhdo** [comment]
Why couldn't we just get rid of tab for expanding snippet? I opened this issue before: https://github.com/syl20bnr/spacemacs/issues/999 and fix it with this PR: https://github.com/syl20bnr/spacemacs/pull/1000, so one day we remove `TAB` for expanding snippet. `M-/` executes `hippie-expand`, a very popular command in Emacs world to quickly cycle completion candidates from its sources (and after the PR, `yasnippet` is one). And `hippie-expand` is built-in command and is a superset of `dabbrev-expand`.

If we remove `company-yasnippet`, the completion candidates shown become real candidates instead of mixing with snippets. To a new user, how does he distinguish between which is a snippet and which is a completion candidate? He may accidentally press a snippet, be annoyed and have to undo.

After all we are finding another key binding, and we already have one built-in.

**Comment by CestDiego** [comment]
I think that too. The only thing is that C-vim-keys won't be able to support complete-common, unles.. .we do complete-common with `C-l` IF there is a common preffix (if there is a common preffix and you wanted to expand you'd at least need the common preffix right?) ad if there is not a common preffix well then just complete the candidate. :P that way we don't need `<RET>` I don't know if I'm explaining it well. 

Is there a way for a key to complete preffix at first if there is, and if there is not just expand the candidate?

**Comment by CestDiego** [comment]
@tuhdo we could apply a different face for snippets maybe?  as you see in 
![snippet](https://camo.githubusercontent.com/07a758ae0f1663a9f05ab3eac70f683a60d63c57/68747470733a2f2f692e696d6775722e636f6d2f38446f30365a412e706e67) the snippets are displayed like this

snippet-short-name -> snippet-name

And functions like this

function_name <f>

and other things don't have anything.

I don't know what behaviour does hippie expand bring. I would like to try it if it only shows yasnippets, right now the menu it brings comes up with common words, and such :(

**Comment by mijoharas** [comment]
yeah, I use company for discovery of snippets as well. I don't find them until I see them so I discover them and then become faster.

**Comment by tuhdo** [comment]
@CestDiego It should not bring up any menu. It only cycles available candidates but never show a menu. If you want to expand a snippet, i.e. `defun` type `def` and press `M-/`.

As for yasnippet, if you want to see all available snippets without expanding one, you can use [helm-c-yasnippet](https://github.com/emacs-helm/helm-c-yasnippet) with the command `helm-yas-complete`. It shows you all available snippets in current major mode. You may use it infrequently just to discover new snippets. After that, using `M-/` is simply quicker.

**Comment by CestDiego** [comment]
When I try to insert an snippet with `SPC i s` I get the full name of the snippet, so I'd have to (if I don't remember well the name of the snippet) do `SPC i s` memorize how it's expanded, then `C-g` write the full snippet name and then `M-/` ? :( maybe if we improbe on the `SPC i s` function to actually insert the snippet and not the snippet text it would be cool, obviating the fact that to call this function we must be in normal state :(

**Comment by cpaulik** [comment]
If the behaviour described by @CestDiego [here](https://github.com/syl20bnr/spacemacs/issues/1372#issuecomment-96712482) is possible then I would be strongly in favor since it would require at most two TAB to do the completion.

I do not like the current solution because of having to press RET if there are more than one completion possibility.

**Comment by tuhdo** [comment]
@syl20bnr no you don't. You only need to `SPC i s` (I've just known it) to select a snippet, press `RET` to expand that snippet. No need to press `C-g`.. The next time, just use `M-/`. I think most people when expanding a snippet, they know it in advance and just use a key binding to quickly expand it i.e. I never wait for `company` to show its popup but as soon as I type `def`, I press `M-/` immediately.

**Comment by syl20bnr** [comment]
OK so here is current state of the design I gathered from the discussion:
- obviously no `RET` for competion
- `TAB` to complete (replace `RET`)
- `C-j` and `C-k` to browse the candidates
- `C-l` can be added to complete to go nicely with `C-j` `C-k`
- We remove snippet from company backends and use dedicated key bindings for it, `M-/` is the default and map well for holy-mode. We can add one more with `CTRL` as an atlernative for `insert state`, `C-l` is once again a possibility since it will be available in `instert state`.

Do I forget anything ?

**Comment by mijoharas** [comment]
@syl20bnr I think that's a good summary of a lot of the points that have been mentioned, my own opinion would change two points on that.

I would keep `TAB` as complete-common, after having used it like that for a day, it seems to make sense to me. I think I might be outvoted on this one so I don't mind either way.

I like that company displays yasnippet things, I use it for discovery of snippets as otherwise I never find them. It's pretty possible that that's just because I have a suboptimal workflow.

otherwise :+1:

**Comment by syl20bnr** [comment]
@ all What are the downsides of incorporating the snippets in company candidates ? They are clearly indentified with an `->` aren't they ?

@mijoharas the downside for `complete-common` is that it _may_ required two TABs to complete, but is it really the case in practive ?

**Comment by CestDiego** [comment]
@syl20bnr the fact the snippets are followed by -> should be in the documentation. I'd like to experiment with @tuhdo 's setup. maybe a PR?

**Comment by syl20bnr** [comment]
I prefer to be in charged for this one but we have to validate the design first.

So one downside is that it is not obvious that it is a snippet ? We can add it to the readme then. No a big downside in my opinion.

**Comment by syl20bnr** [comment]
OTHO there is `SPC i s` @mijoharas

**Comment by syl20bnr** [comment]
I see one argument against snippet in company which is "it feels out of place in some languages like elisp". Take `funcall` snippet which just inserts parentheses, in a company workflow the open parenthesis is already inserted.

**Comment by tuhdo** [comment]
@syl20bnr the disadvantages is: `yasnippet` cannot distinguish between contexts. For example, when I already type `(def` (cursor is right after `def`), I just want `company` to give completion candidates. But pressing `tab` expands the whole snippet and I have to undo again. It's annoying when your function/variable names contain part of a snippet i.e. if the identifier names contain words like `or`, `and`, `for`,`set`...

**Comment by CestDiego** [comment]
but `SPC s i` doens't always have snippets.

**Comment by tuhdo** [comment]
And not in some languages like `elisp`, but other languages as well i.e. you have `for` in your function name and then you cannot use `company` to *quickly* complete anything after `for` anymore, even if the name with `for` is unique and you can press `TAB` right away.

**Comment by syl20bnr** [comment]
@tuhdo we posted at the same time :-)
I agree with this. Separation of concern then ?

**Comment by tuhdo** [comment]
@CestDiego it should be `SPC i s`.

**Comment by CestDiego** [comment]
I get what @tuhdo is saying, I think we should try it.

**Comment by syl20bnr** [comment]
@CestDiego indeed in depends on the point location, which may be a bug somewhere between yasnippets and helm.

**Comment by CestDiego** [comment]
check out https://asciinema.org/a/19268. This shows that some functions that are not snippets go there.

**Comment by syl20bnr** [comment]
Ok so the last little bit to debate is `complete` vs. `complete-common`.
I presonnally feel `complete-common` to be a superior solution minus the fact that is _may_ be required to hit TAB twice is some circumstances (should not be so frequent).

**Comment by tuhdo** [comment]
@syl20bnr I thnk it's a feature. It does not show snippet when point is in a word that is not a snippet prefix. Only when the symbol at point is a snippet prefix, it shows proper ones of that prefix.

**Comment by CestDiego** [comment]
@syl20bnr complete common will be ok because when you hit `TAB` and you want to insert the common preffix, it already inserted it. so you just move on :O

**Comment by mijoharas** [comment]
sounds good to me about both the snippets being removed from company (didn't really use them that much and with `SPC i s` hopefully I shouldn't miss them.) and I also agree with insert common.

**Comment by CestDiego** [comment]
you can see the use-package case for common-preffix here @syl20bnr 
[![alt](https://asciinema.org/a/19269.png)](https://asciinema.org/a/19269)

**Comment by tuhdo** [comment]
@CestDiego in your previous video about the snippets, I see that `SPC i s` showed `add-hook` snippet and expand properly, while both `company-complete` and `hippie-expand` cannot see and expand it. So, I think `SPC i s` is a better command for snippets here.

**Comment by CestDiego** [comment]
@tuhdo check this [![alt](https://asciinema.org/a/19270.png)](https://asciinema.org/a/19270)

 In that video the snippet was expanded, but it took more keybindings (going to normal state and use SPC i s) BUT the snippet did not have the snippet part.. (the possibility to go from one field to another)

**Comment by CestDiego** [comment]
I'm excited about this, when we get this going smoothly I might be giving my time to creating my own snippets for my projects :3  just like @magnars in [Emacs Rocks!](http://emacsrocks.com/e06.html)

**Comment by tuhdo** [comment]
@CestDiego the same bug in the video happened also with `company-complete`. You can check it with `defalias`. This really depends on snippet and I think it's a yasnippet bug.

**Comment by tuhdo** [comment]
`SPC i s` is supposed to use for exploring snippets and it only shows snippets. After you remember some, you can expand with `M-/` quickly. Also, since I use `holy-mode` I don't have to switch editing modes. `C-c i s` is quite quick to press for me.

**Comment by CestDiego** [comment]
oh ye... it has to do with yasnippet I guess, but it's weird that company didn't complete define-key. D:

**Comment by tuhdo** [comment]
We can conclude that even for exploring purpose, `company` cannot does it well because it can miss snippets and it can even mess up completion, so better separate yasnippet from it. `SPC i s` is for actual exploring and `M-/` for quick snippet expand once you familiar with some.

**Comment by CestDiego** [comment]
defalias doesn't work with `M-/` so ye It's a yasnippet bug. I do think though that we should have to go into normal mode to do `SPC i s` OTOH there is `C-o` to go into normal mode for next keybinding... so I guess I'm cool with that if that shows into the doc.

What is the difference from C-p and hippie expand?

**Comment by tuhdo** [comment]
`defalias` and `M-/` or `TAB` (current behavior) works for me. Anything `company` can expand, `M-/` can expand. However, `SPC i s` trumps both.

`hippie-expand` is for cycling completion candidates, not for pasting. You can press `M-/` multiple times to cycle caniddates. I use it to quickly complete some text with prefix, especially useful in writing commit message.

**Comment by CestDiego** [comment]
how can one go backwards into completino candidates with `M-/`? `C-p` did the same for me, completed stuff and cycled but never could return to last candidate

**Comment by tuhdo** [comment]
The difference is that it does not cycle your kill ring like `C-p` but get completion candidates from `hippie-expand-try-functions-list` Here is [the list of functions](https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L1674).

**Comment by tuhdo** [comment]
For example, you can type a partial lisp function name not in the kill ring. `C-p` won't complete it for you, but `M-/`will.

**Comment by tuhdo** [comment]
You can also use [hippie expand to complete words in a dictionary](http://blog.binchen.org/posts/autocomplete-with-a-dictionary-with-hippie-expand.html)

**Comment by CestDiego** [comment]
In insert mode C-p does not paste anything. it searches for stuff in the current buffer and completes. But I agree that hippie expand seems more complete... I vouch for that. :) :+1:

**Comment by tuhdo** [comment]
It pastes things from kill ring. See its description: `Replace the just-yanked stretch of killed text with a different stretch.`. Even the help in the microstate mentions so.

**Comment by CestDiego** [comment]
I have
```
C-p runs the command evil-complete-previous, which is an interactive compiled
Lisp function in `evil-commands.el'.

It is bound to C-p.

(evil-complete-previous &optional ARG)

Complete to the nearest preceding word.
Search forward if a match isn't found.
Calls `evil-complete-previous-func'.

[back]
```

**Comment by tuhdo** [comment]
Is that in insert mode? The `C-p` I mentioned is in normal mode and it is `evil-paste-pop`.

I've looked at `evil-complete-previous`. You can customize `evil-complete-previous-func` which is default to collect from all buffers only. Probably it's time to replace `evil-complete-previous` with `hippie-expand` for `C-p` :)

**Comment by tuhdo** [comment]
Doing so, you can use `C-p` to expand snippets, which I think would be comfortable with most Vim users?

**Comment by CestDiego** [comment]
I think that could be cool `M-/` is just too far away for me in the keyboard. :) let's try that

**Comment by PierreR** [comment]
As a note `M-/` is awful when using an azerty keyboard ;-)

**Comment by PierreR** [comment]
In case it helps this was my `company` configuration before using spacemacs : 
```
;; Company
(defun company-complete-common-or-cycle ()
  (interactive)
  (when (company-manual-begin)
    (if (eq last-command 'company-complete-common-or-cycle)
        (let ((company-selection-wrap-around t))
          (call-interactively 'company-select-next))
      (call-interactively 'company-complete-common))))

(define-key company-active-map [tab] 'company-complete-common-or-cycle)
(define-key company-active-map (kbd "TAB") 'company-complete-common-or-cycle)
```
I have got it while reading an issue about 'AC vs company' on the company github repo. It might worth a try.

**Comment by syl20bnr** [comment]
I pushed in develop the following design:

- no `RET` to complete
- `TAB` complete common prefix and cycle
- `C-j` `C-k` to select alternative candidates
- `C-l` complete the selection
- `jk` pressed quickly complete the selection
- `C-p` is hippie-expand
- Removed `company-yanippet`

### Why `TAB` with `complete-common-or-cycle` ?
Using just `complete-common` only, TAB does nothing when the common prefix is completed, which feels weird, it feels natural to want to cycle between the remaining candidates.

### Why `jk` ?
Because we have to replace `RET`. `RET` is convenient because it does not break the typing flow, no modifier is involved and the fingers stay on the homerow, but we know that `RET` gets in the way. `jk` tries to reproduce the convenience of `RET` without any compromises.

### How `jk` is implemented ?
I tested a lof of different implementations and I sticked with this one: whenever `j` is pressed when company is active we keep the current time in a variable. When `k` is pressed we checked the time elapsed since the last `j` if its not nil. With some magic, we then make company complete the selection.
This implementation should have no negative impact on the UX. It may need some tweaking in some terminals though.

### TODO:
- find additional bindings for `complete-selection`
- make `jk` customizable via a dotspacemacs variable.

I really like the feeling of `TAB` and `jk` combined but it is opinionated. Maybe we can provide 2 way to auto complete, this one and another one where `TAB

**Comment by CestDiego** [comment]
Great! :) gonna test it now. I don't feel right about the `jk` thing I think it should reuse sth like key-chord or sth but I don't know how is that implemented anyway. BTW I guess there are people that have already replaced `fd` for `jk` in evil escape so maybe a warning should be made as welll (although I remember there being an issue with evil escape with `hjkl` keys. Anyway will report back :)

**Comment by syl20bnr** [comment]
`key-chord` has some very nasty edge cases with `evil`, I was able to reliably _crash_ emacs with it enabled. There is also some issue with the prefix arguments.

**Comment by CestDiego** [comment]
Oh I didn't know that...lol if this works then it's ok then :)

**Comment by sooheon** [comment]
@syl20bnr regarding your reasoning for `C-j` and `C-k` keybindings, are you aware that `M-n` and `M-p` does the same by default? When working in lisps, many people often use `C-j` in both normal and insert mode for splitting up lines, similarly to `enter`. `C-k` I'm sure you know is another essential smartparens/paredit/lispy convention for killing the rest of the sexp. Binding those to have different behaviour only during completion would give us the same problems as with having `return` complete.

**Comment by CestDiego** [comment]
I didn't understand the problems with RET. What are them exactly? I didn't
know about m-c and M-p just tested them and at first glance they look kinda
good.

That being said I wouldn't be mad if the completions used M-n and M-p for
navigating... I have one issue with the company pop-up though,, sometimes
when there is not enough space at the bottom the popup will appear on top
of the text, but the functions that go to the 'next' candidate go up
instead of down, and the same inverted behavior with 'prev' candidate :(
it's not very intuitive visually even though it makes sense programatically.

**Comment by sooheon** [comment]
@CestDiego RET in insert mode should give you a new line. Your muscle memory expects it. If you're typing without looking at the cursor, and press RET for a newline but company popup appeared, it would give you a completion when you don't want it. It forces you to pay attention to the state of company popup, and do things like esc and then RET.

**Comment by CestDiego** [comment]
Oh ye that happened to me .... well I guess you are right with the C-j and
C-k then...I use them a lot in web-mode.... @syl20bnr maybe we should
reconsider this.

**Comment by sooheon** [comment]
Continuing on the `M-n` vs `C-j`, I see why you would like to hold down `C`, move with `j` or `k`, and complete with `l`. It's a common `vi` idiom. However, I think you'd get nearly the same experience changing that to `M-l` for complete (or any other `M` binding) and using `M-n/p` for nav. Adding `company-show-numbers` only makes this more consistent, as numbered selections are completed with `M-num`.

**Comment by cpaulik** [comment]
I  have to say that I do not like `C-l` for completion because it is very inefficient as @syl20bnr already said to go from tab to ctrl with your left pinky. 

Why not use `shift-tab` to cycle and keep tab on complete. One can easily press the `right-shift` while keeping the left pinky on the `tab` button.

These bindings worked for me on linux for both GUI and Termnal emacs:

```elisp
      ;; key bindings
      (define-key evil-insert-state-map "k" 'spacemacs//company-complete-end)
      (let ((map company-active-map))
        ;; use TAB to auto-complete instead of RET
        (define-key map (kbd "j") 'spacemacs//company-complete-start)
        (define-key map [return] 'nil)
        (define-key map (kbd "RET") 'nil)
        (define-key map [tab] 'company-complete)
        (define-key map (kbd "TAB") 'company-complete-selection)
        (define-key map (kbd "<tab>") 'company-complete-selection)
        (define-key map (kbd "C-/") 'company-search-candidates)
        (define-key map (kbd "C-M-/") 'company-filter-candidates)
        (define-key map (kbd "C-d") 'company-show-doc-buffer)
        (define-key map (kbd "C-j") 'company-select-next)
        (define-key map (kbd "C-k") 'company-select-previous)
        (define-key map (kbd "C-l") 'company-complete-selection)
        (define-key map (kbd "<backtab>") 'company-complete-common-or-cycle)
        (define-key map (kbd "S-C-i") 'company-complete-common-or-cycle))
```

As a side note `C-l` does the exact opposite in helm - going back so we might want  to look at that for consistency if `C-l` is kept to complete.

**Comment by sooheon** [comment]
@cpaulik `C-l` in helm is a whole other problem, I agree it should go forward and to the right (like in ido), not up a directory. I have to say that tab and shift-tab not being pure reversible actions of each other is unintuitive.

**Comment by cpaulik** [comment]
Also in the last develop I can no longer expand snippets with tab. Is it on purpose that this is only possible with `M-/` now?

**Comment by sooheon** [comment]
If you read above syl20bnr has said that he took out yasnippet.

**Comment by cpaulik** [comment]
Ah sorry I missed that.

**Comment by mijoharas** [comment]
Hmmm... I'm in favour of the `C-j` and `C-k` bindings as they are the same as in helm...

**Comment by PierreR** [comment]
Just a little question. Does `space` complete the selection with an extra space ? Most of the time this is what I want (or mean) while completing the selection.

**Comment by PierreR** [comment]
I'm also in favour of the C-j and C-k bindings for the reasons pointed by @mijoharas 

I actually hope there will be option to keep `RET` completing the selection for the same reason. That's what helm is doing. Personally I have yet to run in the issue described for `RET` so I don't see the problem. While selecting a completion it is quite clear I am in a different context so I never expect it to create a newline at that point. If I am not mistaken that's what most IDEs out there are doing ...

**Comment by tuhdo** [comment]
> I actually hope there will be an option to keep RET completing the selection for the same reason. That's what helm is doing. Personally I have yet to run in the issue described for RET so I don't see the problem. While selecting a completion it is quite clear I am in a different context so I never expect it to create a newline at that point. If I am not mistaken that's what most IDEs out there are doing ...

I agree with you. I see no problem with `RET` and I think it's quite convenient and popular not only in Emacs but other IDEs out there.

**Comment by cpaulik** [comment]
We should have default behaviour that is what most people expect. Which is to complete either with `tab` or with `RET`

**Comment by syl20bnr** [comment]
The discussion goes in circle. :-)

I'll keep the current design with RET added for complete-selection.

Then I will add back the variable to use only TAB as complete-selection.

We have still to fix the issue where sometimes company is not disabled when
going back to normal state.

Le jeudi 30 avril 2015, Christoph Paulik <notifications@github.com> a
écrit :

> We should have default behaviour that is what most people expect. Which is
> to complete either with tab or with RET
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/1372#issuecomment-97763093>.
>


-- 
-syl20bnr-

**Comment by mijoharas** [comment]
complete-selection or complete-common? as isn't that the current situation? either way, sensible defaults, with maybe a section in the documentation for auto-completion layer to show people how to customize this to suit themselves as it seems most people want different things here :smile:

**Comment by syl20bnr** [comment]
Same as it is in develop right now but with RET added for
complete-selection.

Plus a variable to use only TAB instead but with complete-selection instead
of complete-common-cycle. As said above complete-common alone does nothing
when the prefix is completed so it cannot be used in a TAB only setup.

Le jeudi 30 avril 2015, Michael Hauser-Raspe <notifications@github.com> a
écrit :

> complete-selection or complete-common? as isn't that the current
> situation? either way, sensible defaults, with maybe a section in the
> documentation for auto-completion layer to show people how to customize
> this to suit themselves as it seems most people want different things here [image:
> :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/1372#issuecomment-97815910>.
>


-- 
-syl20bnr-

**Comment by trishume** [comment]
I like this new design complete-common-or-cycle is awesome! I also like the idea of the `jk` chord.

There should definitely be a variable for use of `RET` because people that primarily use languages with semicolons mostly won't have problems with it but people who frequently use things like Ruby and Haskell will constantly have trouble with it.

This makes it sound like it should be language specific but that would kill muscle memory. So better to have a global preference (and maybe a toggle) and then keep around some strategies (like my old hack with keywords) that make it so that `RET` users can at least sometimes use ret-unfriendly languages like Ruby.

Also as a dvorak user, +1 for having a variable for the `jk` binding.

**Comment by syl20bnr** [comment]
I pushed the new design for auto-completion UX. I think it captures well all the stuff we said in this discussion.

You can check the documentation here:
https://github.com/syl20bnr/spacemacs/tree/develop/contrib/auto-completion#key-bindings

**Comment by syl20bnr** [comment]
I consider this issue fixed.

**Comment by 1ambda** [comment]
How I can redefine `ac-next` and `ac-previous` in my `.spacemacs`?

I used this code but failed :(

```
(defun dotspacemacs/user-config ()
  "..."

  ;; evil
  ;;; http://ergoemacs.org/emacs/keyboard_shortcuts_examples.html
  (define-key evil-insert-state-map (kbd "C-p") nil)
  (define-key evil-insert-state-map (kbd "C-n") nil)

  ...

  ;; auto-complete (should be followed by evil key maps)
  (define-key map (kbd "C-n") 'company-select-next)
  (define-key map (kbd "C-p") 'company-select-previous)

)
```
