### ISSUE TITLE
Set gpg homedir for spacelpa archive verification

### ISSUE THREAD

**Issue by klao** [syl20bnr/spacemacs#13738]
Adding spacemacs' public key to check spacelpa archives to the user's default gpg keyring is probably the wrong thing to do. Instead it should use the elpa keyring under `~/.emacs.d/elpa/gnupg`.

**Comment by smile13241324** [comment]
I think this change is affecting spacelpa's architecture, therefore I would like to get @syl20bnr opinion before this is merged.

One small comment from me, I have seen that you are hard coding the path to elpa, I think it is possible to have your elpa archive in a custom location. I am not entirely sure about this, will need to scan the repo to know exactly, but this is something we should double check before this is merged.

**Comment by klao** [comment]
Yeah, I agree, I felt bad hardcoding the location, but with a quick search I wasn't able to figure out what's the right way to do this. I'll take a look at `package.el` and maybe I figure it out.

**Comment by klao** [comment]
OK, I figured out how it's done in `package`. Now the path doesn't have to be hardcoded and the resulting code is actually a bit nicer. :)  Updated the PR.

**Comment by smile13241324** [comment]
The new code is good, I also think it makes more sense to rely on the elpa key ring than on the standard one. Lets merge it and see if someone complains.

**Comment by ViktorHaag** [comment]
> The new code is good, I also think it makes more sense to rely on the elpa key ring than on the standard one. Lets merge it and see if someone complains.

Hey @smile13241324 -- I'm complaining. 8)

In my setup, I have my Spacemacs configuration directory hosted on Dropbox, and then symlinked into the home directory of each computer I have, so that I have one Spacemacs config for everywhere. Unfortunately, it looks like gpg-agent likes to make special files (sockets?) in the GnuPG directory and this causes Dropbox to hiccup because those files are not syncable.

I'll see about further hacking my config to move the GnuPG directory away from `/elpa/gnupg`, but is it reasonable to, for example, have a config switch that toggles to use the user's own home `~/.gnupg` instead if they want? Or to move this package directory into the Spacemacs .cache directory? (For my setup, I've configured the cache directory to be outside the Spacemacs home directory so it's local to each separate machine I work on.)

Just a thought... 8/
