### ISSUE TITLE
M-x org-schedule command is not working

### ISSUE THREAD

**Issue by quaziashfaq** [syl20bnr/spacemacs#13754]
#### Description :octocat:
M-x org-schedule is not working

#### Reproduction guide :beetle:
- Start Emacs
- open a file with org extension
- Go to a item or task
- Press C-c C-s or M-x org-schedule to schedule a task
- The calendar pops up but gone.
- In the minibuffer, a error message shows that 'Key sequence i j starts with non-prefix key i'

*Observed behaviour:* :eyes: :broken_heart:
I can't set schedule. 

*Expected behaviour:* :heart: :smile:
I should be able to see a calendar pops up. I choose a date and thus I schedule a TODO item.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: test (rev. d1a6d62e2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git helm lsp markdown multiple-cursors org syntax-checking treemacs
                 (org :variables org-enable-org-journal-support t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by emacs18** [comment]
As far as I can tell, the only function that would print 'Key sequence i j starts with non-prefix key i' message is `define-key` which is a emacs built-in function written in C.

So your emacs encountered what seems like an invalid elisp code.  This could be in one of the packages you installed, e.g., you could have ended up with versions of packages that had interoperability problems.  This also could be in your own personal customization code.  Thus examining your own config may be a good place to start.  Also just removing all installed packages and restarting emacs (so that they would be installed with latest versions) might be something you could try.

**Comment by smile13241324** [comment]
@quaziashfaq please update your emacs packages, this was a bug in org, I am on latest develop and updated my packages some minutes ago and the issue is not present on my side.

**Comment by smile13241324** [comment]
#13735 for details

**Comment by quaziashfaq** [comment]
Thank you all. Yes. After I updated my emacs packages, I didn't face this issue again.
