### ISSUE TITLE
Error loading .spacemacs

### ISSUE THREAD

**Issue by watsodw** [syl20bnr/spacemacs#13822]
I just installed Spacemacs and when I start Emacs, I get this:

Error loading .spacemacs: (void-variable I)

I did a traceback: 

Debugger entered--Lisp error: (void-variable I)
  eval-buffer(#<buffer  *load*-183009> nil "/Users/dwwatson/.spacemacs" nil t)  ; Reading at buffer position 3373
  load-with-code-conversion("/Users/dwwatson/.spacemacs" "/Users/dwwatson/.spacemacs" nil nil)
  load("/Users/dwwatson/.spacemacs")
  (condition-case err (load dotspacemacs) ((debug error) (message "Error loading .spacemacs: %S" err) nil))
  (if (condition-case err (load dotspacemacs) ((debug error) (message "Error loading .spacemacs: %S" err) nil)) nil (dotspacemacs/safe-load))
  (if (file-exists-p dotspacemacs) (if (condition-case err (load dotspacemacs) ((debug error) (message "Error loading .spacemacs: %S" err) nil)) nil (dotspacemacs/safe-load)))
  (let ((dotspacemacs (dotspacemacs/location))) (if (file-exists-p dotspacemacs) (if (condition-case err (load dotspacemacs) ((debug error) (message "Error loading .spacemacs: %S" err) nil)) nil (dotspacemacs/safe-load))))
  dotspacemacs/load-file()
  spacemacs/init()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (error (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat (file-name-directory load-file-name) "core/core-load-paths.el")) (require (quote core-spacemacs)) (spacemacs/init) (configuration-layer/sync) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/Users/dwwatson/.emacs.d/init.el" nil t)  ; Reading at buffer position 1264
  load-with-code-conversion("/Users/dwwatson/.emacs.d/init.el" "/Users/dwwatson/.emacs.d/init.el" t t)
  load("/Users/dwwatson/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x400cfbe1>)()
  command-line()
  normal-top-level()

Anyone have an idea what causes the error?

Thanks.

**Comment by jr0cket** [comment]
Using `SPC h I` uses a template that provides key information about your Spacemacs setup which can help others understand the problem.  Unfortunately this issue was raised without this, limiting the help that can be provided.

Suggest comparing your `.spacemacs` file with the spacemacs.template, `SPC f e D` will start ediff with both files to help with the comparison.  Remove any additional code from your .spacemacs file unless you know for certain that it works.

Alternatively, remove the .spacemacs file and restart Emacs.  This will create a clean spacemacs file to which you can add customization and test they work.
