### ISSUE TITLE
Abnormal Status bar for Emacs build --with-xpm=no

### ISSUE THREAD

**Issue by sunlin7** [syl20bnr/spacemacs#13834]
Hi,
Abnormal status bar present for Emacs build --with-xpm=no, Spacemacs last develop branch (ba982822c6b4b9e784d5c1fa35afa3e5126b4593).
![image](https://user-images.githubusercontent.com/4402280/89975275-f235b580-dc97-11ea-81bc-c86b7e552b72.png)

**Comment by duianto** [comment]
Confirmed.

Emacs 27.1 built with: `--with-xpm=no`

The following returns: `nil`
```elisp
(image-type-available-p 'xpm)
```

The mode line is blank:

![VirtualBoxVM_2020-08-17_07-49-00](https://user-images.githubusercontent.com/13420573/90363001-20354400-e062-11ea-9f88-98adb8d2e3dd.png)

### Cause

https://github.com/TheBB/spaceline seems to require Emacs built with image support.

Because the messages buffer shows:
>Error during redisplay: (eval (spaceline-ml-main)) signaled (error "Invalid image type ‘xpm’")

and the error message is reported here:
Modeline is blank https://github.com/TheBB/spaceline/issues/158

The issue is closed, but you could comment there that you also would like it to work without image support.

### Workaround

The `doom` mode line theme works:

![VirtualBoxVM_2020-08-17_07-47-24](https://user-images.githubusercontent.com/13420573/90363015-2a574280-e062-11ea-9192-159b82fb8d2c.png)

<details><summary>
PopOS 20.04, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 76301564c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
‘‘‘elisp
((elfeed :variables elfeed-feeds
         ’(("http://nullprogram.com/feed/" blog emacs)
           "http://www.50ply.com/atom.xml"
           ("http://nedroid.com/feed/" webcomic)))
 emacs-lisp git helm multiple-cursors version-control treemacs)
‘‘‘
- System configuration features: JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by sunlin7** [comment]
@duianto Thank you.
Close as upstream issue.
