### ISSUE TITLE
Powerline does not scale correctly after upgrading emacs to 27.1

### ISSUE THREAD

**Issue by yzh119** [syl20bnr/spacemacs#13843]
#### Description :octocat:
After I upgrade my emacs from 26.3 to 27.1, the height of powerline becomes twice the size it previously was:

![image](https://user-images.githubusercontent.com/11773619/90247142-966e5680-de68-11ea-802e-f4c670205bef.png)

and change the value of `powerline-scale` does not help.

#### Reproduction guide :beetle:
- Start Emacs
```
$ emacs &
```

*Observed behaviour:* :eyes: :broken_heart:
The height of powerline is larger than it previously was.

*Expected behaviour:* :heart: :smile:
The powerline should look "thinner".

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ca2cdd0fc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html coq lsp javascript helm auto-completion better-defaults ibuffer imenu-list
      (chinese :variables chinese-enable-youdao-dict t)
      semantic emacs-lisp
      (python :variables python-backend 'lsp python-lsp-server 'pyls)
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
      ocaml rust git themes-megapack latex racket markdown org spell-checking syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by jr0cket** [comment]
Suggest trying a different font family or theme.  There may also be something missing from the Emacs build.

I have not seen issues raised like this on the Spacemacs Gitter community https://gitter.im/syl20bnr/spacemacs

Unfortunately the `SPC h I` key binding in Spacemacs was not used to raise this issue, so there is no information available about the system you are using and therefore it will be much harder to diagnose.

**Comment by yzh119** [comment]
Hi @jr0cket , I updated the issue description following your template.
Yes I do think it's because of font, I'll try to figure out a workaround.

**Comment by duianto** [comment]
If someone else encounters the same issue, it would be helpful to know what you were using when the issue occurred:
- Linux distribution, maybe the default OS font has an effect, depending on the Spacemacs font choice
- Emacs Theme
- Is it a HiDPI display and is it using any OS level scaling

**Comment by andreyk0** [comment]
@duianto experienced the same issue on Arch / gnome / wayland / HiDpi screen @ 200%.
My config is [here](https://github.com/andreyk0/home_dot_files/blob/master/spacemacs).

I do have the fonts explicitly set in the config and  was running with `dotspacemacs-mode-line-theme '(vim-powerline)` before the update.

```lisp
dotspacemacs-default-font '("Source Code Pro Medium" :size 13.0 :weight normal :width normal)
```
If someone's looking for a way to re-create the issue -maybe this'll help.

After update tried to fiddle with a few more themes. Emacs default one didn't have this issue. Tried `doom` and it worked with [an extra hack](https://github.com/andreyk0/home_dot_files/commit/deca19303ae064e5300b5d1d6ebaa999dc00c070#diff-5887721483a97f89e9a6292016a76321) that I pasted from some search result. Ugly but works for now, sorry, I don't know elisp, can't fix this properly.

**Comment by yzh119** [comment]
@duianto, I'm using Arch / gnome / xorg / HiDpi screen @ 200%.
The theme used is tango-dark, and trying other themes doesn't help (like @andreyk0 ).
font configuration:
```
   dotspacemacs-default-font '("Source Code Pro"
                               :size 28
                               :weight normal
                               :width normal
                               :powerline-scale 1)
```

**Comment by duianto** [comment]
Maybe there's some useful info here: https://www.reddit.com/r/emacs/comments/51wm7d/emacs_on_hidpi_displays/

**Comment by philippera** [comment]
Hi, I have the same problem since the emacs 27.1 upgrade. I run Arch / i3-gaps / xserver / Xft.dpi: 192
Here is what it looks like: https://folio.ink/SevRmI
Here is my config file: https://github.com/philippera/arch-dotfiles/blob/master/homedir/.spacemacs

**Comment by philippera** [comment]
dotspacemacs-mode-line-theme '(spacemacs :separator wave :separator-scale 0.5)

:separator-scale at 0.5 solves the problem for me

**Comment by yzh119** [comment]
@philippera 's solution works for me as well :)

**Comment by yang-ling** [comment]
@duianto 

> Is it a HiDPI display and is it using any OS level scaling

→ I can confirm this issue only happens when you use HiDPI display and set scaling.
  I have installed spacemacs both on my home MacBookPro and my work PC.
  Spaceline looks well on my work PC, but it looks much more larger on my home MBP.

  I solved it by changing `dotspacemacs-mode-line-theme` setting.

  You can:
  - set `:separator-scale` to 0.5 if you have a HiDPI display.
  - Or set spaceline theme to `vanilla`, which is default Emacs mode-line. (I feel `separator-scale` doesn't take effect when `vanilla` is used.)

  Both of the following config work for me:
  - `dotspacemacs-mode-line-theme '(spacemacs :separator wave :separator-scale 0.5)`
  - Or `dotspacemacs-mode-line-theme '(vanilla :separator wave :separator-scale 1.5)`

@jr0cket Your comments are very helpful. Thanks!

**Comment by laynor** [comment]
I just fixed a very similar issue to this one in my config. The issue seems related to the unicode fonts - try opening `spaceline-segments.el` and check the function `spaceline--unicode-number`.
In my case the lines where the unicode chars appear had lots of interline spacing. It was due to emacs selecting Noto Sans to display the symbols, which appears to have a very different height w.r.t. my default font, at least when displaying those symbols.
You can verify what font is being used with `M-x describe-char`.
I solved my issue adding this to my config: 
```
  (set-fontset-font "fontset-default" 'symbol (font-spec :size 12 :name "Symbols Nerd Font Bold"))
```
in my `dotspacemacs/user-init` function.

**Comment by lebensterben** [comment]
For future references,
try setting `:separator-scale 0.5` in `dotspacemacs-mode-line-theme` on high DPI.
