### ISSUE TITLE
Can't use graphviz 

### ISSUE THREAD

**Issue by WingDust** [syl20bnr/spacemacs#13884]
Spacemacs version: 0.300
Emacs version : 27.1
OS: windows 10

I want to perview graphviz on windows 10 but 
`SPA m ,`: `Error dot :can't open h:/工作/framework/first.dot`
And
I want to compile it
`SPA m c` : 
```
-*- mode: compilation; default-directory: "h:/工作/framework/" -*-
Compilation started at Fri Aug 28 21:15:37

dot -Tpng "h:/工作/framework/first.dot" -o "h:/工作/framework/first.png"
Error: dot: can't open h:/工作/framework/first.dot

Compilation exited abnormally with code 2 at Fri Aug 28 21:15:37

```

**Comment by duianto** [comment]
Maybe `dot` doesn't understand the special characters in your path: `工作`

If the same thing happens without Spacemacs,
with just Emacs and the package:
https://github.com/ppareit/graphviz-dot-mode

Then it should be reported upstream.

Because `SPC m ,` and `SPC m c` works for me in Spacemacs.

I downloaded the latest stable version of graphviz: `graphviz-install-2.44.1-win64.exe`
from: https://www2.graphviz.org/Packages/stable/windows/10/cmake/Release/x64/

After installing it, I added the path: `C:\Program Files\Graphviz 2.44.1\bin`
to the Windows PATH environment variable.

Installed the Spacemacs `graphviz` layer.
And added the path to the `bin` directory to the `.spacemacs.env` files, `PATH=` line.

After restarting Spacemacs, it finds `dot.exe` when evaluating: `(executable-find "dot")`
`"c:/Program Files/Graphviz 2.44.1/bin/dot.exe"`

After saving the first example on this page: https://renenyffenegger.ch/notes/tools/Graphviz/examples/index
as `graphviz_example.dot`:
```dot
digraph D {

  A [shape=diamond]
  B [shape=box]
  C [shape=circle]

  A -> B [style=dashed, color=grey]
  A -> C [color="black:invis:black"]
  A -> D [penwidth=5, arrowhead=none]

}
```
Pressing: `SPC m ,`
Showed:
>Unknown image type; consider switching ‘image-use-external-converter’ on
revert-buffer-insert-file-contents--default-function: Cannot revert nonexistent file c:/Users/username/Temp/graphviz_example.png

When I tried compiling it from a command prompt:
>Format: "png" not recognized. Use one of:

When I searched for the error, I found this SO thread:
https://stackoverflow.com/questions/35688320/graphviz-seems-doesnt-support-png-and-map

Where they state that:
>Graphviz plugins need to be registered before they can be used. In Windows, open the command prompt as admin and type dot -c to register. You can verify it by typing dot -v

After running: `dot -c` from an admin prompt.
Then `dot -v` shows:
```
C:\WINDOWS\system32>dot -v
dot - graphviz version 2.44.1 (20200629.0846)
libdir = "C:\Program Files\Graphviz 2.44.1\bin"
Activated plugin library: gvplugin_dot_layout.dll
Using layout: dot:dot_layout
Activated plugin library: gvplugin_core.dll
Using render: dot:core
Using device: dot:dot:core
The plugin configuration file:
        C:\Program Files\Graphviz 2.44.1\bin\config6
                was successfully loaded.
    render      :  cairo dot dot_json fig gdiplus json json0 map mp pic ps svg tk vml xdot xdot_json
    layout      :  circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
    textlayout  :  textlayout
    device      :  bmp canon cmap cmapx cmapx_np dot dot_json emf emfplus eps fig gif gv imap imap_np ismap jpe jpeg jpg json json0 metafile mp pdf pic plain plain-ext png ps ps2 svg tif tiff tk vml xdot xdot1.2 xdot1.4 xdot_json
    loadimage   :  (lib) bmp eps gif jpe jpeg jpg png ps svg
```

And now `SPC m ,` opens a buffer that shows the resulting `.png` file.
And `SPC m c` shows:
>-*- mode: compilation; default-directory: "~/Temp/" -*-
Compilation started at Sun Sep 13 19:41:45
>
>dot -Tpng "c:/Users/username/Temp/graphviz_example.dot" -o "c:/Users/username/Temp/graphviz_example.png"
>
>Compilation finished at Sun Sep 13 19:41:45


<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7a7b04abb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey command-log emacs-lisp git go graphviz haskell helm
            (javascript :variables javascript-backend 'lsp)
            lsp multiple-cursors org
            (python :variables python-backend 'lsp python-lsp-server 'mspyls)
            shell version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by WingDust** [comment]
@duianto 
 You are right with `SPA m c` can't handle with path has non-English word ,
I just do the test All English word path and non-English path. 
and Thanks for You find the solution
