### ISSUE TITLE
The commit c8b3e46 failed for no init.el in dot emacs, neither following its document

### ISSUE THREAD

**Issue by sunlin7** [syl20bnr/spacemacs#13933]
Hi @smile, 
The commit c8b3e46 failed for no init.el in dot emacs, neither following its document.
I have no `~/.emacs.d/init.el`, so there is an error message when execute this function; and in its document, `spacemacs/find-user-init-file` will edit the `user-init-file`. 
Please revert the change, if openning Spacemacs init file with shortcut is require, we should create a new function for that.

**Comment by emacs18** [comment]
Following is the change in question.

```diff
 (defun spacemacs/find-user-init-file ()
   "Edit the `user-init-file', in the current window."
   (interactive)
-  (find-file-existing user-init-file))
+  (find-file-existing
+   (expand-file-name "init.el" user-emacs-directory)))
```

For me the value of `user-init-file` is `~/.emacs`, but the value of `(expand-file-name "init.el" user-emacs-directory)` is `~/.emacs.d/init.el`. The two are clearly not the same.

I see two problems with this change. First the doc-string for the function was not updated, so that the doc-string still says that `user-init-file` would be edited which clear is incorrect. Second the check-in comment for the change says the following:

> <SPC f e i> should work with Emacs profile switcher plexus/chemacs

I use `chemacs` package. As far as I know you must use `~/.emacs` file for this package. Thus the rationale for the change does not seem to match reality, i.e., if you want `spacemacs/find-user-init-file` to edit profile switching related file, then shouldn't it be editing `~/.emacs` rather than `~/.emacs.d/init.el`?

**Comment by smile13241324** [comment]
Hmmm, if this change has side effects I will revert the commit in question. @emacs18 if you are familiar with `chemacs` could you give it a try after the revert to see whether this is breaking `chemacs` functionality?

@sunlin7 thanks for reporting.

**Comment by smile13241324** [comment]
Reverted the commit in question, @sunlin7 please retry and close this issue when your issue is gone now.

**Comment by emacs18** [comment]
@smile13241324 chemacs seems to be working fine for me after picking up latest spacemacs version.

**Comment by sunlin7** [comment]
@smile13241324 It's work like a charm after apply your last change. Thank you.
