### ISSUE TITLE
Org mode column view columns misaligned

### ISSUE THREAD

**Issue by bobf32** [syl20bnr/spacemacs#14058]
#### Description :octocat:
Column widths are not uniform in org mode column view.

#### Reproduction guide :beetle:
- Start Emacs
- Open an org mode doc with several level of heading, say four or so
- Navigate to a high level heading which contains sub-headings
- Enter column view with C-c C-x C-c

*Observed behaviour:* :eyes: :broken_heart:
- On entering column view in the lines corresponding to the higher level headings the column widths are bigger that in the lines where the heading level is lower.
- See pic [here](https://i.imgur.com/Re6tvnq.png)

*Expected behaviour:* :heart: :smile:
- In column view all columns should be the same width.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c70f32283)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(vimscript javascript html asciidoc markdown helm emacs-lisp git markdown org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bobf32** [comment]
Doing a package rollback seems to fix the problem...

**Comment by duianto** [comment]
`C-c C-x C-c` calls `org-columns` which is defined in `org-colview.el`

There was a change to that file 6 days ago.
https://code.orgmode.org/bzg/org-mode/commit/90b14cb409adbd5529b8bbef32ad5239e5c85404
>org-colview: Fix done keywords highlighting in agenda buffers
>* lisp/org-colview.el (org-agenda-columns): Populate
org-done-keywords from org-done-keywords-for-agenda or the done keywords
will use the same face as those not-done.
>
>TINYCHANGE

This might be where the issue was discussed:
https://lists.gnu.org/archive/html/emacs-orgmode/2020-10/msg00104.html

The `org-colview.el` files commit history shows that the previous change occurred 5 months ago: 
https://code.orgmode.org/bzg/org-mode/commits/90b14cb409adbd5529b8bbef32ad5239e5c85404/lisp/org-colview.el

So the most recent change might be what caused the issue.

Org mode issues are reported by sending an email to: `emacs-orgmode@gnu.org`

**Comment by droy** [comment]
Is this resolved?

**Comment by bobf32** [comment]
@droy Doesn't seem to be. I don't use emacs under windows now but I resurrected it and a quick test shows the problem is still there.

**Comment by droy** [comment]
Thanks for checking. Should I infer that this is not a bug on Linux and only a bug in Windows and MacOS? Does your setup of org-mode cause headings at different levels in trees to have different font sizes? I would maybe expect any setup where font sizes don't change to not display this bug. Any idea where I might look to patch things?

**Comment by dankessler** [comment]
Including the below snippet inside of `dotspacemacs/user-config` "fixes" this behavior for me.

```
(set-face-attribute 'org-column nil
                    :height (face-attribute 'default :height)
                    :family (face-attribute 'default :family))
```

I figured this out by first reviewing [this SE thread](https://emacs.stackexchange.com/questions/12949/org-column-face-settings-not-coming-through-in-org-mode-column-view) which led me to [this OrgMode FAQ item](https://orgmode.org/worg/org-faq.html#column-view-tiny-font), and I extracted the above code from example provided there.

In essence, it sets the height (and family) attributes for the `org-column` face  *back* to the original defaults (which is probably what your column headers are using) so that they will override the underlying height specified by level 1 (or 2 or 3) org-mode headings as specified by spacemacs {light, dark} theme.

I think this can probably be abstracted into a PR that can be submitted upstream to [spacemacs-theme](https://github.com/nashamri/spacemacs-theme), and if adopted, could trickle down to spacemacs itself.

**Comment by droy** [comment]
Works, thanks.

**Comment by dankessler** [comment]
For me at least, the above fix is over-zealous as setting `:height` alone is sufficient to correct things for me. I've submitted a PR upstream to spacemacs-theme (cross-referenced above) which only includes the height fix.

**Comment by dankessler** [comment]
@droy (and others who might be following), the following is IMHO a more robust fix, e.g., will appropriately track if you scale text buffer-wise or frame-wise (see additional info in the [PR here](https://github.com/nashamri/spacemacs-theme/pull/183)).

```
(set-face-attribute 'org-column nil
                    :inherit 'default)

```

**Comment by droy** [comment]
Also works for me. Thanks, again.

**Comment by droy** [comment]
Following up. I noticed an error message in *Messages* at startup

    (Spacemacs) Error in dotspacemacs/user-config: Invalid face: org-column

Will look into debugging this myself, but wanted to pass this on.

**Comment by dankessler** [comment]
This has now been [fixed upstream](https://github.com/nashamri/spacemacs-theme/pull/183) but I think needs to be manually pulled into spacemacs. However, I'm unsure what the standard way of tracking upstream is (I can't tell from the commit history if it's a subtree merge, or clever cherry picking, etc).

**Comment by droy** [comment]
Ok, thanks.

**Comment by lebensterben** [comment]
@dankessler 
It seems that this package has not been updated since Feb 2021. At least we need them to publish anew release.

**Comment by lebensterben** [comment]
Updates: 

I saw that there is a new release on melpa. I had just asked other maintenaners about how to update this.

**Comment by duianto** [comment]
The upstream spacemacs-theme fix:
Update org-column face to use default height https://github.com/nashamri/spacemacs-theme/pull/183

has now been pulled into Spacemacs:
[bot] Built-in auto-update #14887
https://github.com/syl20bnr/spacemacs/pull/14887/files#diff-601dbb1a7b7dd54e2bfcefbda3cd46ae97fd0c0cad926f36e1da397213e4a6e0R749
