### ISSUE TITLE
Can't quit Emacs

### ISSUE THREAD

**Issue by ShapelessCat** [syl20bnr/spacemacs#14051]
#### Description :octocat:
Every time I use `:wq` to quit Emacs, I see "Wrote $HOME/.emacs.d/.cache/places", and it never end.

#### Reproduction guide :beetle:
- Start Emacs
- Open ANY file and edit it
- Try to type `:wq` to quit Emacs

*Observed behaviour:* :eyes: :broken_heart:
I see Emacs says "Wrote $HOME/.emacs.d/.cache/places".
It seems this operation never end, and I can't quit Emacs.

*Expected behaviour:* :heart: :smile:
When I type `:wq`, just quite Emacs normally.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. dad4406f7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm auto-completion better-defaults git multiple-cursors markdown org
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        version-control treemacs lsp emacs-lisp ess java windows-scripts
        (scala :variable scala-backend 'scala-metals)
        rust racket haskell)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
Spacemacs closes for me.
After adding a comment: `;; testing`
in `.spacemacs` and not saving it.
Then pressing `:wq` `RET`

`$HOME` seems like it's a Linux path?
Have you copied over your `.emacs.d` directory or some other files from a Linux setup?

It's probably best to clone a fresh copy on each OS and copy over your configurations when everything is up and running.

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ac3c3546a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(autohotkey emacs-lisp
            (erlang :variables erlang-enable-lsp-mode t)
            git ivy javascript lsp multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/")
                 org-enable-jira-support t org-enable-roam-support t)
            python rust shell spell-checking syntax-checking version-control treemacs yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by ShapelessCat** [comment]
@dubnde Not a Linux path. I git clone a fresh copy, and I still can't close any modified files normally.

**Comment by duianto** [comment]
According to:
https://en.wikipedia.org/wiki/Home_directory#Default_home_directory_per_operating_system

`$HOME` is listed as an Environment variable in `linux`, `mac`, `android`, etc.

Windows uses:
>%USERPROFILE%
%HOMEDRIVE%
%HOMEPATH%

---

I also cloned a fresh copy of the develop branch
`git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d`

From a command prompt visiting the directory:
`C:\Users\username\AppData\Roaming`
(where Emacs looks for a `.emacs.d` directory)


And for me `:wq` still closes Spacemacs without any errors, from a modified `.spacemacs` file.

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 76849892e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

---

Do you see any other error messages in the `SPC b m` messages buffer?

Could you try the latest stable Emacs version: 27.1

And make sure that there is no `.emacs.d` directory,
or files called: `.spacemacs` or `.spacemacs.env` in your home directory.

#### Note
(You @ mentioned someone else. It's understandable, since the GitHub autocompletion has a mind of it's own)

**Comment by ShapelessCat** [comment]
@duianto I'll try the Emacs 27.1. By the way, my emacs can't identify the .emacs.d in `C:\Users\username\AppData\Roaming`, and I have to put it in `C:\Users\username\`.

**Comment by duianto** [comment]
Maybe you've added a Windows `HOME` environment variable pointing to that directory?

That's the setup I had (a `HOME` environment variable with the value: `C:\Users\username\`) before my previous comment, but I removed the variable, to make sure that it wasn't the reason why it worked for me.

But the issue didn't occur after restarting the computer without the HOME variable either.

By default (at least with the official Emacs version https://www.gnu.org/software/emacs/)
Emacs creates and/or looks for a `.emacs.d` directory in the roaming directory.
https://www.gnu.org/software/emacs/manual/html_node/emacs/Windows-HOME.html

**Comment by ShapelessCat** [comment]
@duianto I just notice one thing that I did pay enough attention, which might be the reason:
Recently, I'm reading some Racket language documents, and I uses org-mode to take notes. These notes include org-mode code blocks, and the language is Racket. Every time I edit these files, after editing I can't quite Emacs normally. Since in these days I only did this in Emacs, I didn't take this into account as something special. However, today I opened some other notes (in org-mode) that doesn't include Racket code blocks, and I can quite my Emacs normally after editing.

I just removed the Racket layer support from the list following the `dotspaces-configuration-layers` in my `.spacemacs`, and the quit Emacs functionality recovers. I guess there must be some bug(s) in the Racket layer.

**Comment by duianto** [comment]
I created a `spacemacs-issue-14051.org` file, containing:
```org
#+begin_src racket
  (+ 1 1)  ; => 2
  (- 8 1)  ; => 7
  (* 10 2) ; => 20
  (expt 2 3) ; => 8
  (quotient 5 2) ; => 2
  (remainder 5 2) ; => 1
  (/ 35 5) ; => 7
  (/ 1 3) ; => 1/3
  (exact->inexact 1/3) ; => 0.3333333333333333
  (+ 1+2i  2-3i) ; => 3-1i
#+end_src
```

`:wq` still works for me, after each of the following tests:
(Spacemacs was restarted with the `racket` layer installed before the first test)
- Just opened the file
- Added a comment with the url to the source of the racket snippet, as the first org racket block line:
`;; https://learnxinyminutes.com/docs/racket/`
- Added a org heading before the org racket block
`* testing issue 14051`
- Added a new expression as the last org racket block line:
`(+ 1 (- 2 (* 3 (/ 4 5))))`

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(autohotkey emacs-lisp
            (erlang :variables erlang-enable-lsp-mode t)
            git ivy javascript lsp multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/")
                 org-enable-jira-support t org-enable-roam-support t)
            python racket rust shell spell-checking syntax-checking version-control treemacs
            (vue :variables vue-backend 'lsp)
            yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by ShapelessCat** [comment]
@duianto I'll try to reproduce it in my another computer. If I can't, I think this is not a general enough issue, and I'll close this issue first.
I'll update in the following days of this week.

**Comment by emacs18** [comment]
I think one weakness of `kill-emacs` is that users are allowed to modify it in at least two ways, but without proper error handling, so that user added custom code may prevent emacs from exiting on some type of errors. For example one can add hook functions to `kill-emacs-hook` variable. If one of these functions throws an error, then this may prevent `kill-emacs` from completing, i.e., emacs never quits. Another way to customize `kill-emacs` is via [function advising](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html#Advising-Functions). For example spacemacs modifies `kill-emacs` via this advice:
```elisp
    (defadvice kill-emacs (around spacemacs-really-exit activate)
      "Only kill emacs if a prefix is set"
      (if (and (not spacemacs-really-kill-emacs)
               (spacemacs//persistent-server-running-p))
          (spacemacs/frame-killer)
        ad-do-it))
```
I have run into situations where I could not quit emacs due to problems within either hook functions or advised functions. In such cases, I can force emacs to exit by removing all customizations related with `kill-emacs`, i.e., following function:
```elisp
    (defun my-kill-emacs ()
      "Kill emacs unconditionally by first removing all hook functions, and also
    removing all advices."
      (interactive)
      (setq kill-emacs-hook nil)
      (advice-mapc (lambda (function properties)
                     (advice-remove 'kill-emacs function))
                   'kill-emacs)
      (kill-emacs))
```
Typing `M-x my-kill-emacs` should always work.

**Comment by lebensterben** [comment]
@emacs18 I completely agree with you.
Emacs allows great degree of customization so these are situations we have to live with.
But I'm not sure whether we should use your alternative `kill-emacs` that disregard user configurations.

In my view, vast majority of users of `spacemacs` may not customize `emacs` to such a degree that `kill-emacs` won't work as expected.
Instead of unloading all hooks, probably a less radical approach is to have a wrapper that shows a more informative error message, should `kill-emacs` failed.

**Comment by emacs18** [comment]
The problem reported in this issue is that someone could not exit emacs.
I run into this problem once every few weeks or months.
I simply provided a way for someone to quit emacs without having to resort to `pkill -9 emacs` or similar drastic solutions.
That is all.

I think emacs itself should be modified to `kill-emacs` to catch errors, if any, then ask the user what to do.  I think one of the options presented to the user should be to ask if all hooks and advices should be ignored and exit.

**Comment by emacs18** [comment]
https://git.savannah.gnu.org/cgit/emacs.git/commit/etc/NEWS?id=b218c8b6b587d4f0629cbe81bf2dba95d07844d0
was checked in 15 hours ago to prevent `kill-emacs` from failing due to errors in hook functions.  So this problem is solved at least on emacs 28.   The fix appears not to be on emacs-27 branch.
