### ISSUE TITLE
magit provides git-commit-mode but it is a self-contained package on ELPA? 

### ISSUE THREAD

**Issue by clanghans** [syl20bnr/spacemacs#14069]
Hi, 

I was trying to tweak git-commit.el and stumble upon the different sources for that file. I found a wiki [EmacsWiki](https://www.emacswiki.org/emacs/GitCommitMode) where they claim that they merged git-commit into magit. I think the git commit packaged then is not needed anymore. 

Also tried to disable the git-commit package in the 'layers/source-control/packages' but it is not removed hence I could not test the behaviour without it. 

I am on develop with a selfcompiled emacs from master.

**Comment by dalanicolai** [comment]
Definitely you mean `~/.emacs.d/layers/+source-control/git/packages.el`. So the package git-commit is included in the list of packages needed for the git layer (develop branch), while indeed git-commit.el has been [merged into magit](https://github.com/magit/magit/blob/master/lisp/git-commit.el). So probably git-commit.el can be removed from the list of needed packages. This issue is just a notification/question about this situation.

**Comment by dalanicolai** [comment]
Also you must mean MELPA instead of ELPA. Thanks for opening the issue, but please try to be clear, and use `SPC h I` (capital i) for raising issues...

**Comment by clanghans** [comment]
#### Description :octocat:
git-commit.el is provided by the wrong MELPA package.
git-commit was completely merged from magit. See:
[EmacsWiki](https://www.emacswiki.org/emacs/GitCommitMode)


#### Reproduction guide :beetle:
- locate git-commit-20200828.1753 under ~/.emacs.d/elpa/28.0
- locate magit-20201020.2130 under ~/.emacs.d/elpa/28.0


*Observed behaviour:* :eyes: :broken_heart:
`SPC h d f` git-commit-next-message points to git-commit.el, which lives in the
git-commit package and not in magit.

*Expected behaviour:* :heart: :smile:
git-commit.el is found in the magit package

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. fc9d63b31)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
 cmake
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/")
 (lsp :variables lsp-clients-clangd-args
      '("-j=4" "--background-index" "--log=error" "--header-insertion=iwyu" "--header-insertion-decorators")
      lsp-auto-guess-root t lsp-ui-doc-position 'top)
 (shell :variables shell-default-shell 'ansi-term shell-default-full-span nil shell-default-position 'right shell-default-width 80 shell-default-term-shell "/usr/bin/zsh" close-window-with-terminal t)
 emacs-lisp git helm ibuffer org
 (python :variables python-formatter 'yapf python-format-on-save t)
 semantic shell-scripts themes-megapack version-control
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 (dash :variables dash-autoload-common-docsets nil dash-docs-use-workaround-for-emacs-bug nil))
```
- System configuration features: XAW3D XPM JPEG TIFF GIF PNG NOTIFY INOTIFY GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM MODULES THREADS JSON PDUMPER

**Comment by clanghans** [comment]
> Also you must mean MELPA instead of ELPA. Thanks for opening the issue, but please try to be clear, and use `SPC h I` (capital i) for raising issues...

sorry, was not aware. Still a newbie.

**Comment by smile13241324** [comment]
Well, yes git-commit is now included in magits repository on github, however it is not part of magit.el which you can easily check by opening a buffer for magit-status.el and check the files in the directory.

When you further check the version on magit [https://melpa.org/#/git-commit](here) you can see that the source refers to magits github repo, where you can find the file in the elisp directory.

We are pulling git-commit from melpa so it should be the one from magits repository.

Here is the proof, when you open git-commit.el you can find the license header of magit:
```elisp
;;; git-commit.el --- Edit Git commit messages  -*- lexical-binding: t; -*-

;; Copyright (C) 2010-2020  The Magit Project Contributors
```
So in my opinion we are using the right source.

**Comment by clanghans** [comment]
Thanks for clarification. Then we can close this.

**Comment by dalanicolai** [comment]
Indeed thanks for the clarification. It is not exactly clear to me how such
multi-file packages management works. But in vanilla Emacs, when I install
just `magit` using `M-x list-packages`, it automatically also installs
git-commit. So in that sense it comes with magit. Therefore I assumed that
declaring a separate git-commit also was not necessary in the git-layer (I
assumed this was deprecated), because of what clanghans pointed out. Also
he said that he discovered two different git-commit.el on his system,
although indeed on my system I also just have a single git-commit form
Melpa. Anyway, it is not very important when it is working alright, but I
guess it is cleaner if redundant code is removed (and I still assume it is
redundant, and clearly also confusing)

**Comment by dalanicolai** [comment]
Actually I have tested to install the git-layer, without having the
git-commit declared in the package-list and git-commit.el got installed
successfully. (But I am no expert, maybe there is another reason that the
git-commit is included there. Just sharing what I observed...)

**Comment by smile13241324** [comment]
Not sure if removing this would really improve the code, the point is right now it is an explicit dependency from us as we explicitly bind functions against it when it is lazily loaded.

If we would remove it we would change it to an implicit dependency pulled by magit. This would not allow us to lazily bind functions to it, we would have to do that in the init-magit block. Also we would make us dependent on an internal dependency of magit, what happens if they switch to a different package internally? Then our binding would be broken entirely.

Therefore if there are no pressing reasons to change I would like to keep it as it is for now.

**Comment by dalanicolai** [comment]
Well that is a very clear and strong explanation, very informative. In this
way in the end my arguments will get stronger also I guess:) Thanks for
sharing!
