### ISSUE TITLE
Error with Emacs 25. on Ubuntu 18.04

### ISSUE THREAD

**Issue by alexjose70** [syl20bnr/spacemacs#14081]
Hello,

When I am trying to install spacemacs, I am having this error:

Warning (initialization): An error occurred while loading ‘/home/lll/.emacs.d/init.el’:

Wrong type argument: stringp, random-gif

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

when I start the debug-init, it is comming this error:

https://easyupload.io/ymvu8w (I safe the output on that file)

**Comment by smile13241324** [comment]
@alexjose70 can you format your code please, as it is right now I cannot read this.
Basically it looks like your init.el is not working please check:
* What's your exact version of emacs? It must be at least 25.1.
* If your .emacs.d was created by emacs instead of spacemacs loading will fail, please remove the existing .emacs.d and retry.
* Are you running emacs on terminal or on UI.
* Do you run a standard dotfile? I have noticed the string `random-gif` which is what emacs complains about. This string is not in the spacemacs source code, so I expect this is the reason for your startup issues.

**Comment by alexjose70** [comment]
@smile13241324 . Thanks a lot for replying!.
1. it is emacs 25.3.2
2. I deleted the folder .emacs.d. But, on this error, I use .emacs.d/spacemacs/ folder.
3. I runned it from terminal. But, It is displayed on the UI.
4. I did not know what do you mean by standard dotfile. You mean .emacs? if so, I have empty file on .emacs.

Best Regards,
Alexis Meneses

**Comment by smile13241324** [comment]
Basically your Spacemacs config is in a file called .spacemacs normally located in your home directory. Please remove this file and restart Spacemacs this should remove this `random-gif` string. Spacemacs will generate a new one for you after having asked some basic question during the startup.

Btw are you on develop or master? Master should still be working but is effectively pinned and as of today horribly outdated so if you are just starting with Spacemacs you will most likely want to use `develop` instead of master.

**Comment by alexjose70** [comment]
Wou, I just delete de .spacemacs, now, it works fine.

How do I use the develop brand? I just git clone the spacemacs and I assume that it is using the master.

**Comment by smile13241324** [comment]
Just switch the branch in the git repository, to `develop`. Best remove the dotfile before you do that as the default has changed multiple times up to now. Otherwise you will have to diff and merge yourself with `SPC f e D`.
