### ISSUE TITLE
Formal website

### ISSUE THREAD

**Issue by naseer** [syl20bnr/spacemacs#1411]
I purchased the domain spacemacs.org to donate to this project - right now it redirects to the github page. We could have all of the excellent documentation that currently exists on a github pages repo and we could redirect the domain there. 

Opening this issue to discuss this.

**Comment by cpaulik** [comment]
I love the idea but I think @syl20bnr already thought of it. See http://spacemacs.info/ which links to the gh-pages branch of this repo

**Comment by tuhdo** [comment]
If so it's better if we have two. And I think `.org` is better than `.info`.

**Comment by nashamri** [comment]
That's great! 
Maybe we can leave `spacemacs.info` for the official documentations and `spacemacs.org` will be the place for guest blog posts, videos, tutorials and news, etc.

**Comment by naseer** [comment]
Will leave it to @syl20bnr  - on how he wants to use the .org

**Comment by syl20bnr** [comment]
Thank you for buying the `.org` domain! :+1:

I was not ready to put it on a `.org` since I won't move the project to a github org for now, though the project will be moved to an organization at some point.

We will use the `.org` domain since it now exists and it is a better domain that `.info`. 
I have no idea what we can do with the `.info`, I will probably just redirect it to `.org` :-)

**Comment by syl20bnr** [comment]
@naseer I updated the CNAME file, you can create the A records if it is not already the case, thank you!

**Comment by naseer** [comment]
I've added the A record now.

**Comment by naseer** [comment]
Domain is sorted - website development tracked in #1423
