### ISSUE TITLE
highlight-parentheses for C-mode does not display anything in buffer

### ISSUE THREAD

**Issue by janemba** [syl20bnr/spacemacs#14149]
Hi,

I don't know if it is a bug but I enable _highlight-parentheses_ with _C-mode_ but the buffer bar doesn't display anything when I highlight a parentheses. Should I add some settings in .spacemacs ?

**Comment by smile13241324** [comment]
Hi @janemba,

Please provide some more information about your emacs setup, you can get these conveniently by `SPC h I`.
You should first make sure that you have C/C++ layer installed in your dotfile, otherwise you are down on vanilla emacs functions.

Normally parentheses are highlighted by default with all available backends however this is not visualised in the buffer-bar (not content of [highlight-parentheses](https://github.com/tsdh/highlight-parentheses.el/blob/master/highlight-parentheses.el)).

It can be controlled via a dotfile setting `dotspacemacs-highlight-delimiters` here is the code from spacemacs-editing-visual layer:
``` elisp
(defun spacemacs-editing-visual/init-highlight-parentheses ()
  (use-package highlight-parentheses
    :defer t
    :init
    (progn
      (when (member dotspacemacs-highlight-delimiters '(all current))
        (add-hook 'prog-mode-hook #'highlight-parentheses-mode))
      (setq hl-paren-delay 0.2)
      (spacemacs/set-leader-keys "thp" 'highlight-parentheses-mode)
      (setq hl-paren-colors '("Springgreen3"
                              "IndianRed1"
                              "IndianRed3"
                              "IndianRed4")))
```

Maybe you are talking about eldoc integration? This is dependent on the backend used, for single files the simple emacs default backend can be used, for projects a fullfledged LSP server is highly recommended. These can automatically show information for things at point which seems to be what you are looking for.

**Comment by janemba** [comment]
Hi @smile13241324,

> Maybe you are talking about eldoc integration? This is dependent on the backend used, for single files the simple emacs default backend can be used, for projects a fullfledged LSP server is highly recommended. These can automatically show information for things at point which seems to be what you are looking for.

Mistake is on me it is not about `highlight-parentheses`, I don't have any backend. That was the issue. Fixed now. Thanks.
