### ISSUE TITLE
flycheck pops up twice with emacs-ycmd

### ISSUE THREAD

**Issue by naseer** [syl20bnr/spacemacs#1431]
(Contrived gif to show the issue visually)

![ycm-popup-issue](https://cloud.githubusercontent.com/assets/35860/7382158/8a79e356-edd9-11e4-83f9-8a58b4190b61.gif)

The issue goes away when disabling ycmd-mode in the current buffer. However, when I disable ycmd completely from config layers, it doesn't pick up my ycm config, so it doesn't give any error (apart from the first missing header error)

**Comment by naseer** [comment]
CC @tuhdo @abingham for info

**Comment by naseer** [comment]
This only happens on OSX and not Linux (I'm using emacs-24.5), so I'm closing this as this isn't a spacemacs issue

**Comment by tuhdo** [comment]
I think the error was shown twice because there were 2 active checkers and both return the same error. If you want to see one popup, you should disable the default flycheck checker and only use `ycmd` one.

As for the header file not found, see this issue: https://github.com/flycheck/flycheck/issues/458. When a header file not found, the default checker simply stops there without further checking the rest of your file.

**Comment by naseer** [comment]
I just used the "header not found" to illustrate the problem, my real file
doesn't have that problem.

How can I check which flycheck checkers are active? I'm only seeing this
issue on osx, it works fine on Linux with the same .spacemacs
