### ISSUE TITLE
Reverse typing after editing source code block

### ISSUE THREAD

**Issue by fluca1978** [syl20bnr/spacemacs#14359]
I'm using spacemacs 0.300 on emacs 26.3 on Neon (Ubuntu).
When I insert a source code block (`M i s src`) and I type the language (e.g., `sql`) the block becomes uneditable, because Emacs wants me to edit in a indirect buffer that is opened but not prompted. I then switch to the buffer, edit, and press `M-c RET` to exit the buffer.
Since then, Emacs starts writing right to left, or better in reverse mode so that `hello` is printed as `olleh` with the cursor fixed at the very beginning of the line. The only thing I have to do is kill the buffer and re-open.
All other buffers work fine, so it is like options for that buffer are changed.

**Comment by lebensterben** [comment]
Which mode are you in?

**Comment by fluca1978** [comment]
I've seen this happening with `sql`, it does not happen for example with `perl`.
The major mode is org.
I've also seen that when I start editing the sql block the minibuffer shows `SQL product nil is not supported; treated as ANSI`, in the case this can be useful.

**Comment by thanhvg** [comment]
I assume you were talking about org-mode and problem with sql source block. I also have this problem. My guess is org-mode is loading a bunch of sql backends when an sql bock is created, then it hangs on loading them. My workaround is to use example block instead or src block because I only need the syntax highlight.

```
#+begin_example sql
drop table 
#+end_example
```
Hope some org-mode experts can help us with this.

**Comment by fluca1978** [comment]
That is exactly the same problem I have, and so far I'm using the src block without specifying the `sql` language.
