### ISSUE TITLE
Evil keybindings for navigation no longer behave as expected in Info buffers

### ISSUE THREAD

**Issue by hwesterholt** [syl20bnr/spacemacs#14375]
#### Description :octocat:
Evil keybindings show weird behaviour in \*Info\* buffer; navigating between nodes via `]` and `[` no longer seems to work. (Other keybindings like `j`, `k` or `m` behave just as before)

#### Reproduction guide :beetle:
- Start Emacs
- Open \*Info\* via `C-h i` and choose any manual (e.g. the Emacs Lisp Intro)
- Press `]`

*Observed behaviour:* :eyes: :broken_heart:
Instead of opening the next node, `which-key` pops up. Apparently, `]` is interpreted as a prefix and the only follow-up suggestion is to press `u` (`evil-collection-unimpaired-url-decode`).

*Expected behaviour:* :heart: :smile:
Next node opens.

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3acf188ba)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion bibtex c-c++ csv dap deft emacs-lisp emoji finance games git helm html ipython-notebook javascript latex lsp
                 (org :variables org-enable-roam-support t)
                 osx pdf python ranger shell spell-checking syntax-checking themes-megapack version-control yaml)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER

#### Backtrace :paw_prints:
```
No backtrace.
```

**Comment by duianto** [comment]
It seems to have been caused when the `evil-collection` package was added:
[spacemacs-evil] add evil-collection #14200

to fix the deprecated `evil-magit` package.

We could add `evil-collection-info` support.

But there's a note about the square bracket bindings:
https://github.com/emacs-evil/evil-collection/blob/334670e29d964c5f591f75ccbf52b7b5faf4daba/modes/info/evil-collection-info.el#L91
>    ;; TODO: "[" and "]" are Emacs default for fine-grained browsing.
    ;; We usually use "C-j"/"C-k" for that.
    (kbd "C-j") 'Info-forward-node
    (kbd "C-k") 'Info-backward-node

One benefit with adding `evil-collection-info` support, would be that a common (consistent?) set of evil key bindings would be used.

**Comment by duianto** [comment]
Adding this to the `.spacemacs` `dotspacemacs/user-config` section, seems to restore at least the square bracket keys:
```elisp
  (evil-collection-define-key 'motion 'evil-collection-unimpaired-mode-map "]" nil)
  (evil-collection-define-key 'motion 'evil-collection-unimpaired-mode-map "[" nil)
```
to:
```
 ]                      ;; Info-forward-node
 [                      ;; Info-backward-node
```

**Comment by hwesterholt** [comment]
@duianto Thank you for your prompt feedback and the suggested workaround for the `[` and `]` keys.

Here is some information that I should have probably included earlier:
I had taken a look at `evil-collection` before filing the issue and I like the idea of using `evil` all over Emacs. However, I guess that the previous bindings (without `evil-collection`) were a mix of both `evil` and Emacs? Here is how I used to navigate through info:
  * move point via `h/j/k/l` (`evil`)
  * show menu items via `m`, switch to other nodes via `n`, `p`, `[`, and `]` (Emacs bindings I learned from the Texinfo docs)

This worked fine for me.

Do I understand you correctly in that Spacemacs has recently included `evil-collection` but support for `evil-collection-info` is still missing? Generally, I would be more than willing to learn new keybindings if that meant more consistent behaviour but I cannot make sense of the way Info currently behaves; it appears that some `evil-collection` bindings have found their way into Spacemacs while others have not (does this make sense?). Additionally, some of the previous `evil` bindings have been overwritten, I think:

  * Unchanged bindings:
    * `j` (`evil-next-line`) and `k` (`evil-previous-line`), both defined in `evil-motion-state-map`
    * `m` (`Info-menu`), `n` (`Info-next`) and `p` (`Info-prev`), all defined in `Info-mode-map`
  * Changed bindings
    * `h` has been mapped to `Info-help` (`Info-mode-map`)
    * `l` has been mapped to `Info-history-back`(`Info-mode-map`)
    * `[-` and `]-` are new prefixes defined in `evil-collection`)

I have tried to use `C-j` and `C-k` instead of `]` and `[` to move between nodes, but `C-j` is mapped to `electric-newline-and-maybe-indent` (set in `global-map`) and `C-k` is mapped to `kill-visual-line` (set in `visual-line-mode-map`).

This leaves me with two questions:

1. How can i politely ask that `evil-collection-info` be added as a feature? (I am afraid that I am not Lisp-savvy enough (yet) for my own PR)
2. In the meantime, what would I have to do to temporarily restore the functionality of `h` and `l`? Which keymap would be appropriate?

**Comment by duianto** [comment]
>Do I understand you correctly in that Spacemacs has recently included evil-collection but support for evil-collection-info is still missing? 

The `evil-collection-info` bindings have not been added yet.

The `evil-collection` was added in the PR:
[spacemacs-evil] add evil-collection #14200

Because the `evil-magit` package, (that Spacemacs used in the [git layer](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bsource-control/git)), has been deprecated, and moved to the `evil-collection`:
https://github.com/emacs-evil/evil-collection/tree/master/modes/magit

The evil-collection inclusion seems to only have intended to add support for the evil collections: `magit` and `vterm` bindings.

But calling: `(evil-collection-init)` seems to also have changed key bindings in other modes as well.

As you noted the changes in: `Info-mode`
I just noticed that in `help-mode`:
`[` and `]` also have the same prefix behavior of showing:
`u -> evil-collection-unimpaired-url-encode`
`u -> evil-collection-unimpaired-url-decode`

A new variable was also introduced: `spacemacs-evil-collection-allowed-list`
which is intended to make it possible to choose which evil-collection bindings one want to use.


We can add `info` to the allow list:
https://github.com/syl20bnr/spacemacs/blob/af0d0e72763c6b441087dfdb96b65020c3c43650/layers/%2Bspacemacs/spacemacs-evil/config.el#L22

Then the evil collection info key bindings work:
`[` and `]` are bound to:
https://github.com/emacs-evil/evil-collection/blob/334670e29d964c5f591f75ccbf52b7b5faf4daba/modes/info/evil-collection-info.el#L93-L94
```
    (kbd "C-j") 'Info-forward-node
    (kbd "C-k") 'Info-backward-node
```

`m` (`Info-menu`), is bound to:
https://github.com/emacs-evil/evil-collection/blob/334670e29d964c5f591f75ccbf52b7b5faf4daba/modes/info/evil-collection-info.el#L83
```
    "gm" 'Info-menu
```

and `n` and `p` are bound to:
https://github.com/emacs-evil/evil-collection/blob/334670e29d964c5f591f75ccbf52b7b5faf4daba/modes/info/evil-collection-info.el#L95-L96
```
    "gj" 'Info-next
    "gk" 'Info-prev
```

and the standard vim `h` backward and `l` forward char keys work as expected:
https://github.com/emacs-evil/evil-collection/blob/334670e29d964c5f591f75ccbf52b7b5faf4daba/modes/info/evil-collection-info.el#L42-L43
```
    "l" 'evil-forward-char
    "h" 'evil-backward-char
```

**Comment by duianto** [comment]
If you want the evil collection info bindings now.

Add the following to the `dotspacemacs-configuration-layers` section in your `.spacemacs` file:
```elisp
(spacemacs-evil :variables spacemacs-evil-collection-allowed-list '(info))
```

**Comment by hwesterholt** [comment]
Cool! Thank you so much for your detailed response that goes beyond what I had hoped for. I'll certainly check out `evil-collection` bindings for `dired` ... and one of these days I'll use `eww` for browsing. I'll close this issue now, thanks again.

**Comment by jojojames** [comment]
I recommend disabling unimpaired if using evil-collection with spacemacs: https://github.com/emacs-evil/evil-collection/blob/334670e29d964c5f591f75ccbf52b7b5faf4daba/evil-collection.el#L113 which is where the ] bindings are coming from. I assume spacemacs has their own version of unimpaired.

**Comment by duianto** [comment]
@jojojames Thanks for the suggestion.

@hwesterholt Pull the latest develop branch, the `[` and `]` keys now navigate in the Info buffer.
