### ISSUE TITLE
Layers list documentation on the website is outdated

### ISSUE THREAD

**Issue by knl** [syl20bnr/spacemacs#14420]
Comparing the content of layers documentation on https://www.spacemacs.org/layers/LAYERS.html with the `README.org` files in the repo shows that they are out of sync. It is also quite telling that in the bottom right there is: `Created: 2016-10-03 Mon 00:55`.

Maybe the website is built from the `master` branch, but would be great if we could be able to switch between `master` and `develop` documentation.

**Comment by lebensterben** [comment]
use

https://develop.spacemacs.org/layers/LAYERS.html 

instead

**Comment by blablablerg** [comment]
Do people use the main branch?

**Comment by smile13241324** [comment]
master is officially stale, the default is develop.
I have asked the others if we can change the website generation for `spacemacs.org` to develop. Right now `spacemacs.org` is showing master and `develop.spacemacs.org` shows develop.

**Comment by altsalt** [comment]
Wow, while reading through the documentation and considering switching to Spacemacs, I came across a broken link to one of the layers. Just dropped by to submit a quick PR and my pre-search found this issue. Glad I didn't put in too much effort, but to answer your question @blablablerg , yes, people absolutely use the main branch, since that's what anyone unfamiliar with the project is directed to.

**Comment by smile13241324** [comment]
@altsalt you are right the current way of communicating the status of stable is really not consistent. We have switched from stable releases on master to a rolling release workflow on develop some time ago due to just having not enough hands to curate master probably.

Anyway I will try to get a decision from our BDFL and see where it goes.

About broken links to documentations, this can happen as the website is auto generated from org hence if a non compatible link is merged, happens from time to time, you end up with a 404. Our CI tries to detect this but is not always successful.
Please double check on `develop.spacemacs.org`, if you still have broken links there please kindly report them as issues.

Famous last words, Spacemacs is better than it looks, if you have the time give it a try, not knowing from which editor your coming (Emacs? Vim?) we support both flavours. Still this is community work and an awfully complex one so if you stumble over bugs (you will, I mean its a big system) consider opening issues for them or try your luck with PRs.

And as always treat the community just the same as you want to be treated, and welcome to Spacemacs.
