### ISSUE TITLE
When in Insert Mode, Shift-Backspace invokes C-h

### ISSUE THREAD

**Issue by nugend** [syl20bnr/spacemacs#1443]
Evil issue? Spacemacs issue? Not really sure how to investigate. Doesn't seem to show up in the bindings when I use 'SPC-?' to search for it. C-h is present in those listings. No problem in Normal Mode (works like 'h').

**Comment by TheBB** [comment]
Not so much action here. Is this still an issue?

**Comment by nugend** [comment]
Hmm... it's more consistent now at least. Shift-Backspace invokes C-h in both normal and insert mode, so maybe I can just change the binding for Shift-Backspace?

**Comment by StreakyCobra** [comment]
There is an ongoing more general discussion about how to handle difference between `<tab>`, `TAB` and other keybindings in terminal in #3472. I've reported and linked this issue there, so closing this one to avoid dispersing discussions.

**Comment by imme-emosol** [comment]
Github issues are not a knowledge base and my issue was different, yet I am leaving a comment here, that Backspace not working in spacemacs evil editing mode, might be because this needs to be set/changed: `(normal-erase-is-backspace-mode 1)` ( https://www.gnu.org/software/emacs/manual/html_node/emacs/DEL-Does-Not-Delete.html#DEL-Does-Not-Delete ).
