### ISSUE TITLE
local package `zoom-frm` is outdated

### ISSUE THREAD

**Issue by lebensterben** [syl20bnr/spacemacs#14508]
https://github.com/emacsmirror/emacswiki.org/blob/master/zoom-frm.el

Question: for those localised package which are now available one `emacswiki`'s git repository, should we replace them altogether?

**Comment by snuffop** [comment]
I look forward to seeing the PR's  you create to address these issues.

**Comment by duianto** [comment]
This package has been updated.
[ci] Update built_in_manifest, add frame and zoom packages https://github.com/syl20bnr/spacemacs/commit/4a4557c3c80ccf59bcc2671e09bfee862d694363

Packages that are listed in `.ci/built_in_manifest` are checked by a bot,
which opens a PR when the local version doesn't match the source.

**Comment by lebensterben** [comment]
@duianto thx for the explanation.

Are all local packages inside "spacemacs*" layers intentionally updated by CI?

And for those non-"*spacemacs" layers, should we restrain the use of local packages?

**Comment by duianto** [comment]
I don't know, I'll ask the other maintainers.

**Comment by JAremko** [comment]
@lebensterben  only packages in `.ci/built_in_manifest` are updated.  We can add more packaged there but the core question is
why we have built-in packages if they can be updated :smile:  
 Libs are built-in because we need needed  them to bootstrap Spacemacs/handle errors.  Some other packages don't have upstream (forks or something obscure and abandoned).  So if a  package has reliable upstream I think we should install it from there instead of keeping it built-in.

Except packages that are always used  and hosted only at GitHub, like something from base layer. In this case it might make sense to keep them built-in + auto-updated since it will speed-up installation and everyone uses them anyway, also we'll be able to review changes  :thinking:

**Comment by lebensterben** [comment]
closing as this is resolved in https://github.com/syl20bnr/spacemacs/commit/4a4557c3c80ccf59bcc2671e09bfee862d694363
