### ISSUE TITLE
error at startup, unknown option `filter=tree:0'

### ISSUE THREAD

**Issue by sunlin7** [syl20bnr/spacemacs#14543]
Errors:
    - 
      An error occurred while installing nose (error: (error Failed to checkout ‘nose’: ‘Command ’(env LC_ALL=C /usr/bin/timeout -k 60 600 git clone https://github.com/syl20bnr/nose.el.git ~/.emacs.d/.cache/quelpa/build/nose/ --origin origin --filter=blob:none)’ exited with non-zero status 129: error: unknown option `filter=tree:0'

**Comment by lebensterben** [comment]
git error 129 means you supplied wrong arguments to `git`.

**Comment by sunlin7** [comment]
The git option `--filter=blob:none` require git-2.20, while in CentOS 7 the default git is git-1.8.
Run the git without `--filter=blob:none` can resovle this issue.
Close this ticket as local issue. Thanks.

**Comment by cubranic** [comment]
@sunlin7 wait: this may be a local issue, but I don't see how I am supposed to just "run git without the `--filter=blob:none` option" -- this error happens in Spacemacs's own package installation process during startup. It's Spacemacs that runs git, and we can't resolve this issue until you explain how to tell it not to use the filter option.

**Comment by sunlin7** [comment]
I run the `strace` then get the command line. 
Update the git to last version should be also work.

**Comment by cubranic** [comment]
@sunlin7 I'm glad you solved the problem on your own and closed this issue, but for those like me who come across it when searching for related problems, I'd like to document a better way to solve it. Obviously, upgrading git may not be an option for all users, nor would a less deeply technical user know how to run strace.

I don't have a deep knowledge of Emacs internals, but a quick grep through .emacs.d led me to "--filter=blob:none" being set in `core/libs/quelpa.el`, when the value of `quelpa-git-clone-partial` is set to `blobless`, while the OP's problem with `--filter=tree:0` happens when the variable has value `treeless`. Setting `quelpa-git-clone-partial` to `nil` should make Emacs do a regular clone, which while wasteful will at least work with older versions of `git`. Perhaps Spacemacs should fall back to this value on its own, on such systems?

**Comment by lebensterben** [comment]
@cubranic 
You should make this suggestion upstream.

https://github.com/quelpa/quelpa/

**Comment by cubranic** [comment]
Thanks @lebensterben, I didn't realize it was done by a separate package, and not Spacemacs. Filed quelpa/quelpa#218.

**Comment by duianto** [comment]
The changes have been applied upstream:
quelpa-git-clone-partial: check version berfore doing partial clone
https://github.com/quelpa/quelpa/pull/219

There's a pending PR here:
https://github.com/syl20bnr/spacemacs/pull/14573/files#diff-a59516a621055bd4dfc1c31d233860559ec07bfcc0e29e48121759eddd9834b9

to apply the upstream quelpa changes. I'll merge the PR,
when I get confirmation that the changes to the unrelated file 
that's included in the same PR should be reverted.

**Comment by cubranic** [comment]
Thank you for following up on the upstream fix @duianto!

**Comment by duianto** [comment]
The PR has been merged:
[bot] Auto-update #14573
