### ISSUE TITLE
ox-twbs cannot be found nor installed on development branch

### ISSUE THREAD

**Issue by jsevo** [syl20bnr/spacemacs#14555]
`SPC SPC package-install [RET] ox-twbs`

not showing up (used to be there). I am on the development branch. Also `SPC SPC org-twbs-export-to-html` not available. Apologies if I am missing something obvious.

**Comment by alexey0308** [comment]
Hi Jonas, can it be found if you do `package-refresh-contents`?

See also [FAQ](https://develop.spacemacs.org/doc/FAQ.html#install-a-package-not-provided-by-a-layer) on how to add additional packages.

**Comment by jsevo** [comment]
Hi Alexey,

Sorry I did not include that detail, no, `package-refresh-contents` does not fix the issue. Also, I was able to us `ox-twbs` a few months ago and cannot for the life of me think what might have changed.

**Comment by lebensterben** [comment]
@jsevo 
A few general steps:
- Checkout the latest develop branch
- Upadate existing Emacs packages
- `SPC f e D` to update your dotspacemacs

Then, try to add this package to `dotspacemacs-additional-packages` and see whether it would be installed that way.

**Comment by alexey0308** [comment]
by the way, in the docs it is written that you can just add to the layers
```
     (org :variables
          org-enable-bootstrap-support t)
```
to have this package installed.

**Comment by alexey0308** [comment]
Maybe the package is actually installed, but something gone wrong? Are you able to do `package-delete` or `package-reinstall`? Because one does not see a package listed in the `package-install`, if it is installed. Ironically, maybe deleting it first can solve the issue :)

Also it can be helpful, if you share the configuration in .spacemacs, related to the issue and people can give more advice...
