### ISSUE TITLE
smooth scrolling  and notmuch layer

### ISSUE THREAD

**Issue by kvaneesh** [syl20bnr/spacemacs#14621]
#### Description :octocat:

smooth scrolling and notmuch

with smooth scrolling enabled, using moving lines always result in cursor jumping to the
last line of the window. If I use emacs -Q and do

(add-to-list 'load-path "homedir/.emacs.d/elpa/27.2/develop/notmuch-20210205.1412")
(require 'notmuch)
(setq scroll-conservatively 101)

Things work as expected, that is jumping from one email thread to next keep the focus on the top of the
window/buffer and scrolling up/down do things as expected with smooth scrolling.

With spacemacs we are always jumping to the bottom of the window.

#### Reproduction guide :beetle:
- Start Emacs

scrolling in a buffer with multiple emails in notmuch with spacemacs.

*Observed behaviour:* :eyes: :broken_heart:

With spacemacs we are always jumping to the bottom of the window.

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>
Jumping from one email thread to next keep the focus on the top of the
window/buffer and scrolling up/down do things as expected with smooth scrolling.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4dc1d7640a98)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python html markdown
	(org :variables org-enable-reveal-js-support t)
	(helm :variables helm-completion-style 'helm helm-grep-file-path-style 'relative)
	emacs-lisp notmuch
	(git :variables magit-revision-insert-related-refs nil magit-revision-show-xref-buttons nil magit-backup-mode nil)
	asm
	(gtags :variables gtags-enable-by-default t)
	(lsp :variables lsp-navigation 'both lsp-ui-doc-enable nil lsp-enable-file-watchers nil lsp-enable-indentation nil lsp-clients-clangd-executable "/usr/bin/clangd" lsp-clients-clangd-args
	     `("--background-index=true" "-j=1" "--header-insertion=never" "--clang-tidy")
	     lsp-ui-peek-always-show t lsp-ui-doc-use-webkit t lsp-use-native-json t lsp-semantic-tokens-enable t lsp-headerline-breadcrumb-enable t lsp-modeline-code-actions-enable t lsp-signature-function 'lsp-signature-posframe lsp-ui-sideline-enable nil)
	(c-c++ :variables c-c++-backend `lsp-clangd c-c++-lsp-enable-semantic-highlight `rainbow)
	(auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-enable-snippets-in-popup t auto-completion-use-company-box t auto-completion-private-snippets-directory nil)
	(shell :variables shell-default-position 'bottom shell-default-height 30)
	mycustom version-control
	(multiple-cursors :variables multiple-cursors-backend 'evil-mc))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by kvaneesh** [comment]
I can recreate this without an updated spacemacs and just notmuch layer

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 66d774cd6725)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors notmuch treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER GMP

**Comment by kvaneesh** [comment]
using spacemacs-base as the distribution gets the correct behavior with the above minimal layer config

**Comment by kvaneesh** [comment]
adding window-purpose to dotspacemacs-excluded-packages seems to  help.

**Comment by kvaneesh** [comment]
I can recreate this with emacs -Q and the below lisp 
```

(require 'notmuch)
(require 'window-purpose)
(require 'window-purpose-x)
(setq scroll-conservatively 101)
(purpose-x-golden-ratio-setup)
```

**Comment by lebensterben** [comment]
So this is a upstream bug?

**Comment by kvaneesh** [comment]
Looks like some interaction between window-purpose, smooth scrolling and notmuuch. Not sure if there is a possible way to workaround this in spacemacs.

**Comment by bmag** [comment]
@kvaneesh I will look into this, but I can't understand the problem with the current info. I will need you to provide more precise info - see my questions below. Keep in mind that I never used notmuch, I only know it's an email client. I will say this - window-purpose isn't supposed to affect scrolling in any way, it should only affect what happens when changing which buffer is displayed in which window.

> scrolling in a buffer with multiple emails in notmuch

What commands should I use to open notmuch? I assume this is some buffer that displays a list of available emails. What command should I use to scroll in this buffer?

> With spacemacs we are always jumping to the bottom of the window

Don't understand what this means. The cursor moves to the last line in the window? What action on your part triggers a jump?

> Jumping from one email thread to next keep the focus on the top of the window/buffer

Not sure what is a "jump", do you have a threaded view of emails in this buffer, and "jump" is a command that moves the cursor to the beginning of the next thread? Do you mean after the jump, the line under the cursor should be at the top of the window?

> scrolling up/down do things as expected with smooth scrolling

I don't actually know what is the expected scrolling experience of smooth scrolling.

> `(purpose-x-golden-ratio-setup)`

Is this necessary to reproduce the bug?

**Comment by kvaneesh** [comment]
> @kvaneesh I will look into this, but I can't understand the problem with the current info. I will need you to provide more precise info - see my questions below. Keep in mind that I never used notmuch, I only know it's an email client. I will say this - window-purpose isn't supposed to affect scrolling in any way, it should only affect what happens when changing which buffer is displayed in which window.
> 
> > scrolling in a buffer with multiple emails in notmuch
> 
> What commands should I use to open notmuch? I assume this is some buffer that displays a list of available emails. What command should I use to scroll in this buffer?

notmuch-search and specify search strings like to:emailaddress (ex: to:notmuch) 

> 
> > With spacemacs we are always jumping to the bottom of the window
> 
> Don't understand what this means. The cursor moves to the last line in the window? What action on your part triggers a jump?
> 

it will open buffer with emails In that window we can use `n` and `p` command to jump from one email to the other. when doing so, the cursor should remain at the top of the window. But with window-purpose/purpose-x-golden-ratio-setup i find the cursor jumping to last line of the window.

> > Jumping from one email thread to next keep the focus on the top of the window/buffer
> 
> Not sure what is a "jump", do you have a threaded view of emails in this buffer, and "jump" is a command that moves the cursor to the beginning of the next thread? Do you mean after the jump, the line under the cursor should be at the top of the window?
> 
> > scrolling up/down do things as expected with smooth scrolling
> 
> I don't actually know what is the expected scrolling experience of smooth scrolling.

when using up-down arrow keys, it should not recenter the buffer in the window. 

> 
> > `(purpose-x-golden-ratio-setup)`
> 
> Is this necessary to reproduce the bug?

yes.

**Comment by bmag** [comment]
Looking around notmuch's code, couldn't find any bug. It was somewhat time consuming, but I managed to set up notmuch in a VM. However, I still don't understand how to reproduce the error.

I set up Ubuntu 20.04, installed notmuch from Ubuntu's repo via `apt install`, installed golden-ratio and window-purpose from Melpa, and used the `init.el` below.

```elisp
;; init.el
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
			 ("melpa" . "https://melpa.org/packages/")))

(package-initialize)

(setq tab-always-indent 'complete)
(setq ring-bell-function #'ignore)

(require 'notmuch)
(require 'window-purpose)
(require 'window-purpose-x)
(require 'golden-ratio)
(setq scroll-conservatively 101)
(purpose-x-golden-ratio-setup)
```

I followed these steps:
1. start Emacs
2. `M-x notmuch RET`
3. press `TAB` until point (the cursor) is on the "all mail" button, then press `RET`. Now the Emacs frame contains a single window, showing a buffer named `*notmuch-saved-search-all mail*` (major mode: `notmuch-search`). The buffer is similar to this [notmuch-search buffer screenshot from notmuch website](https://notmuchmail.org/screenshots/), only point (the cursor) is on the first line of the window (and of course different email messages).
![notmuch-search buffer](https://user-images.githubusercontent.com/4334375/115714224-8e63a080-a37f-11eb-9b0d-bf4a29abaf56.png)

4. from here I tried pressing `n` and `p` repeatedly, but didn't see any bug. If point is on some line that isn't the last line in the window, and I press `n`, then the point moves to the next line and that's it (no scrolling). If point is on the last line of the buffer, and I press `n`, then the point moves to the next line of the buffer, and the window is scrolled such that point's new line becomes the last line of the window. Similar behavior happens when I press `p` in the opposite direction (just swap the words "last", "next" with "first", "previous", etc.).

I won't be able to debug further without precise reproduction steps.

**Comment by kvaneesh** [comment]
Thanks for taking the time to debug this. In the above window you show above, select an email conversation with more than one email by pressing 'enter'. In the email view window 'n' and 'p' should move you from one email message in the thread to the next. I will also try to do a screencast video to show the bug.

**Comment by kvaneesh** [comment]
https://github.com/bmag/imenu-list/commit/76f2335ee6f2f066d87fe4e4729219d70c9bc70d  Can that make a difference? I am reverting this to recreate. I will just revert that and see if it recreate.

**Comment by bmag** [comment]
> Thanks for taking the time to debug this. In the above window you show above, select an email conversation with more than one email by pressing 'enter'.

How does Emacs' frame look after this action - does it show just a single window, which displays a buffer whose major mode is `notmuch-show`?

> email view window

I assume this refers to the window displaying the `notmuch-show` buffer.

> In the email view window 'n' and 'p' should move you from one email message in the thread to the next.

And then what happens? I still don't see a problem.

> I will also try to do a screencast video to show the bug.

Please do, and be careful not to share sensitive information by mistake.

> bmag/imenu-list@76f2335 Can that make a difference?

Very unlikely, but can't say for sure yet.

> I am reverting this to recreate. With every package updated, I can recreate, Reverting the above commit, I can recreate.

Didn't understand when you can recreate and when you can't. Maybe you forgot to write "not" somewhere in this sentence.
