### ISSUE TITLE
Obtrusive scrollbars are visible after recent spacemacs update, prevent windows from resizing

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#14789]
#### Description :octocat:
After a recent update of spacemacs, scrollbars started showing up where none were visible before. For example:

![Visible Scrollbars](http://synic.world/s/0fb55462.png)

They are only visible for a second after trying to scroll, but while visible, windows cannot be resized.

#### Reproduction guide :beetle:
- Start Emacs (GUI)
- Use the mouse scrollwheel in a window with enough text to scroll

*Observed behaviour:* :eyes: :broken_heart:
Scrollbars become visible, you can't resize windows

*Expected behaviour:* :heart: :smile:
I would like to make it so that the scrollbars worked the way they did before.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2515f141b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust typescript perl5 go swift csv lua nginx sql auto-completion emacs-lisp git yaml javascript html markdown major-modes python org osx python ipython-notebook django syntax-checking spell-checking colors spacemacs-layouts vimscript helm
      (version-control :variables version-control-diff-tool 'diff-hl)
      (c-c++ :variables c-c++-enable-clang-support t)
      (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
can you git-bisect to pin down the commit that caused this problem?

**Comment by duianto** [comment]
This was introduced here:
[defaults] Improve scrolling with mouse wheel #14542

The PR reduced the scroll wheel speed from `5` to `2`,
and the variable `mouse-wheel-progressive-speed` was disabled.

The scroll bar was added with an idle timer to be able to scroll longer distances.

It takes 45 scroll wheel turns to get from the top to the bottom of `.spacemacs`,
with the default Spacemacs frame size.

The scrollbars can be turned off in `.spacemacs`:
```
dotspacemacs-scroll-bar-while-scrolling nil
```

>windows cannot be resized.

If you mean dragging the border between two windows that are split left and right `SPC w v`, then I'm able to reproduce it.

It seems to be a bug in upstream Emacs, because it also happens without Spacemacs (just `emacs -q`).

There's no mouse over drag handle on the border between the windows, when the scrollbar is visible and the frame is split left and right `C-x 3`.

**Comment by synic** [comment]
Yup, that seems to be it. Thanks!
