### ISSUE TITLE
Straight.el based package managment workflow support. 

### ISSUE THREAD

**Issue by hongyi-zhao** [syl20bnr/spacemacs#14867]
Does spacemacs support package management workflow based on [straight.el](https://github.com/raxod502/straight.el)?

Regards,
HY

**Comment by alexalekseyenko** [comment]
I believe this is the main discussion:
https://github.com/syl20bnr/spacemacs/pull/14240
so that may be the better place to continue it, but it's definitely worth revisiting.

Functional package management is desirable (and inevitable) for all kinds of reasons and I think this comment:
https://github.com/syl20bnr/spacemacs/pull/14240#issuecomment-813636044
summarizes the situation pretty well.

**Comment by lebensterben** [comment]
See https://github.com/syl20bnr/spacemacs/pull/14240
