### ISSUE TITLE
 "dotspacemacs-line-numbers t" does not work

### ISSUE THREAD

**Issue by douglas-raillard-arm** [syl20bnr/spacemacs#14945]
#### Description :octocat:

"dotspacemacs-line-numbers t" does not work. Setting it to any value does not
bring line numbers. I checked with the .spacemacs.template file to avoid any
custom conf issue.

#### Reproduction guide :beetle:
- Start Emacs
- install the template as .spacemacs
- modify it so that you get "dotspacemacs-line-numbers t"

*Observed behaviour:* :eyes: :broken_heart:
No line numbers displayed when opening a text file.

*Expected behaviour:* :heart: :smile:
Line numbers displayed when opening a text file.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. fa514c6ac)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by douglas-raillard-arm** [comment]
Seems to actually work for most file. The one for which it did not work was without any extension, so maybe it was not recognized as code by emacs

**Comment by lebensterben** [comment]
Please use emacs >27

**Comment by lebensterben** [comment]
Please provide more details on how to reproduce the issue.

**Comment by douglas-raillard-arm** [comment]
Hi @lebensterben , sorry for the delay.
To reproduce:
1. load my emacs config (attached)
2. echo 42 > foo
3. emacs foo # No line number displayed by default
4. mv foo foo.rs
5. emacs foo.rs # After adding a recognized extension, emacs displays line numbers

`.spacemacs` conf: [spacemacs.txt](https://github.com/syl20bnr/spacemacs/files/7235757/spacemacs.txt)

**Comment by swang251** [comment]
Hi @douglas-raillard-arm , I believe what you experienced is the expected behavior. 

When a file without an extension is opened, it is by default in the [Fundamental mode](https://www.gnu.org/software/emacs/manual/html_node/emacs/Major-Modes.html#:~:text=The%20least%20specialized%20major%20mode,is%20in%20its%20default%20state.). When the `dotspacemacs-line-numbers` is toggled in your `~/.spacemacs`, it automatically toggles line numbers in all `prog-mode` and `text-mode` buffers, but not a `fundamental-mode` buffer. 

You can change the default mode of a no-extension file to the text-mode if you want. Check [here](https://www.emacswiki.org/emacs/AutoModeAlist) for more details.

Check the [Documentations](https://develop.spacemacs.org/doc/DOCUMENTATION.html#global-line-numbers) for more details about `dotspacemacs-line-numbers`:
> Line numbers can be toggled on in all `prog-mode` and `text-mode` buffers by setting the `dotspacemacs-line-numbers` variable in your `~/.spacemacs `to `t`.

**Comment by douglas-raillard-arm** [comment]
That makes sense, I'll try to fix my conf, thanks for the insights.
