### ISSUE TITLE
[Feature request] list buffers

### ISSUE THREAD

**Issue by DjebbZ** [syl20bnr/spacemacs#1495]
Hello everyone,
I just installed Spacemacs to try it out and finished the evil-tutor. Along the way, I played a bit with it, and noticed there's no binding to list buffers. I know Emacs has `C-x C-b`. Why not adding a `list-buffers` command, bound to `SPC b l`? It's not used and not listed in the docs. I verified the availability with `SPC h d k` (`spacemacs/describe-key`).

**Comment by tuhdo** [comment]
You can use `SPC b s` (next release it's gonna be `SPC b b`) for interactive buffer listing that you can narrow by typing search patterns.

My [Helm guide](http://tuhdo.github.io/helm-intro.html) could help you better at using Spacemacs, since Spacemacs is Helm centric. The key bindings listed there is not the same as Spacemacs, but you can use `M-x` to search for the commands and see the key bindings next to it.

Also you may find my [Helm Projectile guide](http://tuhdo.github.io/helm-projectile.html) useful.

**Comment by DjebbZ** [comment]
`SPC b s` does approximately what I want. Gonna read your guides to learn more. Thank you !
Closing.

**Comment by CarlQLange** [comment]
Also if you really want a list-buffer function:

```elisp
(evil-leader/set-key "bl" 'ibuffer)
```
