### ISSUE TITLE
VTerm layer init annoyances if no vterm available

### ISSUE THREAD

**Issue by pataquets** [syl20bnr/spacemacs#15044]
Spacemacs devel branch, Ubuntu Bionic.
If you install `shell` layer, `vterm` package initilization asks to compile `vterm`.
Although useful in many cases, this has two drawbacks:
* If, as in my case, I can't compile easily and do not want to mess with Nix or whatever, and I'm not interested in VTerm, the question keeps popping each time.
* Due to the above, `emacs --daemon` hangs on boot awaiting Y/N to compile prompt .

So far, I've worked around it by setting `vterm-always-compile-module` to `t`, and, since compilation fails on Bionic due to CMake version, it just works, but it can be annoying or even a blocker to use in other setups.

Maybe an option to disable `vterm` pkg init checks for compilation would do.

**Comment by pataquets** [comment]
cc: @deb0ch (FYI)

**Comment by lebensterben** [comment]
first, you can choose to use other she'll implementation via layer variable. Alternatively you can disable the vterm package by adding it to package exclusion list.

second, why would the daemon ever try to compile vterm? do you open vterm buffer in daemon? that sounds like a configuration issue, not a bug.

**Comment by pataquets** [comment]
Thank you @lebensterben.

I was using default shell (no explicit conf variable). However, I've explicitly set `shell-default-shell 'ansi-term` just to be sure, and it keeps asking.
I guess that Spacemacs' layer install/loading on startup runs always the VTerm binary present check.
Also, I'm not opening any VTerm buffer on startup (at least, not intentionally). No VTerm buffer pops up after startup.
Also, I was afraid to exclude `vterm` in case something else on the layer broke, but I've just tried it and everything works, so far (I have to test it better, though).

Maybe just a warning on the troubleshooting note in the layer docs section would be enough, I'm not sure if it's necessary or it's just me :)

**Comment by lebensterben** [comment]
this sounds strange. spacemacs in no circumstances launches vterm on  startup. Actually packages are loaded lazily. That is, commands and functions are registered but not loaded until user actually use them.

So by default vterm-* commands should not be eagerly loaded, let alone running automatically.

**Comment by GreenRecycleBin** [comment]
I just ran into the same issue now that [`multi-vterm.el` is part of Spacemacs's shell layer](https://github.com/syl20bnr/spacemacs/blame/develop/layers/%2Btools/shell/packages.el#L372-L389) and it [`(require 'vterm)`](https://github.com/suonlight/multi-vterm/blob/36746d85870dac5aaee6b9af4aa1c3c0ef21a905/multi-vterm.el#L34). This happens because [`package.el` byte-compiles files by default](https://github.com/emacs-mirror/emacs/blame/4289044ccf5a07862234903f09d6eb46ac08a925/lisp/emacs-lisp/package.el#L65-L66) unless they opt out with `;; -*-no-byte-compile: t; -*-` (or [`((emacs-lisp-mode . ((no-byte-compile . t))))` for a directory](https://emacs.stackexchange.com/a/36847/5377)).

As mentioned, `(setq vterm-always-compile-module t)` in `dotspacemacs/user-init` works around this problem.

```
  INFO     Scraping files for multi-vterm-autoloads.el... 
Generating autoloads for multi-vterm.el...done
  INFO     Scraping files for multi-vterm-autoloads.el...done
Wrote /Users/greenrecyclebin/.emacs.d/elpa/28.2/develop/multi-vterm-20221031.610/multi-vterm-autoloads.el [2 times]
Checking /Users/greenrecyclebin/.emacs.d/elpa/28.2/develop/multi-vterm-20221031.610... [3 times]
Compiling /Users/greenrecyclebin/.emacs.d/elpa/28.2/develop/multi-vterm-20221031.610/multi-vterm.el...
Vterm needs `vterm-module' to work.  Compile it now? (y or n) n
Checking /Users/greenrecyclebin/.emacs.d/elpa/28.2/develop/multi-vterm-20221031.610...
Done (Total of 0 files compiled, 1 failed, 2 skipped)
```
