### ISSUE TITLE
default-pop-shell won't cd to current file/buffer's directory in this situation

### ISSUE THREAD

**Issue by RedLobster999** [syl20bnr/spacemacs#15052]
#### Description :octocat:
short description:
default-pop-shell SPC' won't cd to current file/buffer's directory in some situation

long description:
pop-shell won't cd into the directory of current file
if the current file happens to be the file that pop-shell was called/activated from for the first time
however it will cd into current file's directory if that directory is different
from the directory of the file that pop-shell was called/activated from for the first time

my investigation:
under function "shell-pop-up" I found

```
    (when (and shell-pop-autocd-to-working-dir
               (not (string= cwd default-directory)))
      (shell-pop--cd-to-cwd cwd))
```
I suspect that "(string= cwd default-directory)" part is causing this unexpected behavior

#### Reproduction guide :beetle:
0 create file ~/foo.txt and ~/bar/baz.txt
1 Start Emacs
2 open file ~/foo.txt
3 type SPC'
4 i'm now in the terminal in ~/ home directory
5 type SPC' to hide the terminal
6 split a second window and jump into that
7 open file ~/bar/baz.txt
8 type SPC'
9 i'm now in the terminal in ~/bar
10 type SPC' to hide the terminal
11 jump back to the first window to ~/foo.txt
12 type SPC'
13 i'm now in the terminal however still in ~/bar

*Observed behaviour:* :eyes: :broken_heart:
on the last step, 13, the location of the terminal is the same as step 9
(cd was not called)

*Expected behaviour:* :heart: :smile:
the location of the terminal in step 13 should be home directory ~/ instead of ~/bar

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 483cdd1c0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript emacs-lisp git helm org
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            neotree)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
Confirmed. Thanks for the report.

**Comment by lebensterben** [comment]
Workaround found:

Whenever a new shell buffer is created, it would be named as `*SHELL-INDEX*`.
When `layouts-enable-local-variables` is non-nil, it's named as
- `*LAYOUT-remote-SHELL-INDEX*` on remote session.
- `*LAYOUT-SHELL-INDEX*` otherwise.

In either case, each new shell buffer is uniquely identifiable by the INDEX.
Therefore a quick fix is to keep a hashtable of file-buffer-id shell-buffer-index pair.

When opening the pop-up shell, first examine whether this file buffer has an associated shell buffer. If so, directly open that buffer with specific index. Otherwise, let pop-shell start a new buffer and store the index of the newly created shell buffer in the hashtable.

The only issue is, when a shell buffer is closed, we need to delete that entry in the hashtable.
