### ISSUE TITLE
Spaceemacs can't display Chinese on Windows 8

### ISSUE THREAD

**Issue by yxsongbo** [syl20bnr/spacemacs#1510]
it can display on ubuntu.

**Comment by louy2** [comment]
Could you give a screenshot and a sample document? I have no problem with `utf-8` document in Chinese, but I observe problem with other encoding formats.

**Comment by yxsongbo** [comment]
![capture](https://cloud.githubusercontent.com/assets/135945/7587120/67c955cc-f8e6-11e4-8f35-3631ff62902d.PNG)

now I solve the ploblem by edit core/core-dotspacemacs.el like this:

(set-fontset-font "fontset-default" 
'gb18030 '("Microsoft YaHei" . "unicode-bmp"))

but i think add the code to core-dotspacemacs.el is not a good way. and I am confused why spacemacs work well in Ubuntu, but not in Windows 8 ?

how can I give you a sample document ?

Thank you.

**Comment by louy2** [comment]
Since you have already got your working settings, you can create a layer called maybe "chinese" and put the settings in `chinese/config.el`.

[Documentation on private layer configuration](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#configuration-layers)

**Comment by syl20bnr** [comment]
I'm very interested in having a `chinese` layer in spacemacs. We could add some chinese specific packages to it like these one:

- http://melpa.org/?utm_source=dlvr.it&utm_medium=twitter#/weibo
- https://github.com/xuchunyang/pinyin-search.el
- https://github.com/tumashu/chinese-pyim

**Comment by et2010** [comment]
I've already made a private layer called chinese, if you are interested ; )
https://github.com/et2010/Chinese

**Comment by louy2** [comment]
I personally do not use in-emacs input method. Is there any benefit to it over independent IME like RimeIME?

**Comment by hijarian** [comment]
@louy2 If you use in-emacs input method, key bindings continue to work even if you are inside this input method.
For example, the plague haunting Cyrillic languages is that if you change your keyboard layout via, let's say, window manager, then in Russian keyboard layout you have *no* keybindings, because `C-x` becomes `C-ч` and Emacs doesn't know what to do with this. If you change your layout via Emacs, `C-x` will continue to work even if when you hit `x` key you get `ч` printed. This is insanely helpful in Viper emulation, because working with Cyrillic text in Vim is just horrible - you must change keyboard layout each time you enter and exit input mode!

However, I don't know how all of the above applies to very specific IME like CJK/devanagari/whatever ones.

**Comment by andyque** [comment]
@syl20bnr  I have created a Chinese layer https://github.com/syl20bnr/spacemacs/pull/2024

**Comment by louy2** [comment]
@hijarian I see. Unfortunately the input method I use is not available in emacs yet.
