### ISSUE TITLE
Cannot exit emacs

### ISSUE THREAD

**Issue by Soromeister** [syl20bnr/spacemacs#15105]
Trying to exit emacs after clicking inside on the "Update packages". Commands just pile up and there is no way to simply "cancel whatever keeps piling down there. Please see screenshot for details. This would not have been an issue in VIM, where ENTER actually executes the command you're giving it.

![image](https://user-images.githubusercontent.com/45243695/137707071-6fe15377-1dca-42f7-90e7-fcf180cf8da2.png)

**Comment by smile13241324** [comment]
Ok there seems to be a bug in the home buffer when emacs is run in terminal mode and a left click is done on the update button.

This results in jumping into the mini buffer where all entered keys are listed.

This only happens when the button is clicked in terminal mode.

**Comment by smile13241324** [comment]
@duianto are you familiar with those push buttons? I have no idea whats going on here but all non url link buttons on the home buffer are broken when spacemacs is running in terminal mode and a mouse is used.

**Comment by duianto** [comment]
This might be related to using the mouse in a Linux terminal.
I don't know if it also happens in a Mac terminal.

### Summary:
The package update doesn't start when mouse clicking on `[Update Packages]` in the Manjaro Terminal.
It just inserts minibuffer text like this, with every mouse click:
>ESC [ < 0 ; 6 0 ; 1 3 m-

At least for me, in Manjaro, `C-g` cancels the minibuffer mouse click messages.
Then Spacemacs works as expected, and `SPC q q` exits.

I'm not familiar with Linux terminals, so someone with more knowledge would probably have to investigate further.

### Manjaro Terminal
`emacs -nw`

When mouse left-clicking on the `P` in the button `[Update Packages]`.
Then the minibuffer shows:
```
ESC [ < 0 ; 6 0 ; 1 3 m-
```
Nothing else seems to happen.
The package update never starts.

Left-clicking again shows:
```
ESC [ < 0 ; 6 0 ; 1 3 m ESC [ < 0 ; 6 0 ; 1 3 M ESC [ < 0 ; 6 0 ; 1 3 m-
```

Pressing `C-g` shows: `Quit`.

`view-lossage` (`C-h l`) shows:
```
ESC [ < 0 ; 6 0 ; 1 3 M ;; widget-button-click
ESC [ < 0 ; 6 0 ; 1 3 m ESC [ < 0 ; 6 0 ; 1 3 M ESC [ < 0 ; 6 0 ; 1 3 m C-g C-h l ;; view-lossage
```
`6 0` is the column.
`1 3` is the row.

### Manjaro Gui Emacs
`emacs`

Mouse left-clicking on `[Update Packages]
shows in the minibuffer:
>Contacting host: melpa.org:443

Pressing `C-g` shows: `Quit`

It seems to be possible to cancel the package checking at any point.

### Windows 10 Command Prompt (cmd.exe)
`"C:\Program Files\Emacs\x86_64\bin\emacs.exe" -nw`

Mouse clicking on `[update packages]`,
starts checking for updates.

Pressing `C-g` might only work if it's pressed in the first 2 or 3 seconds.
while it still says:
>--> refreshing package archive: melpa... [1/3]

There's a delay (maybe 2 seconds) before it cancels the checking.
Then it says: `Quit`

The delay makes it seem like nothing happened.

If one waits for about 3 or 4 seconds, then `C-g` doesn't do anything, even if it's pressed multiple times. The package checking continues until it's done.

At least when:
>--> All packages are up to date.

If there are packages with updates, then it might cancel before showing the number of packages with updates, and asking for confirmation to update.

`view-lossage` (`C-h l`) shows:
```
 <help-echo> <help-echo> <down-mouse-1> ;; widget-button-click
 <mouse-movement> <mouse-movement>      ;; anonymous-command
 <mouse-1>                              ;; widget-button-press
 C-h l                                  ;; view-lossage
```
The `<mouse-movement>` entries are not related to actually moving the mouse.
Because the mouse was turned up-side down,
(the laser isn't detecting any motion)
before left clicking on the button.

`<mouse-movement>` is added when the left mouse button is clicked.
This can be seen by pressing the left mouse button and opening `view-lossage` with `C-h l` before releasing the mouse button.
```
 <help-echo> <down-mouse-1>        ;; widget-button-click
 <mouse-movement> <mouse-movement> ;; anonymous-command
 C-h l                             ;; view-lossage
 <mouse-1>                         ;; mouse-set-point
```

### Windows 10 Gui Emacs
`"C:\Program Files\Emacs\x86_64\bin\runemacs.exe"`

Mouse clicking on `[update packages]`
shows in the minibuffer:
>Contacting host: melpa.org:443

Pressing `C-g` cancels the package checking.
and the minibuffer shows: `Quit`

### Both Manjaro and Windows 10 in Gui Emacs

`view-lossage` (`C-h l`) shows:
```
 <help-echo> <help-echo> <down-mouse-1> ;; widget-button-click
 <mouse-1> C-h l                        ;; view-lossage
```
The instances of `<help-echo>`, come from moving the mouse pointer over a button.
`<mouse-1>` comes from releasing the left mouse button.

The messages buffer seems to add `<mouse-1>` at the beginning of the next line, when a new line is added to `view-lossage`.

#### Wiget Fields
And the widget (button) fields, are the same in both Manjaro and Windows 10.

Moving the cursor (with the keyboard, not the mouse),
to the `[` in `[Update Packages]`,
and evaluating (`S-M-;`):
```
(wiget-at (point))
```
returns:
```
(push-button :args nil :value #("Update Packages" 0 15 (face font-lock-keyword-face)) :help-echo "Update all ELPA packages to the latest versions." :action (lambda (&rest ignore) (configuration-layer/update-packages)) :mouse-face highlight :follow-link "
" :button-overlay #<overlay from 258 to 275 in *spacemacs*> :from #<marker (moves after insertion) at 258 in *spacemacs*> :to #<marker at 275 in *spacemacs*>)
```

The only difference is the positions in the `:button-overlay`, `:from` and :to`.
Most likely because the Spacemacs logo, looks different in the terminal versions.

Possibly because the Windows Command Prompt doesn't have the correct font.

The Spacemacs home buffer logo looks like this:
In Windows Command Prompt:

![cmd_NkkM7yVJh6](https://user-images.githubusercontent.com/13420573/143780278-65e871d7-cb02-4b80-8180-0397c5c61aa7.png)

In the Manjaro Terminal:

![VirtualBoxVM_AHm9nMOnK7](https://user-images.githubusercontent.com/13420573/143780293-7047ce67-177a-4c17-be19-38ffc02cbe56.png)

### System info

<details>
<summary>Manjaro</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 23367d08f)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

</pre>
</details>

<details>
<summary>Windows 10</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 23367d08f)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey helm emacs-lisp git html javascript markdown multiple-cursors
                 (org :variables org-enable-roam-support t)
                 pdf python
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>
