### ISSUE TITLE
.emacs file stops Mac OSX from installing spacemacs

### ISSUE THREAD

**Issue by xandhiller** [syl20bnr/spacemacs#15130]
On Mac OSX I had to delete my `.emacs` file to get Spacemacs to initialise (after cloning the repo to `~/.emacs.d`). This isn't mentioned on the docs as far as I can see.

**Comment by HanshenWang** [comment]
Getting started with Spac(emacs) can be a huge undertaking, and you're right,
the warning is found under the README.md.
https://github.com/syl20bnr/spacemacs#default-installation and not the docs
explicitly. And I agree knowing whether or not you have an existing Emacs
configuration is dependent on your UNIX knowledge of dotfiles as configuration.
Is there anything not up par in the current link above?

I'm glad you got it resolved. In the docs, I believe the exposition for the
README.md excerpt is here
https://develop.spacemacs.org/doc/QUICK_START.html#dotdirectory-spacemacsd. But
hey, everything is working, and welcome to Spacemacs!

I know what I got started I really liked Jack of Some's videos linked here:
https://github.com/syl20bnr/spacemacs#getting-help

I'd be remiss too if I didn't point out `SPC h SPC` is excellent to browse not
just the docs (`Quick Start` and `Beginners tutorial` are recommended if you
haven't glanced at em already `C-j/C-k` to select), but also which elisp package
belongs to which layer. `C-h f`, `C-h v` and `C-h b` are also going to become
your bread and butter! Check out the `helpful` layer too.

Indulge me here, but the last thing I wish I knew when starting out is
to use magit to backup your `.emacs.d`. Backup the `elpa` directory too (where
your third party emacs packages reside). Because stuff will break upstream, and
I've become irrationally attached to my emacs editing environment.

All the best,

**Comment by liuzhijun-source** [comment]
It is normal. Emacs find .emacs file in your home dictionary at first to loading configuration, if it cannot find it, emacs will look up the init.el file in .emacs.d dictionary. Deleting .emacs file is correct. This is a common sense in Emacs.

Have good time learning Emacs ;)

**Comment by smile13241324** [comment]
I think this has been clarified so far. Please feel free to add clearer instructions to the documentation in your first PR, nudge nudge, and welcome to Spacemacs and the emacs world :)
