### ISSUE TITLE
[auto-completion] No auto completion in `ielm` buffers

### ISSUE THREAD

**Issue by bjarkevad** [syl20bnr/spacemacs#1523]
As the title says, there's no auto completion in `ielm` buffer. This can be enabled by simply executing `company-mode`.
Is there a reason that this is disabled by default?

**Comment by person808** [comment]
You can add `(global-company-mode t)` to your `.spacemacs` to have it everywhere by default

**Comment by syl20bnr** [comment]
For better modularity and better control on company completion backends we activate company explicitly for each mode.
The decision to enable company globally must be done at the user level, Spacemacs won't do it. I think it is documented in the README of the auto-completion layer.

**Comment by syl20bnr** [comment]
Well I said better modularity it is discutable. I would correct this by saying it is more about the decision to explicitly define what it is used in a layer. The new emacs-lisp layer in develop is an example of such approach. Instead of having configuration spread everywhere or having implicit configuration, everything is listed in the layer, so by looking at the layer we know what is configured, we have a central place to have the full picture. It will be even better when packages.el and extensions.el will be merged.
In the case of company there is also the need (well I find it to be a need) to cherry-pick the backend per mode instead of putting them all in one globally available bucket. This approach is possible with the design described above so everything fit nicely together.

**Comment by tuhdo** [comment]
IELM is Emacs Lisp REPL. We should enable company for it in Emacs Lisp layer.

**Comment by TheBB** [comment]
Company is enabled in IELM now.
