### ISSUE TITLE
Feature Request: Idiomatic, mnemonic binding for search and replace

### ISSUE THREAD

**Issue by mcp292** [syl20bnr/spacemacs#15263]
I'd like to perform a search and replace without issuing `:%s/old/new/gc` every time. 

I'm looking for `query-replace` or similar, but with a spacemacs binding. It's currently bound to the emacs `M-%`. It would be more idiomatic and mnemonic to be bound to the search leader `SPC s`. I'm thinking `SPC s R`. (I wouldn't mind having `SPC R` be an alias for this, but expect that binding is already used by a layer I don't have enabled.)

The solution should work inside and outside of projects. I mention this because I came across [a suggestion to use `SPC *`](https://www.reddit.com/r/spacemacs/comments/hl0xuq/comment/fww38aw/?utm_source=share&utm_medium=web2x&context=3), but that only works if you're in a project. Same goes for the already bound `SPC s p`.

Sure I can make a binding in my `.spacemacs`, but as a new spacemacs user, I'm surprised to see such a commonly used function not optimized through the spacemacs idiom. Seeing that there are a bunch of posts and discussions regarding this [1] [2], it seems I am not alone in this reaction and so I make this post to serve as a request to integrate this binding into spacemacs by default.

References:  
1. https://duckduckgo.com/?q=search+and+replace+spacemacs
2. https://duckduckgo.com/?q=find+and+replace+spacemacs

**Comment by lebensterben** [comment]
one of "spacemacs idiom" is to use well-known vim keys.
M-% uses a modifier and should be avoided for top level bindings.

**Comment by dalanicolai** [comment]
Actually the vim search replace is much nicer than the Emacs query-replace... it shows a nice preview, and you can use vim regexps instead of the convoluted Emacs regexps. So personally I would point users to use that, and divert them from `query-replace`.

@lebensterben That means you agree that is better under `SPC`?

Well, in the end I also agree, for discoverability, that it is nicer if there is a Spacemacsey binding for this, instead of the default Emacs binding. But what about `SPC s q` (at least no modifier key required)?

**Comment by lebensterben** [comment]
it's a common pattern that you may need to slightly modify the last search query.

Our current way of using vim-style search is that you can use arrow keys to revisit the ex command history, which becomes extremely handy.

On the other hand, query-replace is too rudimentary. I'm not convinced to give it a dedicated "SPC s" binding.

**Comment by mcp292** [comment]
Okay, what about including an interactive version of `:%s/old/new/gc` under a `SPC s` binding?

> Our current way of using vim-style search is that you can use arrow keys to revisit the ex command history, which becomes extremely handy.

This is handy, but since you can't use vim bindings in the helm buffer, I stopped using this feature.

> Well, in the end I also agree, for discoverability, that it is nicer if there is a Spacemacsey binding for this, instead of the default Emacs binding. But what about SPC s q (at least no modifier key required)?

`SPC s q` is nice for `query-replace`. But, I agree with both of you that the vim search is more powerful and we don't need to support and encourage use of `query-replace`. So instead, if we bind the vim search functionality making it interactive, then we'd want some mnemonic of the vim function `substitute`.

In case there is any confusion, when I say making interactive, I envision you being to issue something like `SPC : s` and then being prompted for `old` and `new`; instead of having to format the command which is many more keystrokes.

**Comment by lebensterben** [comment]
"making it incremental" in the way you suggested actually make it not incremental any more.

currently as you are typing, matched text are highlighted in the main buffer.

query-replace style "interactivity" has no such incremental search ability.

**Comment by mcp292** [comment]
> "making it incremental" in the way you suggested actually make it not incremental any more.

I think you mean "interactive" here, and if so I get your point. This would be a trade off: extra keystrokes, but more control and incremental highlighted vs less keystrokes, less control, full query highlighting.

Users would still be free to use `:%s/old/new/gc`, but also have the option do to the quicker `SPC : s` (or whatever we bind it to).

**Comment by lebensterben** [comment]
Let aside whether to make a new command with the feature you suggested, I'm not convinced to have it take a new key binding, which could be used for other more important/useful commands.

**Comment by lebensterben** [comment]
We have a limited amount of prefix keys and assigning `SPC :` or other `SPC <prefix>` should be taken very cautiously. In my opinion only most frequently used commands deserve such key bindings.

**Comment by mcp292** [comment]
Thank you for the clarification. I do agree with that sentiment. Wouldn't you consider search and replace to be a very common action?

**Comment by lebensterben** [comment]
it's very often used. but it goes back to the other issue, that the current way of handling search and replace is better than the proposed one in every aspect accept for a few more key strokes. And that a few more key strokes is completely cancelled out by the amount of typing saved due to the availability of ex command history.

**Comment by mcp292** [comment]
That's a good argument, but saving key strokes is very important, especially to "vim" users. And as I mentioned, the ex history is also great, but the fact that it can't be edited through vim bindings, makes it less useful and in most cases quicker to start over than revert to standard emacs bindings or arrow keying. In other words if I could `b b cw` on the ex history, that would justify your point completely and close this issue, but as far as I have seen you can't in the helm buffer. And so the saving of key strokes returns to being important.

**Comment by lebensterben** [comment]
> especially to "vim" users

No that's not a valid argument.
vi users would prefer our current implementation.

**Comment by mcp292** [comment]
I'd like to hear others chime in on the important of minimizing keystrokes.

>  vi users would prefer our current implementation.

This proposition would not change anything for people who prefer the `%s/old/new/gc` pattern. It would be an additional means of using this, or at the very least, a better binding for `query-replace` than the emacs `M-%`.

I think we both see where we're coming from, and I appreciate your cooperative discussion. I'd like to step back for a bit and hear thoughts from others in the community.

**Comment by dalanicolai** [comment]
@mcp292 I suggest that you first watch [this video](https://www.youtube.com/watch?v=XAHVwhTsF-g&t=198s). If after watching that video you still find some quick substitute keybinding very important (because you really do REGEXP replace frequently, then I suggest you add the following to your `user-config`:
```
(defun quick-ex-substitute (beg end)
  (interactive "r")
  (if (region-active-p)
      (evil-ex "'<,'>s/")
    (evil-ex "%s/")))

(spacemacs/set-leader-keys "sx" #'quick-ex-substitute)
```
(where the 'x' stand for ex

It gives you a very convenient shortcut, and I guess also the least amount of typing, plus all the other advantages of the vim style mentioned above. When you notice that you really use it very frequently, then open a PR for it (you should then document it also, and convince others that this is a very valuable command/shortcut).

**Comment by mcp292** [comment]
Thank you @dalanicolai! Very clever, simple, and effective approach to the problem! I have added it to my config and will report back after some extensive use. So far it really makes the vim command much less painless to use.

From my use so far, I don't think the `if (region-active-p)` statement is doing what you want. If I highlight something with `v ll` then issue `SPC s x`, it literally inputs `'<,'>s/` into the minibuffer, when I'm assuming you want the highlighted text instead.

I'm not in love with `x` as the mnemonic, but I'm just as lost for a better option that's not already taken. The reason I'm not sold is that `ex` doesn't have much to do with the specific action: `substitute`. `s`, `S`, are both taken, `u` is not. I'm not sure if `u`, as in sUbstitute, would even count as a mnemonic.

> (and probably use the command to replace quick- for spacemacs/ ;)

I don't understand this last part. Do you just mean that if it makes it into a PR to change it from `quick-ex-substitute` to `spacemacs/ex-substitute`?

**Comment by mcp292** [comment]
Ha, what's cool about binding `u`, is that the binding resembles `sub`
```lisp
(spacemacs/set-leader-keys "su" #'quick-ex-substitute)
```

**Comment by dalanicolai** [comment]
@mcp292 Great that you like the idea. The `if (region-active-p)` is working as intended then, namely you can select a region and then the substitute command will work only within that region (similar as in vim). If you would like an option to get the highlighted text inserted also, then you could add that as an extra condition, e.g. when the command is invoked with a prefix (universal argument).

Personally, I thought the `x` mnemonic was well found, first because it is very convenient to type, and second, for me `SPC s` already implies search/replace/sbstitute(/symbol), because I would find it more strange to put replace commands under `SPC r`, or `query-replace` under `SPC q` etc. So I think SPC as be remembered as standing also for substitute. However, indeed a good point can be made for `SPC s u` also, for me it is all the same, as long as it is available somehow.

> I don't understand this last part. Do you just mean that if it makes it into a PR to change it from quick-ex-substitute to spacemacs/ex-substitute?

That's what I meant indeed.

Another option, something that I should do maybe do myself also, is create a personal layer with `personal improvements`, document the improvements well in its README, and then try to evangelize it somehow.
For example, I am using `J/K` to scroll full pages (like in zathura, and now also in Spacemacs in the pdf-tools pdf reader). However, I don't expect Spacemacs to accept this as a 'default' as it is not very `evil`. On the other hand, I would recommend these bindings to anyone, because `J`/`K` are not frequently used bindings in vim (alhough I use J quite frequently, but I have just 'interchanged it to `C-f`).
I have quite a few more handy personal configurations, e.g. for emacs-lisp modes, wrapping a symbol/selection within a `print` form by pressing `, p` etc. So there are multiple possibilities to evangelize these tips and tricks
- keep a literal version of your dotfile (using org-mode) and publish it, but that is somewhat inconvenient when using Spacemacs
- create a separate documented layer, and publish it
- keep a Spacemacs tips&tricks blog

Of course, another option is to create PR's and hope they get accepted. But maintainers, for a good reason, usually have to be somewhat careful/conservative. So for this last option, you must provide really strong arguments for why your PR/new feature is worth merging

**Comment by mcp292** [comment]
> The if (region-active-p) is working as intended then...

I'm glad it's working as intended then! I misunderstood the intention because I'm not familiar with that particular substitute syntax yet.

> Personally, I thought the x mnemonic was well found, first because it is very convenient to type, and second, for me SPC s already implies search/replace/sbstitute(/symbol), ... SPC s can be remembered as standing also for substitute. 

I agree that putting the binding under `SPC s` is intuitive. So far `SPC s u` is becoming very natural for me. I like to think of it as `SPC su(b)`.

> Another option, something that I should maybe do myself also, is create a personal layer with personal improvements, document the improvements well in its README, and then try to evangelize it somehow.

I like this idea. I wouldn't vote to have it come with spacemacs, but I would definitely vote to have a community configs section in the docs that people can draw from, even if just to check syntax. Contributor configs can be prioritized.

**Comment by mcp292** [comment]
Update:  
I think the mark logic needs some work. If I open a buffer and right away issue `SPC s u`, I get:  
```txt
The mark is not set now, so there is no region
```

**Comment by dalanicolai** [comment]
Ah yes... there is some unnecessary code in that function... the following should fix it:
```
(defun quick-ex-substitute ()
  (interactive)
  (if (region-active-p)
      (evil-ex "'<,'>s/"))
  (evil-ex "%s/"))

(spacemacs/set-leader-keys "sx" #'quick-ex-substitute)
```

**Comment by mcp292** [comment]
That fix works!

**Comment by mcp292** [comment]
I'd like to update this thread with two useful features I've found that remediate my cited limitations of `:`:
> And as I mentioned, the ex history is also great, but the fact that it can't be edited through vim bindings, makes it less useful and in most cases quicker to start over than revert to standard emacs bindings or arrow keying. In other words if I could `b b cw` on the ex history, that would justify your point completely and close this issue, but as far as I have seen you can't in the helm buffer. In other words if I could `b b cw` on the ex history, that would justify your point completely and close this issue, but as far as I have seen you can't in the helm buffer. 

The two useful findings:
1. By hitting [`C-f`](https://stackoverflow.com/a/7047701/4682839) in the command buffer, you can type and edit your command using vim bindings. You can also scroll up and hit enter on previous searches to use them, or edit them all the same! From normal mode, this is bound to `q:` for ex and `q/` for search! (Although I can't track these bindings down with `describe-function` (`evil-command-window-ex`, `evil-command-window-search-forward`)).
2. With [`C-r "`](https://stackoverflow.com/a/3997110/4682839) in the command buffer, you can insert from your clipboard.

With that, I will close this issue. Re-open if you see fit.
