### ISSUE TITLE
Cannot undo after expanding Emmet expressions in web-mode. Redo also impossible after attempting undo.

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#1533]
After expanding Emmet expressions using `Tab`, if I press `u` or `Cmd-z` etc. to attempt undo, I'll always get a message `[yas] Snippet n exited` ("n" seems to be the count of how many emmet expansions I've done in the current file), while nothing changes in the buffer. Also after trying to undo I seem to lose all my redo history because it says "no further redo information" upon attempting a redo.

**Comment by dsdshcym** [comment]
I can undo a emmet expand. Are you still running into this issue these days?

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
