### ISSUE TITLE
Cursor acting up in terminal mode 

### ISSUE THREAD

**Issue by pathouse** [syl20bnr/spacemacs#15350]
#### Description :octocat:
extra characters inserted into terminal related to recent change around cursor shapes

git bisect indicates issue was introduced with this PR: https://github.com/syl20bnr/spacemacs/pull/15322

#### Reproduction guide :beetle:
- Start Emacs in terminal mode (iterm2)
  - I run as a daemon with `emacs --daemon` and then start new clients with `emacsclient -t`
- do anything with cursor

*Observed behaviour:* :eyes: :broken_heart:
- extra characters displayed
![image](https://user-images.githubusercontent.com/4028193/153942505-2db42d68-e54b-4377-aafe-657d5daa3832.png)

*Expected behaviour:* :heart: :smile:
- cursor displayed normally

#### System Info :computer:
- OS: darwin
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 0bdddfc16)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(lua sql python systemd yaml auto-completion better-defaults colors csv docker elixir emacs-lisp git go helm html markdown multiple-cursors nginx org react
     (ruby :variables ruby-test-runner 'rspec ruby-version-manager 'rbenv)
     ruby-on-rails
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     syntax-checking terraform themes-megapack
     (treemacs :variables treemacs-use-git-mode 'deferred)
     version-control)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB XIM MODULES THREADS JSON PDUMPER LCMS2 GMP

- Terminal: iTerm2 - Build 3.4.14

---

Other details here - although I have `.spacemacs.env` file where `TERM=xterm-256color` when I use `getenv` to see the value of `TERM` it always returns `dumb`

**Comment by lebensterben** [comment]
@pathouse 
Thanks for reporting.

I didn't see this issue in terminal when I was testing. ( on Linux, the terminal is Alacrity)

Can you try to add "term-cursor" and "evil-terminal-cursor-changer" to excluded-packages and see whether the issue persists?

(It should be evil-terminal-cursor-changer causing the problem but I'm not sure because it acts okay on my system.)

**Comment by pathouse** [comment]
@lebensterben no worries - when reading through the history around these issues i've learned terminals are a bit of a nightmare

yup when i run `M-x evil-terminal-cursor-changer-deactivate` the problem goes away

**Comment by lebensterben** [comment]
Thanks for your reply.
I will try to debug it, or I may revert the changes.

**Comment by lebensterben** [comment]
@pathouse 
Can you try to set environment variable TERM_PROGRAM to iTerm.app?

If you're using .spacemacs.env, you can manually add this entry.

**Comment by pathouse** [comment]
@lebensterben yeah i've been looking into that and something seems to be up w/ env vars being set from my `.spacemacs.env` file

I have the following relevant entries:

```
TERM=xterm-256color
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.4.14
```

`TERM_PROGRAM` and TERM_PROGRAM_VERSION` have the correct values via `getenv` 

but `getenv` for `TERM` always returns `dumb` for me

**Comment by lebensterben** [comment]
@pathouse 

Can you try
- Manually install exec-path-from-shell, by adding it to additional-packages list
- replace [this line](https://github.com/syl20bnr/spacemacs/blob/0bdddfc165a11b5fb2d319bc028b327744186ed5/core/templates/.spacemacs.template#L526) by (exec-path-from-shell)

**Comment by pathouse** [comment]
@lebensterben hm tried that and no luck - getting error when i try to call that function there
`(Spacemacs) Error in dotspacemacs/user-init: Symbol’s function definition is void: exec-path-from-shell-initialize`

**Comment by lebensterben** [comment]
@pathouse 
Okay.

Instead of replacing [this line](https://github.com/syl20bnr/spacemacs/blob/0bdddfc165a11b5fb2d319bc028b327744186ed5/core/templates/.spacemacs.template#L526), comment it out.

And then add (exec-path-from-shell-initialize) in user-config.

(This must work as long as you've added it in dotspacemacs-additional-packages)

**Comment by lebensterben** [comment]
@pathouse 
Thanks.
You can add the package to excluded-packages list for now.
I will investigate.

**Comment by formido** [comment]
I just installed Spacemacs from develop and have the same issue. I don't have a `.spacemacs.env`, though.

**Comment by wujiang** [comment]
I have the same issue when running in iTerm2. After `evil-terminal-cursor-changer-deactivate`, it works fine.
Another observation is that it works fine within tmux inside iTerm2.

**Comment by hrldcpr** [comment]
This is still an issue fyi. (I'm using iTerm2 and emacs editing style.) The fix for me was excluding the package in my spacemacs config, i.e.:

```lisp
dotspacemacs-excluded-packages
'(
  evil-terminal-cursor-changer
  )
```

**Comment by jakshi** [comment]
Just to mention that I have the same issue.

```
   dotspacemacs-excluded-packages '(
       evil-terminal-cursor-changer
   )
```

Fixes the issue for me.

* MacBook Pro 2018
* macOS Monterey
* Emacs 28.1
* Spacemacs branch: Tip of develop
* Built-in and 4K external displays
* Editing style: Emacs
* Terminal: iterm2 (Build 3.4.4)

**Comment by Decoherence** [comment]
A big thank you to everyone who's worked on this issue (and @hrldcpr for the suggestion!). I've been trying to track this down for a bit, digging into the lovely complexities of terminals 😎. 

The issue occurs in iTerm and the built-in Terminal app, using either zsh or bash.

I figured it could be related to changing editor states since the characters resembled hex color codes (or repeated sequences of hex codes). 

`dotspacemacs-excluded-packages '(evil-terminal-cursor-changer)` did the trick for now.

- MacBook Pro (16-inch, 2021) on latest Monterrey
- Emacs 28.0.60
- iTerm Build 3.4.15
- Spacemacs tip of develop (rev. [b3e67aa](https://github.com/syl20bnr/spacemacs/commit/b3e67aafe2451ca91e2d310d29879616e10981d0))

**Comment by hrldcpr** [comment]
I just tried this again (i.e. pulled the latest `develop` and removed the `dotspacemacs-excluded-packages` fix) and it seems like it's no longer an issue!

@pathouse want to see if it's fixed for you too, and if so close this issue?

**Comment by jakshi** [comment]
Just wanted to confirm that that issue is not appear anymore with latest develop branch spacemacs.
