### ISSUE TITLE
How to change cursor type to bar in Evil-emacs-state

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#1543]
I could use  (setq-default cursor-type 'bar) to change the cursor style to bar, but in spacemacs, the settings is not working.

How to get rid of it?

Thanks.

**Comment by syl20bnr** [comment]
I have to work on this, right now it is not so easy to do it.

**Comment by andyque** [comment]
@syl20bnr  Thanks

**Comment by sooheon** [comment]
Some kind of flexibily within evil-mode would be good as well. For example, some people prefer to keep the rod shape in insert mode (if the colors are good enough to distinguish).

**Comment by dzhwinter** [comment]
@zilongshanren  Have you solved it? I find it may be cause by zsh...

**Comment by bmag** [comment]
How about this?
```elisp
(setq evil-emacs-state-cursor '("SkyBlue2" bar))
```
I recently discovered evil has a brief manual, which is very helpful for customizing evil-related stuff, you should check it out. It's available from evil's page on bitbucket.

**Comment by dzhwinter** [comment]
Still not work. I checked my system again and I found that It have the same situation even in pure vim. It's caused by terminator simulator.

**Comment by qqldd** [comment]
I also have this problem with new installed spacemacs. With the spacemacs upgrade from April on another machine, the cursor in terminal is still bar. But with the new installed spacemacs, it becomes hbar.

**Comment by dzhwinter** [comment]
my problem was solved when  I reboot my machine on one occasion. As a programmer, it seems stupid, but solved my problem and I don't know the reason....

**Comment by qqldd** [comment]
I found after upgrading to 0.103.6, all machines' emacs has hbar cursor and I cannot change it. 

@dzhwinter  I cannot reboot the machines as they are servers. :(

**Comment by zilongshanren** [comment]
I found a solution:

```
  (setq evil-emacs-state-cursor '("chartreuse3" (bar . 2)))
```

**Comment by NightMachinary** [comment]
Unfortunately, ` (setq evil-emacs-state-cursor '("chartreuse3" (bar . 2)))` has no effects whatsoever for me. :(
What can I do to use a bar cursor in insert mode?

**Comment by NightMachinary** [comment]
@syl20bnr Can you reopen this, please?

**Comment by duianto** [comment]
@NightMachinary That command works for me on both the master and develop branches.

I didn't think it worked at first, because `chartreuse3` and `(bar . 2)` looks the same as the default evil insert state cursor, but then I remembered that I was in emacs state and it's supposed to be a blue box. 😄 

The default value of the `evil-emacs-state-cursor` variable, is: `("SkyBlue2" box)`.

This makes it more obvious that the `C-z` emacs state cursor has changed.
```
(setq evil-emacs-state-cursor '("white" (bar . 4)))
```

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey helm auto-completion emacs-lisp git html org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES
