### ISSUE TITLE
tracking issue: replace volatile-highlight by evil-goggles

### ISSUE THREAD

**Issue by lebensterben** [syl20bnr/spacemacs#15441]
As pointed out [here](https://github.com/syl20bnr/spacemacs/issues/15437#issuecomment-1086281828), vhs is too old and not implemented in a clean way.

I propose to replace it by [evil-goggles](https://github.com/edkolev/evil-goggles/tree/8f20a16e74016f37ad76dc4f2230d9b00c6df3c2).

**Comment by lebensterben** [comment]
feel free to make a PR if anyone is interested in it. this should be fairly straightforward and easy.

**Comment by thanhvg** [comment]
Just to make sure we have enough info here:
`evil-goggles` comes with Spacemacs already, but it is not turned of by default. All you need to do is set `vim-style-visual-feedback t`

**Comment by lebensterben** [comment]
@thanhvg 
It should not be placed inside vim layer in my opinion. It should be turned on for all evil user by default.

**Comment by emacs18** [comment]
I just discovered that volatile-highlights caused many problems for me.   

I got fed up with 'd d' bound to evil-delete taking minimum 3 seconds, that I took a closer look.  It turned out to be volatile-highlights!  After I disable it, 'd d' is now as fast as kill-line.

Also I could not figure out for years why removing thousands of lines from shell buffer hosed emacs.
It also turned out to be volatile-highlights!   For years I had to limit myself to removing only about a thousand lines or so to avoid this problem.  If I forgot this and tried to remove many thousands of lines in shell buffer, then emacs would hose.  Repeated Control-G may or may not wake up emacs!  This is the reason why I looked for and learned about "pkill -USR2 emacs" to wake up emacs.  I did not have to know such hack during my first 30 years of emacs use.  It is only after using spacemacs that I managed to hose emacs like this.

This is just one of many "features" that spacemacs enable by default that makes emacs unusable running on linux servers with NFS disks.  I also have to disable projectile mode completely to prevent emacs from hosing.  Another way to hose emacs is to type "/u/" within shell buffer to make emacs go to sleep for 10 seconds or more.  This is because it tries to complete all the names under /u/ directory which has tens of thousands of entries!

**Comment by emacs18** [comment]
If I submit a PR which removes volatile-highlights, would that be accepted?
I don't know anything about the alternatives such as evil-goggles mentioned above.

**Comment by lebensterben** [comment]
@emacs18 

https://github.com/edkolev/evil-goggles

evil-goggles requires minimal setup. Since I plan to add it, I suggest to try it out to see whether it also has performance issue on your device.

**Comment by emacs18** [comment]
I set `vim-style-visual-feedback` to `t`, restarted emacs, and verified that `evil-goggles-mode` was `t`.  I removed lines via `d d` as well as over 100 thousand lines in my *shell* buffer.  All seemed well.

**Comment by lebensterben** [comment]
@emacs18 

Great to hear that. You can go ahead and submit to PR to remove volatile-highlight.

(Optionally you can replace it by evil-goggles. If you didn't I will add it later.)

**Comment by emacs18** [comment]
Removing volatile-highlight is easy.  I don't know what you mean by replacing it with evil-goggles.   evil-goggles is already a user option via `vim-style-visual-feedback`.  If you mean to replacing with evil-goggles that `vim-style-visual-feedback` should be set to `t`, then I'm not sure that is wise.

**Comment by lebensterben** [comment]
@emacs18 

volatile-highlight is enabled for are users while evil-goggles is disabled by default and only works for evil users.

By "replacing volatile-highlight by evil-goggles" I mean:
- Make evil-goggles default for evil users
- Try to achieve feature parity, which is mainly `undo-tree` commands that we configured for volatille-highlight but it's not supported by evil-googles. This seems to be easily doable by modifying https://github.com/edkolev/evil-goggles/blob/8f20a16e74016f37ad76dc4f2230d9b00c6df3c2/evil-goggles.el#L572 and defining some faces.

**Comment by emacs18** [comment]
Sorry.  I don't understand.  This is an area I don't know much about.
