### ISSUE TITLE
Want Help On Snippet Resource

### ISSUE THREAD

**Issue by louy2** [syl20bnr/spacemacs#1558]
After `rgrep` the `.emacs.d` folder and find no snippet, I finally realize spacemacs doesn't provide any out of the box. What are some nice resource that the community can recommend? I am looking for JS and CSS resource as complete as found in browser console, but others are welcome as well.

And maybe we should have a section in doc dedicated to this. Good snippets are very instructional and aligns with the purpose of newbie-friendly.

**Comment by tuhdo** [comment]
Spacemacs does provide `yasnippet`. It's just you must include `auto-completion` layer before using it.

**Comment by louy2** [comment]
I know, I have them enabled. But I haven't noticed any default snippets coming into play when I'm coding yet.

**Comment by tuhdo** [comment]
The snippets should be in `elpa/yasnippet-<version>/snippets` directory. Try checking for `yasnippet` directory in `elpa`. There should be a `snippets` directory there. You should try checking variable `yas-snippet-dirs` to see where the default snippet directory is. But your issue probably related to this issue: https://github.com/syl20bnr/spacemacs/issues/1553

**Comment by louy2** [comment]
OK... now I am pretty sure the default css snippets are not what I expect. What's your experience with snippets?

**Comment by liujoey** [comment]
:+1: when I first try to expand `def` in python, it gave me nothing, so I thought the yasnippet was not working, I even asked it on chat. And then I realized that it could be my fault using a wrong trigger sequence. So I opened the snippets folder to check out what exactly laid in it, you know what? In order to expand `def` in python, you have to type `dec` as the trigger! What the h*ll?
So yes, snippets definitions are very confusing. If we could have valid sequences listed in auto-complete list, it would be very help for a beginner.

**Comment by tuhdo** [comment]
You could list all available snippets with `helm-yas-complete`.

**Comment by liujoey** [comment]
I think listing available snippets is a good fit for the auto-complete. I type first few char like `de` and the popup shows `dec   [snippet]` sort of thing. Why bother to `M-x helm-yas-complete` while we already have auto-complete?

**Comment by tuhdo** [comment]
Because mixing snippet expand with regular completion could be annoying when you just want to complete and it expands instead. For example, when I narrow to a candidate like `define-and-set` in Emacs lisp, I know such prefix is the unique one or a few and I want to quickly press `TAB` to complete. Unfortunately, `set` is part of a snippet so it expands instead of complete and I have to undo and type a few more characters.

The correct way to do it:

- Use `helm-yas-complete` to explore all available snippets in the mode you are new.
- Once you remember a snippet, next time if you want to expand that snippet, type the prefix then press `M-/` or `C-p`.

**Comment by mkcode** [comment]
@louy2 - We include https://github.com/AndreaCrotti/yasnippet-snippets as a submodule in this project. Did you `git submodule sync; git submodule update` in the spacemacs repo?

**Comment by mkcode** [comment]
Actually - looks like we have some redundancy here with https://github.com/AndreaCrotti/yasnippet-snippets being a submodule in both the elpa/yasnipptet*/snippets and being defined here in .gitmodules: https://github.com/syl20bnr/spacemacs/blob/c39f6e4b98391b780bea2caa3f458fca3eeafacb/.gitmodules#L22-L24

**Comment by mkcode** [comment]
Opened #1566 for this issue.

**Comment by liujoey** [comment]
@tuhdo you misunderstand my point,  I didn't say we should use TAB for expand,  I'm just saying we list available snippets in the list, use tab to cycle the list, use RET to complete, and use M-/ to expand the snippets. There's no conflicts.

**Comment by louy2** [comment]
@tuhdo @liujoey Basically using yasnippet as a backend of ac and company. I belive it is supported, just a bit lost in how to enable.

**Comment by TheBB** [comment]
We now have `auto-completion-enable-snippets-in-popup` that should fix this.
