### ISSUE TITLE
undo-tree changed Treemacs layout when move history cursor

### ISSUE THREAD

**Issue by godshen1** [syl20bnr/spacemacs#15592]
When I use Spacemacs with the Treemacs feature inside it, like the picture, I opened it by Alt Shift m + p + t

![](https://camo.githubusercontent.com/c2b132440f049f8e1867e69cc07c61d60c566a751e5183581f67e938120ca7ef/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f6b576f6f7a2e706e67)

Then use Ctrl x + u to open undo-tree

![](https://camo.githubusercontent.com/88d0bb078e1159aac58a8c036e0cf450342a4a00c135abc1f48041c508935aa8/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f314f5948332e706e67)

When I move the cursor on the undo-tree by Ctrl + p, the layout had been resized

![](https://camo.githubusercontent.com/828ed97875c22d6059b0ef58fd29146cef68f1c2cc9989fc80346eaa74904132/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f46593555662e706e67)

Even I close the undo-tree window, the layout didn't back to the first picture.

![](https://camo.githubusercontent.com/0367db684a905aa36094d14c4d90f49485e870c07e2963be628b621c55f7cabc/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f624f726a452e706e67)

Why it happened? How to avoid it?

**Comment by dCaples** [comment]
Okay looked into the source code of `undo-tree` and `treemacs`, and it turns out, the issue is with `undo-tree`. You see, when you change undo version in the undo tree, it calls the `(balance-windows)` function. The reason this is called is to resize the undo-tree Diff to fit all of its contents. However, instead of balancing the parent window of the undo-tree sub-windows, it instead balances all of the windows in your emacs frame! This is what resizes treemacs. To temporarily fix the issue, open `undo-tree.el` (in my case located at `~/.emacs.d/elpa/27.1/develop/undo-tree-0.8.2/undo-tree.el`) and edit the line that says `(balance-windows)`. Replace it with `(balance-windows (window-parent win))` This will get overwritten when `undo-tree` updates, but I will submit a pull request to undo-tree fixing this issue. Hope this was helpful!
-Diego

**Comment by lebensterben** [comment]
@dCaples thanks for investigating.

**Comment by dCaples** [comment]
I made a pull request upstream, so hopefully this should be fixed soon!

**Comment by dCaples** [comment]
Undo-tree's GitLab repo doesn't allow pull requests, and its maintainer's website says to email pull requests, but the email it says to mail to is invalid, so I found his email in the elpa undo-tree page and sent him an email with the pull request, but it has been a very long time with no response and the request hasn't been merged. What should I do?

**Comment by lebensterben** [comment]
@dCaples 

Let's wait....

**Comment by lebensterben** [comment]
@dCaples what email have you used?

I found two:

toby+undo-tree@dr-qubit.org

toby-undo-tree@dr-qubit.org

**Comment by dCaples** [comment]
I sent it to both. The second one (toby-undo-tree@dr-qubit.org) never sent me a confirmation email, and gmail said it couldn't send the email, but the first email worked. I never got a response though.
