### ISSUE TITLE
how to update spacemacs in local PC using git?

### ISSUE THREAD

**Issue by zhumingpassional** [syl20bnr/spacemacs#15642]
If spacemacs has updated its codes, how to update spacemacs in local PC using git after the first git clone? 

could you pls provide the commands? I am not familiar with git, and only know several common git commands.

thanks very much.

I tried the following commands, but failed.
$ git checkout develop
$ git remote -v
$ git fetch upstream
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
$ git merge upstream/develop
merge: upstream/develop - not something we can merge

could tell me the reason?

**Comment by BenedictHW** [comment]
Is the upstream remote configured properly?

``` shell
ben@BHW-THINKPAD:~/.emacs.d/.git/magit/posts$ git remote -v
origin	git@github.com:BenedictHW/spacemacs.git (fetch)
origin	git@github.com:BenedictHW/spacemacs.git (push)
upstream	https://github.com/syl20bnr/spacemacs (fetch)
upstream	https://github.com/syl20bnr/spacemacs (push)
```

You are right that fetching updates from upstream is a operation general to git.
Instead of piecing together knowledge from forum scraps and informal word of
mouth I recommend https://git-scm.com/book/en/v2

After having a working knowledge, the fruit of your labour will be rewarded with
the Emacs pearl that is magit. https://github.com/magit/magit

Or its incarnation as a spacemacs layer
https://develop.spacemacs.org/layers/+source-control/git/README.html

Good luck,

**Comment by lebensterben** [comment]
`git pull --rebase`.
