### ISSUE TITLE
New helm backspace behavior and renaming of files

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#1583]
With the new backspace behavior #1524 it is hard to rename a file `SPC f R`.

**Comment by CestDiego** [comment]
^ this. We should instead embrace `C-l` to go up a directory

**Comment by mbertheau** [comment]
My take on this:

1. <kbd>&lt;backspace&gt;</kbd> in vim, emacs and most everywhere else deletes one character backwards. I don't know about ido. Making it delete a whole path component is surprising **and** destructive, since you lose the path that was there.
2. <kbd>&lt;left&gt;</kbd> moves the point to the left in vim prompts, some emacs prompts and most everywhere else. I don't know about ido. Making it delete a whole path component is even more surprising, since <kbd>&lt;left&gt;</kbd> usually doesn't delete text.

I have seen helm being praised, but since I moved to spacemacs maybe a month ago, helm has been one of the frustrating parts of the experience :/

**Comment by cpaulik** [comment]
:+1: for deleting characters with backspace

**Comment by agzam** [comment]
:+1: for one character at a time, and `C-backspace` of `S-backspace` for deleting word by word

**Comment by yangj1e** [comment]
I am annoyed by this behavior as well. Backspace should delete one character at a time.

**Comment by TheBB** [comment]
This isn't a problem any more.

**Comment by yarray** [comment]
Sorry for bothering but is this problem fixed now? It seems backspace now works as expected but left/right key remains the same.

Also the I had a hard time with the Neotree rename-mode. Besides the left/right problem, the file name of target node will not appear, which is quite inconvenient since most time renaming involves only minor corrections. Should I open a new issue for this?
