### ISSUE TITLE
haskell-yas: no such file or directory

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#1595]
At startup: `An error occurred while initializing haskell-mode (error: (file-error Cannot open load file no such file or directory haskell-yas))`

**Comment by oneeman** [comment]
I was getting this today, too.  Pulling the latest version of the master branch fixed it for me.  See https://github.com/syl20bnr/spacemacs/issues/1471

**Comment by syl20bnr** [comment]
@xged did updating to 0.101.4 fix your issue ?

**Comment by Skyfold** [comment]
Same issue and I'm on Release 0.101.x
Not sure how to find out what (x) it is.

**Comment by jasoncyu** [comment]
@Skyfold Go to your ~/.emacs.d folder. What commit are you on (i.e. do a git log and look up the sha hash of the current commit)

**Comment by Skyfold** [comment]
commit 1ab88419096eda428c19e876d6ea0bdf2b5c1e4e on the 23rd of April is the current commit I'm on. I noticed that when I fallback to a working version the commit stays the same. When I update I end up with the above error and DogeMacs is displayed instead of Spacemacs. Strangely, after updating, spacemacs says there is a new version (0.101.4), but when I update again it says "All packages are up to date".

**Comment by xged** [comment]
Update fixed my issue
