### ISSUE TITLE
Deprecate importmagic for python-import-symbol-at-point

### ISSUE THREAD

**Issue by jgarte** [syl20bnr/spacemacs#15952]
Hi,

Emacs now has built in functionality for importing python symbols automatically.

I think we should switch to [python-import-symbol-at-point](https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/python.el#L6483) instead of using the third party library [importmagic](https://github.com/syl20bnr/spacemacs/search?q=importmagic).

The built in emacs function works flawlessly unlike importmagic.

What do you think?

**Comment by emacs18** [comment]
This seems to be too eary for two reasons.  One this seems to be available only on emacs 28 and later.  Two this is too flaky.  
I tried it on emacs 29 and ran into this error:  `helm-M-x-execute-command: Doing vfork: Argument list too long`

This happened when I created a test file in my home directory on linux.  The problem is that `python--import-sources` return value was 15 mega bytes, and emacs tried to pass this as an argument to python sub-process.  It looks like this lacks some basic checks such as making sure that the command line length is not too long before attempting to launch python sub-process!

**Comment by jgarte** [comment]
`python-import-symbol-at-point` works great for me with [vertico](https://github.com/minad/vertico)/consult ™️ 

I've been using it daily. I haven't run into any issues yet but then again, I'm not using helm in my setup.

**Comment by emacs18** [comment]
The problem is not related with helm vs ivy.  The problem is with `project-files` which may work fine for most projects, but utterly fails when one happens to try to edit a python file in a high level directory which has many other sub-directories with other projects.

**Comment by emacs18** [comment]
Minimally emacs should have a check so that it does not lauch a subprocess when the command line argument is too large, e.g., more than 4k or 8k bytes or whatever the limit dictated by the OS.  Following is the code in question:
```elisp
(defun python--import-sources ()
  "List files containing Python imports that may be useful in the current buffer."
  (if-let (((featurep 'project))        ;For compatibility with Emacs < 26
           (proj (project-current)))
      (seq-filter (lambda (s) (string-match-p "\\.py[iwx]?\\'" s))
                  (project-files proj))
    (list default-directory)))
```
The flawed logic here is that `project-files` is called without any checks on amount of data it could generate.  Following shows that under my home directory, there are 148,402 python files and just the number of bytes taken up by these file names is over 13 MB.  Emacs attempts to pass these 13 MB as a single command line argument to python sub-process!

```shell
$ cd
$ find . -name '*.py' | wc
  148402 13662160
$
```

**Comment by smile13241324** [comment]
I agree with @emacs18 as long as the build in emacs module is not able to work with enterprise grade python projects we should not move to it. Also many of our users are still using emacs 28.X which does not come with the necessary module so a change is not possible at the moment.

When the minimum version of emacs is set to 29.X in Spacemacs we can start this discussion again.
