### ISSUE TITLE
Non Asynchronous Spacemacs Update

### ISSUE THREAD

**Issue by vaneda** [syl20bnr/spacemacs#1599]
I have been noticing that the spacemacs update function that displays `'Start checking for new version'` is now blocking rather than asynchronous on the dev channel. It runs about every 6 hours of uptime and completely halts the editor until it finishes. Is anyone else noticing this issue?

Emacs Build `24.5.1`
OS `Windows 7` 
Spacemacs Build `0.102.0`

**Comment by StreakyCobra** [comment]
@vaneda Do you still have this issue on the last spacemacs release with the packages updated?

**Comment by howdoicomputer** [comment]
I'm noticing this as well. Emacs locks up and I can't do anything if version checking does not succeed.

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.

@howdoicomputer As this kind of issue is installation specific and this one is pretty old, its probably not related to yours. Please open a new issue for your problem, it will also offer it more visibility (and more help at the same time) :-)
