### ISSUE TITLE
error with python layer

### ISSUE THREAD

**Issue by ebynapura** [syl20bnr/spacemacs#16012]
when i run `.py` file, or run `python` cmd in eshell or powershell mode, it doesn't work, and i check the warnings buffer like this:

Warning (python): Python shell prompts cannot be detected.
If your emacs session hangs when starting python shells
recover with ‘keyboard-quit’ and then try fixing the
interactive flag for your interpreter by adjusting the
‘python-shell-interpreter-interactive-arg’ or add regexps
matching shell prompts in the directory-local friendly vars:
  + ‘python-shell-prompt-regexp’
  + ‘python-shell-prompt-block-regexp’
  + ‘python-shell-prompt-output-regexp’
Or alternatively in:
  + ‘python-shell-prompt-input-regexps’
  + ‘python-shell-prompt-output-regexps’ Disable showing Disable logging

**Comment by ebynapura** [comment]
sth wrong about the interpreter setup, but i don't understand why, need help please~

**Comment by sunlin7** [comment]
What's the output for  `which python` or `which python3` in your eshell ?

**Comment by ebynapura** [comment]
```
e:/code $ which python
d:/Program Files (x86)/python/python.exe
e:/code $ which python3
c:/Users/xxx/AppData/Local/Microsoft/WindowsApps/python3.exe
```

**Comment by sunlin7** [comment]
Please refer the https://github.com/jorgenschaefer/elpy/issues/733 maybe can resolve the warning in your side.

**Comment by smile13241324** [comment]
Hi :),

I have tried to find out whether there is a general issue with Spacemacs and the python interpreter setup but it looks to be working fine, even with the ancient eshell.

I am afraid that the issues you are seeing are related to your OS environment rather than Spacemacs and have to be fixed there. From my personal experience I can say that emacs will most likely never run fine on Windows, your best bet is to move to WSL2 and run emacs in the Linux environment there.

Anyway I am going to close this as not related to the project for now.

mfg
Maxi
