### ISSUE TITLE
Unable to completely disable smartparens mode globally

### ISSUE THREAD

**Issue by adamflott** [syl20bnr/spacemacs#1603]
I do not like smartparens mode in any shape or form, but when I try to disable the mode globally it re-enables itself. For example, it appears in markdown-mode. Including it in the excluded-packages variable didn't help either.

The relevant items from my ~/.spacemacs

```elisp
(defun dotspacemacs/layers ()
  "Configuration Layers declaration."
  (setq-default
   ;; List of additional paths where to look for configuration layers.
   ;; Paths must have a trailing slash (ie. `~/.mycontribs/')
   dotspacemacs-configuration-layer-path '()
   ;; List of configuration layers to load. If it is the symbol `all' instead
   ;; of a list then all discovered layers will be installed.
   dotspacemacs-configuration-layers
   '(
     auctex
     auto-completion
     better-defaults
     colors
     (git :variables
           git-gutter-use-fringe t)
     go
     haskell
     markdown
     syntax-checking
     themes-megapack
     )
   ;; A list of packages and/or extensions that will not be install and loaded.
   dotspacemacs-excluded-packages '(smartparens)
   ;; If non-nil spacemacs will delete any orphan packages, i.e. packages that
   ;; are declared in a layer which is not a member of
   ;; the list `dotspacemacs-configuration-layers'
   dotspacemacs-delete-orphan-packages t))
```

...

```elisp
(defun dotspacemacs/config ()
  "Configuration function.
 This function is called at the very end of Spacemacs initialization after
layers configuration."
  (progn
    (global-linum-mode)
    (smartparens-mode -1)
    (smartparens-global-mode -1))
)
```

**Comment by trishume** [comment]
This may be a bug in the exclusion mechanism but probably what you actually want to do is disable it activating on most pairs. See this commented out section of my config:

https://github.com/trishume/dotfiles/blob/master/emacs%2B/spacemacs.symlink#L136

**Comment by adamflott** [comment]
@trishume Thanks! Had some other gems in there too

**Comment by hamhut1066** [comment]
Has there been any progress on this? currently electric-mode and smartparens are in conflict.

I'm using the above config, and it doesn't seem to be working. @trishume could you point to the specific SHA where your above comment was relevant?

**Comment by trishume** [comment]
Here's the code to disable smartparens for most pairs: https://github.com/trishume/dotfiles/blob/4bd506c057ec27f064769a96937be92d1a825f3a/emacs%2B/spacemacs.symlink#L110

**Comment by mkollaro** [comment]
I found a better [solution](http://emacs.stackexchange.com/q/16935/10462) - add `smartparens` to the `dotspacemacs-excluded-packages` list in `.spacemacs`.

**Comment by jluttine** [comment]
Just wanted to point out that if you exclude `smartparens`, you'll lose some features you might be interested in. For instance, it disables `SPC j n` which I like even though I don't like automatic closing parentheses. So depending on your preferences and what you hate in `smartparens`, you may want to just add `(spacemacs/toggle-smartparens-globally-off)` to your `dotspacemacs/user-config` in `.spacemacs` instead of excluding the package. But if you hate everything in `smartparens`, then just exclude the whole package.

**Comment by jluttine** [comment]
I'm sorry but I don't understand why setting `(spacemacs/toggle-smartparens-globally-off)` `dotspacemacs/user-config` in `.spacemacs` doesn't work. If I understood docs correctly, it should disable the mode globally, but it doesn't. Have I misunderstood something or is it a bug?

**Comment by adamflott** [comment]
It's no longer an issue. I've had `dotspacemacs-excluded-packages '(smartparens)` and happy

**Comment by jluttine** [comment]
But I don't want to exclude the package so I'm not happy. :smile: 

So is it a bug or am I doing something wrong?

**Comment by TheBB** [comment]
`smartparens-mode` is a local mode that enables smartparens features in a single buffer.

`smartparens-global-mode` is a global mode. If it is enabled you get `smartparens-mode` in every buffer. Turning it off does **not** prevent you from turning on `smartparens-mode` anywhere. (That would be silly, because if that were true there would be no way to selectively enable smartparens. It would be either everywhere or nowhere, depending on that mode.) In fact `smartparens-global-mode` is off by default already.

Spacemacs enables `smartparens-mode` in all programming buffers by switching it on in the hook. Therefore you have to remove the function from `prog-mode-hook`.

[@NJBS](https://gitter.im/syl20bnr/spacemacs?at=571a54ed0eef754b5ea98cc9) told you how to do that.

**Comment by jluttine** [comment]
Yes, thanks! I got it working. Just for reference if someone else is interested: Put these lines into `dotspacemacs/user-config` in `.spacemacs`:
```
  (remove-hook 'prog-mode-hook #'smartparens-mode)
  (spacemacs/toggle-smartparens-globally-off)
```
I suppose the latter line isn't even necessary because it is globally disabled by default anyway. Thanks, this is great!

**Comment by razzmatazz** [comment]
I am not sure what is it that `spacemacs/toggle-smartparens-globally-off` does on the latest/development branch but it definitely doesn't "toggle smartparens globally off" :(

This is my script from `dotspacemacs/user-config` that fights it off with some success in shell and prog modes:
```
  (remove-hook 'prog-mode-hook #'smartparens-mode #'show-smartparens-mode)
  (spacemacs/toggle-smartparens-globally-off)

  (add-hook 'shell-mode-hook (lambda () (progn (smartparens-mode 0)
                                               (show-smartparens-mode 0))))
```

**Comment by beyondpie** [comment]
put `smartparens` in spacemacs exclude packages not work for me.  I use develop branch and emacs version 28.0.5, and spacemacs will reinstall smartparens.

**Comment by beyondpie** [comment]
also
`
 (remove-hook 'prog-mode-hook #'smartparens-mode)
  (spacemacs/toggle-smartparens-globally-off)
`
not work for me.  
spacemacs has error: 
`(Spacemacs) Error in dotspacemacs/user-init: Symbol’s function definition is void: spacemacs/toggle-smartparens-globally-off
`

**Comment by duianto** [comment]
>(Spacemacs) Error in dotspacemacs/user-init: Symbol’s function definition is void: spacemacs/toggle-smartparens-globally-off

Your getting that error because the `spacemacs/toggle-smartparens-globally-off` function hasn't been defined yet when it's called from the `dotspacemacs/user-init` section.

Add the snippet to the `dotspacemacs/user-config` section instead.

The `dotspacemacs/user-init` sections is for configurations that need to be applied before the layers and packages are loaded, as described in the user-init docstring:
>(defun dotspacemacs/user-init ()
  "Initialization for user code:
This function is called immediately after \`dotspacemacs/init', before layer
configuration.
It is mostly for variables that should be set before packages are loaded.
If you are unsure, try setting them in `dotspacemacs/user-config' first."
