### ISSUE TITLE
Python layer: activated virtual environment is ignored when starting the REPL

### ISSUE THREAD

**Issue by elatomo** [syl20bnr/spacemacs#16044]
#### Description :octocat:

When starting a python REPL from an activated virtual environment, the default Python interpreter is used instead of the defined in the virtual environment.

#### Reproduction guide :beetle:
- Start Emacs
- Open a python file
- Activate a virtual environment (`pyvenv-workon`)
- Start the REPL (`spacemacs/start-or-switch-repl`)

*Observed behaviour:* :eyes: :broken_heart:
- Even though the `PATH` contains the virtual environment (`getenv PATH`), the Python interpreter used is the default Python interpreter in the system instead of the one defined in the virtual environment.

*Expected behaviour:* :heart: :smile:
- The Python interpreter launched is the one defined in the virtual environment  (the `PATH` is respected). 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. d0d014160)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp common-lisp
                 (python :variables python-test-runner 'pytest python-formatter 'black)
                 (typescript :variables typescript-indent-level 2)
                 rust git helm markdown yaml html docker
                 (org :variables org-want-todo-bindings t)
                 (shell :variables shell-default-shell 'vterm shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking treemacs emoji)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

**Comment by elatomo** [comment]
I took a quick look to the commit history, and it appears that https://github.com/syl20bnr/spacemacs/commit/cd0eeb9f7bbcc8a752bb344e751aa31a70dc06a6 is potentially causing the issue. To confirm this, I performed a local revert of the change, and the Python REPL now launches properly without any issues.

**Comment by ghost** [comment]
This issue is a problem for me. At present, I am using the last commit without it, https://github.com/syl20bnr/spacemacs/commit/ecf1d32c0cd9489700c0a0578fed600a8471bd90.

**Comment by TheDohn** [comment]
Using `git bisect` I agree that (https://github.com/syl20bnr/spacemacs/commit/cd0eeb9f7bbcc8a752bb344e751aa31a70dc06a6) appears to be the problem.

**Comment by ghost** [comment]
I too used `git bisect` to determine that https://github.com/syl20bnr/spacemacs/commit/cd0eeb9f7bbcc8a752bb344e751aa31a70dc06a6 is the first commit with this issue.

**Comment by TheDohn** [comment]
So this isn't sexy but I just essentially fixed that code back to the way it was locally and that fixes the issue. I just stash and pop those changes onto the develop branch when I pull until this is fixed. I don't know enough lisp to fix this properly right now, but I might take a swing at it at some point if there isn't a better solution.

**Comment by sfalmo** [comment]
This also affects conda and presumably any other form of virtual environment.

I think the problem of the current code is that the python interpreter is set once to the absolute path of the system python. See in particular the following function, which is called in `init-python`, i.e. when entering python-mode:

https://github.com/syl20bnr/spacemacs/blob/d813a33c80e8f9bd0788c0c0caa68d189c9833e2/layers/%2Blang/python/funcs.el#L153-L175

To my understanding, this function should check if `ipython` is available and if so, select it instead of the standard `python`, as specified in the docs (https://develop.spacemacs.org/layers/+lang/python/README.html#inferior-repl-process). But notice that once this function is called outside of an environment, `python-shell-interpreter` is set to the absolute path of the system python (usually `/usr/bin/python`). Further calls will not change `python-shell-interpreter` due to the first `when` clause, even if an environment has been activated in the meantime. Apart from that, the function is not even called when activating a virtual environment.

I think the best solution would be to reduce the logic of this function to a minimum and let the environment choose the correct python interpreter.

Maybe @sunlin7 can help out as he wrote the above function.

**Comment by sunlin7** [comment]
Background:  The https://github.com/syl20bnr/spacemacs/commit/cd0eeb9f7bbcc8a752bb344e751aa31a70dc06a6 was commited in https://github.com/syl20bnr/spacemacs/pull/16011, 
It try to fix these two issues:  
https://github.com/syl20bnr/spacemacs/issues/16001
https://github.com/syl20bnr/spacemacs/issues/15873

I'll check these scenaris together.

**Comment by sunlin7** [comment]
Hi @elatomo @TheDohn 
Could you help verify the solution in #16074 ?
As @sfalmo  mentioned the potential bug in his comment that the absolute path or `ipython` will always different with the original `python-shell-interpreter` and treated as customer value and then the local value never be used.

**Comment by ghost** [comment]
The problem is gone; thank you, @sunlin7. This issue ought to be closed.

**Comment by TheDohn** [comment]
This still seems to be a problem for me when using a conda environment. I will look into it more when I have time.

**Comment by sunlin7** [comment]
Look forwording your update. Thanks

**Comment by TheDohn** [comment]
So just to describe my issue a bit more:  if I activate a conda env in Spacemacs (`conda-env-activate`), then open a python REPL (`spacemacs/python-start-or-switch-repl`) it can't find any of the libraries - it says stuff like "ModuleNotFoundError: No module named..." even though when I evaluate `print(os.getenv('CONDA_PREFIX'))` that points to the correct conda env. I can also activate that env at the command line and python finds the libraries fine (so I am not doing anything too stupid, the libraries are indeed installed in the conda env).

I am 99% sure it has to do with that `python/init-python` function in layers/+lang/python/packages.el. Prior to some recent commits (which I haven't identified) I was able to just manually undo the changes in commit `cd0eeb9` and it would work. Now that function has gone through some other changes and I can't just apply that duct tape - I need to completely comment out the function `python/init-python` and replace it with the version from prior to the `cd0eeb9` commit since the changes to that function are larger.

I am not sure how to diagnose or narrow down the problem I am having any further given my knowledge of lisp and python. Are there other tests I can run or information I can provide that would help me articulate the issue?

**Comment by sunlin7** [comment]
Can you cherry-pick the https://github.com/syl20bnr/spacemacs/commit/52c5715da076940b8c04658f4b899c2ae60a08a5 and give a try?
If it dosen't work for you, please observe the variable `python-shell-interpreter` for worked one and non-worked one, that's maybe can help me to understand the issue.

**Comment by elatomo** [comment]
> Hi @elatomo @TheDohn Could you help verify the solution in #16074 ? As @sfalmo mentioned the potential bug in his comment that the absolute path or `ipython` will always different with the original `python-shell-interpreter` and treated as customer value and then the local value never be used.

Hi @sunlin7! https://github.com/syl20bnr/spacemacs/pull/16074 works great for me, thanks!

**Comment by TheDohn** [comment]
@sunlin7 ~I am a bit confused (sorry!) isn't `52c5715` on the develop branch? In which case if I am up-to-date on develop I should have those changes incorporated right?~

So I am not clear what cherry picking would do, so I just checked out that specific commit, and unfortunately the problem persists for me. Are there any other tests I can run or information I can provide? I am wondering if the problem is unique to me using conda since other people here might have been using another virtual environment tool.

**Comment by sunlin7** [comment]
> please observe the variable python-shell-interpreter for worked one and non-worked one, that's maybe can help me to understand the issue.

**Comment by TheDohn** [comment]
Ah sorry, I clearly didn't read your original message completely. When I evaluate `python-shell-interpreter` in the two cases:
- Working case (on the most recent commit `4882f70e6` and I manually replace the function `python/init-python` with the version prior to commit `cd0eeb9`) this evaluates to "python3". 
- Non-working case (on the most recent commit `4882f70e6`) it evaluates to "/usr/bin/python3", which is one of the default python installations on my machine.

**Comment by sunlin7** [comment]
Thanks for the troubleshooting information, the `python3`​ works but `/usr/bin/python3`​ doesn't work, that imply there're different ones.
Could you please evaluate the
(executable-find "python3")​

to get the `python3`​ full path for worked case? NOTE: activate the conda​ virtual environment first. Thanks.

**Comment by sunlin7** [comment]
I guess the reason: conda envrionment use `/opt/conda/bin/python3`, and `python-shell-interpreter` was initialized as `python3` can be expanded to conda python3; but latest lisp use the full path `/usr/bin/python3`, it will failed with conda envrionment. 

I'll try to chage the code to restore previouse basename.

**Comment by sunlin7** [comment]
@TheDohn 
Please give a try with #16107, it should work for you.

**Comment by TheDohn** [comment]
@sunlin7 That works! Thank you for your work on that and helping me troubleshoot - it is very much appreciated!!

**Comment by sunlin7** [comment]
Great, thank you !
