### ISSUE TITLE
Recent undo-tree package leaves *.~undo-tree~ files

### ISSUE THREAD

**Issue by Antiarchitect** [syl20bnr/spacemacs#16062]
#### Description :octocat:
Having similar issue after recent packages update: https://github.com/syl20bnr/spacemacs/issues/15426

#### Reproduction guide :beetle:
- Start Emacs
- Edit some file
- git status

*Observed behaviour:* :eyes: :broken_heart:
See *.~undo-tree~ files related to those I edit

*Expected behaviour:* :heart: :smile:
No extra files are created in working directory

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.0.92
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. bdc9d0bec)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion ansible csv
                 (docker :variables docker-dockerfile-backend 'lsp)
                 emacs-lisp git
                 (go :variables go-backend 'lsp go-use-golangci-lint t)
                 (helm :variables helm-no-header t)
                 html javascript
                 (json :variables json-backend 'lsp json-fmt-tool 'prettier)
                 (lsp :variables lsp-rust-server 'rust-analyzer)
                 multiple-cursors nginx org puppet python ruby
                 (rust :variables rust-backend 'lsp)
                 (shell :variables shell-default-term-shell "~/Sync/dotfiles/sway-alacritty.sh")
                 shell-scripts
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 systemd themes-megapack
                 (treemacs :variables treemacs-show-hidden-files t treemacs-sorting 'alphabetic-asc treemacs-use-filewatch-mode t treemacs-use-follow-mode t)
                 typescript
                 (yaml :variables yaml-enable-lsp t))
```
- System configuration features: CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XAW3D XDBE XIM XPM LUCID ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by scottyj503** [comment]
I am seeing this as well.  I believe it was due to [this](https://github.com/syl20bnr/spacemacs/commit/4ec0b8b88f10fa9ac9c42811b65030532664d64d#diff-1cb355d2a8f6cd984f656c92fdef1400c375fd9b1c50bb68af74eb812109213d) recent commit.

The [previous](https://github.com/syl20bnr/spacemacs/blob/50a2f034eb6c0f865df9d574920e5dc6df015fe5/layers/%2Bspacemacs/spacemacs-editing/packages.el#L550) packages.el had the following on line 550.  

I reverted back to [1b1866d20a](https://github.com/syl20bnr/spacemacs/commit/1b1866d20a58a4d6df74d39c5a26f7d6a9a377c5) and the behavior stopped.

**Comment by smile13241324** [comment]
Should be fixed
