### ISSUE TITLE
The private directory

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#1620]
There is a problem with `private` as it exists today. An optimal use-case for people who are interested in source-controlling their personal configuration would be to symlink the whole directory into a different repo. That way, new layers automatically end up where they should be. Unfortunately, this doesn't quite fit with the current structure, because the directory contains readme files that git expects to be there. Git doesn't allow the adding of these files past a symlink, so such a strategy causes the root `.emacs.d` repository to be perpetually dirty. This is anathema for people like me. :-)

Instead, the user has to symlink each new private layer individually, *after* moving it where it should be (since `configuration-layer/create-layer` creates a regular folder). Another option is to symlink a subdirectory of `private`, but that runs into #1619, since arbitrary subdirectories aren't automatically searched (you have to add this directory to the search path instead). And in any case it only solves half the problem, since `configuration-layer/create-layer` will still happily ignore your shiny new symlink. (One might of course set `configuration-layer-private-directory`, but it is marked const. Maybe it shouldn't be?)

All the workarounds strike me as inconvenient when there's a much simpler solution: delete the directory in git, create it on startup if necessary, and move the documentation within (which is quite sparse in any case) somewhere else.

**Comment by syl20bnr** [comment]
I don't get it, you can put layers anywhere and reference their directories with `dotspacemacs-configuration-layer-load-path`. Why you don't want to use that ?

**Comment by TheBB** [comment]
Because `configuration-layer/create-layer` won't put them there. It assumes this stuff should go in `private`, so the design of `private` should facilitate that.

**Comment by syl20bnr** [comment]
I see, so we can ask the user where we should put the layer with helm or ido first.

**Comment by justbur** [comment]
I like this suggestion and made a PR for it

**Comment by BlinkD** [comment]
same with this ,i reset the configuration-layer-private-directory
```
   configuration-layer-private-directory "~/dot-spacemacs/"
   dotspacemacs-configuration-layer-path '("~/dot-spacemacs/")
```

**Comment by fmdkdd** [comment]
You can use [GNU Stow](https://www.gnu.org/software/stow/) to symlink your private directory into .emacs.d/private, without disturbing the README file.  Since the private directory is created by cloning Spacemacs, Stow will symlink the content of your private directory into spacemacs/private.

This allows you to manage your .spacemacs and private directory in a separate repository.  Check [my configuration](https://github.com/fmdkdd/dotfiles/tree/master/spacemacs).

If you add files into your private directory, you can tell Stow to update the symlinks with `stow -R`.

**Comment by Profpatsch** [comment]
I advise everybody to use gnu `stow` for dotfiles in general, since it’s such a simple yet elegant solution.

> I see, so we can ask the user where we should put the layer with helm or ido first.

As a new user I wouldn’t want to be bothered by such a question, since I probably would have no idea what I need this for.

**Comment by justbur** [comment]
So a new user wants to create a layer (going beyond some simple configuration in .spacemacs) but can't be bothered to think for a second about where the layer should go in the filesystem? They should be reading the documentation for creating a layer anyway, so I don't see why this is overkill. 

It's also worth recognizing that not everyone has easy access to `stow` since some people work on windows, for example (and not always by choice).

**Comment by Profpatsch** [comment]
> So a new user wants to create a layer (going beyond some simple configuration in .spacemacs) but can't be bothered to think for a second about where the layer should go in the filesystem?

I misread this init for the ones at first startup, sorry.
