### ISSUE TITLE
New lines getting wrong indentation in Python

### ISSUE THREAD

**Issue by andresmrm** [syl20bnr/spacemacs#1646]
When adding a new line after, for example, a `if True:`, I'm getting an indentation of 3 spaces in the next line, not 4.
And when adding a new line after this `pass`: 

    def aaa():
        pass

I'm getting 1 space in the new line, not 0.

Any ideas why?

**Comment by cpaulik** [comment]
I can not reproduce. Are you on the master or develop branch? What is your emacs version/OS?

**Comment by andresmrm** [comment]
Arch Linux, Emacs 24.5-1
Not sure about SpaceEmacs branch... When it starts there is a "(0.101.4)" in the top right of the pig head.

**Comment by andresmrm** [comment]
Oh, and sometimes, when I open a python file, I get that "blocking call to accept-process-output" error and Spacemacs crashes. Not sure if it's related...

**Comment by cpaulik** [comment]
I've got the same emacs version on ubuntu and can not reproduce the indent issue on master. Does this happen in an empty python file? I'm asking since as far as I know python tries to guess the indent from the code already there.

The `blocking call to accept-process-output` is anaconda related and should only happen if you are in a environment without the dependencies installed. What do you mean with Spacemacs crashes? Does is really crash or can you quit the current process with `C-g`?

**Comment by andresmrm** [comment]
You right: it doesn't happen in an empty file. Tried to search for bad indented lines in the first file, to see if it's a "repetition" problem, but the `blocking call` error crashed me again... =/
With "crash" I mean Spacemacs freezes. Even trying to close the window does nothing. I have to `pkill emacs`.

**Comment by andresmrm** [comment]
Installing the deps seem to have solved the anaconda problem.
Removing some multiline strings seem to have solved the indentation problem.
Thanks! =)

**Comment by jasoncyu** [comment]
@andresmrm what dependencies did you install? i also periodically get the `blocking call to accept-process-output` error

**Comment by andresmrm** [comment]
`pip install  jedi==0.8.1 json-rpc==1.8.1 service_factory==0.1.2`
As recommended here:
https://github.com/syl20bnr/spacemacs/tree/master/contrib/lang/python#anaconda-dependencies
I still get the `blocking` stuff sometimes, but at least it's not freezing forever like before.
