### ISSUE TITLE
How can i move .spacemacs to .emacs.d or ~  , when i use it in the win10?

### ISSUE THREAD

**Issue by e665107** [syl20bnr/spacemacs#16512]
I hope .spacemacs can move to the ~,   and my ~(home dir) is  d:/program files/emacs,  Following is my environment settings:

(cond((equal system-type 'windows-nt)
       (setenv"HOME" "D:/program files/emacs")
      (setenv"ARTISTIC_STYLE_OPTIONS" "D:/program files/emacs/.emacs.d/user_bins/AStyle/astylerc.opt")
      (setq default-directory "~/")
      ))

This configure works well, when i use emacs,   but here spacemacs doesn't work!   .spacemacs  will be make under ~,    if i  set the home dir to D:/program files/emacs, it should be make under the new dir!  But it disappoints me!   Can you give me a direct? Thanks!

**Comment by smile13241324** [comment]
See the following section from the documentation:
# First Launch and Configuration

1. After cloning Spacemacs, the first time when you launch Emacs, Spacemacs will
   automatically install the essential packages it requires. This step is the
   bootstrap.

2. Once the bootstrap packages are installed, Spacemacs checks whether you have
   an customization file `$HOME/.spacemacs`, known as `dotspacemacs`:

   - If it already exists, Spacemacs loads it as the configuration.
   - Otherwise, you need to answer a few questions and Spacemacs will generate
     the `dotspacemacs` file for you.

   If you are new to Emacs and/or Spacemacs, it's fine to just accept the
   default choices. They can be changed in the `dotspacemacs` file later.

3. Spacemacs will download and install remaining packages it will require,
   according to your `dotspacemacs`. When the all the packages have been
   installed, restart Emacs to complete the installation.

4. `dotspacemacs` is the configuration file for Spacemacs, it's self
   explanatory and is written in Emacs Lisp. Read
   [general documentation][DOCUMENTATION.org] and
   [quick start guide][QUICK_START.org] for more information.

5. In case you want to store your `dotspacemacs` at another location, say
   under `$HOME/.spacemacs.d`:

   - First set the environment variable `SPACEMACSDIR` to `$HOME/.spacemacs.d`.
   - Move `$HOME/.spacemacs` to `$HOME/.spacemacs.d/init.el`.

   In other word, set `SPACEMACSDIR` to the parent directory of your
   `dotspacemacs`, and move `dotspacemacs` to the said directory.

**Comment by smile13241324** [comment]
In other words please set the environment variable SPACEMACSDIR. 
Also you should consider moving from native windows to wsl2 as we do not longer officially support windows natively as now a pure linux environment is included in windows 10 and beyond.
