### ISSUE TITLE
Matrix Moderation

### ISSUE THREAD

**Issue by golanv** [syl20bnr/spacemacs#16596]
The Matrix room (also the old Gitter room), which is linked on both the Spacemacs website as well as the `*spacemacs*` buffer in Spacemacs is lacking moderation. Bots now regularly submit Spam posts without removal, advanced support questions are often unanswered, and participation in the room has slowed to nearly a halt. Would it be possible for moderation to return to this room? If not, could new moderators be appointed so that perhaps this official Spacemacs community might be revived?

**Comment by bryce-carson** [comment]
There are bots spamming? Oh, that's not good. As far as I know, the website is locked to @syl20bnr's user account and Sylvian hasn't decided to remove the Download button which misdirects people to the ancient, "surely borked but when" release 0.200, which hasn't been recommended in ages. I'm not surprised there are bots on Gitter now either, and it's also probably Sylvian that has administrator access for that (and he alone).

There was discussion years ago about moving Spacemacs to an organization (which might resolve the issue with the website), but that hasn't happened and isn't likely to happen.

Personally I'd advocate for removing the Gitter chat button and references to it at this point. It's _too dead_, and GitHub Discussions would be an easier platform given GitHub is otherwise the single-stop shop for everything else present-day Spacemacs, right?

**Comment by golanv** [comment]
I would really much prefer not removing the Gitter/Matrix chat button or abandoning the room. Yes, there are bots in the room, but that is not uncommon on Matrix these days unfortunately. In active chats, moderators simply remove the message and kick the bot. There is still discussion in the room, and users help one another when possible (although it was far more active a year ago). I don't think abandoning the room will leave a positive impression on the +8K Spacemacs users still present (although, I don't know how many of those users are active). I believe it would be much better for the project to simply give some attention to the room again, some moderation, and perhaps some of active contributors helping out to answer questions once in a while, if possible.

**Comment by bryce-carson** [comment]
Ideally, yes.

**Comment by choffee** [comment]
It looks to be only a couple of spamers in the room at the moment. I've reported/blocked a couple and it's cleaned up most of it.
I think there are a few users who are admin in the room so hopefully they can help.

**Comment by golanv** [comment]
Reporting and blocking users (spam bots in this case) will remove messages for the user submitting the report. A room admin or mod will be needed to ban a user and delete messages globally though. Thanks for following up on this @choffee !

**Comment by fnussbaum** [comment]
@smile13241324 Do you by any chance have permissions to assign new moderators in the gitter chat?

**Comment by smile13241324** [comment]
Unfortunately I have not, at least I think so. I can have a look tomorrow evening and report back here

**Comment by syl20bnr** [comment]
I cleaned up the spams and banned the users.
@smile13241324 as long as you log with your gitter.im user in Elements you should have admin privileges. Actually all the moderators before the gitter migration to matrix have been given admin privileges on the room.

@fnussbaum @golanv I gave you moderator level with your current accounts.

**Comment by syl20bnr** [comment]
> It looks to be only a couple of spamers in the room at the moment. I've reported/blocked a couple and it's cleaned up most of it. I think there are a few users who are admin in the room so hopefully they can help.

And thank you @choffee for the initial cleanup 😃
