### ISSUE TITLE
Theming mishandling introduced (loading theme from package)

### ISSUE THREAD

**Issue by ViktorHaag** [syl20bnr/spacemacs#16689]
#### Description :octocat:

Commit [8172c0f](https://github.com/syl20bnr/spacemacs/commit/8172c0f871cf0abc5ea4e77c41cea937b8c215ed) introduced a defect with theme handling, presumably when trying to divine the appropriate fallback theme.

My init file uses the themeing layer and the tango plus theme:
```
   dotspacemacs-themes '(tango-plus)
```

Prior to the commit in question, Emacs was able to install the tango-plus-theme
package and successfully apply theme with a light background as desired.

After the commit in question, Emacs didn't apply the theme the same, producing a
dark background instead of the light background.

#### Reproduction guide :beetle:
- Rewind to the commit just before 8172c0f
- Start Emacs
- Take a screen shot

![theme-good](https://github.com/user-attachments/assets/00578a83-98f8-44f5-9477-e53acfac7fa8)

- Quit
- Then, step forwward to commit 8172c0f, start Emacs, take screen shot

<img width="608" alt="theme-bad" src="https://github.com/user-attachments/assets/6f159390-7ad3-46e5-9de3-41bc5bafa98c">

I'd expect the loading of my theme to stay the same and be readable.

#### System Info :computer:
- OS: darwin
- Emacs: 29.4
- Spacemacs: 0.999.0
- Spacemacs branch: local-develop (rev. a2cae1bc6)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: compleseus
- Layers:
```elisp
(auto-completion compleseus denote-personal emacs-lisp git html ibuffer-personal
                 (javascript :variables js-switch-indent-offset 4)
                 local-functions lsp markdown multiple-cursors
                 (org :variables org-enable-github-support t org-enable-org-journal-support t)
                 (osx :variables osx-command-as 'meta osx-option-as 'super osx-control-as 'control osx-function-as nil)
                 (python :variables python-backend 'lsp python-formatter 'black python-format-on-save t python-lsp-server 'pyright python-shell-interpreter "~/.pyenv/shims/ipython3")
                 restructuredtext spacemacs-editing syntax-checking tern theming
                 (treemacs :variables treemacs-use-icons-dired nil)
                 yaml)
```
- System configuration features: ACL GLIB GMP GNUTLS JSON LCMS2 LIBXML2 MODULES NOTIFY KQUEUE PDUMPER RSVG SQLITE3 THREADS TOOLKIT_SCROLL_BARS TREE_SITTER WEBP XIM XWIDGETS ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by stradicat** [comment]
Can confirm.

Behaviour 1: Emacs window theme is initially either `spacemacs-light` or `spacemacs-dark` instead of the user-defined themes

Behaviour 2: Editor frame takes some of the user-defined themes (in my case, `doom-solarized-light` and `doom-one`) at least for `prog-mode`modes, but not for `markdown-mode`:
![Captura de pantalla 2024-11-29 a la(s) 21 45 26](https://github.com/user-attachments/assets/71de4964-fdac-47fa-af8d-e594e2d8363d)
![Captura de pantalla 2024-11-29 a la(s) 21 45 09](https://github.com/user-attachments/assets/3c72c317-9b0b-4927-9bfa-04e48bf72b98)


Behaviour 1 began taking place after commit `5ff44b284f8b251d45e7c90ddc020c3a23f6a47b`.

Behaviour 2, additionally, after commit `61c3fbd5367fb52f58826dddb83453af99503d5f`.

**Comment by sunlin7** [comment]
I can reproduce the issue, and try my best to fix it.

**Comment by sunlin7** [comment]
Hi @ViktorHaag @stradicat  Please help verify the PR #16690. Thanks

**Comment by stradicat** [comment]
Hello @sunlin7, #16690 does indeed fix behaviour 2 (editor frame applies some of the user-defined themes, but window elements are from `spacemacs-light` or `spacemacs-dark`).

Behaviour 1 (Emacs windows starts with either built-in `spacemacs-light` or `spacemacs-dark` theme elements instead of the user-defined themes) is still present, however. If it's the result of an underlying performance feature, I can live with it. Something changed after commit `5ff44b2` regarding theme handling.

**Comment by sunlin7** [comment]
reproducting behavior 1...

**Comment by ViktorHaag** [comment]
> https://github.com/syl20bnr/spacemacs/pull/16690 does indeed fix behaviour 2 (editor frame applies some of the user-defined themes, but window elements are from spacemacs-light or spacemacs-dark).

Agreed; same here.

> Behaviour 1 (Emacs windows starts with either built-in `spacemacs-light` or `spacemacs-dark` theme elements instead of the user-defined themes) is still present, however. If it's the result of an underlying performance feature, I can live with it. Something changed after commit `5ff44b2` regarding theme handling.

Ideally, there'd be a way to start with a user defined theme, and a way to make sure a package is present/installed, if needed, and only then to fall back to spacemacs-light or spacemacs-dark.

My current work around is to define my themes like this:
```
   dotspacemacs-themes '(spacemacs-light tango-plus)
```

And then to use `SPC T n` to switch to my theme after startup.

I actually (from HEAD of `develop`) tried to use this syntax (as suggested in the docs/comments for this [commit](https://github.com/syl20bnr/spacemacs/commit/977110e7eb9d128a4df69a2a9606813e50f2a2b5)), and it threw an error so I abandoned that approach and filed the defect report:
```
   dotspacemacs-themes '((tango-plus :package tango-plus-theme))
```

**Comment by sunlin7** [comment]
I can reproduce the case 2 now, researching the root cause.
```
   dotspacemacs-themes '(doom-solarized-light tango-plus)
```

**Comment by sunlin7** [comment]
Hi @ViktorHaag @stradicat I had correct my PR #16690 (I lost the `progn` in the `if-let*`), it should resolve both case 1 and case 2 now. 
Please help verify it. Thanks.

**Comment by stradicat** [comment]
Theme handling works again on my side, no unexpected behaviour detected.

**Comment by sunlin7** [comment]
Great! Thank you for confirmation, and look forward @smile13241324  to help approve the MR.

**Comment by ViktorHaag** [comment]
Yep -- confirmed on my side as well that this seems to work fine.
