### ISSUE TITLE
C-j not work in ido-find-file

### ISSUE THREAD

**Issue by BlinkD** [syl20bnr/spacemacs#1687]
i have two layers `a` and `b`
--a
----funcs.el
----packages.el

--b
----funcs.el
----packages.el
----config.el

if i both open `b/config.el` and `a/packages.el` ,and im in file buffer `a/packages.el`
C-x C-f ,and type `config.el` then press `C-j` immediately ,which i want create config.el in layer `a` (in the same path with `a/packages.el`)
but ido-find-file still complete the filepath `b/config.el`

**Comment by TheBB** [comment]
Is this still a problem?

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
