### ISSUE TITLE
Help popup focus on single window

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#1734]
If I use a help describe command `SPC h d [key]` in a frame with multiple windows the focus is on the help buffer, which is great since I can read it then close easily with `q`. However, if I have a single window open and I try the same, the focus is not on the help buffer, making it inconvenient and inconsistent since I have to switch to the window with the help buffer then close it which results in extra keystrokes.

**Comment by tuhdo** [comment]
This sounds strange since it behaves differently when you have multiple windows and one window. It is supposed to behave like what you described with single window.

You don't have to switch to help window to press `q`. You can press `C-g` to cancel anything `popwin` shows you. The current behavior prevents point to move to other buffer, so you don't have to switch back to main buffer *while still want the help buffer remains*.

**Comment by tuhdo** [comment]
You can customize the behavior in `popwin:special-display-config` and uncheck `noselect` for `*Help*` buffers, the save it.

**Comment by jupl** [comment]
Personally I like the focus on the help window but I think the important thing is that the behavior is consistent regardless of the number of windows. I would expect it to behave the same way whether it is to focus on the help buffer or refocus on the last thing.

**Comment by syl20bnr** [comment]
I have the same issue and it is very annoying, must use `SPC w u` to close the help window.
To be fixed.

**Comment by tuhdo** [comment]
It seems like a popwin bug. If this is the case, we should set all `noselect` to `nil` by default, so `popwin` windows are always selected.

**Comment by tuhdo** [comment]
@syl20bnr To fix it, you can change every `noselect` to `nil` in [here](https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L2083).

**Comment by syl20bnr** [comment]
@tuhdo thank you, I'll do it tonight if nobody PR it.
