### ISSUE TITLE
Add more robust profiling for spacemacs startup

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#1749]
Add options to present time taken to load each package to help optimize spacemacs loading and find packages not set up.  Since we already track total startup time, can we set up a log of each package load to determine the time taken for each package?

**Comment by sooheon** [comment]
This would be nice, and it would pair well with the excluded-packages variable. Some people may want to improve their startup time, but not know where to start from the long list of default packages.

**Comment by cpaulik** [comment]
You can set `use-package-verbose t` in your `dotspacemacs/init`. Then each package will display its loading time, if it is loaed, in the messages buffer during startup.

**Comment by sooheon** [comment]
If I put `(setq use-package-verbose t)` in my dotspacemacs/init, each packages displays a message on load, but still doesn't show the load time.

**Comment by cpaulik** [comment]
According to the [documentation](https://github.com/jwiegley/use-package#information-about-package-loads) it produces a message for each `:config` block that takes longer than 0.1s to load.

Since most spacemacs packages are lazy loaded you will not see a time anyway until the `:config` block is executed i.e. when you use the package the first time.  For example the only times I see during startup are for some erc packages that are not lazy loaded and then when I use `helm` for the first time it also shows me the time.

**Comment by sooheon** [comment]
Ah thanks for the tip.

**Comment by ralesi** [comment]
This should work,  will give it a try

**Comment by hsitz** [comment]
I don't think the discussion in this thread is accurate.  For one thing, if you look at the use-package-verbose documentation, it indicates load time will be loaded for packages that take more than 0.1 seconds, even if verbose is off.  If verbose is on, you're supposed to get load times for everything, regardless of how long they take.  Also, the output in my messages buffer is the same, regardless of whether I have use-packages-verbose set to t in spacemacs init function or not.
