### ISSUE TITLE
Separate layer repositories?

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#1850]
Spacemacs is slowly getting to the point where keeping every layer in the main repository is getting unsustainable.

For example, everyone who is using Spacemacs will need to download layers for Spotify, Evernote, Perforce, xkcd, Puppet, etc. when cloning or updating the repository.

I am not advocating immediate action, but I think this will be an important problem for Spacemacs in the future.  As Spacemacs grows, we will need to pay more attention to what layers are accepted into the main repo with more care.

The thing is, using a single Git repo to store packages (layers) is not The Right Thing(c).  Using the main Spacemacs repo as a layer repository is definitely not The Right Thing(c).  Some sort of formal layer repository should be set up.

Ideally, Spacemacs only ships with a handful of "core" layers, and the rest of the contrib layers are stored in various separate layer repositories, which would then be added to Spacemacs via configuration:

    (setq spacemacs-layer-repositories '(
        "syl20bnr/spacemacs-dev-layers"
        "syl20bnr/spacemacs-misc-layers"
        "billybob/private-layers"))

Again, this is not a call to action, but sooner or later this issue will need to be addressed, so it would be beneficial to at least think about it early on.

**Comment by syl20bnr** [comment]
Cloning layer repos is a planned feature from the beginning but I would not be so sure about "not the right thing to do" for various reasons:
- layers are light
- layers can be discovered and introspected easily
- we can provide better overall quality by reducing clashes, enforce conventions, see the wall picture of what Spacemacs offers etc...

We should not forget that Spacemacs emerged from a need to get control over the ever growing set of packages available.

Splitting the configuration all around can compromise these guarantees, we have to be careful.

Although I used to be excited by this feature, this is not the case anymore.

**Comment by JoshTGreenwood** [comment]
I've had similar thoughts of removing the layers from this Git repo but have ultimately changed my opinion.  I'd advocate keeping them all in one place until it becomes a pain point for 2 reasons:

1.  Discovery:  As a new user, it is incredibly easy to find out what's available to me by just scanning the contrib directory.  It's also easy to know what's _not_ available instead of endlessly googling for a solution.  Maybe the answer to this (if the layers do eventually find their own home repo's) is to still maintain a canonical reference to all available layers in this repo.

2.  Searchability:  Figuring out which plugins (and core) are using which keybindings and functions is a lot easier when they can be searched from this repo.

**Comment by cpaulik** [comment]
I can only think of two maintainable solutions:

1. the current one of having everything in one git repository should work for a pretty long time since layers are only a few text files.
2. a MELPA like approach for Spacemacs layers in which we can still maintain control over the layers that are officially supported by Spacemacs. This might not be necessary for a very long time, if ever.
