### ISSUE TITLE
base16 themes not showing up

### ISSUE THREAD

**Issue by griffgruff** [syl20bnr/spacemacs#1851]
When I do   : space T h
None of the base16 themes are showning.

Worked fine in the previous release.

**Comment by syl20bnr** [comment]
The themes have been removed from the spacemacs layer since they are not required anymore, now all the themes listed in `dotspacemacs-themes` are not deleted if detected as orphans.
It also means that if you want to have them always available in `SPC T h` even if you don't use theme then you have to add them explicitly to `dotspacemacs-additional-packages`:

```elisp
(setq  dotspacemacs-additional-packages '(base16-theme))
```

Note that `dotspacemacs-additional-packages` is a new variable introduced in 0.102.0.

**Comment by griffgruff** [comment]
cool .... thank you.

**Comment by syl20bnr** [comment]
If it works for you then you can close the issue :-)

**Comment by griffgruff** [comment]
solved!

**Comment by lmartins** [comment]
This is supposed to go inside `(defun dotspacemacs/config () )` right?
I've added it there, where I also have other settings working fine, but after reload base16 themes still doesn't show on the helm list.

**Comment by syl20bnr** [comment]
@lmartins it goes in `dotspacemacs/layers` you should already have it defined with the an empty list.

**Comment by lmartins** [comment]
Got it, thanks.
