### ISSUE TITLE
[BUG]tmux layer unset global prefix key C-h

### ISSUE THREAD

**Issue by BlinkD** [syl20bnr/spacemacs#1855]

**Comment by StreakyCobra** [comment]
@BlinkD Can you give some steps on how to reproduce please?

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
