### ISSUE TITLE
Inserting line above point

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#1873]
The function `spacemacs/insert-line-above-point-no-indent`, bound to `SPC i K` is broken. It doesn't work on the first line in the buffer. While fixing that, I noticed that my *new* version didn't work on the first *character* in the buffer. While fixing *that*, I noticed that my *new new* version didn't work on the first *non-blank* character in the buffer.

I conclude that before I lose my mind someone with more experience should look at it.

**Comment by travisbhartwell** [comment]
I've made a bit of progress on this:

```elisp
(defun spacemacs/insert-line-above-no-indent (count)
  (interactive "p")
  (save-excursion
    (if (eq (line-number-at-pos) 1)
        (evil-move-beginning-of-line)
      (progn
        (evil-previous-line)
        (evil-move-end-of-line)))
    (while (> count 0)
      (insert "\n")
      (setq count (1- count)))))
```

This works correctly if you are not on the first line, or any character on the first line.  The expected behavior is to insert a line before but keep the point where it is.  If you are on the first character of the first line, it keeps the point on the first character of the buffer, meaning it stays in the new blank line.

I'm not sure why the save-excursion is working differently.  Perhaps we need to wrap this whole thing in a test if the point starts at the beginning of the buffer, move it to match where the content is.

**Comment by travisbhartwell** [comment]
Check PR for a working solution, not sure if it is the optimal one though.
