### ISSUE TITLE
When enable semantic in emacs-lisp buffer, the completion is very slow

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#1907]
If I enable semantic layer or manually enable semantic mode, the company mode completion is very very slow when editing elisp code. It will try to parse all the elisp in Emacs installation  and ELPA directory.

And even in elisp comments, the company tries to use `company-capf` as the backend.
If I disable semantic layer, it will use `company-dabbrev` when completing comments.

@tuhdo 
Toughts?

**Comment by tuhdo** [comment]
`company-capf` is the expected backend to be used. I had no slowness with it. Could you describe how is it slow? And even without `semantic-mode` enabled, in Emacs Lisp `company` should use `company-capf`. Do you set `company-idle-delay` to very small value?

**Comment by andyque** [comment]
@tuhdo 
Yes, I set `company-idle-delay` to 0.08. I know `company-capf` is the right backend, but it should only be used when completing lisp code not the comments in lisp.

When wrting comments in lisp, it should use `company-dabbrev` as the default backend.

**Comment by a13ph** [comment]
This affects me, despite me having default Spacemacs setup for `auto-completion` and `semantic` layers (i didn't specifically enable company anywhere so IDK if i have it enabled in elisp files or not).
I really want to use semantic, but this is making it very troublesome. (yes, this issue is only with semantic enabled)

I'm not even mad at it parsing all the emacs sources, I'm just mad it's doing it when I'm typing and not doing when I'm not, when it's clearly better to do so the other way around :laughing: 
Any hope of parsing while idle to build some sort of cache/index? Or do I have to run some tag tool somewhere?

**Comment by mrkgnao** [comment]
I have this issue too, and it'd be great if a manual tagging procedure of the kind @a13ph describes exists. With `semantic` enabled, `elisp-mode` is barely usable.

**Comment by ikzk** [comment]
I have this issue too. Any plan to solve this?

**Comment by a13ph** [comment]
@d12frosted, can you please reopen this issue then?

**Comment by btljuice** [comment]
I have the same issue also on my end, when auto-completing in my .spacemacs file:
- With both the `semantics` and `auto-completion` layer, the auto-completion is quite slow after typing two letters. The bottom status bar describes some parsing effort in what appears to be all my *.el files for my layers.
- Without the `semantics` layer, auto-completion is "virtually" w/o any delay.

I have disabled semantics since I don't use it very much. On my end I'm fine like that, but I'm willing to help / debug / support if needed.

---

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
 smex cscope gtags
 (shell :variables shell-default-height 16 shell-default-position 'bottom shell-default-shell 'shell)
 (spell-checking :variables spell-checking-enable-by-default nil)
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 typography version-control git perforce dash evil-snipe vinegar
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 ranger imenu-list markdown org org-clock-csv finance emacs-lisp common-lisp latex c-c++ java python lua shell-scripts windows-scripts autohotkey vimscript csv restclient html javascript)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by braham-snyder** [comment]
does your `semanticdb-find-default-throttle` include `omniscience`? if so, this may fix it: https://github.com/syl20bnr/spacemacs/pull/7736#issuecomment-313320906

**Comment by d12frosted** [comment]
@a13ph I am the master of timing, right?

**Comment by agzam** [comment]
Any update on this issue? Even `(semantic :disabled-for '(emacs-lisp))` seems to be not working

**Comment by braham-snyder** [comment]
judging from @beta1440's [PR](https://github.com/syl20bnr/spacemacs/pull/9354), my suggestion in https://github.com/syl20bnr/spacemacs/pull/7736#issuecomment-313320906 worked for him -- can you confirm whether that works?

**Comment by agzam** [comment]
@braham-snyder it seems it did stop forcing company.el to parse big number of files, but there's still noticeable lag (about half a second long) there and there. Sigh. I guess I have to disable semantic layer. Nothing else seems to work for this issue.

**Comment by agzam** [comment]
nope, I was wrong...  it actually still tries to parse bunch of files, when something being typed in elisp docstings.

**Comment by kkweon** [comment]
Any update on how to fix this? 

In the mini-buffer, it says `parsing **/*.el` every time I type a string and I can't type anything while parsing, which takes forever parsing all *.el.

![image](https://user-images.githubusercontent.com/2981167/36344494-0573e6c8-13d0-11e8-9b09-b3169d09b6fa.png)

**Comment by braham-snyder** [comment]
FWIW, https://github.com/syl20bnr/spacemacs/pull/7736#issuecomment-313320906 is still working for me

**Comment by NightMachinary** [comment]
This needs a fix IMO? A caching system?

**Comment by josiah14** [comment]
I do have to say, for an editor configured and (mostly) written in Emacs Lisp, it's a little unnerving that it has this much trouble with its native language.  I'm finally taking the time to try to learn Emacs Lisp, and this particular issue is almost enough for me to give up on it and use other editors for the language layers that don't work well enough for me.

**Comment by NightMachinary** [comment]
The problem is with a third-party package that you need not enable. Other
editors just don’t have that many extensions going for them, so they are
less trouble.
Soon the LSP will become common, and all editors would use it. That should
solve quite a lot of problems.

**Comment by light2yellow** [comment]
https://github.com/syl20bnr/spacemacs/issues/11058#issuecomment-407269954 fixed this issue for me (and also #11058).

**Comment by quicknir** [comment]
Is there any resolution for this?

**Comment by duianto** [comment]
The following PR is now on the `develop` branch:
Improve the use of semantic #11511
