### ISSUE TITLE
Stuck in 'Initializing...'

### ISSUE THREAD

**Issue by fatlazycat** [syl20bnr/spacemacs#1909]
When choosing a 'recent file' from the startup screen ( which happens to be a haskell file ), spacemacs gets stuck stating 'Initializing...'.

Appears that hitting any key then kicks it into life and normal operation is resumed.

**Comment by syl20bnr** [comment]
Does it happen if you `SPC f e i` to open the `init.el` file and then `SPC f r` to open the haskell file ?

**Comment by fatlazycat** [comment]
Sorry been away. Yes it does the same behaviour.

Though have noticed after I push a key it says 'no new modules' then pops into the haskell file.

**Comment by emmanueltouzery** [comment]
I have seen this error too and noticed the following: if I open the haskell file with `emacs Test.hs`, I hit the problem. If I rather launch `emacs` and once it's loaded, then open the haskell file, then no problem. I'm personnally certain that it's tied to haskell. When it works just after the point where it would otherwise be stuck it displays `No new modules`.

**Comment by fatlazycat** [comment]
as of 1.103.2 this no longer occurs. Not sure which version fixed it.

of if it was an update to emacs packages.
