### ISSUE TITLE
Text being placed to the right on Web mode

### ISSUE THREAD

**Issue by carlosgaldino** [syl20bnr/spacemacs#1950]
![untitled mov](https://cloud.githubusercontent.com/assets/48889/8107070/f6c19e2c-101c-11e5-9650-1541a1726c69.gif)

Major mode is Web. Spacemacs version is `0.102.2`.

If the fill indicator is disabled everything works normally. Any ideas?

Thanks.

**Comment by TheBB** [comment]
I can replicate this. Also note that the indentation is off by one if the fill indicator is enabled.

**Comment by syl20bnr** [comment]
OMG this is ugly. Maybe it is a know bug with `web-mode` and `fill-columun-indicator` ?

**Comment by TheBB** [comment]
Yes, it's an upstream bug left open for over a year now. See [here](https://github.com/alpaker/Fill-Column-Indicator/issues/46).

**Comment by syl20bnr** [comment]
@TheBB Thank you !

**Comment by emmanueltouzery** [comment]
my fix is to disable FCI for web-mode:
https://github.com/alpaker/Fill-Column-Indicator/issues/46#issuecomment-107699526

there is also a problem with magit blame mode:
https://github.com/alpaker/Fill-Column-Indicator/issues/59

and other little ones left & right. Maybe workarounds for these could be pushed in spacemacs instead of having the users handle them? Although that would reduce the push for proper fixes I guess...

**Comment by Compro-Prasad** [comment]
I think this bug has evolved. Now, it does fix it self after writing a few characters on the line.

**Comment by Compro-Prasad** [comment]
@sdwolfz @syl20bnr A comment just popped up from the fill column indicator maintainer. He is probably transferring ownership to interested people. Should we keep this broken package or wait for someone to become a maintainer?

https://github.com/alpaker/fill-column-indicator/issues/46#issuecomment-458613417
