### ISSUE TITLE
Enhance evil-lisp-state

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1955]
Currently, getting into the lisp state takes too many keys (4 keys for Emacs to `C-c k <something>`). That's why I'm using Lispy. We can make it better:
- Adapt its key bindings for Emacs users. Serious, I like it but I cannot use it like this. Just `f/b/n/p` is enough. Slurp can be replaced with `>` and barf with `<` to free the key bindings.
- Make use of `avy/ace` (we should remove `ace-jump-mode` really). In Lispy, I can press `q` to jump to any open parenthesis in current defun. It's really convenient.
- Similarly, I can remove any symbol and jump to it with `H` in current defun.
- Lispy provides two handy commands: `lispy-knight-up` and `lispy-knight-down` that allows me to jump up/down the next sexp on the next line. If the next sexp is a bigger scope, jump up to it. For example:

``` elisp
(when (or (equal (user-full-name) "tuhdo")
            [](equal (user-full-name) "tudo"))
    (smartparens-global-strict-mode))
```

Point is `[]`. When I use `lispy-knight-up`, it jumps to the parenthesis at `when` and when use `lispy-knight-down`, it jump to the parenthesis on the next line.
- `[` and `]` should just jump to beginning and end of defun. It is currently unbound.
- `e` to eval current sexp at current parentheses.
- For `holy-mode`, we should add a 2-keys binding i.e `C-]` to get into lisp state quickly.

**Comment by syl20bnr** [comment]
It seems that 4 keys is a lot but it is not in practice, the issue is that evil-lisp-state is meant to be used in Vim style, it has never been thought to be used in Emacs style.

In Vim style the user is most of the time in `normal state`, then `SPC k`  can really be viewed as one keystroke once the muscle memory is done.
Once `SPC k` is pressed we are in lisp state so it is not required anymore for the following manipulations.

What I want to experiment is to use Lispy but with the following changes:
- the state is not defined by the position of the point
- `SPC k` enter Lispy state
- Tweak Lispy to be more compliant with Vim in Vim style

There is a package that partly does this I believe, we should give it a try.

**Comment by sooheon** [comment]
I like the idea of extending lispy with a more vi compliant key theme (which could be PRed upstream as a drop in alternative to the `special` lispy key theme. Curious what is the package that partly does this?

**Comment by redline6561** [comment]
This might be the package @syl20bnr was thinking of: https://github.com/bcarrell/evil-lispy

**Comment by justbur** [comment]
@syl20bnr suggested in chat that for holy-mode users we could have `M-m k` toggle lispy. What do you all think of that?
