### ISSUE TITLE
flycheck popup is messed up

### ISSUE THREAD

**Issue by Eilie** [syl20bnr/spacemacs#2033]
For some reason flycheck compilation error popup can't be displayed over text so it chooses to add each line of compilation error popup at the end of existing line:
![](http://i.imgur.com/ETbqtzl.png)

Maybe i've built my emacs without some important use flag for this to work properly?

**Comment by syl20bnr** [comment]
Do you have a repro step ?

**Comment by syl20bnr** [comment]
Also what is your emacs version and OS ?

**Comment by andyque** [comment]
@syl20bnr  I could confirm this issue and I have personally disable the popup tooltip in flycheck.
I think it's a bug in https://github.com/auto-complete/popup-el

**Comment by syl20bnr** [comment]
@andyque thank you for the feeback.

@Eilie  I just noticed that you have the fill-column displayed, there are a bunch of issues with it, if you disable it (`SPC f` I believe) does it fix the issue ?

**Comment by Eilie** [comment]
@syl20bnr Disabling `fci-mode` did fix the issue indeed, thank you. But is there a way to get this around without disabling `fci-mode`?

**Comment by StreakyCobra** [comment]
Does this still happen? The flycheck tooltip library has been changed, if it was the issue it may be solved after updating the packages.

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
