### ISSUE TITLE
Replace anconda with elpy

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#2050]
elpy has more features aside from completion, such as prompt for imports with `importmagick`, unit test support and other things. We can keep some other packages.

**Comment by andyque** [comment]
@tuhdo  anconda mode only deal with code completion and it is more responsive. 
See here for more information:
https://github.com/proofit404/anaconda-mode/issues/38

**Comment by syl20bnr** [comment]
We already made the decision to go with anaconda and to have only one python environment in spacemacs, see https://github.com/syl20bnr/spacemacs/pull/370

**Comment by syl20bnr** [comment]
My principal point that makes Elpy a no go without compromises is that I want the modularity to be at the Spacemacs level, see `spacemacs contrib layer` as our `Elpy`. I want to be able to compose what a python experience is at the spacemacs level instead of fighting a big behemoth to play well with the spacemacs platform (helm, project management etc...).

**Comment by syl20bnr** [comment]
Not that `Elpy` is not alone in this case, `EDTS` for Erlang has been removed for the exact same reasons.

**Comment by tuhdo** [comment]
Alright then.

**Comment by jerome-diver** [comment]
now how to just use elpy with spacemacs ? is there a tuto somewhere or do i consider to just stop with spacemacs because i can not have a pyhon IDE under spacemacs without loose hairs ?

**Comment by Compro-Prasad** [comment]
LSP is quite popular nowadays.

**Comment by jerome-diver** [comment]
ok, thank you.
