### ISSUE TITLE
How to specify bold font in spacemacs?

### ISSUE THREAD

**Issue by dongzhangfan** [syl20bnr/spacemacs#2087]
Hi, everyone. I find that on default spacemacs use Source Code Pro Bold for bold face fonts. I think this font is too bold for 13pt size. Any idea to set the bold face font to use Source Code Pro Medium Instead?

**Comment by geo7** [comment]
@dongzhangfan did you find a solution for this?

**Comment by nixmaniack** [comment]
AFAIK, there isn't a single one off setting which allows this. The way I see you can achieve this is via `customize-face` for faces you want to control their `:weight` (boldness of face) but since there are other packages/themes which can I override these settings this might be difficult to achieve.

**Comment by TheBB** [comment]
I think @nixmaniack's solution is best. You can tweak the `:weight` of the `default` face. Since this is quite subjective I don't think we should spend too much time on it.

**Comment by Tom007Cheung** [comment]
You can config your **".spacemacs"** file!

    dotspacemacs-default-font '("Source Code Pro"
                               :size 24
                               :weight normal
                               :width normal
                               :powerline-scale 1.1)
