### ISSUE TITLE
vi-tilde-fringe displays ~ on the current line

### ISSUE THREAD

**Issue by Profpatsch** [syl20bnr/spacemacs#2089]
When you go into insert mode, the ~ stays until the first char is typed. This differs from vi behaviour and is quite annoying.

**Comment by syl20bnr** [comment]
This is a known issue and it is due to the emacs implementation. You can use the layer `vim-empty-lines` for an alternative solution closer to Vim one thats works in the terminal. Using this layer will automatically replace `vi-tilde-fringe`.

The reason why `vim-empty-lines` is not enabled by default is that there are some side effects with it. But for a regular usage of Emacs it should be good enough.

**Comment by Profpatsch** [comment]
I looked into it and it seems the emacs fringe functions are done C code.

Probably best to turn ~ off alltogether.

**Comment by geo7** [comment]
is this still an issue?

**Comment by Profpatsch** [comment]
@geo7 It’s not fixed. I still don’t think it should be like that. I try to ignore it.

**Comment by TheBB** [comment]
The layer is fine, you can use that.
