### ISSUE TITLE
Spacemacs hangs on Tromey.com 

### ISSUE THREAD

**Issue by LBEaston** [syl20bnr/spacemacs#209]
Tromey.com appears to be down (not responding to ping). This is causing spacemacs to hang when trying to connect to tromey.com:88
Commenting out `("ELPA" . "http://tromey.com/elpa/")` on line 51 of config-system.el fixes this. Should there be some kind of timeout when it can't reach a host? I waited about 30 seconds before deciding it was taking too long.

**Comment by syl20bnr** [comment]
I close this issue for now since it does not seem trivial to implement and the benefit is pretty low because Spacemacs does not check for archive update unless during installation or explicit update.

**Comment by bmag** [comment]
@syl20bnr why not stop using tromey.com entirely? AFAICT tromey has not been updated in a very long time:
- according to [this SE answer](http://emacs.stackexchange.com/a/2223/6533), tromey is retired and no longer updated since 2010.
- judging by tromey's [news page](http://tromey.com/elpa/news.html), the last update was made on August 15, but the year is not mentioned. It does mention perspective.el version 1.3. As you can see [here](https://github.com/nex3/perspective-el/commit/75c4becb495e0e544ad4fc2acf4930e58ac4fa34), version 1.3 was released on August 2010. The latest version is actually 1.12 (see https://github.com/nex3/perspective-el/blob/master/perspective.el#L10) and available from MELPA.

I did <kbd>SPC a P</kbd> and looked at several ELPA packages. Some of them have newer versions available from MELPA or other archives, but there are a few that I couldn't find in the other archives (or as a built-in package). For example, `asciidoc` is on tromey, but I couldn't find it in the other archives. I did find an `adoc-mode` package at MELPA, though.

Does Spacemacs actually use any of the packages in tromey? And if so, can we replace them? I think it will be best to drop tromey, as it sometimes causes significant delays.

**Comment by syl20bnr** [comment]
I'm for removing tromey, the less archive we get the better. I strongly believe that using multiple archives does not worth it, as long as MELPA is highly active it will always be the best ecosystem of packages, introducing other repos is just adding noise (with the exception of very specific repos that have authority like org).

**Comment by syl20bnr** [comment]
offtopic: MELPA is tailored for community-driven approach. For stability it remains only one thing to address to Spacemacs: having a stable initial state of packages for first installers.

**Comment by kendall** [comment]
FWIW, I get hangs on tromey.com that are sometimes quite lengthy.

+1
