### ISSUE TITLE
hangs/freezes when doing `<space> p f` without an open project

### ISSUE THREAD

**Issue by xxv** [syl20bnr/spacemacs#2090]
To reproduce, launch spacemacs and immediately type `<space> p f`.

This is release 0.102.x.

**Comment by xxv** [comment]
Still occurs on 0.103.x.

**Comment by d12frosted** [comment]
@xxv Does it still occur? For me it says that I am not in project.

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.

**Comment by xxv** [comment]
Ah, whoops. Yes, it still occurs. I just tried it on a fresh checkout of spacemacs into `~/.emacs.d/` and it froze. It said on the bottom:

> Empty cache. Projectile is initializing cache...

And sat there, forever. Also, it looks like it was running `find` which is taking forever and all my CPU.

**Comment by StreakyCobra** [comment]
@xxv Can you please open a new issue following [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) :smiley ? A new issue will have more visibility, and following the template will give us more information such as your installation details and a reproduction guide! Thx
