### ISSUE TITLE
Guide key window not fully displayed

### ISSUE THREAD

**Issue by codygman** [syl20bnr/spacemacs#2209]
It seems to work fine when I only have one buffer open, but if I have two open it looks like this:

![spacemacs-guide-key-display-issue](https://cloud.githubusercontent.com/assets/225847/8504839/fd62950a-219d-11e5-9588-cf897dd0db97.png)

You can see that all of the options aren't displayed. Is this expected? If so how do I scroll to see more of the guide key options?

**Comment by StreakyCobra** [comment]
@codygman Does your problem still appear on the last release? We are using `which-key` now, it probably has changed.

**Comment by codygman** [comment]
Will check after work

**Comment by StreakyCobra** [comment]
:+1:

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for close to one month now. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
