### ISSUE TITLE
Spacemacs-theme doesn't show up with already existing .spacemacs

### ISSUE THREAD

**Issue by nashamri** [syl20bnr/spacemacs#2235]
Hello,

@travisbhartwell noticed this issue and this is what I did to reproduce it:
1- Start afresh.
2- Run spacemacs on develop for the first time works fine.
3- By deleting `.emacs.d` and keeping the `.spacemacs` and removing `spacemacs-dark` line from it.
4- Installing spacemacs again but now since there's a `.spacemacs` file which doesn't mention the spacemacs theme, it fails to show up when `SPC T h`

This could be an issue when updating from `0.103` to `0.104`

**Comment by travisbhartwell** [comment]
A little more details.  I'm running `develop`.  If I leave my `dotpspacemacs-themes` the default, like this:
```elisp
   dotspacemacs-themes '(spacemacs-dark
                         spacemacs-light
                         solarized-light
                         solarized-dark
                         leuven
                         monokai
                         zenburn)
```
The spacemacs themes are loaded.  But, even if I leave the spacemacs themes in, but make something else the first on the list, like this:

```elisp
  dotspacemacs-themes '(misterioso
                         spacemacs-dark
                         spacemacs-light
                         solarized-light
                         solarized-dark
                         leuven
                         monokai
                         zenburn)
```

When I hit SPC T h, spacemacs-dark or spacemacs-light doesn't show up.

I did just notice that if I hit SPC T n, it will switch to them, to this seems to be a product of loading on demand.

**Comment by syl20bnr** [comment]
Oh I see, it must be listed in the packages.el of Spacemacs layer, I forgot about this sorry.

This is a good place to set explicitly the configuration variables as well, even if the values are the default one it gives some kind of additional documentation about the configuration variables available for the themes.

**Comment by sooheon** [comment]
I am seeing the same issue for zenburn as well.

**Comment by syl20bnr** [comment]
For zenburn and monokai I removed them from the dotfile template because they are not part of spacemacs core.
For anyone wanting to do it I suggest to improve `themes-megapack` layer by adding a new layer variable called `themes-megapack-popular-themes-only`. Or it could be a brand new layer called `popular-themes` and I could even add this layer commented in the dotfile template.

Now for the core of the issue we are facing here there is only one solution which is to add the used themes in a private layer to ensure that there are downloaded and available at any point in time. We should document this.
