### ISSUE TITLE
A suggestion for "don't create backup~ files" in spacemacs/config.el

### ISSUE THREAD

**Issue by xfq** [syl20bnr/spacemacs#2271]
In [spacemacs/config.el](https://github.com/syl20bnr/spacemacs/blob/8e97a740265130b7a96ad7d57595af49f95030be/spacemacs/config.el#L223-L226):

```elisp
;; don't create backup~ files
(setq backup-by-copying t
      make-backup-files nil
      create-lockfiles nil)
```

I suggest changing it to:

```elisp
;; don't create backup~ files
(setq make-backup-files nil)
```

I understand the rationale for setting `make-backup-files` to `nil` (although the default value of `vc-make-backup-files` is already `nil`), but I think it isn't necessary to change the value of `backup-by-copying` and `create-lockfiles`. Here are my reasons:

* The value of `make-backup-files` is already `nil`, so changing the value of `backup-by-copying` won't have any effect.
* IMHO lockfiles are more important than backup files since they can prevent concurrent changes.

**Comment by geo7** [comment]
@TheBB Is this still relevant? Aren't backups sent to `cache` or something now? 

If not then Suggestions / discussion tag might fit here.

**Comment by xfq** [comment]
It's still relevant.

Although `spacemacs-auto-save-directory` is in `spacemacs-cache-directory` by default, whatever I said in the original post is irrelevant to the auto-saving feature, and is still true in the current `develop`.

**Comment by StreakyCobra** [comment]
@xfq Can you propose your change in a PR? It would be better discussed there.

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
