### ISSUE TITLE
Cannot move down with C-n in Magit

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#2277]
`magit-section-forward--evilified-magit-mode-map-C-n` is bound to `C-n`, but pressing it in Magit does not go to next line with Emacs style, while it's supposed to be.

**Comment by syl20bnr** [comment]
Can you confirm that it works inside sections ? Is this limited to part of the buffer with no section ?

**Comment by syl20bnr** [comment]
Actually this is the expected behavior, you don't need `C-n` in holy-mode, it is just `n`. In emacs state the stock magit key bindings just works. 
Now I realize that the remapping creates a lot of noise with `SPC  ?` so I should find better function names.

Right now the function names have 2 possible forms:
-  `x-or-y--evilified...` where `x` is for emacs state (or any other state which is not evilified) and `y` is for evilified.
- `y-evilified...` where `y` is for evilified and `y` does nothing in other state.

Not easy to find some naming rules to make it clear.

Now I'm aware of this I'll be able to think about a better way to handle the remapping. I think I will store the stock unmodified maps in order to use/restore them in emacs state, and put some function to convert them on the fly when at editing style switching time and initialization time.
May be quite some work though.

**Comment by tuhdo** [comment]
But `C-p` works normal. Without it, I cannot move down a line inside the hunk, since `n` skips to the next hunk.

**Comment by osener** [comment]
Not being able to use <kbd>C-n</kbd> is quite serious since it is used to mark and stage individual lines, which is a fundamental part of magit workflow.

Btw, <kbd>C-v</kbd> is also broken.

**Comment by sixpi** [comment]
This is broken for me too.

**Comment by justbur** [comment]
After #3578, magit will no longer be evilified and this should be resolved
