### ISSUE TITLE
spacemacs does not use PATH from nix-shell

### ISSUE THREAD

**Issue by ublubu** [syl20bnr/spacemacs#2294]
I have a nix-shell set up for my haskell project. I want to run spacemacs in this nix-shell so it has access to all the project's dependencies and matching tools - i.e. ghc, cabal, ghc-mod, lens, mtl, etc

nix-shell configuration: https://gist.github.com/ublubu/e99f7b3282e7c236ac1b

In nix-shell, my PATH has everything I need. In particular, it has this:
`/nix/store/mr9s0r4bxb85vqh6i7l0as2nxq7fr492-ghc-7.8.4/bin`

If I run a vanilla emacs from the nix-shell (by typing `emacs [RET]` after moving `~/.emacs.d`), its exec-path contains everything I expect (`C-h v exec-path [RET]`). However, when I run spacemacs (typing `emacs [RET]`), its `exec-path` does not. Furthermore, the "original value" listed by `<SPC> h d v "exec-path"` does not contain the expected paths.

I also tried, just for the sake of exploration, adding a line akin to https://github.com/ianbattersby/dotfiles.emacs/blob/master/spacemacs.symlink#L171
in my `.spacemacs` file:
`(add-to-list 'exec-path "/nix/store/mr9s0r4bxb85vqh6i7l0as2nxq7fr492-ghc-7.8.4/bin")`
But that entry didn't show up in my `exec-path` either.

This is probably redundant, but I also tried this after seeing `exec-path-from-shell`:
If I run `$SHELL -c "echo $PATH > blah.txt"` in spacemacs and emacs, the results match their respective `exec-path` values.

How can I get spacemacs to pick up PATH from the environment where it is invoked - the way plain emacs does?

**Comment by ublubu** [comment]
FWIW, the "original value" of `exec-path` in spacemacs is the same outside the nix-shell (started from a normal terminal) as it is inside the nix-shell. It seems like spacemacs is unaware of the nix-shell it is started in - in addition to nuking the "original value" (Where/When does this happen?).

**Comment by ublubu** [comment]
https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L1035

Found it. Once I disable the initialization of `exec-path-from-shell` (e.g. by deleting `x` from the condition), the `nix-shell` path is used as expected. What do we need `exec-path-from-shell` for? Is it safe to turn off? In this case, at least, it doesn't even do what it's supposed to do.

**Comment by jb55** [comment]
It's used in osx when launching from the app so that the paths are set up correctly. I ran into the same nix path issue as well and it took me awhile to figure out how to fix it.

Us nix users are probably the minority though, it would be great if someone started some nix with spacemacs documentation.

**Comment by ublubu** [comment]
@jb55: Hahaha where were you five days ago / did you already file an issue for this? But seriously, I like this idea about docs. What other issues have you run into? It sounds like (?) you've been at this longer than I have. Want to start the docs?

everyone: If `exec-path-from-shell` is only needed for OSX, why do we use it everywhere else, too?

**Comment by travisbhartwell** [comment]
+1 on the Nix with Spacemacs documentation.

Fellow Nix user here.  Nafai on #nixos on Freenode.  Would love to collaborate on docs and figuring out this stuff.  Particularly the best strategies for doing Haskell and Python development (which would be the two I'm most likely to do) on Nix OS with Spacemacs.

**Comment by travisbhartwell** [comment]
Regarding docs, would it be useful to create another issue to track issues that we need to figure out and document?

**Comment by CestDiego** [comment]
What about this? https://github.com/purcell/exec-path-from-shell

**Comment by ElessarWebb** [comment]
+1 Very annoying bug

**Comment by travisbhartwell** [comment]
To get around this, I have added `exec-path-from-shell` to my `dotspacemacs-excluded-packages` list:

```emacslisp
   dotspacemacs-excluded-packages '(exec-path-from-shell)
```

Since we now have a nixos layer, would it be reasonable to add `exec-path-from-shell` to the excluded packages of that layer, since this is likely the right thing for all Nix OS users?

If there is consensus that this is the right thing to do, I can make a pull request making that change.

**Comment by StreakyCobra** [comment]
@ublubu (and @travisbhartwell maybe) We are doing a cleanup of issues. Is this one still valid? If not, it would be nice if we can close it. If yes, it seems an easy PR can solve it, could anyone create it? Thanks :smile:

**Comment by travisbhartwell** [comment]
I don't currently have the workaround in place as [mentioned above](https://github.com/syl20bnr/spacemacs/issues/2294#issuecomment-131552605), so this is with a somewhat default configuration.  I just did a quick test by launching Spacemacs from within a `nix-shell` and indeed `exec-path` is incorrect, it is the original PATH value (I'm assuming of a bash login shell) and not what is set in the nix-shell environment it is launched from.

Unfortunately, just excluding `exec-path-from-shell` isn't a good solution because other layers that could be used on Nix OS rely on it -- the rust layer, for example.  That's why I reverted the work around I mentioned previously.

I'll need to look into this more closely to see what's the appropriate way to work with this.

**Comment by StreakyCobra** [comment]
@travisbhartwell :+1: Thanks for the feedback, It is indeed a bug :smile:

**Comment by joefiorini** [comment]
A few months later, but fwiw I had the same issue in Fish shell on OSX. Adding `exec-path-from-shell` to `dotspacemacs-excluded-packages` fixed it for me.

**Comment by jb55** [comment]
So the problem with adding `exec-path-from-shell` to excluded packages is that some layers seem to require it, such as rust and go. This is kind of awkward, which means I can't use these layers.

**Comment by CestDiego** [comment]
This is something that should be addressed by @syl20bnr if it really has to
do with package dependencies in layers

On Thu, Feb 18, 2016, 10:54 PM William Casarin <notifications@github.com>
wrote:

> So the problem with adding exec-path-from-shell to excluded packages is
> that some layers seem to require it, such as rust and go. This is kind of
> awkward, which means I can't use these layers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/2294#issuecomment-186040619>
> .
>
-- 
Diego Berrocal
http://cestdiego.github.io

**Comment by StreakyCobra** [comment]
@jb55 You can try what I've explained [here](https://github.com/syl20bnr/spacemacs/pull/5024#issuecomment-183136832), i.e. to modify `exec-path-from-shell` to only set variables like `GOPATH`, `RUST…`, etc… so that `PATH` is not modified.

**Comment by cdepillabout** [comment]
I ran into this as well.  I'm not using NixOS.  I'm using `nix` on Arch Linux.

I imagine that `exec-path-from-shell` is nice to have for users on OSX, but as a Linux user it feels very unintuitive.  As a novice emacs user, it took quite a long time to figure out why my PATH was being overwritten.

I feel that something unintuitive like `exec-path-from-shell` should be opt-in rather than opt-out (at least for Linux users).

**Comment by bfrog** [comment]
I was just bit by this bug, very very annoying to even discover.

**Comment by Rotaerk** [comment]
Ditto

**Comment by siddharthist** [comment]
None of the above-mentioned workarounds solve the problem for me. Bizarrely, [this StackOverflow answer](https://stackoverflow.com/questions/33188054/get-spacemacs-emacs-gui-version-to-recognize-nix-shell-environment) did:
```bash
nix-shell --pure shell.nix
emacs --daemon
emacsclient -c -a emacs
```

**Comment by JonathanReeve** [comment]
@siddharthist, could you explain how to use emacs-direnv? Here's what I've tried: 

1. Putting `use_nix shell.nix` in the `.envrc` in my project's root (which has a shell.nix). 
2. Installing `direnv`. 
3. Running `direnv allow` in the project root. 
2. Installing `emacs-direnv`, then enabling `direnv-mode`. 
4. Running `M-x direnv-update-environment`

Am I missing something? I still can't get it to work. I'm running emacs in daemon mode as a system service, by the way, in NixOS.

**Comment by seanparsons** [comment]
I'm using `direnv` without the Emacs plugin and I can see GHC in `exec-path`, but when something like Dante or company-ghci try to run cabal then it fails because cabal can't see GHC.

**Comment by siddharthist** [comment]
@seanparsons When using Dante, you can put this in a `.dir-locals` file:
```
((haskell-mode
  . ((dante-repl-command-line . ("nix-shell" "default.nix" "--pure" "--run" "cabal new-configure && cabal repl lib:your-lib-here --builddir=dist/dante")))))
```

**Comment by seanparsons** [comment]
@siddharthist You hero!

**Comment by langston-barrett** [comment]
Still valid.

**Comment by zeta-00** [comment]
@langston-barrett , adding: use_nix shell.nix to .envrc works, but for some reason it opens another emacs application with everything working correctly, that defeats the purpose of using `lorri+direnv+emacs-direnv` with the `lorri shell` command.

Is there a way to get this `use_nix shell.nix` command in .envrc working with this setup without having to spawn another emacs application? with all my other shell.nix projects, after i initialize everything in a shell in emacs(M-x shell), then, all i need to do is run `lorri shell` and everything works correctly, but for some reason i'm only having issues when running ihaskell with emacs-ipython-notebook in emacs(M-x ein:run), for some reason it is not detecting jupyter? that's why i'm here trying to find a correct fix for this issue.

**Comment by zeta-00** [comment]
@langston-barrett , i think this `exec-path-from-shell` is only for osx users, so i don't think that i need to set it up(it looks to complicated as well):

https://github.com/purcell/exec-path-from-shell

**Comment by magthe** [comment]
I can't seem to get this to work either...

Added this to `~/.spacemacs`:

```
   dotspacemacs-additional-packages
   '(direnv
    ...)
```

and put a `.envrc` in a folder with a `shell.nix`:

```
use_nix shell.nix

export FOOBAR=foobar
```

then I start Emacs and open `dired` in the folder.

Now for the strange bit. `FOOBAR` _is_ set, but nothing relating to Nix is. No `PATH`/`exec-path` changes, none of the numerous envvars that get set when I `cd` into the folder in a shell are set.

Is it `use_nix` that is broken in some way?

**Comment by magthe** [comment]
Just thought I'd report that I've managed to get _emacs-direnv_ to work with `nix-shell`+`direnv` on my Arch box. Keeping an eye on the `*direnv*` buffer and solving issue by issue popping up there was the key to my success.

My layer for `direnv` looks like this:

`packages.el`:
```
(defconst direnv-packages
      '(direnv))

(defun direnv/init-direnv ()
  (use-package direnv
    :init
    (progn
      (direnv-mode))))
```

**Comment by blablablerg** [comment]
weird bug, I can get it to work running emacs as daemon or using emacs -nw.

**Comment by blablablerg** [comment]
hmm.. I managed to make it work by commenting `(spacemacs/load-spacemacs-env) ` out in the spacemacs dotfile, leaving `defun dotspacemacs/user-env ()` empty. 

Everything seems to work fine so far.. does this have any other unforeseen impact?

**Comment by davidpa9708** [comment]
still an issue,

> To get around this, I have added `exec-path-from-shell` to my `dotspacemacs-excluded-packages` list:
> 
> ```
>    dotspacemacs-excluded-packages '(exec-path-from-shell)
> ```
> 
> Since we now have a nixos layer, would it be reasonable to add `exec-path-from-shell` to the excluded packages of that layer, since this is likely the right thing for all Nix OS users?
> 
> If there is consensus that this is the right thing to do, I can make a pull request making that change.

this seems to be the solution
