### ISSUE TITLE
[search-engine] Request: search visually selected text or/and whole line at point

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#2311]

**Comment by endrebak** [comment]
I think we are meant to be able to search for visually selected text with `*` and that we are not because of a bug.

To search for selected text, you may use `SPC s S`, but it only seems to work if the string isn't too long. To edit the `helm-swoop` results use `C-c C-e` and then save when finished.

`helm-swoop` is nicer in some ways because it can find all matches in all open buffers. 

You can also use the above to edit all matches in a project with `helm-ag` and then `C-c C-e` (insanely nice feature: you change all instances of the search string in the whole buffer).

**Comment by xged** [comment]
You missed the layer of the question (search-engine).
I found that useful nonetheless. :)

**Comment by endrebak** [comment]
Oh, did not see the brackets. Glad it wasn't a complete waste of time though.

**Comment by felipe-barros** [comment]
Wow, that was a very nice tip! Thanks!
