### ISSUE TITLE
Placement of auto-completion spawned modal dialogs/etc

### ISSUE THREAD

**Issue by ianbattersby** [syl20bnr/spacemacs#2316]
Noticed in the recent release that the placement of modal dialogs seems to have lost it's placement intelligence (on 99% of occasions). @cpaulik suggested opening this issue as it seems I'm not alone in witnessing this behaviour.

![2015-07-14-081643_1600x900_scrot](https://cloud.githubusercontent.com/assets/185776/8669135/c9159c24-2a09-11e5-833b-0f7160c547e9.png)

*Note:* Running on 'develop' branch, pulled this morning to verify problem still exists.

**Comment by ianbattersby** [comment]
NB: I've also seem some weird behaviour on @nosami's config that offsets the first row of the auto-completion dialog - will try and source a screenshot.

**Comment by nosami** [comment]
Not sure if this is the same issue or not. I have a an issue when company triggers on the same line that has a flycheck error.

<img width="971" alt="screen shot 2015-07-14 at 19 18 02" src="https://cloud.githubusercontent.com/assets/667194/8681081/4527ef08-2a5d-11e5-94fd-ef9cfe27166b.png">

I'm only just getting started with spacemacs though.... more than likely this error is because of something I put in my [.spacemacs](https://github.com/nosami/configs/blob/master/.spacemacs#L197-L202) file

**Comment by nosami** [comment]
I fixed my issue with this

```elisp
  (setq flycheck-display-errors-function 'my-flycheck-pos-tip-error-messages)

(defun my-flycheck-pos-tip-error-messages (errors)
  (when (not (company-search-mode))
    (flycheck-pos-tip-error-messages errors))
  )
```

Now I can have company mode and on the fly syntax checking and inline errors :D

**Comment by EricCrosson** [comment]
@nosami, I think you found a subtler yet similar bug. 

@ianbattersby, I fixed my tooltip-overriding-choices problem with the following code
```lisp
(defun company-quickhelp--show ()
      (company-quickhelp--ensure-compatibility)
      (company-quickhelp--cancel-timer)
      (let* ((selected (nth company-selection company-candidates))
             (doc (company-quickhelp--doc selected))
             (ovl company-pseudo-tooltip-overlay)
             (overlay-width (* (frame-char-width) (if ovl (overlay-get ovl 'company-width) 0)))
             (overlay-position (* (frame-char-width) (- (if ovl (overlay-get ovl 'company-column) 1) 1)))
             (x-gtk-use-system-tooltips nil))
        (when (and ovl doc)
          (with-no-warnings
            (pos-tip-show doc nil (overlay-start ovl) nil 300 80 nil (+ overlay-width overlay-position) 1))))))
```
This was available as some patch into the company files, but as I'm not in complete control (yet) over which source the layer-installer grabs packages from, patching the company file directly didn't click in my mind as a viable option. Instead I redefined the method in my configs, which had the desired effect: tooltips no longer overlap the box of choices. 

Since both of these are now solved, we should be close to closing this issue!

**Comment by ianbattersby** [comment]
Awesome! Many thanks :)

**Comment by StreakyCobra** [comment]
As @ianbattersby's and @nosami's issues were solved long time ago, and nobody else reported them in the meantime, I'm closing this issue. Feel free to open a new issue in case of troubles :relaxed:
