### ISSUE TITLE
Org mode speed keys 

### ISSUE THREAD

**Issue by recifx** [syl20bnr/spacemacs#232]
Request enhancement to have org mode speed keys operational in orgmode buffers.

**Comment by StreakyCobra** [comment]
I don't know "speed keys", but what I read [there](http://orgmode.org/manual/Speed-keys.html) indicates that it's only a matter of customizing a variable to make it work. This issue is more than one year without any message, so there is not enough interest to enable it in spacemacs for now, especially as it could be an unwanted behavior for most users. I'm closing this issue then.
