### ISSUE TITLE
New feature. Env from shell.

### ISSUE THREAD

**Issue by jvillasante** [syl20bnr/spacemacs#2331]
This would be a nice addition I think:
https://github.com/purcell/exec-path-from-shell

It has to execute early for other packages to load.

Currently I have something like this in my .spacemacs
```
  (defun set-PATH-from-shell-PATH ()
    (let ((path-from-shell (shell-command-to-string "$SHELL -i -c 'echo $PATH'")))
      (setenv "PATH" path-from-shell)
      (setq exec-path (split-string path-from-shell path-separator))))
  (defun set-GOPATH-from-shell-GOPATH ()
    (let ((gopath-from-shell (shell-command-to-string "$SHELL -i -c 'echo $GOPATH'")))
      (setenv "GOPATH" gopath-from-shell)
      (setq exec-path (split-string gopath-from-shell path-separator))))
  (if window-system (set-PATH-from-shell-PATH))
  (if window-system (set-GOPATH-from-shell-GOPATH))
```
This load both $PATH and $GOPATH which I'm using, I would like to be able to write a function but I don't know lisp. Something like this:

```
(defun set-variable-from-shell (variable)
...)

(if window-system
  (set-variable-from-shell("PATH"))
  (set-variable-from-shell("GOPATH)))
```

Or better yet, integrate purcell package. Any help here??

**Comment by jb55** [comment]
`exec-path-from-shell` is [already included](https://github.com/syl20bnr/spacemacs/blob/93e3b883c061c1fd685e9ef588b979704ca95c78/spacemacs/packages.el#L1032-L1035) in the base spacemacs packages. 

It's strange that it's not picking up your path correctly...

One thing to note is I've had to add `exec-path-from-shell` to my `dotspacemacs-excluded-packages` list when launching from the terminal, because `exec-path-from-shell` ignores the inherited path and tries to do its own thing.

**Comment by StreakyCobra** [comment]
As said, `exec-path-from-shell` is already integrated within spacemacs. Some documentation has also been added about this `exec-path-from-shell` in some layers (`go`, `rust`, `osx` at least). I'm closing the issue as it's main objective is solved. But feel free to open other issues if you are encountering bugs with it :smile:
