### ISSUE TITLE
`u` cannot undo emmet-expand-yas insertion

### ISSUE THREAD

**Issue by louy2** [syl20bnr/spacemacs#2351]
Reproduce steps:
1. `web-mode`
2. Type `html:5`
3. Hit `TAB`, confirm the snippet is expanded
4. Hit `ESC` to return to normal state
5. Hit `u`

Expected:
Snippet is deleted.

Actual:
Snippet stays.

_Messages_:

```
[yas] Snippet 2 exited.
Undo branch point!
```

`undo-tree-visualize` shows that two branches seemingly identical are created right after the snippet is expanded.

**Comment by felipe-barros** [comment]
I can confirm this.

**Comment by Devagamster** [comment]
This is probably an issue with emmet-mode not spacemacs, and so an issue could be created here: https://github.com/smihica/emmet-mode

**Comment by StreakyCobra** [comment]
I can't reproduce it any longer, not on `develop` nor on `master`. Is someone still encountering this issue?

**Comment by louy2** [comment]
Still having this problem. Let me update everything and see.

**Comment by StreakyCobra** [comment]
Ok now I can reproduce it, but I can't tell what was the difference since last time. Doing `SPC a u` to open the undo tree, it seems expending is doing an additional step (indenting the region)  just after. When pressing `u`, this indenting is undone, but redone just after, making it impossible to go further back in history.

**Comment by louy2** [comment]
Oh, that's why. I remembered that single-line expansions are free of this problem. Why is the indenting redone just after?

**Comment by StreakyCobra** [comment]
No idea :stuck_out_tongue:
