### ISSUE TITLE
neotree crashing when using scp?

### ISSUE THREAD

**Issue by smoh** [syl20bnr/spacemacs#2395]
When I scp into a remote directory / open a remote file, and hit `SPC f t` or `SPC p t`,
the emacs seems to crash / hang forever until I "force quit" the process on osx yosemite.
I'm using the latest version of spacemacs.
Can anyone comment on this?

**Comment by d12frosted** [comment]
Does it still happen for you?

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
