### ISSUE TITLE
HTML & JavaScript merge into Web? Or new React layer? Discussion of layering

### ISSUE THREAD

**Issue by louy2** [syl20bnr/spacemacs#2400]
Cont. #2286 
Rel. #2399 #1769 #1770 

The reason emerged when I am configuring JSX, where I want indentation and syntax-highlight from `web-mode` but completion from `tern-mode`. To do that, either duplicated config of the `tern` is introduced in both `javascript` and `html`, or the layers in question are merged into one, `web`.

As @robbyoconnor has put, JavaScript being in a separate layer benefits Node.js users. Although popularized by web, JavaScript is indeed used in pure CLI's such as [Keybase](https://github.com/keybase/node-client). 

I have tried writing a separate layer as #2399 does as well as putting JSX into HTML layer. I do want to attract notice that #2399 actually introduces `!framework` category, which is another discussion we might have. In this case it is another form of duplication, where `react` layer shares some config with both `javascript` and `html`.

**Comment by robbyoconnor** [comment]
There are DOZENS of JS frameworks and new ones popping up left, right and center...

**Comment by robbyoconnor** [comment]
Sigh ;/ I dunno what to think here.

**Comment by cmccloud** [comment]
I'm in favor of keeping the layers separate. React isn't the first framework to introduce a new language which compiles to html or js; configuration targeting framework specific syntax is likely to need updating at a faster pace than configuration for either javascript or HTML, and we don't know whether competing frameworks will introduce incompatible syntax.

**Comment by louy2** [comment]
Upon closer look into #2399 I realized that duplicates are not necessary as long as:

1. the framework layer depends on other more general layers
2. the conflicts between the more general layers are resolved at source (best) or hacked at the framework layer (risk inconsistent behavior)

It is a space of configuration offered by a major-mode shared by several layers. Considering this, merging seems to defeat the purpose of layering, returning it to major-mode defined borders. Surely we have to be careful in resolving conflicts and tracking changes among several files if we choose to divide things up.

**Comment by louy2** [comment]
Problem still is that keybindings don't follow their minor modes, but bound by major mode. So duplication of keybinding in this case is inevitable.

**Comment by louy2** [comment]
I missed one thing: merging into a web layer is grouping two major modes. It's also breaking the major mode defined border. 
@cmccloud Syntax is really not the concern here. Current HTML mode handles erb, haml, jade, slim, etc. because web-mode was created for these. Current JavaScript layer handles coffeescript as well. It is not obvious that a different syntax leads to a different layer.

**Comment by axyz** [comment]
I think jsx is way more a js layer than a web layer. Web-mode is great for syntax highlight and correct indentation and autoclosing of tags and other small things, but i guess that js2 keybindings should have precedence on a conflicting scenario as jsx is in fact javascript with just a bit of xmlish syntax. The problem would then be how to synchronize the js2 layer keybindings with the hypothetical react's one. Is there a way to import keybindings from a required layer? 

maintaining them equal by hand it's not a viable solution on the long run i fear.
the other possibility would be to just select a subset of all those keybindings as well as adding some others that may be useful with jsx (also something from web-mode for example), but then it would be hard to decide what not to include from the js2-layer.

The other possibility would be to just select a subset of all those keybindings as well as adding some more that may be useful with jsx (also something from web-mode for example), but then it would be hard to decide what not to include from the js2-layer.

For my day to day work I do not use all the js2 keybindings, but we should surely try to include them all.

I don't know spacemacs intarnals yet, would it be feasible for example to load a layer, read its keybindings and set them on demand on the current layer?

**Comment by louy2** [comment]
@axyz The best JSX support now IMO is [babel-sublime](https://github.com/babel/babel-sublime). If only I can port it to be a major mode...

**Comment by CestDiego** [comment]
The author of web-mode said he'd be supporting more react in the next release, I think we should wait for that

**Comment by axyz** [comment]
@CestDiego well web-mode is already quite good with react and any additional support will be useful, but what is missing is the IDE features of js2 so we'll be facing the same issue I fear. 

I'm wondering of it would be feasible to have dedicated minor modes for things like tern with his own keybindings and just create the react layer with webmode plus those minor modes avoiding the problem to have the keybindings for tern on the js2 mayor mode. We can then have configuration options to use eslint, flow, etc...

@louy2 I think it would need a big community effort, or at least I'd have no idea of where to start :smile: however trying to convert the oceanic-next colorscheme would also be interesting as it seems optimized for babel looking js

**Comment by syl20bnr** [comment]
I propose to keep the `html` and `javascript` layers and to create a new layer `react` in the `!framework` category even if `react` is not a complete framework.

`tern` init function stays in the `javascript` layer, in the `react` layer we can add `tern` with an associated `post-init` function where we define any hook we need. It is possible to extend/override the tern configuration thanks to `use-package` hooks. This stuff has been added to spacemacs recently and are not documented yet, I will just point you to existing snippets in the code base instead:

1) adding a hook for a package that is initialized in another layer: flycheck

```elisp
(defun python/post-init-flycheck ()
  (add-hook 'python-mode-hook 'flycheck-mode))
```

The hook is declared in a `post-init` function which is evaluated only if a `init` function has been found. The `init` function for flycheck is in the `syntax-checking` layer which means that if this layer is not used then `python/post-init-flycheck` won't be evaluated. Also a package is considered `used` (ie must be installed) if and only if there exists a `init` function. In the case where the `syntax-checking` layer is not used, the `init` function won't be defined so flycheck won't be installed.

2) extending `:init` and `:config` code blocks of use package: magit extensions in `shell` layer

```elisp
(defun elixir/pre-init-popwin ()
  (spacemacs|use-package-add-hook popwin
    :post-config
    (push '("*mix*" :tail t :noselect t) popwin:special-display-config)))
```

In this example, `popwin` package is added to the `elixir` layer and its configuration is associated to a `pre-init` function which is executed before any `init` function. It also means that this `pre-init` function is evaluated only if `popwin` is actually used. But the meat of this example is `spacemacs|use-package-add-hook` which allows to insert stuff at the beginning or end of `:init` and `:config` code blocks defined in the `use-package` form in the `init` function. Here we must use a post-config hook because popwin is lazy loaded and the variable `popwin:special-display-config` will be defined only when popwin is actually loaded.


With these tools I think we can achieve a react layer that rely on packages defined in other layers.

**Comment by axyz** [comment]
so let's see if I've understood: on #2399 I'm correctly using `react/post-init-flycheck` and `react/post-init-web-mode` however I should try to move `tern-mode` and `js2-minor-mode` out of `post-init-web-mode` and use instead something like `post-init-js2-mode` and `post-init-tern-mode` where I check for extension and initialize the modes.

Then I should use `pre-init-tern-mode` to extends tern config and eventually set keybindings?

If I've got it, the problem, may be that actually tern's keybindings are inside `js2-mayor-mode` so, will I be able to edit them using `pre-init-tern-mode` ? Or are you suggesting to just use that function to configure tern and then rewrite the keybindings on react layer `use-package` `:config` section?

**Comment by syl20bnr** [comment]
@axyz Yes you are correct.

You have to use `react/pre-init-tern` and `spacemacs|use-package-add-hook tern :post-config` to add the modified bindings at the end of the config block.

We can avoid the need for `spacemacs|use-package-add-hook` though. Evaluating a key binding expression with `evil-leader/set-key-for-mode` does not require the symbols to exist. So we could move the key bindings from `:config` to `:init` and then a simple plain `react/post-init-tern` without `spacemacs|use-package-add-hook` would work.

But using directly the `:post-config` hook of `use-package` is more robust since it should always work. In my previous paragraph the configuration will break if we add something that require some symbols from term to be defined (since term is lazy loaded and `react/post-init-tern` is execute at spacemacs initialization time, before term is actually used).

**Comment by axyz** [comment]
great from the first tests it seems to work like a charm.

However obviously there are a lot of conflicting keybindings with web-mode, My idea is to give precedence to js2 keybindings (loosing some xml manipulation functionality is not that bad when working with jsx) also I think that having new prefixes will just generate confusion when switching from a js to a jsx file.

So assuming that we want to override some web-mode keybindings what is the cleaner way to do it inside `:post-config` ?

for example if I have a command on `SPC a b c` on web-mode and I try to set something from js2-mode on `SPC a b c d` using `evil-leader/set-key-for-mode` it gives me an error instead of overwriting the prefix. Is there a command to firstly unset a keybindings or a command to directly overwrite it?

Do you agree with this kind of policy? to maintain seamless keybindings with js2-mode loosing some web-mode benefits? was it done before on other layers?

**Comment by axyz** [comment]
@syl20bnr The layer it's now way better thanks to your advice. However I'm still unsure on a point:
adding keybindings with `set-key-for-mode` on `:post-config` will add those keybindings "system-wide" so for example I get tern keybindings on all `web-mode` layers, in fact I only want them when editing `jsx` files.

Is there a way to conditionally create or remove keybindings from a layer? Is this addressed on other layers?

**Comment by louy2** [comment]
@axyz 
You can wrap the keys in a function that checks `jsx` and add it to `web-mode-hook`.

**Comment by axyz** [comment]
I've tried something like that... But after the hook will run once, won't
the keybindings remain on all future web-mode hook?

Il giorno 18:01 mar 28/lug/2015 Yufan Lou <notifications@github.com> ha
scritto:

**Comment by louy2** [comment]
@axyz 
Until restart, yes. `evil-leader/set-key-for-mode` sets the key in `evil-leader--mode-maps`. If you want to remove it you'd want to hack there, since `evil-leader` doesn't offer a remove function.

All the problems stem out from the fact that Emacs regards one major mode as a file type. It does have a mechanism of inheritance for major mode though.

**Comment by axyz** [comment]
@louy2 my last commit on #2399 should solve all the previous problems.

**Comment by TheBB** [comment]
I'm assuming the new react layer has brought this discussion to a close for now.
