### ISSUE TITLE
Proposal: New JavaScript Layer Keybindings

### ISSUE THREAD

**Issue by louy2** [syl20bnr/spacemacs#2420]
This is a dramatic change and will break habits used to the old ones. I just think the old ones did not conform to the conventions enough. Considering this all started because one of them conflicted with a planned #2399 JSX layer keybinding, this might be overkill, but whatever. If people like this then it will be implemented, if not then ad-hoc adjustment involving only `rename-variable` will be performed.

```
;; toggle (should be a group but only one member)
"mT" 'js2-mode-toggle-warnings-and-errors

;; folding
"mzc" 'js2-mode-hide-element
"mzo" 'js2-mode-show-element
"mza" 'js2-mode-toggle-element
"mzr" 'js2-mode-show-all
"mzF" 'js2-mode-toggle-hide-functions
"mzC" 'js2-mode-toggle-hide-comments

;; change (c is taken by compile)
"mCf" 'js2r-toggle-function-expression-and-declaration
"mCi" 'js2r-ternary-to-if
"mCo" 'js2r-arguments-to-object
"mCt" 'js2r-var-to-this
"mCv" 'js2r-rename-var
"mCp" 'js2r-localize-parameter
"mCV" 'js2r-inline-var

;; join/join
"mjja" 'js2r-contract-array
"mjjf" 'js2r-contract-function
"mjjo" 'js2r-contract-object
"mjjs" 'js2r-split-string
"mjjn" 'js2r-forward-slurp

;; join/split
"mjsf" 'js2r-expand-function
"mjsa" 'js2r-expand-array
"mjso" 'js2r-expand-object
"mjsv" 'js2r-split-var-declaration
"mjss" 'js2r-split-string
"mjsl" 'js2r-forward-barf

;; Surround (s taken by REPL)
"mSu" 'js2r-unwrap
"mSf" 'js2r-wrap-in-for-loop
"mSp" 'js2r-introduce-parameter
"mSl" 'js2r-log-this
"mSd" 'js2r-debug-this
"mSF" 'js2r-extract-function
"mSM" 'js2r-extract-method
"mSV" 'js2r-extract-var
"mSE" 'js2r-wrap-buffer-in-iife

;; insert/documentation
"midf" 'js-doc-insert-function-doc
"midf" 'js-doc-insert-file-doc
"midt" 'js-doc-insert-tag
"midT" 'js-doc-describe-tag
"midg" 'js2r-add-to-globals-annotation
"mig" 'js2r-inject-global-in-iife  ; insert global

;; goto
"mgg" 'tern-find-definition
"mgn" 'tern-find-definition-by-name
"mgG" 'tern-pop-find-definition

;; help
"mht" 'tern-get-type
"mhd" 'tern-get-docs

;; text
"mxD" 'js2r-kill
"mxJ" 'js2r-move-line-down
"mxK" 'js2r-move-line-up

;; indent
"m=" 'web-beautify-js
```

**Comment by oppenlander** [comment]
Moving to these bindings removes the "Refactoring" namespace, which [other](https://github.com/syl20bnr/spacemacs/tree/master/contrib/!lang/clojure#refactoring] [modes](https://github.com/syl20bnr/spacemacs/tree/master/contrib/!lang/csharp#refactoring) [follow](https://github.com/syl20bnr/spacemacs/tree/master/contrib/!lang/scala#refactoring).  
I would be more behind with reworking the mnemonics to be generic, so they can be shared between modes with rich refactoring libraries.

**Comment by robbyoconnor** [comment]
I don't like this.

**Comment by oppenlander** [comment]
Has there been any discussion on a dependency structure for layers? 
The problem this rewrite solves is coming from a higher level layer (either `web` or `react`) conflicting with `javascript`, which the higher level layer should guarantee is loaded along with it.

**Comment by louy2** [comment]
@oppenlander 
I don't think it is a good namespace to follow. Refactoring includes a lot of different actions totally unrelated otherwise.

Spacemacs aims to combine the power of Vim and Emacs. I am much inspired by [Why Atom Can’t Replace Vim](https://medium.com/@mkozlows/why-atom-cant-replace-vim-433852f4b4d1), so I think a good solution is to also represent composability as often as possible. Which often means, action first, target second. 

@robbyoconnor 
As for consistency:
- No consistency within
  - In [Clojure layer](https://github.com/syl20bnr/spacemacs/tree/master/contrib/!lang/clojure#refactoring), `m r e f` is "extract function", while `m r e l` is "expand let". `e` is meaning two opposite things here. Later you'll find `r` means either "rename", "remove" or "replace".
- No consistency across function
  - In [Scala layer](https://github.com/syl20bnr/spacemacs/tree/master/contrib/!lang/scala#refactoring), `m r f` is "format source", while JavaScript uses `m =`.
  - In Clojure layer `m r s n` is "sort ns", while in Scala layer the similar function "organize imports" is `m r i`.
- No consistency across keybinding
  - In Scala layer `m r r` is "rename a symbol project wide", but in [C# layer](https://github.com/syl20bnr/spacemacs/tree/master/contrib/!lang/csharp#refactoring) `m r r` is "Refactor symbol under cursor". 

The problem was keys of `tern-mode` bound to js2-mode from javascript layer conflicts with keys originally in web-mode. Now I see such mess in keybinding a bigger problem.

**Comment by robbyoconnor** [comment]
I don't know @syl20bnr -- you have an opinion?

**Comment by louy2** [comment]
My bad in part though: I should've conformed to [CONVENTION](https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.org) more. Probably will change the keybindings for the better.

**Comment by oppenlander** [comment]
It's not extensive, but there is a section in [CONVENTIONS for Refactoring](https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.org#refactoring). 
Since this section is so simple, it makes sense that there would be no consistency across functions and keybindings.

But I would argue there _is_ consistency within.
The convention `javascript` and `clojure` follow is for the two characters after the namespace (`SPC m r`) to be a mnemonic of the function it's calling. 
I originally made a [function to make this more clear](https://github.com/syl20bnr/spacemacs/blob/master/contrib/!lang/javascript/packages.el#L91), but it polluted other modes.

I don't think composability comes in to the conversation, unless you're talking about doing something like writing a layer over these refactoring libraries to operate over VIM-style boundries.

**Comment by louy2** [comment]
@oppenlander 
Mnemonic of the function is not part of the "Consistency" described in DOCUMENTATION. And it doesn't help discoverability. While composability achieves both. Even if it's not full composability, it is still more consistent than the current refactor mess. 

Refactoring IMO is just smarter text manipulation. Extractions are effectively better `evil-surround` (but `s` is REPL in CONVENTION, which I feel strange). The whole transformation group can go to `c` which stands for "change", to make space for `t` "test". Oh, and rename there as well.

Emacs is an **editor** but the whole CONVENTIONS has nothing about editting source code. Evil is nice, but it is not everything. While so much goes to evaluation, REPL, compilation and debugging, as if Emacs is an IDE. It can be, but it often is not.

**Comment by robbyoconnor** [comment]
Don't mind me...
![Poporn](http://gifrific.com/wp-content/uploads/2014/02/Maurice-Moss-Eating-Popcorn-The-IT-Crowd.gif)

**Comment by syl20bnr** [comment]
Achieving composition of refactoring commands across languages is out of the scope of Spacemacs. 

Refactoring capabilities vary a lot between languages, it would be a nightmare to achieve something that works as expected, the composition will be left with many and different holes deoending on the language which annihilates the whole point of having composition in the first place.

Composition works in Vim because it has no holes; it works on text and is agnostic of any language semantic. A word is a word, a line is a line etc...

@oppenlander nailed it, the conventions are not very detailed on purpose. It is reduced to its minimum which is allocating a space for refactoring commands that assure to not collide with other key bindings. 

Once we have define enough sets of refactoring key bindings we can take a step back and look at the whole picture and start looking to unify some recurring commands, but we may be never able to do so.

I see refactoring commands as advanced feature not vital to learn a language so I don't mind if the key bindings are different between languages. But no matter the language we know that those functionalities are behind `SPC m r`, the rest can be discovered with `which-key`.

There are so many possible refactoring commands that we are compelled to put them behind a reserved key, trying to use the whole keyboard for them is a guarantee of an endless fight with the rest of the conventions. For the sanity of the project we don't want that :-)

**Comment by robbyoconnor** [comment]
^^^ :+1:

**Comment by axyz** [comment]
so, trying to be pragmatic... in all the cases such the `react` layer we have to decide hat to do between

1) overriding other layers keybindings on specific cases (such as loading a `jsx` file). If it is possible, what is the preferred way of doing this kind of keybindings overwriting?

2) looking for unused letters on the actual mayor's mode conventions aware keybindings. This sometimes works like a charm as in the case of `SPC m h [things]` for tern commands in `javascript` mode that can be seamlessly imported as they are on `we-mode` when editing `jsx` files. In other cases we have conflicts and then we have to choose other letters (if available) or just ignore some of the less important commands.

in the case that 2) will be the way to go. I guess it would be a priority to try to use keybindings that respect conventions over original keybindings that may not. However I see 2 possible pitfalls: 

if I try to respect conventions more strictly on the `react` layer I may end up reserving keys that may be needed in the future to make `web-mode` more adherent to conventions (just supposing). 

Also, We'll probably face situations where we need some important commands and we have to assign them to letters that do not recall semantically that command (`i j` instead of `i p` to insert a "pizza", you got the point...)

**Comment by louy2** [comment]
@syl20bnr 
The point of having composition is not a perfect composition system, but a structure for easier discovery of function. `which-key` doesn't help much if what you see is this (taken from javascript layer):

![2015-07-27_13-07-52](https://cloud.githubusercontent.com/assets/2263580/8912383/95fec7a0-3460-11e5-905d-2d82f91a31c9.png)

Normally such partial composition is bad because it breaks expectation, but because the expectation is guided by `which-key`, we can afford it being partial. After all, even in different languages, a function is a function and a symbol is a symbol, etc. In most cases a refactor action can be attributed to a general text manipulation category, as I have shown. 

It is an agressive approach towards a trivial problem, I admit. At least, I hope to remind people to take care of categorization when assigning keybindings, making most out of the discovery platform `which-key` offers. I will start the bridging work behind `r`.

**Comment by syl20bnr** [comment]
@louy2 I uncommented the major mode specific prefix commands since they seem to work correctly now, it gives a better which-key buffer.

![capture d ecran 2015-07-30 a 23 15 24](https://cloud.githubusercontent.com/assets/1243537/9000175/64c28772-3711-11e5-9606-1b92668c9dc4.png)

**Comment by louy2** [comment]
Great. Much better. 
Kinda want to punch the paredit guys for picking ["slurp" and "barf"](https://stackoverflow.com/questions/30177987/slurpage-and-barfage-in-clojure) as "join" and "split".
