### ISSUE TITLE
`C-h` after a prefix doesn't describe bindings anymore

### ISSUE THREAD

**Issue by myrjola** [syl20bnr/spacemacs#2429]
Do I understand https://github.com/syl20bnr/spacemacs/pull/2393#issuecomment-124984246 correctly when I think that pressing `C-h` when which-key popup is visible should give me something like helm-descbinds? I’m using the latest develop branch with up-to-date packages and pressing `SPC w C-h` doesn’t seem to do anything. I expecteded a helm buffer with the window management keybindings to pop up. At least when we used `guide-key` that feature was working. 

I can confirm that `which-key-use-C-h-for-paging` value is `t`.

**Comment by syl20bnr** [comment]
This is by design.
We can set this variable to nil in spacemacs to follow the principle of least astonishment.
Question is: which keychord do we set for paging then ? :-)

**Comment by myrjola** [comment]
Now I delved into the excellent which-key documentation and got paging explained to me [1]. It was meant for prefixes with many bindings like `C-x`. Turns out which-key manages to fit all `C-x` bindings on one page on my screen, so I'm in no need for paging. I also think it's easier to find what I'm looking for with search.

I'm able to revert back to the old functionality by adding `(setq which-key-use-C-h-for-paging nil)` to my `dotspacemacs/init`. So for me this issue is solved.

[1] https://github.com/justbur/emacs-which-key#paging-1

**Comment by justbur** [comment]
You can blame me. I'm trying to figure out the right defaults for which-key and then the right defaults for it in spacemacs. 

It probably makes sense to bind a key other than C-h. The reasoning behind C-h actually help-char is that it's hooked into the command loop in exactly the right way. You can bind another key but you have to do so for every possible key sequence that you might want to use it for. Not that big of a deal for spacemacs though because you only have to do it once. 

The keys I like for this are page down, c-tab or one of the middle f keys
