### ISSUE TITLE
Navigation keys in Dvorak layout

### ISSUE THREAD

**Issue by vkz** [syl20bnr/spacemacs#2443]
I wonder if Dvorak-typists considered binding navigation keys to something more accessible than `hjkl`? I see 3 possible solutions here:
* bind `dhtn` as nav keys to match physical keys `hjkl` typical for qwerty keyboards
* bind `b` to move left, `f` to move right, `n` to move down, `p` to move up: basically drop `CTRL` in your default nav Emacs commands
* leave default Emacs nav commands unchanged i.e. `C-b/f/n/p`. `vim` normal mode steels them and it's driving me nuts

I seem to be ok with the rest of `vim` bindings, but navigation keys are unusable on Dvorak. Problem is that any solution would probably require changing a bunch of packages and extensions.

**Comment by vkz** [comment]
people suggested appropriating [evil-dvorak](https://github.com/jbranso/evil-dvorak). It may serve as a foundation, but I'd like to emphasise that binding:
> `s` move the cursor one character to the right

is imho is a terrible default. Why use Dvorak and `evil` if you keep using pinky this often?

**Comment by louy2** [comment]
Pinky to right is Evil default as well on `l`. On the other hand, why not ditch direction pads and go [hardcore](http://melpa.org/#/hardcore-mode)? Oh wait that is not the same [hardmode](https://github.com/wikitopian/hardmode) in Vim. Such a pity.

**Comment by vkz** [comment]
@louy2 `l` isn't under pinky on **qwerty** so it's not an issue for your typical Evil or vim user. I probably misunderstood your comment

**Comment by louy2** [comment]
@vkz When I use `hjkl` together pinky is at `l` since food finger is at `h`. Oh I see. To avoid covering `d` for delete `evil-dvorak` moved the directions right one key.

For most navigations I use `SPC SPC`, `f`, `w`, `e`, etc. I use pinky more frequently for `;` as repeating `f` than for `l`.

**Comment by vkz** [comment]
@louy2 right. Unfortunately, I have almost 0 experience actually using vim bindings, so can't even imagine what consequences such rebindings would have.

**off-topic**
I have a heavily customised layout - my own creation - that's just based on Dvorak. Only the char keys are in their default locations. I make absolutely minimal use of pinkies outside of typing text. Non-text and special symbols, numbers, etc - everything remapped. Don't even type Shift with pinky. Existing layouts are so busted I don't understand why people keep using them. RSI waiting to happen

**Comment by tuhdo** [comment]
@vkz I thought that you are a Vim user seeking for Dvorak layout. The `s` key placement is actually equivalent with `l` in `qwerty`. And you don't use pinky to press; you use right ring finger to press it.

**Comment by vkz** [comment]
@tuhdo one of us is confused here:
![dvorak](https://cloud.githubusercontent.com/assets/917220/8938143/80ff69b2-3565-11e5-85df-5e420730de32.png)
![u_s_](https://cloud.githubusercontent.com/assets/917220/8938159/9b6e7540-3565-11e5-861a-cf99433c3c85.png)

**Comment by vkz** [comment]
s-dvorak is pinky

**Comment by tuhdo** [comment]
Ah yes, you are right.

**Comment by louy2** [comment]
@vkz 
For casual uses RSI is very improbable, so it lives on. In your case, you need not rebind the vim bindings -- they are mnemonic so they are supposed to follow their letters. Getting used to it takes some time, in the meantime you can keep your current habits. What are you using now?

**Comment by vkz** [comment]
@louy2 I am not a casual user. I have fairly severe RSI. I confess I fail to see how `hjkl` are mnemonic. I have no problem with the rest of vim bindings on Dvorak.

I'm using vanilla Emacs with lot's of stuff stolen from other people. It's my 5th or so iteration trying to get my `init.el` right.

**Comment by hamhut1066** [comment]
I'm interested in a solution too, I currently use _shift_ + _[_ to jump around, but it's not a true replacement, and when I do have to use _j_ and _k_ it is a pain to use.

dvorak-mode in vim just moves all the keys back to their positions in qwerty mode. would this be an option? Or do we only want to move around navigation?

**Comment by vkz** [comment]
@hamhut1066 `dvorak-mode` doesn't have docs but from what I see in the code it doesn't apply here

**Comment by louy2** [comment]
@vkz 
My miss, `hjkl` are not mnemonic. I subconciously ignore them when I consider keybindings -- they are just direction pad for me. :stuck_out_tongue:

**Comment by vkz** [comment]
no worries :)

**Comment by hamhut1066** [comment]
@vkz looking at the keybindings provided in [evil-dvorak](https://github.com/jbranso/evil-dvorak), it seems everything is quite dramatically changed, (not only moving keys around), it could cause quite considerable confusion.

**Comment by vkz** [comment]
I don't think that `evil-dvorak` is the way to go either. It doesn't address the issue of other evil/Spacemacs extensions that assume original bindings

**Comment by felipe-barros** [comment]
I type Dvorak for more than 10 years (RSI), and have used Vim for several years before moving to Spacemacs, and just to give my grain of sailt, I have never, ever, reconfigured anything.

This conversation is approachable through many angles and most of them have a long, long history  in forums and mailing-lists since forever.

Dvorak was created for typing text (well, English text) and although I love it, was done so with questionable science. Vi movement keybindngs for Qwerty typists to avoid leaving the home-row while at the same time dramatically improving their _anti-socialness_.

The `hjkl` dance is obviously a fundamental part of our day-to-day editing, but, as @louy2 mentioned, abusing them [isn't the best way of Viming](https://youtu.be/SkdrYWhh-8s). So, I've found that I can use them less and less and that the keys I'm left with to do so when I need it, `cv` and `jp` (looking with Qwerty eyes), do the job well enough.


Dvorak has good support in OS`s nowadays and Vim keybindings are everywhere, but as far as I know (and please tell me if I'm wrong), there isn't a way to fuse them and still live a happy life. You would have to rethink and rebind and reconfigure more than 30 years of work from the greatest [hikikomoris](https://en.wikipedia.org/wiki/Hikikomori) in this planet. A task I don't want to anyone.

It isn't ideal, but default Vi keybindings _do_ work with Dvorak. And you get not to get involved in a lifelong struggle to adapt every software under the Sun to your exotic keyboard layout/modal-editing choices :D

Of course, YMMV, and If you still think this is a war worth fighting, I have no other reaction but to applaud your bravery.

**Comment by hamhut1066** [comment]
@felipe-barros I'll support you on that. A well thought out answer.

**Comment by mightybyte** [comment]
I've used dvorak for 10 years now and vim for much longer.  I use hjkl for movement and I think it works fine.  No, it's not on the home row, but it's still not hard at all.  j and k are still right next to each other like they used to be and h and l are at locations in the right hand that correspond well with the directions they represent.  I say hjkl are fine with dvorak.

**Comment by TheBB** [comment]
I don't think it's feasible at this time to support alternative keyboard layouts in this manner. Maybe in the future. @StreakyCobra's work on bepo might provide answers.

**Comment by StreakyCobra** [comment]
For me there aren't miracles with alternative keyboard-layouts. Either:

- You deal with the new positions of `hjkl` on your keyboard-layout.
- You remap, mode by mode, the equivalent `hjkl` keys to your keyboard-layout (`dhtn` for dvorak, `ctsr` for bepo).

It is a personal choice, there is no true/false answer. Although the first one is the easier to do, it isn't the best in term of ergonomic and speed. This is especially true for bepo, where `hl` are upper and lower rows of the ring finger (not the better one for this usage :neutral_face:). The second option, remapping the keys, is a nightmare to do and maintain.

People who want to keep `hjkl` don't have anything to change, and people wanting to remap can join their forces to create a `+keyboard-layouts/dvorak` layer. That will allow to share and save work, and newcomers will thank you for doing this, even if it is not complete.

----

I'm currently writing a layer [`+keyboard-layouts/bepo`](https://github.com/StreakyCobra/spacemacs/tree/layer/bepo/layers/%2Bkeyboard-layouts/bepo) which is doing this. Here is few remarks:

- Start with an already existing, simple and accepted solution to remap. (I took [this one](http://bepo.fr/wiki/Vim#Principe) from the original bepo's wiki). It's a one to one mapping between keys, so people who had taken this as staring point for their custom config will not be lost. Notice the keys don't have  to have a meaning (`change` is now on `l` on my keyboard), but nobody cares as it gets soon in the fingers memory.
- Invert the keys only **if they represent a movement**. If there is – an imaginary – `gt` binding, and `t` is for `tag` and doesn't represent the movement, don't remap it.
- If some move doesn't make sense, like in magit status where action are made line by line, there is no meaning of going left and right, so I kept the `c` for `commit` instead or rebinding it to left as in bepo layout.

**Comment by jbranso** [comment]
I'm the author of evil-dvorak.  I'm actually trying to figure out if I want to keep maintaining my own .emacs.d (https://github.com/jbranso/.emacs.d) or somehow tweak spacemacs to work for me.  I'm thinking of using spacemacs, because my .emacs is a huge bug infested mess.  If I ever get spacemacs reconciled with evil-dvorak, I'll let ya'll know.

**Comment by sayash** [comment]
Bump... any ideas here?

**Comment by jbranso** [comment]
I've actually since decided not to use spacemacs for the time being.  I'm not willing to put the effort into figuring out why evil-dvorak doesn't play nicely with spacemacs.  :(

**Comment by StreakyCobra** [comment]
@jbranso A regular spacemacs contributor, @AlejandroCatalina, has open a PR (#5245) to add some dvorak support. I saw he [is using `evil-dvorak`](https://github.com/AlejandroCatalina/spacemacs/blob/bf329f6871793d95b82f0ef85dac8462f8c1d936/layers/%2Bkeyboard-layouts/dvorak/packages.el), but he did some [modifications to your code](https://github.com/AlejandroCatalina/evil-dvorak/commits/599e3c594690b39fa793efc83b160263ba85d2f0) for this (at least I suppose because he decided to link his own fork :-) )

As the PR is based on the bepo (a french dvorak) layer that I made, they are sharing a lot of code, so I'm currently working to group them together in a `keyboard-layout` layer. If we can manage to make the official `evil-dvorak` to work with Spacemacs it would be a benefit for everyone.

@AlejandroCatalina Do you have any information about the integration of `evil-dvorak` in Spacemacs?

**Comment by jbranso** [comment]
Well @StreakyCobra, that would be pretty awesome if you guys put dvorak support in spacemacs!  It looks like @AlejandroCatalina  has already done most of the spring cleaning to my code base.  I developed evil-dvorak for me, and he's taken out most of the cruft that must people don't need, want, or will use.  I will go ahead and merge @AlejandroCatalina changes into my codebase in a week or 2.

**Comment by StreakyCobra** [comment]
Nice, let's see how it will integrate when you'll have updated it.

**Comment by StreakyCobra** [comment]
@jbranso I started to work on the new layer, but I'm not sure if we will need your package finally. The auto-correction functions I made for bepo are working also for dvorak. The [`keyboard-layout` layer](https://github.com/StreakyCobra/spacemacs/tree/d70ce3a31c99e889d63e70c6871b6ee087fd5592/layers/%2Bintl/keyboard-layout) that regroup `bepo` and `dvorak` already offers `hjkl` corrections for dvorak. Still a WIP, but promising :-) I'm also not sure that my way of correcting will be compatible with your way of doing it. Your way (by doing a package, defining a minor mode with a specific keymap) is better, but is limited to one package/major-mode. The layer that I made offer more potential to Spacemacs as it's allows to define layout-agnostic remapping for any packages.

Anyway, I'll continue to work on the new layer and will let you know when it will be in a usable state so you'll be able to test it and give some feedback :relaxed: (Actually it's probably already quite useable if you are motivated :wink:)

**Comment by jbranso** [comment]
Thanks for the update @StreakyCobra.  And I actually think that your method of changing the navigational keys is quite promising too!  I should contact the maintainer of evil, and ask if he would be interested in adding the variable keyboard-layout, which if set to 'dvorak would do essentially what you are doing with your keybord-layout layer, instead of adding another minor mode on top of evil.  And I'll probably try out spacemacs at some point, because you guys have done a REALLY good job of making it beautiful!  P.S.  Do the spacemacs developers intend to put some of your packages into gnu as well as melpa?  ie: which-key?  I'm only asking, because I'm curious if the developers contribute code to upstream emacs.

**Comment by AlejandroCatalina** [comment]
@StreakyCobra sorry for the delay, busy week.

I actually have evil-dvorak on spacemacs and it plays really well together. It remaps several basic keys but it's for a good purpose. But those bindings are, of course, debatable.

**Comment by jbranso** [comment]
Thanks for the update @AlejandroCatalina .  And I agree with you that those keybindings are not vimish.  I started using emacs, then dvorak, them evil.  That's why the keybindings I chose are a little wonky, but I really do appreciate your forking of my project.  It's been needing some spring cleaning, and what you've done looks great.

**Comment by AlejandroCatalina** [comment]
Great! I'll stay tuned, thanks @jbranso

**Comment by StreakyCobra** [comment]
@jbranso Adding a keyboard-layout variable in `evil` may be a solution, but I'm not sure it would help on our case. Remapping `hjkl` movements it's not difficult per se, what is difficult is to correct the function that can be mapped on the destination binding. Let's say for example that Spacemacs is mapping `n` to a function `foo`, then if evil just bind on its own line-up to `n`, then the binding of the function `foo` is lost. Even if `evil` does some check on his side to invert `n` and `k` functions, this will be dependent of the load ordering of the packages, maybe `n` wouldn't be already mapped when `evil` is loaded. For now the more generic and elegant solution I have found is this automatic correction of key-binding by swapping functions once the packages have been loaded. It requires hack sometimes (I'm pretty sure there is no perfect solution) but otherwise it's a quite satisfying :smiley:

For your other question: http://melpa.org/#/which-key :wink: (spaceline also is there)

@AlejandroCatalina I think only `hjkl-htns` inversion must be in the `keyboard-layout` layer by default. They are the most important and only bindings that are not depending on user preferences. It is possible to easily tweak more keys in `.spacemacs` by adding a function like this in the `user-init`:

```elips
(defun kl/post-config-evil ()
  "Remap movements key to be visual."
  (visual-line-mode)
  (kl/set-in-all-evil-states-but-insert "t" 'evil-next-visual-line
                                        "s" 'evil-previous-visual-line
                                        "C" 'evil-beginning-of-visual-line
                                        "R" 'evil-end-of-visual-line))
```

The function name will tell to after which configuration personal bindings should be done, this will take care of running them at the correct timing. I'll document this better by giving examples.

**Comment by AlejandroCatalina** [comment]
@StreakyCobra  Yeah I'm totally on this. The reason I made more changes is because of `evil-dvorak`, but we can make a minimal layer with only movement keys rebindings and then add more *usual tweaks* packages or configs. That may be useful.

**Comment by StreakyCobra** [comment]
Yes, and of course if some bindings are getting on consensus we can rebind them directly.

**Comment by jbranso** [comment]
So today, I compared @AlejandroCatalina evil-dvorak, with my own.  I tried to strip out as much functionality as possible, so that I only rebound "hjkl" to "htns".  There's still a bit more work to do, but I'll get evil-dvorak in a better shape by tomorrow.

P.S. @StreakyCobra Are you and the other spacemacs devs also interested in putting which-key on melpa,  aka assigning copyright to the FSF?

**Comment by jbranso** [comment]
Just another update.  evil-dvorak now has much less functionality than it had before.  The functionality that I added to it was largely personal preferences, which is now gone.  It only depends on evil-mode now, and the code is much cleaner.  If either of you require more tweaking of the package for spacemacs, please let me know.

**Comment by AlejandroCatalina** [comment]
I'll take a look this week. Thank you for your work @jbranso !

**Comment by StreakyCobra** [comment]
@jbranso I'm not sure to understand your question, it's already on melpa, no? http://melpa.org/#/which-key

Also, questions regarding which-key would be better discussed with its author, justbur: https://github.com/justbur/emacs-which-key :smiley:

Nice work for `evil-dvorak` :+1: I still don't think I'll use it in the `keyboard-layout` layer because another way of rebinding keys is needed at Spacemacs level because of the layers system. But I suppose it can now be used by simply adding it to `dotspacemacs-additional-packages` and putting:

```elisp
(require 'evil-dvorak)
(global-evil-dvorak-mode 1)
```

in `dotspacemacs/user-config`. This will already allows `dvorak` users to have a basic support :100:

**Comment by jbranso** [comment]
Well if you're curious, @StreakyCobra if you put packages on elpa, all contributors have to sign copyright assignment to the FSF.  If a package is put on melpa, then it can be automatically installed in GNU Emacs.  For example, php-mode will never be in elpa or installed by default in GNU Emacs, because not all of its contributors would sign copyright assignment papers with GNU.  So if I ever want to use php-mode,  I have to install it from melpa.  The reason it's good to assign copyright to the FSF, is that is the only way to properly enforce the GPL.

Anyway,  thanks for the great work to initially help me out @AlejandroCatalina !  Yeah Spacemacs!

**Comment by StreakyCobra** [comment]
@jbranso Ok :+1: , but you asked about MELPA, not ELPA, it's why I didn't understood your question :smiley: Thx for the info.

**Comment by jbranso** [comment]
Yup. anytime.
