### ISSUE TITLE
how to use latex build command

### ISSUE THREAD

**Issue by spencerlyon2** [syl20bnr/spacemacs#2462]
I'm trying got get latex to build using pdflatex when I do `SPC m b`.  I have the following in my `~/.spacemacs`:

```
(latex :variables
            latex-build-command "pdflatex"
            latex-enable-auto-fill t
            )
```

When I try to compile a basic latex file, I get the following error:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\(?: \"\\\\\\|\"\\|%\\(?:(\\(?:\\(?:PDF\\(?:out\\)?\\|ex\\(?:\\(?:ec\\|tra\\)opts\\)\\|file-line-error\\|latex\\|mode\\|o\\(?:\\?\\|utpage\\)\\|tex\\))\\)\\|cS\\|dS\\|vv\\|[%'SV`abdfl-tv]\\)\\)" nil nil)
  TeX-command-expand(nil TeX-master-file)
  TeX-command("pdflatex" TeX-master-file -1)
  (progn (let ((TeX-save-query nil)) (TeX-save-document (TeX-master-file))) (TeX-command latex-build-command (quote TeX-master-file) -1))
  latex/build()
  call-interactively(latex/build nil nil)
  command-execute(latex/build)
```

Any suggestions?

**Comment by justbur** [comment]
I think your build command is wrong. It should be one of the options that show up after C-c C-c. If you use LaTeX then it will default to pdflatex because TeX-PDF-mode is t

**Comment by spencerlyon2** [comment]
Yep, if I just remove the command specification all together it works. Sorry for the noise...

**Comment by izahn** [comment]
I'm not so sure there's not a real issue here; at the least the name of the variable is confusing. It probably would be better to have named the variable `latex-build-use-latexMk` and documented it to take `nil` or `t`, but that requires changes to the actual code. Failing that the documentation should more clearly indicate that the only values that really make sense are "LaTeX" or "LatexMk". I'll try to work up a PR to clean this up a little.

**Comment by justbur** [comment]
That's actually not true though. It's the commands as defined by auctex
that are valid. You can define your own and make any name valid. It should
say that you need to specify a valid auctex command not necessarily the
command to run from the command line.

**Comment by izahn** [comment]
You can already set the default command with `TeX-command-default`; as far as I can tell from looking at the code the only thing `latex-build-command` is used for that isn't already covered by `TeX-command-default` is setting up LatexMk. I definitely think there is some cleanup to be done here.

**Comment by justbur** [comment]
Yes, I think there are definitely problems with the current code, and it could be cleaned up. I think it would be better to stick to using the auctex builtin functions as much as possible, so that the builtin documentation is correct.

The latexmk stuff just sets up latexmk as another option in `TeX-command-list`, so it's actually harmless as far as I can tell to include it for everyone. Having to set the build command to latexmk to get that code loaded is unnecessary. Sometimes you may want to have it as an option even if it's not your primary choice for building the file.

**Comment by izahn** [comment]
I took a look at the code earlier today, but I'm not really sure how to proceed. One issue is that right now latexmk is the only build tool (besides the default ones provided by auctex) included in the spacemacs latex layer. However, in the future we may wish to support other tools, or change to something else if a better option becomes available. With that in mind, I'm no longer sure that changing `latex-build-command` to `latex-build-use-latexMk` is a good idea.

I mostly agree with the idea that `auctex-latexmk` should just be loaded for everyone. The only issue is that AFAIK TeXLive doesn't ship with latexmk, so unless people know to install it the "LatexMk" build option won't work. I would say we should enable it if `(executable-find "latexm")` is non-nil.

I'll take another look and see if I can find a more consistent way to set things up.

**Comment by justbur** [comment]
I'm pretty sure latexmk was included in my texlive distribution but that's
going to vary across distributions.
That would be great. I've dug around in auctex and use it often. I have my
own config but it would be nice to see a better implementation here.
Also it's worth keeping in mind that the latex build process is often more
complicated than compile once and view, which is what that original build
command function assumed.
