### ISSUE TITLE
Strange tmux characters in projectile buffer

### ISSUE THREAD

**Issue by honza** [syl20bnr/spacemacs#2480]
After running `SPC p f`, I see this. There is a file called `.env`. Emacs is running in GUI mode.

![screen shot 2015-07-30 at 13 30 45](https://cloud.githubusercontent.com/assets/206357/8988924/5bc0d162-36bf-11e5-90f8-1d5ade4df7cf.png)

I'm not sure where to even begin debugging this. Thanks!

**Comment by syl20bnr** [comment]
mmmh no idea for now :smile_cat:

**Comment by syl20bnr** [comment]
Can you give more details about your environment ? OS, Emacs versions etc...

**Comment by honza** [comment]
* Emacs version 24.5 (9.0)
* Spacemacs version 0.103.2
* Tmux 2.0
* OS X 10.10.3
* base16-tomorrow-dark color scheme.

**Comment by aradunovic** [comment]
@honza

I just fixed this issue **thanks to you**!
Since I have the exact same setup as you, it was easy to trace the issue to **base16-tomorrow-dark** colorscheme.
I also had [base16-shell](https://github.com/chriskempson/base16-shell) script installed, which was **most likely** the cause of the problem. It was either the script or colorscheme...or both.

I uninstalled the script and changed the colorscheme everywhere (emacs, iterm, vim...).
After that I run `projectile-invalidate-cache`, restarted emacs and **the issue was gone**!

I hope this will help you.

**Comment by honza** [comment]
@aradunovic You're a genius. I've been banging my head against this for weeks now. Uninstalling the base16-shell script solves this. The script [inserts](https://github.com/chriskempson/base16-shell/blob/5acf5629a8bd186399a378c37c10507675525514/base16-tomorrow.dark.sh#L36) a whole bunch of stuff when run under tmux. OSS ftw! Thank you
