### ISSUE TITLE
Discussion/Advice: How do you handle shadowed bindings?

### ISSUE THREAD

**Issue by travisbhartwell** [syl20bnr/spacemacs#2490]
So, a side effect of using evil and evilfy, many modes have bindings that are shadowed.  For things like gnus, this sometimes can render it unusable.  Recent updates to `evilfy` have rendered much of gnus unusable.  For example, if I do `C-h m` to see the mode bindings, I get these functions as being shadowed (narrowed from the list of total bindings):

```
C-k             gnus-group-kill-group
  (that binding is currently shadowed by another mode)
RET             gnus-group-select-group
  (that binding is currently shadowed by another mode)
C-y             gnus-group-yank-group
  (that binding is currently shadowed by another mode)
SPC             gnus-group-read-group
  (that binding is currently shadowed by another mode)
#               gnus-group-mark-group
  (that binding is currently shadowed by another mode)
=               gnus-group-select-group
  (that binding is currently shadowed by another mode)
N               gnus-group-next-group
  (that binding is currently shadowed by another mode)
V               gnus-version
  (that binding is currently shadowed by another mode)
c               gnus-group-catchup-current
  (that binding is currently shadowed by another mode)
g               gnus-group-get-new-news
  (that binding is currently shadowed by another mode)
j               gnus-group-jump-to-group
  (that binding is currently shadowed by another mode)
l               gnus-group-list-groups
  (that binding is currently shadowed by another mode)
n               gnus-group-next-unread-group
  (that binding is currently shadowed by another mode)
<mouse-2>       gnus-mouse-pick-group
  (that binding is currently shadowed by another mode)
C-c C-x         gnus-group-expire-articles
  (that binding is currently shadowed by another mode)
M-#             gnus-group-unmark-group
  (that binding is currently shadowed by another mode)
M-g             gnus-group-get-new-news-this-group
  (that binding is currently shadowed by another mode)
```

Many of these, such as `g` are essential functions.  What's the general strategy for dealing with this?  I want to help fix this.  I'm not opposed to moving these bindings, I don't have that much muscle memory for gnus to be stuck in them.  It just want all useful functionality available.

Do we just go through each of these things that are shadowed, find where they are original bound (i.e., which keymap) and in the packages.el call appropriate functions to make them evil?

I assume this is something we would want documented somewhere:  "How to integrate a mode into Spacemacs/Evil".

**Comment by syl20bnr** [comment]
I believe that gnus still uses the old evilify macro, the new one called `spacemacs|evilify` is only used for magit right now.

I'm surprised that so many bindings are shadowed because evilified state only bind 10 or so keys to minimize the impact on the original mode map.

The rules for evilifation is the following:
- [a-z] bindings moved to [A-Z]
- [A-Z] bindings moved to [C-a, C-z]
- [C-a, C-z] bindings moved to [C-A, C-Z]
- [C-A, C-Z] is skipped and won't be available
- C-g is never shadowed, so G is directly moved to C-G

When you start magit status buffer you can see that the new macro warns when some bindings are begin lost.

The rules are modeled here: https://github.com/syl20bnr/spacemacs/blob/develop/core/core-evilify-keymap.el#L153-L167

In develop we added recently `gg` and `G` to the evilified state map so the `g` key is pretty crowded (`g`, `G` and `C-g` are already taken by the evilified state so only on key can be remapped to `C-G`, all the others will be lost, it is OK in magit since only `g` is used) https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/extensions/evil-evilified-state/evil-evilified-state.el#L56-L75

**Comment by sooheon** [comment]
Evilification is just one of those aspects of spacemacs where you can't avoid some case-by-case tweaking. The rules for evilification are sound, but they won't work for every mode automatically. 

Whats your opinion on having a way to opt out of evilification (including evil-mode) for a particular mode, when that mode has its own modal paradigm already, which one can choose to learn (like magit or gnus)?

**Comment by mkcode** [comment]
It's possible you may want to manually configure the bindings for gnus. You could easily adopt this example:

```elisp
(eval-after-load 'ibuffer
  '(progn
     (defvar ibuffer-mode-map)
     (evil-make-overriding-map ibuffer-mode-map 'normal)
     (evil-define-key 'normal ibuffer-mode-map
       "j" 'evil-next-line
       "k" 'evil-previous-line
       "RET" 'ibuffer-visit-buffer)))
```

There are all sorts of good examples in evil-integration.el
