### ISSUE TITLE
Evilify overriding `g`

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#2533]
The recent commit https://github.com/syl20bnr/spacemacs/commit/6dc3ea3393562c8dc0d7c6077713b797ef7b8c42 overrides the `g` command for evilified modes (by adding Vim's `gg` command).  This is a pretty serious problem since a lot of Emacs's modes use `g` for refresh, update and the like.

The `G` key might also be troublesome.  I can't recall if it's also a commonly used key.  I know elfeed uses it for refreshing feeds.  If elfeed's the only one, then it is okay to override it in `evilify`.

**Comment by TheBB** [comment]
Since `g` and `G` are overridden, and `C-g` is skipped by default, anything on `g` now ends up on `C-S-g`. That's quite the trek…

**Comment by darkfeline** [comment]
@TheBB Control-Shift doesn't work on terminals, and it doesn't seem to work for me in the GUI either (likely a configuration matter, I'll find it somewhere...)

**Comment by syl20bnr** [comment]
This is why I didn't add these keys before but I finally tried it since it was proposed and I was OK with it using C-S-g in Magit without any issue, the comfort of having gg and G to navigate is superior than having refresh on g.

Now C-S does not work in terminal which I once again forgot, this is an issue. Maybe we need to add a prefix to the rebinding rules.

Maybe we could ditch evilified state, use motion state instead and move the major mode map behind `SPC m` so every first command of Magit would start with `,` which could be bearable and still follow the philosophy of Spacemacs (that is no usage of modifiers).

**Comment by luxbock** [comment]
I almost never have to use `gg` in a magit-buffer, but I use the `g` command to refresh all the time. I would imagine most people are the same. I think your proposed solution of prefixing all of magit's regular commands with `,` would be highly counter-productive, if you think in terms of how many extra key presses it will result just so one can fix the ability to use `gg` sometimes when it's necessary.

**Comment by syl20bnr** [comment]
`gg` and `G` are not about Magit Status buffer only, open a Magit Log buffer for instance and you'll be happy to have `gg` and `G` available.

The main idea behind "evilified" buffer is to achieve consistency among all the different non-evil friendly buffers in Emacs.

I'll work on a different set of rules, basically on replacing only the `C-S` "layer" of the evilification by a prefix since `C-S` is not available in the terminal. Refreshing on `g` would be `<leader>g` which is not a big deal for a binding that does not need to be repeated.

The rules would become: `a-z` -> `A-Z` -> `C-a C-z` -> `<leader>a-<leader>z` -> `<leader>A-<leader>Z` -> `<leader>C-a <leader>C-z`
In practice we should rarely go up to the leader cases except for `v` and `g` which will have the same exceptional behavior (that is `v`, `V`, `C-v` and `g`, `G`, `C-g` already reserved by the evilification) so these exceptions remain easy to explain.

**Comment by syl20bnr** [comment]
My ultimate goals are:
- to get full consistency (looking at the vanilla cheat sheet of a mode map, you should be able to deduce the evilified version of it and vice versa)
- to be able to evilify a buffer in one call to a function

**Comment by darkfeline** [comment]
@syl20bnr Would it be that bad to ditch `gg` and keep `G`?  `gg`'s behavior can be reproduced with `1G`.  In fact, vi (not Vim) only has the `G` command.  Although I don't think there's anything wrong with your proposed rules or your ultimate goals.

Also, Spacemacs should definitely stay away from double modifier keys, even if Control-Shift worked in terminals.

**Comment by syl20bnr** [comment]
> gg's behavior can be reproduced with 1G

Interesting, so we may be able to remove `gg`, I keep this in mind.

**Comment by kepi** [comment]
Please, leave both `G` and `gg` as it should be or make it somehow configurable. I bet there are more people here than me who likes spacemacs because consistency and compatibility with vim.

I'm using both `G` and `gg` keys hundreds of times a day. You cant say - its ok to use `1g` instead of `gg`. If I want to break my hands, I would use default emacs keybindings ;)

Maybe important to understand that on many keyboard layouts you have to use numbers with some modifier key, so as it is kind of comfortable to type `1G` on english layout, its really uncomfortable on different ones.

**Comment by darkfeline** [comment]
>Maybe its important to understand that on many keyboard layouts you have to use numbers with some modifier key
Like which ones?  I find it hard to believe one would do any serious text work on such an incomplete keyboard.

**Comment by kepi** [comment]
Like almost any non-english layout in the world? :) In my language (Czech) to be able to write texts I have to use many czech characters which are placed on same row as numbers. Numbers are normally typed with shift, special characters (like $ # etc) are written with AltGr or by switching layout to english (which isn't viable for any serious text work :) ).

**Comment by darkfeline** [comment]
@kepi Paging through the Wikipedia page on keyboard layouts, it seems only Tifinagh, Dzongkha, Thai, and Bengali are like that, although Czech wasn't listed.  The ones I'm familiar with, the standard International/European, Chinese, and Japanese (which together represent more than 50% of the world population) all have regular numbers like the standard US, and it seems like that's the rule rather than the exception.  Thus, the minority users using a keyboard without non-chorded numbers are free to bind `gg` at their leisure.

The `gg` command makes sense when there's also `gu`, `gU`, `gd`, `gf`, and a whole slew of other commands to share its prefix, but in evilified mode where it's all by itself it makes less sense.

@syl20bnr can make the final decision.

**Comment by kepi** [comment]
First of all - non-enlish part was only minor comment. It still dont make sanse to use `1G` instead of `gg` . But decision is not up to me, I only wanted to add different point of view so @syl20bnr have more info to decide.

But @darkfeline please, find better source than that Wikipedia page. I thing French, Germans, (Czech), Slovaks, Poles and many many others will be really surprised that they can write numbers without modifiers :) on their default layout. But lets forgot about this, I don't intended to start some large discussion.

**Comment by TheBB** [comment]
For what it's worth, I agree with @syl20bnr's idea to leverage the major-mode leader key. I use `gg` habitually all the time. The major-mode leader key is available and unused in almost every evilified buffer, and it would make sense since this is exactly the kind of thing it is for—commands which are major-mode specific.

**Comment by justbur** [comment]
Fixed in #3578

**Comment by darkfeline** [comment]
Is there any documentation about auto evilification?  I believe `g` gets auto evilified into `C-S-g`.  What does `G` get evilified to?  Is it possible to automatically evilify `g` into, e.g. `gr` and `G` into `gR`?  `g` is a common binding in a lot of packages, and it doesn't make sense to either 1. have it auto evilified into something as horrendous as `C-S-g` nor 2. have to bind it manually to something sane for every package/mode.

**Comment by TheBB** [comment]
Yes, search in the main doc file (on develop). G isn't evilified into anything currently. You should get warnings about that in case it happens (as well as all other missed bindings).

**Comment by justin808** [comment]
Are these warnings related to this thread? or should this be a separate issue?


```
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-status-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-refs-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-diff-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-select-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-cherry-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-reflog-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-process-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(No files need saving)
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-process-mode-map':
   - `magit-refresh-all' originally mapped on `G'
```
