### ISSUE TITLE
Buffer contents get pushed by simultaneous display of autocomplete list and syntax error label

### ISSUE THREAD

**Issue by aviralg** [syl20bnr/spacemacs#2575]
In the image below, as I type, I get a list of possible completions and at the same time a syntax error.
This invariably happens in the following situation - 
    
    self.<current cursor postion>

![spacemacs-bug](https://cloud.githubusercontent.com/assets/4531751/9136942/09a0640e-3d38-11e5-849d-c2256aa130b5.png)

**Comment by syl20bnr** [comment]
Does this happen everytime on every objects ?

**Comment by aviralg** [comment]
Yes, as of now, whenever I press tab for completion of class methods and class variables, this happens. But I am exclusively working in Python, so I don't know for other languages.

**Comment by CestDiego** [comment]
I can't reproduce this, @aviralg have you updated your packages and have the issue persist?

**Comment by TheBB** [comment]
I can reproduce it. Seems only to be a problem if you scroll down so that the company popup opens upwards. You also have to have `idle-change` in `flycheck-check-syntax-automatically` so that you get errors while typing, at the same time as company pops up.

I'm not sure how to go about fixing this. I want to suggest defaulting `flycheck-check-syntax-automatically` to `(save mode-enabled)`, which I think is a more sensible default than what we are currently using.

**Comment by TheBB** [comment]
@lunaryorn I don't suppose you have seen this one before?

**Comment by lunaryorn** [comment]
@TheBB Sorry, but this issue is somewhat unclear to me.  What is the actual problem here?  The _display_ of the error (which doesn't look right to me), or the syntax error itself?

And besides, are we talking about Auto Complete or Company here?

**Comment by TheBB** [comment]
We're talking about company. If you have syntax checking on idle change, sometimes you'll end up in a situation where company will want to complete *and* flycheck will find a syntax error. Then company shows its popup and flycheck shows its "SyntaxError: blah blah" tooltip, and you end up with something like the image in the OP where they conflict.

**Comment by lunaryorn** [comment]
@TheBB So we're talking about the “corrupted” display? This is not a Flycheck issue then:  You're using `flycheck-pos-tip` at this place which is a 3rd party package.  You'll have to ask the author of https://github.com/flycheck/flycheck-pos-tip.

**Comment by TheBB** [comment]
Ah okay, sorry for the misunderstanding.

**Comment by StreakyCobra** [comment]
Does this still happen? The flycheck tooltip library has been changed, if it was the issue it may be solved after updating the packages.

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
