### ISSUE TITLE
Difference between :edit and C-x C-f

### ISSUE THREAD

**Issue by aviralg** [syl20bnr/spacemacs#2585]
Why is there a difference between :edit and C-x C-f ?

:edit gives me helm-mode-completion-at-point. This, on my system, does not complete directory names after the first level. On the other hand C-x C-f gives a damn good *Find File* thingy.

Of course I could just use C-x C-f all the time, but my perception is that :edit of vim is equivalent to  C-x C-f of emacs. If such is the case, they should both be bound to the same action.

**Comment by louy2** [comment]
`:edit` is a simulated vim EX command, which is handled by Evil by a EX command processor, not bound to keymap. It can be used to, e.g., open all files whose names are mentioned in the current buffer, by composing a EX command. For a more convenient way to invoke Helm find files, you can use `SPC f f`.

**Comment by aviralg** [comment]
Thanks for telling about `Spc f f`. So what exactly do you mean by - 'open all files whose names are mentioned in the current buffer.' I believe a buffer corresponds to one file. 
I have 4 buffers open right now in spacemacs. But only one of them is visible, as I have only one window. So typing `:edit` and pressing `tab` does no completion at all! 
Now, when I create 2 windows side by side, both showing different buffers, `:edit` still does not do any completion beyond the name of the buffer in the current active window.

**Comment by sooheon** [comment]
`:edit` is an ex command, originally from vim, implemented in evil. It can be used as part of a vim macro, which is what louy2 is referring to. If you begin typing a relative or absolute path, it will give you tab completion (but not very featureful). For switching between buffers, look at `space b b` or `spc tab`.

It really doesn't make sense for you to demand that `C-x C-f` and `:edit` be bound to the same command, because they're fundamentally different. You can read up about them by googling, really it's not an issue for spacemacs, and this issue should be closed, imo.

I think what you need is some discoverability, so try using `C-h f`, `C-h k`, and `C-h i` to query things you are curious about. It's really one of the best parts of emacs, so use it! :)

**Comment by aviralg** [comment]
Thanks for the detailed explanation.
