### ISSUE TITLE
Evil keys are sometimes lost in org mode

### ISSUE THREAD

**Issue by knl** [syl20bnr/spacemacs#2651]
Hi,
thanks for this great project that drawn me closer to Emacs and org mode. 

I'm experiencing a weird problem, that when I spend some time in an org buffer, some of the evil/spacemacs keybindings do not work. For example, `d` kills the whole line instead of `d d`. Or `M-left` stops increasing the level, or `d $` doesn't delete till the end of line anymore.

Is there any way to debug why is this happening?

Thanks,
Nikola

**Comment by sooheon** [comment]
I'm in org mode quite a bit recently and I've never seen this, nothing to do but be very observant next time it happens, I guess.

**Comment by geo7** [comment]
@knl I seem to remember having something similar to this *ages* ago actually and I'm trying to remember what was the cause :/ If I do I'll report back - one thing that I did deactivate was `evil-org-mode`, mainly because it shadowed movement keys but perhaps there's a connection there? 

Bit of a shot in the dark I guess

**Comment by zilongshanren** [comment]
@sooheon  
If you use `SPC f e h` to navigate to a layer README.org, the evil org keybindings are lost.

**Comment by zilongshanren** [comment]
I could confirm this issue

**Comment by StreakyCobra** [comment]
I can't reproduce this problem. Does anybody of you is still having it?

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
