### ISSUE TITLE
Scala-mode: Period key triggering autocompletion.

### ISSUE THREAD

**Issue by siegelzero** [syl20bnr/spacemacs#2702]
When the auto-completion window pops up, pressing the `.` key triggers completion. This doesn't happen in other major modes that I've used - only scala mode.

In a situation where you have objects `foo` and `foobar`, this can cause serious headaches. Trying to type `foo.attribute` is impossible, since the `.` key expands `foo` to `foobar` whenever `foobar` is at the top of the completion candidate list.

**Comment by Devagamster** [comment]
In the meantime, control g could exit the auto-completion and allow you to press . again. Agreed that its an issue though.

**Comment by chrisbarrett** [comment]
Yep, I never bothered to fix that one. I've got muscle memory at this point to just `C-g` out of the popup, but you could also use `C-q .` to just insert a period char literally.

**Comment by chrisbarrett** [comment]
I have vague recollections of Visual Studio doing the same thing so it's never really bothered me, but YMMV.

**Comment by StreakyCobra** [comment]
Is this a Spacemacs issue, or should it be reported upstream to `???` ?

**Comment by chrisbarrett** [comment]
Yeah, it's a layer issue. The period key is bound to trigger company completions. The problem is when the company popup is already open--it gives undesired behaviour. I'll have a look at it today.

**Comment by StreakyCobra** [comment]
Ok, I haven't look at it before. Probably removing these 3 lines should do the trick: https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/scala/funcs.el#L94-L96

**Comment by diego-alvarez-hs** [comment]
I just pushed a PR fixing that because it's causing a lot of headaches as @siegelzero suggested.

Speaking of autocomplete, I'm wondering why scala/java layers are the only ones that have a function to complete with period? https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/scala/funcs.el#L87

How are others layers using company to accomplish that behavior?

**Comment by d1egoaz** [comment]
I just pushed a PR fixing that because it's causing a lot of headaches as @siegelzero suggested.

Speaking of autocomplete, I'm wondering why scala/java layers are the only ones that have a function to complete with period? https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/scala/funcs.el#L87

How are others layers using company to accomplish that behavior?
