### ISSUE TITLE
Bloody Leuven

### ISSUE THREAD

**Issue by louy2** [syl20bnr/spacemacs#2704]
Reposting https://github.com/abo-abo/avy/issues/92

Drama:
Avy makes Leuven all bloody!

Technical:
When avy is showing candidates under theme leuven, the background, instead of staying unchanged, turns red.

**Comment by bmag** [comment]
Here we set `avy-background` to t, regardless of the theme being used: https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L414
We should probably not set it here, but let the active theme set it. I hope to work on it tomorrow, but removing that line is probably enough.

**Comment by louy2** [comment]
Turns out Leuven [conciously set it to red](https://github.com/fniessen/emacs-leuven-theme/blob/master/leuven-theme.el#L295).

**Comment by kRITZCREEK** [comment]
Bloody Leaven sounds like the coolest theme ever...

**Comment by bmag** [comment]
Sorry, didn't get around to working on this as I hoped.
However, since Leuven uses a bloody red on purpose, I don't know if this should be considered a Spacemacs bug or not.

Reasons not to set `avy-background` in Spacemacs: it's part of the look and feel of a theme, so it should be set by the theme being used.

Reasons to set `avy-background` in Spacemacs: no theme actually sets it (I have the `themes-megapack` layer and searched elpa directory), so maybe it's not a theme setting after all.

**Comment by TheBB** [comment]
We can't start changing themes, surely? That's a can of worms. It's easy enough to fix locally with `custom-set-faces`, no?

Anyway, there's an upstream bug report https://github.com/fniessen/emacs-leuven-theme/issues/22 so I'm marking this as reported upstream.

**Comment by StreakyCobra** [comment]
If anyone is interested to contribute to this, they seems to be open to discussion upstream, so I'm closing this issue in Spacemacs side.
