### ISSUE TITLE
eldoc makes python buffers hang

### ISSUE THREAD

**Issue by agriffis** [syl20bnr/spacemacs#2708]
It seems like eldoc makes my python buffers hang frequently for somewhere between 3 and 20 seconds. It's not really usable like this, so I end up shutting off eldoc with M-x eldoc-mode.

While it would be nice to understand why it hangs, I'd also be happy with a spacemacs python layer config toggle for disabling eldoc by default. I haven't been able to find one so far.

**Comment by agriffis** [comment]
I was able to work around this by adding `eldoc` to `dotspacemacs-excluded-packages`

I guess this can be closed now, though it seems like having `eldoc` by default in the python layer provides a poor OOTB experience for spacemacs.

**Comment by cmccloud** [comment]
I ran into something similar in larger python files - If I remember correctly it had to do with the way that anaconda mode sends file information to the server to be parsed - each request sends the entire contents of the buffer. If eldoc mode is causing those requests to be made frequently, that might be the cause of what you're seeing.

**Comment by CestDiego** [comment]
Can you provide a python file to test this on? We could just use a fix that disables eldoc for larger files as well

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
