### ISSUE TITLE
This symbol ⊝ is not displayed.

### ISSUE THREAD

**Issue by thefucker** [syl20bnr/spacemacs#2720]
SPC t -	⊝	-	centered-cursor mode
i work on windows10

**Comment by TheBB** [comment]
Do you have a font with that symbol? I can't reproduce but I don't have Win 10.

**Comment by syl20bnr** [comment]
I believe that the default fallback font we use is no longer distributed with win 10 :-(

**Comment by d12frosted** [comment]
Is it still valid? Any updates on this issue?

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
