### ISSUE TITLE
Org layer does not work properly with emacs 24.3

### ISSUE THREAD

**Issue by ipsod** [syl20bnr/spacemacs#2725]
I was unable to get org-mode to work properly in emacs 24.3.  Headings would sometimes have plain-text formatting, and plain-text have heading formatting.  Also, the heading jump/indent functions worked sporadically, sometimes recognizing (n)th level headings as siblings to (n+1)th level headings.

Overall, it was unusable, both with master and dev branches of spacemacs.

Upgrading to emacs 24.5 fixed the problems.

**Comment by justbur** [comment]
@syl20bnr  To add to this, support for 24.3 is not currently being respected across layers. There are a number of packages in my layers that have 24.4 requirements. Some examples that I found are `git-commit`, `magit`, `helm-unicode`, `magit-gitflow`, and `ranger`.

**Comment by robbyoconnor** [comment]
@syl20bnr -- Maybe we should bump our minimum version -- which let's be real -- isn't unreasonable :)

**Comment by TheBB** [comment]
Well, 24.3 is the current Ubuntu LTS version, for one.

**Comment by robbyoconnor** [comment]
@TheBB -- if somebody can use emacs, they can compile it....let's assume our users are completely useless :)  [here](http://ubuntuhandbook.org/index.php/2014/10/emacs-24-4-released-install-in-ubuntu-14-04/) are instructions on how to compile and install emacs 24.4.

**Comment by geo7** [comment]
Yeah tricky - I don't think that one can presume that someone who uses emacs can compile it, they can *learn* to compile it I'm sure. But the process is 

* Install emacs
* go to Spacemacs, follow instructions
* install spacemacs
* Install some layers
* find out stuffs not working
* wonder why
* make an issue / gitter post that things aren't working
* informed "*can't compile wtf why even use emacs*" 'help'
* buy ticket to NY
* buy gun
* go to emacs meetups and wait for robby


Which isn't **really** a great chain. So things should be changed a bit IMO. 

I've been trying to help a bit when I bump into an Ubuntu user via a script that I've written for compiling emacs from source and installing Spacemacs - but I'm always a bit unsure because it's probably not the best script, installing from source isn't the **best** approach etc (one could make a deb package or a PPA or something more robust I'm sure). I don't talk about uninstalling / cleaning up or anything like that in it (for moving onto the next emacs version or whatever). Also (in retrospect) I think that a better approach than installing from the tar that GNU hosts would be to use the GitHub mirrors, I've not really looked into that though. 

******

> let's assume our users are completely useless :)

I don't think that's a very good idea

**Comment by ipsod** [comment]
A project like this should have a low barrier for entry. It doesn't take an expert to find a bug - I'm a case in point - and some beginners become contributing experts.  I'm not bad with computers - have over 600 lines in my .vimrc - and I almost uninstalled spacemacs multiple different times before I ever got it anywhere close to usable, and would have without the support I got in the chat room, and definitely would have uninstalled if I hadn't come into Spacemacs already believing in it.  That's way too high of a bar for entry.

**Comment by geo7** [comment]
@ipsod I agree :+1:  - though this might be better of as a separate [discussion] issue
if you have thoughts re this kind of thing.

**Comment by geo7** [comment]
@TheBB this might be another candidate to close (think the Org 24.3 issue is being handled on a different thread somewhere?)

**Comment by robbyoconnor** [comment]
That and support for 24.3 is slowly being removed

**Comment by AdrieanKhisbe** [comment]
@robbyoconnor I concour :)

**Comment by syl20bnr** [comment]
We dropped support for 24.3 in develop branch so I mark this as "fixed" in develop :-)

**Comment by robbyoconnor** [comment]
If you're on Ubuntu 14.04 -- There is a ppa for emacs 24.5 -- google around.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
