### ISSUE TITLE
Names for Prefix Commands

### ISSUE THREAD

**Issue by Profpatsch** [syl20bnr/spacemacs#2727]
See e.g. https://github.com/syl20bnr/spacemacs/issues/2713#issuecomment-133764648
It’s part of self-documenting the possibilities.

If it already exists it should be documented.

**Comment by syl20bnr** [comment]
To be sure I understand the issue, you are asking for a documentation on how to give names to prefix commands ? Maybe as well an explanation about what they are etc... ?

**Comment by Profpatsch** [comment]
@syl20bnr Yes. Of course provided there is a way.

**Comment by justbur** [comment]
Instead of documenting the (IMO inelegant) current method for 0.104, can I suggest changing the way keys are bound to integrate the naming of prefixes with the binding of keys, so that the whole process is more transparent and easier to understand. I came up with one proposal in #2731. Of course this would be a bigger initiative, and I would not want this to hold up the 104 release.

**Comment by justbur** [comment]
I can add documentation, but I'm not sure where to put it

**Comment by syl20bnr** [comment]
Create a section in the documentation for setting key bindings if it does not exist yet.

**Comment by justbur** [comment]
Added documentation to #2876

**Comment by justbur** [comment]
Probably can be closed now
