### ISSUE TITLE
! in filepath breaks backwards-spacing in helm-find-files

### ISSUE THREAD

**Issue by Profpatsch** [syl20bnr/spacemacs#2737]
e.g. when in `foo/bar/!lang/` hitting backspace deletes the last char (`/`) instead of the last directory (`!lang/`).

Not sure how to find out what backspace does, since `C-h k` doesn’t work in helm (yay for breaking global invariants).

**Comment by Profpatsch** [comment]
Ok, interestingly arrow left still works.

If I have `/!foo/bar/baz/` everything deletes char-wise, if I have `/foo/bar/baz` at most `baz` deletes char-wise.

**Comment by TheBB** [comment]
Ping @tuhdo. `helm-find-files-initial-input` breaks here, so the advice falls back to the original behaviour.

Any reason we can't just define backspace in `helm-find-files-map`?

**Comment by justbur** [comment]
I was looking into this just now. I don't completely understand the code in helm-files.el yet, but it looks to me like helm expands the directory if there is only one candidate left after deleting a character. I think the problem is that if you delete the last "/" there are many candidates left still, and this is preventing helm from "expanding" to the sub-directory. My guess is this has something to do with "!" being a special character in helm pattern matching (related to major-mode of buffers or something). If I'm right we should be able to find a character that's not special to helm and everything should work fine again. 

@Profpatsch Left arrow is bound to `helm-find-files-up-one-level` so it makes perfect sense that that works. 
@TheBB I don't think that's a good solution because it is possible and useful to delete single characters in some cases. Start entering a non-existent directory for example. 
@TheBB I don't think it's reasonable to remap delete, because

**Comment by syl20bnr** [comment]
The issue has not been fixed but we moved the folders to `+` prefix :-)
