### ISSUE TITLE
gocode doesn't work well on windows7

### ISSUE THREAD

**Issue by LuoPX-15510486969** [syl20bnr/spacemacs#2750]
i have installed gocode.exe on my windows7 and after i put "go" in .spacemacs it only installed go-mode and go-eldoc . According to lang/go/packages.el it should install another three package company company-go flycheck, but it doesn't. look at the screenshot of packages.el
![qq 20150825101626](https://cloud.githubusercontent.com/assets/13256245/9457171/82df7bec-4b12-11e5-815e-5a020a524b5c.png)

another question : when i type in go-mode it is very slow.i don't know what should i do to fix this problem.

**Comment by TheBB** [comment]
Just because the packages are listed doesn't mean they will be installed. The `auto-completion` layer is for company and the `syntax-checking` layer is for flycheck.

**Comment by sooheon** [comment]
Just to add on, you can see this because the use package definitions are called `*/post-init-*` and one of them is only eval'd `when (configuration-layer/layer-usedp 'auto-completion)`. 

Unrelated, but re: the go layer, I think it should handle racer installation within the layer as well, with the recent changes to it. It's pretty unclear as it is looking at the readme how exactly you're supposed to set up racer.

**Comment by LuoPX-15510486969** [comment]
thanks a lot. after i add auto-completion and syntax-checking it works.   i agree with @sooheon ,after i read the go readme ,i dont know how to install it .so it is a good advice to complete the doc. a

another question i don't know whether it is related spacemacs .  when i type in go-mode ,it was so slowly .But on ubuntu it does not occure.
