### ISSUE TITLE
spacemacs with gocode backend on windows does not work well

### ISSUE THREAD

**Issue by LuoPX-15510486969** [syl20bnr/spacemacs#2791]
gocode can work with complete but when i type i have to wait second to another type.for example when i type"fmt" ,after type "fm"have to wait for seconds to type"t". but on ubuntu it works well.
After i configure a pure emacs environment, it works well.so i think it is some setting due to the problem ,but i dont know where

**Comment by StreakyCobra** [comment]
@LuoPX-15510486969 Do you still have this problem with the last spacemacs release after updating the packages also?

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
