### ISSUE TITLE
undo-tree gives issue occasionally

### ISSUE THREAD

**Issue by danielwuz** [syl20bnr/spacemacs#298]
Once in while I get `unrecognized entry in undo list undo-tree-canary` from undo-tree-undo and couldn't undo to further history beyond that point. Need to fix this.

**Comment by deech** [comment]
I'm on Emacs 24.4 and Commit "Merge branch 'develop' (v0.32.0)" (051dad0694b6399b60749a6a7519f03a1f13fef2). I still get this happen quite often and have lost work in the process. Unfortunately I can't reproduce reliably.

**Comment by syl20bnr** [comment]
I believe to have get rid of it in version 0.36.0 and above. I had to remove the support for persistent undo history which is the problematic feature but not 100% sure. Since it is a rather annoying bug I prefer to play safe here. I did not encountered the bug since the last changes in 0.36.0, so I hope it will work for you as well.

**Comment by ralesi** [comment]
I would like to work on getting persistent-undo back.  Is there a use case where this always occurs?  I will look into it further, as I would like to make the undo-tree usage more like in Vim.  

Is there any functionality built into Emacs that allows linear undo / redo?

**Comment by syl20bnr** [comment]
What's the main differences with the Vim behavior ?

There is no known repro step this is why I had to revert it back in trunk. To be honest I don't want to reactivate it in my personal config because it can be really annoying and it is easy to loose several minutes of work.
If it does not happen in your config then I don't know how we can deal with it.

If undo-tree-mode is not active then I guess that undo / redo is linear.

**Comment by adamdavislee** [comment]
For me the issue was simply that I was executing the `undo` command, while the `undo-tree-mode` was enabled.  I simply needed to use the `undo-tree-undo` command instead.

**Comment by cremacs** [comment]
I still have this issue (undo-tree-canary) whenever I do a long series of edits. Is there a recommended solution?

**Comment by aaronjensen** [comment]
I'm seeing this as well. It's probably a separate issue from this original one, but it's certainly still an issue

**Comment by sickill** [comment]
I'm on 0.200.7 and still experiencing `unrecognized entry in undo list undo-tree-canary`. Lost work because of this :(

**Comment by ideasman42** [comment]
Also still experiencing this problem, could this bug be re-opened?

**Comment by xuhdev** [comment]
Is [this](https://lists.gnu.org/archive/html/bug-gnu-emacs/2014-01/msg01106.html) relevant?

**Comment by aaronjensen** [comment]
Possibly, but it's 3 years old at this point 😢

**Comment by xuhdev** [comment]
It seems to me that if you update to the latest version (master) of undotree and clean up your undo cache, this issue no longer occurs. There is no need to modify configuration.

**Comment by jonathanj** [comment]
I just had this happen to me again on `develop` (updated within the last few days), I've had `(setq undo-tree-enable-undo-in-region nil)` set for a few weeks. So it would seem to me that this issue most definitely still exists.
