### ISSUE TITLE
auto-completion does not work in ESS/R for user-defined variables

### ISSUE THREAD

**Issue by YulongNiu** [syl20bnr/spacemacs#2988]
I am using `company` mode in the `auto-completion` layer. 

Here is a piece of  R codes for an example:

``` r
testFun <- function(x, y) {

  testVec <- rep(x, y)
  ## auto-completion does not work
  test
}
```

I defined the variable `testVec`, and  the `testVec` candidate would not show up after I typed  `test`.

**Comment by TheBB** [comment]
Does it work with ESS/company outside of Spacemacs? If not, consider reporting upstream to ESS and dropping a link to your bug report (or feature request) here.

**Comment by TheBB** [comment]
Do you have an R process running? Looking through the ESS source it looks like you need one, but I can't be sure as I don't use R.

**Comment by YulongNiu** [comment]
@TheBB Thanks! This problem is repeated in a Emacs only containing `ess` and `company` packages, and an related R process was running. I submitted an issue to ESS emacs-ess/ESS#235.

**Comment by vspinu** [comment]
> I defined the variable testVec, and the testVec candidate would not show up after I typed test.

Completions are only shown for defined symbols, that is variables that already exists in the R's global enviornment. You want a completion for local variable which ESS cannot do, even if you evaluate the function.  

Normally company-dabrev backend should kick in and show you symbols in the same buffer, but it does not. Probably because of how company works.

**Comment by syl20bnr** [comment]
I think `company-dabbrev-code` should grouped with https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/ess/packages.el#L85

**Comment by vspinu** [comment]
Yes. This could be a workaround but I wold leave this to the user. I personally use dabrev/hippie  expansion  so I would not want dabbrev to pupup in my company. 

BTW, hardwiring company backends for ESS might not be a good idea. ESS might change it's [`ess-company-backends`](https://github.com/emacs-ess/ESS/blob/master/lisp/ess-r-d.el#L193)  definition  because it's likely to change slightly in the near future. Why do you need this in the first place? ESS activates company by default.

**Comment by StreakyCobra** [comment]
As explained by the upstream developer the behaviour is intended, and, as it's a matter of personal preferences, it's better to leave the choice to the user. I'm closing it, but feel free to open a new issue at any time in case of troubles :relaxed:
