### ISSUE TITLE
how to install key-chord properly?

### ISSUE THREAD

**Issue by tkossak** [syl20bnr/spacemacs#3025]
I installed `key-chord` using `list-packages` but it was removed after restarting emacs with the following message:

    Found 1 orphan package(s) to delete...
    --> deleting key-chord... [1/1]

How should i install it properly?

I need `key-chord` to make <kbd>jk</kbd> binding to exit insert mode.

**Comment by TheBB** [comment]
Add it to `dotspacemacs-additional-packages`, alternatively set `dotspacemacs-delete-orphan-packages` to `nil`.

**Comment by TheBB** [comment]
But why can't you just `(setq evil-escape-key-sequence "jk")`?

**Comment by geo7** [comment]
Just commenting on the off chance that this is from
[this thread](https://github.com/syl20bnr/spacemacs/issues/2292) and possibly
[this comment](
https://github.com/syl20bnr/spacemacs/issues/2292#issuecomment-121190474). Since
this issue (I've now edit my comment there) `evil-escape` is functioning better
and I have disabled the key chord that I was previously using.

@tkossak Anything installed will be removed unless it's put into
`dotspacemacs-additional-packages` (or setting delete orphan packages,
personally I'd rather add to additional though).

[Here's a link to the documentation for adding an additional package](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#without-a-layer) -
note whether you are reading the documentation for Master or Develop branch
though (this is a link to the master) as somethings might be slightly different.
Eg "*just put the configuration in the dotspacemacs/config*" would be
"*dotspacemacs/user-config*" in develop.

******

## Note

A current problem with `evil-escape` is mentioned in #2938

**Comment by tkossak** [comment]
> But why can't you just (setq evil-escape-key-sequence "jk")?

Thank you. I didn't know it's possible without key-chord! I'm new to spacemacs but slowly reading the documentation :)

**Comment by TheBB** [comment]
:+1:

Presuming this is fixed.

**Comment by wires** [comment]
I could not get the remapping to work without adding `key-chord` to `dotspacemacs-additional-packages` first:

```elisp
(defun dotspacemacs/layers ()
  ;;...
  (setq-default dotspacemacs-additional-packages '(key-chord))
  ;;...
)

(defun dotspacemacs/user-config ()
  ;;...
  (setq-default key-chord-two-keys-delay 0.2)
  (setq-default evil-escape-key-sequence "jj")
)
```

**Comment by wires** [comment]
(updated prevous comment, the pasted code didn't work well)
