### ISSUE TITLE
Can't change tab-width in text-mode, markdown-mode, fundamental-mode

### ISSUE THREAD

**Issue by thiru** [syl20bnr/spacemacs#3037]
I came across this issue trying to get markdown-mode to use 2 spaces for tabs instead of 4.  But even after disabling the markdown layer, I can't seem to do the same when in text-mode nor fundamental-mode.

I've tried putting the following in `dotspacemacs/config` but to no avail.

    (setq indent-tabs-mode nil)
    (setq tab-width 2)

I also tried putting it in a mode-specific hook e.g.:

    (add-hook 'text-mode-hook (lambda ()
                            (setq indent-tabs-mode nil)
                            (setq tab-width 2)))

I'm running under Arch Linux x64, Emacs 24.5.1, Spacemacs master branch (last commit d993a021847cde2c42865bab6afa8adbb2edda0b - 30 Aug 2015).

**Comment by TheBB** [comment]
Setting `tab-width` in `dotspacemacs/config` won't have the effect you want because it's a buffer-local variable, so if you set it it will take effect in the buffer that happens to be open at the time the code is run. (The home buffer, most likely.) You can `setq-default` instead.

The hook should work though. Can I see a sample file where it doesn't? Does it have any tab characters?

**Comment by TheBB** [comment]
Your hook works fine for me. I trust you understand that `tab-width` controls the displayed width of actual tab characters in the file, and not the behaviour of the tab *key* as such? It's a common mistake to make.

**Comment by thiru** [comment]
Hi, first off thanks for your response!

My understanding was that by setting `indent-tabs-mode` to `nil`, spaces would be used in place of tabs.  Is that incorrect?  I've been testing with empty text and markdown files.

What I'm seeing is that 4 spaces are always being inserted in both plain text files and markdown files, except when pressing the TAB key in a text file (which correctly inserts 2 spaces).  So when I use the *>>* command in normal mode in a text file or markdown it inserts 4 spaces to the beginning of the line.

I just tested this on develop as well with the same behaviour.

**Comment by TheBB** [comment]
Yes, when you set `indent-tabs-mode` to `nil`, spaces are inserted instead of tabs when you hit the tab key or use other indentation tools. *How many* spaces are inserted is specific to the major mode in question and must be configured separately for each major mode.

I don't know how this is done in markdown mode, but with the markdown layer enabled I get two spaces of indentation automatically. That is, when hitting TAB while in insert state, the cursor cycles through a handful of positions which are offset by two spaces.

Sometimes you open a file with a tab character in it (this can happen independently of the setting of `indent-tabs-mode`. Then, Emacs needs to know how many spaces that tab character should be displayed as. This is what `tab-width` does. It has nothing to do with indentation.

**Comment by TheBB** [comment]
For the record, `>>` and `<<` will shift text by whatever is the value of `evil-shift-width`, which can be different from `tab-width` or other indentation settings.

**Comment by TheBB** [comment]
Sorry for the spam, but I have to ask why you would want to indent in markdown though, since AFAIK you're not really supposed to. Anything indented by four spaces or more is considered to be code, right? It could be that markdown just doesn't support a lot of indentation settings for that reason.

**Comment by thiru** [comment]
Ah hah!  I wasn't aware of `evil-shift-width`.  How come that doesn't use the value of `tab-width` (just curious)?

So with that, it solves all my tabbing woes except that markdown mode still inserts 4 spaces when I hit the tab key.  But like you said that is major mode-specific so I'll see if I can figure that one out by looking at the markdown mode docs.

I use markdown for note taking primarily and I like using ordered and unordered lists everywhere.  So that lends itself to deep nesting at times.  And I think you're right in that last comment because it seems markdown mode in Emacs seems to want to limit my indentation to no more than two levels.  I've also noticed that when converting markdown to HTML, the indentation is often limited to just a few levels.  I don't see why it can't simply support arbitrary indentation?

Anyway, I'm planning to learn Org mode soon so that should drastically reduce my markdown use.  I hope Org mode supports arbitrarily deep list indentation..

**Comment by TheBB** [comment]
Yes, org is great for this.

> I wasn't aware of evil-shift-width. How come that doesn't use the value of tab-width (just curious)?

Because those are really different things. `evil-shift-width` is about indentation and `tab-width` is about displaying tab characters. I've been meaning to figure out a way to get `evil-shift-width` to automatically listen to the major mode's indentation settings... but nothing final so far.

**Comment by thiru** [comment]
Ok I see.  That would be great if you could get that working.  But I'm sure that's a lower priority item, and understandably so.  Thanks so much for your help on this!
