### ISSUE TITLE
[OS X] Installation problem (no such file or directory evil)

### ISSUE THREAD

**Issue by franleplant** [syl20bnr/spacemacs#3039]
Hi!
    Im trying to install spacemacs on OS X but I get this error when running it with 

`emacs --debug-init`

```
Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "evil")                                                                                                                     |  require(evil)
|  eval-buffer(#<buffer  *load*> nil "/Users/myUser/.emacs" nil t)  ; Reading at buffer position 249
|  load-with-code-conversion("/Users/myUser/.emacs" "/Users/flp/.emacs" t t)
|  load("~/.emacs" t t)
|  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\20$
|  command-line()
|  normal-top-level()
```

**Comment by syl20bnr** [comment]
First thing to do is to remove your `~/.emacs` file, it prevent spacemacs from being loaded correctly.

**Comment by StreakyCobra** [comment]
@franleplant What's the status of this issue?

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
