### ISSUE TITLE
start-eclimd and stop-eclimd cannot be called interactively

### ISSUE THREAD

**Issue by martinmr** [syl20bnr/spacemacs#3073]
I am using the Java layer which uses emacs-eclim. This package ships with two functions, start-eclimd and stop-eclimd (both in eclimd.el) which make it easier to handle the eclimd service. However, I cannot call these functions interactively ("SPC + :"). I don't know enough about emacs packaging to know if the issue lays in the way spacemacs is importing emacs-eclim or with the package itself. I'd appreciate it if someone could take a look at this issue.

**Comment by martinmr** [comment]
@kleewho: You might be able to help me with this since you wrote the layer. Thanks.

**Comment by TheBB** [comment]
`start-eclimd` is interactive, so you can run it from `SPC :`, but it isn't auto-loaded so the function isn't available until eclimd is loaded.

On the other hand, the java layer readme says that you must have `eclimd` already started. The layer isn't intended to try to start, stop or control eclimd. Therefore, you should probably start eclimd manually.

Since there's been no movement here for 11 days, and since I'm trying to clean out old issues, I'm closing this. Feel free the open a new issue if you consider this an important feature.
