### ISSUE TITLE
swiper with spacemacs

### ISSUE THREAD

**Issue by drorbemet** [syl20bnr/spacemacs#3074]
I got kind of addicted to swiper and counsel and now I am thinking about moving from prelude config to spacemacs.
Are there some thoughts on using swiper optionally or as a replacement for some use cases covered by helm in spacemacs?

**Comment by EricCrosson** [comment]
`helm-swoop` completely replaced swiper in my book. Are you aware of any functionality of `swiper` that `helm-swoop` doesn't bring to the table?

**Comment by syl20bnr** [comment]
Spacemacs uses` helm` everywhere instead of `ido` and `swiper` is an `ido` like package. I hope that `helm` will meet your expectation (be sure to be aware of multiple selection with `C-SPC` and the context menu by pressing `C-z`). The functionality of swiper are provided on `SPC s s` (`SPC s S` to search for selection or symbol under point).

Spacemacs is a very opinionated kit pushing further the idea of a starter kit so you have to make some concession and embrace the spacemacs way to do stuff, if you don't like it you can always exclude packages and create your own layer, Spacemacs is still Emacs and you can change everything. At the very least with Spacemacs you benefit from the layer architecture.

**Comment by drorbemet** [comment]
With ivy / swiper / counsel I can attach and run custom commands which take a match as input and execute on the fly while searching without leaving the search results and without leaving current text buffer which I am working at. It feels like a generic completion function.

Use cases are e.g. collecting the text surrounding matches from multiple files into current text buffer  or copying files and folders into current directory (or moving,  opening with desktop app, deleting, inserting content, etc.).

With e.g. counsel-ag or counsel-locate I can change the following on the fly without terminating the search session:
- the search pattern 
- the selection of a match
- and the custom operation on a match

Furthermore the ivy buffer supports normal text editing commands and therefore feels very convenient and familiar like to any other text buffer in emacs. And it displays the count of matches while searching.

http://oremacs.com/2015/04/16/ivy-mode/
http://oremacs.com/2015/07/23/ivy-multiaction/
http://oremacs.com/2015/04/22/swiper-0.3.0/

**Comment by syl20bnr** [comment]
Please check Helm, as I said especially C-SPC for multiple selections, C-z for actions.
Check the persistent actions which execute an action without leaving the search.
When Helm is active, `C-c ?` to get the help. For instance try `SPC f f` to find files and `C-c ?`.
You can transform a helm result to a stand alone buffer with F3.

Also check: 
Search in files: https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#searching
Find and replace is search result: https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#replacing-text-in-several-files

Honestly [Helm](https://github.com/emacs-helm/helm) is a _very_ powerful and complete package, I doubt that there is a killer feature in swiper that cannot be done in Helm, this is all a matter of changing habits :-)

**Comment by syl20bnr** [comment]
Also check fuzzy matching with helm.
I think the best is just to redirect you to @tuhdo tutorials: http://tuhdo.github.io/helm-intro.html

**Comment by justbur** [comment]
Not sure what the difference between this and helm-swoop is but there's a version of swiper that uses helm, [swiper-helm](https://github.com/abo-abo/swiper-helm).

**Comment by sooheon** [comment]
@drorbemet I think spacemacs is pretty deeply integrated with helm for now. I have a personal swiper/counsel/hydra/lispy config which I use, 90% replacing the equivalent helm commands, and I have no problems so far. I could share it if you'd like, but it would be more useful just for you to take some ideas from. Mostly, I think it's up to the user to set it up if they want something other than helm, as its a core feature of spacemacs.

OTOH, there is the `dotspacemacs-use-ido` variable, so a `dotspacemacs-use-ivy` replacing some uses of helm with swiper/counsel/ivy equivalent would not be unprecedented.

**Comment by justbur** [comment]
I was playing around yesterday with creating a new "distribution" of spacemacs that doesn't use helm, and it wasn't that hard to put together something functional with ivy and friends. There are a couple of places that would need more work, `SPC feh` for example is built for helm, but the basic find-file, switch buffer, search, etc. commands are pretty easy to swap out. 

I think going the alternative distribution route is preferable in this case to the dotspacemacs variable, because so much has to change (that ido variable only changes the binding for `SPC ff` so it's not that useful). This is a big project, but if it's kept independent from the rest of spacemacs as a distribution I don't see any harm to having the option to go helm-free.

**Comment by syl20bnr** [comment]
Helm is deeply rooted in the Spacemacs design and it is expected to be present. Ido option is anecdotal and is more here for historical reasons. I see a lot of maintenance burden to support a replacement of Helm for little benefits. The distribution route is very interesting in the sense that in the future (really not a priority for now) we can provide a way for users to use Spacemacs with their own distribution, it will then be possible for anyone to create, distribute and maintain a different distribution of Spacemacs. This would be really cool but let's focus on layout and windows first (release 0.105).

**Comment by incandescentman** [comment]
@sooheon Your swiper/counsel/hydra/lispy config sounds interesting. What does it do?

**Comment by sooheon** [comment]
@incandescentman I found that I liked a lot of the design choices abo-abo made. For example, I much prefer the ivy interface combined with hydra over helm. I've replaced most generic helm completions with the equivalent ivy commands. Hydra I use mostly as an extension to swiper, and for other small hydras in org mode, etc. I'd like to use it instead of micro-states when applicable, but nothing like a systematic replacement. And lispy is pretty indispensable for me, while evil-lisp-state I've found a bit clunky. I've added a few bindings to make it a mostly complete superset of traditional paredit bindings + lispy's modal bindings at special point.

A quick example of a helm-swoop type swiper search with a hydra for extra modal actions:
<img width="732" alt="screen shot 2015-11-06 at 10 03 33 pm" src="https://cloud.githubusercontent.com/assets/302945/10997731/cc143ee8-84d2-11e5-9f72-95067b6d7852.png">

Looking over it now, it feels too personalized to be a proper layer, but as I love spacemacs so much, I'm always mulling over how best to contribute to integrating these packages I love into it as well.

**Comment by incandescentman** [comment]
@sooheon This is awesome.

**Comment by sooheon** [comment]
@incandescentman try pressing `C-o` in ivy :)

**Comment by mrkgnao** [comment]
@sooheon I wonder how much more I'm missing. 😲

**Comment by sooheon** [comment]
@mrkgnao Feel free to jump in the deep end with ivy, just read through the [README](https://github.com/abo-abo/swiper) and feel free to ping me with any questions.
