### ISSUE TITLE
Document the differences between spacemacs and spacemacs-base

### ISSUE THREAD

**Issue by xfq** [syl20bnr/spacemacs#3180]
I searched `README.md`, `doc/DOCUMENTATION.org`, and `doc/FAQ.org`, but found nothing about the differences of these two distributions.  The only place I found a little info about them is in `dotspacemacs/install`, but IMHO the info there isn't enough.  As a user, I'd like to know the exact differences between these two distributions to help me make a choice, e.g., which packages are in `spacemacs` but not in `spacemacs-base`.

**Comment by robbyoconnor** [comment]
`spacemacs-base` is a stripped down version. `spacemacs` builds off of `spacemacs-base`.

**Comment by justbur** [comment]
@xfq https://github.com/syl20bnr/spacemacs/issues/2937 shows the differences. I agree though. It should be explained in the docs

**Comment by roytruelove** [comment]
The difficult part for me (as a beginner) is that if you diff the `spacemacs` and `spacemacs-base` distributions is code in `spacemacs-base` that isn't in `spacemacs`.

**Comment by TheBB** [comment]
> However if you diff the spacemacs and spacemacs-base distributions [there] is code in spacemacs-base that isn't in spacemacs

The spacemacs-base layer is used implicitly and unconditionally. Therefore someone who is using the spacemacs layer is actually using both the spacemacs layer **and** the spacemacs-base layer.

**Comment by benthamite** [comment]
I wasn't able to find the files referenced in the [relevant FAQ section](https://develop.spacemacs.org/doc/FAQ.html#what-is-the-difference-between-spacemacs-base-and-spacemacs-distributions). In general, there appears to be precious little information about `spacemacs-base`, which makes it difficult to build a minimal configuration methodically. I would appreciate some additional documentation, ideally what layers and/or packages would turn `spacemacs-base` into the standard `spacemacs` distribution, so that those who want to transition to the former can do so by gradual elimination.

**Comment by syl20bnr** [comment]
Let me see what I can do to improve this.
