### ISSUE TITLE
Haml-mode with minor robe-mode

### ISSUE THREAD

**Issue by FiloSpaTeam** [syl20bnr/spacemacs#3236]
The Haml files have their own structure, but there is the possibility that those contain ruby functions.
Enabling minor robe-mode, we can have with robe server activation the autocompletion

**Comment by robbyoconnor** [comment]
Doesn't haml-mode handle this already?

**Comment by robbyoconnor** [comment]
In either case, this is easily fixed.

**Comment by FiloSpaTeam** [comment]
``` lisp
(defun html/init-haml-mode ()
  (use-package haml-mode
    :defer t
    :config
    (progn
      (tagedit-add-experimental-features)
      (add-hook 'haml-mode-hook (lambda () (robe-mode 1))))))
```

Can be a solution?

**Comment by robbyoconnor** [comment]
My elisp-fu is bad.

**Comment by FiloSpaTeam** [comment]
Yeah ;-) i'll try and if works, push to develop.

**Comment by robbyoconnor** [comment]
don't push to `develop` -- use a feature branch and do a PR.

**Comment by FiloSpaTeam** [comment]
ok perfect ;)

**Comment by StreakyCobra** [comment]
@FiloSpaTeam Do the provided answers fulfil your needs? If no, can you explain what do you expect/need more? If yes, this issue can probably be closed :relaxed:

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
