### ISSUE TITLE
Solarized theme line number background

### ISSUE THREAD

**Issue by fladd** [syl20bnr/spacemacs#3241]
The line numbers (when shown) are not having a different background colour, as it is the case in the original Solarized Vim theme. Instead, they seem to have the same background as everything else.

**Comment by robbyoconnor** [comment]
@fladd, This is something that has to be addressed upstream, perhaps report this upstream and link to this issue we can track it. There won't be a direct 1 to 1 correlation between the emacs and vim color schemes sadly.

**Comment by person808** [comment]
@robbyoconnor @fladd We still use a fork of solarized-theme, leftover from when it was the default. This could be a case of the local version of the theme being behind the upstream version.

**Comment by TheBB** [comment]
Well, I just tried the upstream, and it has the same "problem."

* Theming is subjective in any case.
* There's no reason to expect a one-to-one correspondence between Vim and Emacs themes.
* We're likely to remove our Solarized fork soon in any case.
* It's easy to tweak themes in user config.

So I don't it's worth spending time on this.

**Comment by fladd** [comment]
"There won't be a direct 1 to 1 correlation between the emacs and vim color schemes sadly."

Why not?
What exactly is the upstream version? Where to get that? And where to get the Solarized theme from, once it is removed from the core Spacemacs distribution?

**Comment by TheBB** [comment]
Upstream for Solarized in Emacs is here: https://github.com/bbatsov/solarized-emacs. It's preferred to [this one](https://github.com/sellout/emacs-color-theme-solarized) due to being on MELPA. You can report your issue there, but, as I said, this is not difficult to fix in your own config.

Once it's removed from Spacemacs it will be auto-magically downloaded if you use it, as is the case with any other theme right now. You won't have to change anything.

Themes can differ for any number of reasons: they are maintained by different people, Emacs defines faces for different things than Vim does, etc.
