### ISSUE TITLE
 Variable binding depth exceeds max-specpdl-size

### ISSUE THREAD

**Issue by mukhali** [syl20bnr/spacemacs#3254]
hi

my system is

#### System Info
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.104.2
- Spacemacs branch: master (rev. 074f425)
- Distribution: spacemacs
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory nil)
 better-defaults restclient unimpaired vim-empty-lines semantic
 (eyebrowse :variables)
 emacs-lisp git html ipython-notebook
 (python :variables python-test-runner 'pytest)
 markdown
 (latex :variables latex-enable-auto-fill t)
 emacs-lisp shell-scripts windows-scripts common-lisp
 (org :variables org-enable-github-support t)
 (shell :variables shell-default-shell 'shell shell-default-height 50 shell-default-position 'bottom)
 (syntax-checking :variables syntax-checking-enable-tooltips nil)
 (colors :variables colors-enable-nyan-cat-progress-bar t colors-enable-rainbow-identifiers t)
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 smex deft prodigy rcirc version-control
 (mukhali :variables chinese-enable-youdao-dict t))
```
when i run  pytest-all 

```
 Variable binding depth exceeds max-specpdl-size
```

display.

customize-variable show max-specpdl-size = 1500,

why ? can anyone tell me how ?

**Comment by syl20bnr** [comment]
Seems to be a bug with the package itself (pytest).

**Comment by mukhali** [comment]
thx

**Comment by CestDiego** [comment]
@mukhali has the issue been resolved?

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
