### ISSUE TITLE
orgmode.org is down

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#3270]
This is known. Nothing we can do. I am opening this issue if for no other reason, so others do not.

**Comment by Xe** [comment]
Melpa seems down too

**Comment by duerrp** [comment]
I think there should be a timeout on the package repositories so that the basic bootstrap installation works even when orgmode is down. The only way I could fix my attempt at "Update" was by commenting the orgmode repo in core-configuration-layer.el. Without bootstrap, the rollback function does not work either btw., spacemacs never got to a state where the button was active.

**Comment by robbyoconnor** [comment]
It's back up -- so I am closing this.

**Comment by duerrp** [comment]
Shall I open a new issue for the timeout? Right now spacemacs' update / rollback mechanism does not work if any of the package sources is down.

**Comment by robbyoconnor** [comment]
I suppose...i'm just a guy who cares about the project :)

**Comment by EricCrosson** [comment]
I think some handling of this eventuality would enhance the spacemacs experience. It's nice when your editor can roll with the punches instead of error out during the first install. Even just a 'don't mind all the red errors, package update is not expected to work right now' to indicate this issue isn't one to spend time diagnosing

**Comment by kissgyorgy** [comment]
emacs won't start when you have a package marked for install and the repository is down. That's not expected from a text editor.
Staring 
```
Found 1 new package(s) to install...
--> fetching new package repository indexes...
```
for a couple of minutes now, and and I can't even quit or do anything with C-c.

**Comment by robbyoconnor** [comment]
again?

**Comment by d12frosted** [comment]
Yeah, the same here

**Comment by d12frosted** [comment]
But I also have problems with installing some other packages:

```
--> fetching new package repository indexes...
--> installing spacemacs:evil-anzu... [1/5]An error occurred while installing evil-anzu (error: (error Error retrieving: https://melpa.org/packages/evil-anzu-20150124.1609.el "incomprehensible buffer"))
--> installing spacemacs:helm-themes... [2/5]An error occurred while installing helm-themes (error: (error Error retrieving: https://melpa.org/packages/helm-themes-20151008.2321.el "incomprehensible buffer"))
--> installing spacemacs:highlight-numbers... [3/5]An error occurred while installing highlight-numbers (error: (error Error retrieving: https://melpa.org/packages/parent-mode-20150824.1600.el "incomprehensible buffer"))
--> installing spacemacs:move-text... [4/5]An error occurred while installing move-text (error: (error Error retrieving: https://melpa.org/packages/move-text-20140307.844.el "incomprehensible buffer"))
--> installing spacemacs:vi-tilde-fringe... [5/5]An error occurred while installing vi-tilde-fringe (error: (error Error retrieving: https://melpa.org/packages/vi-tilde-fringe-20141027.1942.el "incomprehensible buffer"))
```

**Comment by Malabarba** [comment]
@kissgyorgy 
> for a couple of minutes now, and and I can't even quit or do anything with C-c.

FWIW, the usual "quit" key in emacs is C-g.

**Comment by kissgyorgy** [comment]
Thanks! I was using it for closing menus and canceling actions, but I was not sure if that's the right key :smile: So you can even cancel running functions?
