### ISSUE TITLE
Use mdfind instead of locate in helm-locate in OS X layer

### ISSUE THREAD

**Issue by Andre0991** [syl20bnr/spacemacs#3280]
I think it would be cool to use `mdfind` as the default command in `helm-locate` on OS X.

By the way, I used to use this code on my own Emacs configuration:

``` emacs-lisp
(setq helm-locate-command
      (case system-type
        ('gnu/linux "locate -i -r %s")
        ('berkeley-unix "locate -i %s")
        ('windows-nt "es %s")
        ('darwin "mdfind -name %s %s")
        (t "locate %s")))

```
(from https://github.com/xiaohanyu/oh-my-emacs/issues/59 )

But it's not working on Spacemacs for some reason.

Thanks.

**Comment by mclearc** [comment]
I would like to see this as well. There is [spotlight.el](https://github.com/benmaughan/spotlight.el) but it uses  [swiper](https://github.com/abo-abo/swiper). It would be great to have the option of using a native helm function. If anyone has tips on how to get this implemented I'm happy to try and help (but I'm totally new to emacs)

**Comment by Andre0991** [comment]
@mclearc I think I got it.

First we have to set `helm-locate-fuzzy-match` to `nil`.

``` emacs-lisp
(setq helm-locate-fuzzy-match nil)
```
Source: https://github.com/emacs-helm/helm/issues/799

Then just use the snippet of code that I posted and `mdfind` works as the command for `helm-locate` - way better than locate on OS X, IMHO.

**Comment by mclearc** [comment]
Thanks @Andre0991, that works great.

**Comment by Andre0991** [comment]
@mclearc No problem.

@TheBB Could you tag this issue as suggestion please?

By default, OS X doesn't even create the `locate` database. So `helm-locate` would be useless in this situation. That's why I think using `mdfind` would be nice.

Besides that, `mdfind` is more standard as it is used in Spotlight and thus using it creates a more consistent experience on OS X.

Of course, there's also the fact that I find `mdfind`'s results much better, but that's just my opinion.

Thanks.

**Comment by d12frosted** [comment]
Can't get `mdfind` working with `helm-locate`. You see, when you type something like `att` in `helm-locate` it actually sends `[^a]*a[^t]*t[^t]*t`. If you try to give it as input to `mdfind` it will return empty list. I am not sure how it supposed to be working. Because `mdfind` doesn't work with regexps. 

```
λ mdfind -name ".*hs" ""
/Users/d12frosted/Library/Caches/Metadata/Safari/History/https:%2F%2Fgithub.com%2Fsyl20bnr%2Fspacemacs%2Fissues%2F335.webhistory
```

But following thing is working:

```
λ mdfind -name "kMDItemFSName = '*.hs'" ""
# a lot of haskell source files
```

But it will not work for input like 

```
λ mdfind -name "kMDItemFSName = 'src/*.hs'" ""
# a lot of haskell source files
```

So really I am not sure. Looks like `mdfind` and `locate` has very different API. So my suggestion would be to use a good wrapper for `mdfind` (like `spotlight.el`, but `helm-spotlight`) and allow users to use it instead `helm-locate`. 

Also, helm already have some spotlight stuff. So it's possible to implement something like

```
(defun helm-spotlight ()
  (interactive)
  (helm :buffer "*helm: spotlight*"
        :sources '(helm-source-mac-spotlight)))
```

But the problem is that `helm-source-mac-spotlight` is not configured as I would like. So I could look into it in future. But if someone wants it now - feel free to experiment and share results! :smile:

**Comment by Andre0991** [comment]
Yeah, I noticed using `mdfind` through `helm-locate` returns slightly different results comparing to running just `mdfind`.

But it is good enough for me. Generally the top results are the same (for the inputs I'm using) in both cases.

Anyway, I'm cool with closing this issue, but if someone comes up with a way to use `mdfind` having exactly the same results as running it outside Emacs, it would be even better and cool to incorporate in the OS X layer.

**Comment by d12frosted** [comment]
@Andre0991 wait, are you saying that `(setq helm-locate-command "mdfind -name %s %s")` works for you (and just returns slightly different output? For me it's empty output.

**Comment by Andre0991** [comment]
@d12frosted Sure, it should work.

Did you change `helm-locate-fuzzy-match` to `nil`?

**Comment by d12frosted** [comment]
@Andre0991 ah well, I didn't. I'll check this out once I am home. Thanks for the tip.
