### ISSUE TITLE
Discussion: Refining the layer system

### ISSUE THREAD

**Issue by justbur** [syl20bnr/spacemacs#3308]
Seeing the discussion between @lunaryorn and @syl20bnr on twitter, I had some ideas.

I think there's a lot of value in the layer system, but I also agree that it's a little daunting to comprehend at first. So I think there's value in refining the concepts to make them clearer and thought it couldn't hurt to discuss them. 

I wanted to throw an idea out that is actually not too different from the current functionality, but which structures things a little differently and which I find simpler to comprehend. As always, feel free to ignore me.

Here is my proposal for the hierarchy:

1. package: Just how emacs uses the idea now
2. configured-package (needs a name probably): This is what the init function does for the most part. It wraps a package in a configuration that plays nicely with the rest of spacemacs and sets good defaults. These are the real value of a project like spacemacs to me at least, and what I want easier access to.
3. layer: declares what configured-packages it uses and potentially performs some *minimal*
integration between them. In this light, layers are for convenience to easily be able to setup some language environment without having to hunt down relevant packages.

The idea then which is a little different from how things are structured now is that spacemacs is a library of configured-packages (all in the same file or each package in its own file). Layers group the configured-packages into ready to use sets targeting languages/functionality/etc. The layers then just become lightweight declarations. 

From the user side, I can easily think in terms of the configured-packages themselves or the layers (package groups). Ideally, I could search the configured-package list or the layer list. I can also provide my own configuration for a package that will be picked up by spacemacs automatically. 

To be clear, I know that any of this can be accomplished in the current system. That's not my concern. I'm simply thinking about experimenting with how things are organized and presented, so as to make the inner workings more transparent.

**Comment by lunaryorn** [comment]
I'd like to note that having played with the layers system for a while, I do now understand its purpose and intent, and think that it is a great idea.  It seamlessly enables be to override those parts of Spacemacs that I do not like, without interfering with the rest.

As such, I do not think that the layer system would profit of adding even more terminology, but rather by better documentation.  Specifically, I missed how-to guides on hooking into layers and packages with pre-init and post-init functions, and failed to extract a crucial piece of information from the existing documentation, namely that spacemacs loads _all_ layer files _before_ calling any functions from the layers.  IOW, each init function in a layer sees all other enabled layers and can hook in or even override any others.

To me, that has been the missing link, and discovering it now lets me understand how the layer system enables isolated configuration, while still providing the right amount of flexibility for my personal configuration.

Thinking of it, the one piece that might really improve the documentation here is probably a little case study:  A user doesn't like Spacemacs’ default configuration for a particular package and wishes to extend or even replace it. How does the layer system enable this?

**Comment by justbur** [comment]
I don't mean to just add terminology, but I think the right unit to think in terms of in spacemacs is a packages init function, at least if you are trying to understand how it works. Once you understand how the package's init function works (as you allude to above), the layer is nothing more than a collection of packages with init functions. 

Maybe it's just a documentation thing, but I do think coming up with useful and appropriate terminology aides understanding.

**Comment by justbur** [comment]
@lunaryorn I do like the suggestion of a case study

**Comment by TheBB** [comment]
@lunaryorn Most of the things you mention are explain in `doc/LAYERS.org`. Did you read this? If you did, feel free to propose clarifications if anything was unclear.

**Comment by lunaryorn** [comment]
@TheBB No, I didn't initially, simply because I wasn't aware of it, and then didn't consider it relevant for my use case. 

Maybe that's also a problem:  `helm-spacemacs` advertises this file as “Tips for writing layers”, which was not what I wanted to know initially.  I didn't even _know_ that I should probably a layer for my purpose—overriding the configuration of a specific package.

I think that the intentions of this document are good, but it doesn't really answers that I have as a user.  It tells me how layers work, what to consider when writing my own layer, etc. but it does _not_ tell me _what_ layers actually enable me to do, specifically entirely “stealing” and thus overriding a package from the `spacemacs-base` layer.

IOW, my use case wasn't “Hey, I want to write a layer, how do I do that and what do I need to consider.”  It was “Hey, I like spacemacs, but I really need a different configuration for `exec-path-from-shell`.  How do cleanly override the built-in `exec-path-from-shell` configuration without messing with the base layer?”

After my convo with @syl20bnr on Twitter I now understand that I can write my own layer that “steals” `exec-path-from-shell` from `spacemacs-base`, but there’s no documentation in Spacemacs telling me that.
