### ISSUE TITLE
Cursor color changed unexpectedly after saving a buffer

### ISSUE THREAD

**Issue by lululau** [syl20bnr/spacemacs#3378]
Using evil-emacs-state to edit a text file which is under a git repo, the cursor color is now sky blue, then save the buffer, and after buffer saving, the cursor color becomes to yellow which is for evil-normal-cursor unexpectedly.

In fact, I noticed that the invocation of `kill-all-local-variables` (invocation chain: `after-save-hook -> diff-hl-update -> diff-hl-changes -> diff-hl-changes-buffer -> vc-call-backend -> vc-git-diff -> vc-git-command -> vc-do-command -> vc-setup-buffer -> kill-all-local-variables`) caused this issue. But I still have no idea about how to fix it. I tried to append evil-refresh-cursor to after-save-hook, but does not work.

The follow steps could be used to recur the unexpected color changing simpler:

1. Open a a file which is under git repository in Emacs.
2. `M-x`, then eval `(save-current-buffer (set-buffer (generate-new-buffer "a temp buffer")) (kill-all-local-variables))` in mini buffer.

**Comment by StreakyCobra** [comment]
@lululau Can you reproduce this problem on `develop`? I can't reproduce it, but I'm also not sure to do it correctly.

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.

**Comment by aaronjszy** [comment]
I had this same problem. It was related to the version-control layer being configured to use `diff-hl`: `(version-control :variables version-control-diff-tool 'diff-hl)` Dropping that variable config solved the problem me.
