### ISSUE TITLE
Document External Dependencies & How To Manage?

### ISSUE THREAD

**Issue by louy2** [syl20bnr/spacemacs#3420]
Looking through `c-c++` layer, `ycmd` is not officially supported on Windows, but is not documented in the layer README. What other such external dependencies are there? For example `javascript` layer is dependent on `tern`. These are not obvious as that `c-c++` surely depends on a C/C++ compiler.
- [ ] `c-c++` : `ycmd`
- [x] `javascript` : `tern`

Then come the question of management. If the packages themselves doesn't guard against the absence of an external dependency (or not well enough) (or just don't want them to be installed at all), consider following options:
- a universal variable to exclude all externally dependent packages
  - a way for layers to mark such packages such as a distinct list
- guard logic provided by layers
- guard logic provided by core

**Comment by syl20bnr** [comment]
I like the idea and we have a reference implementation in Flycheck for this kind of third party check. Would be extremely cool to define a framework to be used globally in Flycheck.

**Comment by syl20bnr** [comment]
cc @lunaryorn (if you have ideas about this).

**Comment by lunaryorn** [comment]
I'm not sure about the intention of this issue, and I do not think that I can contribute ideas.

Flycheck is in a much better position to check for external tools, because by (syntax checker) definition it knows about all external tools it's going to use.  The “framework” to check external “dependencies” is essentially just `executable-find`.  In Flycheck the problem is simple, because it's scope is very limited.

Not so in Spacemacs which does not know all external tools a priori, and cannot easily find out what external tools it's going to use, simply because there's no standard at all, and every package does things differently.  I presume it'll be hard to find a generic solution for discovering external dependencies.  And any manually maintained list—regardless of how and where—is necessarily incomplete.  Such things tend to age soon and get stale very quickly.

And that's not even talking about Windows, which is pretty much a different story.  Again, Flycheck is in a better position here, simply because officially it doesn't support Windows at all :grin:

----

So if you'd like to hear my opinion, I'd say better don't try to do anything about it at all.  The scope of this issue is huge.  Just stay with documenting things, fix documentation if it's missing, and trust your users.  At some point they just have to read documentation of packages.  This is Emacs, after all :sunglasses:

**Comment by louy2** [comment]
I am using Flycheck on Windows day to day and find it awesome. That said I had a bad time with YouCompleteMe, where ycmd is from.

I am pretty much on the line of manual management, of course on the premise that on a layer basis, the external tools can be limited as the Flycheck layer. The problem is not external dependency *discovery*, but rather *control*.

What I mostly indend is less surprise. Some packages with external dependencies attempt to build the dependencies on the first run, which when it triggers errors can show a mess. Because packages are hidden under layers, Spacemacs users don't expect this like other package users do. And indeed it mostly affects Windows users who often don't have a complete building environment setup. From my habit of spf13-vim, I prefer a pure elisp setup to be the baseline.

**Comment by syl20bnr** [comment]
We have already discussed the third party management and we dediced very early to not manage them (i.e. install them or anything). But what I propose here is different than this, it is basically to do the same thing as Flycheck which is to use `executable-find` to check for the availability of third parties.

Between maintaining a prose documentation about thirs party and declaring them in `init` function, my choice is to declare them in code and then be able to do more powerful things like automatic availability check and possibly a new source for helm-spacemacs.

**Comment by justbur** [comment]
It would be cool if this could be handled at the layer level. Upon declaring a layer the layer code could do the executable-finds for the necessary dependencies and issue warnings. This could then be combined with the 24.3 code that was going to be added.

**Comment by louy2** [comment]
From what I understand we are pretty much agreeing on going the Flycheck "guard logic provided by layers" route.

**Comment by lunaryorn** [comment]
I'm not sure why this is the “Flycheck” route… Flycheck really just calls `executable-find`.

**Comment by louy2** [comment]
@lunaryorn Basically it is dispersed package specific whatever guard logic inside a layer, including `executable-find`.

But I found another example, `ycmd`. It's a layer in `+tool` that's configuring this, and `c-c++` is using `post-init-ycmd` to guard the initialization. It basically changes the problem of external dependency to layer dependency.

**Comment by louy2** [comment]
@lunaryorn Now I see I've had a big misunderstanding. The `executable-find`'s are not in `syntax-checking` layer but in `flycheck` package. I'm sorry.

**Comment by lunaryorn** [comment]
@louy2 Indeed, and that's the main difference here.  Flycheck automatically knows what executables to check.  A spacemacs layer not so :)
