### ISSUE TITLE
Spc-f-s breaks evil-repeat

### ISSUE THREAD

**Issue by dvzubarev** [syl20bnr/spacemacs#3433]
Tested on develop and 104.2
use some evil operator (e.g. x) save changes with SPC-f-s, try to use evil-repeat. 
It will not take any effect. No error messages are displayed.

**Comment by StreakyCobra** [comment]
Yep, same here. Doesn't break when using `:w` though.

**Comment by StreakyCobra** [comment]
Oh, I found why it's happening. It **literally** repeats the last action, in this case "saving the file".

It is tricky to verify, but it can be tested with:

1. Create a `test.el` file.

2. Open the file in spacemacs.

3. Paste the following code in it:

    ```elisp
(defadvice save-buffer (before save-buffer-always activate)
  "always save buffer"
  (set-buffer-modified-p t))
```
    
4. Put the cursor on `defadvice`, and do `, e f`.
    This is needed because spacemacs will not write a file if it has not been changed. This advice forces the rewrite in any case.

5. Open an external terminal and run `inotifywait -e modify test.el`

6. Go back to spacemacs, do `x` somewhere to remove a char, the try `evil-repeat` to verify it removing another char, and then `SPC f s`. Notice the file is saved by looking at the terminal displaying `test.el MODIFY`, and also because `inotifywait` as finished.

7. Run again in the terminal the previous `inotifywait` command.

8. Go back to spacemacs and do `evil-repeat`

9. In the terminal `test.el MODIFY` is outputed, the file has been written again.

Conclusion, `SPC f s` is saved as an action that `evil-repeat` will repeat.

**Comment by StreakyCobra** [comment]
I found the solution:

```
evil-declare-not-repeat is a compiled Lisp function in `evil-common.el'.

(evil-declare-not-repeat COMMAND)

Declare COMMAND to be nonrepeatable.
```

And it is working :tada: The question now: @syl20bnr Do we want this behavior as the default in spacemacs?

**Comment by syl20bnr** [comment]
I guess we can check the behaviour in Vim itself but I bet that Evil already chose what Vim does.

**Comment by StreakyCobra** [comment]
I'll check, but I have a doubt, since `:x` is not saved as a repeatable action. I could be due to the fact than `SPC f s` is wrapped inside a custom spacemacs function.

**Comment by StreakyCobra** [comment]
```elisp
(defun spacemacs/write-file ()
  "Write the file if visiting a file.
   Otherwise ask for new filename."
  (interactive)
  (if (buffer-file-name)
      (call-interactively 'evil-write)
    (call-interactively 'write-file)))
```
`evil-write`, nor `write-file`, are saved as reproducible actions, so I suppose `spacemacs/write-file` shouldn't be either.

**Comment by puyo** [comment]
I was having this problem still, and realised it's the `osx` layer's interaction, since it uses `save-buffer` not `spacemacs/write-buffer`. I am working around this problem via:

```
  (defun custom-save-buffer ()
    "Save the buffer but don't muck up evil-repeat"
    (interactive)
    (save-buffer nil))
  (evil-declare-not-repeat 'custom-save-buffer)
  (global-set-key (kbd "s-s") 'custom-save-buffer)
```

Forgive me if my elisp isn't very good, I'm a bit of a beginner.
