### ISSUE TITLE
New `magit-blame-quit` micro-state stays on and breaks when you switch files.

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3467]
It doesn't turn off when you change buffers/files.   After that, you cannot quit at all.

**Comment by syl20bnr** [comment]
This is a limitation of the micro-states, I don't see any satisfying solution to this problem. If we turn off the micro-state when switching the buffer then we have to quit magit-blame as well which is not very practical. We have the same issue with the time machine then.

Seems that a micro-state is not a good fit then.

**Comment by synic** [comment]
Yeah, seems to be a problem with the scroll micro state too.  `SPC n .` and then switching buffers screws it all up.

**Comment by StreakyCobra** [comment]
I don't know the underlying technology, so take my comment as an user point of view, and forgive my mistakes. As I just tested, it seems that a micro-state is specific to a buffer, and there **can not** be more than one micro-state active at the same time, even on different frames. So as soon as a buffer is changed, there is no reason to **keep** the micro-state open.

The question then become: Does it make sense to switch to another buffer when `<micro-state-name>` is active? If **yes**, it shouldn't be a micro-state. If **no**, it can be a micro-state.

For the scroll micro state, I don't really see reasons to switch to another buffer when scrolling, so it can be a micro-state. For the git blame and the time machine micro-states, users can want to switch to another buffer in some use-cases, but I think it is not the majority of cases.

So from my point of view, the better is to **close** a micro-state as soon as the buffer is changed, whether it is scroll, git blame or time machine. Also, git blame and time machine should be kept as micro-states because they are more useful in this form, but additionally other ways can be provided to use these functionalities in a way that allows buffers switching.

Here is my 2 cents.

**Comment by synic** [comment]
There's no use-case for switching buffers with the scroll micro state open, other than the rather large one of "didn't turn scroll micro-state off when I switched buffers", which is exactly what happened to me.

**Comment by StreakyCobra** [comment]
So if micro-state gets always closed when switching buffers it should be fine, no?

**Comment by synic** [comment]
Yes, that would work.

**Comment by syl20bnr** [comment]
I pushed 7107ea5 which should fix this issue. The commit makes `SPC g b` idempotent so one can initiate it in a buffer, then switch to another buffer and discard the micro-state with `q`, when the user comes back to the magit-blame buffer he can press `SPC g b` again to reactivate the micro-state.

**Comment by synic** [comment]
Actually, now `SPC g b` does not enter a micro-state at all anymore, d'oh.  Time machine still works, though.

**Comment by robbyoconnor** [comment]
Works for me

**Comment by synic** [comment]
Hrmm, seems to be working for me now too.  I don't know what I did
differently.

**Comment by synic** [comment]
Should I close this?

**Comment by StreakyCobra** [comment]
When it's Fixed in develop, it will be closed at the next release. If you want to close it in the meantime it's up to you :-)
