### ISSUE TITLE
helm-spacemacs has several packages with nil for the layer name

### ISSUE THREAD

**Issue by justbur** [syl20bnr/spacemacs#3493]
Most of these are packages that are not installed on my system, but I don't think that has anything to do with it.

This also breaks using this tool to jump to these files. 

![caputre2](https://cloud.githubusercontent.com/assets/2208382/10636557/819b428c-77ce-11e5-8114-218d0f285bfe.png)

**Comment by syl20bnr** [comment]
Binding this issue with #3393

**Comment by StreakyCobra** [comment]
On my system all the problematic packages are the ones which don't have an associated `<layer>/init-<package>` function.

It's (probably, I'm still learning :smile:) related to [this line](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+distribution/spacemacs-base/local/helm-spacemacs/helm-spacemacs.el#L239) for the jumping part, and to [this line](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+distribution/spacemacs-base/local/helm-spacemacs/helm-spacemacs.el#L167) for the layer name, because there is no `:owner`, as it is defined as the layer [having the `<layer>/init-<package>` function](https://github.com/syl20bnr/spacemacs/blob/develop/core/core-configuration-layer.el#L267-L276).

But I don't know if the best solution is to set as convention that a layer has to provide a — possibly empty — `<layer>/init-<package>` for each package it is owning, or to adapt the code to deal with case when no `<layer>/init-<package>` function is defined.
