### ISSUE TITLE
c-c++ layer per project variables

### ISSUE THREAD

**Issue by jvillasante** [syl20bnr/spacemacs#3548]
I have this on my `.spacemacs` file:
        (c-c++ :variables
                    c-c++-default-mode-for-headers 'c++-mode
                    c-c++-enable-clang-support t)

I want to set the `c-c++-default-mode-for-headers` on a per project basis. How can I do that?

**Comment by TheBB** [comment]
You can't, but you can add a regexp to `auto-mode-alist` that includes the project name.

```lisp
(push '(".*my-c-project-name.*\\.h\\'" . c-mode) auto-mode-alist)
(push '(".*my-c++-project-name.*\\.h\\'" . c++-mode) auto-mode-alist)
```

**Comment by jvillasante** [comment]
This can be placed on `.dir-locals.el` or must be done on `.spacemacs` file?

**Comment by TheBB** [comment]
Do it in your `dotspacemacs/user-config`.

**Comment by StreakyCobra** [comment]
@jvillasante Does @TheBB solution answered your question?

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
