### ISSUE TITLE
extract layers mechanism as standalone elisp package

### ISSUE THREAD

**Issue by thkoch2001** [syl20bnr/spacemacs#3590]
I believe the layers mechanism of spacemacs could also be interesting for people that want to keep using plain emacs but are looking for a good way to organize their configuration. (me ATM)

It might also help to make spacemacs more approachable. One can start using layers and maybe switch to full spacemacs later?

Hopefully it also becomes possible to use spacemacs layers in plain emacs and thus increase their userbase.

**Comment by a13ph** [comment]
:+1: For a modular Emacs distro it's strangely not modular in some regards
And increase in userbase will probably lead to more layers available and improvements of layer system itself

**Comment by syl20bnr** [comment]
The layer system is not finished.

I originally started to work on it outside of Spacemacs (see Crown repos) but I changed my strategy because nobody would have used it this way. I decided to start implementing it in my configuration as well as documenting it extensively. Few weeks later some people started to try it so the strategy seems to have work.

So basically speaking Spacemacs was a POC and a direct usable application of Crown. Spacemacs has grown quickly and so it took quite some time to implement the desired feature of the layer system without breaking people config.

I'll release the layer system as a stand-alone package at some point but there is still work to be done on it and I want to limit the scope of users to Spacemacs users for now because it makes things a lot easier to manage (especially backward compatibility etc...).

**Comment by a13ph** [comment]
I assume it would be wise to discuss these matters with JW, since he's author of use-package and quite a take on init file, which reminded me of Spacemacs layer system somewhat
Maybe not now, but just at some point. Since it's not urgent, scheduling a talk and asking him to look into our loading and layer setup earlier rather than later might give him time to assess and schedule well, too
(I'm just trying to make all parties happier here)
