### ISSUE TITLE
Flycheck is removed after every launch

### ISSUE THREAD

**Issue by selfawaresoup** [syl20bnr/spacemacs#3677]
I have the `flycheck`package in my `dotspacemacs-additional-packages` but after launch, it is not installed. When I install it manually using `package-install` it works until the next relaunch and then it's gone again. My other packages are not affected by this.

This issue only started popping up recently, I don't know with which version exactly.

**Comment by syl20bnr** [comment]
Interesting behavior.
To know if a package is already supported in Spacemacs you can summon `helm-spacemacs` on `SPC f e h` and type flycheck. You'll that it belongs to the layer `syntax-checking`. So you can add this layer to your layer list.

I keep this opened because we have to fix the behavior you got when adding `flycheck` to additional packages.

**Comment by lnwdr** [comment]
Thanks, adding the 'syntax-checking' layer helped. Flycheck is now installed after launch.

**Comment by robbyoconnor** [comment]
That's definitely a problem -- but (*this is my opinion solely*), I think we should just not support this setup.

**Comment by syl20bnr** [comment]
@robbyoconnor it may be useful to allow it but we can add a warning about the existed layer that contains the same package.

**Comment by robbyoconnor** [comment]
in that case, people should provide their own layer
