### ISSUE TITLE
Helm freezes if you click and drag in the results list

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#3700]
Unclear if this is a helm, evil, spacemacs, or something else bug, but if I click and drag within helm results, it gets me into a state where I can no longer do anything useful in helm. esc, fd, q, etc do nothing to get me out of it. I can enter insert mode and type into the helm results, but this is not useful. I have to `SPC w c` to close it, followed by a `fd` to get back to a useful mode.

**Comment by bmag** [comment]
What happens is that clicking the mouse makes the helm window active. Usually in helm, the minibuffer is the active window, and the helm window shows the results but isn't active. What you need to do is to press <kbd>SPC w b</kbd> (which moves the focus to the minibuffer), and then you can continue with the helm session. If <kbd>SPC w b</kbd> doesn't work, try <kbd>C-x o</kbd> instead.
There was an old issue about this, and I think also a recent PR to add documentation for this (to the FAQ?), but I can't find them right now.

**Comment by aaronjensen** [comment]
Thanks @bmag, I think that we should actually have this not be possible, or much easier to get out of. If there's no reason to have that helm window active, it seems like it should automatically activate the minibuffer or it should make it really easy to get back to it (by binding esc, q, fd, etc all to go back to the mini buffer?)

**Comment by bmag** [comment]
It's not that easy to disable the user from selecting\* another window. Closest thing I know, without doing further research, is that you can try to add a `(no-other-window . t)` window parameter for helm windows, which in some cases prevents the user from selecting that window.
Anyway, this is entirely a helm issue and not specific to spacemacs. I suggest you report the issue to helm instead, or comment on a similar issue if one exists. Keep in mind though that helm is not designed to work with the mouse (I believe), so clicking and dragging results in helm window is kind of abusing helm.

\* "selecting" is the technical term for changing the focus to another window in emacs

**Comment by michael-heerdegen** [comment]
I have closed the Helm issue because what aaronjensen wants has been default behavior in Helm for a very long time.

We have there the option "helm-prevent-escaping-from-minibuffer" that is true by default.  It does two things: it prevents the user from selecting any other window (see "helm-prevent-switching-other-window"), and it deactivates any mouse bindings (see "helm--remap-mouse-mode").  So AFAIK it's really impossible with any means for the user to switch to any other buffer in a Helm session by default.

Maybe you have you deactivated that stuff in spacemacs?

**Comment by TheBB** [comment]
No, that option is `t`, and escaping the minibuffer (with the mouse) is really easy. I see that is not the case with helm on its own, so we must be doing something wrong. Thanks.

**Comment by TheBB** [comment]
I picked apart Spacemacs until I had literally only ten lines of code left, and could still reproduce this issue. Turns out it's a minor incompatibility issue between Evil and Helm. After playing with bisect, it was introduced (from Evil's side, at least) in changeset [1067](https://bitbucket.org/lyro/evil/commits/c48ce9485572f20e4830b0d67cb00b78de225935) (July 28, 2012). That also gives us the solution: override `[down-mouse-1]` in `evil-motion-state-map` during a Helm session. Commit [https://github.com/syl20bnr/spacemacs/commit/d14f10e47d55a27c8b762df505455706ebac096b] fixes this rather long-standing annoyance in develop. :tada:

I will leave it up to @michael-heerdegen or @lyro (CC) whether this should be dealt with in Helm or Evil if at all. At the very least it's dealt with in Spacemacs.

**Comment by syl20bnr** [comment]
Nice :+1:

**Comment by michael-heerdegen** [comment]
Eivind Fonn <notifications@github.com> writes:

> I will leave it up to @michael-heerdegen or @lyro (CC) whether this
> should be dealt with in Helm or Evil if at all. At the very least it's
> dealt with in Spacemacs.

I do know neither spacemacs nor evil, but what you have done sounds
reasonable.  But does this honor helm-prevent-switching-other-window ->
nil correctly now OTOH?  Some people might actually prefer the behavior
you consider a bug.

**Comment by TheBB** [comment]
Good point, I've changed it.

**Comment by aaronjensen** [comment]
Awesome, thanks for tracking this down and fixing!
