### ISSUE TITLE
Editable dired mode has crippled evil mode

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#3776]
If you enter editable dired mode with <kbd>SPC f j</kbd> <kbd>SPC b w</kbd> You end up in an emacs mode. If you hit <kbd>ESC</kbd> the modeline turns orange, indicating evil normal mode, but only hjkl work, nothing else, not even <kbd>i</kbd>. You can't get back into holy mode w/o <kbd>SPC t E e</kbd>.

If it's too much to get full evil mode in it, we should at least disallow <kbd>ESC</kbd> I'd think.

**Comment by elemakil** [comment]
I can not reproduce this. Which spacemacs version are you using?

**Comment by aaronjensen** [comment]
latest develop, all packages updated an hour ago. It seems to repro in vim and hybrid mode.

**Comment by bmag** [comment]
@aaronjensen could you paste the output of <kbd>SPC h d s</kbd>? It shows some more details about your setup.

Also, could you explain what are you trying to do, and what exactly doesn't work as expected?

In dired-mode, <kbd>SPC b w</kbd> enters Wdired (writable dired) which is used to edit the buffer's contents. To properly exit wdired-mode you need to press either <kbd>C-c ESC</kbd> (to abort changed) or <kbd>C-c C-c</kbd> (to apply changes). These bindings will work also if you already pressed <kbd>ESC</kbd>.

**Comment by aaronjensen** [comment]
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 39c69de)
- Distribution: spacemacs
- Layers:
```elisp
(better-defaults emacs-lisp markdown syntax-checking auto-completion erlang elixir git dash html org colors spacemacs-layouts osx vinegar github javascript react deft floobits)
```


I'm trying to use vim mode to make changes in wdired. In evil mode, I'd expect most things to leave me in evil mode, and when they don't, they shouldn't make it so easy for me to get into a pseudo evil mode. Once you hit esc, you're stuck (yes the bindings you mention work, but I couldn't figure out how to get back into insert mode). 

As a new user, these are the sorts of things I run into that are frustrating. I love spacemacs and its philosophies, and I think that "pit of success" is an important philosophy as well, hence issues like this :smile:

**Comment by bmag** [comment]
You're right that it shouldn't be easy to get into a pseudo evil mode, and it does look to me as some integration that needs to be done in spacemacs. But I'm not sure where it should go. As far as I can see, spacemacs doesn't actually have a configuration for dired, other than the vinegar layer (that I see you're using) and the ranger layer. Maybe someone else here who knows more about the dired integration can help.

By the way, for me, `i` from the pseudo evil mode does bring me into insert state (actually hybrid state for me, since I use hybrid editing style).

As for the behavior of `ESC`, binding `ESC` in `wdired-mode-map` should make `ESC` return you to normal evil mode, but it won't catch escaping via `evil-escape`.

About discovering `C-c ESC` and `C-c C-c`, you should see a message about them in the echo area right after you press `SPC b w`. That at least should make the user aware of how to exit Wdired.

Maybe this can be turned into a more concrete dired-related feature request or pull request?

**Comment by ralesi** [comment]
Vinegar uses evilify,  which I think is what is getting you in trouble.   I will take a look if I can switch to normal state when going into wdired.

**Comment by aaronjensen** [comment]
I can confirm that disabling the vinegar layer makes things work a lot better in wdired, so this seems to be specific to vinegar.

**Comment by justbur** [comment]
This is bizarre. Something is wiping out `evil-normal-state-map` locally after entering `wdired-mode`. I don't see what it could be right now. 

By the way, this is a bad choice in the vinegar layer
```elisp
(define-key evil-normal-state-map (kbd "-") 'dired-jump)
```
There is no need to change the global normal-state binding in this case.

**Comment by justbur** [comment]
Got it. It's this
https://github.com/syl20bnr/spacemacs/blob/develop/core/core-evilified-state.el#L77-L78

@syl20bnr why does evilify do this?

**Comment by ralesi** [comment]
> (define-key evil-normal-state-map (kbd "-") 'dired-jump)

@justbur why don't we want to define this?  Part of vinegar.vim was making the directory buffer universally available with `-`.  Similar to `C-x c-j` in dired-x.

**Comment by ralesi** [comment]
I guess we can isolate it to a configuration variable, but it is consistent with the vim version.

**Comment by justbur** [comment]
> @justbur why don't we want to define this? Part of vinegar.vim was making the directory buffer universally available with -. Similar to C-x c-j in dired-x.

Sorry my fault. I misinterpreted the purpose of the function. Ignore that comment

**Comment by aaronjensen** [comment]
This no longer repros.
