### ISSUE TITLE
Always suddenly "Making tags completion table for $some-path"

### ISSUE THREAD

**Issue by colorgmi** [syl20bnr/spacemacs#3850]
When I edit something, this suddenly come to hang the spacemacs; so long, I have no idea what to do.  Can anybody help me?

**Comment by StreakyCobra** [comment]
Can you try to press `C-g` when this happen? And if you can give more informations, like the kind of file you're editing, what you were typing, etc. it would be nice :-)

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
