### ISSUE TITLE
helm-ag - C-g no longer exits.

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3892]
Other helm stuff works fine, but C-g has to be pressed twice to close helm-ag.

#### System Info
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 659d585)
- Distribution: spacemacs
- Layers:
```elisp
(unscroll auto-completion xkcd emacs-lisp jabber git gtags dash yaml github javascript html markdown extra-langs python ruby org osx python django syntax-checking spell-checking version-control lua colors spacemacs-layouts vimscript
          (c-c++ :variables c-c++-enable-clang-support t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by justbur** [comment]
This is not likely to be a spacemacs issue. Is there something that leads you to believe it is?

**Comment by justbur** [comment]
not to mention that I can't reproduce it

**Comment by a13ph** [comment]
I can. It fires up argument listener for me. `C-g 1234 C-g` in echo, for example. And it actually works as argument too `C-g 4k` moves four lines up.

**Comment by a13ph** [comment]
#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 05a40a2)
- Distribution: spacemacs
- Layers:
```elisp
(emacs-lisp)
```

**Comment by a13ph** [comment]
Actually! only in `SPC s p`, which actually runs grep for me... And `SPC g g` or other grep or ack ones work fine

**Comment by StreakyCobra** [comment]
I can reproduce something like this, but with a few additional conditions:

1. Open Spacemacs
2. Open a file in spacemacs source code, like `core-dotspacemacs.el`
3. `SPC s p` to initialize the search
4. Enter `dotsp` and **just before the result get colored**, press `C-g`
5. You are now either in the buffer with `helm-ag` open, or still in `helm-ag` but as a normal buffer.

It is possible you have to repeat this several time, because it seems you have to press `C-g` at a precise timing.

I don't know if it is really related to original issue, but in all other case I can't reproduce the issue.

**Comment by synic** [comment]
I can't reproduce this anymore.

**Comment by S-X-ShaX** [comment]
I have this issue as well,when I pressed C-x C-f or M-x,helm display a list in the minibuffer,but press C-g it just show Quit and it's still there(not clean and cursor is also in minibuffer),I must press C-g twice to close it.
