### ISSUE TITLE
Flycheck error display error: (void-function x-display-pixel-width)

### ISSUE THREAD

**Issue by Xuyuanp** [syl20bnr/spacemacs#3897]
This message appeared when I put the course on the highlight warning line.

Here is my user-config:

```lisp
  (setq-default tab-width 4)
  (global-hl-line-highlight)
  (global-linum-mode)

  (setq-default dotspacemacs-configuration-layers '(go))

  (setq-default dotspacemacs-configuration-layers '(python))

  (setq-default dotspacemacs-configuration-layers
                  '((haskell :variables haskell-enable-ghc-mod-support t)))

  (setq-default dotspacemacs-configuration-layers
                '(auto-completion :variables
                                  auto-completion-enable-help-tooltip t
                                  auto-completion-enable-snippets-in-popup t))

  (setq-default dotspacemacs-configuration-layers '(osx))
```

Do you need any more info?

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.104.4
- Spacemacs branch: master (rev. f04bb61)
- Distribution: spacemacs
- Layers:
```elisp
(osx)
```

**Comment by TheBB** [comment]
I don't know about the actual error, but that code is not right. There is already a place in `dotspacemacs/layers` right at the top of your dotfile where you are supposed to put your layers.

**Comment by nixmaniack** [comment]
As @TheBB said, config isn't correctly set. But as for the actual error I had it on my remote machine where I use emacs only in terminal. I had to set following to get around it instead of using pos-tip to show the error which spacemacs sets explicitly. 

`(setq flycheck-display-errors-function 'flycheck-display-error-messages-unless-error-list)`

I think there's bug in pos-tip where it's not correctly detecting x window system vs plain terminal. Should be reported upstream.

**Comment by Xuyuanp** [comment]
I'm new to emacs from vim.

@nixmaniack , It works as you did, thank you!
