### ISSUE TITLE
Add beginner information on typical github workflow

### ISSUE THREAD

**Issue by StreakyCobra** [syl20bnr/spacemacs#3898]
We should add a section in the wiki explaining the typical github workflow for beginners.

@nixmaniack suggests also to add the video from @travisbhartwell for creating a PR for spacemacs.

This could be used as a base, but should be reworded/improved and commands added:

***

This is *one* typical workflow:

1. You fork Spacemacs.
2. You clone your fork of spacemacs to `.emacs.d`
3. You add the original repo as a remote: `git remote add upstream https://…`
4. You never, ever, do modifications on original branches, i.e. `master` and `develop`. This allows you to easily get the changes made to the original repository back to your, by simply `git pull --rebase upstream/develop`. Once pulled from upstream, you can push changes to your fork. All this will keep it up to date with the original one. You can do the same for `master` also.
5. When you want to work on features, you create a new branch by A) getting on develop `git co develop`; and B) create a branch `git checkout -b BRANCHNAME`.
6. Do you modifications on this BRANCHNAME, push it to your fork, go in github and create the pull request.

All this allows you to test your changes by simply running emacs when your `BRANCHNAME` is the active branch, and switching to `develop` to be again on official changes.

**Comment by travisbhartwell** [comment]
My video is found at https://www.youtube.com/watch?v=pWzJ6IGXwmk, and an associated blog entry is at http://iam.travishartwell.net/2015/07/29/how-to-make-a-pr-for-spacemacs/.  Perhaps the text of that blog entry could be adapted for the documentation?

**Comment by StreakyCobra** [comment]
Yes, would be nice to have an explanation with both `magit` and the equivalent command line way of doing it :-)

**Comment by travisbhartwell** [comment]
I could do this, but I also give permission to anyone else looking for a beginner friendly (and non-coding) issue to adapt the text of my blog entry as necessary.  If @syl20bnr and the Spacemacs devs don't mind, I would appreciate a link back to my blog and/or video in the docs, but otherwise my text could be used as a basis for this (no sense in reinventing the wheel).

Additionally, as @StreakyCobra mentioned on Gitter:

> From my point of view at least. Plus maybe a little short summary like shown in the original comment, for having a global overview of the steps.

**Comment by StreakyCobra** [comment]
Of course we will link you blog/video back :-)

**Comment by travisbhartwell** [comment]
Also, the Markdown source for that entry is here: https://github.com/travisbhartwell/iamtravis-blog/blob/master/_posts/2015-07-29-how-to-make-a-pr-for-spacemacs.md

It's probably easier to convert from that to the org mode format documentation than copying and pasting from my blog directly.

**Comment by travisbhartwell** [comment]
One thing that I didn't call out in my documentation or video is that as you need to make changes to your Pull Request to respond to feedback, you don't have to open a new pull request.  You can simply push to the existing branch you made the pull request with.  Pointing out that this would be an appropriate time to use amended commits and `git push -f` to make the commit history clean would also be useful.

**Comment by balajisivaraman** [comment]
I've added a [wiki page](https://github.com/syl20bnr/spacemacs/wiki/Beginner's-Guide-to-Contributing-a-Pull-Request-to-Spacemacs) that should allow us to close this issue.

My sincere apologies to @travisbhartwell for making changes to his post. They mostly revolve around using `origin` and `upstream` to refer to the fork and upstream instead of `origin` and `mine`, which can be confusing. I have also added CLI commands for all the steps and fixed any out-dated `magit` commands that might have been referenced. In addition, I have also added instructions on how to update the PR with maintainer feedback.

**Comment by robbyoconnor** [comment]
@balajisivaraman is amazing. Now if only people read this...odds are they won't.

**Comment by travisbhartwell** [comment]
@balajisivaraman No need to apologize!  My post was by no means perfect, I just offered as a base that someone could start from.  Looks like you've done a great job with that.

`origin` and `upstream` are probably more clear.

Just glancing over it, this looks great!

**Comment by StreakyCobra** [comment]
@balajisivaraman Very nice, thanks! I'll look later this week for adding a link to the contributing guide, and also maybe some links to it in the wiki.

**Comment by StreakyCobra** [comment]
#4831 will fix this issue

**Comment by d12frosted** [comment]
Already in [master](https://github.com/syl20bnr/spacemacs/commits/master/CONTRIBUTING.org), so closing this.
