### ISSUE TITLE
Missing `SPC` binding in several modes

### ISSUE THREAD

**Issue by StreakyCobra** [syl20bnr/spacemacs#3981]
With the new `bind-key` transition, it seems that several modes have lost their `SPC` key binding:

- `rspec-mode` compilation window  [Gitter – November 28, 2015 4:04 PM](https://gitter.im/syl20bnr/spacemacs?at=5659c28c7b1084ab21a51305)
-  `speedbar-mode` #3980
-  `ranger-mode` #3926
-  `python-nose` #3940
- And maybe even terminals #3927

**Comment by justbur** [comment]
I'll explain more later but the leader key is in the global evil maps. It's possible for minor modes to override these. you can rebind or unbind the shadowing key.

**Comment by autosquid** [comment]
and in c++ compilation mode.

**Comment by justbur** [comment]
evil-leader used local state maps for its bindings. bind-map uses the regular global maps, hence the small number of differences. Using local maps for what are essentially global bindings is a hack I think. Evil rightfully allows minor modes to override the global state maps which is what is happening here. 

My preference would be to explicitly rebind in these cases because i think it more closely matches the intended design of evil mode. I can also make an option for bind-map to use the local maps like evil-leader if that's what people want.

**Comment by justbur** [comment]
@StreakyCobra this should be closed I think, since it doesn't affect master

**Comment by PierreR** [comment]
This is not fixed in `Puppetfile` mode.

**Comment by justbur** [comment]
@PierreR I took a look at puppetfile mode and it's defined in a somewhat non-standard way. I don't think the correct hooks are being run for it. We'll probably need to do something like this for it
```elisp
(add-hook 'puppetfile-mode-hook
          (lambda ()
            (dolist (map (list evil-normal-state-local-map
                               evil-visual-state-local-map
                               evil-motion-state-local-map))
              (define-key map (kbd dotspacemacs-leader-key) 'spacemacs-cmds))))
```

**Comment by justbur** [comment]
Actually, I have another idea that might work through `bind-map` let me update it.

**Comment by justbur** [comment]
I think the puppetfile issue will be fixed after updating to https://github.com/justbur/emacs-bind-map/commit/e239bbdaefa17f7057ae97cb844e3e2ab0ce57bc
