### ISSUE TITLE
term or ansi-term cannot press TAB for shell auto-completion.

### ISSUE THREAD

**Issue by jezenielzapanta** [syl20bnr/spacemacs#399]
It seems like when I press <TAB> from `ansi-term` and `term` buffers. The minibuffer echos `Wrong type argument: characterp, tab`. Is this a natural response?

**Comment by syl20bnr** [comment]
Nope this is not expected.

**Comment by jezenielzapanta** [comment]
Thanks for the quick reply. I love spacemacs. :+1:

**Comment by PythonNut** [comment]
I think this should fix it:
```emacs
(defun force-yasnippet-off ()
  (yas-minor-mode -1)
  (setq yas-dont-activate t))

(add-hook 'term-mode-hook #'force-yasnippet-off)
(add-hook 'shell-mode-hook #'force-yasnippet-off)
```

**Comment by jezenielzapanta** [comment]
@PythonNut thanks. how did you know that yasnippet caused the problem?

**Comment by PythonNut** [comment]
@jezenielzapanta I too have a pretty overdone config. When I first began using `yasnippet` I noticed the problem a few days later and bisected my config... turns out it was `yasnippets` fault after all. I'm pretty sure it has to do with `yasnippet` binding the `yas-expand-from-trigger-key` command to `<tab>` everywhere. Normally, this command is pretty safe and contains a lot of workarounds, but it doesn't have a workaround for `ansi-term`.

**Comment by jezenielzapanta** [comment]
@PythonNut maybe we should raise this to the yasnippet repo?

**Comment by PythonNut** [comment]
@jezenielzapanta see [capitaomorte/**yasnippet** #289](https://github.com/capitaomorte/yasnippet/issues/289).

**Comment by syl20bnr** [comment]
@jezenielzapanta @PythonNut PR welcome! Add it to the `:init` property of `yasnippet` init function: https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L2126

**Comment by PythonNut** [comment]
I'll get around to it!

**Comment by syl20bnr** [comment]
:+1:

**Comment by jezenielzapanta** [comment]
This can be closed now. :+1: but i think we can remove this piece of code when yasnippet fixed it on their side.
