### ISSUE TITLE
the slurp work incorrectly.

### ISSUE THREAD

**Issue by JaydenFish** [syl20bnr/spacemacs#3997]
SPC k s work incorrectly.
like this:
a = dict[2]
a= di()ct[[2]
a=di(ct)[2]
a=di(ct [2])

There is a needless space between 'ct [2]'.
Could you please repair this mistake?

**Comment by syl20bnr** [comment]
Since you are not in a lisp dialect, can you try the hybrid version ``SPC k ` s`` (this is a backtick) ?

**Comment by asdyjd** [comment]
This one is also incorrectly.
I want to use this function in C++ and python.
It's very useful.
Could please repair this mistake?

**Comment by StreakyCobra** [comment]
> [...]
> Could please repair this mistake?

----

> [...]
> Could please repair this mistake?

----

This is probably not a mistake as `SPC k` is made for the **lisp** language, not Python, so it's **at most** an enhancement or a feature request, not a mistake. Also if you want to see it corrected the soonest as possible, code contribution are always welcome https://github.com/syl20bnr/evil-lisp-state

**Comment by TheBB** [comment]
I get the expected behaviour by using `sp-slurp-hybrid-sexp` on SPC k ` s ` s ` s...

```
a = dict[2]
()a = dict[2]
(a) = dict[2]
(a = dict)[2]
(a = dict[2])
```

Note that you can't do SPC k ` s s s s... as that will call the hybrid function first and the regular one after that.

It sure would be nice if evil-lisp-state could "promote" the hybrid commands somehow in non-lisp modes so I didn't have to go to the backtick every time. Or perhaps enter an evil-hybrid-lisp-state on SPC k ` so I only had to use it the first time.

**Comment by syl20bnr** [comment]
> It sure would be nice if evil-lisp-state could "promote" the hybrid commands somehow in non-lisp modes so I didn't have to go to the backtick every time. Or perhaps enter an evil-hybrid-lisp-state on SPC k ` so I only had to use it the first time.

Would be nice indeed.
