### ISSUE TITLE
org-cycle problem in evil normal state

### ISSUE THREAD

**Issue by dingmingxin** [syl20bnr/spacemacs#4024]
Here are the layers that I loaded.
```Lisp
dotspacemacs-configuration-layers
'(
     better-defaults
     emacs-lisp
     git
     markdown
     org
  )
```
When I start emacs in OSX Terminal.app , opening a org file. Hitting TAB key in the keyboard did not trigger function:
```lisp
org-cycle
```

By describe-function org-cycle, I got:
```lisp
It is bound to <mouse-1>, <normal-state> <tab>, <tab> .....
```
I have nothing special settings in my Terminal.app. And Tab behavior is normal in "Gnu Emacs for OSX"(GUI mode).

spacemacs version: 0.104.6
emacs version: 25.1
osx: 10.11.1

How can I solve this problem .Can anyone help me out ?  Much appreciations.

**Comment by StreakyCobra** [comment]
It's probably another variant of #3472. The `<tab>` keycode is only understood by the GUI version of emacs, and the `TAB` keycode is understood by both Terminal and GUI versions of emacs. There is two of them because, for historic reasons, `TAB` and `C-i` are the same keycode. So to have the possibility to differentiate <kbd>Tab</kbd> from <kbd>C-i</kbd> in GUI, the `<tab>` keycode is used.

- `<tab>` = <kbd>Tab</kbd> (GUI only)
- `TAB` = `C-i` = <kbd>C-i</kbd> = <kbd>Tab</kbd> (Terminal, or GUI if `<tab>` is not set)

There are people wanting to use `TAB` everywhere, like you, to have the same behaviour in Terminal and in GUI. There are others people, like in the linked issue, that want to use `<tab>` everywhere to have the possibility to differentiate Tab key from C-i in GUI, but breaking terminals.

@justbur found a clean way to satisfy everybody and this will probably be soon in `develop` (and later in `master`). This is truly awesome, because it will even work on demonized emacs :-)

**Comment by dingmingxin** [comment]
Thanks for replying in time.
But in which way can I configure emacs, making TAB act as `org-cycle` in org mode ?
I have tried this in `~/.spacemacs.d/init.el`
```lisp
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
  This function is called at the very end of Spacemacs initialization after
  layers configuration. You are free to put any user code."
  (define-key evil-normal-state-map (kbd "TAB") 'org-cycle)
  )
```
But it did not work as I expected.

**Comment by syl20bnr** [comment]
This is a temporary regression in develop, we will fix it soon, sorry for this.

**Comment by justbur** [comment]
@dingmingxin like this in user-config

```elisp
(evil-define-key 'normal evil-jumper-mode-map (kbd "TAB") nil)
```

**Comment by dingmingxin** [comment]
@syl20bnr  Thanks for your awesome work.
@justbur  Just tested:
```lisp
  (evil-define-key 'normal evil-jumper-mode-map (kbd "TAB") nil)
```
This works for me . Thank you very much.

**Comment by StreakyCobra** [comment]
Related PRs: #4025, #3999

**Comment by vitiral** [comment]
Just want to mention that this is still broken for me in mainline.

@justbur is there a way to do it so that that only takes effect for org mode? Something like `(evil-define-key-mode 'org-mode ... et`
