### ISSUE TITLE
mu4e composing mode evilification

### ISSUE THREAD

**Issue by kshmelkov** [syl20bnr/spacemacs#4070]
I have just tried mu4e layer from develop branch. I liked it a lot, but it seems that keybindings in composing mode are still default i.e. non-evilified (`C-c C-s` is send for example). I noticed that `SPC m` bindings are completely missed.

I am a recent vim convert so my elisp experience is around zero. Can you point me to some docs how to remap keybindings in spacemacs way?

**Comment by darkfeline** [comment]
The composing mode is derived from Emacs's native `message-mode`, so I'm not sure if this should be fixed in the `mu4e` layer.

The default send keybinding is `C-c C-c`, which is also used in a lot of other places both in Emacs and Spacemacs.

As a new Vim convert, it is useful to know that it is quite common for Emacs (and Spacemacs) to use `C-c C-c` and `C-c C-k` for "commit" and "cancel", respectively.  For example, writing git commit messages using Magit, writing emails using mu4e (or `message-mode`), and writing notes in Org mode.

I don't think Spacemacs has a convention currently to rebind them to any leader bindings (`SPC` bindings), but I think that would be worthy to add and implement.  Perhaps `SPC m c` and `SPC m k`?

> I noticed that `SPC m` bindings are completely missed.

`SPC m` bindings are specific to each mode, so in this case, it isn't that the bindings were "missed" so much as no specific bindings were assigned to that mode.

The composing mode should still be "evilified" though.  Are the Vim keybindings not working for you in that mode?

**Comment by justbur** [comment]
@StreakyCobra @syl20bnr let's come up with a convention for C-c C-c and C-c C-k. I think the suggestion here makes sense but it would be nice if there was an official convention

**Comment by kshmelkov** [comment]
Thank you for such a quick answer. I know about emacs `C-c` convention, but find it too difficult for pinky. For example, in org-mode notes `,,` works as confirmation and I find it very handy. For `C-c C-k` I can suggest `, ESC` if it fits spacemacs conventions.

Can anybody orient me to an example of such remapping? I know I could find it somewhere in org-mode sources, but I hope there is a smaller package with similar remappings.

**Comment by StreakyCobra** [comment]
@darkfeline I'm working on it in #3872 to provides `SPC` bindings. It's more general, but will provide `SPC . .` for `C-c C-c` and `SPC . k` for `C-c C-k`. It's just a proposal now, it may be better to have these on some other prefixes.

**Comment by justbur** [comment]
Hmm I like `,,` but not the second one. I'm thinking of `,q` or `,k`

**Comment by StreakyCobra** [comment]
@justbur In `git` layer we bind `,a` and `,c` as I just saw.

**Comment by justbur** [comment]
That was me :-) but now I like `,,`

**Comment by darkfeline** [comment]
I'm not sure about `SPC .` as a prefix, since there is a de facto convention of using `.` to enter microstates, for example `SPC w .`.

Keep in mind that `,` is actually `SPC m`, so `,,` is actually `SPC m ,`, and the user is free to bind the `SPC m` shortcut to whatever they want.  If they bind it to, say, `` ` ``, then the key binding `` ` ,`` is not quite as memorable.

**Comment by TheBB** [comment]
@darkfeline In org we use `,,` for `org-ctrl-c-ctrl-c`. It's bound as a double tap of the major mode leader key, not literally as `SPC m ,`.

**Comment by justbur** [comment]
Regardless we need a convention across modes.

**Comment by StreakyCobra** [comment]
Yep, but do we bind this to `SPC m` as a major-mode binding, or somewhere else as a global binding?

**Comment by darkfeline** [comment]
I still prefer using `c` and `k` since it's intuitive to native Emacs users, they aren't hard to hit, and they're mnemonic, sort of (commit, kill).  But `,,` works too, we just need a convention since Org and Magit are apparently on two different pages here.

:+1:  `SPC m`, since these are pretty mode specific commands.

**Comment by StreakyCobra** [comment]
Draft of convention in #4071

**Comment by fandag** [comment]
Regarding the original question on key bindings in the mu4e layer, should we add something like

    (spacemacs/set-leader-keys-for-major-mode 'mu4e-compose-mode
      (if dotspacemacs-major-mode-leader-key
          dotspacemacs-major-mode-leader-key
        ",") 'message-send-and-exit
        "a" 'message-kill-buffer
        "c" 'message-send-and-exit
        "k" 'message-kill-buffer)

to the mu4e layer or is it better to add it directly to the native `'message-mode` in Emacs? (and is the above code the preferred way to bind keys now? I didn't follow the recent changes to key binding closely...)

**Comment by darkfeline** [comment]
`message-mode`, I think Gnus uses it too since it is Emacs's mode for composing emails, not exclusive to mu4e.
