### ISSUE TITLE
t in post-command-hook

### ISSUE THREAD

**Issue by jschaf** [syl20bnr/spacemacs#4175]
There is a lone `t` in `post-command-hook`

I'm on develop and all my packages are upgraded.  I commented out my spacemacs.
## Steps to reproduce
1. Run emacs
2. Switch to scratch buffer
3. Eval "post-command-hook" with type <kbd>M-: post-command-hook</kbd>
4. Observe `(evil-normal-post-command t)`

The `t` occurs in the local post-command-hook, it's not present in the global value.

`emacs -q` doesn't have a `t` in the post-command-hook.

I found this because for some reasons, a `t` in the post-command-hook seems to close `pos-tip` tooltips.

All the post-command-hooks in spacemacs look normal.  I checked all the elpa packages and they also look normal.  So, I'm not sure what's going on.

**Comment by Miciah** [comment]
`t` has a special and desired meaning in `post-command-hook`; to quote [the Running Hooks section in the Emacs Lisp manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Running-Hooks.html), "If the hook variable is buffer-local, the buffer-local variable will be used instead of the global variable. However, if the buffer-local variable contains the element `t`, the global hook variable will be run as well." Evil in particular relies on the behavior described in the manual (cf. https://github.com/emacs-evil/evil/issues/19).

Do you still see the problem with `pos-tip`? Can you provide more details around that problem?

**Comment by jschaf** [comment]
I'm not on spacemacs any more.  I'll close as not reproducible.
