### ISSUE TITLE
Hihglight diffs on the fly with diff-hl-flydiff-mode

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#4355]
@syl20bnr @TheBB  @justbur Should we go back to `diff-hl` as main tool for highlighting diffs, since it got on-the-fly highlighting now? Maybe we can use both: `diff-hl` for highlighting changes, `git-gutter` for manipulating changes on buffer.

**Comment by StreakyCobra** [comment]
Ping @ralesi (as he worked on this in #3632)

**Comment by tuhdo** [comment]
I think the commit added a microstate for staging hunks and is independent of VCS tools for highlighting changes. What I am suggesting is making `diff-hl` the default highlighting tool, since it can highlight unsaved buffers. In other words, whenever you type something into current buffer, `diff-hl` highlights the changes immediately without having to save the file to refresh the buffer.

**Comment by StreakyCobra** [comment]
I know the PR is not really related, but I pinged him because he worked on the differences between the [highlighting libraries](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bsource-control/version-control#differences-between-margin-programs) for this, so he may have some opinions about this :-)

**Comment by ralesi** [comment]
The main reason I chose to move away from diff-hl and make it optional is that it is the only of the three supported tools that cannot stage hunks.  The other two tools also have options to update after a time period instead of after save also.   


Rich






On Sun, Jan 3, 2016 at 7:12 AM -0800, "Fabien Dubosson" <notifications@github.com> wrote:












I know the PR is not really related, but I pinged him because he worked on the differences between the highlighting libraries for this, so he may have some opinions about this :-)

**Comment by tuhdo** [comment]
@ralesi But not it can highlight on the fly, as you type, not after a period of time, not after saving; just right after you insert a character in current buffer, it highlights. Of the three, this is the only one that can do that. That's why I suggest to keep both `diff-hl` and `git-gutter` (I don't know the remaining one, but I guess it's `git-gutter+`?

**Comment by ralesi** [comment]
One option I guess is to write a function that temporarily turns on git-gutter mode and stages and then switches back,  this way we could use facilities in both tool simultaneously.  


Rich






On Sun, Jan 3, 2016 at 8:02 AM -0800, "Tu Do" <notifications@github.com> wrote:












@ralesi But not it can highlight on the fly, as you type, not after a period of time, not after saving; just right after you insert a character in current buffer, it highlights. Of the three, this is the only one that can do that. That's why I suggest to keep both diff-hl and git-gutter (I don't know the remaining one, but I guess it's git-gutter+?
