### ISSUE TITLE
Tips For Emacs Users Missing

### ISSUE THREAD

**Issue by mattharrison** [syl20bnr/spacemacs#437]
As a long time emacs user (no vim experience), I would like to try spacemacs, but woule appreciate some hints. The documentation hints that there are/were some hints at one point at this url...

https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#tips-for-emacs-users

**Comment by syl20bnr** [comment]
Oh it has been removed because it was only one tip for replacing the default evil state to emacs state. I decided to remove it because it is not a good advice.

There is now the Vim tutor adapted for evil. Install spacemacs then press `<SPC> h T` to open the evil-tutor. It is only about Vim though, the commands specific to spacemacs on the spacebar are not taught. 

But everytime you press `<SPC` you'll get a buffer on the right with the possible key strokes.
