### ISSUE TITLE
Error on emacs 24.3.1

### ISSUE THREAD

**Issue by michaelmior** [syl20bnr/spacemacs#4391]
I'm new to Spacemacs (and an emacs noob), but there seems to be an issue here for me. I get the following on first launch:

`An error occurred while installing helm-flx (error: (error Package `emacs-24.4' is unavailable))`

**Comment by StreakyCobra** [comment]
What's your emacs version?

**Comment by StreakyCobra** [comment]
Short answer: Update to emacs 24.5

Long answer: There are known bug with old versions of emacs, and nobody to take care of it as we are all using more recent versions. For know it's written emacs 24.3 is still supported but not fully featured, but it seems that it's not even the case.

CC @syl20bnr

**Comment by syl20bnr** [comment]
Too much packages require at least 24.4 nowadays, we will drop the support for 24.3 in 0.106.0.
Currently 24.3 is supported only minus some local errors which prevent users from being able to use some packages like Magit (which is problematic since it is an important package, this is why we decided to drop 24.3 a follow the stream).
