### ISSUE TITLE
An error about yas

### ISSUE THREAD

**Issue by fenxian** [syl20bnr/spacemacs#4457]
![screenshot from 2016-01-06 23 40 19](https://cloud.githubusercontent.com/assets/5669903/12146622/9512ae3e-b4cf-11e5-9f64-0813f2f507a2.png)

![screenshot from 2016-01-06 23 42 05](https://cloud.githubusercontent.com/assets/5669903/12146623/95617226-b4cf-11e5-8ae2-668caf718068.png)

In above image, i show an error tip "[yas] check your 'yas-snippet-dirs' : ~/.emacs.d/snippets is not a directory". This issue can be solved after creating this folder. However, I find the same folder in "layer/auto-completion/snippets". So, I think this may be an error?

The other image come from my .spacemacs file.

**Comment by TheBB** [comment]
That's a path included by yasnippet. Maybe it'd be good to remove it? We have another private snippet directory, so nothing is really lost.

@syl20bnr what do you think?

**Comment by TheBB** [comment]
Anyway this is just a warning, so no need to worry about it. See #4458 for a fix.

**Comment by fenxian** [comment]
I fix it follow the #4458. It works ok!

**Comment by syl20bnr** [comment]
Should be fixed in 0.105.4

**Comment by xiangsheng** [comment]
When I try to install the all-the-icons package (i.e. including the package name into the additional-packages list) and restart, I find a similar error about yas. The different is about the directory location, more precisely, the error is that "~/emacs.d/elpa/yasnippet-20180204.1613/snippets" is not a directory. The error is gone when I create this directory.

**Comment by radoslawg** [comment]
I have this issue in 0.200.13.x when switching to python buffer:

`[yas] Check your `yas-snippet-dirs': p:/home/.emacs.d/elpa/yasnippet-20180319.607/snippets is not a directory
[yas] Prepared just-in-time loading of snippets with some errors.  Check *Messages*.`

asking emacs to `describe-variable`gives
`yas-snippet-dirs is a variable defined in ‘yasnippet.el’.
Its value is
("p:/home/.emacs.d/private/snippets/" yas-installed-snippets-dir "p:/home/.emacs.d/layers/+completion/auto-completion/local/snippets")

Original value was 
("p:/home/.emacs.d/snippets")`

going deeper

`yas-installed-snippets-dir is a variable defined in ‘yasnippet.el’.
Its value is
"p:/home/.emacs.d/elpa/yasnippet-20180319.607/snippets"

  This variable is obsolete since 0.13;
  Yasnippet no longer comes with installed snippets
  This variable may be risky if used as a file-local variable.`

**Comment by radoslawg** [comment]
because apparently `yas-installed-snippets-dir` is obsolete removing lines

```        
;; ~/.emacs.d/elpa/yasnippet-xxxxx/snippets
(push 'yas-installed-snippets-dir yas-snippet-dirs)
```
from `~\.emacs.d\layers\+completion\auto-completion\packages.el` fixes this warning for me.
should i perhaps post new issue for this?
