### ISSUE TITLE
Some bugs or questions about C-C++ layer

### ISSUE THREAD

**Issue by jcppython** [syl20bnr/spacemacs#4493]
Here is my configuration
![screenshot from 2016-01-08 18 26 36](https://cloud.githubusercontent.com/assets/5669903/12195856/676b8bc4-b635-11e5-8007-9f63e0b5d68f.png)

emacs-version
GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8) 
1. The "SPC m" is undefined when I open a C/C++ header file. 
   In addition, the illustration of “Key Bindings” part has some wrongs in C-C++.
   https://github.com/fenxian/spacemacs/blob/master/layers/+lang/c-c++/README.org
2. It can't find the C++ headers. 
   ![screenshot from 2016-01-08 18 34 39](https://cloud.githubusercontent.com/assets/5669903/12196043/9c119444-b636-11e5-93a3-81727f22a8cc.png)
   I need to configure it?
3. An unfriendly tip as shown in following:
   ![screenshot from 2016-01-08 18 31 51](https://cloud.githubusercontent.com/assets/5669903/12195989/5c235264-b636-11e5-89d7-b042dda4bd42.png)
   
   And, the code is right. In other words, this tip shouldn't exist in here.
   In addition, how to open a header file? command or key binding?
4. Can you give me more information about how to scan a big C/C++ project with spacemacs?
   For  example, how to configure it for my project? 
   How to jump to the definition of references?

Thank you~

**Comment by tuhdo** [comment]
1. It's strange. If you enabled `semantic` layer, at least `SPC m r` should be available to access `srefactor`'s menu.

2. For C++ header files, you must add your C++ header paths to the variable `company-c-headers-path-system` for it to complete. Something like this:

```elisp
(add-to-list 'company-c-headers-path-system "/usr/include/c++/4.8/" )
```

Because it's is system-specific, we cannot preconfigured it.

3. As for the error message, probably it cannot find the header file. You might try adding project include paths for your C++ using the variable `flycheck-clang-include-path`.

4. To jump around C++ source code, you can either use the `gtags` layer (after adding the layer, some `SPC m` key bindings for `gtags` should be available. Use the command `helm-gtags-create-tags` to generate a tag database at your project root. Then, you will be able to jump to definitions and find references.

**Comment by fenxian** [comment]
1. 
![screenshot from 2016-01-08 19 58 00](https://cloud.githubusercontent.com/assets/5669903/12197464/2601dc58-b642-11e5-94fb-380b643e910b.png)

![screenshot from 2016-01-08 20 00 52](https://cloud.githubusercontent.com/assets/5669903/12197513/8e8d09c8-b642-11e5-806d-8541a2ae7127.png)


Sorry, `SPC m` is undefined occuring some times. This situation is incidental...
You can see that: I type `SPC m g c` to create gtags .. .
You can try to `SPC m` when you open a C/C++ file immediately after you start spacemacs.

2.  Where is better  place to add the following codes?  dotspacemacs/user-config () ? 
     ```    
      (add-to-list 'company-c-headers-path-system "/usr/include/c++/4.8/" )
     ```  
     May be we can add a variable to configure it when we enable C-C++ layer?

3.  What is different between `flycheck-clang-include-path` and `company-c-headers-path-system / company-c-headers-usr-system`?
     Do I should to add project include paths into `company-c-headers-usr-system`?

4. I have jump operations when `SPC m` is available. I have another question:
    Could we can create tha gtags file into another folder? Because the project belong to a big team sometimes. I can't to write files into the root of project at that time.

**Comment by TheBB** [comment]
Are your packages updated? How old is your `bind-map` package?

**Comment by fenxian** [comment]
elpa/bind-map-20151217.829/..

I think it should be the latest.  I install the spacemacs yesterday.

**Comment by TheBB** [comment]
Yeah ok, it's not that then. Can I try your dotfile?

**Comment by fenxian** [comment]
@TheBB dotfile refers to .spacemacs? A little change in this file.
[spacemacs.txt](https://github.com/syl20bnr/spacemacs/files/82707/spacemacs.txt)

**Comment by TheBB** [comment]
Okay, I tried with your dotfile (except I had to remove the chinese layer), and `SPC m` works fine for me in C++ mode.

**Comment by fenxian** [comment]
Yeah, It seems chinese layer leads to this issue.
Then, I will have to remove chinese layer? ...

**Comment by TheBB** [comment]
Really? It works without the chinese layer?

**Comment by fenxian** [comment]
Sorry, I try to operate it more times. The problem still exist after I comment `chinese layer`.
In addition, I find that `SPC m` can work after I have some other operations, for example, `gg` and `G`.

Can you give more methods to debug it?

**Comment by Voleking** [comment]
@jcppython I have the same issues with you. Have you fixed this problems?

**Comment by Voleking** [comment]
@TheBB Hi, I have the same issues that can't find the C++ headers.
Here is the problem that whether I set `c-c++-default-mode-for-headers 'c++-mode` or not company-c-headers find header files at `/usr/include`,  but should be at `/usr/include/c++/4.2.1`.What   should I set in my `.spacemacs`?

**Comment by beta1440** [comment]
@Voleking Do you have clang support enabled? If you do, create a `.clang_complete` file in the root of your project. Add the flag `-I/usr/include/c++/4.2.1` to the beginning of the `.clang_complete` file. Otherwise, try adding (add-to-list 'company-c-headers-path-system "/usr/include/c++/4.2.1") to your `.spacemacs`.

**Comment by syl20bnr** [comment]
May be fixed in develop after https://github.com/syl20bnr/spacemacs/pull/9381 is merged.
