### ISSUE TITLE
Is there a setting to disable the title bar chrome on Windows?

### ISSUE THREAD

**Issue by ashic** [syl20bnr/spacemacs#4510]
I can see that I can maximise without the chrome, but was wondering if it's possible to hide the title bar completely (as with the menu hidden, it's essentially dead space).

**Comment by StreakyCobra** [comment]
What is the *chrome* for you? The tittle bar is usually managed by the *window manager* (WM) — I hope it's also the case on *Microsoft Windows* though :wink: — so it's probably on the *Microsoft Windows* side you have to look.

**Comment by kRITZCREEK** [comment]
Did you try <f11>? It turns on "real" fullscreen

**Comment by kRITZCREEK** [comment]
... < f11 >

**Comment by ashic** [comment]
F11 works, but it's essentially a maximize. I was hoping to have no title bar while not maximised.

**Comment by syl20bnr** [comment]
I believe we have an option for this, let me try something on a windows box.

**Comment by syl20bnr** [comment]
Indeed we have it: set `dotspacemacs-fullscreen-at-startup` to `t`.

Maybe we should update the docstring to be more explicit about the removal of window decoration.

**Comment by syl20bnr** [comment]
But the taskbar disappear too... this is really a full fullscreen :-)

**Comment by StreakyCobra** [comment]
@syl20bnr I think he explicitly ask to remove the bar(chrome, or whatever) without maximizing. AFAIK this kind of tweaks could only be achieved on the OS/WM side.

**Comment by StreakyCobra** [comment]
@ashic So what you want to have is a Spacemacs window without the title frame when the windows is not maximized, right?

**Comment by ashic** [comment]
yup :)

**Comment by StreakyCobra** [comment]
@ashic Ok thanks. As I said this is most probably a tweak that can be achieved at the operating system level, because it's the window manager that is decorating the window. I looked a little bit and I haven't found any clue about this being possible from within emacs.

I'm afraid we can't do more on our side. I'm closing this issue then, but feel free to let us know if you get any information about this being possible, we will be happy to look at it :relaxed:

PS: I can point you [here](https://superuser.com/questions/38687/windows-program-to-remove-titlebar-frame-etc-from-a-window) as a starting point for solving your problem (especially the first two answers)
