### ISSUE TITLE
ESC in layouts microstate and Org agenda buffer

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#4562]
Exiting the layouts microstate (`SPC l`) using `ESC` while in the Org agenda buffer interprets the `ESC` as a regular Emacs `ESC` (as meta modifier).

I think it's because `ESC` isn't handled evilly in evilified state?  Would this be considered a bug or desired behavior of evilified state?
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.7
- Spacemacs branch: master (rev. 8a94bbf)
- Distribution: spacemacs
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t)
 better-defaults spell-checking syntax-checking semantic typography
 (chrome :variables edit-server-new-frame nil)
 dash elfeed erc finance gtags ibuffer mu4e org ranger
 (shell :variables shell-default-shell 'shell shell-default-term-shell "/usr/bin/zsh" shell-default-height 50)
 spacemacs-layouts version-control git github c-c++ clojure common-lisp emacs-lisp go html javascript latex lua markdown python ruby shell-scripts sql yaml evil-cleverparens mir-bbdb mir-magit-annex mir-pass mir-remind-to-diary mir-mpc)
```

**Comment by TheBB** [comment]
This is an intended feature of all microstates: any key that is not recognized by the microstate exits it, and then that key does whatever it's supposed to do elsewhere.

**Comment by syl20bnr** [comment]
> I think it's because ESC isn't handled evilly in evilified state? Would this be considered a bug or desired behavior of evilified state?

It is fixed for Magit buffer, maybe we could generalize this.

**Comment by syl20bnr** [comment]
@TheBB you are right but I guess the issue is not that it exit the micro-state but that ESC acts like Meta.

**Comment by darkfeline** [comment]
Alternatively, could the layouts microstate be bound to `SPC l .` like many of the other microstates and have `SPC l` be a prefix for the layout commands?  Having `SPC l` be a microstate and this current evilified behavior is doubly bad because one would do `SPC l o o` to switch to the Org layout and then either press `C-g` or (mistakenly) `ESC C-g` to exit the microstate.

In theory one could exit the microstate naturally without `ESC` but there's always the chance that the next key you press is actually bound in the microstate and performs undesired behavior, and tapping `ESC` a few times to return to a normalized state is natural Vim usage.

**Comment by StreakyCobra** [comment]
I agree that `SPC l` shouldn't be a microstate by default. It exits when a non-existing key is pressed, and `j/k` are not mapped, but in bepo these up/down keys are `t/s` and both are bound to something in spacemacs layout micro-state..

Having `SPC l .` for the microstate would be consistent with the other concepts. #4225 will hopefully allows to let people define which keybindings should enter the micro-state.

**Comment by syl20bnr** [comment]
I don't agree with removing the micro-state from `SPC l` but I agree we may have to tweak it (1) and I'm open to an experimentation (2).

(1) What you propose here is to set the `:persistent t` keyword and add `ESC :exit t` to the layout micro-state.

(2) The micro-state provides an important thing which is the list of layouts. As far as I know, out of the box we don't have an easy way to display some text in the minibuffer when pressing a command prefix, i.e. pressing `SPC l` display a nice list in the minibuffer (or even in the header). _BUT_ with @justbur knowledge about prefixes in `which-key` I am hopeful that we could provide such feature. So here is the picture:
- `SPC l` is a prefix not bound to a micro-state
- we have some package that allows to register functions to echo messages in the minibuffer or header when a given prefix is pressed, this package takes care of the dirty thing like hiding the echo of the current pressed keys and replace the minibuffer/header content with the result of the registered function
- pressing `SPC l 1` will then echo two messages:
  - `SPC l` display the list of layouts with the current one highlighted
  - `1` update the message with the new active layout (no need to use the package for 1 since it is directly bound to the switch function)
- With this design I can stop at `SPC l` a little bit before deciding where to go, or I can rush to `SPC l 1`
- Some sort of time out of the printed message would be cool

cc @justbur :-D

**Comment by syl20bnr** [comment]
Maybe it could be a feature provided by `which-key` because the function result should be concatenated with `which-key` messages. Or we only use the header.

**Comment by justbur** [comment]
I don't use layouts yet, so I'm not really familiar with the issue, but if you dynamically bound a key to a map under `SPC l` which-key would show the layouts in the popup. Highlighting the current layout would be slightly more work, but not hard.
