### ISSUE TITLE
auto-complete cannot work in xml 

### ISSUE THREAD

**Issue by fuzihaofzh** [syl20bnr/spacemacs#4705]
I add xml, auto-complete, company into dotspacemacs-configuration-layers. But I cannot get complete in spacemacs. How to solve this?

**Comment by StreakyCobra** [comment]
It would be nice if you can update your issue following the template and explanation [here](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) :-)

**Comment by maplewizard** [comment]
#### Description
In xml file, auto-complete, company cannot work.

#### Reproduction guide
- Start Emacs
- Open a xml file.

DESCRIPTION OF THE OBSERVED BEHAVIOUR
Type some thing, no hint appears.
DESCRIPTION OF THE EXPECTED BEHAVIOUR
Type some thing, some relevant hint appears.
#### System Info
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.8
- Spacemacs branch: master (rev. ef5a2ad)
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(osx python ipython c-c++ markdown spacemacs-base auto-completion better-defaults emacs-lisp git markd\
own org lua company xml spell-checking syntax-checking version-control)
```

#### Backtrace

**Comment by TheBB** [comment]
You have `xml` in your layers, but there's no layer called `xml`. There is one called `html`. Using it, I do get completion in XML files.

Although I should note that there's almost nothing to complete in XML.

**Comment by maplewizard** [comment]
Thanks, I want to complete those I have just typed before.

**Comment by TheBB** [comment]
There's no reason to add `spacemacs-base` to the list of layers either, if you are using the `spacemacs` distribution.

Also, there is no layer called `company`. Company is a package in the `auto-completion` layer.

Run `dotspacemacs/test-dotfile` to find errors like this.

**Comment by maplewizard** [comment]
@TheBB I added the html layer, but I still cannot get completion in xml file? Should I set something to bing xml file to html layer?

**Comment by TheBB** [comment]
Well, you have to change which backends you use then, I guess. See the `company-backends` variable.

**Comment by TheBB** [comment]
I'm not sure but I think you want `company-dabbrev` in the front list.
