### ISSUE TITLE
Theme toggle broken

### ISSUE THREAD

**Issue by stormpat** [syl20bnr/spacemacs#472]
When changing themes, the ```SPC T n``` is broken. Obviously this is not a big deal, you can toggle themes with ```SPC T h``` and choose from the list.

**Comment by syl20bnr** [comment]
Fixed in https://github.com/syl20bnr/spacemacs/commit/053b9b0e3e214bddb5bccf559cbd7984b7f2a399 in `develop` branch. Will be in next release which I will release soon.

As a bonus, the `.spacemacs` variable is now `dotspacemacs-themes` instead of `dotspacemacs-default-theme`. This is a list of themes and `<SPC> T n` will now cycle through this list instead of a predefined one.
