### ISSUE TITLE
How can I avoid jumping to the last editing position when undoing something?

### ISSUE THREAD

**Issue by 3rd3** [syl20bnr/spacemacs#4783]
When I press undo, Spacemacs does not just undo but it also jumps to the last position where I've edited something. Most of the time this is not what I want, because I want to continue editing at the position where I'm doing the undo. I could not find any setting in my configuration which might cause this behavior.

**Comment by TheBB** [comment]
Why would something cause this behaviour? Isn't this the expected behaviour pretty much everywhere? I would rather look for something that could change the behaviour *away* from the default.

What comes to mind is for you to write a new function for undo (whichever undo function you like to use), which calls the original inside a `save-excursion` block.

**Comment by TheBB** [comment]
This works for me.

```lisp
(defun bb/save-ex-call (orig-fun &rest args)
  (save-excursion
    (apply orig-fun args)))

(advice-add 'undo-tree-undo :around 'bb/save-ex-call)
```

**Comment by 3rd3** [comment]
Just to be clarify what happens:

State 1:

   writing somethin▊
   some text
   

A little pause, then state 2:

   writing something
   some text
   writing some more▊

When I then press `U`, this happens:

   writing something▊
   some text
   

But I want this to happen:

   writing something
   some text
   ▊

**Comment by TheBB** [comment]
Uh, I already have the behaviour you want. Maybe you can check the setting of your `evil-want-fine-undo`?

**Comment by 3rd3** [comment]
That's it, thanks!
