### ISSUE TITLE
Is it possible to use which-key for any key?

### ISSUE THREAD

**Issue by user471** [syl20bnr/spacemacs#4800]
For example you could press `v` and emacs would show the keys similar to when you press `yi`.

**Comment by robbyoconnor** [comment]
Uh -- this works -- `v` throws you into `visual-state` then the rest works... Did you try this?

**Comment by nixmaniack** [comment]
Since `v` is a complete key sequence you don't get `which-key` pop up. Once you're in visual state with `v`, you activate another set of keys. Here if you type `i` which isn't a complete key sequence(Prefix command)  `which-key` pops up.

In this particular case, you can do `SPC h d K` to describe `evil-visual-state-map` to see what bindings are available. Although I'm not sure how to get those prefix commands description in that keymap description. 

Also `which-key` added support for evil operators (which I think is enabled by default in spacemacs) by setting variable `which-key-allow-evil-operators`

This is all from my little knowledge and exploration. @justbur could explain more though. :smile:

**Comment by user471** [comment]
> Did you try this? 

Did I try what? I know `v` is visual-state. I want `which-key` to show me all available keys in visual state.

>Since v is a complete key sequence you don't get which-key pop up.

Why `v` is a complete key? It doesn't do anything by itself, you need to press something.
What about `y`? I don't think it's a complete key, but `which-key` doesn't work with it either.

>In this particular case, you can do SPC h d K to describe evil-visual-state-map

I would prefer `whick-key` over plain documentation

**Comment by robbyoconnor** [comment]
@user471 PRs welcome to `which-key` to fix it.

**Comment by StreakyCobra** [comment]
@user471 Pressing `v` enter the visual **state**, which is a state like, the normal state. When you are in normal state, you don't have a menu open all the time telling you that `j` is going to the next line, `k` to the previous line, and so one. It is the same for the insert state, same for the replace state. I don't get why the visual state would be different.

**Comment by robbyoconnor** [comment]
I'm trying to figure out why this is even being discussed....

**Comment by user471** [comment]
@StreakyCobra For normal and insert state it make sense, because you are in this states most of the time. What is wrong with showing what can you press for example after `y`?

**Comment by StreakyCobra** [comment]
I use the visual state quite often too. When you press `y` in the normal state the command is not complete and it shows you the possibilities to complete it. in visual state `y` copy directly what's selected, so there is nothing else to show. Or I didn't understood your question.

**Comment by user471** [comment]
>When you press y in the normal state the command is not complete and it shows you the possibilities to complete it

Hm, this doesn't work for me. `which-key` doesn't show up after I press `y`.

Spacemacs v.0.105.9

**Comment by StreakyCobra** [comment]
Oh, me neither actually, I assumed it did. Having this could be interesting for `y`. But not for `v`.

**Comment by user471** [comment]
>Having this could be interesting for y

Not only for `y` but for any key `p`, `q`, etc.

>But not for v.

It could be really useful for new users. But it should be possible to disable.
Maybe something like `(setq which-key-disable-evil-key '("v"))`

**Comment by robbyoconnor** [comment]
:+1: to what @StreakyCobra said

**Comment by StreakyCobra** [comment]
For `p` ? This just paste something, there is no keys to press afterward (except if you have `dotspacemacs-enable-paste-micro-state t` but this has to be activated in purpose and there is a help message at the bottom, so it's not even relevant in this case)

For `q` ?? After `q` you can use whatever letter you want to select a register, there is no need, nor sense, to show the alphabet in which-key.

All those bindings (`v`, `p`, `q`) are not Spacemacs' specific, they are basis concepts of the `vim` modal editing style. If people are not used to `vim` they should first learn the concepts (like with `SPC h T`) or use the emacs editing style.

The only one that *could* make sense for me is `y`.

**Comment by user471** [comment]
>For p 

I mean show keys after `"[a-z]`
>For q

Show available macros after @ and command @@

Also could be used for marks, `d` , `>`, `=`
>If people are not used to vim they should first learn the concepts (like with SPC h T)

The can learn but it doesn't mean they can remember everything, that is why `which-key` exists.

**Comment by robbyoconnor** [comment]
As we said -- Pull requests welcome but adding visual state is stupid as hell, really freaking stupid.

**Comment by user471** [comment]
>adding visual state is stupid as hell, really freaking stupid. 

I don't see anything stupid in helping people to learn.

**Comment by robbyoconnor** [comment]
Like I said, this is just two people's opinions. PRs welcome. Neither of us care enough to do it, or at least I don't.

**Comment by justbur** [comment]
@user471 open an issue at which-key. You can always use `SPC hk` or `SPC ?` to show bindings at the "top-level" this will give you the options after `v` but in a long list. 

The issue with `y` is that as far as Emacs is concerned it is a complete command. After `y`, evil "manually" reads the subsequent key strokes outside of the usual Emacs mechanism for doing this. That's why which-key is not displaying. I may be able to do something with `y`, which is why you should open the issue at which-key.

**Comment by user471** [comment]
> You can always use SPC hk or SPC ?

But could it help me find out about `@@` command?

**Comment by justbur** [comment]
@user471 I don't think so. I can't do everything with which-key...
