### ISSUE TITLE
Projectile rails doesn't work

### ISSUE THREAD

**Issue by Eilie** [syl20bnr/spacemacs#4804]
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion git ruby-on-rails yaml syntax-checking
                 (ruby :variables ruby-version-manager 'rbenv))
```
#### Reproduction guide
- Open controller file in Rails project and press `SPC m r f`.
- You'll get `SPC m r f is undefined` error.

Issuing `M-x projectile-mode` or `M-x projectile-rails-mode` fixes the issue. In `M-x projectile-mode` case minibuffer says that projectile is disabled which is weird tho, looks like it doesn't matter which way you turn it.

**Comment by peterhoeg** [comment]
It's working fine here and I see ```projectile``` in the list of enabled modes, so something is not triggering correctly for you. When projectile-mode is run and the ruby-on-rails layer included, the hook takes care of enabling projectile-rails-mode, so that explains why triggering either manually works.

The odd thing is, that projectile-mode is being switched on in ```core-spacemacs-buffer.el```. Are you sure there is no syntax error in some of your files that prevents spacemacs from initializing correctly?

**Comment by d12frosted** [comment]
I am not ror developer, so just throwing a question - does the problem persist with the latest Spacemacs with updated packages?

**Comment by asok** [comment]
I believe that might be conntected to: https://github.com/asok/projectile-rails/issues/105 the remedy is to update the packages and enable the global mode via `(projectile-rails-global-modes)`.
This PR fixes it: https://github.com/syl20bnr/spacemacs/pull/7541

**Comment by TheBB** [comment]
Shoud be fixed.
