### ISSUE TITLE
auto complete in C/C++ project is very slow 

### ISSUE THREAD

**Issue by chengyi** [syl20bnr/spacemacs#4818]
I use `company` in my C/C++ project, But the tips popup window shows very slow and sometimes doesn't show at all.
is it required some additional config?

**Comment by phinicota** [comment]
Same here. Haven't found a solution and stopped using auto-complete all together but I'd like to know if a solution exists.

**Comment by kzjeef** [comment]
Have same problem here too.

When I open more and more files in buffers, typing is too slow to typing.

**Comment by kzjeef** [comment]
I think i found the cause, 
after debugging company 's backend, I the lag is caused by company clang backend, 
which enabled by c-c++ layer. 

after disable c-lang support in that layer, the typing is very smooth now.

Hope this helpful, maybe it's should fire a bug to c-c++ layer's clang support.

btw, you can type 
`company-diag` to check the information about company backend.

**Comment by chengyi** [comment]
@kzjeef  In fact, you must pass the ccorrect compiler params through `.clang_complete` file.
so company will show correct tips with clang backend.

**Comment by deb0ch** [comment]
Now you can also use the ycmd layer as an alternative, which has the reputation of being much faster than company-clang, and is asynchronous.
