### ISSUE TITLE
Powerline Symbols Not Scaling with Font Size

### ISSUE THREAD

**Issue by GEverding** [syl20bnr/spacemacs#482]
I just started using emacs so this might be something I'm not doing but the symbols for powerline aren't scaling when I set the font size greater then 10pt. The symbols are centred and look like they are still  10pt font. Anyone know what's going on?

**Comment by syl20bnr** [comment]
This is a known issue. This is due to the fallback font used for the unicode characters in the mode-line. For now spacemacs does not explicitly define a fallback so an arbitrarily one is chosen, sometimes it is a ugly one with huge symbols like your.

To fix this issue I need several info:
- your OS
- your version of Emacs (the build you are using too)
- the fallback font chosen.

To retrieve the fallback font: Go to [the following line](https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L2137) and put the point (cursor) on the circle latin capital Y then enter `<SPC> : describe-char RET` and look for a font name.
On OS X mine is: `xft:-unknown-Apple SD Gothic Neo-normal-normal-normal-*-13-*-*-*-*-0-iso10646-1 (#x20DC)`

**Comment by GEverding** [comment]
I'm using ubuntu 14.04, emacs 24.3.1 and xft:-unknown-NanumGothic-normal-normal-normal-*-32-*-*-*-*-0-iso10646-1 (#x20DC) is the fallback font.

**Comment by syl20bnr** [comment]
Thank you, I have the same fallback font on Ubuntu 14.04 but the size is different.
`xft:-unknown-NanumGothic-normal-normal-normal-*-13-*-*-*-*-0-iso10646-1 (#x20DC)`

I'll have to look if I can force the size of this font.

**Comment by valrus** [comment]
I'm having this happen too. My powerline and mode-line faces all have height 90.

![screenshot 39](https://cloud.githubusercontent.com/assets/343665/5906213/be28ccc6-a54a-11e4-8c3f-c115dbf41e59.jpg)

**Comment by syl20bnr** [comment]
@GEverding if you remove your font related configuration in your dotfile and install `source code pro`. is it ok ?

**Comment by syl20bnr** [comment]
@GEverding @jmhammond Can you try the version 0.50.0 ? Be sure to have `Source Code Pro` installed. I will set better OS specific default font (that comes preinstalled) later during the week.
