### ISSUE TITLE
Org mode:link hava problem

### ISSUE THREAD

**Issue by 41890819** [syl20bnr/spacemacs#4858]
when the link in outline or in a table,it can't display correctly
![3333](https://cloud.githubusercontent.com/assets/12065353/12672421/19b1fc42-c6b1-11e5-962e-389a2a0d796b.png)
![5555](https://cloud.githubusercontent.com/assets/12065353/12672423/1c87012e-c6b1-11e5-9473-09dd16a2aea2.png)

**Comment by robbyoconnor** [comment]
@41890819, reload the file and it should show it

**Comment by 41890819** [comment]
＠robbyoconnor it does't work.if the link not in a outline or table,it will be right

**Comment by 41890819** [comment]
@robbyoconnor  it does't work.if the link not in a outline or table,it will be right

**Comment by robbyoconnor** [comment]
Please follow [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)

**Comment by StreakyCobra** [comment]
I don't think this is a Spacemacs issue. For me it is more how `org` behaves. It would be nice if someone can test it on a rew emacs install to confirm.

**Comment by thang1thang2** [comment]
#### Description
Links in org mode should be displayed as `link` rather than `[[url][link]]` but currently they're not.

#### Reproduction guide
- Start Emacs
- Be sure to use `vim` editing mode
- Open the `org agenda` file with `SPC a-o-a`
- Hit `RET` on a TODO to open the "real file" in a buffer.

I observe an output of:

```
* [[file+sys:~/Documents/Classes/CPTR/415][CPTR 415: Databases]]
    ** [[file:Classes/CPTR/415/syllabus.pdf][Syllabus]]
    ** TODO [[file+sys:Classes/CPTR/415/Homework/hw2.pdf][Homework 2]]
       DEADLINE: <2016-01-27 Wed>
    *** [[file:Classes/CPTR/415/Homework/HW2/homework2.tex][Assignment]]
    ** TODO [[file+sys:Classes/CPTR/415/Homework/project_1.pdf][Project 1]]
       DEADLINE: <2016-01-22 Fri>
```


I expect links of the format `[[url][tag]]` to display as `tag`.
I also expect <year-mo-da Nme> to be blue and clickable/otherwise interactive.
I can hit `RET` on the `[[url][tag]]` or `<year-mo-da Nme>` links and they'll work as expected; this seems to be purely a visual bug as far as functionality goes for me.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. 72e1413)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible
 (auto-completion :variables auto-completion-return-key-behavior 'nil auto-completion-tab-key-behavior 'complete auto-completion-enable-sort-by-usage t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 colors emacs-lisp extra-langs git github gtags
 (haskell :variables haskell-enable-hindent-style "chris-done")
 html
 (latex :variables latex-enable-auto-fill nil)
 markdown nixos org python
 (ranger :variables ranger-show-preview t)
 semantic
 (shell :variables shell-default-term-shell "/bin/zsh")
 spacemacs-helm spell-checking syntax-checking themes-megapack tmux version-control)
```

**Comment by StreakyCobra** [comment]
@thang1thang2 Thanks :+1: for this amazing report :100:

But I still don't know if it is an `org-mode` behavior or a Spacemacs issue.

**Comment by robbyoconnor** [comment]
Thank you!

**Comment by Andre0991** [comment]
I think this is the same problem of https://github.com/syl20bnr/spacemacs/issues/4793 .

**Comment by mskorzhinskiy** [comment]
I've experienced the same problem and can report that after today's update this problem is gone. At least from my installation.

**Comment by StreakyCobra** [comment]
@41890819 It is fine on your side also?

**Comment by 41890819** [comment]
@StreakyCobra i'm tring now.what i need to do is update the spacemacs and the packages?

**Comment by 41890819** [comment]
@StreakyCobra The problem is gone after i update the packages,thanks a lot!
