### ISSUE TITLE
How to cancel menu after pressing space without getting an error message?

### ISSUE THREAD

**Issue by amichail** [syl20bnr/spacemacs#4861]
Maybe this should be mentioned in the documentation?

**Comment by StreakyCobra** [comment]
@justbur Last time we discussed this you where saying the solution is to press a key that doesn't exist. Do we stick with this or do you want to offer another way to cancel a keypres *and* hide which-key?

PS: I know `C-h u` cancel the key but which-key stay open with toplevel.

**Comment by justbur** [comment]
There's C-h a or C-h C-a for abort, but I just quit with C-g which is the standard way to quit in emacs. It's not an error it's just telling you that the sequence is undefined which you knew already.

**Comment by amichail** [comment]
Why not use C-g to quit and print "quit" instead of something about the sequence being undefined?

**Comment by justbur** [comment]
Because which-key is not "reading" the key sequence. It's doing everything passively. The message that it's undefined is coming from emacs. I don't see the value in trying to intercept that.

**Comment by amichail** [comment]
The user doesn't care about implementation issues.

**Comment by justbur** [comment]
In that case I'd like you to write me a spellcheck package that doesn't suffer from the performance issues that flyspell has.

**Comment by bmag** [comment]
@amichail although it's not stated directly anywhere, the error message you refer to is "\<some key sequence ending in C-g\> is undefined". This is reproducible with bare emacs:
- start emacs: `emacs -Q`
- type `C-x C-g`

result: "C-x C-g is undefined" message in the echo area

If you think this is a bug, you can report it to Emacs itself with the command `report-emacs-bug`. I seriously doubt that the Emacs developers will consider this a bug, though, since this is standard Emacs behavior.

In any case, I see no point in keeping this issue open.

**Comment by TheBB** [comment]
:+1:
