### ISSUE TITLE
Add a new branch "nightly"("footgun" ?)

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#4890]
Given how long it takes for @syl20bnr  to personally verify every big PR and the rate with which the issue\PR heap grows, I think it might be the right time to add extra branch for the crazies and allow the elders to merge all kind of potentially broken PR's into the branch(probably out of sheer curiosity or sadistic pleasure - they deserve it!)

**This will serve as a "trial by fire" for the brave ones and will break or make elispers out of us :smiling_imp:** 

It will help in killing weak or malformed PR's in their cradles - the Spartan way! And syl20bnr will have less to worry about.

*Since the branch won't be representative of the Spacemacs'es quality standards. I propose special logo for the "footgun" release:*

![multiculturalism](https://upload.wikimedia.org/wikipedia/commons/a/af/Confusion_of_Tongues.png)

**Comment by robbyoconnor** [comment]
I too want to see the world burn. Let's do it!

**Comment by nixmaniack** [comment]
Just for the reference, discussion that happened in the past. https://github.com/syl20bnr/spacemacs/issues/3591

**Comment by JAremko** [comment]
It's hard to make something like a new layer or rework an old one without actual feedback  and making someone test your PR is even harder :cry:

@nixmaniack  Well... Thanks for killing the party :worried:

**Comment by nixmaniack** [comment]
@JAremko Sorry, but had to point so that you have context and know what happened in the past which enables you to come up with concrete and better reasons.

**Comment by JAremko** [comment]
@nixmaniack  Ya, thanks.  It's just like they say. Those who don't know history are doomed to repeat it. Or just be tagged as a duplicate. And since doing the same thing over and over again and expecting different results might be referred as insanity... I think we need new, stronger,better arguments.  Like

Pleeeez @TheBB Senpai  :kissing_cat:

**Comment by TheBB** [comment]
I've been meaning to speed up things on develop so that it can be the edgy slightly unstable branch that it's supposed to be, but lately I've just been short of time. Sorry. Sometimes merging PRs take time because I don't use the layers that they change, which makes it difficult to verify correctness. And I have to do *some* kind of review at the very least.

**Comment by TheBB** [comment]
I should add that I feel things have moved a lot quicker lately than when #3591 was under discussion, but I could be wrong about that.

**Comment by StreakyCobra** [comment]
I confirm we are going much more faster since #3591. Back in the time it was mainly @syl20bnr who was merging new features and he wasn't having a lot of time for this. Since then, @TheBB has started to merge a lot of PRs and now we are going a lot faster. I think it is even at the limit of what is manageable as volunteer work for us now. After a rough estimate, we have around 5 new PRs per days, that require careful reviews and a lot of knowledge to not screw other parts (I don't have enough experience to work on most of them because the code base is really complex). There is around 100 comments (random guess) every day that we should deal with, i.e. understanding, reproducing, answering, fixing, … Plus all the gitter provided help. We have more than 500 issues and 120 PRs that need help/review/testing.

The better way to get everything go faster is that all regular contributors start to help answering issues, try to reproduce them, identify bugs, make PRs for simple ones, etc… or to do code review on PRs, test them, report issues, etc...

**Comment by robbyoconnor** [comment]
What we need is more experts willing to dig into the core...if we find
those,  we'll move quick enough that this whole discussion is moot.

--Rob

**Comment by robbyoconnor** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Robert

Confirm that you know Robert: https://www.linkedin.com/e/v2?e=0-ini67o5n-bn&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=u4lK1inb&invitationId=6130896964075732992








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini67o5n-bn&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFbPi21lt5J9QAAAVRVSb0oYTf-UZ7_gMknP_qxyTQqaA_Du8NPa1uf9HllB_AO06dqTlvAKNTTXtyLUQ_hOZSMX8ZEdZx6mXAorAnjyEiR801ZuQMF5GH_Yx3IKgMLRwY4VVdR-VnL79KQ-DbLuttx7_NOVRL8nLd2l_qAHBju9km-QIgTiz4LTwyQ1cVMzR-r&eid=0-ini67o5n-bn


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini67o5n-bn&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
