### ISSUE TITLE
How to properly setup company-tern in JS mode?

### ISSUE THREAD

**Issue by domi91c** [syl20bnr/spacemacs#4903]
When in a Javascript file, hitting tab to complete uses basic auto-completion instead of `company-tern`. I can run the company-tern command by typing it in which gives me the company-tern completion popup, but I'm not sure how to activate it by hitting tab. I haven't customized the JS layer at all.

**Comment by izahn** [comment]
Getting tab to complete or indent depending on context is a mess in emacs. Some things depend on the value of `tab-always-indent`, other package implement their own hacks, and in general getting this to work consistently is very difficult. 

My advice (and what I do) is to forget about fighting over tab key completion, and just bind something else to `company-complete`. In my .spacemacs I have this: 
```
  (eval-after-load 'company
            (lambda()
              (global-set-key (kbd "S-SPC") 'company-complete)))
```
so I can complete with Shift-Space. 

Ultimately I think there should be a conventional key binding for this in spacemacs, but in the meantime just pick one you like.

You may also wish to set `tab-always-indent` to `nil` or `t`, since you have another key for completion. 

This is all just my opinion, there are other options including trying to beat the tab key into submission. I've tried that in the past and concluded it wasn't worth it, but your mileage may vary.

**Comment by portOdin** [comment]
Alright, I'll give that a try. I'm assuming having the company popup appear automatically would also be difficult?

**Comment by izahn** [comment]
The company popup should appear automatically after typing at least `company-minimum-prefix-length` characters. If that doesn't happen than either something is wrong or you've configured it not to complete automatically. Do you get company completion in other buffers (e.g. emacs lisp buffers)?

**Comment by portOdin** [comment]
Yah, it works perfectly in Lisp, even using tab. Actually, I was just trying again with Javascript and `company` works with tab, but it opens the `company-tern` `mini-buffer` instead of automatically opening the `company` popup while I'm typing. Not sure why tab wasn't working before. So now I just need to figure out why the mini buffer is triggered on tab instead of the autocomplete popup.

**Comment by andrew-kennedy** [comment]
Any progress here? I'm trying to figure out how to use company tern myself and am stuck.
