### ISSUE TITLE
Guidelines for user layer contributions

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#491]
I notice that there are not many user layer contributions in spacemacs.  I imagine most people keep the information in their own `.spacemacs` file.   I was thinking about porting the lot of stuff I have in their as a contribution layer, but wondered what guidelines we have for user layers. 

With most of the standard layers and language specific layers, I see a common convention with the bindings to get consistency across them.  Are we shooting for something like that in the user layers as well?

Specifically, I have bindings for dired and other vim related bindings that I had in my old vim config that I would like to share, as well as some ease of use functions and bindings that aren't centered around using `SPC` as a prefix.

**Comment by syl20bnr** [comment]
It's great you ask because I'm not sure I still want to merge user layers.

At the start I thought it will be really cool but it seems not very practical in the end and it may generate noise around the other contribution layers focused on spacemacs. Their integration with the whole spacemacs configuration is not guaranteed therefore their quality will vary. Instead of imposing guidelines for user layers I prefer people to create private layers and PR only the parts that are relevant for the spacemacs configuration.

My layer is now empty and I have my own private layer. The only user layer with contents is the one from @trishume which is indeed used by some people but we could move the remaining into a contrib.

I'm pretty sure I won't support them (user layers) in the future because of the aforementioned reasons.

But we will have other opportunities to be able to share user layers, for example layers could be fetched from other repos.

**Comment by trishume** [comment]
Agreed, now that we seem to be moving in the many small contrib layers direction user layers make less sense. Currently my layer contains 3 things, here's what they are and what I'll do with them:

1. Uncommon language modes. I'll split this out into a layer called `extra-langs`.
2. Hungry delete. Useful feature, will make a small layer for it.
3. Helm Ag. I think this duplicates functionality in core spacemacs but I have to check, might just remove.

**Comment by syl20bnr** [comment]
Cool, for the hungry delete case, maybe we can move it to spacemacs and define a dotspacemacs variable to enable it. Or even better if we can find an appropriate key binding to hungry delete only on demand.

**Comment by trishume** [comment]
@syl20bnr it would be nice if we could create a framework for all those toggles where there was a unified way to set the default state for any of them in `.spacemacs`, or maybe there is a clean way to do this already.

For example, I would probably want hungry-delete and golden-ratio enabled by default.

**Comment by syl20bnr** [comment]
It can be done easily with stock emacs by adding to `dotspacemacs/config`:

```elisp
(golden-ratio-mode)
(global-hungry-delete-mode)
```

but the downside is that there is no standard way to enable globally a minor mode, sometimes the minor mode is defined with `:global t` like `golden-ratio`, sometimes it is globalized with a `global-` function like `hungry-delete`.

To be consistent with the other `toggles` like the ones we have for layers we could define:
- `dotspacemacs-enable-golden-ratio` to `nil` by default
- `dotspacemacs-enable-hungry-delete` to `nil` by default

I don't think a framework is needed, but we can group thoses variables together in the `.spacemacs` template.

**Comment by syl20bnr** [comment]
But the toggle framework is a nice idea and could enable a dynamic discovery of available toggles within a helm buffer.

Actually I like this idea a lot :-)

:+1:

**Comment by syl20bnr** [comment]
So here it is: 8292d39046070a6e64cb149ba3cf8d1ab990c9a4

This is one macro `spacemacs|add-toggle`
By invoking `helm-spacemacs` we can get the list of toggles (change helm tab with `C-l`) and use them.
I will put a better looking helm buffer later (with the doc string etc...).

I'll code tomorrow the corresponding list variable for easy setup of the toggles in the dotfile.

Thank you for the idea!

**Comment by syl20bnr** [comment]
I close this discussion. We will deprecate the user layers when @trishume is ready.
