### ISSUE TITLE
Feature request: make the package updates selectable when clicking the `Update Packages`

### ISSUE THREAD

**Issue by kccai** [syl20bnr/spacemacs#4915]
#### Spacemacs `Update Packages` updates all the packages

Now in the home buffer of Spacemacs, the `Update Packages` will update all the packages to the latest version. However, some new version packages may be buggy and should not be updated. For example, the latest org mode seems to be causing a lot of problems (see #4793 ). It is often the case that a user has to rollback all the packages to their previous versions for a single buggy package.
#### Temporary solution

There are alternatives such as using the command `list-packages` or `paradox-list-packages` to select the packages to be updated.
#### Problem of temprary solution
1. It seems that packages installed in this way cannot be rolled back.
2. A user has to search and exclude the buggy package from all the packages on elpa.
#### Suggestion

Let the user choose which packages should be updated after clicking `Update Packages` using similar interfaces provided by `list-packages` or `paradox-list-packages`.

Thank you very much!

**Comment by TheBB** [comment]
Alternatively (or additionally) let the user choose which packages to roll back.

**Comment by thang1thang2** [comment]
How about a different alternative? If the user is on the stable branch they should expect the build to stable right? Would it be feasible to lock in a max version number for each package on the stable version (perhaps using some sort of file) so that they couldn't update past that. Then, once a week or so, that file could just be updated so that updating spacemacs automatically updated the packages (if any had updates). Another way to do it would to just somehow "delay" the package check by a week (so if they clicked update packages, it checked from a week ago, assuming MELPA updates weekly. Users on the development branch shouldn't expect that kind of stability so they would make excellent guinea pigs; they could quite easily catch the vast majority of prickly bugs and issues in time for the list to be modified to ensure stability.

**Comment by Andre0991** [comment]
> Alternatively (or additionally) let the user choose which packages to roll back.
Yes, I like this idea. That would be the simplest way to revert a bad update.

**Comment by kccai** [comment]
@TheBB :+1: I like this idea too.
@thang1thang2 It might make the package management more complicate to lock the version number for each package. Actually, I have been using the develop branch for several months. In my opinion, the develop branch is stable enough and most of the time the daily package updates on melpa are quite usable.
