### ISSUE TITLE
Loading Racket will destroy company.

### ISSUE THREAD

**Issue by hujianxin** [syl20bnr/spacemacs#4945]
When I startup Emacs and check into a c file for a python file, company works well. But, once I open a Racket file, company will stop working, even in other file.

And the error messages is:
```
Company: An error occurred in post-command
Company: frontend company-pseudo-tooltip-frontend error "Wrong type argument: number-or-marker-p, nil" on command post-command
```

**Comment by hujianxin** [comment]
I deleted racket-mode and company-mode file and restart emacs, this issue reproduced.

**Comment by hujianxin** [comment]
well
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. 8c8da65)
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(spacemacs-ivy auto-completion better-defaults git github
               (shell :variables shell-default-height 30 shell-default-position 'bottom)
               spell-checking syntax-checking version-control dockerfile puppet django org markdown emacs-lisp
               (c-c++ :variables c-c++-enable-clang-support t)
               common-lisp ess extra-lang html javascript java latex python racket scala scheme sql shell-scripts yaml command-log dash pandoc ycmd evil-cleverparens evil-commentary evil-snipe unimpaired vim-empty-lines vinegar eyebrowse spacemacs-layouts colors cscope deft gtags semantic smex speed-reading themes-megapack)
```

**Comment by greghendershott** [comment]
Although I'm not able to test with spacemacs right now, I did confirm that company-mode and latest racket-mode are still working fine with each other on Emacs 24.5.1 on OS X and Emacs 25.0.50 on Ubuntu. I tried both `global-company-mode` and plain `company-mode`.

---

Using <kbd>C-h f</kbd> I searched for `company-pseudo-tooltip-frontend` from the error message you shared. This seems to be the company-mode code that shows the "popup" completion list. `"Wrong type argument: number-or-marker-p, nil" on command post-command` sounds like a problem with a buffer position. Since I can't repro the problem, I can't tell where. But in any case a buffer position isn't a value that would come directly from `racket-mode`, AFAICT. At the moment it doesn't _seem_ like it's a racket-mode issue I could address.

**Comment by StreakyCobra** [comment]
@greghendershott Thanks for your feedback. If there is no bug on a stock Emacs, then it's probably a problem on our end.

@hujianxin When you have time, can you try removing the whole `elpa` directory. Deleting `racket-mode` and `company-mode` was already a good start, but sometime reinstalling all packages have helped for weird problems :-) If it persists, can you update your bug report to [this form](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report), especially for the backtrace. Thanks

**Comment by hujianxin** [comment]
@greghendershott Thanks for your analysis. It's not racket-mode' bug　exactly.
@StreakyCobra Thanks for your attention.
This problem has been solved, and a PR is waiting to be merged. I'll close this issue. Be free to open it again if there's any question.
