### ISSUE TITLE
Emacsclient does not use full frame size

### ISSUE THREAD

**Issue by person808** [syl20bnr/spacemacs#4977]
#### Description

Using `default-frame-alist` to set the window size causes `emacsclient -c` to use only one-quarter of the frame size when the server is already running.
#### Reproduction guide
- Have `(setq default-frame-alist '((height . 24) (width . 55)))` in `dotspacemacs/user-init`
- Run `emacsclient -c -n -a ''`
- Observe normal behavior
  ![screenshot from 2016-02-05 17-40-21](https://cloud.githubusercontent.com/assets/6396431/12864486/d6195f82-cc2f-11e5-89fd-20b7f80ce613.png)
- Close the frame
- Run `emacsclient -c -n -a ''` again

_Observed behaviour:_
![screenshot from 2016-02-05 17-40-44](https://cloud.githubusercontent.com/assets/6396431/12864488/ed6f8e86-cc2f-11e5-9d10-e8b190169e14.png)

Resizing frame manually produces expected behavior

_Expected behaviour:_
![screenshot from 2016-02-05 17-40-21](https://cloud.githubusercontent.com/assets/6396431/12864486/d6195f82-cc2f-11e5-89fd-20b7f80ce613.png)
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. f942639)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
nil
```

**Comment by person808** [comment]
Can also reproduce using `spacemacs-base`

**Comment by StreakyCobra** [comment]
I'm using systemd to start the daemon, and then `emacsclient -a emacs -c` to start clients. I'm not noticing this behaviour, but I suspect it's due to the fact that I use the `i3` window manager. It's a tailing window manager so it forces windows to take the full space: this is probably triggering a resize of the windows.

**Comment by person808** [comment]
Hmm... not seeing this anymore on a fresh install. @NJBS are you still seeing this?

**Comment by NJBS** [comment]
I could probably write a dissertation based on my experiences with this bug at this point. :smile:

The problem you've described in the initial issue is indeed fixed for me. However, something like `  (add-to-list 'default-frame-alist '(fullscreen . maximized))` still produces the same effect you've described in your issue. The frame will maximize on the first start but on new clients connecting through the server the frame appears "stuck" where manually resizing or defocusing and refocusing the window causes it to maximize as intended, just as you've described. I've tried just about every method for maximizing emacsclient frames I've come across and they all seem to produce the same behavior.

To make matters worse, I can't reproduce this on stock Emacs 24.5.1 and the bug disappears on Emacs 25 using the same spacemacs configuration. It also seems to be specific to Windows as I can't reproduce this on any of my Linux machines.

This behavior didn't occur when I first started using spacemacs and I've spent about 3 months now hunting for what package or configuration might cause this. At this point I've pretty much given up since there are way too many possible factors. I've just trained myself to quickly defocus and refocus the frame whenever I open up a new client. :cry:

**Comment by biocyberman** [comment]
I faced this small annoyance also. I do not remember clearly how I got rid of it. Maybe a backup of all private changes, wipe all trace of the setup and start a clean one.

**Comment by deerpig** [comment]
I am getting this same problem on a clean install of emacs 26 from git running on Debian Jessie.

**Comment by ukari** [comment]
Meet the same problem with emacs 27.0.50 and i3gaps

**Comment by ukari** [comment]
I notice the problem could be resolved by use `(setq frame-inhibit-implied-resize t)` which would prevent emacs auto resizing window size.

[ref](https://stackoverflow.com/a/59375928/4616043)
