### ISSUE TITLE
Perl 6 layer

### ISSUE THREAD

**Issue by AlexDaniel** [syl20bnr/spacemacs#5019]
Would be nice to have a layer for Perl 6. See [perl6-mode](https://github.com/hinrik/perl6-mode).

**Comment by AlexDaniel** [comment]
I'll keep some notes here.

Currently fancy quotes are not supported. All these are not working: ``c i ‘``, ``c i “``, ``c i «``, ``c i ｢``.

**Comment by TheBB** [comment]
Use `spacemacs|define-text-object` to make new text objects for those things.

https://github.com/TheBB/spacemacs/blob/develop/layers/+distribution/spacemacs-base/packages.el#L378-L387

**Comment by theckman** [comment]
@syl20bnr has there been any thought to a Perl 5 layer? I think #7758 may have accidentally been closed as a duplicate of this one.

**Comment by AlexDaniel** [comment]
@theckman that's right

**Comment by CeleritasCelery** [comment]
People unfamiliar with Perl don't know that Perl 6 and Perl 5 are different languages. There is an attempt at a Perl 5 layer with [#8572](https://github.com/syl20bnr/spacemacs/pull/8572) but I seriously doubt it will get merged because it overextends on scope and is messy. What we really need is simple Perl 5 layer PR to get started with. I have been intending open one. Maybe we should just start with an issue for discussion.

**Comment by AlexDaniel** [comment]
Dear bot, I still want this.

**Comment by kalkin** [comment]
Dear @AlexDaniel this is solved in the current development branch :)

**Comment by AlexDaniel** [comment]
Ah, right, I remember. But… it is **still** in the development branch??

**Comment by kalkin** [comment]
@AlexDaniel According to the [CHANGELOG.develop](https://github.com/syl20bnr/spacemacs/blob/develop/CHANGELOG.develop#L353) it is. It's part of the next release I guess…

**Comment by lebensterben** [comment]
closing since it's added to develop branch.
