### ISSUE TITLE
Custom GOPATH per spacemacs-layout

### ISSUE THREAD

**Issue by veverjak** [syl20bnr/spacemacs#5036]
Hi, 

I would like to use [spacemacs-layouts](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bwindow-management/spacemacs-layouts) with go. 
I am also using [gb](https://getgb.io/) for golang projects building, therefore I need to update `GOPATH` per project. 

Is there any simple way I could have per layout GOPATH set using ``GOPATH=`pwd`:`pwd`/vendor``?

**Comment by bmag** [comment]
`setenv` is a function you can use to set GOPATH (haven't tried it myself).
`persp-activated-hook` is a hook that runs you switch a layout.
`projectile-after-switch-project-hook` is a hook that runs after you switch a project.
If the current buffer is part of a project, `projectile-project-root` returns the root directory of the project.
You should be able to cook something from these.

**Comment by bmag** [comment]
You can also use a perspective-local variable to store the correct GOPATH of a layout, instead of relying on `projectile-project-root`. `set-persp-parameter` and `persp-parameter` to write/read perspective-local parameters.
And a clarification - what Spacemacs calls "layouts" are called "perspectives" by persp-mode, which is the library that provides most of the layouts functionality.

**Comment by veverjak** [comment]
Thanks for good tips, I will have a look and post if I come up with something useful here. 
Problem with `setenv` is it won't allow me to eval `pwd` or $(pwd) so `projectile-project-root` seems like a good fit.

**Comment by veverjak** [comment]
@bmag  I am trying to use [go-projectile](https://github.com/dougm/go-projectile) package. 
Could you please advice on how this could be added to spacemacs I didn't find for me understandable way how to:
 - add package to spacemacs, 
 - load package when needed.

I've set 
```
   dotspacemacs-additional-packages
   '(
     go-projectile
     )
```
restarted emacs, seems like package was successfully installed, bud I can't see any of `go-projectile` funcitons. 

Would you help me understand how do I make sure the package is loaded in apropriate situations? 

I am coming from vim world, so I would expect that packages are loaded based on file that is opened but I am totally lost in where can I find this definition pieces in emacs.

**Comment by StreakyCobra** [comment]
Just a random guess, try adding `(require 'go-projectile)` in your `dotspacemacs/user-config`.

**Comment by veverjak** [comment]
Thanks @StreakyCobra , this works. 
I wonder this will mean that `go-projectile` package is always loaded for all files?

**Comment by bmag** [comment]
@veverjak adding a package to `dotspacemacs-additional-package` installs it, but doesn't load it. To load a package, you need to `require` it as @StreakyCobra wrote. Most packages define autoloads, so the package isn't loaded until it is needed.
 `go-projectile` doesn't use autoloads, but If `go-projectile` would have defined an autoload for `go-projectile-mode`, then instead of `require` you would have added to your config:
```elisp
(add-hook 'go-mode-hook 'go-projectile-mode)
```
And then `go-projectile` would be loaded the first time you open a Go file.

There is no such concept of a package being loaded for files. A package is either loaded or not loaded. There are major modes and minor modes, which can be enabled only in some buffers but not others (each buffer has one major mode and any number of minor modes enabled). The `go-projectile-mode` is a minor mode that is only enabled in Go buffers.
What the `require` means is that the package is loaded at start-up, affecting start-up time, instead of auto-loaded later.

More info:
Modes: https://www.gnu.org/software/emacs/manual/html_node/emacs/Modes.html
Loading: http://ergoemacs.org/emacs/elisp_library_system.html

**Comment by veverjak** [comment]
Thanks a lot for clarifications, it helps getting more into emacs :+1: 

Anyway my solution is not elegant, but I am using package `go-projectile` and I set `Makefile` in root of the project to get custom `GOPATH`. 

```
export MF_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
export CUR_DIR := $${MF_PATH%/*}
export GOPATH := $(CUR_DIR):$(CUR_DIR)/vendor


gopath:
			echo "${GOPATH}"
```
