### ISSUE TITLE
How to make spacemacs split window right automatically?

### ISSUE THREAD

**Issue by spacegoing** [syl20bnr/spacemacs#5140]
For example. Every time I type `SPC-g-s` to use `magit` layer, spacemacs pop up a window below my current window. However, I would like to split a right window.

Is there anyway to configure spacemacs automatically do this?

**Comment by bmag** [comment]
Yes, there is more than one way to do this, by configuring some Magit or Emacs settings.

You can set `magit-display-buffer-function` to a function that does what you want. This variable decides what function Magit uses to display its buffers.

You can change the values of `split-height-threshold` and `split-width-threshold`. These variables decide when and how `split-window-sensibly` creates a new window. By default, `display-buffer` uses `split-window-sensibly` when it needs to create a new window.

You can set `split-window-preferred-function` to a function that does what you want. This way you can make `display-buffer` use your function instead of `split-window-sensibly`.

Your question is quite general, you'd have a better chance of getting a good answer on [SE](https://emacs.stackexchange.com/).

**Comment by spacegoing** [comment]
Many thanks @bmag . I set `split-height-threshold` to `nil` and `split-width-threshold` to `0`. It works as I wanted.

**Comment by StreakyCobra** [comment]
@spacegoing If your problem has been answered, you may consider to close the issue :relaxed:
