### ISSUE TITLE
How to jump to source code in c++?

### ISSUE THREAD

**Issue by maplewizard** [syl20bnr/spacemacs#5180]
How can I jump to the source code of a function of a c++ file?

**Comment by NJBS** [comment]
If the function is in the same file, `g d` will usually bring you to its definition. Also, take a look at `SPC  s j` which gives you a nice jump-able overview of your source file. Otherwise, check out the [gtags](http://spacemacs.org/layers/gtags/README.html) and [cscope](http://spacemacs.org/layers/cscope/README.html) layers if you'd like to jump between definitions in different files with tags.

**Comment by TheBB** [comment]
`gd` should also work across files if you configure clang properly. I *think*.

**Comment by NJBS** [comment]
Looks like it actually does jump across files when properly configured, thanks for teaching me something new :+1:

**Comment by StreakyCobra** [comment]
@maplewizard Does your question have been answered?

**Comment by maplewizard** [comment]
@StreakyCobra @TheBB @NJBS Thanks， It solved my problems.

**Comment by csfreebird** [comment]
How to use gd, which command or key binding in spacmeacs, any document for configuring it?

**Comment by duianto** [comment]
@csfreebird `gd` is available in the `vim` editing style.
The function is called: `spacemacs/jump-to-definition`, and there's also: 
`spacemacs/jump-to-definition-other-window`, if you want to add a key binding for them.

**Comment by csfreebird** [comment]
Thanks. I can use M-RET g G or g g to use them.
But how to make this jump into the source code instead of the current buffer?

**Comment by duianto** [comment]
I just noticed that the gtags and cscope links in the comment above, lead to 404 pages. It's because the pages have been moved under a `+tags` directory, since the comment was written.

Here are the correct links from the http://spacemacs.org/layers/LAYERS.html#tags page:
http://spacemacs.org/layers/+tags/cscope/README.html
http://spacemacs.org/layers/+tags/gtags/README.html

@csfreebird I don't know how it works in c++ files, but at least in elisp files, `spacemacs/jump-to-definition` isn't limited to the current buffer, it jumps to the file where a variable or function was defined.

Here are some pages that talk about code navigation:
https://www.reddit.com/r/emacs/comments/1rck3u/what_do_you_use_to_navigate_code/

https://vxlabs.com/2016/04/11/step-by-step-guide-to-c-navigation-and-completion-with-emacs-and-the-clang-based-rtags/

http://emacs-fu.blogspot.se/2009/01/navigating-through-source-code-using.html

https://emacs.stackexchange.com/questions/10125/can-emacs-support-go-to-declaration-of-function-in-an-entire-project

C/C++ Development Environment for Emacs
https://tuhdo.github.io/c-ide.html
- Emacs as C++ IDE
http://syamajala.github.io/c-ide.html
`This guide is meant as supplement to Tudho's C/C++ Development Enivornment for Emacs Guide.`

**Comment by csfreebird** [comment]
Thanks,I am trying semantic now.
