### ISSUE TITLE
Question: long line breaks automatically in coffeescript

### ISSUE THREAD

**Issue by mb-dev** [syl20bnr/spacemacs#5208]
This "feature" drives me crazy. I am not sure which package introduces this behavior. Whenever I type a line longer than 74 character in a .coffee file, a line break is automatically introduced and the 2nd line is properly indented. Even if I modify an existing long line, it breaks around column 74.

I didn't experience this in golang or javascript so I think it's specific to coffeescript. I can't find anything related in coffee-mode, or the other packages in lang/js.

My .spacemacs can be found here:
https://github.com/mb-dev/dotfiles/blob/master/.spacemacs

**Comment by TheBB** [comment]
Sounds like something has turned on `auto-fill-mode`. Try disabling that.

**Comment by mb-dev** [comment]
Yeah. That was the cause. I toggled it, and this turned it off. Not sure which package turns it on. 

I don't see this toggle listed under the documentation. Would it be helpful to make a PR and add it? and also write something about line break, so it's easily searchable?

**Comment by TheBB** [comment]
It's turned on by coffee-mode itself [here](https://github.com/defunkt/coffee-mode/blob/master/coffee-mode.el#L1251)

Turning it off by default in Spacemacs would make it difficult to turn back on, since that would set `auto-fill-function` to its default value of `do-auto-fill`, and not the coffee-mode specific function of `coffee-auto-fill-fn`, which presumably does a better job.

I would prefer to document how to turn this off instead.
