### ISSUE TITLE
[RFC] Use melpa-stable default but make user choose melpa or melpa-stable

### ISSUE THREAD

**Issue by coldnew** [syl20bnr/spacemacs#521]
I have encounter some packages issue these days (2015/02/01), some error message like    
      `eieio-make-class-predicate  is void`  or `cl-struct-define` , these functions are introduce in trunk (2015/01/28 ~ 29), but the emacs  version I use is emacs-mac-port 24.4.3.

After I remove all packages in elpa and modify `core-configuration-layer.el` elpa recipes to elpa-stable and re-install all packages, these error messages are gone. I think that's due to melpa packages always use latest version.

Is there any way to make spacemacs use melpa-stable by default but make user choose melpa instead of melpa-stable ?

**Comment by syl20bnr** [comment]
This is a very good point. Originally I planned to use MELPA stable as default when the refactoring of the layer (see milestone) is done. But I changed my mind, I will opt for a good rollback mechanism and stick with bleeding edge packages. The option to change the MELPA repo will still be here though so any user will be able to set MELPA stable as the default one.

**Comment by malchmih** [comment]
I agree with @coldnew. I've also tried to use fresh 24.4 with spacemacs, but had this kind of issue with magit not working. It's quite confusing for a newcomer like me. While in 25 status bar is not drawn for active buffer (for example).

**Comment by syl20bnr** [comment]
@malchmih If it is confusing for newcomers then we can improve the documentation. If by newcomers you say "I don't know about layers and don't want to learn about them" then spacemacs is not a good solution for them. I'm pretty sure that as soon as a user grasps how the layer works (which should be the case by reading the README.md or we have a documentation bug), adding magit is piece of cake and a O(1) operation. Maybe we can emphasis `SPC f e h` with an example like magit ?

As for Emacs 25 it is not supported for now, only stable 24.3 and 24.4  are supported. If it is not clear in the README.md then PR or issue are welcome :-)

**Comment by malchmih** [comment]
@syl20bnr Yeah, I hear you. And I have to say, documentation is really great, thank you. Magit is already in contrib so it's kind of 'included'. If I understood correctly, it wasn't working for me because of the new functions (in my case magit was saying that `cl-struct-define` was undefined). So the only way to resolve this was to change elpa link to elpa stable, or am I missing something?

**Comment by syl20bnr** [comment]
@malchmih I'm very sorry, my previous answer is half off-topic... ;-( I thought I were replying to another issue...

I never heard of this magit error before but it will be possible to specify another repository for a package.

Now in 0.53.0 (soon to be released) there is a rollback mechanism in case of broken package. But it does not solve the issue of a newcomer who installs spacemacs for the first time. This is a very good point and I did not anticipate this... argh
If the user reports it then I could temporarily force the usage of a stable repo just for the problematic package, or even pushed a working version as an `extension` (source shipped directly with spacemacs) temporarily (it already happened in the past, only one time though).

There is inherent issues with MELPA stable like the lower number of packages and some outdated versions because package authors did not create a new label. Now there is the same kind of issues (reversed) in bleeding edge, the difference is that often the bleeding edge bugs are fixed very quickly (and even if it is not, the stable version could suffer from this as well - in the case of a dependency issue for instance).

The package ecosystem is so lively and there are so many users using the bleeding edge repo than for now I prefer to use it instead of the stable variant. I think that the emacs community is not yet ready for a stable MELPA and maybe this is just inherent to the `bazaar` model and we cannot do anything to this. The alternative would be to use marmalade to break the bazaar model but MELPA has won the race... we have to live with the `bazaar` model.

**Comment by malchmih** [comment]
@syl20bnr Sure, no problem =) I got your point with repositories and totally agree. Thank you for your work - I just started using Spacemacs, but it's been a pleasure already.

**Comment by syl20bnr** [comment]
I close this discussion because of a long period of inactivity.
