### ISSUE TITLE
`fd`, newline, smart parens and python mode

### ISSUE THREAD

**Issue by aldanor** [syl20bnr/spacemacs#5261]
**Emacs:** 24.5.1 (Windows).
**Spacemacs:** latest `develop`.

How to reproduce: in Python-mode type `( RET f d` which will result in

```
(
    )
```

instead of

```
(
)
```

because `f` seems to shift the second parenthesis in an irreversible fashion (closing the parentheses manually works ok of course).

This is a minor issue, not sure if it can be considered a bug but still, reporting it for the record.

**Comment by StreakyCobra** [comment]
Confirmed with my different escape sequence (`gq`).

I don't know if it can be avoided. This effect is due to this:

    (
    )

is the correct indentation that python-mode gives to this line if there is only the closing parenthesis. If there is something on the second line, like:

    (
        x)

the indentation is then shifted by 4 spaces, which is also the indentation the python-mode gives. I suppose whenever people press `fd` the indentation is adapted after the first keypress, thus indenting the line, the second keypress escaping and removing the first letter but not correcting the indentation.

This should probably be reported upstream to [`evil-escape`](https://github.com/syl20bnr/evil-escape).

**Comment by TheBB** [comment]
Yeah this really does kill kittens. Thanks for the tip @StreakyCobra. I've had this issue in Python for a while and I never connected it to evil-escape.

**Comment by TheBB** [comment]
For now I will be using

```elisp
  (add-hook 'evil-insert-state-exit-hook 'indent-according-to-mode)
```

**Comment by syl20bnr** [comment]
Maybe using undo instead of the removing the char may work in evil-escape. I'll test it.

**Comment by calebmeyer** [comment]
Just a note (from #5313) This happens in ruby-mode as well. Test text (pipe is cursor position):
```ruby
  def test
  end|
```

**Comment by TheBB** [comment]
I retract my workaround. It's maddening.

**Comment by calebmeyer** [comment]
This has been reported upstream: https://github.com/syl20bnr/evil-escape/issues/69

We can probably close this and follow the progress there.
