### ISSUE TITLE
Map Spc p F to helm-projectile-find-file-in-known-projects?

### ISSUE THREAD

**Issue by mosic** [syl20bnr/spacemacs#5274]
I find myself using `projectile-find-file-in-known-projects` more and more recently, and think it's a shame there's no default binding for it.

Mapping this would mirror projectile's keybindings nicely:

`C-c p f` (`projectile-find-file`) -> `SPC p f` (`helm-projectile-find-file`)
`C-c p F` (`projectile-find-file-in-known-projects`) -> `SPC p F` (`helm-projectile-find-file-in-known-projects`)

Btw I saw https://github.com/syl20bnr/spacemacs/pull/4144 but I'm still unclear of the differences between `projectile-find-file` and `projectile-find-file-dwim`. If it's actually significant maybe an explanation could added to the documentation?

**Comment by sooheon** [comment]
`projectile-find-file-dwim` is highly redundant with `projectile-find-file`. It essentially only does anything extra if your point is on a file path string. Pretty rare case, imo. `projectile-find-file-in-known-projects` is a better candidate for `spc pF`, but I think maintainers put dwim on `pF` because that's a common pattern in spacemacs, where the capitalized version pre-populates the search `spc /` vs `spc ?`, for instance. IMO, if you want the dwim functionality, you should just rebind the `spc pf` binding, and `spc pF` should be used for find-file-in-known-projects, as you suggest.

**Comment by tuhdo** [comment]
`helm-projectile-find-file-in-known-projects` can hang Emacs if you have really large projects i.e. over 100 thousands of files or more in total, that is only usable when you turn on Projectile caching. But in this case, the caching is off by default. I am having more than 120k files in all my projects, so it's not usable and I believe many have people have quite large projects.

`projectile-find-file-dwim` is useful when you need to jump to file at point, without having to type. For example, in a C/C++ projects, you have tons of header files that are in your current project. You can then use `projectile-find-file-dwim` to jump to those files quickly i.e. no need to see a list of candidates then start typing. Or in many cases you see file paths in strings, you may want to jump there to have a look. And if there's more than one candidate, `projectile-find-file-dwim` only selects those files that have the filename at point in it, so it's easier for you to select.

**Comment by tuhdo** [comment]
Here is how `helm-projectile-find-file-dwim` works:

[helm-projectile-find-file-dwim](http://tuhdo.github.io/static/helm-projectile/helm-projectile-find-files-dwim-1.gif)

**Comment by sooheon** [comment]
I see why the dwim is useful, but then why not bind it to `spc pf`? It seems quite redundant with vanilla projectile find file, when the point of dwim is that you don't need multiple bindings, to do a context aware action.

**Comment by tuhdo** [comment]
If we bind it like that, @syl20bnr won't like it; it is similar to text search at point issue as he considered it annoying.

We can't use prefix argument, since prefix argument has meaning in most Projectile commands. Maybe we can make a wrapper Spacemacs command, that when invoke without prefix, call `helm-projectile-find-file` and if we supply a prefix argument, call the dwim version.

**Comment by mosic** [comment]
Nice to hear opinions on both sides, and thank you @tuhdo for the demonstration of `helm-projectile-find-file-dwim`, that looks potentially pretty useful.

Because I'm using caching in my setup (with native indexing, because of a bug in projectile regarding ignored files) I see how my use-case isn't a common one. I ended up adding a shortcut to `SPC o f`:

```
(evil-leader/set-key "of" 'helm-projectile-find-file-in-known-projects)
```

I'm happy with this solution, so I'll close the issue.
