### ISSUE TITLE
Question: what key does 'SPC' refer to?

### ISSUE THREAD

**Issue by chfw** [syl20bnr/spacemacs#5283]
I have searched in the documentation but cannot find the definition for 'SPC' while emacs documentation has clearly stated C for Ctrl key. Could someone help? Thanks

**Comment by TheGreenHabi** [comment]
Hello.
`SPC `stands for `spacebar`

**Comment by robbyoconnor** [comment]
I would have thought this was clear...

**Comment by thang1thang2** [comment]
To be fair, if someone isn't used to `C-a S-b A-d-e-f` type of shortcut describing of shortcuts and keybinds, it can be a tad confusing. In the documentation where we describe that C is for the Control key, we should probably expand it to say that C is for Control (often abbreviated as Ctrl), S is for Shift, A is for Alt, SPC is for Space, M is for Meta, etc. Perhaps a table might be the most condense way to describe the information?

**Comment by d12frosted** [comment]
> A is for Alt

Pretty false. Especially when you continue with `M is for Meta`, which is usually most frustrating key for new users. Do you have `Meta` key on you keyboard? :)

But I see your point. Also it could be noted that `C-x C-s` can be pressed in two ways.

**Comment by d12frosted** [comment]
Ah, and to be totally fair:

https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#evil-leader
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#leader-key
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#emacs

**Comment by chfw** [comment]
If SPC means space bar, I may have wrongly used my keyboard short cuts. When I did 'SPC + k + u', I got exactly a space, 'k' and 'u' in my editor. What's wrong with my setup? Or else..

**Comment by TheGreenHabi** [comment]
Spacemacs is modal editor. I think you are in _Insert mode_. By pressing `Escape key` you will go to _Normal mode_, where all key commands should work as you expect.

**Comment by d12frosted** [comment]
> Spacemacs is a modal editor.

Not really true :) It is modal when you are using vim or hybrid editing style. 

@chfw in case you have any problems with anything it's useful to share output of `SPC h d s`. In case `SPC` prints regular space you could use `M-m h d s`. So we can see the most important parts of your setup.

**Comment by chfw** [comment]
hmm... I think I have chosen emacs mode when I am asked for emacs or vim. I forgot to say that I am actually an emacs user. I guess @d12frosted in emacs mode, I should have used M-m for SPC. I have tried M-m k u and it worked as expected (undo).

**Comment by d12frosted** [comment]
@chfw yay, a fellow emacs editing style user! Usually we have vim users, so they are not confused by all those leaders. I was confused as well back when I just started to use Spacemacs. I think [quick start guide](https://github.com/syl20bnr/spacemacs/blob/master/doc/QUICK_START.org#the-leader-keys) helped me to understand this.

So yeah, you will translate all key bindings like following:

```
SPC   -> M-m
SPC m -> C-M-m (or M-Return)
,     -> SPC m
```

And probably I found my way just by reading configurations:

```
(setq-default
  ...
  dotspacemacs-emacs-leader-key "M-m"
  dotspacemacs-major-mode-emacs-leader-key "C-M-m"
  ...
)
```

So you can even change it :) I was experimenting with `C-c` instead of `M-m` some time ago, but now I think I like `M-m` more :) 

P. S. If you have any questions about Spacemacs and don't feel like opening issue for it - just ask on Gitter.

**Comment by pklapperich** [comment]
Related question... When I'm searching online, I see a lot of things say to type in "<SPC> : some-command". It seems they mean "<SPC> <SPC> some-command" (for evil-mode) or "M-x some-command" for emacs-mode. But why does so much say ":"? Was that key changed at some point?

**Comment by robbyoconnor** [comment]
SPC SPC

**Comment by robbyoconnor** [comment]
:w! is an ex-command in vim parlance.

**Comment by robbyoconnor** [comment]
`SPC SPC` does an emacs command; `SPC :` will execute a function, `:` is an `ex` command, in vim parlance.

**Comment by pklapperich** [comment]
`SPC SPC` and `:` work for me. When I type `SPC :` I just get _SPC : is undefined_

**Comment by robbyoconnor** [comment]
@pklapperich What's your `.spacemacs` look like?

**Comment by pklapperich** [comment]
It's just the default config generated on first use. I chose `vim`, `spacemacs`, `helm` during setup.
[DOTspacemacs.zip](https://github.com/syl20bnr/spacemacs/files/839783/DOTspacemacs.zip)

This is starting to sound like I should be starting a new issue.

**Comment by robbyoconnor** [comment]
Don't give me a zip file -- give me your `.spacemacs` in in a code block...

**Comment by robbyoconnor** [comment]
Here's mine: https://github.com/robbyoconnor/.spacemacs.d/blob/master/init.el

**Comment by robbyoconnor** [comment]
It's customized for me.

**Comment by pklapperich** [comment]
Sorry, I didn't want to splat in 260 lines of unmodified config after co-opting someone else's issue and github wouldn't let me attach the file otherwise.

But it looks like there's no bug... If I checkout `794904adb` _Bump current version to 0.104_ then the default .spacemacs `SPC :` is mapped to `helm-M-x` and `SPC SPC` is mapped to `evil-ace-jump-word-mode`. This remains through 0.105.5 (though `SPC SPC` is mapped differently there.)

If I checkout 105.6 or newer then `SPC SPC` is mapped to `helm-M-x` and `SPC :` is undefined. So I guess that's my answer; `SPC :` keybinding changed to `SPC SPC` in version 0.105.6 (well, technically in `rev 58e5241c8d9`)

**Comment by robbyoconnor** [comment]
Try doing `SPC f e D` and check your config against the template.

**Comment by robbyoconnor** [comment]
I vaguely recall there was an option to map those.

**Comment by pklapperich** [comment]
My config is identical to the template as it's the default config generated by a fresh install. I found the answer to my question before I made my last comment. `SPC f e D` shows only the emacs generated `(custom-set-variables )` differs.

**Comment by markus-zhang** [comment]
> I would have thought this was clear...

This is definitely not clear. I thought it was acronym for SpaceVim and there is a special key for it, so it took me an hour to search the doc and get here.

**Comment by robbyoconnor** [comment]
SpaceVim != Spacemacs

**Comment by jpventura** [comment]
According to the [quick help][quick-help-url], _press_

  - _<kbd>SPC</kbd> (in **Vim** editing style) or_
 - _<kbd>ALT</kbd>-<kbd>m</kbd> (in **Emacs** editing style) to access Spacemacs commands._

[quick-help-url]: https://www.spacemacs.org/doc/DOCUMENTATION.html
