### ISSUE TITLE
Emacs editing style can be corrupted by evil

### ISSUE THREAD

**Issue by d12frosted** [syl20bnr/spacemacs#5291]
#### Description
Even if you are using `emacs` editing style it's still possible to enable (enter?) evil mode. For example, `(evil-insert-state nil)` like in https://github.com/syl20bnr/spacemacs/pull/5290 or some keybindings I can't haunt. It's very-very annoying. At least I know that I can reset everything by calling `holy-mode` twice (to disable it and enable), but I think that `emacs` editing style users should not be affected by evil stuff at all. 

#### Reproduction guide
- Start Emacs
- `M-: (evil-insert-state nil) <ret>`

*Observed behaviour:*
You're in one of vim states. And you can't control your lovely Emacs anymore. 

*Expected behaviour:*
You're still in default emacs editing state. And you are happy. 

#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.11
- Spacemacs branch: deft/emacs-style (rev. 5aea170)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((auto-completion :disabled-for org)
 better-defaults colors
 (deft :variables deft-directory
   (concat d12/dropbox-path "Apps/deft"))
 emoji eyebrowse
 (git :variables git-magit-status-fullscreen t)
 github
 (org :variables org-enable-github-support t org-bullets-bullet-list
      '("◉" "○" "✿" "❀" "✸"))
 pandoc ranger restclient syntax-checking spacemacs-layouts spacemacs-helm spell-checking
 (shell :variables shell-default-term-shell "/usr/local/bin/fish")
 version-control no-dots
 (elfeed :variables elfeed-feeds d12/elfeed-feeds rmh-elfeed-org-files 'nil)
 (csharp :variables omnisharp-server-executable-path "~/Developer/Other/omnisharp-roslyn/artifacts/build/omnisharp/omnisharp")
 emacs-lisp erlang
 (haskell :variables haskell-enable-ghc-mod-support t haskell-enable-hindent-style "chris-done" haskell-tags-on-save nil haskell-process-log t haskell-process-reload-with-fbytecode nil haskell-process-use-presentation-mode t haskell-interactive-mode-include-file-name nil haskell-interactive-mode-eval-pretty nil haskell-process-suggest-haskell-docs-imports nil)
 (html :variables web-mode-markup-indent-offset 2 web-mode-attr-indent-offset 2 web-mode-code-indent-offset 2 web-mode-css-indent-offset 2 web-mode-sql-indent-offset 2 css-indent-offset 2)
 (javascript :variables js-indent-level 2 js2-basic-offset 2)
 lua markdown python ruby shell-scripts yaml react)
```

**Comment by StreakyCobra** [comment]
#5111 I think this one partially solved it.

**Comment by d12frosted** [comment]
Well, that commit is about introducing `spacemacs/normal-to-insert-state` function and using it. But honestly, I think that it's not a solution. In my opinion, emacs editing style ideally should be evil-free. Totally. Without any compromises. We have hybrid editing style for those who stick with both styles. And vim for vim-lovers. 

I'm for making evil (and all it's friends) optional. But it's good to have at least this step. :D

**Comment by AlejandroCatalina** [comment]
Yes I feel the same about it but I think @syl20bnr intentions are not in this line so we do what we can :P.

On Feb 28, 2016 14:16, Boris <notifications@github.com> wrote:

Well, that commit is about introducing spacemacs/normal-to-insert-state function and using it. But honestly, I think that it's not a solution. In my opinion, emacs editing style ideally should be evil-free. Totally. Without any compromises. We have hybrid editing style for those who stick with both styles. And vim for vim-lovers. 

I'm for making evil (and all it's friends) optional. But it's good to have at least this step. :D

**Comment by syl20bnr** [comment]
>  In my opinion, emacs editing style ideally should be evil-free. Totally. Without any compromises. 

Unfortunately this is not the direction I want for Spacemacs but this direction is for stuff under the hood, at the surface the feeling of `emacs` editing style should be like regular Emacs.

Spacemacs is an Evil centric distribution and as such I want it to clearly embrace Evil as _it was the goal from the beginning_.

Avoiding Evil introduced a lot of headache because Spacemacs is not designed to be Evil free, but don't worry the UX for `emacs` editing style was here since early 2015 and even when Evil was still here people were happy (minus one or two things at most that could have been fixed). The evil free `emacs` style is a recent addition and it generated a lot of regression, we basically traded (or shifted) minor inconveniences that coud have been fixed easily for another bag of issue (far more annoying and invasive in the configuration of packages). This was a counter intuitive and radical change to the way Spacemacs is designed (i.e. around Evil) and I made a mistake.

**Comment by syl20bnr** [comment]
@d12frosted BTW the original design of holy-mode fixed this issue since in this design `evil-insert-state` was advised to enable `evil-emacs-state` instead, so this issue is one more regression I can add to the long list of bad consequences following the deactivation of evil.

**Comment by tessiof** [comment]
@syl20bnr If the evil free emacs style is considered a misted, will it be removed?

**Comment by syl20bnr** [comment]
It has been already removed two months ago and back ported to master a few weeks ago.
Now Evil is always enabled behind the hood but it should be transparent for users. It is better to keep evil enabled in order to keep Spacemacs consistent and easy to understand (may be counter intuitive but that's how it is :-))

**Comment by d12frosted** [comment]
For really long time I didn't experience any problems with evil being... well, evil to me. So I consider this issue fixed. Thanks everyone for fixing it!
