### ISSUE TITLE
c-c++ layer conflict with helm-gtags and semantic

### ISSUE THREAD

**Issue by chunhuitrue** [syl20bnr/spacemacs#5295]
#### Description

c-c++ layer disable helm-stags and semantic。
#### Reproduction guide
- add semantic to dotspacemacs/layers in .spacemacs
- add helm-gtags to dotspacemacs-additional-packages in .spacemacs
- start Emacs.now helm-gtags and semantic is ok
- then add c-c++ layer to dotspacemacs/layers in .spacemacs
- start Emacs. helm-gtags is disappear!

_Observed behaviour:_
delete c-c++ layer in .spacemas

_Expected behaviour:_
#### System Info
- OS: darwin
- Emacs: 24.4.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 93e55bb)
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t))
```
#### Backtrace

```
BACKTRACE IF RELEVANT
```

**Comment by bmag** [comment]
First thing, there is a `gtags` layer. Try using it instead of installing `helm-gtags` as an additional package.

Second thing, I couldn't understand what the conflict is. What do you mean that the observed behaviour is "delete c-c++ layer in .spacemacs"? What is the meaning of "helm-gtags is disappear"? The bindings don't work? Spacemacs deletes the package?
