### ISSUE TITLE
YASnippet isn't loaded for CSS/SCSS modes and can't find .emacs.d/private/snippets dir

### ISSUE THREAD

**Issue by exitface** [syl20bnr/spacemacs#532]
Opening a CSS or SCSS file doesn't enable YaSnippet mode.

In my attempt to load them, I performed `M-x yas-global-mode`. This causes emacs to attempt to load from .emacs.d/snippets rather than the .emacs.d/private/snippets dir. Putting snippets in the former dir allows them to be loaded. Not sure if these issues are related. Note that it DOES find .emacs.d/private/snippets on non CSS/SCSS files.

**Comment by jcpetkovich** [comment]
That's because the hook that sets up spacemacs's yasnippet snippets is only added to certain parent modes:

    (add-to-hooks 'spacemacs/load-yasnippet '(prog-mode-hook
                                              markdown-mode-hook
                                              org-mode-hook))

`css-mode` and `scss` mode do not inherit from any of the above top-level mode classes. They both are derived from `fundamental-mode`, so the hook should probably be added to them individually. I have also noticed that snippets aren't loaded for latex mode sometimes, since it derives from `text-mode`.
