### ISSUE TITLE
Escape Deselect in Hybrid Mode

### ISSUE THREAD

**Issue by spattersongt** [syl20bnr/spacemacs#5364]
In dotspacemacs-editing-style 'hybrid, if you go into insert mode, then use Shift+Arrows to select something, then press escape (multiple times) the selection does not deselect.

Vjjjj <ESC> Selects something then deselect on ESC.  Would be nice if the hybrid-started selection would do that as well.

**Comment by justbur** [comment]
Shift plus arrows does not put you in visual state, which explains the result. You can check that you get the same behavior with vim editing style, so this is not specific to hybrid.

**Comment by spattersongt** [comment]
Yeah, it's not visual mode.  But the selection gets wacky when you press escape back to normal mode.  

The only way to end the selection (that I've found) is to go back into insert mode and press Shift+arrow

**Comment by justbur** [comment]
C-g will get you out of it too. That's the emacs way of getting out of
anything.

It's possible this is something worth reporting at the evil repo. I agree
that it's a confusing state to get into.

**Comment by sooheon** [comment]
Yeah C-g is the way you'd do it in emacs, which is natural because essentially with the shift keys what you're doing is like selecting with `set-mark-command`, not `visual-state`. If you want shift + arrow keys to  automatically take you from insert-state to visual state, this is not something which is even in vim, so you're free to customize, but it's new ground.

**Comment by d12frosted** [comment]
Closing this issue as initial question was resolved.
