### ISSUE TITLE
Viewing magit log for single file prevents viewing log for entire branch

### ISSUE THREAD

**Issue by mmcnl** [syl20bnr/spacemacs#5384]
#### Description
Viewing magit log for single file prevents viewing log for entire branch

#### Reproduction guide
- Start Emacs
- open a file within a git repo
- view log for entire branch: `SPC g l l`
- note log shows all branch commits as expected
- view log for current file: `SPC g L`
- attempt to view log for entire branch: `SPC g l l`

*Observed behaviour:*
Shows only commits touching current file

*Expected behaviour:*
Show all branch commits

#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.12
- Spacemacs branch: develop (rev. f6657a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((spell-checking :variables spell-checking-enable-by-default nil))
```

**Comment by mmcnl** [comment]
It appears that the command to view the log for the current file (`SPC g L`) sets a persistent flag within magit to filter the log to that file.

**Comment by bmag** [comment]
Short answer: After `SPC g L`, use this to view log for entire branch: `SPC g l = f l`.

From the little I tested, it seems to work the same way with stock Magit (i.e. without Spacemacs config). You can read about logging in Magit's [manual](http://magit.vc/manual/magit/Logging.html#Logging), and if this behaviour is not intentional please consider reporting a bug upstream to Magit.

From what I see, `SPC g L` (`magit-log-buffer-file`) causes Magit to set a "Limit to files"  flag. For example, it sets `-- "init.el"` if I call `SPC g L` from the file `init.el`.
In `SPC g l` (`magit-log-popup`), you can see the flag's value under `=f`, and you can clear the flag by pressing `=f`.

**Comment by mmcnl** [comment]
Thanks for the input @bmag. The behavior indeed makes sense to me in the context of Magit in the sense that to set the per-file filter you would have had to have manually set the flag yourself. However, I think in the context of Spacemacs it is a sub-optimal user experience. This is because when using the Spacemacs command `SPC g L` someone new to Magit would have no idea what was happening when the `SPC g l l` log command suddenly "breaks" (ie is being filtered) because they had not set the filter themselves (with `=f`) -- it happened under the covers "inside of" the `SPC g L` command. I wonder if it'd be nice for Spacemacs to wrap the `magit-log-buffer-file` function to additionally unset the flag and then bind that wrapped function to `SPC g L`?

**Comment by nixmaniack** [comment]
I agree with @mmcnl. The root level bindings should be wrapped around to provide better user experience. :+1:

**Comment by tarsius** [comment]
This isn't specific to Spacemacs. When using the standard binding <kbd>C-c M-g l</kbd> the same happens.

It's also the intentional default behavior, but it should be possible to configure this. Unfortunately this doesn't quite work right now. The mechanism that should be used to use different log arguments for different kinds of log buffers is "locking a buffer to its value". See [Modes and Buffers](http://magit.vc/manual/magit/Modes-and-Buffers.html) and [Naming Buffers](http://magit.vc/manual/magit/Naming-Buffers.html).

But some additional things are necessary to make this work.

* The buffer has to start out in locked state. If the buffer starts out unlocked and is later locked, then it is to late and the regular log/diff buffer already has the file filter set. There probably should be an option which controls this behavior.
* Currently only the revisions are considered to be part of the "buffer value". For logs and diffs the file filter (i.e. the value of the `"-- "` pseudo argument) should be part of the "value".

These things would have to be implemented in or near `magit-mode-get-buffer`, `magit-generate-new-buffer`, `magit-generate-buffer-name-default-function`. They probably should be  taught to lock the buffer if `this-command` is one of the per-file commands. `magit-generate-buffer-name-default-function` would likely also have to be adjusted.

Please note that I am currently taking a break. So while this all sounds quite straight forward (at least to me) I suspect that things could get a bit more complicated (implementation-wise, but also "if I do this, then I should also..."). If someone else feels like taking a stab at this, then please feel free to do so. Otherwise you'll have to wait until I have more time again to work on Magit. To make sure I don't forget about this, you should probably open an issue against Magit itself (I'll then copy this over).

**Comment by StreakyCobra** [comment]
Thanks @tarsius for you feedback and support :-)

@mmcnl As you are the original poster I let you the honor to open the issue upstream (on magit) as proposed. If you don't want to do it let us know, thanks :-)

**Comment by mmcnl** [comment]
Thanks @StreakyCobra. I've opened an issue upstream: https://github.com/magit/magit/issues/2585

**Comment by tarsius** [comment]
This has been addressed upstream, see https://github.com/magit/magit/issues/2585#issuecomment-218903124.

**Comment by TheBB** [comment]
Thanks, but in fact we removed the alternative bindings for this, preferring instead to go via magit status. So this issue should have been marked as fixed (or not relevant).

**Comment by nixmaniack** [comment]
@TheBB We still have it on develop under `SPC g f h`. :) Thanks @tarsius for the fix, much useful and better now.

**Comment by massich** [comment]
I can observe the same behavior in late versions of develop branch
