### ISSUE TITLE
Use Helm for adding buffers to layouts

### ISSUE THREAD

**Issue by a13ph** [syl20bnr/spacemacs#5437]
Currently `SPC l a` uses ido, and mixing various "similar but not really" UIs is distracting and confusing.
Not to mention even backend completion is very different there

**Comment by bmag** [comment]
`SPC l a` runs `persp-add-buffer`, which uses `read-buffer` to prompt for a buffer.
In turn, `read-buffer-function` is set to `persp-read-buffer`, causing `read-buffer` to call `persp-read-buffer`.
Because `ido-mode` is enabled, `persp-read-buffer` itself calls `ido-read-buffer`, and that's the prompt you see.

It really is confusing that we usually use Helm prompts, but still use Ido prompts sometimes. I think Spacemacs shouldn't enable ido-mode by default. We don't need to remove the entire Ido support, just remove the call to `(ido-mode)` and change any logic that assumes ido-mode is always enabled.

**Comment by a13ph** [comment]
We should have ido/helm/ivy separated by default by user's choice. If he decides to mix and match - that's less usual case and should be handled as such (enable/disable some framework only in some cases somehow)

**Comment by d12frosted** [comment]
What is the status of this issue?

**Comment by bmag** [comment]
It's all good now. Layouts TS uses only Ivy prompts when `ivy` layer is used, and only Helm prompts when `helm` layer is used.
