### ISSUE TITLE
absence of LaTeX change environment hotkey

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#5452]
To insert a LaTeX environment, I can use ",e" or C-c e, or select LaTeX from the menu bar and click "insert environment".

However, currently there's no way to change an environment apart from selecting LaTeX from the menu bar, and clicking "change environment". The hotkey C-u C-c C-e for changing the environment is broken, and no alternatives are offered.

The hotkey I suggest for this alternative is ",E" (compare with ",e" as referenced above for inserting an environment)

Thanks, ndurrani.

**Comment by bixuanzju** [comment]
Why not `SPC u ,e`?

**Comment by bixuanzju** [comment]
BTW, `SPC u` is the equivalent of `C-u`

**Comment by ndurrani** [comment]
Oh that works. I wasn't aware of `SPC U`, so feel free to close this issue. 

Still, changing environments is something I do very often; for example I often decide that I want to reference an equation, so I change from _displaymath_ to _equation_. So I think it would be worthwhile having a more convenient, shorter key sequence than `SPC u ,e`. So something like `,E` as mentioned or `,w` because w is right next to E.

But again, in light of the recent information, there isn't really a problem to fix.

**Comment by vishvanath45** [comment]
@sdwolfz This issue can be closed.
