### ISSUE TITLE
Consider adding 'company-quickhelp' to the 'company-mode' layer

### ISSUE THREAD

**Issue by quartz55** [syl20bnr/spacemacs#546]
Just saw this being posted on the Emacs Reddit and it caught my attention: [company-quickhelp](https://github.com/expez/company-quickhelp)

I think it would provide for a nice enhancement :)

**Comment by syl20bnr** [comment]
Great finding! :+1:

**Comment by Funnnny** [comment]
I tried adding company-quickhelp. Some problem:

- pos-tip color is not match the theme, I added two line below to match solarized dark, but someone might want to do it better 

`(setq pos-tip-foreground-color "#839496")
 (setq pos-tip-background-color "#073642")`

- pos-tip popup show correct tooltip position with lisp file, but in python-mode, it display off a lot to the right. Maybe company-width isn't correct?

Otherwise it's a great addition, if someone point me the right direction I will do a PR.

**Comment by syl20bnr** [comment]
Very cool !

For the color part, maybe the support for pos-tip must be added to the theme itself.
For the position I guess the best is to make the PR and open an issue for it. This way a more people will be aware of it and we my find a solution quicker.

**Comment by syl20bnr** [comment]
Oops wrong button again... sorry

**Comment by Funnnny** [comment]
Someone has reported the position issue here: expez/company-quickhelp#2

**Comment by Funnnny** [comment]
I have opened a PR for update solarized theme. The theme will set pos-tip-background-color, but the pos-tip package will load after that, so it seems to override the value.

Reload theme with SPC T h seems to fix the problem.

**Comment by syl20bnr** [comment]
Thank you @Funnnny, I'll look into this tomorrow.

**Comment by syl20bnr** [comment]
Fixed with #678
