### ISSUE TITLE
ipython-notebook layer and evil mode ("Text is read-only" at the end of cell)

### ISSUE THREAD

**Issue by aldanor** [syl20bnr/spacemacs#5492]
#### Description

Some of the ways to enter insert mode like 'S' that involve deleting don't work in `ipython-notebook`, mostly when this involves deleting/editing the last line of the cell.
#### Reproduction guide + observed behaviour
- Start Emacs
- Start IPython notebook, connect to it via `SPC a i n`
- Enter insert mode via 'i', type `foo` in a new cell, exit to normal mode
- evil commands that don't work:
  - 'S': cursor goes back to the start of the line, but doesn't enter insert mode with `Text is read-only` error (however will work as long as the cursor is not positioned on the last line of the cell).
  - 'dd': same as 'S'.
  - 'Vd': fails to delete selection if it contains last line.
  
  There's probably more of these, but the cause seems to be the same.
- Another example of a problem at the end of the cell: type `foo` in a new cell, exit to normal mode and move the cursor to the next line via `j` (this line still belongs to the cell and is not the global end of buffer). Now you can enter into insert mode successfully with `i'`, however you won't be able to type any text due to `Text is read-only` error; this may be quite confusing.

_Expected behaviour:_
Commands like `dd`, `S` and `Vd` should work even if positioned on the last (or the only) line in the current cell. If entering the insert mode is allowed, inserting new text should also be allowed.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: origin/develop (rev. 82fdd9a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t)
 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
 csv deft emacs-lisp eyebrowse
 (git :variables git-magit-status-fullscreen t magit-save-repository-buffers 'dontask magit-revision-show-gravatars nil)
 (github :variables gh-profile-default-profile "aldanor")
 html javascript ipython-notebook markdown org
 (python :variables python-fill-column 99 python-test-runner 'pytest)
 rust search-engine
 (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t)
 shell-scripts spacemacs-helm syntax-checking themes-megapack version-control yaml aldanor dash osx)
```

**Comment by aldanor** [comment]
Update, a related issue upstream: https://github.com/millejoh/emacs-ipython-notebook/issues/58.

**Comment by alimoeeny** [comment]
Hi @aldanor 
- I tried to reproduce this, but couldn't, with the latests version of `ipython` and `notebooks` (**NOT** `Jupyter`) and latest `spacemacs` on macosx sierra. The output lines are readonly as they should be (at least that is my understanding). while the "command" lines are editable, `S` works there fine as far as I can tell. 

- given the transition to Jupyter HTML Server, is this ticket still relevant? It has been a year or so since I last used iPython notebooks, so I am not up to speed, 
- Can you please confirm the problem still exists?
- Otherwise I want to suggest we close this issue.

**Comment by diadochos** [comment]
#### Description
I started using this layer yesterday, and encountered this same problem.
The observed behaviour is (literally) the same as that reported by @aldanor .

#### Reproduction guide
- Start Emacs
- Start Jupyter notebook with `jupyter notebook`, then connect to it via SPC a i n
- The same procedure as @aldanor has described above.

*Observed behaviour:*
The same as @aldanor .

*Expected behaviour:*
The same as @aldanor . To state again, evil commands that relate to editing the entire line should be allowed when the cursor is within the cell, including its last line.

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.50.1
- Spacemacs: 0.200.2
- Spacemacs branch: nil (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- `jupyter --version` : 4.1.0
- Layers:
```elisp
(csv
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-private-snippets-directory "~/.emacs.d.bak/snippets/")
 better-defaults ipython-notebook emacs-lisp
 (org :variables org-enable-github-support t)
 osx spell-checking syntax-checking
 (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rbenv ruby-test-runner 'rspec)
 python javascript latex yaml php gtags ess version-control git html clojure extra-langs docker my-keybindings my-config-from-spacemacs-base)
```

**Comment by alimoeeny** [comment]
So I guess the important part (missing from the original report) is using `Jupyter` not the not deprecated `ipython`

**Comment by diadochos** [comment]
Oops, I guess that's my bad. I tried it again, this time with a newly installed `ipython notebook`.
So this occurs with both `ipython notebook` and `jupyter notebook` servers.
(I turned off my personal layers and reproduced this as well).

#### Reproduction guide
- Install Ipython notebook with `pip install ipython[notebook]`
- Start Emacs
- Start Ipython notebook with `ipython notebook`, then connect to it via SPC a i n
- The same procedure as above reports follows

#### Observed behaviour
The same as above reports.

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.50.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- `ipython --version`: 5.1.0
- Layers:
```elisp
(csv
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-private-snippets-directory "~/.emacs.d.bak/snippets/")
 better-defaults ipython-notebook emacs-lisp
 (org :variables org-enable-github-support t)
 osx spell-checking syntax-checking
 (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rbenv ruby-test-runner 'rspec)
 python javascript latex yaml php gtags ess version-control git html clojure extra-langs docker)
```

**Comment by aldanor** [comment]
@alimoeeny ipython and jupyter notebooks are the same thing; the problem is observed with the latest version as of today.

**Comment by deisi** [comment]
yep I see the same on windows 7 with a jupyter server.

**Comment by ylabbe** [comment]
I have the same problem on Linux with a jupyter notebook in the latest develop 45ee95c289adaba6f7eff0c2564756ea41d9fb15 and ipython 6.4.0
