### ISSUE TITLE
Switch evil-leader to hydra?

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#550]
Been seeing a lot of posts recently on Reddit.  Think this could be a suitable / more robust solution to `evil-leader`?  Looks like it combines the utility of `guide-key` and `evil-leader` together into a framework.  

https://github.com/abo-abo/hydra

**Comment by syl20bnr** [comment]
`hydra.el` is a macro on top of transient maps which are temporary overlay maps which are exactly the same thing as what micro-states are using, so they cannot be used for regular key bindings.

I will make spacemacs own macro to simplify the micro-states, I don't like the API of hydra.el based on hydras, bodys. colors head blue, red and now amaranth... seriously WTF ?! This is indeed fun but also very confusing for any person reading the code (even blogs must re-explain each time what colors does what otherwise nobody understand anything). For a personal config it's OK and fun, not for an emacs kit.

I let this issue open for some time if others want to comment.

**Comment by syl20bnr** [comment]
I coded the macro for easily defining micro-states: 
- the macro https://github.com/syl20bnr/spacemacs/blob/develop/core/core-micro-states.el#L14-46
- example for helm: https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L1247-1261

It is also fully compatible with 24.3 which is not the case with hydra.
