### ISSUE TITLE
python shell freezes upon TAB completion when using IPython shell

### ISSUE THREAD

**Issue by shelper** [syl20bnr/spacemacs#5544]
#### Description

if i use "ipython" as the default interpreter. and enter the ipython shell, and if I use tab completion within a function definition, whole emacs hangs up.

for instance, if i type:

```
def foo():
      i[cursor here]
```

first of all, no autocompletion popup shows up here, 
and if i press TAB, the shell and emacs freezes, 

but everything outside of a function works, autocompletion popup also shows up, and TAB completion works. 
i disabled company-mode, Helm-mode, problem still exists. 

I enabled debug-on-error. but no debug message, it just freezes the whole emacs, CPU usage is not high either, ~2% on my macbook pro. 
#### Reproduction guide

i am using the latest spacemacs 0.105.14, emacs 24.5.7, on Mac osx Yosemite 
python 3.5.1, ipython 4.1.2

_Observed behaviour:_
DESCRIPTION OF THE OBSERVED BEHAVIOUR

_Expected behaviour:_
DESCRIPTION OF THE EXPECTED BEHAVIOUR
#### System Info
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults emacs-lisp git markdown org python osx)
```
#### Backtrace

```
BACKTRACE IF RELEVANT
```

**Comment by olejorgenb** [comment]
I've got major problems with the python layer too (using the **develop** branch). OPs description seems accurate. Only way to de-hang is to use ctrl-g which kills the inferior python process... 

I've gotten the bug both in the inferior-python repl and in regular buffers.

Completion mostly works but hangs in some cases. Seems semi-random when to me.. Last (reproducible) case was `utilities.show_histogram(hsv[:,:,0], [0], playground_mask-1|)` where playground_mask and hsv are numpy arrays. I don't have to press tab to trigger the bug - probably because I have autocomplete on.

**Comment by mhaffner** [comment]
I'm having a similar issue but I'm not sure it's related to autocomplete. It seems somewhat dictated by how much text is in the `python` buffer (I get the same result using `ipython`). For instance, if I execute the following

`import pandas as pd

df = pd.DataFrame([[1, 2], [3, 4]], columns=['column_a', 'column_b'])

for i in range(1,100000):
    print('Spacemacs'*10)
`

and then type `df['` into the `python` buffer, it hangs somewhat. However, this problem is way worse when using my actual data set which is a pandas dataframe created from a 188kb .csv. If I try something like: 

`import pandas as pd

df = pd.read_csv('langs.csv')
` 
and type `df['`, there is no noticeable hang and I can complete the statement `df['languages'][3]` just fine. If I use 

`import pandas as pd

df = pd.read_csv('langs.csv')

for i in df.iterrows():
    print(i)
`
the `python` buffer is virtually unusable for viewing specific columns/rows of a dataframe. This is really interesting since my first example produces much more text.

**Comment by logc** [comment]
I have also had the same problem as described in this issue. A solution that seems to work is in this [Emacs Stack Exchange answer](https://emacs.stackexchange.com/a/24572):

> IPython 5 has a new terminal interface, which is not compatible with Emacs' inferior shells. To fix it, add the --simple-prompt flag to the IPython command:

    (setq python-shell-interpreter "ipython"
        python-shell-interpreter-args "--simple-prompt -i")

> From the documentation:

>> The new interface is not compatible with Emacs ‘inferior-shell’ feature. To continue using this, add the --simple-prompt flag to the command Emacs runs. This flag disables most IPython features, relying on Emacs to provide things like tab completion.

> Reference: http://ipython.readthedocs.io/en/stable/whatsnew/version5.html#id1

On top of that, I disabled company-mode on Python inferior processes:

    (add-hook 'inferior-python-mode-hook
            (lambda ()
              (setq company-mode nil)))

Both code snippets go into `user-config` within `.spacemacs`.

**Comment by vv111y** [comment]
@logc I think you got it. So far so good. I'm working in python next couple days. I'll post here how it goes.

**Comment by NightMachinary** [comment]
@logc Mine was hanging basically on startup, and your ipython flag fixed it. I suggest adding this to the Python layer.

**Comment by syl20bnr** [comment]
PR welcome :-)

**Comment by NightMachinary** [comment]
@syl20bnr Unfortunately my other PR has not been closed yet, and I am not very familiar with git; How can I send another PR? If I create a new branch from my current PR branch, the new PR will basically have the old one embedded, and if I branch from the develop branch, I won't have both of my changes available to myself.

**Comment by ajholyoake** [comment]
This appears to be in the python layer already (see spacemacs//python-setup-shell in funcs.el)
