### ISSUE TITLE
Eldoc hint in python mode is shown for very short time

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#5564]
#### Description
The eldoc hint (in python mode) which is shown in the echo area lasts for a very short time, making it unhelpful!

#### Reproduction guide
- Start Emacs with python layer enabled
- Open python file and navigate cursor to a method.
![python-eldoc](https://cloud.githubusercontent.com/assets/542810/13950410/cca45f5c-f050-11e5-8f05-db53d420b0b1.gif)

*Observed behaviour:*
Hint doesn't stay for long time

*Expected behaviour:*
Hint should stay till the cursor is in region where hint can be shown

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. f801cee)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip nil auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/" :disabled-for org erc)
 semantic better-defaults emacs-lisp
 (git :variables git-gutter-use-fringe t git-magit-status-fullscreen nil)
 github markdown yaml shell
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary t)
 syntax-checking
 (elfeed :variables rmh-elfeed-org-files
         (list "~/.emacs.d/private/elfeed.org"))
 lua python ruby ruby-on-rails
 (clojure :variables clojure-enable-fancify-symbols t)
 go shell-scripts html javascript dockerfile
 (eyebrowse :variables eyebrowse-display-help nil)
 spacemacs-layouts window-purpose
 (mu4e :variables mu4e-installation-path "/usr/local/share/emacs/site-lisp/mu4e/" mu4e-enable-mode-line t mu4e-enable-notifications t)
 nix-mu4e gnus colors deft finance
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 (version-control :variables version-control-diff-tool 'diff-hl)
 ansible emoji ranger prodigy osx typography
 (theming :variables theming-headings-inherit-from-default 'all theming-headings-same-size 'all theming-headings-bold 'all)
 org command-log erc pdf-tools
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t))
```

**Comment by cpaulik** [comment]
My first guess would be that this is an upstream issue of `anaconda-mode` or even `eldoc` itself. Have you tried this in a vanilla emacs with just anaconda mode installed to make sure it is an spacemacs issue?

**Comment by NJBS** [comment]
I had this exact issue a while ago and updating my packages made it disappear, could you try that?

**Comment by nixmaniack** [comment]
@cpaulik I tried in vanilla emacs, it works as expected.
![python-eldoc-vanilla](https://cloud.githubusercontent.com/assets/542810/13958587/a36462ec-f076-11e5-8514-2e17a76b9828.gif)

@NJBS I did update packages, still the same issue.

**Comment by cpaulik** [comment]
@nixmaniack Thanks. I'll try to look into it.

**Comment by cpaulik** [comment]
Disabling semantic mode solves this for me. I'll have to see if we can make them work together or if this is a upstream problem

**Comment by nixmaniack** [comment]
@cpaulik Indeed, disabling semantic solves the issue. Thanks for the workaround for now. But it'd be nice to make them work together as semantic enhances imenu for jumping around. 

Just to add more information, other modes(emacs-lisp, ruby, clojure) work as expected even with semantic.

**Comment by proofit404** [comment]
@nixmaniack can you explain what makes semantic imenu superior to helm-imenu in python mode?

**Comment by proofit404** [comment]
@cpaulik Something definitely cleanups echo area. I suspect `semantic-idle-summary-refresh-echo-area`.  Does disabling `global-semantic-idle-summary-mode` changes something?

**Comment by cpaulik** [comment]
@proofit404 Thanks for helping out. disabling `global-semantic-idle-summary-mode` or `semantic-idle-summary-mode` also solves the problem. So I'll make a PR disabling this mode for Python since the anaconda-eldoc seems more useful. 

@nixmaniack I seems that `idle-summary-mode` is not working in clojure and ruby so they don't have problems with their external eldoc function.

**Comment by nixmaniack** [comment]
> can you explain what makes semantic imenu superior to helm-imenu in python mode?

I don't think I meant helm-imenu is superior than semantic imenu. I meant, semantic helm-imenu is better than normal imenu. 

Apart from visual aesthetics in helm-imenu, we get goodies of helm (I use follow mode a lot) and with semantic it gives more parsed data to jump around. 

 with semantic
<img width="1280" alt="screenshot 2016-03-26 00 07 50" src="https://cloud.githubusercontent.com/assets/542810/14051303/e876582c-f2e7-11e5-868d-97e687c6b938.png">

without semantic
<img width="1280" alt="screenshot 2016-03-26 00 08 13" src="https://cloud.githubusercontent.com/assets/542810/14051374/5900f11a-f2e8-11e5-9474-90d4bf82b9f0.png">


@proofit404 @cpaulik Thanks for helping out here.

**Comment by IGJoshua** [comment]
I've found the same error in other modes as well. Really any mode which uses both eldoc and semantic. My personal setup uses both eldoc and semantic while coding in C. The frustrating thing is that simply disabling either one removes functionality, as eldoc has the ability to show things like maco definitions and type definitions (if they're on the appropriate line), while if I disable semantic then I lose the ability to recognize functions in some cases, and lose the ability to see the initial values and types of variables under the point.

This has been very frustrating for me to deal with. Is there any way that I can make it so that the semantic idle display function simply won't display when it has nothing to show? That seems like the most effective way to ensure that it won't clear the minibuffer when it has information that I want to see.
