### ISSUE TITLE
Creating a new workspace should clone the current one

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#5566]
Instead of opening the home buffer (which breaks `SPC p f` so it breaks to pace of edition).

## Use case

*Setup:*
- I'm in a layout of a project (`SPC p l`)
- I open a python buffer
- I want to isolate the python buffer and the associated REPL

*What I expect:*

Ideally and naturally I just want to:
- `SPC l w 2`
- `, s i`

*Currently*
- `SPC l w 2`
- `SPC b b` and select the python buffer back
- `, s i`

Maybe that in any case the home buffer introduces an unwanting indirection, so let's try to guess a better workspace state from the start.

**Comment by d12frosted** [comment]
Totally agree. Since we already befriended layouts and workspaces this is expected flow in my opinion. At least, that's what I expect when I open new workspace.

**Comment by tuhdo** [comment]
What you described is what `eyebrowse` does by default. `eyebrowse-new-workspace` is the variable to set, and `nil` to clone current workspace. Since we have layout now, I agree with this change. However, it might be confusing for new users as they won't notice whether a new workspace is created or not, since they're likely to ignore the numbers at the lower left corner. Hence, we should add a function to print something like "Workspace 2 created" in the minibuffer. This can be achived with `eyebrowse-post-window-switch-hook`.

**Comment by syl20bnr** [comment]
Thank you @tuhdo, this is fixed in develop

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
