### ISSUE TITLE
Consider adding automatic language mode installation? 

### ISSUE THREAD

**Issue by moliss** [syl20bnr/spacemacs#559]
One of the things holding me back from using spacemacs full time is the lack of automated installation of major modes for new languages not built in yet. Would this be a bad idea to add? Or has it been added already? It's a feature in prelude.

**Comment by m3hr** [comment]
I can help work on this if you'd like.

**Comment by syl20bnr** [comment]
I won't provide such feature. Spacemacs is designed to install and use only what you explicitly reference in your `.spacemacs` file. If you want the support for a language you can see if it is supported with `SPC f e h` and then add it to your `.spacemacs`.

For now when you add a layer to your `dotspacemac-configuration-layers` variable you have to restart spacemacs but there will be support for installing it without restarting it. It will even be possible to install it from `helm-spacemacs` (`SPC f e h`) but to make it persistent it will be necessary to add it explicitly to your dotfile.

Generally I'm for explicit declaration since it gives more control and tends to make debugging easier.

**Comment by syl20bnr** [comment]
Followup on this. I'm considering it. It can be a nice feature to quickly look at a file in another language without actually installing a layer.

**Comment by m3hr** [comment]
This makes me happy haha. How about some sort of special personal configuration layer that holds odds and ends like this? The documentation compares config layers to Vundle but while Vundle is less organized, it seems like less work? I don't know, the organization as it is is very clean. Just a thought.

**Comment by Compro-Prasad** [comment]
Any progress on this @syl20bnr ?

**Comment by Miciah** [comment]
Does `dotspacemacs-enable-lazy-installation` provide the requested functionality? Lazy installation of layers appears to have been added since this issue was opened, but it is not clear to me whether "installation of major modes for new languages not built in yet" means installing Spacemacs layers that are not enabled by default or installing packages for which layers have not yet been defined.

**Comment by fiveNinePlusR** [comment]
I think this is built in now to spacemacs and can be closed unless the original author of the issue says that it's not what they mean.

**Comment by Compro-Prasad** [comment]
@sdwolfz This can be closed. Spacemacs offers to install a layer according the extension of a file.
