### ISSUE TITLE
next error keybinding wrong

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#567]
the <kbd>SPC e n</kbd> keybinding is bound to ``` 'next-error``` in  https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/keybindings.el#L75

This is changed into ```'spacemacs/next-error``` in line https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L1024 but this keybinding is not in effect for me.

I changed the keybinding in keybindings.el and it worked for me. What is the preferred way of doing this? Happy to submit a PR as soon as I know if changing keybindings.el and removing from packages.el is fine.

**Comment by syl20bnr** [comment]
If I'm not mistaken the `spacemacs/...` variant is for dispatch the next error request to `flycheck` or raw `next-error` so the expected behavior is that `spacemacs/...` overrides `keybindings.el` when `flycheck` is used. You can put a condition in `keybindings.el` to check for the presence of `flycheck` like the one for `fancy-narrow` (https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/keybindings.el#L122)

**Comment by cpaulik** [comment]
Yes this seems to work.

Maybe I'm misunderstanding, but what is the reason for checking for the presence of ```flycheck``` in ```keybinding.el``` and changing the keybinding based on it, when ```spacemacs/next-error``` performs this check anyway?

**Comment by syl20bnr** [comment]
Good point, we can move the  `spacemacs/next-error` functions to `funcs.el` and bind them directly in `keybindings.el` then.

**Comment by syl20bnr** [comment]
Fixed by #580
