### ISSUE TITLE
Neotree does not work with  layouts

### ISSUE THREAD

**Issue by drumaddict** [syl20bnr/spacemacs#5696]
#### Description
Neotree completely messes up layouts.

#### Reproduction guide
* Start Emacs
* Create some project layouts with `SPC p l`
* Switch to a random project layout and open Neotree with `SPC p t`. (Neotree is in sync with projectile : `(setq projectile-switch-project-action 'neotree-projectile-action)`)
* Try to switch to another layout 

*Observed behaviour:*
 Windows disappear,with only Neotree left.
 Error messages:
 `Cannot Resize root window of a frame` or `Window is dedicated to *Neotree*`

*Expected behaviour:*
Switch layers with Neotree adapting to each project layout.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.16
- Spacemacs branch: master (rev. cf8563b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
auto-completion
     better-defaults
     emacs-lisp
     git
     markdown
     typescript
     org
     version-control
     ruby-on-rails
     themes-megapack
     (ruby :variables
           ruby-test-runner 'rspec
           ruby-enable-enh-ruby-mode t)
     (ranger :variables
             ranger-show-preview t)
     )
```

**Comment by StreakyCobra** [comment]
Closely related to #5682

**Comment by nwolfe** [comment]
I absolutely hate the NeoTree integration in Spacemacs -- it's the worst part of the Spacemacs experience in my mind.  And it's unfortunate that it's one of the first things newcomers tend to reach for, because it's so shoddy.

It constantly ends up being doubled, and I have 2 side-by-side trees that both suck.
It constantly screws up perspectives/workspaces.
It constantly screws up window sizes when other things open (open the neotree, and then open magit status, and the status buffer is narrower than it should be).

</vent>

So yes please, anything we can do to improve any of this would go a long way in my mind. 👍 😄

**Comment by bmag** [comment]
> Observed behaviour:
Windows disappear,with only Neotree left.
Error messages:
Cannot Resize root window of a frame or Window is dedicated to *Neotree*

---

> It constantly ends up being doubled, and I have 2 side-by-side trees that both suck.
It constantly screws up perspectives/workspaces.

@drumaddict @nwolfe these two changes together should take care of that: #5725 (layers/+spacemacs/spacemacs-ui-visual/packages.el) and https://github.com/syl20bnr/persp-mode.el/pull/1/ (our fork of persp-mode).

> Expected behaviour:
Switch layers with Neotree adapting to each project layout.

The changes prevent Neotree from messing up the windows, although they don't automatically refresh the *contents* of Neotree's buffer (if that's what you meant).

> It constantly screws up window sizes when other things open (open the neotree, and then open magit status, and the status buffer is narrower than it should be).

Spacemacs has some code that automatically balances the windows (resizes the windows so they have equal width). I suspect that Neotree prevents its window from being resized, and that's why the status buffer is narrower than it should (only the status window is resized instead of all windows). I have no idea what causes this automatic balancing of windows, I tried to locate it several times and failed. :unamused:
