### ISSUE TITLE
ranger closes frame after file selection

### ISSUE THREAD

**Issue by pekhee** [syl20bnr/spacemacs#5741]
### Problem

After selecting a file with ranger first major mode gets loaded then frame gets closed.
### To Reproduce
1. Run emacs daemon
   
   emacs --daemon
2. Create an emacs frame and pass current dir
   
   emacsclient -c .
3. Select a file in `dired`
4. Press `SPC a r`
5. Select another file.
6. Small delay
7. Frame closes
### Notes
- Not passing a directory works correctly.
- Creating another emacs instance and passing a directory works.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.17
- Spacemacs branch: develop (rev. 5c7e0b6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults markdown org
                 (shell :variables shell-default-shell 'multi-term shell-default-term-shell "/usr/bin/zsh" shell-default-height 10 shell-default-position 'bottom)
                 spell-checking syntax-checking themes-megapack git github ruby javascript shell-scripts haskell rust emacs-lisp yaml html markdown dockerfile evil-cleverparens evil-snipe evil-commentary unimpaired vinegar dash vagrant ranger colors ibuffer spacemacs-layouts eyebrowse)
```

**Comment by ralesi** [comment]
@pekhee, we are talking use in terminal, correct?

**Comment by nicu-chiciuc** [comment]
It seems like I have the same issue, although it's not clear when it happens. I use the GUI version of emacs and 70% percent of the time, when selecting a file from ranger, it will close one of the open windows.

**Comment by stagmoose** [comment]
Same problem here. Use spacemacs gui.

**Comment by stagmoose** [comment]
@lebensterben 

https://github.com/ralesi/ranger.el#selected-file-actions says `wf` exit ranger and open selected file in new frame. If I enter ranger and press `wf`, the original frame will be closed (I guess that's because the original frame become ranger frame, and the frame is closed after pressing `wf`).

btw, spacemacs doc say ranger will be `SPC a r` after enabled, but mine is `SPC a t r r` (really weird and verbose haha)

here's my info
```
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2.50
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 42b6ff3f0)
- Graphic display: t
- Running in daemon: spacemacs
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((html :variables web-fmt-tool 'web-beautify css-enable-lsp t html-enable-lsp t)
 auto-completion
 (clojure :variables cider-repl-display-help-banner nil cider-pprint-fn 'fipp clojure-indent-style 'align-arguments clojure-align-forms-automatically t clojure-toplevel-inside-comment-form t cider-result-overlay-position 'at-point cider-overlays-use-font-lock t cider-repl-buffer-size-limit 100 clojure-enable-clj-refactor t)
 emacs-lisp git helm ranger
 (lsp :variables lsp-enable-on-type-formatting t lsp-enable-indentation t lsp-enable-snippet t lsp-enable-symbol-highlighting t lsp-modeline-diagnostics-enable t lsp-ui-doc-show-with-cursor nil lsp-ui-doc-include-signature t lsp-ui-doc-alignment 'window lsp-ui-sideline-enable nil lsp-ui-sideline-show-code-actions nil lsp-lens-enable t treemacs-space-between-root-nodes nil lsp-file-watch-threshold 10000 lsp-log-io nil)
 (shell :variables shell-default-shell 'vterm shell-default-height 30 shell-default-position 'bottom)
 multiple-cursors
 '(ranger :variables ranger-show-preview t)
 themes-megapack treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON PDUMPER GMP


#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

```
