### ISSUE TITLE
Spacemacs-layouts - Special buffers are not added to the current layout

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#5776]
### Repro steps

_Need python layer enabled and installed_
- Start Emacs
- `SPC l 2 y foo RET`
- `SPC f J py RET`
- `SPC m ' RET y`
- `ESC SPC b b`
### Observed behavior

Only buffers `*scratch*` and `xxxx.py` are listed.
### Expected behavior

The REPL buffer should be listed as well.
### Work around

`SPC b a` to add the REPL manually to the layout.

**Comment by cpaulik** [comment]
Could this also the reason why e.g. the `*pytest*` buffer can show up in any layout if it goes into debug mode?

**Comment by syl20bnr** [comment]
I don't know if it shares the same cause but we can add this unexpected behaviour in this issue.

**Comment by d12frosted** [comment]
AFAIU, it's already in master, no? 😸

**Comment by d12frosted** [comment]
Closing this one for now. Let me know if it's not perfect yet and I'll reopen (or reopen yourself) 😸

**Comment by cpaulik** [comment]
This is probably not fixed. Any new `*python*` or `*pytest*` buffer is not added to the current perspective. I'm on latest develop fea919c

**Comment by braham-snyder** [comment]
Not looking fixed for me on develop either.

I think we can easily improve the default behavior quite a bit. Currently, for example, in any non-default layout, after pressing `<return>` on a magit diff to visit the associated file, `previous-buffer` does not return to that magit diff (even after adding `"\\*magit"` to the useful buffers regexp list).

Instead, at the moment, I've just set `persp-add-buffer-on-after-change-major-mode` to `t`--that's worked well for me so far, but unsure if there's a better solution.

For reference, here's what looks like a similar but slightly less general issue (closed "for inactivity") with some discussion that's probably applicable: https://github.com/syl20bnr/spacemacs/issues/4956

Perhaps one of these two issues should be reopened?

**Comment by ngoonee** [comment]
Agree that https://github.com/syl20bnr/spacemacs/issues/4956 or this should be re-opened. My current bug-bear is that opening terms (SPC-') when in a layout doesn't add the term to the layout, which is basically what's being discussed in this linked issue (and would be solved with a proper solution to this issue).

**Comment by d12frosted** [comment]
@bmag do you have any ideas?

**Comment by bmag** [comment]
@d12frosted I'm not familiar enough with persp-mode to tackle this. CestDiego might know, but I don't think he contributes to Spacemacs anymore (haven't seen any issue/PR/comment by him for a long time). We're definitely lacking a person with strong Spacemacs and perps-mode knowledge.

**Comment by d12frosted** [comment]
I see. Thanks for the input 😸 

It's a shame that he is not around :(

**Comment by dsedivec** [comment]
This may be kind of a big hammer, but to get it so that I could `C-x b` back to my `*magit: ...` buffer after e.g. hitting enter on a hunk, I did `(setq persp-add-buffer-on-after-change-major-mode 'free)`.  This apparently adds a buffer to your current perspective if it's not already in another perspective.  @braham-snyder also used `t` for the value, as above, which works by always adding a buffer to the current layout after its major mode is changed (or so I expect).

This variable can also be set to a function.  Finally, there is also `persp-add-buffer-on-after-change-major-mode-filter-functions`.  The behavior of these "filter functions" is someone more complex than I'm prepared to explain right here, use the source. :)

Going to try out `'free` for a while and see how that goes.

**Comment by deb0ch** [comment]
I believe this issue is fixed and can be closed ?
