### ISSUE TITLE
evil-shift-width is broken in python, something keeps setting it to 2

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#5793]
#### Description
`evil-shift-width` is 2 in python, even if you set it otherwise in `user-config`.

#### Reproduction guide
In `user-config`:

```elisp
  ;; Python hooks
  (add-hook 'python-mode-hook
            (lambda ()
              ;; Enable fill column indicator
              (fci-mode t)
              ;; Turn on line numbering
              (linum-mode t)
              ;; Set tab-width to 4
              (tab-width 4)
              ;; Set evil-shift-width to 4
              (evil-shift-width 4)
              ;; Enable automatic line wrapping at fill column
              (auto-fill-mode t)))
```

*Observed behaviour:*
`evil-shift-width` is set to 2 locally in python mode.  

*Expected behaviour:*
It should be 4.

#### System Info
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.105.18
- Spacemacs branch: develop (rev. 5ee970f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql nginx unscroll auto-completion xkcd emacs-lisp git yaml github javascript html markdown extra-langs python ruby org osx python django syntax-checking spell-checking lua colors spacemacs-layouts vimscript spacemacs-helm
     (version-control :variables version-control-diff-tool 'diff-hl)
     (c-c   :variables c-c  -enable-clang-support t)
     (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by synic** [comment]
Looks like I did the config wrong, should be:


```elisp
  ;; Python hooks
  (add-hook 'python-mode-hook
            (lambda ()
              ;; Enable fill column indicator
              (fci-mode t)
              ;; Turn on line numbering
              (linum-mode t)
              ;; Set tab-width to 4
              (setq tab-width 4)
              ;; Set evil-shift-width to 4
              (setq evil-shift-width 4)
              ;; Enable automatic line wrapping at fill column
              (auto-fill-mode t)))
```

However, it still seems like something is broken.  The spacemacs code uses `spacemacs--indent-variable-alist` to decide what `evil-shift-width` to use for a mode.  That contains the following:

```
(((awk-mode c-mode c++-mode java-mode groovy-mode idl-mode java-mode objc-mode
  pike-mode) . c-basic-offset) (python-mode . python-indent-offset) (cmake-mode
  . cmake-tab-width) (coffee-mode . coffee-tab-width) (cperl-mode .
  cperl-indent-level) (css-mode . css-indent-offset) (elixir-mode .
  elixir-smie-indent-basic) ((emacs-lisp-mode lisp-mode) . lisp-indent-offset)
  (enh-ruby-mode . enh-ruby-indent-level) (erlang-mode . erlang-indent-level)
  ((js-mode json-mode) . js-indent-level) (js2-mode . js2-basic-offset)
  (js3-mode . js3-indent-level) (latex-mode LaTeX-indent-level tex-indent-basic)
  (livescript-mode . livescript-tab-width) (mustache-mode .
  mustache-basic-offset) (nxml-mode . nxml-child-indent) (perl-mode .
  perl-indent-level) (puppet-mode . puppet-indent-level) (ruby-mode .
  ruby-indent-level) (rust-mode . rust-indent-offset) (scala-mode .
  scala-indent:step) (sgml-mode . sgml-basic-offset) (sh-mode . sh-basic-offset)
  (web-mode . web-mode-markup-indent-offset) (yaml-mode . yaml-indent-offset))
```

`python-mode` is being set to `python-indent-offset`, however, `python-indent-offset` is set to 4, but `evil-shift-width` gets set to 2 anyway.

**Comment by StreakyCobra** [comment]
The change in `user-config` is probably not working because `evil-shift-width` is [set at the end of `after-change-major-mode-hook`](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+distribution/spacemacs-bootstrap/packages.el#L108), and as the documentation says:

> Normal hook run at the very end of major mode functions.

So it's run after your hook in `python-mode-hook` if I understand correctly.

For the value being 2: with my setup (I don't customize this at all), if I open a python buffer, I get:

> Its value is 4
Local in buffer 14-205732.py; global value is 2

So the value is 4 as expected here. Can you try with a stock `.spacemacs` (just enabling python) to see if it comes from your config?

Ping @TheBB as he has more experience than me in indentation.

**Comment by synic** [comment]
It does NOT happen in vanilla spacemacs, though I don't know what it would be in my config.

https://github.com/synic/dotspacemacs/blob/master/init.el

**Comment by StreakyCobra** [comment]
First try to remove the custom set variables/faces at the end to see if it still happen.

If yes you can try to remove everything inside `user-config` and see if the problem is still here. If it still happen remove everything inside `user-init`. When you have found which one of these functions are responsible, the better is probably to try "bisecting" what is the guilty config: first disable the first half of the incriminated lines and test. If it happens, it means the problem is in the rest of the line, if not the problem come from commented lines. Reproduce the same with the part containing the issue and so on until the problem is identified.

**Comment by dsdshcym** [comment]
I have the same problem here.

I think there might be something wrong with `spacemacs//set-evil-shift-width`. Since it's added recently and it obviously changes `evil-shift-width`.

**Comment by StreakyCobra** [comment]
CC @TheBB

**Comment by TheBB** [comment]
Can I see a file where we get the wrong indentation? I can't repro this on any of my python files. I always get `evil-shift-width` equal to `python-indent-offset`.

If you want it to not be equal, but have `evil-shift-width` equal to 4 in files with indentation 2 then I must ask why. You could of course remove the `python-mode` entry from `spacemacs--indent-variable-alist`.

**Comment by synic** [comment]
Closing, I can't reproduce now.
