### ISSUE TITLE
Spacemacs on Android (w/o root) -- installation somehow fails

### ISSUE THREAD

**Issue by fivethousand** [syl20bnr/spacemacs#5800]
I was trying to get Spacemacs running on Android (w/o root).

Here's how far I got:
1. Play Store -> Emacs App
The emacs app you find in the play store is broken and old.
2. Gnuroot
Also didn't work for me. I don't remember where the installation process failed, but IIRC I did not even manage to get emacs and the repository cloned.
2. Termux.
Install, then: apt update && apt upgrade && apt install git emacs && git clone .... && emacs
Finally with Termux, everything _seems_ to be fine. Spacemacs goes through the package installation flawlessly, but then: 
"Symbol's function definition is void: projectile-mode"
The package is installed (in .emacs/elpa/), and it does work: M-x projectile-mode -> enabled. Something seems to be wrong in the startup script, so I disabled projects it in the spacemacs buffer just to find out that yet another package does not work:
"Symbol's function definition is void: page-break-lines-mode"
It is also installed. M-x page-break-lines-mode -> enabled.

You could now conclude that for some reason packages can not be installed properly. However, evil does work and the packages I tried to install manually also did. Also, manual invocation with M-x did work.

I tried debugging with --debug-init, but that did not give any further insight.
After restarting emacs, M-x projectile-mode/page-break-lines-mode do not work any more. At the same time, M-x evil-mode does work. What's the difference there between evil-mode and the other packages?

After I added (setq debug-on-error t) in init.el, the line with (projectile-mode) was shown. Nothing else.

It looks similar to https://github.com/syl20bnr/spacemacs/issues/4227 but the home directory is set properly and everything is in $HOME/.emacs.d/ 

Emacs: 25.0.92
Spacemacs: 0.105.18 (master)

Does anyone have any suggestions?

**Comment by bmag** [comment]
I'm not sure what's the problem, but it seems related to a few older issues. See #2939 #4229 #5477, and you may want to search issues/PRs with the keywords "projectile-mode void" or "page-break-lines-mode".

From what I gather, disabling projects in the home buffer (aka spacemacs buffer) triggers the page-break-lines-mode bug. It indeed seems to be a bug in the loading order. It may have been fixed in develop by #5477.

As for the projectile-mode bug, I don't know. Sounds like projectile-mode is called before the autoloads are defined. I don't know why it is so, since it doesn't happen to most users.

You can try the following:
- 1. don't disable projects in the home buffer
- 2. after doing 1, delete projectile's directory `.emacs.d/elpa/projectile-*/` so spacemacs reinstalls it on next startup, just in case there was an error during installation. Restart spacemacs twice (1st time to reinstall, 2nd time to see if projectile is loaded properly).
- 3. if 2 doesn't work, try the develop branch, in case the bug has been fixed there.
- 4. if 3 doesn't work (or if you'd rather stay in master branch), go back to master, disable projects in the home buffer, and apply the patch to `core-spacemacs-buffer.el` given in https://github.com/syl20bnr/spacemacs/issues/4229#issue-123042989.  This is only a work-around and isn't a good long-term solution.

Can you provide the output of `SPC h d s` (if it works on your setup), explain how you "disabled projects in the spacemacs buffer", and check if there's anything relevant in the `*Messages*` buffer?

cc @synic @emacs18

**Comment by fivethousand** [comment]
#### System Info
- OS: gnu/linux
- Emacs: 25.0.92
- Spacemacs: 0.105.18
- Spacemacs branch: master (rev. c8c4ff3)
- Graphics display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```
elisp
(emacs-list)
```

I think I found out what goes wrong here, but I don't know enough about spacemacs to find out why this happens and how to fix it:

Unfortunately, none of the above worked. Spacemacs installed projectile after a restart, but after restarting, M-x projectile-mode/page-break-lines-mode do not work again. Looks like package-initialize is not run, because if I do that manually, M-x projectile-mode/page-break-lines-mode work even after a restart. 

I forgot to mention that there is always an additional error message in a second window "Wrong type argument: string, nil". I don't see any further information, though. *Messages* does not contain any errors (besides not being able to load Source Code Pro).

My guess is: Something fails before package-initialize gets called. After the error the script stops. For example which-key is also not enabled, while evil-mode seems to be enabled before.

Is there another way to debug the startup script to get more information *where* it actually fails?

**Comment by fivethousand** [comment]
Whoohooo. I've got it!

#### Installing Spacemacs on Android (no root required!)
1. Install Termux from Google Play Store
2. apt update && apt upgrade && apt install git emacs && git clone https://github.com/syl20bnr/spacemacs .emacs.d && export SHELL=data/data/com.termux/files/usr/bin/bash && emacs

**Comment by cpaulik** [comment]
@fivethousand Does git work for you? I've gotten an error about `git difftool` being broken when e.g. doing `SPC f e d`.

**Comment by fivethousand** [comment]
I didn't check git in depth, but I have the git layer enabled and I don't get any errors on SPC f e d . Weird. I have to mention though that there is a remaining error:

> error in process entinel: async-handle-result: End of file during parsing: /data/data/com.termux/files/usr/share/emacs/25.0.92/lisp/loadup.el

Does git diff work on the command line?

**Comment by d12frosted** [comment]
Could you please try with latest release of Emacs and Spacemacs and all packages? 😸

**Comment by fivethousand** [comment]
**Installation without .spacemacs, vim/full spacemacs/helm selected**
A couple of warnings, no errors.


**Installation with my .spacemacs (with org, semantic layers etc.):**
Still "error in process sentinel...end of file during parsing..." during/after installation, in addition 

`error running timer 'semantic-idle-scheduler-function': (error "No support found to parse buffer \"org-loaddefs.el<org-plus-contrib-20161102>\"`

and
`Save Error: "No support found to parse buffer \"org-loaddefs.el<org-plus-contrib-20161102>\"": /data/data/com.termux/files/home/.emacs.d/.cache/semanticdb/!data!data!com.termux!files!home!.emacs.d!elpa!.emacs.d!elpa!org-20161102!semantic.cache
`
After restarting emacs, I get

`Error in dotspacemacs/user-config: Symbol's function definition is void: orgit-link-set-parameters.
`
 However, my .spacemacs does not contain orgit-link-set-parameters.

**Comment by fivethousand** [comment]
IMHO this should still be marked as a bug....
