### ISSUE TITLE
Just a question, how could I set the default page to "scratch* buffer on startup?

### ISSUE THREAD

**Issue by liuchong** [syl20bnr/spacemacs#5803]
1. how could I set the default page to "scratch* buffer on startup?
2. Also could it do not show the "[?] [Homepage] [Documentation] ... " lines or the whole buffer?

Thanks!

**Comment by triklsbg** [comment]
1. Customize the variable 'initial-buffer-choice' described in:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Startup-Summary.html

**Comment by liuchong** [comment]
thanks but which segment should I put it into in the dotspacemace file?

**Comment by liuchong** [comment]
anyone knows that, or not supported for now?

**Comment by ninrod** [comment]
this does not work: putting `(setq initial-buffer-choice t)` on dotspacemacs/userconfig section does nothing. I think it is a bug.

**Comment by d12frosted** [comment]
`initial-buffer-choice` has no effect since `spacemacs` buffer is manually created and switched to. You could add `(switch-to-buffer "*scratch*")` to `dotspacemacs/user-config`. It will show `spacemacs` buffer at first (with all the installation and loading process) and the switch just to the scratch buffer. Note that you can configure scratch buffer mode by altering value of `dotspacemacs-scratch-mode`. 

I don't know how to avoid showing `spacemacs` buffer in a good way, but you could always redefine `spacemacs-buffer/goto-buffer` in `dotspacemacs/user-init` function.

```elisp
(defun spacemacs-buffer/goto-buffer ()
    (interactive))
```

This has several drawbacks. First of all, it's too intrusive. And no one can guarantee that this option will be possible in the future. Secondly, you loose ability to show Spacemacs buffer at all (e. g. by using `SPC b h`). 

But it's possible to add configuration variable that will control behaviour of `spacemacs/home` function. If no one sends PR for this till Sunday - I'll try to spend some time on this problem.

**Comment by TheBB** [comment]
Closing this in favour of https://github.com/syl20bnr/spacemacs/issues/6899 which is a bit more to the point.
