### ISSUE TITLE
Spacemacs hangs with "making tags completation table" message

### ISSUE THREAD

**Issue by emad-elsaid** [syl20bnr/spacemacs#5889]
#### Description

I have the same problem as #4747, installed spacemacs working fine for couple hours, half an hour then and it was suffering from the same referenced issue.

I'm working on rails project, not a small one (several thousand files), while editing a controller it hang and try to generate TAGS, I have Autocomplete layer enabled.
this is my .spacemacs file 
https://gist.github.com/blazeeboy/5de9e9bf0847f4054b560fe96f50ae54

sometimes it gets back to work when i press C-g for long time, and sometimes it doesn't, also when I was working on spec files it didn't happen, the time I started working on controllers it stopped working.
#### Reproduction guide
- Start Emacs
- Open a ruby on rails project
- Open a controller
- enter insert mode `i` 
- start typing
- it hangs with message "...generating TAGS"

_Observed behaviour:_
- pressing `Ctrl+g` solves the problem in most cases

_Expected behaviour:_
to type normally without hanging, that's obvious 😃 
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 5f26b82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t)
 better-defaults emacs-lisp git markdown javascript osx html shell-scripts sql yaml github eyebrowse
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (ruby :variables ruby-version-manager 'rvm)
 ruby-on-rails
 (syntax-checking :variables syntax-checking-enable-tooltips nil))
```

EDIT: [@StreakyCobra] Correct referenced PR number (reason: Wrong one was linked)

**Comment by jefflasslett** [comment]
This is real.  I've just disabled auto-completion to prevent it.

#### Description
Whilst editing code emacs pauses.  I think it is in the process of doing auto-completion of the identifier being edited.

#### Reproduction guide
- Start Emacs
- Open a file.  I am working on a rails project and so am editing ruby code.
- Change a function name.  Your goal is to get auto-completion to offer up choices.

*Observed behaviour:*
- Cursor freezes and status message is "Making tags completion table for ..."
- Ctrl-g 3 times kills the process and editing can resume.  But it will freeze up again "making tags completion table ..." as soon as you type a bit more.


*Expected behaviour:*
No freezing.  Auto completion choices offered.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git markdown org dash yaml
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking version-control ruby-on-rails)
```






I've attached my .spacemacs (as spacemacs.txt) and my custom theme.  I install the theme locally as I haven't uploaded it to a package archive.  theme_package.zip just contains the tar file for the theme.

[spacemacs.txt](https://github.com/syl20bnr/spacemacs/files/534934/spacemacs.txt)

[theme_package.zip](https://github.com/syl20bnr/spacemacs/files/534936/theme_package.zip)
