### ISSUE TITLE
initial-scratch-message

### ISSUE THREAD

**Issue by rushpixy** [syl20bnr/spacemacs#5906]
hi,  `(setq initial-scratch-message "aaaa")` . put it in `dotspacemacs/user-config ()`.  Why it's not working?

**Comment by StreakyCobra** [comment]
It's because this has to be defined early enough to be used, in `user-init`, `user-config` being ran too late.

**But**, because of the way it's currently coded, https://github.com/syl20bnr/spacemacs/blob/develop/layers/+distribution/spacemacs-base/config.el#L163 is overriding it so it won't work without commenting this line for now.

**Comment by rushpixy** [comment]
if don't hamper upgrade of spacemacs. how achieve ?

**Comment by StreakyCobra** [comment]
You or someone else proposing a PR to fix it :-)

**Comment by CarlQLange** [comment]
I added a PR for this allowing config in your .spacemacs for this here: https://github.com/syl20bnr/spacemacs/pull/9588
