### ISSUE TITLE
gtags update fails

### ISSUE THREAD

**Issue by 3rd3** [syl20bnr/spacemacs#5911]
#### Description

When I save `.cpp` files I get a message `Failed: update TAGS`. I've searched the web, but couldn't find anything insightful.

Reproduction steps unknown.
#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((ibuffer :variables ibuffer-group-buffers-by nil)
 (ranger :variables ranger-ignored-extensions
         '("mkv" "iso" "mp4" "avi" "mp4" "mkv" "zip" "rar" "exe" "ps" "webm" "png" "jpg" "jpeg" "tif" "tiff" "ics" "dmg" "swf" "gz" "m4a")
         ranger-max-preview-size 4 ranger-cleanup-eagerly t)
 (latex :variables latex-enable-auto-fill t)
 org git github version-control finance extra-langs markdown emacs-lisp haskell html javascript ipython-notebook shell-scripts java
 (haskell :variables haskell-enable-ghc-mod-support nil haskell-enable-ghci-ng-support t haskell-enable-hindent-style "gibiansky" haskell-enable-shm-support nil)
 (c-c   :variables c-c  -enable-clang-support t)
 gtags
 (python :variables python-test-runner 'pytest)
 (clojure :variables clojure-enable-fancify-symbols t)
 (shell :variables shell-default-height 20 shell-default-position 'bottom shell-enable-smart-eshell t shell-default-shell 'eshell)
 evil-commentary)
```

**Comment by ZhengshuaiPENG** [comment]
I can confirm this. The same when I save cpp file, it prompts failed

**Comment by shashankmittal** [comment]
Same for Linux kernel project too on Ubuntu.

**Comment by deb0ch** [comment]
Same here.

**Comment by beta1440** [comment]
@3rd3 Just to be clear, did you create gtags in your project and then you get the error, or are you getting the error without using gtags?

**Comment by 3rd3** [comment]
I am sorry, this is too long ago and I don't remember anymore. Perhaps other people do.

**Comment by krixkrix** [comment]
Hmmm is this the bug I am seeing? I am testing the setup provided here:
https://tuhdo.github.io/c-ide.html.
The first time I run "_helm-gtags-dwim_" I am prompted to run gtags, I answer yes and select the parent directory. For GTAGSLABEL I choose _default_. The files GPATH, GRTAGS, GSYMS, GTAGS are created. And finding tags now works fine. 
But then, when I try to update the database with "_helm-gtags-update-tags_" I get the message: 
_Failed: update tags(2)_

Any help is appreciated.

**Comment by sdwolf** [comment]
If you have emacs installed from source, you might have overwritten `ctags` with the one provided by emacs.

Execute: `ctags --version`
If you see something like this you need to reinstall ctags:
```
ctags (GNU Emacs 26.0.50)
Copyright (C) 2017 Free Software Foundation, Inc.
This program is distributed under the terms in ETAGS.README
```

The way I work around this is by configuring emacs with the following command:
```
./configure CFLAGS='-O2 -g3' --program-transform-name='s/^ctags$/ctags.emacs/'
```

That way emacs installs it's ctags (which should probably be named `etags`) with a different name.

Hope this helps.

**Comment by krixkrix** [comment]
@sdwolf: Thanks for your input. This is probably not the right place for me to seek help, so I will limit myself to simply state that:
I have not installed emacs from source, just plain Ubuntu 16.04 repo packages. Emacs 24.5.1 and ctags claims to be: GNU Emacs 24.5.

**Comment by sdwolf** [comment]
If ctags displays `GNU Emacs 24.5.` then maybe it was created by the emacs package when you installed it. Try removing and installing the ctags package and check the version again.

Also, if that fails, you can install ctags from source with the following steps:
```
git clone https://github.com/universal-ctags/ctags.git
cd ctags
./autogen.sh
./configure
make
sudo make install
```

This is sure to overwrite your current ctags binary in `/usr/local/bin` or `/usr/bin`.

**Comment by SlightlyCyborg** [comment]
I installed ctags from source and am also getting this error

Failed: update tags(2)

**Comment by evorion** [comment]
I've just fixed this issue by installing exuberant-ctags on Devuan.

Before the installation of exuberant-ctags I was getting:

`Failed: update CTAGS(3)`

This was my ctags:

`ll /etc/alternatives/ctags
/etc/alternatives/ctags -> /usr/bin/ctags.emacs`

After the installation of exuberant-ctags and the error being fixed I have this:

`ll /etc/alternatives/ctags
/etc/alternatives/ctags -> /usr/bin/ctags-exuberant
ll /usr/bin/ctags*
/usr/bin/ctags -> /etc/alternatives/ctags
/usr/bin/ctags.emacs
/usr/bin/ctags-exuberant`

**Comment by evorion** [comment]
I've just found another very contorted way to get:  Failed: update TAGS(3)
I have .dir-locals.el for one of my C++ projects. Now, through a few hours of debugging, I've managed to figure out that on start of Emacs, Emacs checks for unsafe local variables and prompts you so that if you choose '!' these variables are written to ~/.emacs.d/.cache/.custom-settings

Upon this file being saved a save-hook is executed which ends up trying to update gtags for ~/.emacs.d/.cache/.custom-settings which is not going to work since GTAGS for that file has never been created. I've managed to confirm this bug by running gtags in the ~/.emacs.d/.cache folder which creates redundant gtags files but also makes the 'Failed: update TAGS(3)' message go away.

This is what Emacs was trying to run in the save-hook

`global --single-update /home/vlatko/.emacs.d/.cache/.custom-settings`

And the result was: Failed: update TAGS(3)   <--- This error message is generated by emacs, you won't see it in the command line

So what I did was:

```
cd /home/vlatko/.emacs.d/.cache/
gtags
```

And now the 'Failed: update TAGS(3)' message is gone when I run
```
global --single-update /home/vlatko/.emacs.d/.cache/.custom-settings
```
manually and also when Emacs runs this from it's save-hook.

Edit (2023.09.19.): I've just used the same method to fix the same error when working with python. helm-gtags-update-tags is the culprit. All you need to do is figure out where you need to create the tags.

Edit (2025.03.26): This helps on a project level in .dir-locals.el but also disables gtags updates completely for the entire project:

```
((nil .
   ((eval . (progn
              (remove-hook 'after-save-hook #'helm-gtags-update-tags t)
              )))))
```
