### ISSUE TITLE
Configuring indentation in react / javascript not working as intended

### ISSUE THREAD

**Issue by honkycat** [syl20bnr/spacemacs#5923]
#### Description

Configuring the react / javascript indentation levels doesn't work.

From gitter chat:

```
Below is result of SPC h d v web-mode-code-indent-offset:
web-mode-code-indent-offset is a variable defined in `web-mode.el'.
Its value is 4
Local in buffer App.js; global value is 2

  This variable is safe as a file local variable if its value
  satisfies the predicate `integerp'.

Documentation:
Code (javascript, php, etc.) indentation level.

You can customize this variable.
Seems like my attempt to globally set web-mode-code-indent-offset to 2 is getting overridden somehow in my App.js file.
If I attempt to customize via that link, it just customizes the global value and the value in this buffer stays at 4.
```

Copy of .spacemacs file

https://github.com/csaintc/configs/blob/master/.spacemacs
#### Reproduction guide
- Start Emacs
- Go to javascript file
- type some code
- notice improper indentation on CR

_Observed behaviour:_
Configurations are not picked up on / applied. 

It attempts to indent 4 spaces instead of the configured 2, and it attempts to align multi-line function calls with the parens:

```
return node
  .set('questionSetList', new List([id]))
      .set('')
```

_Expected behaviour:_

```
return node
  .set('list', new List([id])
  .set('')
```

( edit: better example )
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 5f26b82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults emacs-lisp clojure git deft markdown org react ranger dockerfile yaml Saltstack erlang dash
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking themes-megapack version-control
                 (colors :variables colors-enable-rainbow-identifiers t))
```

**Comment by hughrawlinson** [comment]
I may also have this issue. I've set the following in my .spacemacs file:

```
(defun dotspacemacs/user-config ()
(setq-default js2-basic-offset 2)
(setq-default js-indent-level 2)
(defun my-web-mode-hook ()
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-css-indent-offset 2)
  (setq web-mode-code-indent-offset 2)
  (setq web-mode-indent-style 2)
  )
(add-hook 'web-mode-hook  'my-web-mode-hook)
)
```

`SPC m =` then indents the file to 4 spaces, and then jscs goes nuts because it detects the whole buffer as being incorrectly indented.

**Comment by csaintc** [comment]
User https://github.com/stockninja @stockninja was having the same problem

**Comment by stockninja** [comment]
Description

Cannot change indentation from 4 characters to 2 characters in react-mode.

Trimmed my .spacemacs to only enable the react layer, and only set the following values javascript indentation-related variables in spacemacs/user-config:

    (setq web-mode-code-indent-offset 2)
    (setq web-mode-indent-style 2)
    (setq js2-basic-offset 2)
    (setq js-indent-level 2)
No one in the Gitter channel could assist me, so I'm opening an issue.

Maybe there some secret variable I just don't know about?

Reproduction guide

Start Emacs
Open a JSX file with a .js extension.
Indent any line using >.
Observed behaviour:
Line indents by 4 characters

Expected behaviour:
Line indents by 2 characters

System Info

OS: darwin
Emacs: 24.5.1
Spacemacs: 0.105.19
Spacemacs branch: nil (rev. b21c717)
Graphic display: t
Distribution: spacemacs
Editing style: vim
Completion: helm
Layers:
(react)

**Comment by stockninja** [comment]
(my description of same issue)

#### Description
Cannot change indentation from 4 characters to 2 characters in react-mode.

Trimmed my .spacemacs to only enable the `react` layer, and only set the following values javascript indentation-related variables in `spacemacs/user-config`:
```
    (setq web-mode-code-indent-offset 2)
    (setq web-mode-indent-style 2)
    (setq js2-basic-offset 2)
    (setq js-indent-level 2)
```

No one in the Gitter channel could assist me, so I'm opening an issue.

Maybe there some secret variable I just don't know about?

#### Reproduction guide
- Start Emacs
- Open a JSX file with a .js extension.
- Indent any line using `>`.

*Observed behaviour:*
Line indents by 4 characters

*Expected behaviour:*
Line indents by 2 characters

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: nil (rev. b21c717)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(react)
```

**Comment by casertap** [comment]
Same thing for me. After selecting all lines and hitting = to reindent the jsx code.
Every lines get flatten at the same level of indentation.

**Comment by jakecoble** [comment]
It looks like the web-mode indentation variables are unbound when web-mode is loaded, and web-mode uses `standard-indent` [by default](https://github.com/fxbois/web-mode/blob/master/web-mode.el#L70). Setting `standard-indent` to the desired indent level gives the expected behavior.

I'm not yet sure why this happens.

**Comment by casertap** [comment]
Thanks @jakecoble 
can you copy paste a snippet of your config please?

**Comment by hughrawlinson** [comment]
I was able to fix this by adding a `.jsbeautifyrc` to my home directory with the property `"indent_size": 4`. I suppose js-beautify doesn't listen to the setting in emacs.

**Comment by way0750** [comment]
I used to have this problem, and someone told me about setting mode to react. Now indent works perfect in .js for jsx: m-x react-mode
To set it for every .js file, add this to your user config:
(add-hook 'js2-mode-hook 'react-mode)
You might need to have the react layer too.

**Comment by TheBB** [comment]
> (add-hook 'js2-mode-hook 'react-mode)

The correct way to do this is to make an entry in `auto-mode-alist`, which associates filenames to modes.

```elisp
(push '("\\.js\\'" . react-mode) auto-mode-alist)
```

**Comment by casertap** [comment]
@TheBB I do not have a auto-mode-alist section in my config file.
where should I put this? How this is better than the solution of @way0750

**Comment by TheBB** [comment]
There are thousands of variables available for you to configure, very few of them are in the config file. You can put it in `dotspacemacs/user-config`.

The @way0750 solution makes it impossible to enable `js2-mode` if you want to do that in another file. Also some js2 mode config might bleed into react mode, since the calling scheme looks like this:

1. Open js-file. Emacs looks up in auto-mode-alist what mode to enable.
2. Emacs calls `js2-mode`.
3. js2-mode does its setup, then runs `js2-mode-hook`
4. Emacs calls `react-mode` since it's in the hook. It does its setup, then runs `react-mode-hook`.
5. Emacs finishes running `react-mode-hook` and thus is done running `react-mode`.
6. Emacs continues running the rest of the functions in `js2-mode-hook`, potentially destroying `react-mode` configuration.

As opposed to:

1. Open js-flie. Emacs looks up in auto-mode-alist what mode to enable.
2. Emacs calls `react-mode`.

**Comment by morhekil** [comment]
has there been a definitive answer to this problem? I seem to have run into it as well with the latest release of spacemacs, and none of the ways suggested above let me change the indentation in react mode from 4 to 2 spaces.

**Comment by lparry** [comment]
for anyone suffering from these defaults with no obvious variables that can be set that are actually respected, this is what's (mostly) working for me:

```emacs-lisp
  (defun my-setup-indent (n)
    ;; java/c/c++
    (setq-local standard-indent n)
    (setq-local c-basic-offset n)
    ;; web development
    (setq-local javascript-indent-level n) ; javascript-mode
    (setq-local js-indent-level n) ; js-mode
    (setq-local react-indent-level n) ; react-mode
    (setq-local js2-basic-offset n) ; js2-mode, in latest js2-mode, it's alias of js-indent-level
    (setq-local web-mode-markup-indent-offset n) ; web-mode, html tag in html file
    (setq-local web-mode-css-indent-offset n) ; web-mode, css in html file
    (setq-local web-mode-code-indent-offset n) ; web-mode, js code in html file
    (setq-local css-indent-offset n) ; css-mode
    (setq-local sh-basic-offset n) ; shell scripts
    (setq-local sh-indentation n))

  (defun my-personal-code-style ()
    (interactive)
    (message "My personal code style!")
    ;; use space instead of tab
    (setq indent-tabs-mode nil)
    ;; indent 2 spaces width
    (my-setup-indent 2))

  (my-personal-code-style) ;; it would be lovely if this was enough, but it gets stomped on by modes >:(

  (add-hook 'css-mode-hook 'my-personal-code-style)
  (add-hook 'js2-mode-hook 'my-personal-code-style)
  (add-hook 'react-mode-hook 'my-personal-code-style)
  (add-hook 'sh-mode-hook 'my-personal-code-style)
```
with some whack-a-mole going on every time I open something in a new mode to add yet another hook for it.

The example in the original issue works as it should.

The only issue I have now is:

```jsx
<Component
  {...props}
  something={somethingElse}
/>
```
auto-indents to:
```jsx
<Component
    {...props}
    something={somethingElse}
/>
```
but it's a hell of a lot better than awful 4 space tabs or real tab defaults sneaking in absolutely everywhere.

If someone comes up with a more concise solution to just make 2 spaces the default everywhere, I'd love to know about it.

**Comment by matason** [comment]
I am not sure if this will help anyone but I wanted a 2 space indent when editing JavaScript files... I achieved that by setting the js2-basic-offset variable to 2.

**Comment by denistakeda** [comment]
Same for me in typescript and nothing works

**Comment by vladimir-vovk** [comment]
I am not sure what is happening, but after I set variable `standart-indent` to `2` and turn on `react-mode` everything works as expected (only in that order).

**Comment by arvinpan** [comment]
Similar to @matason and thanks to all above.
In my case, I need to use the "hook" way to make sure it does take effect.
Add the following [code snippet](https://stackoverflow.com/a/39331704) to user-config:
```lisp
(add-hook 'js2-mode-hook (lambda () (setq js2-basic-offset 2)))
```

**Comment by adithep** [comment]
I have tried every solution in this thread. Nothing works for me.

**Comment by lane-s** [comment]
I've run into this issue as well and a noticed that reloading my config solves the issue. It's annoying to have to remember to do it every time when it should work on startup though.

**Comment by cinjon** [comment]
I am in the same boat as @adithep. It's strange that this is failing for just ReactJS jsx return blocks.

**Comment by pencilcheck** [comment]
What worked for me is the solution posted by @lparry but I have to put the configuration before the change in auto mode. Then I need to restart emacs for it to work, the SPC f e d doesn't work.
