### ISSUE TITLE
flycheck-gometalinter cann’t be installed auto

### ISSUE THREAD

**Issue by zwb-ict** [syl20bnr/spacemacs#5951]
#### Description
flycheck-gometalinter cann’t be installed auto, my gometalinter location is:
```
/Users/zwb/GolangProjects/bin
```
I have added this path into $PATH

The exec-path val is:
```
("/usr/local/bin/" "/usr/bin/" "/bin/" "/usr/sbin/" "/sbin/"
"/Library/TeX/texbin/" "/Users/zwb/.nvm/versions/node/v4.4.1/bin/"
"/usr/local/opt/llvm/bin/" "/Users/zwb/depot_tools/" "/Users/zwb/.cargo/bin/"
"/usr/local/opt/go/libexec/bin/" "/Users/zwb/GolangProjects/bin/"
"/usr/local/Cellar/emacs/HEAD/libexec/emacs/25.1.50/x86_64-apple-darwin15.4.0/")
```

#### Reproduction guide
- Start Emacs
- Open golang project

*Observed behaviour:*
Got error:
```
File mode specification error: (file-error Cannot open load file No such file or directory flycheck-gometalinter)
```

#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.19
- Spacemacs branch: develop (rev. b772734)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm spacemacs-ivy erc c-c++ emacs-lisp javascript
                (go :variables gofmt-command "goimports")
                (latex :variables latex-enable-auto-fill t)
                lua yaml
                (rust :variables rust-enable-rustfmt-on-save t)
                shell-scripts
                (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
                github
                (version-control :variables version-control-diff-tool 'git-gutter+ version-control-global-margin t)
                (dash :variables dash-helm-dash-docset-path "~/Library/Application Support/Dash/DocSets")
                fasd ranger
                (wakatime :variables wakatime-api-key "b0d4cb91-e437-470c-b54c-72d92716287c" wakatime-cli-path "/usr/local/bin/wakatime")
                (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
                (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-tab-key-behavior 'complete)
                better-defaults
                (chinese :variables chinese-enable-fcitx t chinese-enable-youdao-dict t)
                (ibuffer :variables ibuffer-group-buffers-by 'projects)
                (org :variables org-enable-github-support t)
                osx
                (shell :variables shell-default-shell 'multi-term shell-default-term-shell "/usr/local/bin/zsh")
                smex floobits
                (syntax-checking :variables syntax-checking-enable-tooltips t)
                cscope gtags
                (ycmd :variables ycmd-server-command
                      '("python" "/Users/zwb/bin/ycmd/ycmd")
                      ycmd-force-semantic-completion t)
                ahei blog gtd zwb)
```

**Comment by StreakyCobra** [comment]
CC @JAremko (https://github.com/syl20bnr/spacemacs/pull/5759)

**Comment by JAremko** [comment]
Your PATH should be ok since the package installs only if `flycheck-gometalinter` executable is found on PATH.

Hmm.. Try removing .emacs.d and reinstalling Spacemacs. Also what is your  [`dotspacemacs-enable-lazy-installation`](https://github.com/JAremko/spacemacs/blob/master/.spacemacs#L23) variable in .spacemacs ? Strange that you see this message only when opening a .go file.

**Comment by JAremko** [comment]
Mb @bogdanteleaga  uses Emacs 25. It looks ok on 24(debian) :confused:

**Comment by syl20bnr** [comment]
I guess the update of GOPATH happens too late, would it be a possible cause ?

Maybe this PATH thing should go in config.el ?

**Comment by bogdanteleaga** [comment]
I also have emacs 24(on arch fwiw). Could this be related to the .zshenv(and equivalent for other shells) message that was displayed on startup recently?

To me this looks like `flycheck` cannot find the `flycheck-gometalinter` package/file when it loads up, so maybe an installation gone wrong? Try removing the flycheck packages from under `.emacs.d/elpa`

**Comment by zwb-ict** [comment]
@JAremko @syl20bnr @bogdanteleaga I tried to set
```
 dotspacemacs-enable-lazy-installation
```
to t or nil, and remove .emacs.d/elpa to have a clean reinstall.

But still work.

**Comment by JAremko** [comment]
I think this  [toggle](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/go/packages.el#L6)  stuff might be glitching  :confused: 
 @zwb-ict last one. Can you build Spacemacs from this repo https://github.com/JAremko/spacemacs-pr/tree/gometa  ?

**Comment by zwb-ict** [comment]
@JAremko ```gometa``` branch is OK.

**Comment by JAremko** [comment]
thanks! So it must be something with  @syl20bnr 's patch  https://github.com/syl20bnr/spacemacs/commit/d94b17d   

The responsibility successfully shifted :smile:

**Comment by syl20bnr** [comment]
See my previous comment :-)

**Comment by JAremko** [comment]
@syl20bnr  Hm... When I tried to reproduce the error I witnessed a :sparkles: miracle :sparkles:  Spacemacs installed the package but then it wasn't installed :cold_sweat: It's like it was installed but then removed or something. I don't even know... 

So you are proposing to use a flag instead of `executable-find`  or a variable with a path(provided by user) to gometalinter?  

I cant understand how it is  actually happening.  It looks like the executable(in this bug report) is found because Emacs tries to use the package.   But the package isn't there (file `flycheck-gometalinter`) inst found.  The error message looks like if something tried to require nonexistent package `(require 'fake-package-name)` = `Cannot open load file: No such file or directory, fake-package-name`  :confused:

**Comment by JAremko** [comment]
Now I thinking. What if the insane stuff that a was talking about was happening because of  Emacs repo lag :cold_sweat:

**Comment by JAremko** [comment]
@zwb-ict  Do you still experience this issue with the develop branch? 
I'm thinking. What if it was Emacs repo glitch all along :scream_cat:  
 If you still have it, I'll make a PR with a (hopefully)fix.

**Comment by syl20bnr** [comment]
@JAremko Maybe at install time the PATH is not yet read by Spacemacs so it would evaluate to false.

@zwb-ict How do you define your PATH ?

**Comment by JAremko** [comment]
@syl20bnr  But if it isn't installed wouldn't it throw something like [`flycheck-gometalinter-setup is void`](https://github.com/syl20bnr/spacemacs/commit/d94b17d#diff-21a4d09bdea5c6dfdd7a04eb8a98013fR32)  :confused:

**Comment by zwb-ict** [comment]
@JAremko, I still experience this issue with the develop branch, very glad to see your PR to fix this.
@syl20bnr below is my PATH defined in .zshenv
```
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/zwb/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1

export GIT_EDITOR=vim

export JAVA_8_HOME=$(/usr/libexec/java_home -v 1.8)

export JAVA_HOME=$JAVA_8_HOME

export MAVEN_OPTS=-Djavax.net.ssl.trustStore=/Users/zwb/.m2/jssecacerts

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE="zh_CN.UTF-8"

export PATH=/Users/zwb/.cargo/bin:$PATH
export PATH=/Users/zwb/depot_tools:$PATH
export RUST_SRC_PATH=/Users/zwb/rust/src

export PATH=$PATH:/usr/local/opt/go/libexec/bin
export GOPATH=/Users/zwb/GolangProjects
export PATH=$PATH:$GOPATH/bin

export PATH=/usr/local/opt/llvm/bin:/usr/local/bin:$PATH
export CPLUS_INCLUDE_PATH=$(llvm-config --includedir):$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=$(llvm-config --libdir):$LD_LIBRARY_PATH

export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:$MANPATH

export NVM_DIR=~/.nvm
. $(brew --prefix nvm)/nvm.sh

```

All golang bins are installed in /Users/zwb/GolangProjects/bin

**Comment by JAremko** [comment]
@zwb-ict  This should work if  @syl20bnr  is right. At least it should throw a different error.  `git clone https://github.com/jaremko/spacemacs-pr.git -b issues-5951-1  ~/.emacs.d`    [enable gometa](https://github.com/JAremko/spacemacs-pr/commit/11e696ad06db46ac88f402e60be7625bbcaf628d#diff-9461957b3c790c5c3299cc03bee3e4b1R44)  - it is off by default.  

I think it's better way to handle gometalinter all around. It's a command-line tool first of all.  Really powerful one, but also heavy.  I'm pretty sure that there is someone who would prefer running it from the command-line since it might make old machines unresponsive.  But it's @syl20bnr  call for sure.

**Comment by zwb-ict** [comment]
Thank you @JAremko, ```issues-5951-1``` is OK.

**Comment by JAremko** [comment]
@zwb-ict  cool :+1:  I created PR #5984

**Comment by zwb-ict** [comment]
@JAremko @syl20bnr @TheBB @StreakyCobra @bogdanteleaga it works OK after update to latest develop branch.  Is there anything else?  May I close this issue?

**Comment by JAremko** [comment]
Sure :+1:

**Comment by zwb-ict** [comment]
Thank you @JAremko
