### ISSUE TITLE
Advice for merging customizations from my previous Emacs setup

### ISSUE THREAD

**Issue by luxbock** [syl20bnr/spacemacs#599]
I have a rather large initialization file from my previous Emacs setup, that I'd now like to migrate over to Spacemacs, but before starting, I wanted to ask advice for what the most idiomatic way to do this would be. 

* My old setup uses `use-package` as well, which is where I was doing all of my mode-specific configurations. My impression with Spacemacs is that `use-package` should be used at the level of configuration-layers. This is fine by me, but it leaves open the question of where should be putting the stuff from my old config that's missing from the modes that are already present in Spacemacs? My first guess is that it should all go to `dotspacemacs/config`. Is this correct?

* Due to the amount of customizations I have, I'd like to continue using org-babel to store my modifications, even if it means not using it with `use-package` like I was doing before, because it makes browsing around so much faster. What would be the best way to approach this? With my previous set-up, the only lines I had in my `init.el` file were calls that loaded up org-mode and a call to `org-babel-load-file` to load my `emacs-init.org` file. Should I do the same, but just put all of this inside `dotspacemacs/config` instead? I'm guessing that putting it in `dotspacemacs/init` wouldn't work, as org-mode won't be loaded by then.

Thanks, and sorry if this is not the proper place for this question.

**Comment by syl20bnr** [comment]
1) The only way to install new packages properly in spacemacs is to create and use your own configuration layer and organize all your `use-package` in `init` functions. Without doing this your packages will be deleted at startup because spacemacs thinks you are not using them. You can tell spacemacs that you are using a layer by adding the layer to the `dotspacemacs-configuration-layers` variable. This approach is also recommended to extend existing package configuration.

2) If you organized your settings in a layer you can then use `SPC f e h` to bring a `helm-spacemacs` buffer where you can type a package name and go to the init function.
To keep your stuff with outline support you can still use `outline` I believe, see example here: 
- https://github.com/abo-abo/hydra/blob/master/hydra.el#L322
- https://github.com/abo-abo/hydra/blob/master/hydra.el#L498

**Comment by luxbock** [comment]
Thanks! I found some example configurations on Github so now I have a better idea of how things should work. I will look into using `outline`.
