### ISSUE TITLE
Two GUI windows open when called from terminal on OSX

### ISSUE THREAD

**Issue by jbernsie** [syl20bnr/spacemacs#6023]
I have `emacs` bound as an alias to open the emacs GUI, however when passing a directory/filename to emacs it will open the file or directory in one emacs GUI and the startup screen in another. `dotspacemacs-startup-banner` and `dotspacemacs-startup-lists` have both been set to nil.

**Comment by jaehess** [comment]
Which version of emacs are you using. I am seeing issues on OS X with emacs 24.5.1 with using Window Managers like [Magnet](http://magnet.crowdcafe.com) and maximizing my window always seems to be off by the height of the menubar, as well as getting the OS X menu bar to work required explicitly setting it in my dot files.

**Comment by bernsie** [comment]
Im on 24.5.1 and the issue seems to be related to the daemon process, as starting the daemon process then starting `emacsclient` will stop the double window opening, however just opening a directory or file with straight `emacs .` will launch both the startup screen and the directory in seperate processes
