### ISSUE TITLE
Make creating new frames work consistently with persp-mode enabled

### ISSUE THREAD

**Issue by hedning** [syl20bnr/spacemacs#6117]
Update on #5925.

It's [now possible](https://github.com/Bad-ptr/persp-mode.el/issues/36) to configure what persp-mode does when new frames are created, using the new `persp-init-new-frame-behaviour-override` variable. This should make it possible to make the experience more streamlined for users who doesn't use layouts.

To get the default emacs behaviour setting `persp-init-new-frame-behaviour-override` to an empty lambda works, at least when not using layouts explicitly. Ie. calling `emacsclient -c` starts in the scratchpad, `emacsclient -c file` opens the file properly (even if it's already open somewhere else) and `make-frame` starts with the active buffer of the active frame. Calling `make-frame` from a custom layout however opens the new frame in the default layout, which probably isn't desired.

I don't really use layouts so I haven't tested this out much with any other layout than the default,  but I'm guessing it should be possible to make it behave one way with the default layout and another with custom layouts.

Currently there seems to be quite a lot of seemingly random behavior when creating new frames. Since it's an explicit goal to make layouts work without interference for people who doesn't use them explicitly I thought it would be good to investigate a solution.

@bmag you know your way around the layout code right?

**Comment by bmag** [comment]
@hedning that looks like it might be useful. Myself I haven't experienced "a lot of seemingly random behavior", but I don't use `emacsclient` much either. I think having a nil perspective that doesn't share window configuration between frames (but does contain all buffers) would be a good fit for "make layouts work without interference for people who doesn't use them explicitly". Not sure I'll have any time to work on it in the foreseeable future, unless it turns out to be a small change. 

cc @CestDiego

**Comment by hedning** [comment]
> I think having a nil perspective that doesn't share window configuration between frames (but does contain all buffers)

Yeah, that sounds about right. I might start using layouts some and see if I can make fix.
