### ISSUE TITLE
Understanding shortcut choices, C-* vs SPC *

### ISSUE THREAD

**Issue by quicknir** [syl20bnr/spacemacs#6150]
In general I'm liking the whole scheme and layout of spacemacs a lot. One thing though that I find confusing is when a Ctrl prefix and a space leader lead to a similar set of shortcuts. For instance, C-W and SPC-W both lead to window related shortcuts. Many of the shortcuts overlap but they are not identical. Similarly, in Markdown layer, C-c and , both conceptually access major mode related things, but again the shortcuts are not identical. C++ mode is a bit odd in that C-c has a bunch of shortcuts but , is completely empty.

Is there some rhyme or reason as to what gets selected for which, how? Is this some kind of compromise between backwards/package compatibility and newer shortcuts? Naively I guess I would have expected them either to be completely different, or just to map to the same keymap (more than one way to get the same effect). I've read the docs but they don't seem to shed light on this issue. Indeed, e.g. for window related bindings they don't mention C-w at all.

**Comment by syl20bnr** [comment]
Spacemacs key bindings behind `SPC` leader have been chosen independently of what existed before. One of the nice things of Spacemacs is that all its key bindings are isolated behind `SPC` (or `M-m`) so the default "Emacs" key bindings are near to be 100% untouched. This isolation allow us to be completely free to decide where to put key bindings, and most of the time we prefer mnemonic instead of compatibility because compatibility means we loose potential consistency (each package has its own view on default key bindings). It does not mean we choose mnemonic all the time, and often it happens we choose the same key binding as the default one (most of the time it is incidental).

So free your mind when you hit `SPC` where you enter the Spacemacs world. :-)

**Comment by quicknir** [comment]
That makes sense! Thanks for explaining.
