### ISSUE TITLE
spell-checking: `ESC` does not dismiss flyspell-auto-completion popup

### ISSUE THREAD

**Issue by joehillen** [syl20bnr/spacemacs#6209]
#### Description :octocat:

Trying out the new feature for spell-checking: https://github.com/syl20bnr/spacemacs/commit/f367c4b5aad1043ddeea425a77255d304f007c11

Evil bindings do not work after a flyspell-auto-completion popup activates on a word.

There seems to be no way to dismiss the popup other than `C-g` and all normal state navigation does not work.

I would expect either hitting `ESC` or navigating away from the misspelled word would dismiss the popup.

cc @usharf
#### Reproduction guide :beetle:
- `(spell-checking :variables enable-flyspell-auto-completion t)`
- Open `scratch` buffer
- Type: I'm terrable at spelling.
- Navigate back to the word "terrable"
- Wait for the flyspell popup.
- Hit any of these keys: `ESC`, `w`, `b`, `h`, `j`, `k`, `l`

_Observed behaviour:_ :eyes:

Nothing

_Expected behaviour:_ :broken_heart:

The popup should disappear and navigation should work.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. 9414a8a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(spacemacs-helm ansible asciidoc asm
                (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
                better-defaults clojure colors dockerfile emacs-lisp evil-commentary evil-cleverparens evil-snipe floobits git github go gtags html
                (ibuffer :variables ibuffer-group-buffers-by 'projects)
                intero java javascript joehillen latex markdown nginx org puppet purescript python ranger rebox restclient ruby rust
                (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/bash" shell-file-name "/bin/bash")
                shell-scripts
                (spell-checking :variables enable-flyspell-auto-completion t)
                syntax-checking systemd themes-megapack vagrant version-control vinegar yaml)
```

**Comment by syl20bnr** [comment]
Indeed, only `C-g` works, this is a know issue. @d12frosted proposed to add `flyspell-popup` functionality to `flyspell-correct` which should allow us to fix this issue.

**Comment by mlinchitstest** [comment]
Is there any progress on this? The biggest issue for me is that after hitting `C-g`, the cursor _immediately changes position_ and leaves the misspelled word, which means that _you can't edit the misspelled word yourself without erasing it_. It's not that big a deal in terms of efficiency (you can just backspace, instead of moving the cursor to correct a typo), but it's really counter-intuitive behavior for new users. This makes the popup completely unusable. Perhaps there is a way to have the popup be less automatic? Maybe have an option bring it up the popup by right-click or some shortcut? It's can also cause problems when you're defining any case-sensitive string variables, because the automatically appearing popup will auto-correct your string unless you hit `C-g` (something few will know about) or explicitly choose to ignore the error. In other words, it can very easily mess up your code (in fact it takes effort to have it _not_ mess up your code).

**Comment by nixmaniack** [comment]
@mlinchitstest  This should disable popups. 
```elisp
(spell-checking :variables enable-flyspell-auto-completion nil)
```

**Comment by mlinchitstest** [comment]
what's the best way to set a key to invoke the popup? Should I have a keyboard event  "hook" that toggles `enable-flyspell-auto-completion` on and then (somehow) off? Or is there a better way?

**Comment by nixmaniack** [comment]
> what's the best way to set a key to invoke the popup? Should I have a keyboard event "hook" that toggles enable-flyspell-auto-completion on and then (somehow) off? Or is there a better way?

I don't think there's an easy configuration that would enable this based on how this auto-completion is setup for flyspell. Either you enable it or disable it completely based on `enable-flyspell-auto-completion`.

You can try following snippet - add it user-config(I haven't tested it) after having `enable-flyspell-auto-completion` set to `t`
```elisp
(spacemacs|use-package-add-hook flyspell-popup
  :post-init
  (progn
    (remove-hook 'flyspell-mode-hook #'flyspell-popup-auto-correct-mode)
    (define-key flyspell-mode-map (kbd "C-;") #'flyspell-popup-correct))
```

Now on incorrect spelling you should be able to use `C-;` to correct word with popup.

**Comment by mlinchitstest** [comment]
added this to user-config and it still pops up automatically. being a novice, i tried disabling flyspell-popup-auto-correct-mode, but that naturally just disables the popup feature. I like the popup, but don't like the "auto" part.

**Comment by nixmaniack** [comment]
1. What is the output of `SPC h d k` `C-;`?
2. What  is the output of `SPC h d v` `flyspell-mode-hook`?

**Comment by d12frosted** [comment]
Honestly I don't like this auto flyspell feature and I don't use it all, because it just disrupts my work. Despite this I implemented something similar in [flyspell-correct](https://github.com/d12frosted/flyspell-correct) in order to get rid of `flyspell-popup` package. But in the end I started to hate this `auto-correct` mode so much that I didn't make the change.

The function I use the most is `flyspell-correct-previous-word-generic` (there is a forward variant as well if you need it). Because this function corrects typos just as I notice them. Usually I realise that I made a mistake after I typed several more words. And then I just hit `SPC S c` and `flyspell-correct` asks me to fix the last misspelled word using my interface of choice (`ivy`, `helm`, `popup` or `ido`). 

And this function eliminates the need of using `flyspell-popup-auto-correct-mode` that is enabled only when you wish to correct the last word 😸 Hope you'll like this function, especially it is configured for you in Spacemacs out of box. Just use `SPC S c`. If you wish you can map `C-;` to this function :)

**Comment by joehillen** [comment]
@d12frosted At the very least, this bad default should be removed. It gives everyone a headache.

**Comment by d12frosted** [comment]
By default `enable-flyspell-auto-completion` is set to `nil`.

**Comment by joehillen** [comment]
Oops, my bad

**Comment by mlinchitstest** [comment]
@d12frosted I see that flyspell-correct-popup is part of the spell-check layer. but it is not installed by default when the layer is loaded. How do you load it with the layer?

**Comment by nixmaniack** [comment]
> But when I go to spacemacs/paradox package list. I see flyspell-correct listed as available. But the package is installed, because it's functions are available. This is a little confusing. If spacemacs installs flyspell-correct, shouldn't it be listed in paradox?

It might be the case that package is upgraded and you have old version installed. The new one will be listed as `available` while the other entry would say `installed`.  I'm not sure about paradox but this what happens in the default package manager of emacs. 

<img width="778" alt="screen shot 2017-01-24 at 12 22 52 am" src="https://cloud.githubusercontent.com/assets/542810/22218071/6055bc84-e1cb-11e6-91d8-bfd617ab61eb.png">

**Comment by d12frosted** [comment]
@mlinchitstest `flyspell-correct-popup` is installed only for users that don't use `ivy` or `helm`. I am pretty sure that `ivy` users will feel more comfortable with `ivy` interface for `flycheck-correct`, while `helm` users with feel more comfortable with `helm` 😸 You see the point, don't you? 😸 

As per `popup` interface - it's a bit in a bad situation, because in Spacemacs everyone use `ivy` or `helm`. But don't panic if you still wish to use `popup` as interface for `flycheck-correct`. Just add `flyspell-correct-popup` to list of additional packages and then put following line into `dotspacemacs/user-config` function.

```
(setq flyspell-correct-interface #'flyspell-correct-popup)
```

I haven't tested it myself, but should work since `flyspell-correct-interface` is configured in `init` block. 

---

As per confusing with `SPC h p` - this function lets one to discover available packages. By 'available' here I mean any package that can be installed or is already installed by Spacemacs layer system. So It will list even conflicting packages (like `flyspell-correct-ivy` and `flyspell-correct-helm`). As per paradox - @nixmaniack might have a point. I personally don't use nor `paradox` nor `package-install` interface.

**Comment by mlinchitstest** [comment]
thanks. the appeal of the popup is that is takes up less space. I've tried adding this to both init and user-init, and added `flyspell-correct-popup` to additional packages. It seems that the spelling layer makes sure that `flyspell-correct-popup` does **not** get installed if you use helm.  Any ideas?

**Comment by d12frosted** [comment]
I think that this issue can be closed. Let me know if you have any problems with `spell-checking` layer configurations.
