### ISSUE TITLE
haskell-layer: SPC mht hangs

### ISSUE THREAD

**Issue by reckbo** [syl20bnr/spacemacs#6211]
I installed the haskell layer (under `dotspacemacs-configuration-layers`), and since I want to use ghc-mod for for `SPC mht`, I added this line as instructed by the README:

    (spacemacs/set-leader-keys-for-major-mode 'haskell-mode
            "mht"  'ghc-show-type)

However, running mht results in emacs hanging.  I run top and see this process is started:
   
    /Users/ryan/.local/bin/ghc-mod -b ^J -l --line-prefix=O: ,E:  legacy-interactive

When I kill it, emacs unfreezes.  I've tried various configurations that I found in other threads but to no avail.  Any idea how to fix this?

thanks,
Ryan

**Comment by d12frosted** [comment]
Try running `ghc-mod debug` in the project root and checkout output. Does it show any errors?

**Comment by reckbo** [comment]
No errors, everything looks good.

**Comment by d12frosted** [comment]
You might find a better luck here: https://github.com/DanielG/ghc-mod

I am not proficient at solving issues related to ghc-mod. :( The only trick
I know is `ghc-mod debug` :D


From: reckbo <notifications@github.com> <notifications@github.com>
Reply: syl20bnr/spacemacs
<reply@reply.github.com>
<reply@reply.github.com>
Date: 3 June 2016 at 10:03:50
To: syl20bnr/spacemacs <spacemacs@noreply.github.com>
<spacemacs@noreply.github.com>
Cc: Boris <d12frosted@gmail.com> <d12frosted@gmail.com>, Comment
<comment@noreply.github.com> <comment@noreply.github.com>
Subject:  Re: [syl20bnr/spacemacs] haskell-layer: SPC mht hangs (#6211)

No errors, everything looks good.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/syl20bnr/spacemacs/issues/6211#issuecomment-223506070>,
or mute the thread
<https://github.com/notifications/unsubscribe/AGNNiTr__365RfKUC2am6tQ14HZ2wxd_ks5qH9HTgaJpZM4ItNtn>
.

**Comment by reckbo** [comment]
This issue was resolved by renaming /usr/bin/ghc to ghc78 so that the ghc in my ~/.stack is found instead (which means ghc and ghc-mod are of the same version).

**Comment by d12frosted** [comment]
Great. Thanks for posting here solution.

I've told about this issue so many times but didn't bother to document it in haskell layer readme file. What embarrasses me is that I totally forgot to ask you about versions. :D
