### ISSUE TITLE
Consider adding `intero` mode to Haskell layer

### ISSUE THREAD

**Issue by bixuanzju** [syl20bnr/spacemacs#6233]
Just keep a note here for anyone interested in integrating `intero` into Haskell layer.

[Intero](http://commercialhaskell.github.io/intero/)

**Comment by chrisbarrett** [comment]
For cribbing:

https://github.com/chrisbarrett/spacemacs-layers/blob/e3e38a38d41edc3b757ab6dfe62f0d7f11851c4d/cb-new-haskell/packages.el#L186

**Comment by reckbo** [comment]
This would be good

**Comment by syl20bnr** [comment]
`new-haskell` ... interesting. Several Haskell users would like a new/more modern/more opinionated/less bloated haskell layer :-)

**Comment by d12frosted** [comment]
> more opinionated / less bloated

More options easily lead to bloating 💃

@chrisbarrett I like your clean layer. I don't see anything for completion though. I think `company-ghci` would nicely fit. 

Re `interno` - I've seen it and it was on my list to try.

**Comment by chrisbarrett** [comment]
@d12frosted: interno provides a company backend.

**Comment by d12frosted** [comment]
Yeah, just noticed. :D

**Comment by d12frosted** [comment]
> “I just tried this and it works. It just works. I have never had this experience with Haskell + Emacs. Thank you so much for this.”

From interno site.

**Comment by chrisbarrett** [comment]
Yes, it's been solid for me over the past day of hacking.

**Comment by d12frosted** [comment]
I tried your layer, I like it so far. Just several notes:

1. For some reason there is no `haskell-flycheck-holes` in `local` dir, though `haskell-flycheck-holes` is used in `packages.el`.
2. You use `use-package :functions` in many places where it looks like `:commands` is what you wanted. 
3. Shouldn't [it](https://github.com/chrisbarrett/spacemacs-layers/blob/master/cb-new-haskell/packages.el#L313) be `init` instead of `config`?
4. `haskell-mode` misses several established key bindings. 

But anyway, thanks for that layer! Gonna steal some stuff :-P

**Comment by d12frosted** [comment]
P. S. can anyone explain me why haskell ecosystem has so much tooling with so much problems? And instead of solving existing problems the usual solution is to bring yet another tool.

**Comment by TheBB** [comment]
> Avoid success at all cost.

—Simon Peyton Jones

**Comment by d12frosted** [comment]
And write it using comics sans, yes 💃 

But still, I believe you understand my struggle. 😸

**Comment by chrisbarrett** [comment]
I should clarify--people are welcome to _refer_ to my layers, but I'm not interested in formally submitting PRs and maintaining any code for layers in Spacemacs mainline. I have my own prefs and conventions, key bindings, etc, and I'm converging on being one of those weirdo spacemacs-core users who doesn't use any of the provided language layers. :p

@d12frosted:

> For some reason there is no haskell-flycheck-holes in local dir, though haskell-flycheck-holes is used in packages.el.

It's definitely there on [HEAD](https://github.com/chrisbarrett/spacemacs-layers/blob/master/cb-new-haskell/local/haskell-flycheck-holes/haskell-flycheck-holes.el). :)  

> You use use-package :functions in many places where it looks like :commands is what you wanted.

Nope, `:commands` introduces interactive commands. `:functions` is used to silence the byte compiler.

> Shouldn't it be init instead of config?

Nope, `:init` is run before package load, whereas `:config` is deferred until the package is required. Check the docs for use-package to understand the diff.

> haskell-mode misses several established key bindings.

Meh, I don't care about Spacemacs conventions that much. ;)

**Comment by syl20bnr** [comment]
After thinking about it, and instead of a new layer, we can put it in the current layer but with the a parameter to choose from cabal or slack. This parameter should be dynamic and must work with directory local variables, it should not be a static parameter that configure the layer once and for all. For slack we can base the config on intero. In the documentation we can clearly divide it into two sections, one for cabal and one for slack.

**Comment by syl20bnr** [comment]
Not sure what I said previously make sense but it seems that intero requires slack to work and we should definitely support cabal for projects that don't use slack.

**Comment by tonyday567** [comment]
The main spacemacs layer people are trying is here: https://gist.github.com/dysinger/63b7cd03f77ac0125356051b23f47a37

Intero looks like a good candidate for replacing ghc-mod, and I'd guess that most haskellers have had ghc-mod turned off for a while now, and will jump on the intero bandwagon.  It works well so far as a complete replacement for the existing layer.

**Comment by magthe** [comment]
@syl20bnr do you mean choose `cabal`/`stack` or choose `ghc-mod`/`intero`?

The reason for asking is that `ghc-mod` claims to work with both `cabal` and `stack` (my experience is that it actually does), while `intero` *only* works with `stack`.

To increase the confusion even further it might be worth looking at [hsdev](http://hackage.haskell.org/package/hsdev). I understand that's the tool that atom and sublime is building their haskell support around. I've seen no move towards adding any emacs plugin for it though.

I suspect I'm not the only one who's interested in getting some support for something else in the haskell layer, ideally something that's more reliable than `ghc-mod`, and in particular something that doesn't force me to stay on old releases of GHC for months just due to upstream having a difficult time adding support.

**Comment by d12frosted** [comment]
I believe that we can use `company-ghci` or `intero`. `Intero` is for `stack` users only, while `company-ghci` should work for `cabal` users as well. Still, if anyone wants to use `ghc-mod` - just install it and be happy 💃

**Comment by syl20bnr** [comment]
@magthe good point, I'm not familiar with Haskell but we have to support both cabal and slack projects. When a project uses slack then intero "just work" package should be used. But when a project uses cabal then ideally we want to support the same feature through ghc-mode since intero is not available.

**Comment by magthe** [comment]
I have a feeling that at least a few of the already existing modules, like `company-ghci`, require only minimal changes to support `stack` too, e.g. by replacing calls to `ghci` with calls to `stack ghci` etc.

**Comment by d12frosted** [comment]
`company-ghci` works with `stack` as well. It just uses `stack ghci` instead of plain `ghci`. I know that `ghc-mod` has superior set of functionality compared to `company-ghci`. But from my experience people use 'pro' features of `ghc-mod` pretty rarely. Usually it's all for completion. `C-c C-t` and `C-c C-i` is available from `interactive-haskell-mode` (or `haskell-interactive-mode` - I always confuse them) with associated interactive session. So it's not `ghc-mod` only feature.

**Comment by magthe** [comment]
I wonder if this touches on an issue I found with `intero`, it doesn't have completion in the REPL :(

**Comment by d12frosted** [comment]
Hm. I never had completion in REPL. With `intero` as well. Do you have it with something else?

**Comment by syl20bnr** [comment]
Ideally we would have a layer variable `haskell-something` which takes one of the values `ghc` and `intero`. Depending on the value we setup the correct hooks. We must be able to set this value via directory local variables in order to choose on a per project basic the tooling backend.
For example of such approach see the ruby layer in develop branch and the ruby-test-runner variable.

**Comment by syl20bnr** [comment]
Correction: we don't setup the correct hooks, we enable the correct modes. Hooks are static hooks defined by Sapcemacs to dynamically check the value of the layer variable.

**Comment by d12frosted** [comment]
Totally agree. That would be nice and will help us to properly configure other stuff. I propose `haskell-completion-back-end` as a name. And possible values are `ghci`, `intero` and `ghc-mod`. All of them work with `stack`, but only `intero` doesn't work without stack. Easy to document. 

I might work on this on Sunday.

**Comment by magthe** [comment]
@d12frosted Sure, I have completion in my "interactive haskell", reachable by `SPC m s b` :)

I'm not very good with elisp, but I'd be *extremely* willing to help with testing!

**Comment by tonyday567** [comment]
Maybe @chrisdone can be so kind to help out us spacemacsers with correcting my amateur understanding below, but:

- intero is a rebranding/replacement for ghci-ng
- :completion-at is an additional feature, which provides completion even on compile failure (which I think is an innovation compared to other tools). company mode hookup is then necessarily provided within intero.
- re-introduces haskell-simple-indentation, which had been taken out of haskell-mode
- disables interactive-haskell-mode (the haskell-mode REPL)
- Whether it only works with stack is debatable.  Chris has stated in social media that he doesn't want to guarantee support for non-stack setups in the future (I would presume because non-stack setups are insane).  Despite this, considerable effort has since gone in to support cabal and it works out of the box with cabal setups right now.

https://www.reddit.com/r/haskell/comments/4mrotr/intero_for_emacs/

**Comment by syl20bnr** [comment]
Thank you for all the info, I hope @chrisdone will be able to comment on this.

Wether a back-end support slack and/or cabal is a mater of documentation I guess.

To make Haskell layer more bearable we need a back-end layer variable. Ideally it should be set on a per project basis, actually I see this feature more as a mandatory one.

**Comment by chrisdone** [comment]
@tonyday567 your comment is accurate.

The simple-indentation module is included because a colleague asked to have it somewhere, since it was removed from haskell-mode. 

Regarding `cabal`, I don't have any intention to support it. Just stack! 😅 

Regarding completion in the REPL, that's just a matter of adding the feature. There's no inherent blocker. We could have TAB completion or just enable `company-mode` in the REPL. If you're interested in discussing that further I suggest opening an issue on [intero](github.com/chrisdone/intero).

**Comment by d12frosted** [comment]
Hey @chrisdone! Thanks for your comment! 

> Regarding cabal, I don't have any intention to support it. Just stack! 😅

To be honest, I totally support this. On other side - we have to support non-stack users as well. 😅 But that's our issue. We just have to cleanup current configs. 

> There's no inherent blocker. 

Indeed.

> We could have TAB completion or just enable company-mode in the REPL.

I am all for enabling `company-mode`. 

P. S. fixed link to [intero](https://github.com/commercialhaskell/intero).

P. P. S. @chrisdone thanks for your hard work on haskell ecosystem and for your elisp projects. The funny thing is that I am using Emacs only thanks to you :) I started from your `emacs.d` and liked that experience 💃

**Comment by joehillen** [comment]
Figured folks in this thread might be interested in this: https://github.com/cydparser/spacemacs-intero

**Comment by d12frosted** [comment]
Looks like this layer is intended to be used with `haskell` layer. And looks like it doesn't support no-stack setup. But as intero setup it's nice 👍

**Comment by Rydgel** [comment]
I switched to emacs for this!

**Comment by d12frosted** [comment]
I've sent PR that might interested most of participants. It's not 100% ready yet, but I would like to hear feedback from anyone interested in testing. Thanks.

**Comment by d12frosted** [comment]
Just to let you know - intero is available now on develop branch. Please, refer to haskell layer readme file for instructions on how to enable it. 

Thanks everyone 😸

**Comment by cies** [comment]
Links to the relevant sections in that readme:

https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/haskell#intero

https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/haskell#intero-repl

**Comment by cies** [comment]
It works for me. I switched to the `develop` branch of Spacemacs (simply by `git fetch && git checkout develop` in `~/.emacs.d`) and applied [this work around](https://github.com/syl20bnr/spacemacs/issues/6523). Then started up Emacs, it complained about not having "curses headers", installing `libncurses5-dev` fixed that (on an Ubuntu-derived distro). Intero installed itself, as advertised. Works like a charm. So far a much better experience then using `ghc-mod`: faster, better highlighting, easier to setup.

**Comment by d12frosted** [comment]
@cies glad to hear!

You could also try using `ghci` completion backend - it works a little bit differently (requires active REPL session), but also works nicely.

**Comment by alexanderkjeldaas** [comment]
Is this in the production branch yet?

**Comment by Tehnix** [comment]
Apologies if this is not the right issue to mention this in, but:

Was trying out the intero integration on develop, and it's running super well! One thing I noticed though is that I can't find a key that calls the `intero-apply-suggestion` function, which can be called with `C-c C-r`. 

This could be located under `SPC m r` which is `haskell/refactor`, such as `SPC m r i`. 

This opens a refactor window where it says you can press `C-c C-c` to apply the suggestions, unfortunately I couldn't find which function this calls so we can map that to a `SPC m r ..` key.

If you want to test it, it appeared when I had a function with the type signature like `portNumber :: Intege` and the suggestion fixes it to `portNumber :: Integer`.

**Comment by Tehnix** [comment]
@alexanderkjeldaas I'm fairly certain Intero is only on the develop branch at this moment, so you'll have to switch to that. Other than that I just set `(haskell :variables haskell-completion-backend 'intero)` and it works :)

**Comment by d12frosted** [comment]
> Is this in the production branch yet?

[Not yet](https://github.com/syl20bnr/spacemacs/blob/master/layers/+lang/haskell/config.el). Please wait for next release. Once it gets to `master` branch we will close this issue. 

---

@Tehnix `intero-apply-suggestion` is not configured. PRs are welcome 😸

**Comment by Rydgel** [comment]
Still not in master? What's missing right now?

**Comment by TheBB** [comment]
Nothing as far as this is concerned. We're just waiting for @syl20bnr to press the button for the new release.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Comment by pavelkogan** [comment]
I have the same issue as @alexanderkjeldaas above: no bindings under `SPC m i`.

I'm on v0.200 and I set the `haskell-completion-backend` to `intero` and installed intero in the project, neither of which made any difference.

**Comment by d12frosted** [comment]
Do you have other `intero` key bindings like `SPC m h i`? Please verify that it's bound to `intero-info`.

**Comment by pavelkogan** [comment]
It's bound to `haskell-process-do-info`. There are no `intero` keybindings; looks like `intero-mode` is not loaded so no `intero` functions are available (running it manually gets me the functions via `SPC :` but still no bindings).

**Comment by d12frosted** [comment]
Ok, what is the version of `haskell-completion-backend` after you open Haskell source file you wish to edit with `intero` enabled? If it's `intero` (without anything funky before the name), checkout if you have enabled `auto-completion` layer as it's required to be enabled in order to setup intero. If it's enabled, please try calling `spacemacs-haskell//setup-intero` manually (via `M-: (spacemacs-haskell//setup-intero) <ret>`) to see if it enables `intero`.

**Comment by pavelkogan** [comment]
`haskell-completion-backend` is `ghci`. Not sure why, since I do set it to `intero` when enabling the `auto-completion` layer, as in the docs for the `haskell` layer (minus the incorrect `quote`).

Calling `spacemacs-haskell//setup-intero` manually does work, though.

**Comment by d12frosted** [comment]
Wait, there is no incorrect `quote`. It's required there. But there is a typo - it's better to set it not along with `auto-completion` layer, but with `haskell` layer itself. But this is not critical and should not affect your problem.

**Comment by pavelkogan** [comment]
Ah right, my mistake, I was doing the same thing as in the docs, but I was confused by the extra parens when there are multiple layers specified (the example only uses one).

Anyway, setting `haskell-completion-backend` with the `haskell` layer works. Thanks!

It really doesn't work with the `auto-completion` layer though. Not sure why, or if it's something that needs to be fixed, or if the docs should just be updated.

**Comment by d12frosted** [comment]
> It really doesn't work with the auto-completion layer though. Not sure why, or if it's something that needs to be fixed, or if the docs should just be updated.

I'll take a look. 

I am glad you are now `intero` user 😸 Happy Haskell coding 🗡 💃

**Comment by magthe** [comment]
I would love it if someone would take a look at the navigation too.

1. On my machines `SPC m g d` (`helm-gtags-find-tag`) don't seem to work in Haskell source files. The trigger to create the gtags files never fire so I have to create them manually. Once they are there though, there is no effect at all when pressing the `SPC m g d`. (This just might be a local issue though. However, I don't quite understand the presence of the gtags/global keybindings in Haskell mode at all, <https://www.gnu.org/software/global/> doesn't mention any Haskell support.)
2. The `SPC m g g` (`spacemacs/jump-to-definition`) does bring me to the definition, but there seems to be no way to jump back!

**Comment by joehillen** [comment]
@magthe Let's not pile everything into this issue. You should open a new issue.

**Comment by magthe** [comment]
Realised that and I'm authoring them now :)

**Comment by vertexcite** [comment]
@magthe Was it just #7269 that you added?

**Comment by magthe** [comment]
@vertexcite #7268 too.

**Comment by Cmdv** [comment]
I've never managed to get completion to work with Intero, I've read through this whole thread but can't see how anyone has set it up to work in a `.spacemacs` 😞 

Could someone give a pointer? 😄

**Comment by joehillen** [comment]
```elisp
   dotspacemacs-configuration-layers
   '((haskell
      :variables
      haskell-completion-backend 'intero))
```

**Comment by Cmdv** [comment]
@joehillen I tried that but I just worked out why it wasn't working, as soon as you get an error then any auto completion will stop working until error is fix. Which I assume is Stack? probably a good feature to not continue coding if you have an error.  😄

**Comment by d12frosted** [comment]
@Cmdv behaviour you describe looks like something that should be discussed upstream 😸
