### ISSUE TITLE
Emacs freeze on M-x call (via SPC-SPC / SPC-:)

### ISSUE THREAD

**Issue by mgwio** [syl20bnr/spacemacs#6247]
#### Description :octocat:

Spacemacs experiences a complete lockup for unknown reasons when attempting to bring up M-x using either SPC-SPC or SPC-:

Edit: I just tested and am also able to recreate this with the actual M-x keybind (option-x for me).

There may be other times I've experienced it, but during this action is by far the most frequent.

I'm able to most easily reproduce this situation in 2-column layout.

When 'frozen', there is a solid black bar that goes down roughly the center of the screen. The first time, spamming Ctrl-G somewhere around 30 times gets it to continue. Triggering the freeze again renders spacemacs unresponsive (entirely) until the process is killed (either by force quit or the `kill` command). During both 'phases', emacs uses upwards of 99% CPU.
#### Reproduction guide :beetle:
- Start Emacs
- Split window
- Open files in each window (I just opened .spacemacs while recreating for screenshots)
- Either use normally with standard M-x use, or press M-x bind (SPC-SPC or SPC-:) and cancel repeatedly until freeze
- Ctrl-g spam to "unfreeze" and bring up the M-x helm minibuffer as intended
- Close minibuffer, repeat M-x opening step

Note that I don't just sit there spamming SPC-SPC for fun. The freeze inevitably happens, it's just convenient for demonstration to be able to quickly reproduce it.

_Observed behaviour:_ :eyes:
Emacs freezes with a solid, relatively thin black, vertical bar on the screen and does not visibly respond. C-g spam can 'recover' it once; repeating the freeze procedure causes emacs to be completely unresponsive and consume 99%+ CPU (according to activity monitor).

_Expected behaviour:_ :broken_heart:
Open M-x menu without freeze or black bar.
#### System Info :computer:
- OS: darwin
- Emacs: 25.0.94.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. 0a973c0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil)
 csv javascript html helm emacs-lisp git org osx python ranger renpy smtheme)
```

Note: smtheme layer is just the jellybeans theme.
#### Backtrace :paw_prints:

```
<<BACKTRACE IF RELEVANT>>

```

Attempts to resolve:
- Delete elpa and redownload packages
- Try master instead of developer
- Reinstall emacs

The bar can be seen here on the right side of the left window. It goes from the top of the frame to the bottom, covering all buffer text and the "ni" in "unix". Note the SPC-SPC in the lower left.
![ss_2016-06-06_19 10 57](https://cloud.githubusercontent.com/assets/8557981/15841094/76f77e9c-2c1c-11e6-9595-c4d81c82aa80.png)

Here is a screenshot of activity monitor to show emacs' CPU usage. I've only had emacs open about 20 seconds at this point.
![ss_2016-06-06_19 11 58](https://cloud.githubusercontent.com/assets/8557981/15841120/b065dc96-2c1c-11e6-8c0c-fa8fcfd9a84b.png)

**Comment by NJBS** [comment]
Do you experience this on Emacs 24.5 as well?

**Comment by syl20bnr** [comment]
May be related to helm, can you test with ivy layer instead of helm ?
Also worth the try is to change the value of `gc-cons-threshold` in init.el, try with `20000000` (still with helm layer), I'm curious to see the results. On one of my workstation I have emacs freezes with `100000000` and no freezes with `20000000`, we have to do something about it.

**Comment by miwu** [comment]
@NJBS I can still produce it in 24.5. With a clean spacemacs, I couldn't get it to freeze (symlinked from template). After 7-8 M-x's, the CPU usage did spike. Additionally, I've been attempting to get it to freeze with a single window layout, but haven't had luck. I wonder if it's specific to multi-window layouts (also does it in 3 column)?

@syl20bnr Changing the threshold still freezes, although the entire frame turns black rather than just the vertical strip. Weird.

![ss_2016-06-06_23 23 29](https://cloud.githubusercontent.com/assets/8557981/15845307/c0ee6768-2c3f-11e6-9966-7f3a209486c4.png)

I can't reproduce the problem using the ivy layer, so that may be my workaround :)

Maybe a conflict between helm and another layer / configuration? I can gist my .spacemacs if you're interested in taking a look.

**Comment by syl20bnr** [comment]
Weird indeed, if you can provide your dotfile it can help.
Another workaround may be to use `smex` layer.

**Comment by miwu** [comment]
@syl20bnr [.spacemacs](https://gist.github.com/miwu/e700f748f2fc0b8eff30b5525ac1588d)

**Comment by TheBB** [comment]
It's probably unrelated but you have two entries with `auto-completion` in your list of layers (one without variables and one with). You should remove the one without variables. (As it stands those variables will not be set.)

**Comment by miwu** [comment]
@TheBB LOL didn't even notice that. Thanks!

In other news, I worked a whole day today with Ivy with no problems. It doesn't feel quite as powerful or organized as helm, but it's fast and doesn't freeze no matter how many windows I have open.

**Comment by akovari** [comment]
Same problem here, I don't even need to open 2 tabs, just starting running M-x makes it freeze with that weird bar over the screen.

OS X 10.11.6
GNU Emacs 25.0.95.1, built from homebrew as --with-dev. I previously used the stable version, had the same issue.

Develop branch of spacemacs with ivy layer enabled fixed the freezing.

**Comment by akovari** [comment]
So I just experienced the same problem on Fedora 24.
My [.spacemacs](https://gist.github.com/akovari/64966730577a1c850ab0527871187242)
GNU Emacs 25.0.95.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.20.6) of 2016-07-14

The problem is resolved by switching to develop branch (where Ivy layer is available)

**Comment by deb0ch** [comment]
@akovari You mean problem resolved, as in fixed in develop, or as in you can use ivy instead ?

Is this problem fixed or still ongoing ? (Autumnal cleanup)

**Comment by syl20bnr** [comment]
May be duplicate of #7964
