### ISSUE TITLE
ansi-term: use vim in tmux, press dot, error occurs

### ISSUE THREAD

**Issue by llj098** [syl20bnr/spacemacs#6252]
<PLEASE REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE>
#### Description

use vim in tmux with ansi-term, start vim, edit files, press dot(.), then you can never quit the vim in tmux.

#### Reproduction guide
- Start Emacs
- M-x ansi-term
- in ansi-term, enter: tmux
- vim some-file
- edit file
- press dot(.)
- dot(.) redo action should be fired in the vim
- spacemacs handle the dot(.) event

*Observed behaviour:*

spacemacs handle the dot(.) event, not the vim in tmux

*Expected behaviour:*

after press dot(.) in vim, the redo action should fire in vim not spacemacs

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(auto-completion clojure emacs-lisp deft git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking restclient lua shell smex version-control)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by TheBB** [comment]
Vim in tmux in ansi-term in emacs? This sounds like a really bad idea in the first place.

**Comment by syl20bnr** [comment]
![deeper](https://cloud.githubusercontent.com/assets/1243537/15868018/d9d07c52-2cb3-11e6-8acc-7ef7f9384ad3.jpg)

**Comment by StreakyCobra** [comment]
I went trough the inception, and actually I can't reproduce it.

I suppose it's because I'm forcing `emacs-mode` within terminals with:

    (evil-set-initial-state 'term-mode 'emacs)

So `.` is not catched by `evil`.

Now I'm not sure to have been back enough to be out of the inception :flushed: Is this world real?

![spinning](https://media.giphy.com/media/13S1lWb5qheNBC/giphy.gif)

**Comment by llj098** [comment]
@TheBB @syl20bnr Yes, It sounds a little wired that I use tmux+vim in spacemacs...

Actually, I [want to use emacs as my window manager](https://news.ycombinator.com/item?id=8922359). Sometimes, I want to quick edit some config files when I am in term,, so it happens..

**Comment by llj098** [comment]
@StreakyCobra Thanks, I tried that, `.` works well, but when I want to quit vim (press `:q`), it quits the spacemacs

**Comment by a13ph** [comment]
@llj098 I suggest you look at exwm layer or better yet, aliasing vim to something like emacsclient (may require some tinkering) and instead of tmux to use `SPC w`/`C-w` window commands.
And ask about annoyances/missing features of that setup.
Yours has quite too much indirection and will suffer in compatibilities and performance.

Thanks for the good laugh, though (no offence, I do understand how one can come to such ideas, they are just not too practical unless you are willing to fight with it by writing lots of code)

**Comment by llj098** [comment]
@a13ph Thanks, I will look at exam layer. :)

**Comment by a13ph** [comment]
@llj098 https://github.com/syl20bnr/spacemacs/pull/3321 it's currently an open PR
