### ISSUE TITLE
[Auto-completion] Unintended behavior of TAB in arguments

### ISSUE THREAD

**Issue by LukeXuan** [syl20bnr/spacemacs#6286]
I have turned on `auto-completion-tab-key-behavior 'complete`, however `TAB` key behaves strangely in some situation.

![image](https://cloud.githubusercontent.com/assets/3363954/15982876/723bbaf4-2fc7-11e6-96f6-a69b900bfcad.png)

When I press `TAB` to complete the `list_make` function invocation, it gives me two arguments to fill. However, When I press `TAB` after entering `list_f` intending to finish the `list_first`, it take me to the second argument of the `list_make` function.

**Comment by TheBB** [comment]
The clang completion backend does this for you. It's quite intended. What you're doing inside the function arguments is **not** regular completion, you're just replacing the function signature that was filled in by clang.

**Comment by LukeXuan** [comment]
Well, I didn't quite understand your words. But, When I press RET it will become `list_make(list_first, list_t list)` different from what I get by TAB`list_make(list_f, [cursor]list_t list)`. 

I thought these two key should be the same in this situation, or I've got something misunderstood?

**Comment by TheBB** [comment]
Okay I understand what you mean now. This is because `company-template-nav-map` takes priority over `company-active-map`. This is an implementation detail of company and there's not much we can do about it. I suggest you take it there... although it's implemented using overlays so there may not be much to do at all, other than changing TAB in one of the keymaps. (Personally I prefer using `C-l` to complete.)

If you want to work around it you can undefine TAB and `[tab]` from `company-template-nav-map`, and maybe bind something else to it. We can do that in Spacemacs too if we can find a suitable key.

**Comment by LukeXuan** [comment]
Okay...I'll dive deeper into the code someday.

**Comment by TheBB** [comment]
Here's a quick workaround for you. Replace "..." with whatever you would like to use to jump to the next field.

    (with-eval-after-load 'company-template
      (define-key company-template-nav-map (kbd "TAB") nil)
      (define-key company-template-nav-map [tab] nil)
      (define-key company-template-nav-map (kbd "...") 'company-template-forward-field))

**Comment by LukeXuan** [comment]
Hey guys. Your suggestions works perfectly. This issue could be closed. Thanks.

**Comment by TheBB** [comment]
You can do that yourself.
