### ISSUE TITLE
Magit: Many key bindings should also be reachable with <leader>-m

### ISSUE THREAD

**Issue by ocharles** [syl20bnr/spacemacs#635]
I can't remember how to use Magit to `fetch origin`, and I was hoping to discover a keyboard shortcut with Spacemacs. Alas, `<space> m` doesn't give me anything - but it probably should.

If people agree, I'll try and put together a pull request.

**Comment by syl20bnr** [comment]
The key bindings in magit are directly available without `SPC m`.
More info and use case example in the documentation of the `git` layer: https://github.com/syl20bnr/spacemacs/tree/master/contrib/git#magit (see quick guide)

**Comment by ocharles** [comment]
While that's true, they lose the discoverability that Spacemacs has to offer. I know most of them, but for the ones I don't know, it's a little more fiddling (though, to be fair, `SPC :` and typing `pull` shows me the command and its keyboard shortcut). Happy for this to be closed if it's against design decisions.

**Comment by syl20bnr** [comment]
You are right and spacemacs tries to make things discoverable as much as possible.
But even with transposed magit keys on `SPC m` the users won't discover the "true" bindings on simple keys, it may even have the bad effect that users will use `SPC m` instead of the regular one.
But you have a good point 
An improved guide-key could allow to include the true magit bindings in parenthesis. I plan to make a spacemacs tailored guide-key because there are special use cases, this one may be one more special use case to consider.

**Comment by CestDiego** [comment]
:+1:  for the tailored guide-key! :D
