### ISSUE TITLE
Is there key binding list for emacs mode?

### ISSUE THREAD

**Issue by YuleiXiao** [syl20bnr/spacemacs#6350]
I see the help document, most key bindings are for vim, is there key bindings for emacs?

**Comment by d12frosted** [comment]
Sure Spacemacs supports Emacs keybindings. There is [Editing Styles](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#editing-styles) section in documentation. So as it says, `SPC` is `M-m` by default. Also you can find some evidence in your `.spacemacs` file ([here](https://github.com/syl20bnr/spacemacs/blob/master/core/templates/.spacemacs.template#L118) and [here](https://github.com/syl20bnr/spacemacs/blob/master/core/templates/.spacemacs.template#L124)).

A side note - I am using Emacs editing style and it works wonderful. So no one forces you to dive into evil part of Spacemacs 😄

**Comment by YuleiXiao** [comment]
@d12frosted you mean that I ```SPC``` is ```M-m```? Key bindings list in document like below, I use ```M-m s s``` to ```search with the first found tool```?

```
Key Binding	Description
SPC s s	search with the first found tool
SPC s S	search with the first found tool with default input
SPC s a a	ag
SPC s a A	ag with default input
SPC s g g	grep
SPC s g G	grep with default input
```

**Comment by d12frosted** [comment]
@YuleiXiao Yes, `SPC` is `M-m` by default. So you can translate quoted table like this:

```
Key Binding Description
M-m s s search with the first found tool
M-m s S search with the first found tool with default input
M-m s a a   ag
M-m s a A   ag with default input
M-m s g g   grep
M-m s g G   grep with default input
```

By convention and habit people keep saying `SPC` when they mean leader key. For Vim editing style it's really `SPC`, for Emacs editing style it's `M-m`. Also there is major mode leader key. In Vim editing style it's `,`, in Emacs - `C-M-m` (or `M-<return>` in most cases). But major mode specific functionality can be accessed also from regular leader key - `SPC m` (`M-m m` for Emacs editing style). Here `m` stands for mode. 

And keep in mind that leader keys can be easily changed. Previously I was using `C-c` instead of `M-m`, because it's more adopted in Emacs world and I was using for several years this key binding to access most functionality. But then I realised that `M-m` is far superior to `C-c`, because it's easier to access. Yes, I use two hands to type `M-m`, but it gives me freedom to easily access other keys after pressing `M-m`. So I think that this leader is a great choice.

**Comment by YuleiXiao** [comment]
@d12frosted thank you very much.
