### ISSUE TITLE
Unable to change keybindings in helm-map

### ISSUE THREAD

**Issue by luxbock** [syl20bnr/spacemacs#642]
I'm trying to swap the position of `helm-execute-persistent-action` and `spacemacs/helm-navigation-micro-state`. I have unsuccessfully tried to put these in:
- my private `luxbock/helm-init`, at the end of the `use-package` macro, in the same place where they are defined in `spacemacs/init-helm`.
- in my `.spacemacs` file, in `dotspacemacs/config` inside a `eval-after-load 'helm` statement.
- same location, but using the `helm-mode-hook` instead.

But none of these solutions work.

**Comment by syl20bnr** [comment]
This is a tricky case of lazy loading. I'll have to add a hook for all `init` functions in order to be able to correctly overwrite lazy loaded configurations.

In the meantime you can disable the helm micro-state with `dotspacemacs-helm-micro-state` in your dot file: https://github.com/syl20bnr/spacemacs/blob/master/core/templates/.spacemacs.template#L64-65

**Comment by syl20bnr** [comment]
I consider this question answered and fixed since in 0.63.0 and above `TAB` is not shadowed anymore.
