### ISSUE TITLE
How i switch to evil mode?

### ISSUE THREAD

**Issue by ivan-vilches** [syl20bnr/spacemacs#6466]
i installed on windows, in the process of installation i choosed style emacs. How i can switch to evil mode? .
i tried re.installing but there is no more the option for choose evil mode.
thanks for your help.

**Comment by wutsdat** [comment]
To go back to vim editing search for dotspacemacs-editing-style in your .spacemacs file and put 'vim unstead of what's here. Your reinstalling attempt may have failed because your .spacemacs file was already present.

You can also toggle between editing mode with `<leader> t E` where <leader> is either `SPC` for vim editing or `alt+m` for emacs editing. 

Also feel free to ask your questions in the spacemacs chatroom : https://gitter.im/syl20bnr/spacemacs
