### ISSUE TITLE
Add ergonomics enforcers layer

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#6505]
For those who lack the self control(like me)
Or it can display how many times arrow keys were used(might be in the space-line)

**Comment by JAremko** [comment]
Optionally it should output  how many times arrow keys was used (might be in the space-line)

**Comment by d12frosted** [comment]
Are you talking about something like following config?

```
(global-unset-key (kbd "<left>"))
(global-unset-key (kbd "<right>"))
(global-unset-key (kbd "<up>"))
(global-unset-key (kbd "<down>"))
(global-unset-key (kbd "<C-left>"))
(global-unset-key (kbd "<C-right>"))
(global-unset-key (kbd "<C-up>"))
(global-unset-key (kbd "<C-down>"))
(global-unset-key (kbd "<M-left>"))
(global-unset-key (kbd "<M-right>"))
(global-unset-key (kbd "<M-up>"))
(global-unset-key (kbd "<M-down>"))
```

There is also [no-easy-keys](http://danamlund.dk/emacs/no-easy-keys.html) minor mode, which you might be interested in.

**Comment by JAremko** [comment]
@d12frosted  Yeah. I'm thinking. It might be helpful to have something like this "out of the box" with a single configuration.  It should be helpful especially for the people who has Emacs background and want to learn the Vi style navigation.

**Comment by nixmaniack** [comment]
I remember using [guru-mode](https://github.com/bbatsov/guru-mode) when starting with Emacs.

**Comment by d12frosted** [comment]
@JAremko Before I switched to Spacemacs I used arrows to select windows. This was actually pretty useful. But now since I have `avy-window`, it's much easier. 

```
(global-set-key (kbd "<left>") 'windmove-left)
(global-set-key (kbd "<right>") 'windmove-right)
(global-set-key (kbd "<up>") 'windmove-up)
(global-set-key (kbd "<down>") 'windmove-down)
```

@nixmaniack `guru-mode` looks a little bit more interesting as it can be configured to warn user about wrong usage. 

But to be honest, at this point I don't see any point in adding this package to Spacemacs.

**Comment by a13ph** [comment]
I'd say there is a point in adding some well written ergonomics enforcer(s) to Spacemacs
Would be nice to generalize this and automate (instead of hand-coding all the restrictions)
Arguably such code itself would be out of scope for Spacemacs (rather being a good package), but it's quite close, IMO.
/bloat

**Comment by JAremko** [comment]
@a13ph  I think it's better to make it a part of Spacemacs.  This way it will be straightforward to include some Spacemacs related ergonomics.  For example using `ace-window` instead of spamming `other-window`

**Comment by JAremko** [comment]
Also this tool can display Spacemacs keybindings when their Emacs counterparts are used - if Vim style was chosen by the user.
