### ISSUE TITLE
markdown folds shell coments inside code fences

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#6537]
#### Description

markdown folding thinks that commentary on shell code is a markdown heading.
#### Reproduction guide
- Start Emacs
- open a new md file
- open a shell code fence `sh` and type this

``` txt
# this is a shell comment, not a heading
$ but markdown extension will think it is a heading and create a fold for it
```

_Observed behaviour:_
markdown extension will think it is a heading and create a fold for it

_Expected behaviour:_
markdown extension should consider everything that is inside a code fence to be code, not heading.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:

``` elisp
(emacs-lisp git markdown org)
```
#### Backtrace

```
not applicable
```
#### Screenshot

<img width="794" alt="markdown-folding" src="https://cloud.githubusercontent.com/assets/8352747/16707851/2d0f5f46-45b4-11e6-8ccf-39b02404394f.png">

**Comment by d12frosted** [comment]
Hey,

Thank you for the report. Though I can't reproduce it. What exactly are you doing after you type quoted snippet?

**Comment by TheBB** [comment]
I can't reproduce it either. Once I close the code block (which notably you haven't done in your screenshot) it works as expected.

**Comment by ninrod** [comment]
Hi. the code block is closed. on the right, you have the file, as is, opened in vim. on the left, you have the exact same file in emacs, but I moved my cursor to the line where it is written: "this is a comment" and pressed `zc` (fold close). 

Can you reproduce now?

**Comment by TheBB** [comment]
Right. Outline only supports recognizing headings by regexps so it's incapable of doing this. So your options are:

* Report this to outline (that is, Emacs), get a patch to make it more powerful and then report to markdown-mode to have it make use of this feature
* Use markdown-mode's own folding methods (bound to TAB, they work like org-mode, but you have to be on a heading)
* Use origami folding (in develop), can fold code blocks in markdown (it appears) but it has no special support for markdown headings (it appears)
* Optionally, in addition to the last two, report to evil so that outline isn't used in markdown (coincidentally, I added that feature)

In either case there's not a whole lot we can do on the Spacemacs side I think.
