### ISSUE TITLE
[Haskell layer] Autocompletion breaks with Cabal versions > 1.20.0.6

### ISSUE THREAD

**Issue by bjarkevad** [syl20bnr/spacemacs#656]
There's an issue with `ghc-mod` which causes `company-ghc` to break when using Cabal versions > 1.20.0.6. 
This is a known issue, and it should be fixed with the release of GHC 7.10, but for now it might be a good idea to warn Spacemacs users of the issue.
A solution to this problem is to have an isolated "emacs cabal" sandbox where the layer dependencies are installed:
```
mkdir ~/.cabal-emacs
cd ~/.cabal-emacs
cabal sandbox init
cabal install cabal-install-1.20.0.6  #install the latest supported cabal
cabal install stylish-haskell hlint ghc-mod-5.2.1.2 #install our dependencies
```
(Note that the ghc-mod version has to explicit, for some reason cabal tries to install a very old version otherwise)
and then in `~/.spacemacs`:
```elisp
(add-to-list 'exec-path "~/.cabal-emacs/.cabal-sandbox/bin/")
```

**Comment by syl20bnr** [comment]
We should add it to the documentation then.

**Comment by welf** [comment]
The proposed solution is not fully correct. If you install other version of Cabal to your sandbox, your system will still use Cabal installed globally, because Cabal, installed to your sandbox is not in your `PATH`. To solve this, add to your `~./bash_profile` file: 
```
export PATH="./.cabal-sandbox/bin:$PATH"
```
and type in your terminal `source ~/.bash_profile` to reload this file (or close and reopen your terminal). Make sure this path is located before your global cabal path (use command `$PATH` in terminal).

After it if you launch your cabal commands from the directory where sandbox is initialized, they will use packages from your sandbox in the directory. If you launch commands not in the directory with initialized sandbox, your system will use path to your global Cabal. 

You can validate this launching `cabal --v` in your terminal from your home directory and from directory with sandbox. You should see different versions of Cabal: 
```
cd ~  #go to your home directory
cabal --v  #cabal-install version 1.22.0.1; using version 1.22.1.1 of the Cabal library
cd ~/.cabal-emacs  #go to the directory where sandbox is located and other version of Cabal installed
cabal --v  #cabal-install version 1.20.0.6; using version 1.20.0.3 of the Cabal library
```

**Comment by TheBB** [comment]
@d12frosted You're our Haskell guy. Thoughts on this issue?

**Comment by d12frosted** [comment]
@TheBB Indeed, this is not an issue for users of `ghc-7.10.2`. As for users of older `ghc` - proposed solutions sound right. Since not all `ghc` users are on latest version, I will check this issue and update documentation if needed.

**Comment by d12frosted** [comment]
Oh well, I missed the point in this problem when I was reading it for the first time. So yeah, with `ghc-mod-5.2.1.2` and new versions of `cabal` - `ghc-mod` doesn't work. And this is known. But since there is already new version of `ghc-mod` (`5.4.0.0`) that fixes this problem, and you can use this version even with `ghc-7.8.4`, I don't see any point in adding these workarounds into documentation (despite the fact that they work). So, @TheBB from my point of view, this should be closed by now. :smile:

**Comment by TheBB** [comment]
Good enough for me.
