### ISSUE TITLE
parentheses all turn red when format codes

### ISSUE THREAD

**Issue by liuchong** [syl20bnr/spacemacs#6617]
https://github.com/rust-lang/rust-mode/issues/160

please refre to the above issue about rust layer, what I found is that after I format codes, the parentheses will turn red like this:
![parenthese_turn_red](https://cloud.githubusercontent.com/assets/236058/16906109/033e45f6-4ce4-11e6-8095-86526611c7e0.png)

not sure it's something wrong of spacemacs or rust-mode, anybody could help?

thanks!

**Comment by TheBB** [comment]
This is just rainbow-delimiters being confused if the buffer changes too much. It happens in other modes too. For example if you re-enable rust-mode it'll re-parse the whole buffer and everything will be fine. It should be reported to rainbow-delimiters if anywhere.

**Comment by liuchong** [comment]
ok, created one issue there:
https://github.com/Fanael/rainbow-delimiters/issues/25

**Comment by Fanael** [comment]
While I don't deny this is a bug in rainbow-delimiters, I'm not really certain that's the case.

> It happens in other modes too.

I never remember anything like that happening here.

Moreover, [this](https://github.com/rust-lang/rust-mode/issues/160#issue-166017317) makes me doubt it's actually a rainbow-delimiters problem:
> on the other hand, when I use my own configuration without spacemacs, just "racer, ac-racer, company-racer, toml-mode", there is no such issue.

I'd bet on something messing too much with `syntax-ppss` or `font-lock` internals. The real question then is what *is* this "something".

**Comment by liuchong** [comment]
I'm working for the company with rust, so I'd try to find out some code with the same problem on rustfmt,

> https://github.com/rust-lang/rust-by-example/blob/master/src/file.rs

which maybe you would like to test on the code.

**Comment by Fanael** [comment]
Cannot reproduce the issue on the given code, even when using spacemacs.

Can anybody post some code on which the issue is *known* to occur?

**Comment by TheBB** [comment]
https://gist.github.com/TheBB/623f141ace67aba440891851c3c586a4

This reproduces the issue for me.

Note that as @liuchong says you have to scroll past the beginning of the file, which is a problem with the one he posted because it fits on my screen. With this one I can put my cursor at the end, invoke `rust-format-buffer` and it repros.

Also I'm sure you're aware, but note that if you try to repro with Spacemacs you need to enable the `colors` layer to get rainbow-delimiters.

**Comment by Fanael** [comment]
So.

You're both using Emacs 24, because the bug does not occur in Emacs 25, as rust-mode uses `font-lock-ensure` if present, which somehow avoids the bug. This function does not exist in Emacs 24, so rust-mode falls back to `font-lock-fontify-buffer`, whose behavior in this case is closer to `font-lock-flush`.

I started `emacs -Q`, patched rust-mode to use `font-lock-flush` instead, moved to line 608 of your code, reformatted the code and evaluated `(syntax-ppss)`. The result:

    (-27 17829 nil nil nil nil -37 nil nil (16789 17281 17285 17363 17381 17586 17609 17613 17646 17800 17829))

The first number here is the nesting level, which is clearly wrong. Therefore, it's a rust-mode bug, not related to rainbow-delimiters.

**Comment by TheBB** [comment]
Okay, thanks!

The correct upstream issue is then https://github.com/rust-lang/rust-mode/issues/160

Probably unlikely to be fixed if it's really a non-issue in Emacs 25.

**Comment by Fanael** [comment]
See rust-lang/rust-mode#161.

> Probably unlikely to be fixed if it's really a non-issue in Emacs 25.

Emacs 24 will be with us for quite some time still thanks to all these Debians and RHELs and what not, so if I were the rust-mode maintainers, I'd fix this.

**Comment by TheBB** [comment]
Oh, that was simpler than I imagined then.

Thanks again. :-)

**Comment by Fanael** [comment]
It's simple because it's a workaround, not a fix.

**Comment by liuchong** [comment]
https://github.com/rust-lang/rust-mode/pull/161
The above merged, I've tested it -- downloaded the rust-mode.el and put it into my elpa to replace the old one -- but still have the issue.
Anyway, I've upgraded my emacs to version 25, and the problem gone. 🌚 
Thanks a lot!

**Comment by TheBB** [comment]
You also have to delete the compiled file (rust-mode.elc) if you do that. By default Emacs will load the compiled file if it exists, even if the regular file is newer.

**Comment by liuchong** [comment]
oh yes, the problem is fixed, thanks!
