### ISSUE TITLE
fail to finish fresh installation

### ISSUE THREAD

**Issue by phinicota** [syl20bnr/spacemacs#6648]
#### Description

I am not able to finish spacemacs installation (completely fresh).
Might be worth mentioning:
- I'm behind a corporate proxy (got my http_proxy and https_proxy variabels in environment)
- Already tried the [`--insecure` fix](http://spacemacs.org/doc/FAQ.html#orgheadline4) and the [ssh/dns fix](http://spacemacs.org/doc/FAQ.html#orgheadline14).
- It doesn't seem to be completely frozen: If I `C-g` whilte it's stuck, I'm in a working state missing keybindings and configurations.
#### Reproduction guide

1- Install Emacs from some source
2- Obtain spacemacs (tried cloning and zip file)
3- Run Emacs (tried `---insecure` too)
4- Choose vim mode and any option (base or recommended install)

_Observed behaviour:_

**FIRST LAUNCH**
![first_launch](https://cloud.githubusercontent.com/assets/6539305/17023939/45bfc1c6-4f2c-11e6-93de-21ac4024882c.png)

**AFTER FIRST LAUNCH**
![second_launch](https://cloud.githubusercontent.com/assets/6539305/17024204/61288186-4f2d-11e6-8ee1-93b9d7ed217b.png)

**`--debug-init` OUTPUT**
![second_launch_debug_init](https://cloud.githubusercontent.com/assets/6539305/17024210/6778430a-4f2d-11e6-80a8-63f2ae5e1180.png)
#### System Info

I am running:
Debian Jessie
GNU Emacs 24.4.1 (although tried also 24.5.1 from debian testing)
spacemacs-base-0.105.21
#### Backtrace

**Where it hangs on first launch:**
`installing package: ws-butler@spacemacs-base...`

**Successive launches (as seen in images):**
`Loading HOME/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)... done`
**`--debug-init` output:**
`(Spacemacs)    -> init (spacemacs-base)`

**Comment by a13ph** [comment]
@phinicota I had this issue for around two days and I still don't know for sure how I've solved it or how to reproduce it.

My weak guesses:
- Some bad config file/directory existence was overlooked 
- Environment variables were causing trouble (via exec-path-from-shell maybe), which is why when I had success it was running emacs from [funny enough, 3 layers of] ranger
- Compiled elisp leftovers were messing me up between my tries of emacs 24 and 25 (though I doubt that's the case)

Since my success translated easily to my pretty heavy config, and between different versions of spacemacs, it's probably not a branch thing either.

**Comment by phinicota** [comment]
I somehow doubt it could be environment variables, I'm running almost (as far as we can tell) the same installation as a collegue.

The only grand difference we can find is we have different proxy/dns assigned. This [ssh/dns fix](http://spacemacs.org/doc/FAQ.html#orgheadline14) seemed like it could work... could it be missing something? Is there a way I could confirm dns is messing up?

**Comment by phinicota** [comment]
To update on this, I haven't found a solution, but I've tried running it from terminal and `emacs -nw` seems to be working fine. Same with `emacs --daemon` and `emacsclient -nc` afterwards. Any clues?
