### ISSUE TITLE
popwin:special-display-config is not configurable by the user

### ISSUE THREAD

**Issue by r-darwish** [syl20bnr/spacemacs#6649]
`popwin:special-display-config` is set in `spacemacs-visual-ui` and contains hard-coded height. 

The only way for the user to change, for example, the height of the compilation window is to either patch spacemacs's source code or write lisp that manipulates `popwin:special-display-config`.

I believe that we should have some variables for controlling this behaviour.

**Comment by bmag** [comment]
popwin:special-display-config is the variable for controling this behavior. You're expected to change it in user-config if you want to change the behavior.

Is there anything wrong with it?

**Comment by r-darwish** [comment]
I'm not very experience with lisp, but if I understand correctly, since `popwin:special-display-config` is a list, assuming that I want to change the compilation window height then I need to iterate it until I find the compilation window entry, pop it out and push it back in with the new updated height. Is that the recommended method?

**Comment by bmag** [comment]
`popwin:special-display-config` is an [Association List](https://www.gnu.org/software/emacs/manual/html_node/elisp/Association-Lists.html) ("alist"), where each key is a symbol or a string, and each value is a [Property List](https://www.gnu.org/software/emacs/manual/html_node/elisp/Property-Lists.html) ("plist"). The easiest way to change an existing entry is to push a new one:
```elisp
(push '("*Help*" :dedicated t :position right :stick t :noselect t :width 0.3)
      popwin:special-display-config)
```
Because `push` adds the entry to the beginning, it overrides the existing `"*Help*"` entry that appears later in the alist. A cleaner approach is to modify the entry in-place. If you want to change the height of help windows:
```elisp
(plist-put (cdr (assoc "*Help*" popwin:special-display-config))
           :height 0.25)
```
If you want to change an entire entry:
```elisp
(setcdr (assoc "*Help*" popwin:special-display-config)
        '(:dedicated t :position right :stick t :noselect t :width 0.3))
```

> I need to iterate it until I find the compilation window entry, pop it out and push it back in with the new updated height

That's what `assoc`, `assq`, `plist-get`, `plist-put` and others are for. Admittedly, I wouldn't expect beginners to know about all these functions, but intermediate users should know about them. `popwin:special-display-config` uses a complex data structure that requires these functions, and that's too bad for beginners, but it's useful for more experienced users. On the good side, a simple `push` also works well enough for configuration purposes.

It is possible to implement utility functions to manage `popwin:special-display-config`'s data structure. That's more in the scope of Popwin than Spacemacs, and that project doesn't change much anymore, though that doesn't mean we can't implement something in Spacemacs. Personally I'd rather work on other areas, but that's only me.

**Comment by r-darwish** [comment]
Thanks for the suggestion. For me this is enough and this issue can be closed. I do think that at least the existence of `popwin` should be documented somewhere, as I had to search the word "compilation" in the code to figure out what was resizing my window.
