### ISSUE TITLE
Custom evil keymap (with RET) conflicted with shell

### ISSUE THREAD

**Issue by Ps-Pencil** [syl20bnr/spacemacs#6662]
I have `(define-key evil-insert-state-map (kbd "RET") 'reindent-then-newline-and-indent)` set up but in shell, since I am using evil mode, the shell cannot get the input. Is there anyway to disable it in shell? or any workaround?

**Comment by bmag** [comment]
The conflict is because your choice of keymap was too aggressive. By using `evil-insert-state-map`, you bound `RET` in insert state for all modes (except those that have their own `RET` binding). You also used `define-key`, while Evil provides the more suitable `evil-define-key` function. What you want to do is choose a better keymap.

I'm assuming you want to change `RET`'s behavior only in source code buffers, and only in insert state. Almost all programming major modes derive from `prog-mode`, so you want to bind `RET` in prog-mode's keymap:
```elisp
(evil-define-key 'insert prog-mode-map (kbd "RET") #'reindent-then-newline-and-indent)
```

**Comment by Ps-Pencil** [comment]
Yes! Thank you! Exactly what I was looking for.
