### ISSUE TITLE
Bind indent-new-comment-line

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#669]
This is a useful comment. What this comment does is that when you run it, it adds a new comment line and indent it properly, regardless of you current . The command is bound to <kbd>M-j</kbd> by default, but if I execute it when point is at the end of line, the last character is moved to the next line due to how Vim/Evil cursor works. Not sure If I missed some Vim equivalent.

**Comment by syl20bnr** [comment]
It is perfect on `M-j` for me. To fix it with evil we can `let` the variable `evil-move-cursor-back` to `nil`.

**Comment by syl20bnr** [comment]
Not sure about the above proposition though.

**Comment by syl20bnr** [comment]
@tuhdo When in `insert state` there is no issue, so here what I propose:
- if you happen to be at the end of line in `normal state` then type `a` then `M-j`. It makes sense to do so because anyway you'll want to be in `insert state`.
- in your `dotspacemacs-config` function set `(setq evil-move-cursor-back nil)` it prevent the point from going back when you leave the `insert state`. It _also_ has the side effect of being able to put the point in `normal state` behind the last character of a line! This is what I use, I think that any emacs user using Evil should set this variable to nil but it feels weird compared to vim default so I cannot force it on the user.

**Comment by tuhdo** [comment]
That sounds good to me.
