### ISSUE TITLE
Graphical fill column indicator increases line height

### ISSUE THREAD

**Issue by katusk** [syl20bnr/spacemacs#6707]
#### Description

Graphical fill column indicator increases line height.
#### Reproduction guide
- Start a graphical Emacs with a fresh Spacemacs installation
- Open your new `.spacemacs` file
- Enable fill column indicator by `SPC t f`, this uses a graphical indicator by default if you are in graphical mode
- Make sure the fill column indicator is visible in the buffer area, otherwise there is no anomaly to observe

_Observed behaviour:_
- At the moment you enable the indicator, line height suddenly increases on all visible lines, if the indicator is visible in the buffer area (try `SPC t f` multiple times)
- Moreover, as you navigate between lines with `j` and `k`, the characters on the current line noticeably jump downwards a bit. I guess this is because the current line is highlighted by default, and the indicator is not shown on such lines.
- The observed behaviour is especially annoying in visual selection mode/state: hit 'V' to enter line selection mode/state, then select more than one line in a row by pushing down `j`. As you select more and more lines, and the indicator is not shown anymore on those lines, the height of the selected lines decreases, and you end up with a nice visual contraction effect.
- If you add `(setq fci-always-use-textual-rule t)` to your `dotspacemacs/user-config` section in your `.spacemacs` file to always use a non-graphical indicator even in graphical mode, the anomalies go away.

_Expected behaviour:_
- Enabling the indicator in graphical mode with a non-textual rule should retain visual line height across all visible (and non-visible) lines
#### System Info
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp)
```

**Comment by d12frosted** [comment]
Hey @katusk,

I could not reproduce it on OS X. I wonder if it's somehow related to theme you are using. Also, what is the value of `fci-rule-character`?

**Comment by katusk** [comment]
Hey @d12frosted,

I started with a fresh Spacemacs installation and dotfile in order to reproduce the issue, so the theme is the default one, `spacemacs-dark`. The value of `fci-rule-character` should be the default one, which is 124 according to `C-h v fci-rule-character`, full output:

> fci-rule-character is a variable defined in `fill-column-indicator.el'.
> Its value is 124
> 
> Documentation:
> Character used to draw the fill-column rule on character terminals.
> 
> Changes to this variable do not take effect until the mode
> function `fci-mode' is run.
> 
> You can customize this variable.

But its value is not used in graphical mode, I think, unless you set `fci-always-use-textual-rule`, which actually solves my problem---but then I end up with a fill column indicator consisting of characters instead of a nice fill column indicator consisting of non-character graphics.

My guess is, that the graphics object that is rendered line-by-line as a fill column indicator has a larger height, or uses some extra pixels for padding compared to the actual font used, and this increases the line height. Maybe the calculation of what height this graphics object should be is somehow not accurate on Windows, or with certains fonts? I am not sure.

For reproduction purproses, my `.spacemacs` is the default one, where the font is set to "Source Code Pro", which is installed on my Windows system. If I try it with "Consolas" for example, the results are the same unfortunately.

**Comment by syl20bnr** [comment]
I see this on Windows as well but not on Linux and OS X,  I did not try with `emacs -Q`.

**Comment by katusk** [comment]
@syl20bnr, I tried with `runemacs.exe -Q` on Windows in graphical mode, and I could not observe the originally described anomaly. Steps taken:

- `runemacs.exe -Q`
- Open `.spacemacs`
- Fetch and load `fill-column-indicator.el` from spacemacs' `.emacs.d/elpa/fill-column-indicator-20151030.1233` directory by `M-x load-file`
- Enable fci-mode by `M-x fci-mode`

**Comment by sohail-surge** [comment]
I noticed this happening only after installing source code pro. I disabled the font on my system and no longer have the issue.

Before source code pro: https://i.imgur.com/m3WHw6U.gif
After: http://i.imgur.com/xJnp3vG.gif

So could it be a bug in the source code pro fonts on Windows? I don't want to go back to the default Courier New :)

**Comment by alfalfasprossen** [comment]
It may be a bug in how Emacs on Windows draws images. By default fci-mode uses an image to draw the fci in graphical mode. Since using a character by setting `(fci-always-use-textual-rule t)`, it might be bound to using the image, not the font.

**Comment by duianto** [comment]
### In Spacemacs
Reducing the height of the xpm image: `|`, from 17px to 16px, stops the line height from changing when the fill column indicator is enabled.

The xpm image is defined in the `fci-make-xpm-img` function:
https://github.com/alpaker/Fill-Column-Indicator/blob/master/fill-column-indicator.el#L664

It's height is defined by the `height-str` variable:
`           (dimens (concat "\"" width-str " " height-str " 2 1\","))`
https://github.com/alpaker/Fill-Column-Indicator/blob/master/fill-column-indicator.el#L668

the `height-str` variable is set in the `fci-with-rule-parameters` macro:
``  `(let* ((height-str (number-to-string fci-char-height))``
https://github.com/alpaker/Fill-Column-Indicator/blob/master/fill-column-indicator.el#L625

and the `fci-char-height` variable is set in the `fci-get-frame-dimens` function
``` elisp
    (setq fci-char-width (frame-char-width frame)
          fci-char-height (frame-char-height frame))))
```
https://github.com/alpaker/Fill-Column-Indicator/blob/master/fill-column-indicator.el#L620

`fci-char-height` is used in both the `segment-length` and `vmargin` variables. It's also used in the 
`fci-post-command-check` function, to check if the default char width and height has changed. Therefore the `fci-char-height` variable probably should be left alone.

The `height-str` variable is only used for making the fci image, in the `fci-make-pbm-img` and 
`fci-make-xpm-img` functions, that means that it's height can be changed.

Since the line height issue only seems to occur in windows (according to the earlier comments), then the height only needs to be changed in windows.

The line height issue stops occurring when this line:
```
  `(let* ((height-str (number-to-string fci-char-height))
```
https://github.com/alpaker/Fill-Column-Indicator/blob/master/fill-column-indicator.el#L625

 is changed to something like this:
```
  `(let* ((height-str (number-to-string
                       ;; windows issue: an fci image height of 17px, increases
                       ;; the line height, this reduces the height to 16px
                       (if (eq system-type 'windows-nt)
                           (1- fci-char-height)
                         fci-char-height)))
```

For the changes to take effect, either save the file and restart Emacs, or place the cursor in the 
`fci-with-rule-parameters` macro, and press `, e f` to call `eval-defun`, and do the same thing with the cursor in the `fci-make-xpm-img` function.

### In Emacs -Q
1. Start Emacs with the `-Q` argument
2. `M-x` `package-initialize`
3. `S-M-;` `(require 'fill-column-indicator)`
4. `M-x` `fci-mode`

The line height only changes in the About GNU Emacs buffer (it's opened by pressing `C-h C-a`, or from the menu bar, Help > About Emacs).

![about gnu emacs buffer](https://cloud.githubusercontent.com/assets/13420573/26747539/c030653c-47f6-11e7-8ffb-5aa16c41442b.gif)

This is with the default font: `Courier New`, with the font size: `10`, only the height of this line:
> Copyright (C) 2017 Free Software Foundation, Inc

changes, The gap between `Ordering Manuals` and `Emacs Tutorial` remains the same. The copyright text has a smaller font, or maybe it's scaled down? Or could it even be written with another font?

In a new buffer with some lorem ipsum text, or in for example the fill-column-indicator.el file, the line height doesn't change.

![lorem ipsum text](https://cloud.githubusercontent.com/assets/13420573/26747491/69c971f2-47f6-11e7-8155-a77ced9a213a.gif)

Changing the Emacs font to match Spacemacs:
Options > Set Default Font...
Font: Source Code Pro
Font style: Regular
Size: 13

makes every line height change:

![about gnu emacs buffer source code pro 13](https://cloud.githubusercontent.com/assets/13420573/26749129/a7c2c90e-4805-11e7-81b3-88939211b67a.gif)

It's not a Source code pro specific font issue, the gap between the last two paragraphs, also changes with the default font: Courier New, with a font size of: 13.

Another visual difference from Spacemacs, is that there's no gap between the fill column symbols on each line. In Spacemacs there's a 1px gap between the fci symbols, and the gap is still there after reducing the height to 16px as described above.

In Emacs -Q `(frame-char-height (selected-frame))` returns `22` compared to `17` in Spacemacs. That means that in Emacs, the xpm image height needs to be reduced by 6px, to prevent the line height from changing.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: keyboard-layout-layer-readme-update (rev. 94eab3a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion colors emacs-lisp git helm markdown org ranger
            (spell-checking :variables spell-checking-enable-by-default nil)
            syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES
