### ISSUE TITLE
Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by pradyuman** [syl20bnr/spacemacs#6751]
I can't figure out how to use the new bash on Ubuntu on windows as the default shell for spacemacs.

This was my config:

```
(shell :variables
    shell-default-shell 'ansi-term
    shell-default-term-shell "C:/Windows/System32/bash.exe"
    shell-default-height 30
    shell-default-position 'bottom)
```

I tried with shell, term, and ansi-term and none of them worked. Also tried invoking via `M-x term [path]`

**Comment by NJBS** [comment]
I don't believe there's much spacemacs can do about this. This is a known (long standing) issue with Bash on Ubuntu on Windows process.

``` elisp
M-: (start-file-process "bash" "bash-buff" "C:/Windows/System32/bash.exe")
```

Process bash exited abnormally with code 255
Error: 0x80070057

See https://github.com/Microsoft/BashOnWindows/issues/2 for more discussion.

**Comment by pradyuman** [comment]
Thanks for the information! I think that we should keep this issue open till Microsoft fixes the issue so that others can refer to it as an open issue with spacemacs, but not necessarily a problem with spacemacs itself.

**Comment by Nelthorim** [comment]
As a small update to this issue, the upstream bug in Microsoft/BashOnWindows#2 should have been fixed in the newest Insiders release (Windows build 14986). However, it's still impossible to set up *any* Bash shell in Windows as a terminal (tried with Git-Bash as well), given an error like:

`apply: Spawning child process: Invalid argument`
