### ISSUE TITLE
How to disable feature which split window into 2 when run M-x shell

### ISSUE THREAD

**Issue by liuchong** [syl20bnr/spacemacs#6820]
When I type M-x shell, the window will be splited into 2 windows, but I want it keep one window, as I'm usually use a small size window, if it be splited the windows will too small, so I must type C-x 1 to change it back.
Any one knows that how could I write the configuration to disable this splitting? thanks a lot!

**Comment by liuchong** [comment]
seems the build-in command "shell" changed from emacs version 24 (pop to same window) to 25 (pop to seprated window), anything I can do on this?

**Comment by bmag** [comment]
The command `shell` uses `pop-to-buffer`. If you have the Emacs source code, you can see it for yourself by running `SPC h d f shell` to open the function's documentation, and then clicking the link to the function's source.

Because `shell` calls `pop-to-buffer`, you can configure its display via `display-buffer-alist`. Try this:
```elisp
(push (cons "\\*shell\\*" display-buffer--same-window-action) display-buffer-alist)
```

For more info, see the documentation for `pop-to-buffer`, `display-buffer`, `display-buffer-alist` and the relevant sections in the Emacs and Elisp manuals ([Window-Choice](https://www.gnu.org/software/emacs/manual/html_node/emacs/Window-Choice.html), [Choosing-Windows](https://www.gnu.org/software/emacs/manual/html_node/elisp/Choosing-Window.html#Choosing-Window)).

**Comment by liuchong** [comment]
It works, thanks! :+1:

**Comment by liuchong** [comment]
seems it get bad again, while the config "(push (cons ...))" keep as is in .spacemacs/init.el

**Comment by bmag** [comment]
@liuchong hmm, the behavior shouldn't change unless you changed your config or a package that you use has changed it behavior. You can look at the source of `shell` and examing the value of `display-buffer-alist` to try and understand what causes the bad behavior. The `display-buffer` mechanism is explained in the sources I referred to in my previous comment.

**Comment by aa755** [comment]
Another possible way: on my computer `M-x ansi-term` does not split the window (but `M-x shell` does).
