### ISSUE TITLE
[question] how to kill a set of buffers?

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#6827]
`SPC b b` gives me a list of buffers currently opened. Say that I have 20 buffers in that list. Say that I want to `:bd` 9 buffers out of those 20. What is the fastest/idiomatic way to do that in spacemacs?

**Comment by TheBB** [comment]
Mark then with `C-SPC` and delete with `M-D`.

In general, do `C-z` in helm to see a list of available actions (`M-D` should be listed there).

**Comment by ninrod** [comment]
all right. I've tried that, but `M-D` is not working (I'm using gui emacs). I can issue `M-x` no problem. I can also select the buffers with `c-SPC`. 

Is that a way to rebind `M-d` to something like `C-d` ?

**Comment by ninrod** [comment]
Oh, wait. `M-D` is actually `M-S-d`?  Like, I have to press `alt+shift+d` to actually get the bind to work. It's working now. But I'd like to really rebind that to `C-d`.  Thank you @TheBB 

is there an alternative way to manage open buffers ? like a evilfied way, something like [bufexplorer](https://github.com/jlanzarotta/bufexplorer) that opens a list of buffers in a special buffer an lets you manage those buffers using vim keybindings?

**Comment by bmag** [comment]
> is there an alternative way to manage open buffers ?

Yes, enable the layer `ibuffer` and try the key-binding `SPC b B`. There should be info in the Emacs manual (IBuffer is a built-in feature), or by pressing `?` from IBuffer's buffer.



> Is that a way to rebind M-d to something like C-d ?

Yes, there is. By pressing `C-h k M-D` I open a help buffer that tells me that "M-D runs the command helm-buffer-run-kill-buffers (found in helm-buffer-map)". So what you need is to bind `C-d` in `helm-buffer-map` to `helm-buffer-run-kill-buffers`. Something like this should probably work:
```elisp
(with-eval-after-load 'helm-buffers
  (define-key helm-buffer-map (kbd "C-d") #'helm-buffer-run-kill-buffers))
```
- `with-eval-after-load` is to make sure the code runs after `helm-buffer-map` has been defined.
- because of evil-mode, you may need to use `evil-define-key`.
- `C-h k` may do something else in helm sessions, depending on your editing style (vim style and hybrid style with non-nil `hybrid-mode-enable-hjkl-bindings` vs. emacs style and hybrid style with nil `hybrid-mode-enable-hjkl-bindings`).

**Comment by ninrod** [comment]
Thank you very much @bmag. That was very helpful.
