### ISSUE TITLE
Leisurely navigating through files

### ISSUE THREAD

**Issue by herbertjones** [syl20bnr/spacemacs#683]
Idea extended from from PR  #654.

> The PDF viewer _mupdf_, which provides vi-like bindings, such as ```C-f``` and ```C-b```, also provides extra keys which are easier to hit than the previous two.  As a PDF viewer is more focused on viewing files easily, it makes sense to provide such keys.  When a user is only leisurely browsing through a file in _Spacemacs_, it may be nice to have a micro state which emulates the quick page-up/page-down functionality provided in _mupdf_. The keys used there are ```,``` and ```.``` and this commit uses ```SPC ,``` and ```SPC .``` to page up/down and enter the micro state.
> 
> It could be said that having these bindings are redundant, as most keyboards have PageUp and PageDown keys.  However these are not always convenient to press and some keyboards have them positioned unusually.
> 
> If using the ```,``` and ```.``` keys isn't a good idea, perhaps this could be incorporated into a similar "browsing" micro state.

Extending ```H``` and ```L``` didn't feel right, and using both ```SPC ,``` and ```SPC .``` seems excessive.  I believe a single micro state could encompass the idea of "thumbing through" a file, or files.

https://gist.github.com/herbertjones/94e3e1dd271831d5ea61

Navigation bindings that normally take two key presses, or moving away from the home row, can be replaced with more convenient equivalents.  The mode wouldn't be persistent, so that performing another action such as copy and paste can be done quickly.  Switching windows would also become easy enough to do with a single hand.

Any ideas or improvements welcome.

**Comment by syl20bnr** [comment]
Actually I like a lot your initial idea and a lot less this one. I found out while experimenting with micro-state that non persistent micro-states don't feel right if there is too much bound keys associated to it.

This is why the minimalist micro-state you proposed is very good to do one thing and do it well. I agree that taking `SPC ,` and `SPC .` is too much for just scrolling, so we can put them behind `SPC n` of `SPC s`. Since the micro-state does not bind any alphabetical keys the non-persistent property can be used consistently without thinking about it.

What I propose is to initiate the micro-state via either `SPC s .` or `SPC n .` then pressing repeatedly on `.` will continue the action. You would also find convenient to have two bindings by direction:
- one to scroll by page say `.` and `,` as your proposed
- another to scroll by half page like current `H` and `L` on `<` and `>`

There are a lot of benefit with this micro-state:
- non persistent micro-state will work consistently
- `H` and `L` in `normal state` are free again
- these keys may not be placed differently on other programmers keyboard layouts (not sure about this one)

I'm sorry for the opposite feedback on the PR thread, you can resubmit one.

**Comment by syl20bnr** [comment]
Fixed with #725
