### ISSUE TITLE
how do we resolve the issue that integrated extensions have been updated?

### ISSUE THREAD

**Issue by yilihong** [syl20bnr/spacemacs#6880]
I am curious whether there is a way to update the integrated components automatically.

For example, this gfm export extension for org-mode in Spacemacs has been updated by the original author:
https://github.com/syl20bnr/spacemacs/blob/master/layers/org/extensions/ox-gfm/ox-gfm.el

Original:
https://github.com/larstvei/ox-gfm/blob/master/ox-gfm.el

**Comment by TheBB** [comment]
No, no automatic way. in develop, ox-gfm comes from @syl20bnr's fork which has [this commit](https://github.com/syl20bnr/ox-gfm/commit/f50321f38f92c548d497b6cf7ed1b3ab1c059fc8), missing from upstream. I'm not sure what the deal is exactly but usually we make packages local for a reason. Either because of bugs upstream, or because upstream isn't on MELPA, and so on.

Should be noted at ox-gfm is now part of org-contrib which does cause potential problems.

**Comment by yilihong** [comment]
@TheBB 

Makes sense. thanks for the quick reply.
