### ISSUE TITLE
Make *scratch* Emacs LIsp by default

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#690]
@syl20bnr  We shouldn't change it to `Text`. I guess it is because you want `*scratch*` to be something to temporary store text.  However, we can always create a new temporary  buffer by entering non-existent buffer name. Otherwise this behaviour should be documented.

**Comment by CestDiego** [comment]
if it starts as emacs-lisp I think the startup would be much larger, because it has to load everything that comes to it..flycheck, w/e

**Comment by tuhdo** [comment]
Currently when `*scratch*` is in `text-mode`, after switching to it and insert "(", trying to delete the character with <kbd>backspace</kbd> gives me this error:

> apply: Symbol's value as variable is void: smartparens-strict-mode [2 times]

**Comment by syl20bnr** [comment]
Why should I make it emacs-lisp ? If I'm a clojure programmer and don't hack lisp or don't hack lisp very often it makes no sense for me, I would prefer it to be in clojure-mode.

I cannot impose what scratch buffer must do to the user, moreover it makes the load time to increase as @CestDiego mentioned.

Setting the scratch buffer to a specific major-mode other than text is a user preference and should be set in the dotfile. We can improve the documentation on this point with a scratch section.

**Comment by syl20bnr** [comment]
For the bug you can open an issue, it is not related to scratch buffer.

**Comment by tuhdo** [comment]
The bug was caused when I was working with my C/C++ layer. It's fine now. And yes, I think there should be documentation about the scratch buffer behavior. It is because I use *scratch* buffer frequently to test Elisp code, so when Spacemacs surprised me when the *scratch* buffer is in text-mode.

**Comment by syl20bnr** [comment]
I reopen it to track the update to the documentation.

**Comment by StreakyCobra** [comment]
Putting the following snippet:
```elisp
(setq initial-major-mode 'ruby-mode)
```
in `user-config` or `user-init` doesn't work. It's probably because the buffer get's created between [this](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+distribution/spacemacs-base/config.el#L126-L128) and `user-config`. We can probably extract this as a variable if people need this functionality.

**Comment by d12frosted** [comment]
I don't like duplication of existing variables, that's why it would be nice to make sure that it's possible to configure existing variable. But if it's not really possible to make it safe - I don't mind having `dotspacemacs-***`. 

What I fear is that if we want to support any major mode in scratch buffer - we should set it after layers are initialised. Things that should be tested:

1. Setting it to `org-mode` should not force Emacs to load bundled version of org (it will hurt org layer).
2. Setting it to `ruby-mode` should just set scratch buffer major mode to ruby. 
3. Setting it to not existing `xxx-mode` should just fall to `text-mode`.

**Comment by StreakyCobra** [comment]
You're right, we should make possible for user to customize it. Definitively not "Beginner Friendly" anymore :-)

**Comment by TheBB** [comment]
Can we add a mechanism to revisit the scratch buffer after `user-config` and change the major mode, according to the value of `initial-major-mode`? That wouldn't require a new variable, and it would still let the user configure it in the config function. It would be safe with org as well.

**Comment by TheBB** [comment]
Basically, here: https://github.com/syl20bnr/spacemacs/blob/develop/core/core-spacemacs.el#L194

**Comment by sschuldenzucker** [comment]
@tuhdo, what solved the issue with the `apply: Symbol's value as variable is void: smartparens-strict-mode` for you? I'm gettings this *everywhere* since the most recent update (today).

**Comment by sam217pa** [comment]
https://github.com/sschuldenzucker I do too… kind of annoying, not being able to make a mistake in a text editor…

**Comment by syl20bnr** [comment]
I'm OK with an additional dotspacemacs variable for the scratch buffer, seems required here.
The default major-mode is set to text also to prevent to kick lazy-loading of some package at loading time. I guess that a sane default is to pretend that users don't use the scratch buffer and make no assumption of its content.

**Comment by wginolas** [comment]
I am also getting the `apply: Symbol's value as variable is void: smartparens-strict-mode` in eshell, when I hit Backspace. After I disabled the "Enable smartparens globally."  Toggle with "SPC t C-p" Backspace in eshell works again.

**Comment by TheBB** [comment]
It's now configurable in master. Closing.
