### ISSUE TITLE
react layer: better react file recognition 

### ISSUE THREAD

**Issue by panjan** [syl20bnr/spacemacs#6952]
Hi, react-layer recognizes react files only if you give them a correct suffix or prepend `/** @jsx React.DOM */`.

It would be great if we could detect react files automagically like WebStorm does. Does anyone think that would be useful/possible? I'd be happy to help out.

**Comment by TheBB** [comment]
You have to add regexps to `magic-mode-alist`. See [here](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+frameworks/react/packages.el#L79-L80) for how it's currently done.

Feel free to make a PR with additions.

**Comment by TheBB** [comment]
Note that the CAR instead of a regexp can be a predicate function. So all you need to do is write a function that detects a react file…

**Comment by panjan** [comment]
Thanks for the explanation. I'll look into it.

**Comment by CestDiego** [comment]
@TheBB do you know if magic-mode-alist only checks the first line?  because I have some files that import react but there is some eslint code on top or many other things that are comments as the first line, but the first non comment file is react. So is there a way to make this a thing that counts only the first non-comment-like line?

**Comment by TheBB** [comment]
It checks if it matches the beginning of the buffer. Doesn't have to be the first line, but if so you need a multiline regexp.
