### ISSUE TITLE
org-mode listings have no syntax highlighting on latex exports.

### ISSUE THREAD

**Issue by Dietr1ch** [syl20bnr/spacemacs#7055]
When exporting org to tex, minted should be preferred over plain verbatim for listings. But old verbatim should stay as a fallback when minted is not available.

This is a solved problem, but it's not readily available on the org layer.

Following [this post](http://joat-programmer.blogspot.cl/2013/07/org-mode-version-8-and-pdf-export-with.html), these settings worked.

``` elisp
;; Use minted
(add-to-list 'org-latex-packages-alist '("" "minted"))
(setq org-latex-listings 'minted)

;; Add the shell-escape flag
(setq org-latex-pdf-process '(
                              "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
                              ;; "bibtex %b"
                              "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
                              "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
                              ))

;; Sample minted options.
(setq org-latex-minted-options '(
                                 ("frame" "lines")
                                 ("fontsize" "\\scriptsize")
                                 ("xleftmargin" "\\parindent")
                                 ("linenos" "")
                                 ))
```

Things to discuss,
- There must be a variable in org layer for toggling this, but should minted be default (if available).
- Should shell-escape be enabled? Not enabling it would block this feature.

Regarding the options,
- Changing fontsize seems reasonable as most samples won't fit.
- Line numbering might be required (turning it off should be a layer setting).
  - xleftmargin fixes line numbering alignment. (See this [question](http://tex.stackexchange.com/questions/252263/alignment-of-minted-line-numbers) on tex-exchange)
- Lines on top and bottom seem customary, maybe leaving an option to turn them on is useful.

**Comment by jappeace** [comment]
I don't know where to post this but I had an issue with minted:
I was getting `stringp nil` when trying to use or minted like this.
The reason was that for some source block didn't have a language provided.

Please make minted first be able to deal with no language provided source blocks, or at least show a line number and a clear error message before trying to make this default. This is an example org file that won't be exported with minted enabled:

```
#+BEGIN_SRC
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException:
  Specified key was too long; max key length is 767 bytes
#+END_SRC
```
Producing the following error messages:

```
(Fout: No word lists can be found for the language "".)
org-babel-exp process nil at position 2...
assq: Wrong type argument: stringp, nil
```
For this to be default I would expect at least an error message: "at line x there was no langauge provided for source block". Alternatively you could also make the default behaviour that produces no language for minted, since minted can handle that.
