### ISSUE TITLE
Setup isn't unattended

### ISSUE THREAD

**Issue by codygman** [syl20bnr/spacemacs#7067]
Setup requires user to confirm our is okay to kill buffers so you can't just run setup and go do something else.

**Comment by TheBB** [comment]
Packages are free to do whatever when compiling, there's not much we can do to guarantee an automatic installation.

**Comment by codygman** [comment]
Couldn't we disable all confirmations for setup and then enable them after?

**Comment by TheBB** [comment]
We could advise `y-or-n-p` perhaps, but it sounds risky. It's like answering without knowing what the question is.

**Comment by TheBB** [comment]
To paraphrase Simon Peyton Jones, what if a package asks

```elisp
(when (y-or-n-p "Launch the missiles?")
  (launch-missiles))
```

and we have advised `y-or-n-p` to always return yes?

**Comment by cpaulik** [comment]
@TheBB you are fast. Commenting from the future :smile:

![screenshot from 2016-09-08 23-37-05](https://cloud.githubusercontent.com/assets/380927/18367976/e603a036-761d-11e6-9e7f-d03964a553a4.png)
 
Anyway I agree with you. And just advising `y-or-n-p` would probably not be enough since some packages like e.g. `pdf-tools` will also ask for the sudo password if they need to install system packages.

**Comment by codygman** [comment]
I didn't know there were packages that needed sudo. I suppose there isn't a sane way to handle this. I wonder if advising yes-or-no-p in cases except the sudo one you mention is possible though.

**Comment by d12frosted** [comment]
<img width="779" alt="screenshot 2016-09-12 22 19 08" src="https://cloud.githubusercontent.com/assets/6507913/18449243/1d83b4da-7937-11e6-9cef-2597db172c76.png">

💃 I like the jokes!

**Comment by JAremko** [comment]
https://github.com/JAremko/spacemacs/blob/master/Dockerfile#L124 works for me.
