### ISSUE TITLE
when will the BibTeX layer be added to the master branch?

### ISSUE THREAD

**Issue by yilihong** [syl20bnr/spacemacs#7082]
curious when will the has the BibTeX layer be added to the master branch?
could it be done in the next release? thank you.

currently I don't know where the helm-bibtex is installed and how to change the config related to helm-bibtex. for example, I want to change the Fallback option Google Scholar's address to a US (instead of UK) by adding this line to my user config:

`(setf (cdr (assoc "Google Scholar" helm-bibtex-fallback-options)) "http://scholar.google.com/scholar?q=%s")`

On spacemacs startup, error message: Error in dotspacemacs/user-config: Symbol's value as variable is void: helm-bibtex-fallback-options

**Comment by NJBS** [comment]
The BibTeX layer should be coming in the [next major release](https://github.com/syl20bnr/spacemacs/blob/develop/CHANGELOG.develop#L103).

The reason you're getting an error on startup is because helm-bibtex is lazily loaded and that variable (which is now deprecated by the way) does not exist until the package has loaded. Try the following instead:

``` elisp
  (with-eval-after-load 'helm-bibtex
    (setcdr (rassoc "https://scholar.google.co.uk/scholar?q=%s"
                    bibtex-completion-fallback-options)
            "http://scholar.google.com/scholar?q=%s"))
```

**Comment by yilihong** [comment]
@NJBS 

thank you very much!
