### ISSUE TITLE
python layer not support for python async 

### ISSUE THREAD

**Issue by chenyangguang** [syl20bnr/spacemacs#7143]
My .spacemacs config like this : 

   dotspacemacs-configuration-layers
   '(
     git 
     org
     php
     python
     vim
     syntax-checking
     version-control

But the python layer does't support for python async , for example : 

async def get_stocks_by_range(params): 

it would checked to said "invalid syntax" . Does it means there is a  problem support for  python layer?  Or may be the syntax-checking layer?

**Comment by bmag** [comment]
Please use this template for bug reports: https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report

The backend for auto-completion doesn't support async yet. ([source](https://github.com/davidhalter/jedi/issues/775#issuecomment-247599105))

If your problem is with syntax checking, then probably the checker is using an older python version.

**Comment by Miciah** [comment]
@chenyangguang, [the Jedi 0.12.0 release notes](https://github.com/davidhalter/jedi/blob/master/CHANGELOG.rst#0120-2018-04-15) mention `async` support; does the latest upstream package resolve the issue?
