### ISSUE TITLE
counsel-projectile-switch-project cannot open file

### ISSUE THREAD

**Issue by goofansu** [syl20bnr/spacemacs#7195]
When not in a project, always says "You're not in a project"

When in a project, it open files as an empty buffer as the path is nested with current project.
For example, `spc pp` in  `project1`, choose a file in `project2`, it will open an empty buffer as `project1/project2/file`.

FYI, 

1. I've upgraded to melpa version `counsel-projectile-20160916.1319` and `projectile-20160921.902`.

2. `projectile-switch-project-action` is `counsel-projectile-find-file`

https://github.com/ericdanan/counsel-projectile/issues/11

**Comment by ericdanan** [comment]
It looks like the path to `file` is not expanded correctly somehow. Instead of simply expanding `file` from `project2`, `project2\file` is expanded from the project root at the point where you called `counsel-projectile-switch-project`: either `project1`, or the error message if you were not in a project.

To see if the problem has to do with counsel-projectile specifically, or projectile more generally, you may want to see what happens if you call `projectile-switch-project` instead of `counsel-projectile-switch-project` (with `projectile-switch-project-action` bound to `projectile-find-file`).

**Comment by TheBB** [comment]
I can reproduce this.

> you may want to see what happens if you call projectile-switch-project instead of counsel-projectile-switch-project (with projectile-switch-project-action bound to projectile-find-file).

This one works fine.

**Comment by d12frosted** [comment]
Hm. I can not reproduce it. Does `projectile-project-p` return proper values in both cases?

**Comment by d12frosted** [comment]
I also can't reproduce it with default `spacemacs.el` file (choosing `ivy` on setup).

**Comment by goofansu** [comment]
@d12frosted Thanks. I'll clean install develop branch to try.

**Comment by ericdanan** [comment]
I was unable to reproduce the error in emacs but my setup was a little messed up and I can reproduce it now that I made sure to update all packages. So the problem may not be related to spacemacs at all, sorry for the mess.

What happens is that for some reason, when `counsel-projectile-find-file`  is called as an action of `counsel-projectile-switch-project`, the former command's actions do not keep track of the root of the project to switch. I don't really understand why this happens, but I pushed a commit that solves the problem for me in emacs.

Please let me know if you still have problems.

**Comment by goofansu** [comment]
Hi, @ericdanan, `counsel-projectile-20160926.547` is ok. Thank you for the quick fix.

**Comment by ericdanan** [comment]
You're welcome.

**Comment by d12frosted** [comment]
Closing as it was an upstream issue that is fixed now. Thank @goofansu for reporting and @ericdanan for quick fix 😸
