### ISSUE TITLE
is this supposed to happen?

### ISSUE THREAD

**Issue by JoshRagem** [syl20bnr/spacemacs#7198]
I'm using spacemacs in the terminal (iterm2) and I found today that if I push and hold up/down and then push fn, then release up/down, then release fn, emacs will continuously repeat the up/down movement--so I slowly scroll to the top/bottom of the file.

I tried to google for this but I find it difficult because there are so many things that deal with fn and scrolling in emacs.

**Comment by d12frosted** [comment]
I can reproduce it both in Terminal.app and in iTerm 3. But I am in favour of closing this issue as it's not related to Emacs or Spacemacs, because this behaviour is specific to Terminal.app, iTerm 3, OS X or whatever. You can reproduce the same behaviour in `nano` or just in the shell (with `up` arrow to walk through history). 💃 😸 Though I must admit - this bug is funny 😸

**Comment by JoshRagem** [comment]
That's funny, I didn't think to try other apps. Thanks!
