### ISSUE TITLE
keyboard-layout bepo leads to error with helm and git-gutter+

### ISSUE THREAD

**Issue by letheed** [syl20bnr/spacemacs#7264]
#### Description :octocat:

Emacs opens a Warning frame on startup saying `Error (use-package): helm :config: Wrong type argument: keymapp, nil`
#### Reproduction guide :beetle:
- Start Emacs
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
 better-defaults
 (c-c   :variables c-c  -enable-clang-support t)
 colors emacs-lisp emoji git
 (haskell :variables haskell-completion-backend 'intero)
 helm
 (keyboard-layout :variables kl-layout 'bepo)
 markdown rust
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts syntax-checking
 (version-control :variables version-control-diff-tool 'git-gutter version-control-global-margin t)
 yaml)
```

**Comment by NJBS** [comment]
Can you restart spacemacs using `--debug-init` and provide the backtrace it returns?

**Comment by letheed** [comment]
[MSG.TXT](https://github.com/syl20bnr/spacemacs/files/507343/MSG.TXT)

**Comment by letheed** [comment]
I just noticed that if `version-control-diff-tool` is set to `git-gutter+`, the warning is:
```
Error (use-package): git-gutter+ :init: Wrong type argument: keymapp, nil
Error (use-package): helm :config: Wrong type argument: keymapp, nil
```
`git-gutter` and `diff-hl` don't produce the first line. Is it a different bug or related?

**Comment by NJBS** [comment]
I'm not sure if it's related or not. All three options don't cause any errors for me. `--debug-init` should have caused a \*backtrace\* buffer to appear on the first error that it encountered while starting up. Did no such buffer appear for you during startup? Note that you can also use `SPC t D` to toggle debugging on errors after startup if you're able to consistently cause that error to appear (maybe see if it appears when `SPC f e R` is called for example).

Additionally, can you try commenting out any personal configuration in your `.spacemacs` file to help narrow down the error's origins?

**Comment by letheed** [comment]
After some more investigation, turns out `(keyboard-layout :variables kl-layout 'bepo)` is the culprit.
Both errors go away if I disable the layer. The bepo layer used to work properly, so I didn't suspect it.

**Comment by bersace** [comment]
Any update on this ? I too hit this error messages since I activated keyboard-layout with bepo.

**Comment by emacs18** [comment]
I would like to share a similar problem which may shed light on this issue as well.

https://github.com/emacs-helm/helm-org/issues/5 is regarding "wrong-type-argument keymapp" error while spacemacs starts up. This error is caused by the following line within helm-org-autoloads.el:

``` elisp
(easy-menu-add-item nil '("Tools" "Helm")  ...)
```

Spacemacs seems to activate all packages one by one in a loop before going onto other follow-on steps, i.e., all autoload files are loaded for all packages. It has activated helm package prior to activating helm-org package. However merely activating, i.e., loading helm autoload file, is not sufficient to define helm keymaps. It appears that one must also do (require 'helm-config) to define helm keymaps to be able to call easy-menu-add-item for helm-org. At least this is my understanding of helm-org issue #5 whose url I shared before.

If there is a way to tell spacemacs that when we activate helm package, that we also must evaluate (require 'helm-config), then I think the helm-org issue can be resolved.

**Comment by emacs18** [comment]
I submitted https://github.com/syl20bnr/spacemacs/pull/12713 to fix helm-org activation problem.

**Comment by emacs18** [comment]
This can be closed as far as I'm concerned.
I have not noticed this issue in a long time.
