### ISSUE TITLE
origami vs evil code folding

### ISSUE THREAD

**Issue by tobimensch** [syl20bnr/spacemacs#7291]
Evil can't fold xml/html, while origami can.

With origami I had some disappointing results when trying
to fold C++ code that works perfectly fine with evil.

I think spacemacs should support selecting a code folding method
based on the source code type.

**Comment by tobimensch** [comment]
I think it would be a sensible default to use origami for xml/html and evil for everything else.

**Comment by deb0ch** [comment]
Also had issues folding c++ with origami, it kept bugging with extremely long error messages, saying basically that it couldn't parse the code.

**Comment by agzam** [comment]
I doubt we would ever be able to get perfect folding for all possible languages. But maybe there's a way to fold in languages supported by origami: 
C
C++
Clojure
Go
Java
Javascript
PHP
Perl
Python
elisp

and make the rest to fold using evil

**Comment by siddharthist** [comment]
There is now the `dotspacemacs-folding-method` variable. Does that solve this issue?

**Comment by deb0ch** [comment]
At the moment `dotspacemacs-folding-method` is a "one choice for all", whereas the discussion here is to select a folding method according to the major-mode. So no, it does not solve this issue as-is.

Maybe it could be an alist like below ?

```elisp
'((c-mode . evil)
 (c++-mode . evil)
 (emacs-lisp-mode . origami)
 (js2-mode . origami)
 (t . evil))                 ;; default value
```

**Comment by tobimensch** [comment]
@deb0ch 
Your suggestion is pragmatic. I could live with that.

**Comment by deb0ch** [comment]
I don't know if this solution would be fully satisfying though. 

If there are too many rules it would clutter the `dotspacemacs`. If we select one method because the other one doesn't work it makes little sense to make the choice visible to the user, though He should be able to overwrite the behaviour.

One solution could be to have one such alist behind the scenes with all the obvious rules, and let the user overwrite it whith whatever he puts in the alist in his `dotspacemacs`. Basically merging a spacemacs-defined alist with a user-defined one. I'm just wondering if it would feel like some kind of "black magic". If it doesn't feel like a "mysterious, complicated" behaviour it could be good.

Maybe there is a compromise to find here, or maybe the "two alists solution" is just good.

**Comment by deb0ch** [comment]
Plus, should the `js2-mode` rule be defined in the `javascript` layer, or should all the rules for all the modes be defined in the same place like `spacemacs-core` ?
