### ISSUE TITLE
Auto-completion not working in web-mode?

### ISSUE THREAD

**Issue by mmcnl** [syl20bnr/spacemacs#7322]
#### Description :octocat:

Auto-completion not working in web-mode?
#### Reproduction guide :beetle:
- Start Emacs
- Open a junk file with .html suffix
- Paste in some html content, eg

```
<html>
<body>
<div>
    <h1>Example Domain</h1>
    <p>This domain is established to be used for illustrative examples in documents. You may use this
    domain in examples without prior coordination or asking for permission.</p>
    <p><a href="http://www.iana.org/domains/example">More information...</a></p>
</div>
</body>
</html>
```

_Observed behaviour:_ :eyes: :broken_heart:
- Start typing and notice that no auto-completions are offered 
  <img width="887" alt="screen shot 2016-10-08 at 12 06 24 am" src="https://cloud.githubusercontent.com/assets/1498727/19211203/cfbebe7a-8ceb-11e6-83a5-bc8d3cec287f.png">

_Expected behaviour:_ :heart: :smile:
- auto-completions are offered when typing
- Switch to ruby-mode and enable auto-completion
- Now auto-completions are offered when typing
  <img width="949" alt="screen shot 2016-10-08 at 12 05 39 am" src="https://cloud.githubusercontent.com/assets/1498727/19211207/dfa9d3b0-8ceb-11e6-8bf4-f1fb3f733e35.png">
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.200.0
- Spacemacs branch: develop (rev. ff95f2a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(html auto-completion)
```
#### Backtrace :paw_prints:

```
<<BACKTRACE IF RELEVANT>>
```

**Comment by NJBS** [comment]
That's odd, To my knowledge the html layer shouldn't require any external dependencies for auto-completion. I've tried reproducing using your example and I get the following:
![html company](http://i.imgur.com/zmmGibP.png)
Can you confirm that auto-completion is toggled on (either by looking for the unicode "a" in your modeline or by toggling it on and off using `SPC t a`) then trying the same example as shown in my screenshot and reporting the results?

Additionally, could you give us the value of `company-backends-web-mode` using `SPC h d v`?

**Comment by TheBB** [comment]
> Start typing and notice that no auto-completions are offered

What are you typing and where?

**Comment by mmcnl** [comment]
@NJBS 
```
company-backends-web-mode is a variable defined in ‘config.el’.
Its value is
((company-web-html company-css :with company-yasnippet)
 (company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
 (company-files :with company-yasnippet)
 (company-dabbrev :with company-yasnippet))
```

**Comment by NJBS** [comment]
Considering my personal configuration completely disables yasnippet I don't believe that's the case 😄 .

The `html` layer defines two backends for completion out of the box, `company-web-html` & `company-css`. It will only offer suggestions from these two backends and these suggestions are in fact what you're seeing when you type `he|`. If you would like your offered completions to additionally include any word that might be in your buffers, you can add `company-dabbrev` to your backends for web-mode as well. 

So something like this:
``` elisp
  (push '(company-web-html company-css company-dabbrev) company-backends-web-mode)
```

Note that this will likely clutter your completions since almost everything you type will now match to something. There are a ton of completion backends for company out there, so try looking around to see if you find something more tailored to your needs if `company-dabbrev` turns out to be overkill.

**Comment by mmcnl** [comment]
@NJBS Thanks for the suggestion. That exact code didn't seem to work for me but adding to my web-mode-hook did:
```
                      (set (make-local-variable
                            'company-backends) '((
                                                  company-web-html
                                                  company-css
                                                  company-dabbrev-code
                                                  company-dabbrev
                                                  )))
```
