### ISSUE TITLE
Install guide on Ubuntu not working

### ISSUE THREAD

**Issue by Canoh** [syl20bnr/spacemacs#7363]
Hello I am trying to install Spacemacs, but without success. On Ubuntu, it should be to run the following command;
`git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`

the repository is cloned , but when I boot emacs from terminal, or application, I am still met with the standard GNU Emacs version screen. I have Emacs v. 24.3.1 installed.

Any help in resolving this would be appreciated.

**Comment by d12frosted** [comment]
Make sure that there is no `$HOME/.emacs` file.

**Comment by Canoh** [comment]
I have tried 'sudo rm ~/.emacs' and this command says 'No such file or directory', which leads me to conclude that I do not have this file.

**Comment by TheBB** [comment]
>  I have Emacs v. 24.3.1 installed.

You should be told at startup that this is too old. Spacemacs requires Emacs 24.4 or newer.

**Comment by d12frosted** [comment]
Oh right. Totally forgot about version requirements 😸 😕

**Comment by Canoh** [comment]
Yes, upgrading my emacs to a proper version solved my issue. Thanks

**Comment by deb0ch** [comment]
Ooooooooooooooh I had that same issue a few days ago when trying to install spacemacs on a friend's computer :open_mouth: I will check if it was a version issue then.

Nevertheless, the guy just abandoned on the spot because no time, and now I'm not sure if he will even retry.

Maybe it would be good to put a notice on the website, that appears at the same time as the command when you click "install".

**Comment by riju-t-r** [comment]
I had the same problem after installed spacemacs

Try to delete ,

> $HOME/emacs 

This works fine in my case
