### ISSUE TITLE
Can't bind anything to C-z

### ISSUE THREAD

**Issue by tsmarques** [syl20bnr/spacemacs#7372]
#### Description
`C-z` bind is stuck as evil-exit-emacs-state.

#### Reproduction guide
- Start Emacs
- Try to bind `C-z` to some other command

*Observed behaviour:*
Trying to bind `C-z` to a command/function doesn't work. Even after calling `global-unset`.
I even commented all the layers at `dotspacemacs-configuration-layers` and all my configurations at `dotspacemacs/user-config`

*Expected behaviour:*
`C-z`'s bind stuck as `evil-exit-emacs-state`

#### System Info
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.1
- Spacemacs branch: master (rev. 3706a42)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion syntax-checking emacs-lisp c-c  gtags org git c-c -ide)
```

**Comment by d12frosted** [comment]
This function (`evil-exit-emacs-state`) is defined in `evil` package. And it's bound in that package as well. Please, try using `with-eval-after-load` macro to override `evil` keybindings. 

```
(with-eval-after-load 'evil
  (bind key ....)
```

Put that in your `user-config` function.

**Comment by TheBB** [comment]
Emacs editing style is implemented by always putting the user in evil's emacs state. This state is a special state that passes through every keybinding to Emacs defaults, *except* `C-z`, which is the keybinding used to enter and exit emacs state. The editing style additionally hijacks the evil state changing functions to always put the user in emacs state, which is why `C-z` doesn't *actually* put you in normal state when you use this editing style. However the key is still bound, so if you want to bind it to something else in the global map you have to unbind it in evil-emacs-state-map first.

**Comment by bmag** [comment]
Just adding my 2 cents:

> Try to bind C-z to some other command

Not descriptive enough. There are multiple ways to bind a key, you're just using the wrong keymap. See https://github.com/syl20bnr/spacemacs/wiki/Keymaps-guide and https://www.masteringemacs.org/article/mastering-key-bindings-emacs for good reading material on the matter.

P.S. wow, you responded very quickly @TheBB @d12frosted

**Comment by tsmarques** [comment]
@d12frosted 
I've tried the following but it didn't work:

```
(with-eval-after-load 'evil
    (global-set-key (kbd "C-z") 'my-command))
```

@bmag @TheBB 

I didn't know about the map, I thought they were in the global one. I fixed it by unbinding the key from the map and the rebinding to it to what I needed:

```
(define-key evil-emacs-state-map (kbd "C-z") nil)
```

Thank you all!
