### ISSUE TITLE
company-emoji are not rendered

### ISSUE THREAD

**Issue by abhi18av** [syl20bnr/spacemacs#7395]
#### Description

The issue is with the company-emoji completions which doesn't display a preview of the emoji, though
- the emoji, once typed is rendered fine
- there's an ugly blank space where the emoji should have been 
  #### Reproduction guide
- Start Emacs
- any org-mode flle
- `company-emoji-init`
- type in something like `:smi...`
#### System Info
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 3706a42)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(mu4e auto-completion better-defaults emacs-lisp clojure git markdown org haskell html rust python sql ipython-notebook react xkcd emoji finance search-engine dash fasd pandoc ess chinese restclient prodigy gtags deft colors
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      (ruby :variables ruby-enable-enh-ruby-mode t ruby-test-runner 'rspec ruby-version-manager 'rbenv)
      spell-checking syntax-checking version-control)
```

**Comment by TheBB** [comment]
I'm guessing you need to install a font with those symbols, that's all.

**Comment by abhi18av** [comment]
@TheBB well I use Hack font, should I change it? It's utf8 compliant .

And, is the pop-up font different from buffer font?

**Comment by TheBB** [comment]
Fonts can't be UTF-8 compatible or incompatible, that's not how it works. Fonts have symbols for some but not all of the Unicode codepoints. If you have a font with those symbols and Emacs or your system is correctly configured to use that font for that range of codepoints then you should see them. (I do.) UTF-8 is one of several encodings for Unicode, but the font doesn't ever need to know anything about the encoding.

The pop-up uses symbols from the font, but in the buffer it's rendered with images. That's why it works fine in the buffer.

**Comment by abhi18av** [comment]
Okay, so set the default fonts in the `.spacemacs` but still it's the same case. Have I missed something entirely...? 

Perhaps, the default mac settings don't have the full range of unicode?  I did try to find our something in regional settings but there isn't anything of use.

**Comment by TheBB** [comment]
I don't know much about font settings, sorry. Especially not on OS X.

**Comment by abhi18av** [comment]
Oh, okay. Well, let's wait - someone might pitch in.
