### ISSUE TITLE
Layout order inconsistent when loading from file

### ISSUE THREAD

**Issue by jluttine** [syl20bnr/spacemacs#7396]
#### Description :octocat:

When loading layouts from a file, the order of the layouts is inconsistent.
#### Reproduction guide :beetle:
- Start Emacs
- `SPC l 2`, accept creating new layout `y`, name it `foo`
- `SPC l 3`, accept creating new layout `y`, name it `bar`
- Save layouts `SPC l S`, choose `foo`, then `bar`, then `[>done<]`. Name the file `foobar`.
- Restart Emacs `SPC q r`
- Open layout file `SPC l L`, choose `foobar`.
- Check layout order `SPC l`: you see `2: bar` and `3: foo`
- Restart Emacs `SPC q r`
- Open layout file `SPC l L`, choose `foobar`.
- Check layout order `SPC l`: you see `2: foo` and `3:bar`

_Observed behaviour:_ :eyes: :broken_heart:

When loading the layouts file, the order of the layouts changes: every other
time it is `bar,foo` and every other time it is `foo,bar`.

_Expected behaviour:_ :heart: :smile:

I expected the layout order to be `foo,bar` every time I load the file.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.1
- Spacemacs branch: develop (rev. a6e5ad2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(csv yaml extra-langs emacs-lisp ranger
     (python :variables nose-capture nil python-test-runner 'pytest pytest-cmd-flags "")
     ipython-notebook
     (shell :variables shell-pop-autocd-to-working-dir nil)
     (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence nil auto-completion-private-snippets-directory nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
     (syntax-checking :variables syntax-checking-enable-by-default t)
     (haskell :variables haskell-process-type 'stack-ghci)
     latex git org c-c   html javascript colors lua markdown ibuffer
     (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
     (window-purpose :variables purpose-default-layout-file "~/.emacs.d/.cache/purpose-layouts/ "))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11
#### Backtrace :paw_prints:

```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
First, this is an excellent bug report, thank you. 

Second, I can reproduce the bug with the given recipe. I can also reproduce the bug outside of Spacemacs, both with Emacs 24.5 and 25.1. Note that the following recipe creates a `~/.emacs.d/persp-confs` directory, you can safely delete it when you're done.

**Reproduction guide :beetle:**

- save this file as `test-init.el`:
```elisp
(require 'package)
(package-initialize)
(setq persp-auto-resume-time -1)
(require 'persp-mode)
(persp-mode)
```
- start emacs: <kbd>emacs -Q -l test-init.el</kbd>
- create persp foo: <kbd>M-x persp-switch foo</kbd>
- create persp bar: <kbd>M-x persp-switch bar</kbd>
- get persps: <kbd>M-: (persp-names-current-frame-fast-ordered)</kbd>. Output: `("none" "foo" "bar")`
- save persps `foo` and `bar` to file `foobar`: <kbd>M-x persp-save-to-file-by-names foo bar [\<done\>] foobar</kbd>
- exit emacs: <kbd>C-x C-c</kbd>
- start emacs: <kbd>emacs -Q -l test-init.el</kbd>
- load persps: <kbd>M-x persp-load-state-from-file foobar</kbd>
- get persps: <kbd>M-: (persp-names-current-frame-fast-ordered)</kbd>. Output: `("none" "bar" "foo")`
- exit emacs: <kbd>C-x C-c</kbd>
- start emacs: <kbd>emacs -Q -l test-init.el</kbd>
- load persps: <kbd>M-x persp-load-state-from-file foobar</kbd>
- get persps: <kbd>M-: (persp-names-current-frame-fast-ordered)</kbd>. Output: `("none" "foo" "bar")`

**Observed behaviour: :eyes: :broken_heart:**

Output of `(persp-names-current-frame-fast-ordered)` is inconsistent. It alternates between `("none" "foo" "bar")` and `("none" "bar" "foo")`.

**Expected behaviour: :heart: :smile:**

Output of `(persp-names-current-frame-fast-ordered)` should be consistent - `("none" "foo" "bar")` everytime.

I will report an issue upstream.
