### ISSUE TITLE
Web mode regression: evil-matchit not being applied

### ISSUE THREAD

**Issue by posva** [syl20bnr/spacemacs#7415]
Hello,

After updating to the latest version (tested on the develop branch too), I found out that web mode is not working as well as before.
More specifically the the evil-matchit doesn't apply. I tried toggling it with `SPC :` then `evil-matchit-mode` with no success.
Here is a gif
![oct-16-2016 12-24-04](https://cloud.githubusercontent.com/assets/664177/19416846/982e505e-939b-11e6-9295-9328240de131.gif)

I'm using `==` to indent the `}` at the end. Notice how I manually insert the matching `}` and `'`
#### System Info :computer:
- OS: darwin
- Emacs: 24.5.3
- Spacemacs: 0.200.2
- Spacemacs branch: develop (rev. 6cb349e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp git markdown org
                 (shell :variables shell-default-height 30 shell-default-shell 'term shell-default-position 'bottom)
                 spell-checking syntax-checking version-control c-c++ games speed-reading xkcd emoji yaml markdown html javascript react swift osx eyebrowse elixir typescript python)
```

**Comment by posva** [comment]
just a comment

**Comment by duianto** [comment]
The issue was opened a while back, it might be helpful if you could post your current system info.

### This is what I'm seeing:
`evil-matchit-mode` is enabled when I open a `.html` file or switch to `web-mode` in a new buffer.

Therefore jumping between braces, quotes and tags by pressing: `%`
works as expected.

You mentioned pressing `==` to indent the closing curly bracket, for me it auto indents after one or two seconds after typing `}`.

<details><summary>
System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f5fddc425)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 (colors :variables colors-enable-nyan-cat-progress-bar t)
 emacs-lisp git helm html javascript lsp
 (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
 multiple-cursors
 (org :variables org-agenda-files
      '("~/org/notes.org"))
 (python :variables)
 ranger
 (shell :variables shell-default-shell 'eshell shell-default-height 30)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

---

>Notice how I manually insert the matching } and '

It sounds like you might be looking for `smartparens` to complete the closing pair.
It seems to be disabled by default in `web-mode`.
