### ISSUE TITLE
Error (use-package): helm-ag :init: Symbol’s function definition is void: evilified-state-evilify

### ISSUE THREAD

**Issue by pldimitrov** [syl20bnr/spacemacs#7445]
Happened after a fresh install of emacs-plus using homebrew and cloning spacemacs into `~/.emacs.d`.

OSX: 10.11.6
emacs-plus: 25.1

**Comment by pldimitrov** [comment]
Tried updating spacemacs, tried development branch, updated packages... nothing helps.

my "fix" for now:
`(setq warning-minimum-level :emergency)` in `~/.spacemacs`

**Comment by DGalt** [comment]
Brand new to spacemacs. Moved my old ~/.emacs.d folder and cloned repo, haven't done anything else. Same error on opening emacs.

**Comment by lukehayes** [comment]
This is happening to me on a fresh install. It was working fine an then I added"

`(setq-default helm-make-build-dir 'build')`

and now I have the exact same error.

**Comment by krisleech** [comment]
Same here on fresh install of Emacs 24.5.1 on Ubuntu 16.04.

**Comment by myklam** [comment]
Same here. Also have

Error (use-package): elm-mode :config: Symbol's value as variable is void: spacemacs-useful-buffers-regexp

**Comment by RensDimmendaal** [comment]
Same here.

Error (use-package): helm-ag :init: Symbol's function definition is void: evilified-state-evilify

**Comment by vadzimt** [comment]
Run into the same issue on Fedora 25 (GNU Emacs 25.1.1)
```
Error (use-package): diff-mode :config: Symbol’s function definition is void: evilified-state-evilify
Error (use-package): flycheck :init: Symbol’s function definition is void: evilified-state-evilify-map
Error (use-package): helm-ag :init: Symbol’s function definition is void: evilified-state-evilify
```

**Comment by francioshu** [comment]
24.4 
Error (use-package): helm-ag :init: Symbol's function definition is void: evilified-state-evilify
Error (use-package): pylookup :init: Symbol's function definition is void: evilified-state-evilify
Error (use-package): anaconda-mode :config: Symbol's function definition is void: evilified-state-evilify

**Comment by fzondlo** [comment]
Getting the same error on a fresh install on OSX after running these commands and opening the app:

```
brew tap d12frosted/emacs-plus
brew install emacs-plus --HEAD --with-natural-title-bars
brew linkapps emacs-plus
```

**Comment by chtld** [comment]
I have the same error with you!
Symbol's function definition is void: evilified-state-evilify-map

**Comment by RyodoTanaka** [comment]
I had the nearly same error with you.
And fixed with following procedure.

## Environment
OS : Ubuntu 16.04 LTS 64bit
Kernel : 4.15.0-43-generic
Installed Emacs : Emacs 24.1

## Error code
I got following error at the first time.
`edebug/:init: Symbol's function definition is void: evilified-state-evilify-map`

## To fix
1. Uninstall Emacs24.1 by `apt remove` command.
2. Install Emacs25.1 or newer.
   For me, I installed Emacs26.1 by `apt install` command adding [PPA](https://launchpad.net/~kelleyk/+archive/ubuntu/emacs) repository.
3. Clone `develop` branch into `~/.emacs.d` directory.
4. Launch Emacs.

I hope it will help you.
Bests,
