### ISSUE TITLE
Emacs freezes from time to time

### ISSUE THREAD

**Issue by pspencil** [syl20bnr/spacemacs#7451]
[.spacemacs.txt](https://github.com/syl20bnr/spacemacs/files/533831/default.spacemacs.txt)
#### Description :octocat:

Spacemacs freezes from time to time, usually after some key binding, but the exact keys pressed to trigger the freezing is different each time.

Since it is not consistently reproducible, I am not actually looking for a fix right away. (But if there are any, please tell me.) I am just looking for a way to find out what happened. 
#### Reproduction guide :beetle:
- Sorry. I haven't found a way to consistently reproduce it.
- On average it is about 1-2 times per day.

_Observed behaviour:_ :eyes: :broken_heart:
Emacs freezes. Not responding to any key press. It eats up CPU but memory usage seems fine.

_Expected behaviour:_ :heart: :smile:
Not freezing?
#### System Info :computer:
- OS: Ubuntu 16.04
- Emacs: 24.5.1
- Spacemacs: 0.200.1
- Spacemacs branch: master (rev. 3706a42)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
See dotfile
```
#### Backtrace :paw_prints:

```
<<BACKTRACE IF RELEVANT>>
```

**Comment by NJBS** [comment]
Next time you experience a freeze can you try sending Emacs a SIGUSR2, it will try to unfreeze Emacs and immediately drop you into a debugger with a backtrace of what Emacs was currently running. If you can provide a couple of backtraces it'll be much easier to pinpoint the issue.

**Comment by yoavg** [comment]
I don't know if it is the same bug, but spacemacs freezes to me as well -- I can't characterize the exact conditions, but it definitely happens when I am editing very long lines, such that the word-wrapped text spans almost the entire window, or the entire window (for example the list inside package-selected-packages in .spacemacs). Then, some commands just freeze, sometimes. This happens most often with ":" (switching to ex mode) but also happened with SPC SPC, and with some other movements which I cannot characterize well.

Sending SIGUSR2 displays "Entering Debugger..." in the minibuffer, but still stuck.
Another SIGUSR2 un-stucks it, but clears the buffer, and I need to undo in order to get the content back.

When things are stuck, I often see a white column in the stuck window.

**Comment by Ps-Pencil** [comment]
I switched to Lubuntu not long ago. The frequency has decreased. Haven't seen it stuck for quite a while.

**Comment by stormpat** [comment]
Im having similar issues. It seems to be related to auto-completion. (I have had this issue for many months, but finally read this issue and found the SIGUSR2 command, so i finally got to debug it)

As I suspected the freeze seems to be related to company mode, for me always when in web-mode usually when buffer has mixed html/css/js and maybe even some PHP)

Heres the error message:

```lisp 
Debugger entered--Lisp error: (quit)
  re-search-backward("\\(?:\\_<\\([[:alpha:]-]+\\):\\(?:[^{};]*[[:space:]]+\\)?\\([^{};]*\\_>\\|\\)\\=\\)\\=" nil t)
  looking-back("\\_<\\([[:alpha:]-]+\\):\\(?:[^{};]*[[:space:]]+\\)?\\([^{};]*\\_>\\|\\)\\=" nil)
  company-grab("\\_<\\([[:alpha:]-]+\\):\\(?:[^{};]*[[:space:]]+\\)?\\([^{};]*\\_>\\|\\)\\=" 2)
  company-css(prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer default.php> #<window 3 on default.php> 1456 10264)
  apply(company-idle-begin (#<buffer default.php> #<window 3 on default.php> 1456 10264))
  timer-event-handler([t 22560 24075 136872 nil company-idle-begin (#<buffer default.php> #<window 3 on default.php> 1456 10264) nil 0])
``` 

Will try and narrow it further.

**Comment by bmag** [comment]
IIRC `looking-back` is a slow operation. Combine with Emacs' slowness with long lines and maybe that's the cause. Or maybe not. Probably can be tested by changing the regexp to a simpler one.

**Comment by rodonn** [comment]
I'm also getting fairly frequent freezes when editing a large Latex file. I'm getting a debugger message similar to stormpat where it looks like the `looking-back` operation is what is freezing.

In case it helps anyone else dealing with a bug that causes Emacs to freeze, this will find the pid for Emacs and send SIGUSR2 to it so that you can unfreeze Emacs and see the debugger messages.
`ps aux | grep -ie emacs | grep -v grep | awk '{print $2}' | xargs kill -SIGUSR2`
