### ISSUE TITLE
Counsel find file doesn't complete at first TAB press

### ISSUE THREAD

**Issue by pspencil** [syl20bnr/spacemacs#7516]
#### Description :octocat:

`counsel-find-file` `TAB` completion takes two `TAB`s to complete when the item is not the only one
#### Reproduction guide :beetle:
- Start Emacs
- Use ivy
- `SPC f f`
- `C-j` to navigate to some directory
- Press `TAB`
- Press `TAB`

_Observed behaviour:_ :eyes: :broken_heart:
completion happens at second press

_Expected behaviour:_ :heart: :smile:
completion happens at first press
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:

``` elisp
(markdown yaml
          (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-tab-key-behavior 'cycle auto-completion-private-snippets-directory nil)
          fasd better-defaults emacs-lisp
          (latex :variables latex-enable-folding t)
          git evil-commentary ivy python java
          (shell :variables shell-default-position 'right))
```
#### Backtrace :paw_prints:

```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
I don't think this something we change. Can you test if the same happens if you use vanilla Emacs + Counsel?

**Comment by Ps-Pencil** [comment]
Do you know which option I should pass to emacs to start vanilla emacs?

**Comment by Ps-Pencil** [comment]
I looked at the stuff. It seems in the ivy-side, the correct function to use to complete folder names should be `ivy-alt-done` instead of `ivy-partial-or-done`. The description for these functions doesn't seem to be accurate. 

I added `(define-key ivy-minibuffer-map (kbd "TAB") 'ivy-alt-done)` to dotfile and everything works.

Could you try to do `ivy-alt-done` during `counsel-find-file` when the cursor is on a directory that is not `./` nor `../` to confirm that it completes instead of exiting the minibuffer (which is what it allegedly does)?

**Comment by Ps-Pencil** [comment]
Currently the behaviour of `ivy-alt-done` on a file is to open the file directly instead of completing the name first. Is that the desired behaviour?

The problem seems to be due to `ivy-partial-or-done` not doing what it says it does. I will look into the code.

**Comment by Ps-Pencil** [comment]
Here is the code. The explanation for current behaviour is: 
When `TAB` pressed first time, nothing happens if there is nothing to complete or there might be more than one completion target.
When `TAB` pressed second time, ivy detects there is no change to the input and calls `ivy-alt-done` which goes into the directory, although ivy thinks it will open the file.
```
(defun ivy-partial-or-done ()
  "Complete the minibuffer text as much as possible.
If the text hasn't changed as a result, forward to `ivy-alt-done'."
  (interactive)
  (if (and (eq (ivy-state-collection ivy-last) #'read-file-name-internal)
           (or (and (equal ivy--directory "/")
                    (string-match "\\`[^/]+:.*\\'" ivy-text))
               (string-match "\\`/" ivy-text)))
      (let ((default-directory ivy--directory)
            dir)
        (minibuffer-complete)
        (setq ivy-text (ivy--input))
        (when (setq dir (ivy-expand-file-if-directory ivy-text))
          (ivy--cd dir)))
    (or (ivy-partial)
        (when (or (eq this-command last-command)
                  (eq ivy--length 1))
          (ivy-alt-done)))))

```
I guess ivy people thinks this is the correct workflow? 

It might be worth adding a variable like `spacemacs/ivy-tab-key-behaviour` or some sort to toggle this behaviour.

**Comment by biox** [comment]
One tab is the behavior that everyone ought to expect - having tabs act dfiferently depending on which dir you happen to highlight is bad UX - one tab, one selection, one completion ought to be the default behavior. I never want to spend time thinking about whether or not my directories are unique.
