### ISSUE TITLE
long delay when closing parenthesis when dotspacemacs-smart-closing-parenthesis is not nil

### ISSUE THREAD

**Issue by yoavg** [syl20bnr/spacemacs#7525]
#### Description :octocat:

When `dotspacemacs-smart-closing-parenthesis` is set to t, and the smartparens mode is _not_ enabled, emacs freezes for a while when inserting a closing parenthesis.
The profiler shows the delay is in `spacemacs/smart-closing-parenthesis`.

When I exclude the smartparens package the issue goes away.
#### Reproduction guide :beetle:
- Set `dotspacemacs-smart-closing-parenthesis` to `t` in `.spacemacs`.
- Start Emacs
- Edit a large-ish file (for me it was an .org file with 1080 lines), enter a ")" near the end of the file.

_Observed behaviour:_ :eyes: :broken_heart:
it takes a while to enter the closing paren.

_Expected behaviour:_ :heart: :smile:
entering the closing paren should be immediate.
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.1
- Spacemacs branch: master (rev. 3706a42)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(csv python helm auto-completion emacs-lisp git markdown
     (org :variables org-agenda-files
          (list "~/Dropbox/orgs/")
          org-refile-use-outline-path t org-outline-path-complete-in-steps nil org-refile-allow-creating-parent-nodes t org-refile-targets
          `((nil :maxlevel . 4)
            (org-agenda-files :maxlevel . 4)))
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     syntax-checking latex bibtex themes-megapack ranger emoji)
```
#### Backtrace :paw_prints:

```
```

**Comment by vaz** [comment]
This is happening for me too, most noticeably in moderately-sized org files.

- It is specifically when `dotspacemacs-smart-closing-parenthesis` is enabled.
- In `*Messages* I see `Unmatched expression.` which is an error from `smartparens.el` defined around line 570. But I think that's coming after the bug's delay, since it happens any time the cursor touches the unmatched paren.
- Doesn't matter if smartparens-mode is on or off, or strict mode or not, and has nothing to do with `dotspacemacs-highlight-delimiters`
- Doesn't matter if I omit `smartparens` package from `auto-completion` layer (it's still loaded anyway, I think this is referenced in #6144, other things depend on it).

### Related bug

Also in org-mode, with `dotspacemacs-closing-parenthesis` ON, and with `smartparens-mode` OFF (where `|` is cursor):

```org
* one (|
* two
```

If I press `)` to close the paren, I get:

```org
* one ()|
*) two
```

This only occurs when `dotspacemacs-smart-closing-parenthesis` is non-nil on startup; if it's nil, it doesn't matter if sp is on or not, this extra paren doesn't get added.

----

Is this smart closing parens behaviour not implemented anywhere else, like as an option in smartparens itself (I'm not too familiar but it seems natural there's a more standard smartparens way if auto-insertion is a feature)? Or, is there a quick (or not quick) way to just disable the auto-insertion of closing pair characters?

The `C-q )` escape hatch isn't sufficient for me. (I have my shift keys mapped to insert parens if tapped, so it's reeeeally easy for me to insert an unmatched paren in an org file like this—but it's really worth it when working on code, especially lisps.)
