### ISSUE TITLE
Make ? show/hide keybinding in every transient state

### ISSUE THREAD

**Issue by Somelauw** [syl20bnr/spacemacs#7556]
I noticed that some transient states have a keybinding "?" to show/hide keybindings and other don't.
I think all transient states should have to option because:
- These keybindings take up screenspace. Some transient states like the window one are very wide.
- To experienced users showing them is pointless
- Consistency

Some transient states that already support hiding keybindings using "?":
- ediff
- layout

Some transient states that don't but probably should:
- VCS
- windows

**Comment by duianto** [comment]
The window transient state has gotten the `?` toggle feature in this commit:
Make window manipulation transient hint collapsible https://github.com/syl20bnr/spacemacs/commit/13fd53d65d3197b7d4a4371899a7ec9bab91e7c4
 ("manipulation" has been removed from the name since the commit) 

That commit can be used as a guide for implementing it in other transient states.
