### ISSUE TITLE
Layout splits/buffers not preserved when creating additional layouts

### ISSUE THREAD

**Issue by rjhilgefort** [syl20bnr/spacemacs#7574]
#### Description :octocat:

 Creating multiple new layouts seems to modify splits on previously focused layout on create.
#### Reproduction guide :beetle:
- Start Emacs
- Create new layout `SPC l l`, type new name, focus is changed to new layout
- Create some splits (and open some new buffers for fun, or not, doesn't matter for reproduction)
- Create another new layout `SPC l l`, type new name, focus is changed to new layout
- Create some splits again in the second layout
- Go back to the first layout you created
  
  _Observed behaviour:_ :eyes: :broken_heart:
- Notice that your splits/buffers are not how you left them
  
  _Expected behaviour:_ :heart: :smile:
- Splits/buffers in your first layout should be exactly as you left them
#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.3
- Spacemacs branch: develop (rev. 48c3ecd)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
  `elisp
  ((auto-completion :variables auto-completion-enable-company-help-tooltip t)
  better-defaults colors dash emacs-lisp emoji evil-snipe evil-commentary games
  (git :variables git-enable-github-support t git-gutter-use-fringe t)
  github lua org osx pandoc
  (shell :variables shell-default-height 30 shell-default-position 'bottom)
  shell-scripts themes-megapack tmux version-control vim-empty-lines html javascript markdown syntax-checking rjhilgefort)
  `

**Comment by bmag** [comment]
I can't reproduce this. Make sure to update your packages, you might have an old version of persp-mode.

**Comment by zilongshanren** [comment]
@bmag  I also meet this issue from time to time, but I can't reproduce it stably.

**Comment by SimonGZ** [comment]
This may be unrelated but I wonder if the underlying cause is the same...

I use a minor-mode called [olivetti](https://github.com/rnkn/olivetti/blob/master/olivetti.el) to do nice soft-wrapping of my text windows, and some recent change in Spacemacs/Persp mode has now made Persp mode incompatible with that package. When I have Olivetti enabled and switch perspectives, my other perspectives lose their splits and I get error messages like:

`[persp-mode] Warning: Can not restore the window configuration, because of the error -- (error Window #<window 15 on  *temp*> too small for splitting 3)`

I assume that some change in Persp mode is now in direct conflict with how Olivetti cleans up after itself. (This may not be Spacemacs fault, maybe Olivetti is depending on something it shouldn't.) I'm not enough of an emacs lisp wizard to comprehend exactly what is going on but I wonder if a similar issue could be happening here where Persp mode's behavior has changed in some way and it's now referencing something that gets changed/affected by other minor/major modes like Olivetti.

**Comment by westlywright** [comment]
I can repro this consistently. I have a layout setup for some projects, everytime i switch back to the default layout or close spacemacs and reopen and then back to the layout whatever buffer split I have open on the top most window now fills all previous splits. Sometimes Spacemacs won't maintain the number of splits I left it with.

I've not reported bugs to Spacemacs (new vim user) so i'm not sure what info you all need but if someone wants to enlighten me about logs and such they need to debug I'll be happy to provide.

**Comment by westlywright** [comment]
@rjhilgefort I was able to track this down to golden-ratio, i disabled it and regardless of how many times i switch layouts or kill and restart spacemacs my layouts are preserving correctly. I did not see that in your layer list but figured I might as well mention it

**Comment by rjhilgefort** [comment]
@westlywright I do use golden-ratio, so that would be consistent. That's sad to hear and isn't the first issue I've had due to golden-ratio. @westlywright, do you think the issue you found could be an integration issue when used in Spacemacs? If not, I suppose this can be closed and I'll throw something together an issue for that package.

**Comment by westlywright** [comment]
@rjhilgefort Sadly I'm so new to Emacs/Spacemacs I am unable to answer that question :(
