### ISSUE TITLE
Idea about building layers using Nix/nix-shell?

### ISSUE THREAD

**Issue by sid-kap** [syl20bnr/spacemacs#7578]
# Problem

I just switched from Ubuntu to NixOS, and I'm slowly learning how to get all of my layers working on the new machine.

One problem is that some layers (pdf-tools in particular) require a build step (i.e. running a `make`), and also  depend on some system-level tools and libraries. At first I tried installing these dependencies globally using Nix, and then having spacemacs build the layers. Unfortunately, this did not work. 

To make a long story short, it seems that **some things in Nix can only be done in `nix-shell` or `nix-build`**. You don't need to know all the details, but I'll provide them just in case:
- The build process for pdf-tools involves running a `./configure` script. It turns out that the `./configure` script uses some macros that are provided by `pkg.m4`, which is provided by pkg-config, and which, on a typical Linux machine, is installed at `/usr/share/aclocal`. However, because of the way that Nix works, Nix stores its `aclocal` macros all over the place (separated by the package that installed them); it then uses a patched version of `aclocal` to find these files. As far as I can tell, this patched version of `aclocal`, which knows where to find all the macros, is _only available_ in `nix-shell` or `nix-build`.  
# Possible Solution

We could give users an option to build all packages inside of nix-shell. (For NixOS users, I think this is the only way to successfully build these packages.)

On the surface, this should be a relatively small change: we simply need to replace each call to `make install` (or whatever command we're using to build the package) with `nix-shell --pure --run "make install" -p <list of nix packages the layer needs>`. 

Here lies the catch: we need to somehow know which nix packages each layer needs in order to be built. This list will probably always include `gnumake`, `autoconf`, `automake`, `pkg-config`, and `emacs`; in addition, each package will have its own additional dependencies. (For example, for `pdf-tools` it would be `libpng, zlib, poppler`.)

Where would we get these lists? I suggest that we store them all in the spacemacs codebase somewhere.
# Conclusion

1) Is my understanding of the problem accurate? Is `nix-shell` really the only option for building `pdf-tools`, for example?
2) If so, does my proposed solution sound like a good idea?

**Comment by olejorgenb** [comment]
Some comments:

- I think it's possible to override the nix emacs package to expose additional binaries/libraries to the emacs process. I don't remember exactly how though. It involves `overrideDerivation`.

- If the dependencies is only needed during build, starting emacs from a `nix-shell -p ...` when installing the packages should work.

- There's an effort by the nix community to create nix-derivations for most/all emacs packages: [The state of Emacs](https://github.com/NixOS/nixpkgs/issues/11503) / [nixos-manual](https://nixos.org/nixos/manual/index.html#module-services-emacs)

I'm not sure how smooth the nix-derivations integrates with spacemacs though? Will spacemacs try do download already-installed system-wide packages for instance? 

It doesn't seem straight forward to automate the process, since the actual emacs-derivation need's to be modified when adding a new package.

> Here lies the catch: we need to somehow know which nix packages each layer needs in order to be built.

The build dependencies could probably be extracted from [emacs-packages.nix](https://github.com/NixOS/nixpkgs/blob/0e69fb2f196d553e1db04aff46f50868aec42424/pkgs/top-level/emacs-packages.nix) (or using techniques from the emacs2nix program)

Another problem is run-time dependencies. This is probably not very common (?), but I assume some packages have them. `cscope`, etc.

**Comment by sid-kap** [comment]
As you suggested in your 2nd bullet, the dependencies for the package I care about (pdf-tools) was only needed during build, so using `nix-shell -p` was sufficient.
