### ISSUE TITLE
company mode in org-mode documents is extremely annoying

### ISSUE THREAD

**Issue by ocharles** [syl20bnr/spacemacs#771]
I seem to have `company-mode` always active when editing `org-mode` documents, but it rarely does the right thing. When I finish a line with the word `in`, it often ends up changing to `inaugural` or some other word in the document, and then I have to go back and correct it. I'm not sure auto-completion really makes that much sense when editing plain text.

**Comment by trishume** [comment]
I often find this annoying as well. There's a couple things you could try:

- Switch to using the tab key for completions instead of enter, there's a config variable for this, check the source.
- Disable company mode completion in `org-mode`. I think I already disabled it by default for markdown, and if I haven't I should. It should also really be a default for org-mode and other text-based modes.
- Set company to only offer completions after special characters like `.`, `::` and `->`. There's a setting for this but I forget it, this is how most other IDE's solve this problem.

Ever since I added functionality that disables completion for line ending ruby keywords like `do` I haven't been annoyed with this as much but it does bite me occasionally. I haven't yet decided which of these fixes I want to adopt.

**Comment by TheBB** [comment]
I see no company in org-mode so I believe this is fixed. Please reopen if I'm mistaken.
