### ISSUE TITLE
RFC: Improve Spacemacs experience for new users

### ISSUE THREAD

**Issue by chrisbarrett** [syl20bnr/spacemacs#772]
This is a dump of my experience coaching vim users switching to Spacemacs over the past 2 months. I want to see what improvements people would approve of before I start logging individual issues and submitting PRs.

# tl;dr
- We should automate more parts of the Spacemacs setup procedure
- We should also consider adding an in-Emacs tutorial on setting up everything else
- We need to think about ways to help users customise their keybindings
- We need a better documentation system than GitHub (e.g. [ReadTheDocs][])
 
# Background
I've been hands-on, helping 4 vimmers at work switch to Spacemacs. Three of them have stuck with it and think it's awesome, and the other gave me valuable feedback about what turned them off.

From my experience coaching them and based on their feedback, I can make some general observations about their Spacemacs experience. I'll call them 'users' for ease of writing, but I don't want to imply that I'm speaking for all users. :)

# Issues
1. Users want to jump right in, so they read the Readme.md but not the documentation
2. Users get stuck the moment they need to configure anything that's not in `~/.spacemacs`. They don't know how to manage their own config layers.
3. There are too many ways to configure key bindings, and it's not always clear which to use.
4. Vim users expect to be able to bind whatever they want to `,` as their leader key, and the way Spacemacs hijacks comma for `SPC-m` is frustrating
5. Vim users expect a single keybinding for finding files pretty much anywhere.

## Issue 1: Documentation

As we all know, the documentation needs to be improved. GitHub does not provide a good experience for reading documentation, especially because readmes get scattered around the different layers and neglected. 

We should consider putting our documentation on [ReadTheDocs][]. Flycheck does this and it rocks. We should also make updating the docs standard practice following feature PRs. 

### .spacemacs
The `~/.spacemacs` config file thing is working fine, but users consistently get stuck when they create new config layers and forget to update their `.spacemacs` to wire them up.

We should consider automatically loading any config layers in `.emacs.d/private`.

Configuring spacemacs requires elisp, and there are surprisingly few good tutorials out there on elisp. I might write our own one for inclusion in the documentation.

### config layers

You really need to read the documentation to understand how to use config layers, and we've established that users don't read the documentation. ;)

I think we should *always* create a `config.el` and `keybindings.el` when interactively creating a new layer. We should also improve the explanatory comments in the templates for those files -- I'm happy to submit a PR on that one.

## Issue 3: Customising Keybindings

Configuring keybindings right now is hard. Any time users want to bind something, they have to know which of the following to use:
- `define-key`
- `global-set-key`
- `evil-global-set-key`
- `evil-define-key`
- `bind-key`

These all bind keys in different situations, so if a user picks the wrong one things will work *some of the time*, which is worse than things not working at all!

We can probably write an interactive key binding utility that reads a key sequence, asks which states and modes to bind it in, and then automatically write the correct setting to a keybindings file. Otherwise, we need a flowchart in the documentation. :(

## Issue 4: Customising the Evil Leader

Vimmers expect to be able to bind their stuff to `,` (comma). The current practice of putting ever-changing mode-specific bindings there is not helpful to them, because their own bindings get clobbered. I don't believe mapping `,` to `SPC m` pays its way, given that this is what I see in scala-mode:

![screen shot 2015-03-07 at 3 30 36 pm](https://cloud.githubusercontent.com/assets/836504/6539678/304861e6-c4df-11e4-9b86-2adb18efc85c.png)

That's utterly bewildering, and of course when those mapping were introduced they clobbered my existing bindings which I had set up and *did have meaningful names*. 

I suggest we revert the mapping from `,` to `SPC m` so that users can safely customise their leader again.

## Issue 5: File Navigation and Helm

The first thing experienced Vim users ask me is if we have [Control-P][] or [Command-T][] equivalents in Emacs. I set them up with `helm-for-files` bound to `C-SPC` and they're happy. This puts buffer killing, switching, and file search in one place, and cleanly avoids all the separate emacs-y commands for doing this stuff. The users I've coached unanimously love helm.

I believe `C-SPC` is a good binding, because it's normally used for `set-mark-command` which we never use in evil. If set with bind-key, it works globally, no matter what buffer or state they're in, so they feel confident that they can move around in Emacs without getting lost.

I propose we bind `C-SPC` to `helm-for-files` in the base distribution of Spacemacs.

# Conclusions

I'm hoping none of the above is too contentious. ;) I'm interested in feedback from @syl20bnr, as well as @trishume, @bjarkevad and other regular contributors on these points, because your experiences may be very different!

[ReadTheDocs]: https://read-the-docs.readthedocs.org/en/latest/index.html
[Control-P]: https://github.com/kien/ctrlp.vim
[Command-T]: https://github.com/wincent/Command-T

**Comment by syl20bnr** [comment]
Thank you Chris for the great feedback ! I will comment on the issues keeping the same order.

### Issue 1: Documentation
It is surprising since I believed that the documentation was one of the selling points of spacemacs. It is extensive and pretty up to date. Moreover the documentation on any layer can be accessed directly inside emacs via `helm-spacemacs` on `SPC f e h`.
My initial plan was exactly to follow Flycheck example with texinfo files and export to ReadTheDocs but I don't feel that it is a game changer (and to be honest I find the ReadTheDocs of Flycheck very hard to read because of the style with blue boxes everywhere).

### Issue 2

#### .spacemacs
If this is confusing then we need a tutorial. The explicit declaration of layers is a design choice that is very important. It gives flexibility and make things like debugging easier. If I put some automatic loading somewhere people will right away ask to me for an `exclusion` list. I prefer to write what I need, not what I don't need because it is not what's interesting. If you show me your dotfile I don't care that you exclude `xxxx` layer, but I do care about what layers you are using.

#### config.el
I agree, people don't read the doc. This is true for every single manual (even programming languages nowadays). My only answer to this plague is the chat room with courtesy and good pointers to the related documentation parts (can be a markdown or better, the source code).

I agree for `config.el` because the contributed layers show that it is useful. On the other hand `keybindings.el` is misleading and I could consider harmful. `keybindings.el` is for key bindings that are not bound to a package or extension (i.e. key bindings for emacs built-in commands). The contributed layers show that it is not required, I should not mention it in the doc.

`guide-key` while fantastic is not fully adapted to spacemacs, we need to develop our own `guide-key` with sane handling of mode specific bindings and explicit docstrings instead of command names. This is something I want before a 1.0 release. It is not impossible that `guide-key` could do the trick, the advanced functionalities have still to be reviewed but I won't tolerate any more work-around with it, the fact that we have to define prefix commands to have group name is already a work-around that I don't like very much.

### Issue 3: Key bindings
I fully agree on this and this is tricky to address. Maybe it should be part of a `build your own layer` tutorial. I think we can narrow the key bindings for new users to `define-key`, `evil-leader/set-key` and `evil-leader/set-key-for-mode`, the names are easy to grasp and straightforward, once the tutorial shows them how to alter a keymap of a package (say helm), how to add a key on the leader and then how to do it specifically for a mode, they have good tools to get started.

### Issue 4: Leader and guide-key
I use the shortcut all the time and it allows to keep 4-key sequences reasonable, we can put an emphasis on the fact that it is customizable in the dotfile.

I don't want to change the mode specific leader. The philosophy of spacemacs is to set on `SPC` the leader that vimmers normally put on `,` so for me `,` is free as a default.
It is possible to swap these keys for the die hard vimmer in the dotfile but I cannot make it a default.... this is spacemacs! and there are pretty much only 2 good candidates for a leader... space and comma :-)

### Issue 5: File navigation
Aaaaarrgh it was not enough hard to find a key binding for the `ido` and `helm` micro-states that you want me to give away `C-SPC` ? :-)
Why not use `C-p` and `C-t` ?

**Comment by tuhdo** [comment]
@chrisbarrett If they want something like `CtrlP`, why don't you introduce them Projectile? It is built into Spacemacs by default. And `helm-for-files` is deprecated see https://github.com/emacs-helm/helm/commit/0fda52b45f901402cdc80a331b02078f5301fec6

**Comment by chrisbarrett** [comment]
@tuhdo ooh, that's good to know re `helm-multi-files`. 

In a user's first attempt at Emacs, there is a limited number of things they can deal with before they throw up their hands and decide it's too different and complicated (and these Vimmers I'm teaching are going into Emacs *expecting* it to be too difficult). `helm-for-files` is a winner because is combines
- switching buffers
- killing buffers
- finding recent files
- finding stuff anywhere using locate/mdfind

The fact that a user only has to learn one keybinding (instead of 3) to do all the above is critical, and it's a real confidence builder in their first exposure to Emacs. To belabour the point, I don't teach `switch-to-buffer` and `kill-buffer` or even `find-file` (since they already know `:e`). I just teach `C-SPC`, which is helm.

From a teaching perspective, Projectile doesn't work. It isn't available on first run and is only available in certain contexts, so I'd still have to teach those standard emacs commands. I have maybe 10 minutes to blow them away with Emacs before they need to take a break and projectile doesn't make the cut. I teach projectile in lesson 2, but I mainly focus on `helm-ag`. No need to confuse them with *another* way to switch buffers. ;)

**Comment by chrisbarrett** [comment]
@syl20bnr 

## Documentation

If you've considered and decided not to do ReadTheDocs then that's good. My fundamental issue was that none of these guys would read the documentation, so I was wondering how we can make it more appealing. Maybe we could split the documentation.md into parts and host them on GitHub Pages?

## .spacemacs

Sounds like a tutorial will be the best way to help new users with this. I'll create an issue.

## Keybindings

> ... define-key, evil-leader/set-key and evil-leader/set-key-for-mode ...

Nice, those sound pretty reasonable for beginning users.

## Leader

I think my issue with customising `SPC m` is that there's a lot of dev churn at the moment. It's frustrating when a new Spacemacs release overrides a command you've previously bound under that prefix. If you have made a project-level decision on that, I'm not going to argue against it. :)

## File navigation with helm

`C-p` is super-important (evil-paste-pop). `C-t` is pop-tag-mark, which tbh I've never used, so that might be better. Something I'd like to emphasise is that the command should work in any state (be it `insert`, `normal`, or even `emacs`) for new users to feel like they're safe and in control.

That micro-state that got added to helm overrides marking helm candidates. The alternative key for that, `M-SPC` gets intercepted by the window system on Ubuntu. For those users I trained, I had to bite the bullet and give them some inscrutable elisp to restore their expected behaviour.

**Comment by emmanueltouzery** [comment]
Related to "Prefix Command" display, I think there used to be displayed something like "Group: refactor" and so on. Whether it was or not, that would be a real plus compared to the current situation, if it's achievable.

**Comment by stormpat** [comment]
I have about the same timespan (~2months) with spacemacs, the major difference being, vim was not my main editor before i found spacemacs. I learn more each day i use it, and even starting to grasp lisp, learning mostly with Clojure though.

Big props to @syl20bnr for the hard work, and what i would see as excellent documentation.

Some feedback:

I would really love to see the documentation in another medium than i long Github readme. I was thinking about some kind of website, as a cheat-sheet -like index with instant search, and maybe a section for how-to's and maybe some tutorials and what not.

I would be willing to contribute with something like this, if theres any interest from the community.

**Comment by trishume** [comment]
@chrisbarrett et al: Great ideas. This is a really great writeup with some good ideas.

For my part I like the idea of a tutorial to go along with the more detailed documentation. In fact, I'll try to write one this evening. I'll mainly cover the basics of customization: the `.spacemacs` file and how to create layers. I might do another tutorial on some cool starter tricks for people coming from vim.

**Comment by trishume** [comment]
I also think `spacemacs-mode` could be the beginner discoverability engine of spacemacs, and to that end I've already added buttons for important things. I think it could also benefit from a "Protip™" section that just highlights useful functionality.

**Comment by syl20bnr** [comment]
@chrisbarrett I'm reluctant to change the conventions and key bindings but I have to do it and I'm fine to pay the price of unsatisfied users. The process to get good conventions requires iterations, spacemacs key bindings won't be stabilized until 1.0, the thing is, I have no idea when 1.0 will be ready, but we progress toward stability.

I'm convinced it is worth the trouble, what spacemacs tries to achieve via the conventions is unique in the emacs ecosystem and as elpa becomes more and more popular I think it is an essential component of a strong distribution. The bazaar model can benefit from this.

In the tutorial we also need to address the remapping of keys to other keys, this is something common in Vim but not so common in emacs, there are facilities to do it though. My main concern about key to key mapping is that spacemacs uses almost all of them so while the users must be able to do remapping we have to clearly warn them about doing it.

@chrisbarrett In `develop` branch I pushed what I find a great new `paste` micro-state (seems to be great to to use while not being intrusive). Pressing `p` again while replace the pasted text with `evil-paste-pop` and `P` with `evil-paste-pop-next`, this the same approach than `expand-region`. Thank you for pointing me to this. Sooooo `C-p` could be free again which is really cool for Vim users! :-)

@trishume that's very neat that you work on a tutorial ! For the tips part I have it in my todo list for ages, but never achieved the architecture of it, it must have some kind of intelligence in order to provide tips only for spacemacs layer and the layers declared in the dotfile. It must be easy for anyone to contribute tips at the layer level.

**Comment by trishume** [comment]
@syl20bnr I think I agree with @chrisbarrett that it would be nice to have a place for users to put their personal shortcuts. The main letters under the `SPC` prefix could be considered reserved for use by Spacemacs so you could feel safe in adding additional bindings without overwriting users shortcuts that they have memorized. This prefix could be something like the `SPC o` that I use for my personal shortcuts or the `,` that @chrisbarrett proposes.

**Comment by chrisbarrett** [comment]
@syl20bnr 
> In develop branch I pushed what I find a great new `paste` micro-state

That sounds awesome.

@trishume 
> This prefix could be something like the `SPC o` that I use for my personal shortcuts or the `,` that @chrisbarrett proposes.

The vimmers will really want their `,` because it's easy to type and they have a muscle memory investment, but a special prefix under `SPC` would be ok if there's a commitment not to bind anything to it. Anyone using `SPC ,` for anything?

**Comment by syl20bnr** [comment]
Seems like we _all_ don't read the doc :-)
https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.md#reserved-prefix
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#reserved-prefix-command-for-user

**Comment by chrisbarrett** [comment]
Guilty as charged. ;P

**Comment by syl20bnr** [comment]
As a middle ground for the `,` case, setting it to `nil` could completely disable it.

**Comment by syl20bnr** [comment]
Oh... it already works... was not intended in the first place. This should be mentioned in the doc, even in the readme.

**Comment by chrisbarrett** [comment]
Wait, setting what to nil exactly?

**Comment by syl20bnr** [comment]
`dotspacemacs-major-mode-leader-key`

**Comment by trishume** [comment]
Looks like @syl20bnr in his vast awesomeness has gone back in time and implemented our suggestions in the past! I didn't remember that my arbitrarily claimed `SPC o` was made into a reserved prefix, almost back when I was the only other user to reserve it for :P 

And `dotspacemacs-major-mode-leader-key` being set to nil seems like a good solution for vimmers. Probably should be mentioned as an option for those that want to liberate their leader somewhere in the docs.

**Comment by trishume** [comment]
I've also written up a draft tutorial and posted it on my blog: http://thume.ca/howto/2015/03/07/configuring-spacemacs-a-tutorial/

I still hadn't written a blog article on Spacemacs and I've been slacking off on articles for it so I put it there. I hope you don't mind linking to an external source. My website is a Github repo that you can submit issues and PRs too if it is wrong or needs updating: https://github.com/trishume/trishume.github.com

**Comment by chrisbarrett** [comment]
@trishume nice!

**Comment by tuhdo** [comment]
@chrisbarrett I have to note that `helm-multi-files`` removed the auto activation of `helm-locate`; to invoke it, you have to press `C-c p` manually because Helm maintainer it's an error to put async Helm source together with sync source. Seee this issue: https://github.com/emacs-helm/helm/issues/878. If you are on Linux or OS X, things  aren't that bad, so using `helm-for-files` are still reasonable. If you want to make it easier for them to use Helm Projectile with a single command, you can always add Helm Projectile sources to `helm-for-files-preferred-list`:

```elisp
(setq helm-for-files-preferred-list '(helm-source-buffers-list
                                      helm-source-buffer-not-found
                                      helm-source-projectile-projects
                                      helm-source-projectile-files-list
                                      helm-source-recentf
                                      helm-source-bookmarks
                                      helm-source-file-cache
                                      ;; helm-source-files-in-current-dir
                                      ;; helm-source-locate
                                      ))
```

I removed `helm-source-files-in-current-dir` and `helm-source-locate` because it's really slow when working remotely with Tramp.

**Comment by syl20bnr** [comment]
@trishume this is great ! I will PR some corrections tomorrow.

**Comment by syl20bnr** [comment]
@stormpat does <kbd>SPC ?</kbd> looks like something you described ?
A printable cheat-sheet would be cool, we have to generate it though, a search for `<kbd>.*</kbd>` in the repo gives around 1.3k occurrences and some key bindings are missing (like elixir).

This emacs distribution is just silly :-)

**Comment by edwintorok** [comment]
regarding `CtrlP` replacement, I found `helm-projectile` quite nice, after I modified it to show only files tracked by git:
```
  (setq projectile-enable-caching nil)
 ;;; Show only files tracked by git in helm-projectile
  (setq projectile-git-command "git ls-files -zc --exclude-standard")
  (bind-key (kbd "C-SPC") 'helm-projectile)
```

However this can be quite slow when not inside a project, in which case maybe a fallback to your suggestion of `helm-for-files` would be nicer.

This is similar to how I use CtrlP in vim, and its a lot faster (and cleaner) than using find on large projects:
```
let g:ctrlp_by_filename = 1
let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }
let g:ctrlp_user_command = {
\ 'types': {
\ 1: ['.git', 'git --git-dir=%s/.git ls-files --cached --exclude-standard'],
\ 2: ['.hg', 'hg --cwd %s locate -I .'],
\ },
\ 'fallback': 'find %s -type f'
\ }
```

**Comment by trishume** [comment]
@edwintorok good idea. Does that snippet also include files that aren't yet added to git but would be by `git add -A`. I think git filtering is a good idea but it should only do that in git repos and work by filtering out gitignored files rather than filtering in committed files.

Also thanks for reminding me about this issue, I had forgotten about it and there is a lot of good stuff in here that hasn't been done yet. One suggestion I particularly like is the universal keybinding wizard/macro/whatever.

On the other hand a lot of this has been done or is being done. Perhaps @chrisbarrett could edit his post to use the Github checkbox syntax and then check off the ones that are done.

**Comment by tuhdo** [comment]
It would be nice if we adapt [this Emacs Lisp tutorial](http://bzg.fr/learn-emacs-lisp-in-15-minutes.html) for Spacemacs (i.e. add Spacemacs specific examples). That is, we're going to add another button to the quick help, so users are comfortable with basic Emacs Lisp for customization.

**Comment by edwintorok** [comment]
@trishume: good point, I've updated my `~/.config/git/ignore` with https://github.com/github/gitignore/blob/master/Global/Vim.gitignore to ignore Vim's backup files. Now the default projectile configuration works for me and I don't need to override `projectile-git-command` anymore: `helm-projectile` shows all files that are in the project directory, except those ignored by .gitignore.

**Comment by TheBB** [comment]
I think this discussion has run its course, though there are some good ideas here we can keep going with.
