### ISSUE TITLE
Feature request: Calendar layer

### ISSUE THREAD

**Issue by eedahl** [syl20bnr/spacemacs#7741]
http://jameswilliams.be/blog/2016/01/11/Taming-Your-GCal.html
I've recently set up Spacemacs with calfw and orgcal (which needs request and alert). This is great for viewing your org-mode agenda in a calender, or even syncing with Google Calendar (or other calendars afaik). This is so useful that it should comprise a calendar layer in Spacemacs.

I don't know how to do it, and don't exactly have time right now, but I'm filing this issue in case there are any takers, and for future reference (in case I find chance to do it).

**Comment by eedahl** [comment]
For reference, I installed these packages: calfw org-gcal request alert. That already gets you going.

For Google Calendar, I made an app follwing more or less the instructions of [org-gcal](https://github.com/myuhe/org-gcal.el):
(require 'org-gcal)
(setq org-gcal-client-id "someid.apps.googleusercontent.com"
      org-gcal-client-secret "somesecret"
      org-gcal-file-alist '(("calendarid" .  "~/org/calender.org")))

The command org-gcal-fetch fetches your calendar. You can sync with org-gcal-sync. Add the calendar to your agenda file list, and your google calendar entries should show up in the calfw calendar under cfw:open-org-calendar.

An issue is that the usual keys of calfw love to use SPC, so I have to use alt+m.

**Comment by sineer** [comment]
Hello friends,

I started a calendar layer here to use calfw with org-gcal here:

https://github.com/sineer/spacemacs-calendar-layer/

I haven't really "tweaked" it yet but it does load calfw and org-gcal package then I am able to run cfw commands.

It's missing key bindings as I haven't made up my mind on what keys to use yet.

Also spacebar key open calendar info in calendar buffer that kinda breaks spacemacs spacebar so it would be nice to overwrite calf bindings I suppose...

**Comment by dudelson** [comment]
Hi,
I discovered calfw this week and have tweaked the keybindings to make them work better in spacemacs.

https://github.com/dudelson/spacemacs-calendar-layer

I made the following changes to @sineer's layer:

1. I thought "SPC d" didn't really make sense as a mnemonic for calendar, and there will probably be another layer in the future that could use that prefix better, so I put the calendar under applications instead. Unfortunately "SPC a c" is reserved for calc, so it's "SPC a l" right now, which I'll admit is not much better. I'm open to suggestions. "SPC a o l" will open the org-mode version of the calendar.
2. TAB opens the details view instead of SPC. TAB used to be "next item", which I moved to C-j. I thought this would go nicely with C-k for "prev item", but it turns out that function doesn't exist, and my elisp is almost nonexistent, so I opened an [issue](https://github.com/kiwanami/emacs-calfw/issues/104) on calfw.
3. Deferred loading of all packages in the layer.

I haven't played around with the layer a whole lot yet and I'm sure issues will come up, but now that there are no keybinding conflicts, I'm wondering if there's anything preventing this layer from being merged into spacemacs (I've never written a layer before so I don't know what the process is)? For one thing, I haven't tested the compatibility of the other calfw extensions (howm, ical, etc.).

**Comment by dudelson** [comment]
I completely broke the layer with my previous commit and failed to notice it for a while because I had an old copy loaded into spacemacs. I added a second commit which fixes deferred loading. In the process of writing this commit, I noticed that "SPC a o l" is already bound to `org-store-link`, so I changed the keybindings to "SPC a C" and "SPC a o C", respectively. Perhaps these are better?

**Comment by sineer** [comment]
Cool! Glad to hear someone is trying to maintain that plugin and maybe merge in spacemacs someday like you said would be nice indeed 👍 

I admit I haven't been using that plugin recently so I can't comment on key bindings really I suppose like you said "SPC d" don't make sense it was just my preference for personal use noticing how it was free and easy to remember as in Date.

I'll tag my repos as unmaintained and forward people to your fork :-)

Thank you for your effort!

I look forward to have time to start using calfw with your improved layer again soon (I figure xmas time maybe).

**Comment by eedahl** [comment]
Glad to see people have been at this. I didn't use Spacemacs for a while, but checking it out again I immediately remembered this.

**Comment by dudelson** [comment]
Haven't really done anything with this since I last posted, but I should have some time this summer, so take a look and let me know what improvements can be made :+1:

**Comment by eedahl** [comment]
One thing is I couldn't seem to be able to install it by adding to the dotfile!

**Comment by dudelson** [comment]
Sounds great! I actually went through a period recently where I had no need for a calendar at all, but this seems like a good impetus for me to revisit the calendar layer. I'll try to look into the other layer repo code this week and see what can be combined.

**Comment by Asalle** [comment]
Please do it guys, I'm rooting for you!
