### ISSUE TITLE
[Bug] maximized-at-startup should only maximized if not yet maximized

### ISSUE THREAD

**Issue by mateuspv** [syl20bnr/spacemacs#7744]
#### Description :octocat:
Sometimes I maximize the emacs window before it load , since I have set
maximized-at-startup to true, Spacemacs loads then undo my maximization.

#### Reproduction guide :beetle:
- Start Emacs
- change "dotspacemacs-maximized-at-startup" to true("t") in your configuration
- Restart Emacs
- Before emacs load, maximize it
- Wait for emacs load, it will undo the maximization.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp javascript git shell clojure)
```

Let me know if there's some info missing,
Regards < 3

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/pull/7745

**Comment by mateuspv** [comment]
I was looking at this line but didn't know how to change it ^_^
Thanks <3

**Comment by deb0ch** [comment]
Is it your desktop environment that automatically maximizes Spacemacs upon startup ? Or is it slow enough to get to that line that you have the time for maximizing it manually ? Or are you just super fast ?

I managed to have that maximization instruction as early as possible in the startup process so that maximization should seem instantaneous at startup, which is the case for me.

Really curious about that :smirk_cat:
