### ISSUE TITLE
[Documentation] Improve ivy documentation

### ISSUE THREAD

**Issue by gilbertw1** [syl20bnr/spacemacs#7754]
In a number of ways Ivy behaves very differently than helm does, yet all of the Spacemacs documentation is very Helm specific with little or no mention of Ivy. I would like to rectify this situation by improving the documentation to include how to use Ivy adequately in these scenarios.

I'm happy to work on this documentation update, however I'm curious as to what would be the best form for it to take. Should we:

**A)** Update each section in the documentation that mentions helm in the documentation with an equivalent mention of Ivy and how it fits into the current section.
  - *This could be potentially confusing to new users as Helm is the default and probably what most new users will select.*
 
OR

**B)** Leave the majority of the documentation unchanged and add a section specifically discussing Ivy that highlights the ways in which it deviates from Helm.

I've been running into a number of scenarios where Ivy deviates significantly from Helm (example #7752) in common usage scenarios, and I think this would be a great way to make Ivy a lot more friendly for people to get up and running with.

**Comment by nixmaniack** [comment]
I would vote for B rather than updating it at every place where we mention `helm`.

Also, pointing to the [`ivy`'s documentation](http://oremacs.com/swiper/#key-bindings) will be helpful as I believe it's quite good. The mentioned issue in #7752 is also described in that doc. 

There's pending PR https://github.com/syl20bnr/spacemacs/pull/7463 which adds some ivy bindings but is missing on `C-M-j`.

**Comment by gilbertw1** [comment]
I feel like B is the better option as well. I'll start working on documentation building in that direction.
