### ISSUE TITLE
In c++, flycheck mode "next error" clobbers compile errors

### ISSUE THREAD

**Issue by spott** [syl20bnr/spacemacs#776]
When I compile a c++ file, and there are errors, "next error" (`<SPC> e n`) doesn't work, instead finding next flycheck error instead of next compile error.

It would be nice if when the compile error window is open, "next error" went to the next compile error.

**Comment by tuhdo** [comment]
While waiting for it to be fixed, you can still use stock key bindings `M-g n` and `M-g p` to go to next and previous compile error.

**Comment by spott** [comment]
Awesome.  Thanks.



—
Andrew

**Comment by jb55** [comment]
Related: https://github.com/flycheck/flycheck/issues/95

Looks like @jwiegley has a fork somewhere fixing this.

The `M-g {n,p}` workaround isn't very satisfying when writing Haskell code, since 95% of the time you are jumping through compile errors. It would be nice to have the less RSI `SPC e n` always work for those cases.

Not sure how to fix this since flycheck says they're not going to stop clobbering the next-error binding.

**Comment by jb55** [comment]
After looking around some more it looks like you can disable the next-error behaviour with a setting:

https://github.com/flycheck/flycheck/issues/202

**Comment by jb55** [comment]
But that doesn't work because it looks like `spacemacs/next-errors` calls it anyway... :(

**Comment by StreakyCobra** [comment]
Can anyone check if this bug is still happening?

**Comment by jb55** [comment]
I've muscle memory'd M-g {n, p}, but it would be nice to have proper bindings for these

**Comment by dennishamester** [comment]
I really like what @spott suggested, that `spacemacs/next-error` should go to the next compilation error if the compilation window is open.

Here is a quick fix: dennishamester@0304a2ef03c276cb2b3673d8e7e0a4a3c9360eb3

What do you think?

**Comment by StreakyCobra** [comment]
PR it, that will be better discussed there :-)

**Comment by dennishamester** [comment]
done: #5712

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
