### ISSUE TITLE
ycmd-layer: Look for compilation database in subdirectories.

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#7769]
In addition to looking in the project root, ycmd should look for `compile_commands.json` in subdirectories (e.g. `build`) to accomodate out-of-tree builds. If run in the project root, cmake pollutes the project root when generating `compile_commands.json`. 

Such a file should also be adjusted to accomodate the fact that the paths contained point into the `build` directory, while the user will be editing files in the project root (without affecting header files that cmake creates in the `build` directory.

**Comment by TheBB** [comment]
You have to copy it to the project root after generating it in an OOT build.

The compile_commands.json file won't contain include paths into the build directory unless you have written your CMakeLists.txt to include those paths. My projects include paths in the source tree so the generated file contains paths to the source tree. If that's an issue I suggest you fix your build system instead.

**Comment by beojan** [comment]
Huh, it does seem to work if I just copy the file into the root. It may still be helpful to have the layer check for a build directory though.

**Comment by deb0ch** [comment]
Instead of copying it everytime you could also make a symlink pointing to it. This way, no need to copy every time you build :wink: 

About your feature request, I think that it is simply impossible.

Implementing such a feature would have an absolute requirement: have a 100% consistent way to determine the root of the project, even for files that are *not* in a project. 

Otherwise, this feature would have to search your *entire* filesystem for a `compile_commands.json`.
Even assuming that performance would not be an issue, if your project doesn't have a `compile_commands.json` you will most likely end up with another project's one, and the `.clang_complete` file will never be searched for.

And since there is absolutely no way of knowing where to stop the search for 100% of C/C++ files of 100% of users, there is no way to make it work.

Let me know if my reasoning is flawed or if I misunderstood your request :smirk_cat: 

If there is a feature that you absolutely want, a PR is the :sparkles:absolute best:sparkles: way, and the file is [here](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Btools/ycmd/global_conf.py) :smiley_cat:

**Comment by beojan** [comment]
It could be limited to projects recognized by Projectile.

**Comment by TheBB** [comment]
We can't use Emacs features. This must be strictly on the Python side.

**Comment by TheBB** [comment]
Besides, I often have four different build folders. I don't see a simple way to make a good pick.
