### ISSUE TITLE
NixOS + Spacemacs setup?

### ISSUE THREAD

**Issue by mrkgnao** [syl20bnr/spacemacs#7813]
I've been thinking of making the switch to NixOS for a while. With how NixOS tries to subsume all language/software-specific package management, what are the best practices for setting up Spacemacs on a NixOS box? Is it the same "clone into `.emacs.d`" setup as always, or are you supposed to take advantage of the substantial set of Emacs packages that NixOS can manage on its own?

**Comment by lrosa007** [comment]
I've been using NixOS for the past week with spacemacs and all I did was clone into `.emacs.d` as usual. Although I noticed that the auto-generated variables at the bottom dont seem to show up, it's been working fine. All the elixir/alchemist stuff works really well but it always does. One weird issue I've been having is `void function: font-lock-push` whenever I open a javascript file. I push all .js to react-mode bc weird indentation problems. It's seems like the call to push does that. When it happens things like quotes and brackets don't self close.

**Comment by jb55** [comment]
The dream is to build a spacemacs2nix tool to encode emacs dependencies from spacemacs layers into nix expressions. AFAIK there is no way to use emacs packages from your nix store at this time.

see:
- nixos/nixpkgs#9068
- https://gist.github.com/Profpatsch/ddff34d495f57b505a6b

**Comment by jb55** [comment]
so I have a pretty ghetto hack that seems to work OK:

## Prevent deletion of orphaned packages

By setting `dotspacemacs-install-packages` to `'used-but-keep-unused` in `dotspacemacs/init` in your `.spacemacs`:

```elisp
(defun dotspacemacs/init ()
  (setq-default
   dotspacemacs-install-packages 'used-but-keep-unused
   ))
```

This is a workaround. It's needed because spacemacs can sometimes try to delete stuff from system packages which will crash your startup.

## Get a list of all of your installed packages

Use this command:

    ls $HOME/.emacs.d/elpa | sed 's/-[[:digit:]].*//g;s/\+$/-plus/g' | sort -u

## Paste list into your ~/.nixpkgs/config.nix` overrides:

```
  packageOverrides = super: rec {
    emacs = super.emacsWithPackages (ep: with ep; [
      ace-jump-helm-line
      ace-link
      ace-window
      ac-ispell
      adaptive-wrap
      aggressive-indent
      alert
      # ... etc
    ]);
}
```

You might need to comment out any broken packages.

## Delete spacemacs' package cache

    $ rm -rf ~/.emacs.d/elpa

## Try it out

    $ nix-shell -Q -p emacs

... this might fail, go back and comment out packages until it works.

    $ emacs

done! spacemacs will still install the remaining stuff that isn't in your system packages.

## Annoyances

You have to keep your package list updated by repeating this process. but now you have the benefit of a stable set of packages cached in your nix store!

/cc @Profpatsch @CestDiego

**Comment by Profpatsch** [comment]
To be honest, I’ve just used spacemac’s own declarative package management and updated every month or so. That has worked quite well for me so far.

**Comment by therealpxc** [comment]
I would love to be able to have custom Spacemacs distributions available via `nix-shell` as a way to gently introduce folks at work to reliable, complete, IDE-like command-line editor experiences in development environments. Spacemacs feels great for development in so many languages, and the discoverability is really impressive. The ability to bind unbreakable, pre-configured Spacemacs distros to specific projects would really take what seems to be the central aim of the project (making Emacs more accessible and easier to jump in with but no less powerful) to a whole new level, imo.

But I just started using Spacemacs last week, and I've never used Emacs before then either, so I feel like trying to get this right is a bit out of reach for me.

For my own purposes, the plain old `git` clone into `~/.emacs.d` option has been quite alright, but I do think packaging it with Nix would add some potential for extra niceness (like pinning to a patched or unreleased version of Spacemacs just to get specific features, perhaps particular to a programming language, which haven't been released yet but one knows are stable without risking breakage of other use cases, since they can have their own respective Spacemacsen, too).

**Comment by Profpatsch** [comment]
> but I do think packaging it with Nix would add some potential for extra niceness (like pinning to a patched or unreleased version of Spacemacs just to get specific features, perhaps particular to a programming language, which haven't been released yet but one knows are stable without risking breakage of other use cases, since they can have their own respective Spacemacsen, too).

Isn’t that just checking out a different ref in the spacemacs git repo? There’s not much magic involved.

**Comment by therealpxc** [comment]
Yeah, but every user only has one ~/.emacs.d directory. The difficulty I
anticipate isn't in making that feature happen, but the more general
difficulty of packaging Spacemacs in a natural way (which is why it hasn't
happened yet despite some interest). And that's what would get us different
ones side-by-side and all the other little things one can just do with Nix
packages.

The things I don't know how to do are things like, as was mentioned as a
possibility in the thread, 'patch out auto-updating features' or whatever
else might be necessary to get this to work seamlessly. I'm sure it can be
figured out, but I'll have to spend more time with Emacs in general and
Spacemacs in particular before I'll know what to do.

**Comment by jb55** [comment]
@Profpatsch not really, if you delete the elpa dir you get "whatever package version is latest" so there's no consistent reproducible state that spacemacs is in. I've have stuff be completely broken after updating my packages on the same spacemacs commit.

**Comment by Rizary** [comment]
Assuming the last comment is still last year, there is not any alternative isn't it?

**Comment by puffnfresh** [comment]
I've got some work here on a `spacemacs2nix.el`:

https://github.com/puffnfresh/nix-files/tree/master/spacemacs

It kinda works for me, please give it a go and let me know how it goes for you.

**Comment by deliciouslytyped** [comment]
https://github.com/syl20bnr/spacemacs/issues/12029

**Comment by timor** [comment]
If anyone is interested: I am maintaining a fork which solves some NixOS related problems.  A derivation
which uses this can be found here: https://github.com/timor/timor-overlay/tree/master/pkgs/spacemacs

It uses a slightly patched emacs to run it completely separate from stock emacs under the `~/spacemacs.d` directory.

**Comment by JonathanReeve** [comment]
@puffnfresh, I tried your scripts, but unless I'm missing something obvious, the second script is looking for `spacemacs-bootstrap.nix`, which doesn't seem to exist?

**Comment by mixmixmix** [comment]
@puffnfresh , @JonathanReeve - do you mean that it doesn't work without that missing file? I'm trying to understand NixOS enough to at least have the default setup working, but it proves very difficult.

**Comment by JonathanReeve** [comment]
I couldn't get it to work. I suspect @puffnfresh didn't check in spacemacs-bootstrap.nix to Git? Anyway there appears to be something missing. Unless I'm doing something wrong.

**Comment by mixmixmix** [comment]
I got development nicely working by using upcoming **spacelpa** `dotspacemacs-use-spacelpa t` All my packages properly install with base emacs 26.1 from 19.09

**Comment by Mic92** [comment]
I was able to re-create the missing `spacemacs-bootstrap.nix` from @puffnfresh  repository:

```
with import <nixpkgs> {};
emacsWithPackages (ps: with ps; [
  async
  bind-map
  bind-key
  diminish
  evil
  hydra
  use-package
  which-key
  dotenv-mode
  pcre2el
])
```

**Comment by AleXoundOS** [comment]
So, currently there are 2 approaches: using spacelpa or @puffnfresh solution? What are the practical differences?

**Comment by Mic92** [comment]
I have not found a working one so far.

**Comment by AleXoundOS** [comment]
This is still a concern.
