### ISSUE TITLE
Unable to disable the company-mode in shell

### ISSUE THREAD

**Issue by abhi18av** [syl20bnr/spacemacs#7883]
Guys, I'm stuck at a little nuisance in the `shell`
#### Description :octocat:

I wish to disable the `company-mode` in the shell but the only successful method, so far, is by running the `(setq-local company-mode nil)` in the  `eval`. 

I've tried the following wrt to the `.spacemacs` file ( one at a time :P )

```emacs lisp
(add-hook 'shell-mode-hook (lambda () 
                            (setq-local company-mode nil)))
 
 
(add-hook 'shell-mode-hook (lambda () 
                            (setq company-mode nil)))
 
(add-hook 'shell-hook (lambda () 
                            ( company-mode nil)))
```

Btw, I do use the `company-mode` by default.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(mu4e
 (auto-completion
  (haskell :variables haskell-completion-backend 'intero))
 better-defaults emacs-lisp clojure git markdown org
 (haskell :variables haskell-enable-hindent-style "johan-tibell")
 html c-c++ python sql xkcd finance search-engine dash fasd chinese restclient prodigy gtags deft colors
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (ruby :variables ruby-enable-enh-ruby-mode t ruby-test-runner 'rspec ruby-version-manager 'rbenv)
 spell-checking syntax-checking version-control)
```
- System configuration features: JPEG RSVG IMAGEMAGICK DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by bmag** [comment]
In your layer list, replace `shell` with:
```elisp
(shell :packages (not company))
```
Please report back the result.

**Comment by dubnde** [comment]
I have something like this `(auto-completion :disabled-for shell)`. Don't know if it helps you

**Comment by abhi18av** [comment]
So, I've tried both suggestions 

```emacs lisp
(auto-completion :disabled-for shell)


```

```emacs lisp
              (shell :variables shell-default-height
                                              30 shell-default-position 'bottom
                                              :packages (not company))
```


But they don't work, the `circled a` only goes away if I do `M-x company-mode`

**Comment by bmag** [comment]
I looked at it again, and found that:
- when I open a `shell` buffer (e.g. with `M-x shell`), it doesn't have `company-mode` enabled in the first place
- `shell` layer enables `company-mode` only in `eshell`. It doesn't enable `company-mode` in `shell` at all.
- I doubt anything else in Spacemacs enables `company-mode` in `shell` (and couldn't find anything)
- adding `:packages (not company)` disabled `company-mode` in `eshell` for me
- `(auto-completion :disabled-for shell)` doesn't work because `shell` layer doesn't check if it's disabled or not

@abhi18av if you can describe what you're doing to enable `company-mode` in the first place, and how you open the shell and which shell you're using (`shell`, `eshell`, `term`, etc.) that would be nice.

Also, is this really the value of `dotspacemacs-configuration-layers`? You have `haskell` listed twice, and on of those time is inside `(auto-completion ...)`:
```elisp
(mu4e
 (auto-completion
  (haskell :variables haskell-completion-backend 'intero))
 better-defaults emacs-lisp clojure git markdown org
 (haskell :variables haskell-enable-hindent-style "johan-tibell")
 html c-c++ python sql xkcd finance search-engine dash fasd chinese restclient prodigy gtags deft colors
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (ruby :variables ruby-enable-enh-ruby-mode t ruby-test-runner 'rspec ruby-version-manager 'rbenv)
 spell-checking syntax-checking version-control)
```

And anyway, if you want to disable `company-mode` in a hook you should use:
```elisp
(add-hook 'shell-mode-hook (lambda () (company-mode -1)) 'append)
```
The `append` argument ensures that it's added to the hook after other functions, and `shell-mode-hook` should be replaced by the proper hook that matches the shell you're actually using.

**Comment by abhi18av** [comment]
@bmag  Thanks a lot for the solution!! :smile: 

As for the queries, I did mention that  I enabled the `global company mode ` in my `.spacemacs' config.  The thing is I'm trying to use  the `fregei` or `groovysh` interpreters from the command line and I definitely prefer the `evil bindings` in the buffers. 

With all other shells `multi-term` `ansi-term` `term` and `eshell` - the prompt itself gets deleted when I press the `dd` command which is the `line-deletion-command` in `vim`. 

* As for the Haskell being mentioned twice, I intended to use the [haskell-intero](https://github.com/commercialhaskell/intero) back-end for completion as opposed to the `company-ghci` as is mentioned in the [spacemacs/haskell](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/haskell) layer so I just followed the basic setups. Didn't get the completion working anyhow (

* And yes, this is the real `.spacemacs` - I came to spacemacs from Atom, avoiding IDEs so I wished to test the limits I can push spacemacs to. Turns out there's a lot it can handle! 

I've shaved it some more so the current value is 

```emacs lisp
(mu4e
auto-completion

 better-defaults emacs-lisp clojure git markdown org
 (haskell :variables haskell-enable-hindent-style "johan-tibell")
 html c-c++ python sql xkcd finance search-engine dash fasd chinese restclient prodigy gtags deft colors
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control)
```

And thanks @bmag @dubnde - I appreciate your time :)
