### ISSUE TITLE
Revisit gc-cons-threshold

### ISSUE THREAD

**Issue by mwillsey** [syl20bnr/spacemacs#7886]
I think this should be brought back up for discussion. It looks like it was mentioned in the past (#4687), and then these commits (all within a few weeks) implemented and then undid it.

a462f65a init: revert GC threshold to 100MB
368c1bef init: move restore of GC threshold to the end of init
d87491c6 Reduce gc-cons-threshold after init

Specifically, I think the additions in d87491c6 should be put back. That thread offers some interesting perspectives, and I wonder how performance with those packages has changed since then.

For myself, I know reducing `gc-cons-threshold` back to 800k has made Spacemacs **much** more responsive. Activating helm and bring up the org agenda are two concrete examples of things that would frequently trigger a 100mb (the current default) collection, basically bringing the UI to a screeching halt. Since making this change, I haven't seen a single hang like the several second ones I used to have.

I'd like to hear peoples thoughts on this. Also, I'd encourage people to add `(setq gc-cons-threshold (* 800 1024))` or something like it to their `user-init` or `user-config` and see if it helps responsiveness like it has for me. I acknowledge that `init.el` does currently have a comment suggesting this, but if it really does consistently make things better (I suspect it might), it should be the default.

**Comment by byronsanchez** [comment]
Just a data point from my end:

Emacs: v25.1.1 (native 64 bit build)
OS: Windows 10

When I have a gc-cons-threshold of about 100mb, the editor is mostly usable. I get ui locks every 20-30 seconds that last about 2-3 seconds due to GC, so it's kind of annoying, but usable.

When I have a gc-cons-threshold of the default 800000 value, I can't use emacs at all. Each cursor movement takes like 5 seconds.

So from my end, it's pretty much picking the lesser of two evils and sticking with the spacemacs default. I wish I could find a way to get rid of frequenty ui locks though. I'll probably have to experiment with other values.
