### ISSUE TITLE
Cannot submit in internal issue reporting mode

### ISSUE THREAD

**Issue by gutsle** [syl20bnr/spacemacs#7907]
#### Description :octocat:
Reporting issues with SPC h I does not allow actually submitting.

#### Reproduction guide :beetle:
- Start Emacs
- Start a report with SPC h I
- Try to submit as suggested in the first line using: C-c C-c
"<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-c C-c` TO SUBMIT>>"

*Observed behaviour:* :eyes: :broken_heart:
C-c C-c is undefined

*Expected behaviour:* :heart: :smile:
spacemacs//report-issue-done should be called

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. cf951a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp
 (org :variables org-enable-reveal-js-support t)
 (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by d12frosted** [comment]
Can't reproduce it here.

**Comment by joting** [comment]
I have this issue too, running 200.7

**Comment by shelper** [comment]
me 3, using develop branch on windows

**Comment by timofeytt** [comment]
Can't do it either.

- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(lua clojure php csv ocaml ivy better-defaults emacs-lisp git org ess extra-langs)
```

**Comment by raventid** [comment]
+1 cannot submit issue

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(haskell clojure html ruby rust helm emacs-lisp)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB

**Comment by achikin** [comment]
https://github.com/syl20bnr/spacemacs/issues/9627

**Comment by vadtec** [comment]
#### Description :octocat:
M-m h I does not have C-c C-c defined for submitting issues.

#### Reproduction guide :beetle:
- Run emacs
- M-m h I to submit new issue
- Fill out issue
- C-c C-c <--- undefined

*Observed behaviour:* :eyes: :broken_heart:
<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-c C-c` TO SUBMIT>>

C-c C-c is undefined here.


*Expected behaviour:* :heart: :smile:
C-c C-c submits the issue.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by Compro-Prasad** [comment]
I think it is defined in the develop branch. You should be using the develop branch.
