### ISSUE TITLE
emacs freezes when pressing space four times when running as client

### ISSUE THREAD

**Issue by datafux** [syl20bnr/spacemacs#7911]
#### Description
emacs freezes when pressing space four times

#### Reproduction guide
- Start Emacs
- press Space four times

*Observed behaviour:*
Emacs freezes

*Expected behaviour:* 

#### System Info
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(lua
 (auto-completion :variables auto-completion-return-key-behavior 'nil auto-completion-tab-key-behavior 'complete)
 better-defaults bongo colors emacs-lisp git annex spell-checking latex outline-magic ranger ebib olivetti mu4e ibuffer osx)
```
- System configuration features: JPEG NOTIFY ACL LIBXML2 ZLIB

#### Backtrace
```
```

**Comment by datafux** [comment]
just realized, that this is only issue when running as a client

**Comment by Bost** [comment]
In my case it does not freezes, it eats 100% CPU.

**Comment by Bost** [comment]
Here is my profiling output. [SPC-freeze.txt] (https://github.com/syl20bnr/spacemacs/files/789882/SPC-freeze.txt)
I guess the problem comes somewhere from `helm--search-from-candidate-buffer-1` (See the comment https://github.com/emacs-helm/helm/blob/5b79b86975172c0baa1ed1e034016015b6ab835f/helm.el#L4827) and/or `helm-mm-3-search`.
