### ISSUE TITLE
404 Error for official documentation link

### ISSUE THREAD

**Issue by off99555** [syl20bnr/spacemacs#7916]
How to replicate:
1. Go to http://spacemacs.org/doc/VIMUSERS.html#modes-vs-states
2. Click on `states` as in `we have states`.
3. There you have it.

This error applies to all the links that are org files.

**Comment by duianto** [comment]
There seems to be specific repository for the spacemacs webpage:
[https://github.com/syl20bnr/develop.spacemacs.org](https://github.com/syl20bnr/develop.spacemacs.org)

maybe this should be reported there.

I checked the links on both:
http://spacemacs.org/doc/VIMUSERS.html
and
http://develop.spacemacs.org/doc/VIMUSERS.html

They are the same. It would probably have been enough to just check the develop version, but i didn't notice that i was checking the non develop version until after i was done so i made sure that it hadn't already been fixed in develop.

3.1.1 Modes vs. States

"Emacs" should probably be changed to "Spacemacs", in the second sentence:
before:
> In Emacs, we have states.

after:
> In Spacemacs, we have states.


link text: states
404 link: http://spacemacs.org/doc/DOCUMENTATION.org#states
correct link: http://spacemacs.org/doc/DOCUMENTATION.html#states


3.1.2 Layers

link text: customization
404 link: http://spacemacs.org/doc/VIMUSERS.org#customization
correct link: http://spacemacs.org/doc/VIMUSERS.html#customization

link text: documentation
404 link: http://spacemacs.org/doc/DOCUMENTATION.org#configuration-layers
corrected link: http://spacemacs.org/doc/DOCUMENTATION.html#configuration-layers

3.4.1.1 Special buffers

link text: here
404 link: http://spacemacs.org/doc/DOCUMENTATION.org#special-buffers
correct link: http://spacemacs.org/doc/DOCUMENTATION.html#special-buffers


4.4 Creating a Layer

link text: MELPA
404 link: http://spacemacs.org/doc/melpa.org
correct link: http://melpa.org

link text: use-package hooks
404 link: http://spacemacs.org/doc/LAYERS.org#use-package-hooks
correct link: http://spacemacs.org/doc/LAYERS.html#use-package-hooks

link text: anatomy of a layer
404 link: http://spacemacs.org/doc/LAYERS.org#anatomy-of-a-layer
correct link: http://spacemacs.org/doc/LAYERS.html#anatomy-of-a-layer

link text: LAYERS.org
corrected link text: LAYERS.html
the link is already correct: http://spacemacs.org/doc/LAYERS.html

**Comment by bmag** [comment]
Thanks for spotting this issue. Links in our Org files are supposed to be automatically converted to HTML before as part of the publishing process. I'm not particularly familiar with it, but it's probably safe to say that `core/core-documentation.el` has some part in it.
I see two different bugs here:
- in-line links to headlines in Org files are not converted from `*.org#*` to `*.html#*`.
- the link to `melpa.org` is incorrectly converted to `http://spacemacs.org/doc/melpa.org`

If someone wishes to tackle this, go ahead :smile: 

@duianto thank you for providing so much details :+1: The correct place to report this issue is here.

**Comment by nikolaiam** [comment]
Well spotted! #8138 fixes this together with #8146.

**Comment by syl20bnr** [comment]
Nice work 👍 

Should be fixed on http://develop.spacemacs.org
