### ISSUE TITLE
Develop branch issue: Document the fact that custom settings must be wrapped differently!

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#7926]
**Edit: The issue was found - it's a problem with how Spacemacs wraps settings in develop vs master. Read further down. This needs to be documented somewhere.**

-----

`dotspacemacs-line-numbers 'relative` doesn't work for me on the `develop` branch. I get regular numbers.

I was able to manually enable relative numbers by `<Alt+:>` and typing `(spacemacs-evil/init-linum-relative)`. (Strange function by the way, it isn't called from anywhere as far as I can see; it just sits there in the code in `./layers/+spacemacs/spacemacs-evil/packages.el`...)

I also compared the `master` to `develop` of the nlinum and spacemacs-evil layers (the layers that check the `dotspacemacs-line-number` setting), and they are identical between both `master` and `develop`. That's where the `(when (eq dotspacemacs-line-numbers 'relative)` check is done... Literally identical code...

Suspecting that the bug may be somewhere else, I then tried using my `~/.emacs.d/elpa/` folder from my `master` folder in my `develop` folder, just to be sure I used the exact same packages, but that didn't fix it either.

So for now, I went back to regular `master` because relative line numbers work there...

**Comment by bmag** [comment]
Couldn't reproduce on develop with latest packages. Please make sure your packages are up to date and add more info as per [Debugging](https://github.com/syl20bnr/spacemacs/wiki/Debugging).

**Comment by SteveJobzniak** [comment]
@bmag All packages were the latest. I literally rm -rf ~/.emacs.d, git cloned, checked out the develop branch, and let it install.

But... I just tried something else...

1. Move .emacs.d and .spacemacs.d folders somewhere safe.
2. git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d && cd ~/.emacs.d && git checkout develop
3. Start Emacs and answer the basic tutorial as follows: vim mode, spacemacs, helm.
4. Let it install the ~100 default packages.
5. `<SPC f e d>` to edit config. Set it to `dotspacemacs-line-numbers 'relative`.
6. Restart emacs... I see relative numbers...

But literally the ONLY difference was my config file... So I began trying to gradually copy over sections from mine, to see what breaks it... And nothing did...

So... I came to the final difference between my new and old config file: The "custom" section at the bottom...

And that's what caused it. My `master` dotfile's custom section works properly on `master` but on `develop` it enables absolute line numbers instead of relative.

Here's the thing: I have never written the custom-set-variables section. Spacemacs did that. Somehow... And on `master` this exact file enables relative numbers, and on `develop` it fails... so make of that what you will:

https://gist.github.com/SteveJobzniak/6d9ce01f0ada0dd32f894138e5af616a

**Comment by SteveJobzniak** [comment]
I deleted everything after:

```emacs-lisp
;; Do not write anything past this comment. This is where Emacs will
;; auto-generate custom variable definitions.
```

Now relative lines work perfectly on develop branch too.

**Comment by bmag** [comment]
You can see that the new generated custom section is wrapped inside of `(defun dotspacemacs/emacs-custom-settings ... )`, this is a new feature on develop. It exists so Spacemacs can load these customized settings in an appropriate time during the startup process, instead of loading the unwrapped settings when loading `.dotspacemacs` (this happens before even calling `dotspacemacs/user-init`!).

When using develop, the custom settings should be wrapped in `(defun dotspacemacs/emacs-custom-settings ... )`. When using master, they shouldn't be wrapped. When switching from master to develop, you need to wrap these sections manually, or copy them somewhere else and copy them back after Spacemacs generated the wrapped section. When switching from develop to master, you should unwrap the custom sections.

@syl20bnr I think this gotcha should be documentated, probably in the changelog/release notes for 0.201.

**Comment by SteveJobzniak** [comment]
@bmag @syl20bnr Oh, yeah that's a huge gotcha and definitely needs documentation somewhere.
