### ISSUE TITLE
Installer - Error: Failed to download resource "emacs-plus"

### ISSUE THREAD

**Issue by orsenthil** [syl20bnr/spacemacs#7928]
```
==> Installing d12frosted/emacs-plus/emacs-plus
==> Downloading https://homebrew.bintray.com/bottles-emacs-plus/emacs-plus-25.1.el_capitan.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "emacs-plus"
Download failed: https://homebrew.bintray.com/bottles-emacs-plus/emacs-plus-25.1.el_capitan.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

**Comment by bmag** [comment]
@d12frosted any idea?
@orsenthil I don't know if that's enough info

**Comment by orsenthil** [comment]
@bmag - I just did an installation as it was suggested in the website.

It looks like this URL is  404.

Download failed: https://homebrew.bintray.com/bottles-emacs-plus/emacs-plus-25.1.el_capitan.bottle.tar.gz

Is this something spaceemacs project controls? My installation works fine inspite of this error.

**Comment by d12frosted** [comment]
This is pretty harmless, though I would like to solve this. There is [an open upstream issue][1] for this. Any help is welcome 😸 

P. S. this reminds me that I need to update the formulae! 

  [1]: https://github.com/d12frosted/homebrew-emacs-plus/issues/6

**Comment by paytonrules** [comment]
This has been broken for a long while now. Should the Readme be updated for Spacemacs to just install regular emacs?

**Comment by wadkar** [comment]
I like what @paytonrules said. Specifically, I was surprised to see that @d12frosted 's `emacs-plus` formula pulled over 25[1] dependencies when I tried to install it today.

I came across [Mitsuharu Yamamoto's](https://bitbucket.org/mituharu/emacs-mac) "Mac Port" of Emacs while digging through [this HN discussion](https://news.ycombinator.com/item?id=9594031) . There is a convenient [tap available here](https://github.com/railwaycat/homebrew-emacsmacport) for homebrew users. I am currently _tapping it_ with spacemacs and so far it didn't blow up my MBP (yet :laughing: )

@d12frosted : it would be great if you could take a look at this formula and let us know what you think.

@paytonrules do you want to give it a shot? If there aren't any obvious roadblocks in using the `emacs-mac`, I suggest that we update the README to include this option as well. Let's give the users a choice here and see what the community has to say. If majority prefers this `emacs-mac` port, then we could later update the README to indicate this preference.

I will be more than happy to create a PR for this and move the discussion there if that's preferable?

Thoughts?

-Sudhi

PS: Interestingly, [this comment](https://github.com/d12frosted/homebrew-emacs-plus/issues/6#issuecomment-256476684) indicates that the homebrew team will be recommending the vanilla [EmacsForMacOSX](https://emacsformacosx.com/about) in a cask formula. I haven't tried it as I assumed `emacs-mac` as a better alternative given the [long list of features](https://bitbucket.org/mituharu/emacs-mac). Of course, if spacemacs runs fine on vanilla emacs, then the EmacsForMacOSX binaries are super easy to install and perhaps would be preferable for non-homebrew users.

[1] `brew install emacs-plus` yields:
```sh
===> Installing dependencies for d12frosted/emacs-plus/emacs-plus: libtasn1, gmp, nettle, libunistring, libffi, p11-kit, gnutls, libpng, freetype, fontconfig, pixman, gettext, glib, cairo, jpeg, libtiff, gobject-introspection, shared-mime-info, gdk-pixbuf, libcroco, icu4c, harfbuzz, pango, librsvg, libtool, imagemagick
```

**Comment by d12frosted** [comment]
@wadkar 

Sorry, I was very busy lately, just saw your comment. 

Debates about the choice between GNU Emacs and Emacs Mac Port start time to time in Spacemacs community. I would say that it's a matter of preference and some luck. Both of them have disadvantages. And ideally I would like to recommend both of them with a short note on the differences between them. 

As for all these dependencies that comes with `emacs-plus`, you can easily disable them, just take a look at available options. You see, 'official' GNU Emacs formulae comes with many options that are disabled by default and some of them are so good that in my opinion they should be enabled by default for most users. So instead of asking people to install `emacs` or `emacs-plus` or `emacs-mac` or whatever with many switches (and some of them become deprecated or change names[1]) I like to ask people to install one thing that bring most of the features they would want to use. Power users are free to disable options they don't like or don't need. No one is forcing you to go with everything enabled 😸 

As for EmacsForMacOSX - this is a good alternative for some people. Probably this should also be mentioned in readme file 😸 

  [1] Last time I've noticed name change I've also noticed many people having troubles due this name change.

**Comment by cjpoor** [comment]
Don't you think the brew bottle should be updated so that it does not need to built from source?
Also look at switching from linkapps which is about to dropped from Homebrew?
Cheers,
Chris.

**Comment by d12frosted** [comment]
I agree, bottle should be updated. In case anyone wants to update it sooner than later, know that your help is welcome 😸 

As for deprecation of linkapps, I am not aware of this 😢 Gonna check brew news 😸

**Comment by d12frosted** [comment]
@cjpoor I've updated bottle for sierra. Sorry it took so long 😸

**Comment by d12frosted** [comment]
Closing this issue as well as upstream one. In case someone wishes to provide bottles for other versions of macOS, let me know.

**Comment by cjpoor** [comment]
Thanks :)

**Comment by wadkar** [comment]
Thanks @d12frosted - I have better understanding of the situation now.
