### ISSUE TITLE
Magit: Should mode commands be accessible via SPC m?

### ISSUE THREAD

**Issue by mkleehammer** [syl20bnr/spacemacs#7936]
I was under the impression that comma (,) was a shortcut for `SPC m` major mode commands, but in a git commit buffer they are not exposed this way.  The only way to commit is ",," or ",c".

Is this an oversight or did I misunderstand the design?

**Comment by nixmaniack** [comment]
AFAIK, magit buffers are special buffers and since it has its own way of managing key-driven-actions - Spacemacs doesn't add its own bindings. 

There's special exception for commit buffer where `,c` was added for `C-c C-c` for having Vimmy binding and later `,,` was added as it's easier to type in succession similar to `C-c C-c`.
