### ISSUE TITLE
Proposed layer/package: quicksetindent

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#7939]
One of Emacs' greatest strengths, the per-mode indentation settings, is also a great weakness. It's complicated to set up unified indentation across all of your filetypes. Newcomers have to scour the net for old, partial lists of what variables to use for configuring each mode, and where and how to put those configurations. And they end up with partial configurations where only a few of their modes are affected.

Spacemacs is Emacs for the masses. So perhaps I can help this situation.

I compiled an up-to-date list of all variables, and the great thing about these is that they're all pretty standardized by now. New modes usually stick to using one of these. So this list should stay universal for a long time.

I then put it all into a package which lets you easily set the indentation variables either globally or locally per-buffer, with a single command.

So somebody who wants a global default of 4 spaces, no tabs, would just add the following three lines to their dotspacemacs user-config:

```emacs-lisp
  (require 'quicksetindent)
  (quicksetindent/set-indentation t 4)
  (setq-default php-mode-coding-style 'pear)
```

The first line wouldn't be necessary if this was made into a layer or package. And the last line is only necessary for people who work in php-mode (which always applies a "style" at startup, which sets the indentation; the source code description for my package has more info).

I placed all of this into the public domain, so anyone is welcome to do whatever you want with it: Hack it apart, put it into a layer (to make its usage in Spacemacs even easier), submit it to MELPA, or do anything else you feel like. ;-)

Enjoy:
https://github.com/SteveJobzniak/emacs-quicksetindent/blob/master/quicksetindent.el

**Comment by syl20bnr** [comment]
After thinking about it I believe that the best option for the integration of this great list of defaults is to turn it into a layer. Several advantages to do so:

1) we leverage all the mechanics provided by layers, especially `:disabled-for`/`:enabled-for` keywords which allow to include or exclude the effect of a layer onto the others. Also `post/pre-init` functions will be handy to handle the specific cases. 
2) we can introduce layer variables to name the settings.
3) we can document it in a layer README accessible easily with `SPC h SPC`
 
There are several way to do it, more or less "spacemacsy".

1) The first one, less spacemacsy is to keep the current structure of @SteveJobzniak package.
2) The second one, more spacemacsy is to define the defaults in `post-init` function for each language.

I would like to do a mix of both actually.

For supported languages by spacemacs then I would prefer to set the default in a `post-init` function, this is to respect the philosophy of spacemacs layer desing which is "user should be able to know everything about a layer configuration/feature by just looking at one file (i.e. packages.el)"

For unsupported languages we can let them in the package (but ideally we should start a layer for this language :-)).

@SteveJobzniak there is a conflict between the package approach and the layer approach with the current design of the package. Layer approach is spacemacs specific where defaults are dispatched in language layers, which means nobody outside of spacemacs can take advantage of the defaults. The package approach on MELPA allows anybody to use it and this package should definitely be on MELPA. The conflict comes from the default settings application, with layers only the actually used layers will set the defaults, with the package all the defaults settings are applied no matter what. It is not an issue performance wise but I don't like to define a bunch of variables that are useless. So ideally we should have both, it should be possible if we change the package design to be a minor-mode. It can then be hooked to `prog-mode-hook` to achieve the current design, or it can be hooked to specific modes. What do you think?

**Comment by SteveJobzniak** [comment]
@syl20bnr I like the the idea of making the "set all defaults" into an optional minor mode which uses a `prog-mode-hook`. And as main configuration, use the Spacemacsy `post-init` for each built-in language.

One important thing to consider: Be sure that http://editorconfig.org still works. The risk of per-language hooks (and the reason I use global defaults instead of hooks myself) is that the Spacemacs hook runs later than EditorConfig and overrides whatever settings the project itself wanted via its ".editorconfig" file. So there would have to be some sort of logic to solve that. Perhaps "if the editorconfig minor mode is active and the current path has a .editorconfig file in it somewhere, then don't apply our defaults".

I need to go. Good luck and take care, everyone. And have a wonderful Christmas! 🎄

**Comment by deb0ch** [comment]
Will this still work with [dtrt-indent](https://github.com/jscheid/dtrt-indent) (and vice versa) ?

**Comment by SteveJobzniak** [comment]
@syl20bnr Oh I just thought of something and came back to let you know... Since I am leaving for almost half a year, it would be a good idea to merge my major Colors layer bugfixes and enhancements while it can still be merged, since I can't come back to rebase it. Several people in the official gitter chat use my fork, as well as myself, and it is stable and correct. It fixes so many issues that the layer is finally usable: https://github.com/syl20bnr/spacemacs/pull/7945 ;-)

Anyway, take care everyone and I wish you all the best!

**Comment by InvisibleTech** [comment]
Based on the status of this ticket... I assume quicksetindent is not part of a released and stable version of spacemacs.  Please let me know if I a, incorrect in this conclusion.  Thanks.

**Comment by SteveJobzniak** [comment]
@InvisibleTech It is not, but you can use it anyway. Look at my config:

https://github.com/SteveJobzniak/spacemaxed

Read the installation docs here and the sections relevant for you:
https://github.com/SteveJobzniak/spacemaxed/blob/master/spacemaxed/docs/01_INSTALL.org

But in short: Move to a ".spacemacs.d" folder instead of a ".spacemacs" file. And in that folder, place an init.el (which is your old .spacemacs file). Make a subfolder for quicksetindent and tell your init.el to load and use its code. Just look at my example and good luck. :)

**Comment by tonylotts** [comment]
What's the remaining work to be done here?

**Comment by Compro-Prasad** [comment]
@syl20bnr Any updates on this?

**Comment by retiform** [comment]
@Compro-Prasad well the orignal code and user are both deleted

**Comment by Compro-Prasad** [comment]
Then this PR should be closed. Right?

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
Add dtrt-indent layer for automatic indentation detection #12101
