### ISSUE TITLE
flet macro issue

### ISSUE THREAD

**Issue by ztlevi** [syl20bnr/spacemacs#7954]
I am facing the warning.
`Warning (bytecomp): ‘flet’ is an obsolete macro (as of 24.3); use either ‘cl-flet’ or ‘cl-letf’.`
While I have no idea which key is flet...

**Comment by bmag** [comment]
Since it's a byte-compilation warning, I'm going to assume that you saw this warning message during package installation. Part of the installation process of a package is to byte-compile the package, and fixing those warning is the responsibility of each package maintainer. Almost always these warnings are harmless. If it's not the case, feel free to comment.
