### ISSUE TITLE
custom-set-variable doesn't work

### ISSUE THREAD

**Issue by samrayleung** [syl20bnr/spacemacs#7970]
i try to customize company by modify its default value,for example i change `company-idle-delay` from 0.2 to 0.01 and `company-minimum-prefix-length` from 2 to 1,and i can find the statement in `custom-set-variables` function block in my .spacemacs file. but after i restart Emacs ,i find nothing change,and then I type `M-x customize-group` Enter `company`,and I find all the values i modified are reset,but the statement correspond  to my modify is still  in my .spacemacs file,then i try customize other variable,and it doesn't work ,either.Finally ,i comment `custom-set-variables ` block ,then,nothing changes,it is so weird

My Emacs Version 24.5.1
Spacemacs Version 0.200.5

**Comment by bmag** [comment]
I'ts kind of hard to understand what you tried, where you saw that wrong/unchanged values, what you configuration looks like. Can you please use this [guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging) (here's the [template](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template)), and if possible attach your dotspacemacs file?

**Comment by samrayleung** [comment]
#### Description :octocat:
custom-set-variable function doesn't work 

#### Reproduction guide :beetle:
- Start Emacs
- `M-x customize-group RET company RET`
- Change `Company Idle Delay` from 0.2 to 0.1
- Click `State`,Press `save for future session ` item
- Restart Emacs 
- `M-x customize-group RET company RET`


*Observed behaviour:* :eyes: :broken_heart:
find `Company Idle Delay` is still 0.2 instead of 0.1

*Expected behaviour:* :heart: :smile:
`Company Idle Delay ` should be 0.1


#### System Info
- OS:GNU/Linux
- Emacs 24.5.1
- Spacemacs 0.200.5
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Spacemacs branch: master (rev. 664ba6a)
- .spacemacs file
[init.txt](https://github.com/syl20bnr/spacemacs/files/658904/init.txt)

#### Backtrace :paw_prints:

**Comment by bmag** [comment]
Because of how the startup process works, your customize-powered settings are evaluated extremely early - even before `user-init` runs. Because of that, your settings for `company-idle-delay` is evaluated and later `company-idle-delay` is set back to 0.2 by `company`'s configuration in `auto-completion` layer. The solution for now is to either move your custom settings to a different file (see variable `custom-file`) and load that file in `user-init` or `user-config`, or to avoid using `customize` (instead put a `setq` in `user-config`).
In develop branch this should be fixed by incorporating `customize` settings in the startup process. (but there are still some rough edges)

**Comment by samrayleung** [comment]
get,thanks for you suggestion

**Comment by samrayleung** [comment]
i follow your suggestion,i put this statement  `  (setq custom-file (expand-file-name "~/.spacemacs.d/custom.el" user-emacs-directory))
  (load-file custom-file)
` in the `user-init`,but it doesn't work as before.Then i put the statement in `user-config`,it works.I just wonder is there something wrong with my statement  ,because it doesn't work exactly as you expect,or the custom file will be overwritten even after `user-init` run?  just wanna make it clear
