### ISSUE TITLE
New Evil mantainer?

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#7985]
It's known that frank fischer will no longer mantain evil. As evil is a core dependency, how's the quest for a new mantainer going?

**Comment by TheBB** [comment]
I contacted Frank Fischer but didn't hear back.

**Comment by ninrod** [comment]
can't evil just be forked and developed here in github? perhaps inside an spacemacs organization?

**Comment by stormpat** [comment]
Good point @ninrod! 

I think a spacemacs org maintaining evil could work, as many spacemacs bug reports are directly related to evil-mode, and evil is the core of spacemacs.

Would love to hear opinions from non spacemacs evil-mode users about this kind of a setup.

However i would not see a fork as the correct solution. This could lead to there being two non-compatible evil-modes. (think vim vs. neovim async).

There has to be a general agreement where the project is maintained, and by what team.

**Comment by BinaryKhaos** [comment]
Generally though, and I hope nobody minds me bringing this up, there should also be a discussion how to deal with the current Spacemacs situation where issues and pull requests keep increasing and it is very obvious there currently is a serious lack of manpower -- or at least of those people, who have commit access to the repository. For evil mode to flourish under a possible spacemacs org, the current structural issues at hand have to be solved first (and not only for evil mode's sake).

Perhaps it would be good to open up a another issue about this since I think it is very important and needs discussion as well?

**Comment by ninrod** [comment]
@stormpat I think that @TheBB just create the evil organization. Here is the relevant issue: https://github.com/emacs-evil/evil/issues/737. 

That's awesome news by the way. And thanks @TheBB.

**Comment by ninrod** [comment]
closing because the emacs-evil org now maintains evil.
