### ISSUE TITLE
spacemacs always opening two windows when opening from finder (macOS)

### ISSUE THREAD

**Issue by lightingghost** [syl20bnr/spacemacs#8055]
When I trying to open a file directly from finder, spacemacs always open one empty window, and then open that file in another window. 

Besides, the first window (empty one) follows the window size configuration that I set in .spacemacs, while the second window (the file) doesn't.

Is there any way to solve this?

Thanks,

**Comment by djwf** [comment]
I'm also seeing this on macOS 10.12.2, spacemacs 0.200.7, emacs 25.1.1 installed via `brew install emacs --with-cocoa --with-imagemagick`.  I have no entries in `user-config` or `user-init`, and the following layers enabled:

    helm
    auto-completion
    better-defaults
    emacs-lisp
    git
    markdown
    org
    (shell :variables
           shell-default-height 30
           shell-default-position 'bottom)
    spell-checking
    syntax-checking
    version-control

Note that this happens when opening files from the Finder *or* using `open -a Emacs <filename>`.  Using `emacs <filename>` does not open two windows.
