### ISSUE TITLE
Shell has faulty insertion behavior

### ISSUE THREAD

**Issue by travisallison** [syl20bnr/spacemacs#8061]
#### Description
When the default shell is something other than shell, the insertion behavior in the middle of a line is faulty.  The insertion jumps immediately to the end of the line.  See the following URL for a better visual description of the problem. 
http://stackoverflow.com/questions/40447007/spacemacs-multi-term-command-cannot-insert-text-in-existing-text

Note: it happens in the following shells: term, ansi-term and multi-term.

#### Reproduction guide
Start emacs
Make sure that the default shell is term, ansi-term, or multi term.
Open a terminal using SPACE '
Type a word at the prompt.  Escape. Go backwards a few steps using h key.  Type i for insertion mode.  Type a letter.

-*Observed behaviour:*
Letter will be inserted at end of line.
*Expected behaviour:*
Letter will be inserted in the middle of the word.

Note: if you maneuver backwards with the arrow key instead of escaping to command mode, you can insert into the middle of the word.  Also, if you move backwards with the arrow key while in insertion mode.  Then escape to command mode.  Move backwards with h key.  Then enter insertion mode and type a letter, the letter will be inserted where you escape to command mode.  It's as if the shell isn't being updated with the current cursor position when in command mode.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown c-c++ auto-completion ycmd evil-commentary
          (c-c++ :variables c-c++-enable-clang-support t)
          emacs-lisp git org ibuffer pdf-tools tmux
          (shell :variables shell-default-shell 'multi-term shell-default-width 30 shell-default-position 'bottom)
          version-control themes-megapack)
```

**Comment by xged** [comment]
Same (for a long time).

**Comment by chu-** [comment]
Same problem

**Comment by chu-** [comment]
#3125 Inconsistencies in ansi-terminal

**Comment by mattduck** [comment]
I believe this behaviour (and that in #3125) is due to the way the terminal process 
is handled in Emacs, which is described here: https://github.com/syl20bnr/spacemacs/issues/4063#issuecomment-162407568.

In the default term-char-mode, all characters in insert-state are sent to the
terminal, including control characters which can be used for movement. 
When you ESC to normal-state in Evil, your movement bindings are not sent to 
the terminal.

The "proper" way to use your Emacs bindings to edit text in term-mode is to
use term-line-mode and send the whole line at once, but this has its own
downsides - eg. you lose access to tab completion.

One workaround to get more familiar term bindings is to go into emacs-state,
and use `set -o vi`. This way you can ESC to access normal-mode within the
terminal.

Disclaimer: I'm not using spacemacs, just evil.
