### ISSUE TITLE
list packages in layers

### ISSUE THREAD

**Issue by mlinchitstest** [syl20bnr/spacemacs#8103]
is there a way to list the subordinate packages of all layers? Whenever I find a package on melpa, I'm often wondering whether spacemacs has a layer for it (and whether I should add that layer), or if I should just install it from the repo by adding it to ` dotspacemacs-additional-package`. each spacemacs layer installs a number of packages and I'd like to know if there is a way to list these packages.

**Comment by crshd** [comment]
I usually just `grep -r "package" layers/*`

**Comment by d12frosted** [comment]
There is a nice functionality in Spacemacs just for this. `SPC h SPC` is hard artillery that allows to search many things (especially if you are using `helm` completion system). Usually I use more specific help / search commands. For example, `SPC h l` allows to search layers and quickly jump to `readme`, `package.el`, `config.el`, `funcs.el` etc. `SPC h p` is for searching packages. It's a nice command because it also shows which layer configures this package.

Checkout `which-key` popup after hitting `SPC h` for more useful key bindings. More info can be found in the [documentation](https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#getting-help).

**Comment by mlinchitstest** [comment]
Thanks! quick question (i'm new to emacs): emacs has an `easy customization` interface. i notice that some variables have already been set by spacemacs, but there are still lots of free variables. In principle, is it ok to use `easy customization` with spacemacs? Is it ok to use `setq` in that command bar at the bottom? Or should this be avoided?

**Comment by bmag** [comment]
@mlinchitstest if you're on master branch, variables set by the customize interface are loaded very early in the startup process (probably too early, depending on what you're trying to change), so it's more reliable to put `setq` calls (and others) in `user-init` and `user-config`. On develop branch it should be ok to use customize, since it is now better incorporated into the startup process.

**Comment by d12frosted** [comment]
Closing this issue as initial question is answered.
