### ISSUE TITLE
`SPC m` undefined in org-mode

### ISSUE THREAD

**Issue by Troyciv** [syl20bnr/spacemacs#8106]
#### Description :octocat:

In org-mode: when having a `# SETUPFILE: anyfile` line in the document, the `SPC m` entry gets lost, as well as the `,` major-mode leader key.

#### Reproduction guide :beetle:
- Start Emacs
- only org layer enabled
- create a new file `test.org` that contains the followed:
```
# TITLE: test
# SETUPFILE: anyfile.org
* org test
```
- `SPC f s`
- `SPC b d`
- `SPC f f` open test.org
- press `,` or `SPC m`

*Observed behaviour:* :eyes: :broken_heart:

when `,` pressed: `Can't find`

when `SPC m` is pressed: `SPC m is undefined`

*Expected behaviour:* :heart: :smile:

- open the org mode command menue

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(org)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
Tried to reproduce this on Linux with 
* Emacs 25.1.1 
* Spacemacs 0.200.7 
* On master as well as on develop

Unfortunately I did not encounter any errors while I was working with your test file.
Could you update your Emacs version to 25.1.1 and check whether the issue persists?

**Comment by j-martin** [comment]
Confirming I have the same issue with 24.5.1 and Org-mode 9.0.3.

Pressing esc solves the issue.

I also ended up writing a wrapper fn for it:

```
(defun jm/open-file (file)
  (find-file (expand-file-name file))
  (evil-normal-state))
```

**Comment by smile13241324** [comment]
Hmm I have actually ment that it could be interesting whether this still happens with emacs 25. Anyway I have an older 24.5.1 emacs at work maybe I can reproduce it there.

In the meantime would you mind adding a backtrace to your issue because currently I have no idea where this could come from.

Btw: Do you set some org settings in your dotfile without a 
```lisp 
(with-eval-after-load 'org
  ;; here goes your Org config :)
  ;; ....
  )
```
construct? This will trigger spacemacs to load the elpa distribution of org rather than the melpa one which could cause various issues. 

[org readme](https://github.com/syl20bnr/spacemacs/tree/b7e51d70aa3fb81df2da6dc16d9652a002ba5e6b/layers/%2Bemacs/org)

**Comment by smile13241324** [comment]
I have tried to reproduce your issue on my old emacs 24.5.1 on develop. However I was not successful.

Awaiting your backtrace.

**Comment by simpler360** [comment]
![image](https://cloud.githubusercontent.com/assets/12069254/23587720/50feb664-01d8-11e7-87ef-4cae7fa79a9c.png)
I am a new user of emacs, Even I am getting same error with emacs 25.1. Screenshot

**Comment by simpler360** [comment]
If you see evil-org-mode is not enabled (E) that is E with circle only (K) is present in the list

**Comment by simpler360** [comment]
How to get a backtrace? I can past it.

**Comment by simpler360** [comment]
tried SPC t D for backtrace. 
but after the message SPC m is undefined 
there is know Backtrace buffer

**Comment by simpler360** [comment]
Sorry I am very new to Emacs

**Comment by simpler360** [comment]
spacemacs version  0.200.7@25.1.2 
on Ubuntu 16.04( elementary os loki)

**Comment by simpler360** [comment]
![image](https://cloud.githubusercontent.com/assets/12069254/23587928/70b5cf76-01db-11e7-9eb1-7e30cd36d760.png)
Also there is no option displayed as m after pressing spc

**Comment by simpler360** [comment]
Also there is no option with m after pressing SPC
![image](https://cloud.githubusercontent.com/assets/12069254/23587954/b0fae634-01db-11e7-9322-a2fc5ef79aa9.png)

**Comment by simpler360** [comment]
Please disregard my request, As I was a new user did not know had to remove the comments in the .spacemacs file

**Comment by smile13241324** [comment]
@simpler360 Well now I am confused are you still able to reproduce this issue? If yes could you please supply your dot file and short instructions how to reproduce.

**Comment by Vezill** [comment]
I've also been having this issue for the last week or so since switching to develop and the solutions suggested are not working (edit and save the file, enter and exit insert-mode, pressing esc). The only real changes to my .spacemacs file recently was updating it with all the new changes in develop, as well as removing unused stuff and cleaning it up.

I've included my [.spacemacs](https://github.com/syl20bnr/spacemacs/files/1001710/spacemacs.txt) file just in case it helps, although I'm still learning emacs/spacemacs so hopefully it's not too bad lol.

**Comment by smile13241324** [comment]
@Vezill Hi there, thanks for your .spacemacs file, I was finally able to reproduce the issue. The problem is that you are using `vanilla org-mode` instead of the official `org layer` thanks to not listing `org` in your layers list. 

This also means that the layer specific keybindings are not set as `org/init-org` is not called, thus the missing major mode binding.

When you add the org layer all works fine.

Btw by scanning your spacemacs file I have noticed an error in your `user-config` which will also prevent emacs from loading org correctly. You are trying to set `(add-hook 'org-mode org-mode-adaptive-wrap)` which fails as it must be `(add-hook 'org-mode 'org-mode-adaptive-wrap)` instead. Also you are trying to add this to `org-mode` but you should add it to `org-mode-hook` instead.

@d12frosted I have reproduced the issue but I am not sure that this is really a bug, would you mind having a quick look into it? Seems that it is possible to load `org` without `org layer` which will cause missing keybindings.

**Comment by Vezill** [comment]
Thanks for taking a look at my config file @smile13241324 ! Nice catch on the org-mode hook, I'm still learning lol.

I actually noticed myself a few days after posting that I was missing it, and it seemed to fix the problem for a little while. Today while adding a new value to `org-todo-keywords`, when I went to test it I ran into the same problem again. After running a diff on my old vs current config file I noticed emacs had put more packages into `package-selected-packages`, including `org-plus-contrib`, and I couldn't get org-mode to work again until I removed it. 

I'm not too sure why this would be, but maybe this info will help.

**Comment by cjpoor** [comment]
I found that I had to (require 'org) to resolve this issue (at least it seems to be resolved.)
Mint linux, Spacemacs  0.200.13@27.0.50

**Comment by dmitry-kabanov** [comment]
I had the same issue (`SPC m` is undefined).

It turned out that I forgot to enable `org` layer by adding `org` to the list `dotspacemacs-configuration-layers`.

Maybe it should be mentioned somewhere at the beginning of the documentation on the `org` layer.

**Comment by smile13241324** [comment]
Not sure how to make it more obvious than it already is. Currently doc for org says 
```
Since version 0.104, spacemacs uses the org version from the org ELPA repository instead of the one shipped with emacs. Then, any org related code should not be loaded before dotspacemacs/user-config, otherwise both versions will be loaded and will conflict.

Because of autoloading, calling to org functions will trigger the loading up of the org shipped with emacs which will induce conflicts. One way to avoid conflict is to wrap your org config code in a with-eval-after-load block like this:
```

Also the installer step mentiones that for using the layer it must be added to the dotfile and gives a code example.

Recommendations?

**Comment by dmitry-kabanov** [comment]
@smile13241324 Well, something like a warning block that states that if you get a "`SPC m` is undefined" errors, it means that you forgot to add `org` layer to the `.spacemacs`.

I guess, it should be enough.

**Comment by smile13241324** [comment]
Agreed, I will add a warning to the org layer readme next time I am working on spacemacs.

**Comment by smile13241324** [comment]
@dmitry-kabanov I have adjusted the Readme.md for 'org'. Would you mind checking whether the current version is more clear?

**Comment by cjpoor** [comment]
So sorry, but I cannot see any difference. What did you change?

**Comment by dmitry-kabanov** [comment]
@smile13241324 Yes, your pull request (#10985) looks fine to me.
