### ISSUE TITLE
SPC c h hide/show-comments-toggle does not work

### ISSUE THREAD

**Issue by zwb-ict** [syl20bnr/spacemacs#8123]
#### Description :octocat:
SPC c h does not work

#### Reproduction guide :beetle:
- backup .emacs.d and .spacemacs.d
- git clone https://github.com/syl20bnr/spacemacs.git ~/.emacs.d -b develop
- Start Emacs
- open a c file with comments
- run SPC c h

*Observed behaviour:* :eyes: :broken_heart:
comments cann't be hide

*Expected behaviour:* :heart: :smile:
comments can be hide

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 3bbeae)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers: ```helm emacs-lisp```

**Comment by yqrashawn** [comment]
Same thing happen in js2-mode.

**Comment by duianto** [comment]
It seems like the <kbd>SPC c h</kbd> `hide/show-comments-toggle` command toggles the `invisible` text property between: `hide-comment` and `nil`. 

But characters don't get hidden unless their `invisible` text property is set to `t`.

The `hide/show-comments-toggle` only seems to be looking for if there is no `invisible` property, or if it's set to either: `hide-comment` or `nil`. Because it doesn't change the `invisible` property when it's set to `t`.

#### Steps to reproduce:
- Start emacs
- Open the *scratch* buffer: <kbd>SPC b s</kbd>
- Change it to `emacs-lisp-mode`: <kbd>SPC SPC</kbd> `emacs lisp` <kbd>RET</kbd>
- Type:
```
one
two
three
```
- Move the cursor over the `t` in `two` and comment out the line: <kbd>SPC c l</kbd>
- The text properties can be viewed by evaluating: 
<kbd>S-M-;</kbd> type: `(describe-text-properties (point))` <kbd>RET</kbd>
before trying to hide the comment the properties are:
```
Text content at position 5:


There are text properties here:
  face                 font-lock-comment-delimiter-face
  fontified            t
```
- Move back the cursor to the scratch buffer window: <kbd>SPC b s</kbd>
- Try to hide the comment: <kbd>SPC c h</kbd>
- Check the text properties again by evaluating the previous command: <kbd>S-M-;</kbd> <kbd>M-p</kbd> <kbd>RET</kbd>
now the `invisible` text property has been added:
```
  invisible            hide-comment
```
but the comment is still visible.

- Move back the cursor to the scratch buffer window again: <kbd>SPC b s</kbd>
- Run the <kbd>SPC c h</kbd> `hide/show-comment-toggle` command again. It changed the invisible text property to:
```
  invisible            nil
```

- Move back the cursor to the scratch buffer window: <kbd>SPC b s</kbd>
- Change the `invisible` property of the character under the cursor to `t`:
<kbd>S-M-;</kbd> type: `(put-text-property (point) (1+ (point)) 'invisible t)` <kbd>RET</kbd>
Now the character under the cursor isn't visible in the buffer anymore.

- The <kbd>SPC c h</kbd> `hide/show-comment-toggle` command doesn't change the `invisible` property when it's set to `t`.

#### Show characters with the `invisible` property
One way of showing every character with the `invisible` property, is to move back the cursor to the scratch buffer <kbd>SPC b s</kbd> and evaluating <kbd>S-M-;</kbd> the command: 
`(remove-text-properties (point-min) (point-max) '(invisible))`.

But it probably has other side effects because a comment in `hide-cmnt.el` says: 
>               ;; Do nothing to text that is already invisible for some other reason.

It sounds like there's other ways of hiding text. And the `remove-text-property` command will make that text visible as well.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. acb2d37)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey emacs-lisp git helm html org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by duianto** [comment]
I read about the invisibility property here:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Invisible-Text.html

There's a variable called: `buffer-invisibility-spec`, when it has the default value `t`, then any non-nil `invisible` property hides the text. This is probably what the `hide-cmnt.el` package expects.
The variable can be viewed by describing the variable <kbd>C-h v</kbd> type: `buffer-invisibility-spec` <kbd>RET</kbd>.

When the scratch buffer is set to it's default mode: `fundamental-mode`, then the `buffer-invisibility-spec` is set to `t`. And when the `invisible` property is set to `hide-comment`, then the text is hidden.

But when the scratch buffer is changed to `emacs-lisp-mode`, then the hidden text is visible again, and the `buffer-invisibility-spec` variable has changed to:
>buffer-invisibility-spec is a variable defined in ‘C source code’.
> Its value is ((hs . t) t)
> Local in buffer *scratch*; global value is t

It's value is a list within a list, but according to the invisible-text page, the acceptable values seem to be:

> t
> A character is invisible if its invisible property is non-nil. This is the default.
> 
> a list
> Each element of the list specifies a criterion for invisibility; if a character’s invisible property fits any one of these criteria, the character is invisible. The list can have two kinds of elements:
> 
> atom
> A character is invisible if its invisible property value is atom or if it is a list with atom as a member; comparison is done with eq.
> 
> (atom . t)
> A character is invisible if its invisible property value is atom or if it is a list with atom as a member; comparison is done with eq. Moreover, a sequence of such characters displays as an ellipsis.

#### possible solution
Maybe the value is supposed to be just: `(hs . t)` without the outer `( t)`.

**Comment by bmag** [comment]
Technically the value `((hs . t) t)` is a valid value, but the problem is that the lone `t` changes in meaning from "any non-nil value is invisible" to "t value is invisible" because of the presence of `(hs . t)`. The value `(hs . t)` is added by `hs-minor-mode` ("Hide-Show").
We enable `hs-minor-mode` in all programming major modes because it is required for Evil folding to work. As a work-around, we can add a hook to `hs-minor-mode-hook` that calls `(add-to-invisibility-spec '(hide-comment . t))` or `(remove-from-invisibility-spec '(hide-comment . t))` as appropriate.

Ultimately, this integration problem between `hide-cmnt.el` and `hideshow.el` should be fixed upstream, so please report the issue upstream. In this case, upstream seems to be this [page](https://www.emacswiki.org/emacs/HideOrIgnoreComments) in EmacsWiki for `hide-cmnt.el` and the emacs bug tracker (`M-x report-emacs-bug)` for `hideshow.el`.

**Comment by zwb-ict** [comment]
@yqrashawn @duianto @bmag  Would you please report this to  upstream? I'm not good at describe issue，and don't how to use ```report-emacs-bug```. In my country, Google cann't be visited. Thank you very much!

**Comment by duianto** [comment]
I sent a mail to the maintainer of `hide-cmnt.el` and one of the authors of `hideshow.el`, with a quick explanation of what i understand about the issue, with a copy of bmags answer, and pointed them to this issue.

**Comment by duianto** [comment]
I got a response:
> Thanks for the report, Duianto.  I think this is fixed now.
> Please try the latest, from MELPA (in up to a day) or from
> here now: https://www.emacswiki.org/emacs/download/hide-comnt.el
> 
> BTW, the explanation given on that GITHUB page (for issue 8123)
> is not quite correct.  An entry such as `(hs . t)' in
> `buffer-invisibility-spec' means that ellipsis is shown instead
> of the invisible text.
> 
> The correct fix for hide-comnt.el is not to add an entry such
> as `(hide-comment . t)' but to add a `hide-comment' entry.
> We want just invisible text for hidden comments, no ellipsis.
> 
> Thx - Drew

**Comment by duianto** [comment]
It seems to be working:

- I downloaded the new version from: https://www.emacswiki.org/emacs/download/hide-comnt.el
- In the `.emacs.d\elpa\hide-comnt-20170101.1008` folder, i backed up the `hide-comnt.el` and `hide-comnt.elc` files, (i made copies of them and added `_backup` to the end of the copies)
- I then copied the new `hide-comnt.el` and paste it into the `.emacs.d\elpa\hide-comnt-20170101.1008` folder, when asked to replace the current version i answered `yes`
- I restarted Emacs and opened the `.spacemacs` file <kbd>SPC f e d</kbd>
- I tried hiding the comments with the key binding <kbd>SPC c h</kbd>, Emacs showed this message: 
`Source file ‘c:/Users/(username)/AppData/Roaming/.emacs.d/elpa/hide-comnt-20170101.1008/hide-comnt.el’ newer than byte-compiled file`
- I opened the `hide-comnt.el` file and byte compiled it with the key binding <kbd>, c c</kbd>
- I restarted Emacs and now the comments in `.spacemacs` are shown and hidden with the <kbd>SPC c h</kbd> key binding.

@zwb-ict can you try if it also works for you?

**Comment by duianto** [comment]
The steps above aren't needed anymore, the `hide-comnt` package has been updated on MELPA so one just have to open the Spacemace home buffer <kbd>SPC b h</kbd>, press <kbd>m</kbd> to jump to the top menu and navigate to 
`[Update Packages]` and press <kbd>RET</kbd> to start updating the packages.

**Comment by zwb-ict** [comment]
@duianto Perfect! I update ```hide-comnt``` to the latest, it works very well. Thank you very much!

**Comment by bmag** [comment]
@duianto thank you :+1:

**Comment by duianto** [comment]
@bmag you pointed the way to the solution so thank you 👍 

Is there anything that has to be done with the `hideshow.el` file/package?
Or should i mail the author that the issue was solved in the `hide-comnt` package, so nothing needs to be changed in `hideshow.el`?

**Comment by zwb-ict** [comment]
@bmag Thank you very much!

**Comment by bmag** [comment]
> should i mail the author that the issue was solved in the hide-comnt package

Yes, it would be courteous to tell `hideshow.el`'s author that our problem has been fixed.

**Comment by duianto** [comment]
I sent a mail informing them that the issue has been resolved.
