### ISSUE TITLE
config error messages vanish when you maximize the window

### ISSUE THREAD

**Issue by mlinchitstest** [syl20bnr/spacemacs#8169]
on startup, spacemacs sometimes gives error messages about its config. these problem is that these messages vanish when you maximize or resize the program window (in windows). if you have spacemacs open as a maximized-window on start-up, these messages will vanish the moment the maximization setting kicks in. 

(p.s. is there a command to bring up these errors manually?)

thanks

**Comment by bmag** [comment]
You can check if the errors appear in the `*Messages*` buffer (not sure, though). If you don't want them to vanish, change the value of `dotspacemacs-startup-buffer-responsive` to `nil` in your dotspacemacs.

**Comment by deb0ch** [comment]
@mlinchitstest are you on `master` or `develop` ? And what are these messages exactly ?

The way the home buffer works has changed between `master` and `develop`. There used to be some stuff disappearing on resize that are not anymore, just not sure if we are talking of the same thing.

Also, when reporting a bug, the output of `SPC h d s` (`describe-system-info`) is really useful, as it is full of information that might help finding and fixing the bug. It is included by default if you use the standard issu reporting template (`SPC h I` to get it, you can even submit from there.)

**Comment by mlinchitstest** [comment]
@bmag 's solution is correct, though i guess it's not worth the loss of responsiveness. 

```
#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.6
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(html helm auto-completion better-defaults emacs-lisp git tabbar org bibtex spell-checking syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS
```

thanks!

**Comment by deb0ch** [comment]
> - Spacemacs branch: nil (rev. nil)

Mmmmh, I guess you are still on the default branch (`master`) ? Or did you switch to `develop` ? This line was the point of me requiring your system info, but I didn't expect it to be empty like that :open_mouth:

**Comment by mlinchitstest** [comment]
i'm guessing it's the default branch. I cloned the repo from the url on your homepage.

**Comment by deb0ch** [comment]
Thanks !

And about these messages that disappear, what are they exactly ? What do they say, what do they look like ? Do you have a screenshot ? :smile_cat:

**Comment by mlinchitstest** [comment]
This is just a line of text with red background that appears right above the powerline.  It says you have some error in your config. I already fixed the error, and have a hard time generating a new one like it for some reason.

**Comment by deb0ch** [comment]
Ok, nice ! Yes, these sometimes comes and goes. Like when you just enabled a layer and don't have internet connectivity to download the packages at startup or when your elisp in your configuration triggers an error or stuff like that.

If it's gone don't worry about it, especially if you don't reproduce, mate :smile_cat:

**Comment by duianto** [comment]
I also ran into this issue.

When a package fails to install, then the error message is shown on the home buffer:

![emacs_2018-02-03_17-27-05](https://user-images.githubusercontent.com/13420573/35771249-de90996c-0929-11e8-8675-58d527c116d0.png)


but the error message disappears if the home buffer is refreshed.
For example: if the frame is maximized: `SPC T M`, or if one opens the filetree `SPC f t`

The error message is not shown in the `*messages*` buffer.

I wonder if it would be better to show the home buffer messages (package installs/updates, etc.) in a separate buffer, or if they also should be printed in the messages buffer, but then they only will be available during the current session, and only as long as more messages hasn't appeared so that they have been pushed outside the buffer.

A possible solution might be, if there was a log file with the most recent messages. Then one could read them even if the current Spacemacs session is broken. But I'm not sure how many recent messages the log should keep?

#### Side note
The mode line is hard to read when the background is bright red with the default light text.
Should it be fixed by the Spacemacs theme, a mode line package or in Spacemacs?
