### ISSUE TITLE
Reproduce a close issue: Package is installed on startup then deleted as an orphan right away(1538)

### ISSUE THREAD

**Issue by qzhao2007** [syl20bnr/spacemacs#8186]
I still meet this issue with emacs 25.1 on mac os seirra, and set dotspacemacs-delete-orphan-packages nil also not work.

From the comments, I find other guys also still meet this issue, so I create a new issue, for the detail, please refer: https://github.com/syl20bnr/spacemacs/issues/1538  to get the detail info.

**Comment by bmag** [comment]
According to that issue, it was fixed at November 2015 by #3663. Since then, a number of people commented saying "I too have this problem", but with no further details. Personally, I'm not convinced it's the same problem, since I don't know what you have tried, what behavior you observed, what packages are being deleted, what's your config, etc.
Please add some detail about your particular case. This [page](https://github.com/syl20bnr/spacemacs/wiki/Debugging) can help you, but please also state how you are trying to install the failing packages,

**Comment by qzhao2007** [comment]
I install package by using M+x package-install and install tabbar, tabbar-ruler,tablist, tab-group.
After adding there 4packages and restart emacs, it says the packages are orphan  and deleted.

I use the spaceemacs master branch without any private change.

wish this  can help you reproduce it.

**Comment by bmag** [comment]
That's less info that what I expected, but luckily it's enough to understand the problem. You did not install the packages correctly. Please read this [FAQ entry](http://spacemacs.org/doc/FAQ#why-are-packages-installed-with-package-install-automatically-deleted-by-spacemacs-when-it-boots) for an explanation.

**Comment by bmag** [comment]
By the way, `dotspacemacs-delete-orphan-packages` was removed and replaced by `dotspacemacs-install-packages`

**Comment by deb0ch** [comment]
I really feel like we should advise the `package-install` function and similar to display a warning message, or even error out as this way won't work anyways if using Spacemacs.

**Comment by bmag** [comment]
Spacemacs uses `package-install` internally, so you'll have to rely on `called-interactively-p` to distinguish between user calls and program calls. You'll also have to advise `package-install-button-action`, and perhaps more user-facing functions that handle installation of package. (if we decide to warn users before installation, we should cover all the cases, otherwise we'll have inconsistency and a less predictable program)

Besides, there's always the fear that advices will have some unexpected effect down the line. As `package-install` is a fundamental function, we should be 100% sure the advice has no ill effects.

Instead, we can post a helpful message on the home buffer when deleting orphan packages. It would only help the user after he already installed packages manually, but at least we won't have to touch `package-install`.

**Comment by deb0ch** [comment]
I prefer the approach of preventing the user from doing stuff that has 0% chance of working beforehand, instead of telling him afterwards that he did :shit: (and he might not even read / understand the message).

Just having that Emacs functionality that has 0% chance of working in Spacemacs available to the user is an inconsistency and goes against POLA.

If we can rely on `called-interactively-p`, I'm sure we can use it just once just on the right function that will cover all the use cases without too much risk.

It's a theory that has yet to be proven but I feel like it's worth the effort :smile_cat:

**Comment by nixmaniack** [comment]
> or even error out as this way won't work anyways if using Spacemacs.

Warning is OK but no error out. I install lots of packages with `package-install` just to try them out and don't care about them until I like something which I add to additional packages. So error out leaves no way of installing packages in running instance. 

Also, advising core functions doesn't sound good as explained by bmag.

**Comment by deb0ch** [comment]
> I install lots of packages with package-install just to try them out and don't care about them until I like something which I add to additional packages. 

Oh, never thought of this use case but it totally makes sense :open_mouth: So I retract my suggestion about error out, but I still feel like something should be done to warn the user **in a way he will be forced to see it**, without being too intrusive.

Because it is a recurrent subject in the gitter chat, users using this function to install packages, and then having the astonishment of seeing their freshly installed package meanly erased by Spacemacs, being confused, not knowing what to do and asking about it in the chat. And for 1 who asks I'm sure there are 10 who don't, give up and keep their frustration.

Giving a warning when the orphan package is deleted could be a solution, but a much better solution would be to give this warning *before* the user restarts.

And without advises I don't see how to achieve this.

Also, I don't quite grasp the danger of using advises in this case, especially if the advice doesn't prevent the advised function from behaving like it usually does (just giving warnings, right ?).

**Comment by bmag** [comment]
> Just having that Emacs functionality that has 0% chance of working in Spacemacs available to the user is an inconsistency and goes against POLA.

True, didn't think of that.

>If we can rely on `called-interactively-p`, I'm sure we can use it just once just on the right function that will cover all the use cases without too much risk.

Some use `M-x package-install`, some will open the package list and install by clicking the buttons (`package-install-button-action`). It's not "just once on the right function", unless `called-interactively-p` around `package-install` can determine when another function is called interactively (I did a small test and it seems it doesn't).

@deb0ch you convinced me that we should warn the user beforehand, if we can do that without causing trouble elsewhere (e.g. in Spacemacs' own installation process).

**Comment by syl20bnr** [comment]
What we can do is to add an `around` advice whose only purpose is to check if a variable is set, something like `spacemacs--install-package`. Everywhere Spacemacs uses `install-package` we let bind the variable to `t`, so we can detect when the function is called outside of Spacemacs layer system. 

`package-install-button-action` does not call `install-packag` down the line ?

**Comment by deb0ch** [comment]
It does:
``` elisp
(defun package-install-button-action (button)
  (let ((pkg-desc (button-get button 'package-desc)))
    (when (y-or-n-p (format "Install package `%s'? "
                            (package-desc-full-name pkg-desc)))
      (package-install pkg-desc)
      (revert-buffer nil t)
      (goto-char (point-min)))))
```

**Comment by bmag** [comment]
@deb0ch thanks for checking. @syl20bnr's solution is simple and easy, I'm in favor.
