### ISSUE TITLE
nlinum line numbers going nuts

### ISSUE THREAD

**Issue by deb0ch** [syl20bnr/spacemacs#8210]
Whenever I use the `nlinum` line numbers, it's only a few edits until they go into a mess, giving totally wrong numbers.

This happens when inserting newlines, pasting code or undoing a change that deleted some lines. Basically, whenever lines are inserted into the buffer. Not sure if anything else also triggers it.

A quick example from a few seconds of using `nlinum`:
![image](https://cloud.githubusercontent.com/assets/6248219/22102960/9b9e76b8-de39-11e6-8e3c-c8682994780a.png)

Sometimes I also get negative (negative ! :scream_cat:) values:

![image](https://cloud.githubusercontent.com/assets/6248219/22103978/7fdc261a-de3d-11e6-9996-027009fa53b6.png)

(on this screenshot, the numbers 503 and 504 are correct. On this exemple, the numbering was right until line 162 and then started again at -338 on the next line.

**EDIT:** I am **not** using relative line numbers in these examples. It haven't reproduced it with relative nlinum.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. bfec178)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables :disabled-for markdown org erc)
 (better-defaults :variables better-defaults-move-to-beginning-of-code-first nil better-defaults-move-to-end-of-code-first t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support nil)
 (colors :variables colors-enable-nyan-cat-progress-bar nil)
 common-lisp csv emacs-lisp
 (erc :packages
      (not erc-social-graph)
      :variables erc-server-list
      '(("jinan.parrot.biz" :ssl t :port "7000" :nick "ThomdB" :full-name "Thomas de Beauchene")))
 git github gtags helm markdown multiple-cursors nlinum org pdf-tools
 (python :variables python-enable-yapf-format-on-save t python-sort-imports-on-save t)
 ranger
 (shell :variables shell-default-height 50 shell-default-position 'bottom)
 shell-scripts spacemacs-layouts
 (syntax-checking :variables syntax-checking-use-original-bitmaps nil)
 themes-megapack version-control vim-empty-lines xkcd ycmd)
```

**Comment by duianto** [comment]
I might have found a clue to what's causing this issue, it seems to happen when the relative numbers scroll outside the window.

### Steps to reproduce
1. with the `nlinum` layer installed (added as a configuration layer and emacs was restarted).
2. start emacs.
3. open `.spacemacs` <kbd>SPC f e d</kbd>.
4. go to the first line `evil-goto-first-line` <kbd>g g</kbd>.
5. enable line numbers `spacemacs/toggle-line-numbers` <kbd>SPC t n</kbd>.
6. enable relative line numbers `nlinum-relative-toggle` <kbd>SPC t r</kbd>.
7. scroll down one line at a time `evil-scroll-line-down` <kbd>C-e</kbd> 10 times.
8. disable relative line numbers <kbd>SPC t r</kbd>.
9. go to the first line <kbd>g g</kbd>.

#### Observed behavior
The relative modes current line highlight was left behind on the lines that scrolled up.

![nlinum-relative-scroll-down](https://cloud.githubusercontent.com/assets/13420573/22970508/b5171638-f372-11e6-90c1-e85acdd06c46.png)

### Scroll up
A similar thing happens when one scrolls up, with the cursor at the bottom of the window.
After step 6, scroll one page down `evil-scroll-page-down` <kbd>C-f</kbd>.
move the cursor to the bottom of the window `evil-window-bottom` <kbd>S-l</kbd> (Shift + lowercase L).
scroll up one line at a time `evil-scroll-line-up` <kbd>C-y</kbd> 10 times.
disable relative line numbers <kbd>SPC t r</kbd>.
scroll down half a page `evil-scroll-down` <kbd>C-d</kbd>.

#### Observed behavior
A long line of 1's remained when they scrolled down below the window.

![nlinum-relative-scroll-up](https://cloud.githubusercontent.com/assets/13420573/22970515/bd654d5a-f372-11e6-8f7d-ef315aefec00.png)

### Scroll down by 5
Another example when scrolling by 5 lines at a time
After step 6, press <kbd>5 C-e</kbd> to scroll down 5 lines, this also sets the <kbd>C-e</kbd> and <kbd>C-y</kbd> scroll commands to scroll by 5 lines at a time from now on.
press <kbd>C-e</kbd> 4 more times.
disable relative line numbers <kbd>SPC t r</kbd>.
go to the first line <kbd>g g</kbd>.

#### Observed behavior
![nlinum-relative-scroll-by-5-lines](https://cloud.githubusercontent.com/assets/13420573/22970607/057c8d74-f373-11e6-939d-d85665bde915.png)

### Reset the scroll commands
To reset the <kbd>C-e</kbd> and <kbd>C-y</kbd> scroll commands to only scroll by one line at a time again.
Prepend a `1` as a digit argument <kbd>1 C-e</kbd>.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 3072e727)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((markdown :variables markdown-live-preview-engine 'vmd)
 auto-completion chrome emacs-lisp git helm html markdown nlinum org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS
