### ISSUE TITLE
CUSTOM_ID tags showing in develop.spacemacs.org

### ISSUE THREAD

**Issue by deb0ch** [syl20bnr/spacemacs#8216]
Reporting here since the org files used for generation are in this project.

every CUSTOM_ID tags from DOCUMENTATION.org (haven't checked the others) is showing on develop.spacemacs.org (for instance [here](http://develop.spacemacs.org/doc/DOCUMENTATION.html#replacing-text-with-iedit)) like on this screenshot:

![image](https://cloud.githubusercontent.com/assets/6248219/22141969/b7ecb79c-def4-11e6-8f42-17ed15c748ce.png)

**Comment by nixmaniack** [comment]
syl20bnr did [mention](https://github.com/syl20bnr/spacemacs/pull/8146#issuecomment-272358064) about that when he merged. Looks like @nikolaiam has solution [there](https://github.com/syl20bnr/spacemacs/pull/8146#issuecomment-272370528).

**Comment by nikolaiam** [comment]
Yes, I did propose the solution but don't have any idea how to execute it as I don't know anything about the conversion process :smile: If you happen to have some pointers on where to start I can look into that, although it might a bit too challenging for my non-existent elisp skills.

**Comment by smile13241324** [comment]
@deb0ch Is this issue still valid? 

I have checked the documents on develop.spacemacs.org and they do not show `PROPERTIES` tags anymore though they are in the file.

Btw seems that the link to the contribution guide is broken.

**Comment by deb0ch** [comment]
Just checked and still there :confused: 
I went to http://develop.spacemacs.org/doc/DOCUMENTATION.html under `Zooming`, just like in the screenshot.

**Comment by smile13241324** [comment]
Sorry I just searched for `:PROPERTIES:`.

The reason for this issue is the manually added `CUSTOM_IDs`. With the current export mechanic those ids are added automatically but it is not checked whether the ID is already existing. If it is we create a duplicate ID which is shown in the export.

To solve the issue we would simply have to remove the manually added ones, then all should work well.
Alternatively we could modify `spacemacs//org-heading-annotate-custom-id` to check for existing :PROPERTIES: drawers and only add new ones if necessary. But I am not so sure that this would be worth it, I mean who would add those drawers anyway.

**Comment by smile13241324** [comment]
Link to related merge request #8465
