### ISSUE TITLE
spacemacs/python-execute-file still uses default interpreter after switching python environments

### ISSUE THREAD

**Issue by alcazoid** [syl20bnr/spacemacs#8244]
#### Description :octocat:
spacemacs/python-execute-file still uses default interpreter after changing env with pyenv.

#### Reproduction guide :beetle:
- Start Emacs
- Create a python file with the following code, printing path to interpreter:
```
import sys
print sys.executable
```
- Switch python environment with SPC-m-V-a
- Run the script with SPC-m-c-c

*Observed behaviour:* :eyes: :broken_heart:
The script prints the path to the default python interpreter(first found in PATH). BTW, SPC-e-v shows that python-pycompile checker actually has correct path to the interpreter, it's just spacemacs/python-execute-file that doesn't know anything about it. Also, SPC-m-' starts REPL in correct env.

*Expected behaviour:* :heart: :smile:
It is expected that the script will be executed with the interpreter from the env chosen, not the first interpreter found in PATH.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(javascript ivy emacs-lisp dash git markdown osx python themes-megapack ess syntax-checking)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by alcazoid** [comment]
Same issue with [conda.el](https://github.com/necaris/conda.el) package for emacs, instead of pyenv.

**Comment by braham-snyder** [comment]
Quick workaround for me was to just use `<major-leader> s B` instead--may or may not require `python-shell-interpreter` to be `"ipython"`.

And FWIW: my attempt to use `python-shell-interpreter` in `spacemacs/python-execute-file` didn't seem to work, nor did `python-shell-get-process-or-error` (which is used in `<major-leader> s B`).

**Comment by christopherlatorres** [comment]
Having this same issue of not changing python interpreter.

**Comment by cpaulik** [comment]
Are you sure that you are using pyenv and not py**v**env. The command `SPC m V a` is for py**v**env. Because it works with pyenv for me.

**Comment by sp3ctum** [comment]
Could it be related to the system itself? I get the same result on fedora. And I am indeed using pyenv.

In the terminal I get access to Python 3, which is what I want to use, but in emacs it defaults to version 2.7, which is not even the default on my system.

I have a hunch that a bunch of other stuff is also broken :(

**Comment by alcazoid** [comment]
@cpaulik you are correct, it's pyvenv

@sp3ctum not sure, I'm on macOS

**Comment by frodera** [comment]
Same problem as the OP here (OS X, Spacemacs 0.200.13@26.1).
Spacemacs ignores the Python version set via **pyvenv** (SPC-m-V-w, _pyvenv-workon_) and just uses system's default.

In my case my venv is a Conda environment:
```
> /Users/frodera/miniconda3/envs/python37/bin/python --version                                                                                                         
Python 3.7.0
```

After setting the env via `SPC-m-V-w`, emacs reports that the path of that env is the first one listed in Spacemaçs' `PATH` and it even lists it in the status bar. However, when running a python script via `SPC-m-c-c` it reverts to system's default (2.7). See attached image.

`getenv "PATH" -> /Users/frodera/miniconda3/envs/python37/bin:/usr/local/opt/coreutils/...`

![screen shot 2018-08-05 at 11 05 18](https://user-images.githubusercontent.com/219724/43681761-cfad2e68-98a0-11e8-8c0e-9c546beea2ae.png)

**Comment by tshu-w** [comment]
same issue here with conda layer, please not close it.

**Comment by tshu-w** [comment]
active

**Comment by dgealow** [comment]
Is there any variable I can set to hardcode the python version it runs as a workaround?

**Comment by tshu-w** [comment]
@dgealow maybe `python-shell-interpreter`

**Comment by dgealow** [comment]
Actually, I found the problem. In [layers/+lang/python/packages.el](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/python/packages.el), the function `spacemacs/python-execute-file` contains the line `(compile-command (format "python %s" (file-name-nondirectory`... , which essentially means that it will always run whatever the default version of python is regardless of any environments or spacemacs variables. It looks like there's a more robust fix in the works in the latest development branch (haven't tested it yet) but as a workaround I just changed that like to ...`format "python3 %s"...` since my default Python 3 installation is what I want 99% of the time.

**Comment by lebensterben** [comment]
Closing now.
Please always use develop branch.

**Comment by tshu-w** [comment]
This issue also happen in develop, If I remember correctly

**Comment by dgealow** [comment]
Issue appears to probably be solved, at least for the use case of "I just want python 3". If no virtual environment is active, then it will use `python-shell-interpreter` to run the script--default `ipython`, overrideable with `(setq-default python-shell-interpreter "python2")` (or whatever python version you want) in `dotspacemacs/user-config`.

However, I can't verify that it works properly with virtual environments, because of [a bug introduced into ipython just 3 days ago](https://github.com/ipython/ipython/issues/13554). Will report back as soon as that gets fixed!

**Comment by dgealow** [comment]
Alright, downgraded my ipython to test this out. It seems that if you have ipython installed in your virtual environment, it will use that version of ipython. However, if you don't, then it will use the system default ipython rather than the virual environment's python.

**Comment by lebensterben** [comment]
We shouldn't support python 2.

So the issue should be considered fixed if it works as expected under python 3, with and without virtual environment.
