### ISSUE TITLE
Differences from vim: Ctrl-L

### ISSUE THREAD

**Issue by idbrii** [syl20bnr/spacemacs#826]
In vim, Ctrl-L causes the window to be redrawn. I think that would translate to:

    (define-key evil-normal-state-map (kbd "C-l") 'redraw-display)

In spacemacs, Ctrl-L is mapped to `recenter-top-bottom`.

Is there a reason for this?

I'm not sure where I'd put the above keybinding since I don't see "evil-normal" anywhere in spacemacs/keybindings.el.

**Comment by danielwuz** [comment]
I think `Ctrl + L` is one of the default binding in Emacs. Just curious, can you talk about the use case of `redraw-display`?

**Comment by syl20bnr** [comment]
I noticed (at least in iTerm2) some artefacts in the rendering sometimes, redrawing may be an easy way to clean the display when they happens.

**Comment by kini** [comment]
`C-l` is one of the default bindings in Emacs, yes. Personally I find it very useful, I hope it doesn't go away :<

**Comment by syl20bnr** [comment]
Does `C-l` do the same thing as `H`, `L` and `zz` combined ?

**Comment by kini** [comment]
No, `C-l` doesn't move point at all.

`C-l` cycles between scrolling the screen so that point is at the top, point is at the bottom, and point is in the center, but the location of point in the buffer doesn't change.

In contrast, `H` moves point to whatever line is currently displayed at the top of the window, `L` moves point to whatever line is currently displayed at the top of the window, and `M` moves point to whatever line is currently displayed in the center of the window.

You can say that `C-l` is like `zt`, `zz`, and `zb`, but it's only one keybinding which cycles between the effects of `zt`, `zz`, and `zb`. (BTW now that I know about `zt`, `zz`, and `zb`, I guess I can live without `C-l`...)

**Comment by TheBB** [comment]
I consider this an upstream (evil) issue. Since this hasn't seen activity for five months I'm closing for now. If it's reported upstream, feel free to notify us so we can track it.
