### ISSUE TITLE
Is it possible to turn of the fuzzy autocompletion in the file finder?

### ISSUE THREAD

**Issue by minad** [syl20bnr/spacemacs#8285]
Hi,

I would like to turn off the too intelligent autocompletion in the file finder (Helm?). Similar to bash and other shells, I would prefer something which just uses the prefix and doesn't use fuzzy comparison.
Is this possible?

And thx for the spacemacs distribution, it is really great!

Daniel

**Comment by liadbiz** [comment]
hi,
Do you want find file in a project recursively or just find file only in current directory? 
actually, when I want to find a file to edit and i known where it is, I like to type spc-f-f, which just like bash. 
when I want to find file in a project and I dont known  file name exactly, I will type spc-p-f,  which do fuzzy finding.

**Comment by minad** [comment]
actually I press ctrl x f

**Comment by liadbiz** [comment]
ctrl x f act same as spc-f-f. Do you think it too intelligent? = =

**Comment by minad** [comment]
At least it doesn't work for me. I describe the problem more in detail. I have to files alpha and beta in a directory and I am in this directory. I press the following sequences:

ctrl x f a tab --> completes to beta
ctrl x f a enter --> opens beta

**Comment by liadbiz** [comment]
aha. I test you case in my spacemacs and it work as same as you. I have nerver aware of this problem.

I think it depends on the algorithm of helm-find-file. i usually type `al`  to find  `alpha` , and more, when I find a file,  i intend to type some charactors  ordered of the file name then up and down to select the finnal right one.

**Comment by duianto** [comment]
#### Confirmed
#### Steps to reproduce
- Create two files called `alpha` and `beta` in a directory
- Press <kbd>C-x C-f</kbd> or <kbd>SPC f f</kbd> and navigate to that directory
- Type: `a`

#### Observed behavior
The file called `beta` gets highlighted.

#### Expected behavior
One would expect it to start looking for the file names first characters, and that the file called `alpha` would become highlighted.

#### Tested
I tried these values one by one:
```
   dotspacemacs-helm-use-fuzzy 'always
```
```
   dotspacemacs-helm-use-fuzzy 'source
```
```
   dotspacemacs-helm-use-fuzzy 'nil
```
and restarted Emacs between each test, but the same thing happened each time. So fuzzy matching might not be what's causing it.

However there doesn't seem to be any difference in what's found if one for instance searches for `em li` in HELM M-x <kbd>SPC SPC</kbd>, it always highlights `emacs-lisp-mode` with `em` and `li` shown with a blue color. But i might be misunderstanding how `dotspacemacs-helm-use-fuzzy` is supposed to work.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. a23761c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((markdown :variables markdown-live-preview-engine 'vmd)
 auto-completion emacs-lisp git helm html markdown org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by minad** [comment]
With ivy I don't have these issues. For now I switched.

**Comment by sooheon** [comment]
Yep. IIRC, ivy has a sort function to special case file names in this way (matches at start are worth more) because this was common. I'm guessing the issue is the "beta" is shorter than "alpha" and that fudges the results in helm's algorithm.

**Comment by minad** [comment]
Is there a possibility to get this fixed in spacemacs or is this an upstream issue of helm? I still prefer helm over ivy.

**Comment by minad** [comment]
@d12frosted What does forum mean?
