### ISSUE TITLE
(global-git-commit-mode 1) not working (Fundamental mode is used for COMMIT_EDITMSG)

### ISSUE THREAD

**Issue by bennofs** [syl20bnr/spacemacs#8294]
#### Description :octocat:
(global-git-commit-mode 1) in user-config does not work

#### Reproduction guide :beetle:
- Run `emacs .git/COMMIT_EDITMSG`

*Observed behaviour:* :eyes: :broken_heart:
- Emacs opens COMMIT_EDITMSG in Fundamental mode

*Expected behaviour:* :heart: :smile:
- Emacs opens COMMIT_EDITMSG in git-commit message mode

### Suspected reason
I believe that this is a race condition: `(global-git-commit-mode 1)` registers a hook
for `find-file`, but perhaps `find-file` is executed before `user-config` has fully executed?

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. 9c497d82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml auto-completion c-c   csv
      (colors :variables colors-colorize-identifiers 'variables)
      docker emacs-lisp git github
      (haskell :variables haskell-completion-backend 'intero)
      helm html javascript markdown nixos nlinum ocaml org php python rust ruby scala shell-scripts spell-checking syntax-checking
      (version-control :variables version-control-global-margin t version-control-diff-tool 'diff-hl)
      yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by JuanKaram** [comment]
Having the same problem with

System Info 💻

- OS: osx
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm

Also followed this: https://github.com/syl20bnr/spacemacs/issues/2522 but no luck so far.

**Comment by bennofs** [comment]
ping @StreakyCobra you seem to know how this is supposed to work?

**Comment by StreakyCobra** [comment]
Hi,

I'm not any longer involved in Spacemacs development, but if I recall correctly this is an "known" issue. This is because the file is specified from command line argument before emacs start . Probably, as already said, the file is loaded before the configurations have been loaded. The problem may come from emacs that load a file passed from command line without using `find-file` hooks, or it may be a problem from the spacemacs way of loading packages/configurations.

The only workaround that I can propose is to start an emacs daemon, and then use `emacsclient` as your editor, so when openining a file like `emacsclient .git/COMMIT_EDITMSG`, the daemon has already loaded all configurations and the file is loaded in the correct mode.

**Comment by StreakyCobra** [comment]
Update: The problem is on Spacemacs' side.

Adding the following code at the end of `~/.emacs.d/init.el` solves the problem:

```elisp
(require 'git-commit)
(global-git-commit-mode t)
```

So it means the problem is coming from the way spacemacs is loading packages/layers/configurations. If you don't want to use `emacsclient`, you can use this as a workaround. Note that you may have problem the first time you start emacs on a new computer because it will not find the `git-commit` package.

**Comment by bennofs** [comment]
Ok, thanks for the info! Sorry for bothering you, didn't know you were no longer involved with spacemacs development.

**Comment by StreakyCobra** [comment]
@bennofs No problem, it's not because I'm not any longer in Spacemacs devevelopment that I can't help :wink: But for sure you'll need someone else to fix it though :smile:
