### ISSUE TITLE
In Windows projectile find files does not work

### ISSUE THREAD

**Issue by maksut** [syl20bnr/spacemacs#8306]
#### Description :octocat:

Projectile find files does not work in Windows when external tools (eg: `find`) are available in the PATH.
It is broken with both `ivy` and `helm`. With `helm` somehow this used work until `helm-projectiles`'s newest release.

I think spacemacs tries to be smart about native tools in Windows. If they are available in PATH, it enables `projectile-indexing-method 'alien` but it also overwrites `projectile-generic-command` to `find . -type f` in [here](https://github.com/syl20bnr/spacemacs/blob/02465e57712f0cc2be9a8714c5f6dac9fadb9ae5/layers/%2Bdistributions/spacemacs-base/packages.el#L325).

Spacemacs should either use the `projectile`'s default `find` command which is: `find . -type f -print0`. Or even better it should not set the `projectile-generic-command` at all. The default is fine.

#### Workaround
`
  (setq projectile-generic-command "find . -type f -print0")
`

#### Reproduction guide :beetle:

- Start Emacs

- Open a projectile project without under source control, then projectile find files.

*Observed behaviour:* :eyes: :broken_heart:

Projectile find file does not work.

*Expected behaviour:* :heart: :smile:

It should :)

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

#### Backtrace :paw_prints:

```

```

**Comment by zhixing2017** [comment]
On my Windows 7, Emacs freezed when I used the command `helm-projectile-find-file`.
Sometimes it worked, but normally, it is not.

**Comment by zhixing2017** [comment]
Now I am using `pt`. So far, so good.

**Comment by zhixing2017** [comment]
I use the spacemacs. It has the command `(spacemacs/helm-project-do-pt)`. 

But now I am using `(spacemacs/helm-project-do-rg)`.  `SPC s r p`

All you need to do is putting the `rg.exe` in you PATH.

**Comment by MoHKale** [comment]
Yeah, same problem. `(setq projectile-generic-command "find . -type f -print0")` works for me. This was a really annoying issue, I thought it was because there were carriage returns in the find output that projectile didn't strip out, for me it seemed to register every found file as a single file. So if I had a directory with:
* a.txt
* b.txt
* c.txt

projectile would open up helm, let me choose a file, but helm just highlighted every file as a choice. If I pressed enter, projectile then opened a file names "a.txtb.txtc.txt" (maybe seperated with spaces).
