### ISSUE TITLE
Line numbers not showing correctly in org files

### ISSUE THREAD

**Issue by fladd** [syl20bnr/spacemacs#8312]
Due to the different font sizes used in the highlighting of org files (with standard theme), line numbers are not shown correctly for headings.

<img width="244" alt="image" src="https://cloud.githubusercontent.com/assets/2971539/22629270/2a5ef862-ebe3-11e6-91c1-81c2410f2f77.png">

**Comment by Compro-Prasad** [comment]
@fladd Did you upgrade to Emacs 26? Line numbers should be fixed there.

**Comment by Alexander-Miller** [comment]
I have no idea why I am on the subscriber list of this issue, but I can help out anyway: The problem with pre-Emacs26 line numbers (linum+nlinum) is that they inherit the properties of the first character on the same line, so you'll often see your line numbers underlined, or change color and size like here.

The solution is to adjust your theme to explicitly set those faces to be default sized. Or upgrade to Emacs26, since it's much faster anyway.
