### ISSUE TITLE
Many commands fail with Error in post-command-hook (global-linum-mode-check-buffers): (wrong-type-argument listp t)

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#8318]
Error again:
```
Error in post-command-hook (global-linum-mode-check-buffers): (wrong-type-argument listp t)
```

**Comment by jupl** [comment]
If you're using the `dotspacemacs-line-numbers` option, that's been changed in develop. For me I had it set to `'relative` but that was breaking despite the latest documentation. I set it to `'(:relative t)` and it was working again for me now.

**Comment by beojan** [comment]
I just had it set to `t`. Setting it to `nil` fixes this, but I'd rather have them on.

**Comment by syl20bnr** [comment]
Same issue this morning at work, I'm fixing it :-)

**Comment by jupl** [comment]
@beojan Try `'(:relative nil)`

**Comment by syl20bnr** [comment]
Should be fine now, `dotspacemacs-line-numbers` should be backward compatible again.

**Comment by kaikuchn** [comment]
I'm getting a similar error (just a different value for the option) since I updated yesterday (I'm not on develop). The error message is `Error in post-command-hook (global-linum-mode-check-buffers): (wrong-type-argument listp absolute)`

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql clojure elm nginx javascript html csv auto-completion better-defaults emacs-lisp osx yaml git elixir ruby markdown syntax-checking version-control)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by jeremyong** [comment]
Getting this right now on emacs 25.2.1
