### ISSUE TITLE
Suspicious error messages when loading help system

### ISSUE THREAD

**Issue by nalzok** [syl20bnr/spacemacs#8363]
#### Description :octocat:
Suspicious error messages when loading help system

#### Reproduction guide :beetle:
- Start Emacs
- Press `<SPC> h <SPC>` start help system

*Observed behaviour:* :eyes: :broken_heart:
The `*Messages*` buffer shows errors:

1. `org-mode fontification error in #<buffer DOCUMENTATION.org> at 381`
2. `Eager macro-expansion failure: (void-variable erc-spacemacs-layout-name)`
3. `Eager macro-expansion failure: (void-variable rcirc-spacemacs-layout-name)`

Despite the error messages, everything seems to work well. I can read the document and the help system didn't crash.

*Expected behaviour:* :heart: :smile:
No error messages :)

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.50.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp helm osx scheme
                 (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/bin/bash" shell-default-position 'bottom shell-default-height 50)
                 syntax-checking)
```
- System configuration features: JPEG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

#### Backtrace :paw_prints:
```
<<Skipped thousands lines of "loading ...done" messages>>

Loading /Users/sunqingyao/.emacs.d/layers/+checkers/spell-checking/packages.el (source)...done
Loading /Users/sunqingyao/.emacs.d/layers/+checkers/syntax-checking/packages.el (source)...done
Loading /Users/sunqingyao/.emacs.d/layers/+chat/erc/packages.el (source)...
Eager macro-expansion failure: (void-variable erc-spacemacs-layout-name)
Loading /Users/sunqingyao/.emacs.d/layers/+chat/erc/packages.el (source)...done
Loading /Users/sunqingyao/.emacs.d/layers/+chat/jabber/packages.el (source)...done
Loading /Users/sunqingyao/.emacs.d/layers/+chat/rcirc/packages.el (source)...
Eager macro-expansion failure: (void-variable rcirc-spacemacs-layout-name)
Loading /Users/sunqingyao/.emacs.d/layers/+chat/rcirc/packages.el (source)...done
Loading /Users/sunqingyao/.emacs.d/layers/+chat/slack/packages.el (source)...done
[yas] Prepared just-in-time loading of snippets successfully.
Text is read-only
Setting up indent for shell type bash
Indentation variables are now local.
Indentation setup for shell type bash
org-mode fontification error in #<buffer DOCUMENTATION.org> at 381
Created https link.
Created nil link.
```

**Comment by rayw000** [comment]
Hi @bmag 

Issue's still here, and I can reproduce it.

### Steps
1. Do not enable at least one of these layers in your `.spacemacs` file: `gnus`, `notmuch`, `mu4e`, `rcirc`, `slack`, `erc`.
2. Start Emacs, invoke `ivy-spacemacs-help` (or `helm-spacemacs-help-packages` if you use `helm` instead of `ivy`)
3. Open `*Messages*` buffer, you can see error messages such as `Eager macro-expansion failure: (void-variable <layer name>-spacemacs-layout-name)`. `<layer name>` is the name of disabled layer.
4. Then you can use help system as nothing happened, and these error messages will not appear again.

### Analysis
I did some work to figure out what happened, followings are clues I could provide.

Both `ivy-spacemacs-help` and `helm-spacemacs-help-packages` invoke `configuration-layer/make-all-packages` indirectly. `configuration-layer/make-all-packages` will load `packages.el` from all enabled/disabled layers.

These six layers (`gnus`, `notmuch`, `mu4e`, `rcirc`, `slack`, `erc`) are a little special, they all invoke macro `spacemacs|define-custom-layout` inside their `packages.el` with a custom variable `<layer-name>-spacemacs-layout-name` defined in their `config.el`.

If one of this kind of layers is enabled, its `packages.el` file will be loaded at Emacs startup, and macro-expansion will not run until its `config.el` is loaded. So everything works fine.

If it is not enabled, its `packages.el` and `config.el` will not be loaded. When we run `ivy-spacemacs-help`, `configuration-layer/make-all-packages` will load `packages.el` of every layer, macro-expansions will be done at this time, but we haven't defined variable `<layer-name>-spacemacs-layout-name` yet. That's why we get these error messages.

### Possible solutions
1. I'm not quite familiar with *Emacs eager macro-expasion*. Perhaps do some tricks to delay the macro-expansion or make `config.el` loaded at proper time is the ideal way to solve this issue. I'm still working on this.
2. Do we really need to customize layout name of layers we mentioned above? How do you think if we hard code a layout name like here https://github.com/syl20bnr/spacemacs/blob/780a96cfacb4236f825773406b5cc703ba486d9a/layers/%2Bspacemacs/spacemacs-layouts/packages.el#L215 and here https://github.com/syl20bnr/spacemacs/blob/780a96cfacb4236f825773406b5cc703ba486d9a/layers/%2Bemacs/org/packages.el#L811

**Comment by duianto** [comment]
Thanks for the fix.
