### ISSUE TITLE
[Shell] Cursor position chainged ater switching buffers

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#8401]
#### Reproduction guide :beetle:
- Start Emacs
- <kbd>SPC</kbd><kbd>'</kbd> 
- write 'ls /etc' <kbd>RET</kbd> (cursor is on the bottom)
- switch b&f: <kbd>SPC</kbd><kbd>TAB</kbd> <kbd>SPC</kbd><kbd>TAB</kbd> (or with <kbd>SPC</kbd><kbd>b</kbd><kbd>b</kbd>, but not with <kbd>SPC</kbd><kbd>b</kbd><kbd>n</kbd>)

*Observed behaviour:* :eyes: :broken_heart:
Cursor position (line) in the buffer has changed.

*Expected behaviour:* :heart: :smile:
Cursor position in the buffer has not changed.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 3072e727)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm auto-completion better-defaults emacs-lisp git markdown org shell
                (shell :variables shell-default-position 'full)
                syntax-checking version-control python github scala)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by bmag** [comment]
Hi @xged, there seems to be missing steps between "Start Emacs" and "switch to `ansi-term` ...". Can you add them please? Can you also describe the before/after situations? (where was the cursor before, where was it after). Is it only `ansi-term` buffer with this problem, or others buffers as well? I will try to look at it later today/tomorrow.

**Comment by xged** [comment]
@bmag updated slightly.

**Comment by bmag** [comment]
Thanks, I managed to reproduce it now. I had to disable `purpose-mode` to make the buffer-switching easier (to allow a non-terminal buffer to display in terminal window).
Note that I could repro with `shell-default-shell` set to `term` and `ansi-term`, but not when set to `shell` or `eshell`. I will investigate later today. Below are before/after pictures.

Before:
![before](https://cloud.githubusercontent.com/assets/4334375/23125157/1a4474ba-f779-11e6-95bd-2c6ef11fb38e.png)
After:
![after](https://cloud.githubusercontent.com/assets/4334375/23125162/1f8b64d8-f779-11e6-9cd3-d0217a8eb515.png)

**Comment by bmag** [comment]
Sorry for the delay in investigating. I found that the bug is reproducible in stock Emacs - just run `M-x ansi-term`, type an `ls` command, then switch to scratch buffer and back with `C-x b`, and the cursor is misplaced in the same way as above. Meaning this is a bug upstream in Emacs.

I didn't find a similar open bug report, so can you please reproduce the bug in stock Emacs (`emacs -Q`) and submit a bug upstream with `M-x report-emacs-bug`? (This [page](https://www.gnu.org/software/emacs/manual/html_node/emacs/Checklist.html#Checklist) explains how to send a bug report for Emacs. Basically they just want a simple explanation and a repro guide that starts with `emacs -Q`.)
