### ISSUE TITLE
Flickering buffer

### ISSUE THREAD

**Issue by threaz** [syl20bnr/spacemacs#8408]
####  Descriptrion:
For no reason, emacs buffer starts to flicker on random occasions. I haven't found a way to reproduce this bug. However, this strange behaviour can often be observed especially during scrolling and closing helm buffers. I have captured one of such incidents and I'm posting it below as a gif. Note that the flickering appears only in the end of record. 

There are times when such problems are much more serious because instead of little strip on the edge of the screen the half of the buffer is blinking! I observed this annoying behaviour even before reinstalling my system and updating the kernel. Although, I'm still running Manjaro distributrion. (I don't know whether this information is valuable or not) 

![ezgif com-crop](https://cloud.githubusercontent.com/assets/9368662/23109305/3d9848a8-f718-11e6-86a1-32c32fb02420.gif)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
 haskell extra-langs c-c++ better-defaults emacs-lisp git markdown ranger shell ibuffer html latex ess syntax-checking org ruby javascript python)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

### edit
The same problem occurs with fresh install of spacemacs-base.

**Comment by deuill** [comment]
Are you using the `Iosevka` font? I'm having the same issue with that font when set with a size where the font doesn't snap to the pixel grid. For a 4K screen, that seems to be `22`, on a 1080p screen, that's `18`, I believe.

No idea why this happens, the closest thing I've found on the internet is this [Stackoverflow thread](http://stackoverflow.com/questions/15078067/emacs-letter-flickering) which describes a similar issue. I solved it by moving to the font size needed in order to eliminate flickering, but that may be too large for some. I assume it's an Emacs thing in general and not related to Spacemacs specifically.

**Comment by threaz** [comment]
Yes, I'm using one of its versions, `Iosevka Term`. I thought it might be the case too and made a test on a clean spacemacs installation without even changing the default font. The problem persists so for me this is not the font issue. 

However, I recently made a switch to compiled from source emacs 24.5(I was using version 25.1 installed via pacman) and the problem is (at least for now) gone.
