### ISSUE TITLE
Detecting React Layer Specific JS files

### ISSUE THREAD

**Issue by CMCDragonkai** [syl20bnr/spacemacs#8425]
There's a recommendation of the react layer README for putting `/** @jsx React.DOM */` in order for the react layer to decide for react major mode. However:

```
The @jsx React.DOM pragma has been deprecated as of React 0.12
```

So the only other ways is to use `.jsx` or `.react.js` file extensions. Is there a better way to preserve them being `.js` files so imports work normally, and still have them detected as react layer, without using the deprecated syntax above?

**Comment by bzalasky** [comment]
What approach are you using for module bundling? In my case, I use webpack, so with babel-loader in place for .js and .jsx files, this is a non issue. Also, the .react.js file is still just a .js file, you just might need to double check the relevant regex if it's giving you trouble.

**Comment by CMCDragonkai** [comment]
I'm only using create-react-app.

**Comment by jupl** [comment]
There's some autodetection for JS files if the first dependency is React. For instance, if you're using ES2015+ for the source code if the first line is `import React from 'react'` react-mode is used even if the file is `.js`.

**Comment by nubunto** [comment]
In my case, I get no syntax-highlight on HTML when opening `.js` files, even with `import React from 'react'` as the first line.

**Comment by chelium** [comment]
Syntax highlighting also doesn't work for me when opening `.js` files with `import React 'react'` in the first line. Like @nubunto said, it works as expected `.jsx` is used as an extension. It also works when `/** @jsx React.DOM */` is the first line in the file. I tried modifying the `react/post-init-web-mode()` in `packages.el` and I was able to get HTML highlighting and indenting for a different comment line at the beginning of a `.js` file. However, I'm new to elisp and I couldn't get the `(add-to-list 'magic-mode-alist '("^import React" . react-mode))` to work for me. Perhaps, the issue is with my environment? I haven't replicated the error on another system. I'll try playing around with it a bit more and see if I can figure out the cause of the issue.

**Comment by chelium** [comment]
I looked into it more. It appears the issue isn't with the regex but with yasnippet? I keep getting this error:
`File mode specification error: (void-function yas-activate-extra-mode)`
After looking through the stacktrace, the function is undefined for some reason. After removing and reinstalling yasnippet by relaunching emacs, everything works fine within that instance. However, the issue still arises if I close and launch a new emacs instance.

**Comment by tudorpavel** [comment]
After updating to spacemacs `0.200.13` I'm also getting this error with React files:
```
File mode specification error: (void-function yas-activate-extra-mode)
```

It only happens when I open a React file as the first file of a particular project. If I open some other file first (such as `package.json`) and then a React file it works as expected. Quite peculiar.

Actually, when opening `package.json` first, I used to get this warning:

```
[yas] Prepared just-in-time loading of snippets with some errors.  Check *Messages*.
```

And in `*Messages*` it said:

```
Skipping check for new version (reason: dotfile)
[yas] Check your `yas-snippet-dirs': /home/user/.emacs.d/elpa/yasnippet-20180211.1442/snippets is not a directory
[yas] Prepared just-in-time loading of snippets with some errors.  Check *Messages*.
[yas] Check your `yas-snippet-dirs': /home/user/.emacs.d/elpa/yasnippet-20180211.1442/snippets is not a directory
[yas] Prepared just-in-time loading of snippets with some errors.  Check *Messages*.
```

However it is unrelated, I managed to avoid the warning by creating a `snippets` folder in that location.

**Comment by gcperrin** [comment]
@tudorpavel exact same issue here.

**Comment by tudorpavel** [comment]
@gcperrin I should've added a 4th edit. My eventual solution was to [rollback the package update](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#update-packages). I tried to investigate the cause but couldn't even isolate a specific package. I did a debug of the bug and the problem is an exception on [this line](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bframeworks/react/packages.el#L66), but I'm not sure how to go about fixing it.
