### ISSUE TITLE
Git branch in modeline can get out of sync

### ISSUE THREAD

**Issue by bb4242** [syl20bnr/spacemacs#8470]
#### Description :octocat:
The git branch displayed in the spacemacs modeline can become out of sync

#### Reproduction guide :beetle:
- Start Emacs
- Open a file in a git repository
- Note that the branch displayed in the spacemacs modeline correctly reflects the current branch
- Create and check out a new branch (`SPC g m b c`), or check out an already existing branch

*Observed behaviour:* :eyes: :broken_heart:
The spacemacs modeline will continue displaying the old branch name. Killing and reopening the buffer will cause the correct branch name to be displayed.

*Expected behaviour:* :heart: :smile:
The branch name in the modeline should update to reflect the current branch immediately.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-enable-smart-eshell t)
 spell-checking syntax-checking version-control colors semantic xkcd
 (python :variables python-enable-yapf-format-on-save nil)
 erlang elixir
 (go :variables go-use-gometalinter t)
 common-lisp clojure c-c   cscope csharp emacs-lisp haskell html ipython-notebook javascript rust ruby scala scheme shell-scripts yaml)
```

**Comment by nixmaniack** [comment]
This is a known issue and briefly mentioned [here](https://github.com/magit/magit/blob/master/Documentation/magit.org#the-mode-line-information-isnt-always-up-to-date) on magit repo. More details can be found [here](https://github.com/magit/magit/wiki/magit-update-uncommitted-buffer-hook#updating-vcs-mode-line-information). 

Since this isn't related to Spacemacs directly this issue can be closed here and preferably should be reported to Emacs upstream for improving built-in "Version Control" package.

**Comment by bb4242** [comment]
OK, thanks for the information. :)  I'll close this and try reporting to Emacs upstream instead.
