### ISSUE TITLE
Line Number :enabled-for-modes does not work

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#8482]
#### Description :octocat:
Line numbers are being enabled despite not being part of :enabled-for-modes

#### Reproduction guide :beetle:
- Have `dotspacemacs-line-numbers` set to the following in `.spacemacs`:
```elisp
'(:enabled-for-modes prog-mode :relative t)
```
- Start Emacs
- Open a non prog mode file (.org, .txt, .md)

*Observed behaviour:* :eyes: :broken_heart:
Line numbers are shown.

*Expected behaviour:* :heart: :smile:
Line numbers should be absent.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. b8c9100d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(clojure colors command-log editorconfig emacs-lisp helm html javascript markdown mouse osx react restclient shell shell-scripts syntax-checking typescript vimscript yaml
         (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete)
         (git :variables git-magit-status-fullscreen t)
         (go :variables gofmt-command "goimports")
         (mu4e :variables mu4e-enable-mode-line t mu4e-enable-notifications t)
         (org-plus :variables org-plus-html-pygments-style "xcode" org-plus-pdf-no-tex t org-plus-use-pygments t)
         (spell-checking :variables spell-checking-enable-by-default nil)
         (version-control :variables version-control-diff-tool
                          (cond
                           (myspacemacs--gui 'diff-hl)
                           (myspacemacs--macos 'git-gutter)
                           (t nil))
                          version-control-diff-side 'left))
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by bmag** [comment]
cc @deb0ch @syl20bnr lets get this fixed. Seems like a problem in `spacemacs/enable-line-numbers-p` (or `spacemacs//linum-enabled-for-current-major-mode`, `spacemacs//linum-disabled-for-current-major-mode`)

**Comment by deb0ch** [comment]
Yep this is normal, derived modes are not supported yet, it is something that still is to be implemented 😸 

I don't know exactly how to do that, I haven't investigated the question.

**Comment by deb0ch** [comment]
Ooops this is not normal, line numbers should not be shown, I will look into it 👷

Actually doing it that way line numbers will never be shown in any modes as derived modes are not supported yet. I haven't investigated how to do that yet.

**Comment by jupl** [comment]
I forgot to note that it was working before. I can't find out at which point it stopped working.

**Comment by bmag** [comment]
@jupl @deb0ch please review #8484. It does two things:
- adds support for derived modes (using `derived-mode-p` instead of `memq`). If a mode has parents in both enabled an disabled lists, then the more specific parent takes precedence.
- fix the reported bug where a non-empty `:enabled-for-modes` and an empty `:disabled-for-modes` didn't actually restrict anything (fixed by adding the `(null enabled-for-modes)` test towards the end)

I wasn't sure what's supposed to happen to unspecified modes when both `:enabled-for-modes` and `:disabled-for-modes` are non-empty. Finally decided that line numbers should be disabled in unspecified modes in this case, because it seemed to fit better with the variable's documentation: 
> The property ‘:enabled-for-modes’ takes priority over ‘:disabled-for-modes’ and
restricts line-number to the specified list of major-mode.
