### ISSUE TITLE
Commenting broken - Symbol's variable as variable is void: evilnc-comment-operator

### ISSUE THREAD

**Issue by sebhahn** [syl20bnr/spacemacs#8483]
#### Description :octocat:
Symbol's variable as variable is void: evilnc-comment-operator

#### Reproduction guide :beetle:
- Start Emacs
- Open text file
- Press SPC c l

*Observed behaviour:* :eyes: :broken_heart:
Error message

*Expected behaviour:* :heart: :smile:
Comment symbol should be added to beginning of line

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. b8c9100)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/" auto-completion-enable-help-tooltip nil)
 bibtex c-c   colors custom-org-config emacs-lisp elixir erc erlang ess games
 (git :variables git-gutter-use-fringe t)
 github gnus html ipython-notebook latex lua markdown
 (org :variables org-enable-reveal-js-support t)
 pandoc pdf-tools plantuml
 (python :variables python-enable-yapf-format-on-save nil python-auto-set-local-pyenv-version 'on-project-switch python-test-runner 'pytest)
 python-config ranger research-config ruby search-engine semantic
 (shell :variables shell-default-shell 'term shell-default-term-shell "/bin/zsh")
 speed-reading spell-checking syntax-checking tmux version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND GSETTINGS NOTIFY FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

**Comment by bmag** [comment]
Can't repro with latest develop and updated packages. Please provide backtrace.

**Comment by sebhahn** [comment]
Thanks for testing! I reinstalled spacemacs and it seems to work again!

**Comment by simonpp** [comment]
I have the same problem with the master branch. Unfortunately, reinstalling spacemacs did not
help in my case.

#### Description :octocat:
Bug appeared after updating evil-nerd-commenter to 20170309.49.

#### Reproduction guide :beetle:
- Start Emacs
- open a file and comment a line using SPC-; 

*Observed behaviour:* :eyes: :broken_heart:

Error message
```
require: Symbol’s value as variable is void: evilnc-comment-operator
```


#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. 7213e1a3)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(javascript php html csv python ipython-notebook markdown auto-completion elpy irony-mode semantic spacemacs-org spacemacs-evil spacemacs-editing spacemacs-editing-visual spacemacs-layouts syntax-checking vim-powerline helm cmake-ide better-defaults emacs-lisp git shell bibtex latex ess elfeed ranger markdown org ibuffer mu4e version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11


#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-variable evilnc-comment-operator)
  byte-code("\306\303	\n\"\307\310\n\311=\203 \312	\"\313\314\f@\fA@\310$)\202s\n\315=\203X	dU\203X	U\204>	\2067`Sf\316U\204XeU\204X\206I`Sf\316U\203X\314S	\"\202s\n\315=\203f\314	S\"\202s\312	\"\314\f@\fA@\")\317\320!\205\201\n\315=\205\201\321 &\210\306
\303	!\322\323?\310\324	\310\325$\203\260`\326	\"\210b\210\327\330!\210b)\202\273	b\210\327\330!\210\326	\"&\207" [evilnc-comment-operator end type beg newpos evilnc-copy-and-comment-operator evil-define-operator "Comments text from BEG to END with TYPE." nil block evilnc--extend-to-whole-comment evil-apply-on-block evilnc--comment-or-uncomment-region line 10 called-interactively-p any evil-first-non-blank "Inserts an out commented copy of the text from BEG to END." :move-point evil-yank-lines lines comment-region evil-paste-before 1 evilnc-original-above-comment-when-copy-and-comment p] 12)
  require(evil-nerd-commenter-operator)
  #[nil "\300\301!\207" [require evil-nerd-commenter-operator] 2]()
  eval-after-load(evil #[nil "\300\301!\207" [require evil-nerd-commenter-operator] 2])
  byte-code("\300\301\302\"\210\303\304!\207" [eval-after-load evil #[nil "\300\301!\207" [require evil-nerd-commenter-operator] 2] provide evil-nerd-commenter] 3)
  autoload-do-load((autoload "evil-nerd-commenter" nil t nil) evilnc-comment-operator)
  command-execute(evilnc-comment-operator)
```

**Comment by sebhahn** [comment]
I also noticed that I got the same issue on another machine

**Comment by korayal** [comment]
I had a similar issue, which was gone after removing the `elpa` directory and triggering a complete reinstall for packages.

**Comment by gdkrmr** [comment]
I had the same problem and resolved it by deleting the content of the `elpa` directory

**Comment by magnetophon** [comment]
I also was able to resolve this by deleting the ``elpa`` dir.
Would it be possible to find the root cause somehow?

**Comment by chrispickard** [comment]
seems like removing the entire elpa directory is not necessary, I was able to solve this by simply removing all .elc files in the evil-nerd-commenter-*/ directory

**Comment by ddxgz** [comment]
I had the same problem. 
Unfortunately I was unable to resolve the issue by simply removing all .elc files in the evil-nerd-commenter-*/ directory.
Resolved it by removing the content of the elpa directory.

**Comment by madand** [comment]
I encountered this problem today. Being in mood for an adventure, I investigated it and found the root cause.

## Minimal workaround ##

Delete `evil-nerd-commenter-operator.elc` and restart Emacs. 

```bash
rm ~/.emacs.d/elpa/evil-nerd-commenter-*/evil-nerd-commenter-operator.elc
```

This has to be done after each update of the `evil-nerd-commenter` package. Fortunately, its updates are rather rare.

## The problem ##

### evil-free ###

As it seems, at some point, developers of `evil-nerd-commenter` realized that most of the functionality can be used without `evil` (installed/loaded). So they moved `evil`-specific bits into the separate file [evil-nerd-commenter-operator.el](https://github.com/redguardtoo/evil-nerd-commenter/blob/498ac2dbbd4382403fd1ff94771bd29d8c5a228f/evil-nerd-commenter-operator.el). The main file ([evil-nerd-commenter.el](https://github.com/redguardtoo/evil-nerd-commenter/blob/498ac2dbbd4382403fd1ff94771bd29d8c5a228f/evil-nerd-commenter.el)) then includes that file using the following code:
```emacs-lisp
(eval-after-load 'evil
  '(require 'evil-nerd-commenter-operator))
```

Since during the package installations `package.el` byte-compiles all `*.el` files, `evil-nerd-commenter-operator.el` is being compiled too, regardless of whether `evil` is present or not. This caused many errors to be emitted during installations on systems without `evil`. So the developers resorted to some black magic (IMO) in that file:

```emacs-lisp
(require 'evil nil 'noerror)

...

;; Local Variables:
;; byte-compile-warnings: (not free-vars unresolved)
;; End:
```

As a result, on `evil`-free systems `evil-nerd-commenter-operator.elc` ends up containing some broken byte-code, but no warnings are ever shown. It is generally OK, because if `evil` is not present at run-time, `evil-nerd-commenter-operator` will never be `require`d anyways.

OTOH, for `evil-nerd-commenter-operator.el` to be complied properly, `evil` must be loaded at **compile time**, since it uses its macros (`evil-define-operator`, `evil-define-text-object`).

Also, the package does not declare `evil` as its dependency (obvious but important point).

### Spacemacs' side of the issue ###

From the previous section you know that `evil-nerd-commenter`:

  * Does not declare `evil` as its (explicit) dependency.
  * Needs `evil` to be loaded at compile-time, in order to successfully compile `evil-nerd-commenter-operator.el`.

Spacemacs installs packages on the very beginning of its startup process, when none of the third-party packages are loaded yet. So that packages are being installed in almost clear environment, with only packages' own explicit dependencies loaded. 

So we have a situation when `evil-nerd-commenter` is being compiled before `evil` is loaded, thus generating broken `evil-nerd-commenter-operator.elc`. The mystery solved.
  
When Spacemacs installs numerous packages, the ones being installed later can see packages (and their dependencies) loaded by the ones installed earlier. This explains why people can workaround the issue by deleting the `elpa` directory (tip: evil is being installed almost first).

## Possible solutions ##

### The Right Thing ###

Split the package into 2 (MELPA recipes [allow](https://github.com/melpa/melpa#user-content-example-multiple-packages-in-one-repository) for this). For example:

  * `emacs-nerd-commenter` - general functionality. No external dependencies.
  * `evil-nerd-commenter` - evil-specific bits. Depends on `emacs-nerd-commenter` and `evil`.
  
But this scenario will brake things (or rather will install evil) for existing users of `evil-nerd-commenter`, that happen not to use `evil`.

### Workaround in Spacemacs ###

Find a way to hook into package installation process and delete the offending file `evil-nerd-commenter.elc`.

**Comment by madand** [comment]
My PR was merged upstream. The issue is fixed.
