### ISSUE TITLE
Projectile rails keybinding not loading.

### ISSUE THREAD

**Issue by esiegel** [syl20bnr/spacemacs#853]
Initially, after loading a ruby file, which is within a rails project, the rails keybindings are not functioning.  Specifically, I'm trying to find a rails model, though all of the keybindings are missing.
```
<space> m r  f m
```

After sleuthing about, I discovered the problem is that projectile doesn't have a current project set.  I've tried adding this, but to no avail:

```emacs-lisp
  ; projectile considers current directory as root
  (setq projectile-require-project-root nil)
``` 

By running this code, which also exists in the projectile-rails package, the keybinding will then magically work.

```emacs-lisp
;; eval-expression
(projectile-project-root)
```

**Comment by horrorvacui** [comment]
I've something similar but instead it stems from the *projectile-rails-on* being a hook of *projectile-mode*. I don't get the rails keybindings till I launch projectile-mode in the project. So I do something with *projectile-mode* or `M-x project-mode`. Since I got a bit tired of doing that I changed it to a hook of enh-ruby-mode since I'm smart enough to know if my project is a rails one or not and that made more sense to me. Like so:

```emacs-lisp
(defun ruby/init-projectile-rails ()
  (use-package projectile-rails
    :defer t
    :init
    (progn
      ;;(add-hook 'projectile-mode-hook 'projectile-rails-on)
      (add-hook 'enh-ruby-mode-hook 'projectile-rails-on))
...
``` 
So far it works but I'm a new convert and my knowledge is too limited to be sure what the ramifications are so I'll defer to someone else as if that is a good decision.

**Comment by horrorvacui** [comment]
I forgot that I instead just added the extra hook and didn't comment it out. So instead I'm using:
```emacs-lisp
(defun ruby/init-projectile-rails ()
  (use-package projectile-rails
    :defer t
    :init
    (progn
      (add-hook 'projectile-mode-hook 'projectile-rails-on)
      (add-hook 'enh-ruby-mode-hook 'projectile-rails-on))
...
```

**Comment by esiegel** [comment]
@horrorvacui Your fix definitely does the trick, but I'd still like to know what is the preferred solution.  How can I get projectile to load by default when I'm within a directory managed by git?  I'd prefer not to use projectile's global mode.

**Comment by horrorvacui** [comment]
@esiegel Hum, perhaps you could start by adding a .git file to the *projectile-project-root-files* so that it picks up on the git file as the project root. Then you'd still need to somehow engage the projectile-mode on its own.
I'm not sure that is the best way to do it. But I agree It would be really nice for projectile to autodetect and launch when in git repos. There maybe more answers in projectile's docs and implementation so I'll check that out next.

**Comment by esiegel** [comment]
It's weird, it seems that spacemacs starts **projectile-global-mode** on [configuration](https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L2308), but this code isn't running.

**Comment by horrorvacui** [comment]
It states it right in the documentation that it should notice a git repo as a project so no need to add any files to *projectile-project-root-files* so ignore what I said about that. I'm not sure about the *projectile-global-mode* issue. I'm guessing this is more or less an issue for me because I enter projects in a way that isn't really best for projectile to even detect it's in project.

**Comment by syl20bnr** [comment]
@horrorvacui You were right, the hook was not valid, only one hook is necessary though.

I also fixed some other issues with `enh-ruby-mode` in `develop` branch. You should be fine now :-)

**Comment by esiegel** [comment]
@syl20bnr Could you comment on why *projectile-global-mode* isn't being enabled?  I linked to the configuration of projectile above.  I read the documentation for *use-package* and it seems that global-mode will be enabled after projectile-mode?  Seems that global-mode should just be enabled from the get-go.

**Comment by syl20bnr** [comment]
@esiegel the `:config` block is evaluated when the package is effectively loaded (required) which happens only after one of the commands listed in `:commands` are executed. So it is not guaranteed that projectile will be loaded when you open a ruby file.
Changing the hook on `enh-ruby-mode` assures that when `enh-ruby-mode` will be loaded and enabled the `projectile-rails` function will be executed which in turn will require correctly `projectile` (since it depends on it, see the source) which will trigger the `:config` block of `projectile` configuration, so `global-projectile-mode` will be triggered at the end.

**Comment by syl20bnr** [comment]
@esiegel to go the the source of a package use `SPC m g g` on a symbol. For instance `SPC m g g` on `projectile-rails-on` will send you to the source.
`;;;###autoload` is a cookie that will load (require) the file when the function is executed, this is how emacs lazy load the packages.

**Comment by esiegel** [comment]
Thanks @syl20bnr , that explains it.

**Comment by horrorvacui** [comment]
I just wanted to note that I found projectile-rails wouldn't get enabled without the other hook if I was in a non-ruby file.
For example, if I entered a rails project by opening a javascript file I might not get the **projectile-rails** keybindings with just the one hook. However, **projectile-rails** would notice that the project was rails even if I entered the project via a javascript file. All I'd have to do then is open projectile and it would enable the keybindings. Not ideal but it was acceptable in my opinion.
Wouldn't one alternative be some kind of guard that looks at all files and checks if they are somehow rails and enables immediately projectile-rails? Might be a bit much though.

**Comment by horrorvacui** [comment]
Actually I wasn't that clear. The reason for the original hook is if you are changing projects with projectile into a rails project without touching a ruby file yet. The hook activates **projectile-rails** for that scenario. However due to the way it all works there is still possible other scenarios where **projectile-rails** doesn't get activated. Maybe there should be a note in the ruby layer about that if no easy fix is available.

**Comment by syl20bnr** [comment]
@horrorvacui I see, in the case of `projectile-rails` maybe the key bindings should be global and not major-mode specific then but which command prefix key binding to choose then ?
This is something I have to think carefully to find a good conventions. We will have the same issue for all the framework related modes.
