### ISSUE TITLE
Tame exec-path-from-shell

### ISSUE THREAD

**Issue by Stebalien** [syl20bnr/spacemacs#8537]
The `exec-path-from-shell` package is a horrible hack that should only be used as a last resort.

Each time it imports an environment variable, it starts an interactive login shell which:

1. Can be really slow (logins are expected to be infrequent).
2. Can break systems that (reasonably) expect one login per session.
3. Breaks spectacularly when one does something like run screen in interactive shells. Note: This may be fixed when and if https://github.com/purcell/exec-path-from-shell/issues/17 is.

To mitigate these issues:

* [x] It should be possible to exclude the `exec-path-from-shell` package. Unfortunately, the go and rust layers expect `exec-path-from-shell` to always be available and crash on startup when it's excluded.
  - [x] `+lang/rust`
  - [x] `+lang/go`

* [ ] It shouldn't be enabled on anything but MacOS. Any not-totally-broken display manager on Linux, FreeBSD, etc. will properly setup the environment using the user's login shell.

* [x] Layers should avoid importing variables from the shell when already defined as this takes away control from the user (having one's environment silently overridden is mildly infuriating). Currently, the rust layer imports `RUST_SRC_PATH` even if already set.
  - [x] `+lang/rust`

* [x] Layers should avoid calling `exec-path-from-shell-copy-env` multiple times as it will run an interactive login shell each time (which is *slow*). The go layer currently calls it twice.
  - [x] `+lang/go`

**Comment by bmag** [comment]
@Stebalien I tend to agree with you, and several people indeed had trouble caused by exec-path-from-shell because it runs an interactive login shell and they had a heavy configuration (IIRC there are several such issues in the bug tracker). I'd like to hear from someone who does need exec-path-from-shell (mainly macOS users I guess), to understand if we can safely disable it in non-macOS machines. Also, Rust and Go layers will need an alternative method of reading the environment variable (at least on non-macOS).

**Comment by Stebalien** [comment]
> I'd like to hear from someone who does need exec-path-from-shell (mainly macOS users I guess), to understand if we can safely disable it in non-macOS machines.

Wouldn't you want to hear from more non-macos users (unless you're looking to remove it entirely). 

Display/Login Managers (I'm reasonably certain all of these work...):

* [x] `login` (the standard textual login manager always starts a login shell).
* [ ] GNOME 3/GDM
* [ ] KDE/KDM
* [ ] XFCE/XDM
* [ ] MATE
* [ ] LXWM/LXDM
* [ ] Unity/LightDM

> Also, Rust and Go layers will need an alternative method of reading the environment variable (at least on non-macOS).

They just use exec-path-from-shell to import environment variables from a login shell into emacs. When the emacs environment is setup correctly (with all the correct environment variables) this isn't necessary. That is, on systems that correctly setup the environment, we can drop exec-path-from-shell without replacement.

---

Assuming we only need it on macos, we could have the osx layer "own" the exec-path-from-shell package and have the rust/go layers use it iff it's available.

Additionally, instead of calling `exec-path-from-shell-copy-env`, they these layers should be adding the variables they want to import to `exec-path-from-shell-variables` in a `my-layer/pre-init-exec-path-from-shell` function so we only start one login shell (when the responsible layer calls `exec-path-from-shell-initialize`).

**Comment by GrappigPanda** [comment]
I want to add on to this that there's another issue (which may need to be opened), but a reliance on `exec-path-from-shell` can cause errors if loaded after other packages. I was able to manually set $PATH & $GOPATH, but the package `go-eldoc` wouldn't respect the changes in the environment variables until I moved `exec-path-from-shell` to the beginning of the `custom-set-variables` at the bottom of the `.spacemacs` file.

**Comment by Stebalien** [comment]
@GrappigPanda

Given that `exec-path-from-shell` is configured in the "pre" package configuration step, configuring `exec-path-from-shell-variables` in `my-layer/pre-init-exec-path-from-shell` should fix that.

**Comment by Stebalien** [comment]
I've filed a pull request (#8543) that fixes everything here *except*:

>  It shouldn't be enabled on anything but MacOS. Any not-totally-broken display manager on Linux, FreeBSD, etc. will properly setup the environment using the user's login shell.

As that needs some discussion/feedback.

**Comment by bmag** [comment]
Merged #8543. @Stebalien the only remaining thing to do is disable exec-path-from-shell on Linux machines, right?

**Comment by Stebalien** [comment]
Yes. And thanks!

**Comment by LdBeth** [comment]
`exec-path-from-shell` should also be disabled for [Mitsuharu's Mac Port](https://bitbucket.org/mituharu/emacs-mac/overview) because it can get the proper environment variables by default.

**Comment by jlee-made** [comment]
I configure my environment in `.bashrc` on my Ubuntu (16.04, 17.10) machines, which I have a vague feeling is 1. frowned upon 2. the reason I rely on `exec-path-from-shell` 3. somehow related to non-standard behaviour by Ubuntu (I recall trying to move it to my currently-empty `.bash_profile` on several occasions and finding "some things" broke -- sorry for lack of details right now).

What should I do if it is disabled on linux so that I can still configure my PATH, PYTHONPATH etc. in one place and have it "work" in both emacs and bash shells (I don't run those shells in emacs)?

Not saying you shouldn't do it, but just to evaluate the consequences for users like me uneducated about the this: If the answer is "put that configuration in .bash_profile instead of .bashrc", my *uneducated best guess* is that a majority of linux users will find they need to make multiple changes -- because many linux users are ubuntu users, and only some small fraction of linux users care much about the distinction between .bashrc and .bash_profile, and fewer still understand all the details (certainly I don't!).
