### ISSUE TITLE
Spaceline counts columns from 0

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#8550]
Vim counts columns from 1.

Since Spacemacs emulates Vim, perhaps edit Spaceline (the status line) to display the column as "current-column + 1". That way we get sane character counting in Spacemacs too.

This is how badly it "works" at the moment:

1st character of 1st line:

- Vim: 1:1
- Spacemacs: 1:0

80th character of 1st line:

- Vim: 1:80
- Spacemacs: 1:79

Very confusing. I noticed that it's because Emacs itself defines "current-column" as 0-indexed. But that's not user friendly. Why does Emacs even bother counting lines starting from 1 when it insanely counts characters starting from 0? They should have made both 0 or both 1. This mishmash is a mess.

Most annoyingly, it means that stuff like fill-column and git commit message editing gets confusing. "50" is actually the 51st column, etc. No other sane editor counts columns the bad way Emacs does it...

**Comment by SteveJobzniak** [comment]
In fact, even Emacs itself is being schizophrenic about this problem, because things like its built-in "fill-column" property are defined as 1-indexed values, so "fill-column 80" means "wrap all text at the real 80th column", aka "current-column 79". Heh.

Example of fill-column 80 (so column 81 and up are marked in red):

![fill80](https://cloud.githubusercontent.com/assets/22373193/24171784/16b9dac8-0e86-11e7-8d27-2c9bcc1dfd11.png)

My cursor is placed on the (non-red) 80th column... and Spacemacs shows... 1:79 as the line location.

So really, Emacs made some neurotic, bad choice for column-counting back in its early days, and it makes no sense at all: 1. Compared to Vim and any other sane editor. 2. Compared to ITS OWN built-in functions.

Luckily this should be a simple fix. Just use "current-column + 1" in Spaceline instead.

**Comment by CeleritasCelery** [comment]
You should open an issue at [TheBB/spaceline](https://github.com/TheBB/spaceline)

**Comment by deb0ch** [comment]
This can be closed now that https://github.com/TheBB/spaceline/pull/194 got merged 👌:sparkles:
