### ISSUE TITLE
error: Invalid byte opcode: op=183, ptr=109

### ISSUE THREAD

**Issue by nalzok** [syl20bnr/spacemacs#8683]
#### Description :octocat:

Error opening files with double click

#### Reproduction guide :beetle:

- Set the "Open With" application of a specific file type, say, `*.md`, to Emacs
- *WITHOUT* starting Emacs first, double click on a file of that type to open it.

*Observed behaviour:* :eyes: :broken_heart:

An error occurs when Emacs starts up, saying `error: Invalid byte opcode: op=183, ptr=109`

![screen shot 2017-04-11 at 23 17 12](https://cloud.githubusercontent.com/assets/13443062/24916906/1ccb86bc-1f0e-11e7-8334-cbfb0bea975a.png)

*Expected behaviour:* :heart: :smile:

Files open correctly with Emacs when clicked on.

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp helm osx scheme
                 (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/bin/bash" shell-default-position 'bottom shell-default-height 50)
                 syntax-checking)
```
- System configuration features: JPEG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

#### Backtrace :paw_prints:
```
Warning (initialization): An error occurred while loading ‘/Users/sunqingyao/.emacs.d/init.el’:

error: Invalid byte opcode: op=183, ptr=109

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

```

------

In case it's relevant, here is my `/Users/sunqingyao/.emacs.d/init.el` (It should remain unmodified):

```
;;; init.el --- Spacemacs Initialization File
;;
;; Copyright (c) 2012-2017 Sylvain Benner & Contributors
;;
;; Author: Sylvain Benner <sylvain.benner@gmail.com>
;; URL: https://github.com/syl20bnr/spacemacs
;;
;; This file is not part of GNU Emacs.
;;
;;; License: GPLv3

;; Without this comment emacs25 adds (package-initialize) here
;; (package-initialize)

;; Increase gc-cons-threshold, depending on your system you may set it back to a
;; lower value in your dotfile (function `dotspacemacs/user-config')
(setq gc-cons-threshold 100000000)

(defconst spacemacs-version          "0.200.9" "Spacemacs version.")
(defconst spacemacs-emacs-min-version   "24.4" "Minimal version of Emacs.")

(if (not (version<= spacemacs-emacs-min-version emacs-version))
    (error (concat "Your version of Emacs (%s) is too old. "
                   "Spacemacs requires Emacs version %s or above.")
           emacs-version spacemacs-emacs-min-version)
  (load-file (concat (file-name-directory load-file-name)
                     "core/core-load-paths.el"))
  (require 'core-spacemacs)
  (spacemacs/init)
  (configuration-layer/sync)
  (spacemacs-buffer/display-startup-note)
  (spacemacs/setup-startup-hook)
  (require 'server)
  (unless (server-running-p) (server-start)))
```

**Comment by duianto** [comment]
I've been trying Emacs 26.0.50, and when I switch back to Emacs 25.2.2, then a warning buffer opens, showing this message:
> Error (use-package): helm :config: Invalid byte opcode: op=183, ptr=77

Trying to open a helm buffer, i.e: helm mini `SPC b b` shows this:
> helm-source-mm-get-search-or-match-fns: Invalid byte opcode: op=183, ptr=77
in the messages buffer.

It might have to do with updating packages in Emacs 26.0.50, causing them to be compiled for 26.0.50, which makes them incompatible for earlier versions. 

This seems relevant:
http://lists.gnu.org/archive/html/emacs-devel/2017-02/msg00711.html

>You need to arrange not to run byte-compiled libs in an earlier
version of Emacs than where they were compiled. This isn't a new
requirement. There has never been a guarantee that newer versions'
bytecode will run on older versions, ...


I seem to remember the last time it happened, that it started working again, after removing the elpa directory and starting Emacs 25.2.2, to let it install/compile the packages again.

#### This time I tried to just remove the `.elc` files.
Since the helm buffers didn't work, I started with elpa/helm-(timestamp), but there was no change.

Also removing the `.elc` files from elpa/helm-core-(timestamp), doesn't show the invalid message on startup, and opening helm buffers works. But when opening `.spacemacs` (`SPC f e d`), then the warning buffer opens, showing this message twice:
> Error (editorconfig): Invalid byte opcode: op=183, ptr=60.  Styles will not be applied.

once when `SPC f e d` is pressed, and it seems like the second time happens when `.spacemacs` has loaded.

The error message mentions `(editorconfig)`, and removing the `.elc` files from the elpa/editorconfig-(timestamp) directory, also stops that error message from appearing when `.spacemacs` is opened.

There might be more issues later on. Other updated packages, might also have been compiled for Emacs 26.0.50.

The best solution is probably to reinstall/recompile the packages, when downgrading Emacs versions.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. f0bc4473)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion colors emacs-lisp git helm html markdown org python version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by x-ji** [comment]
Can confirm that this is likely caused by downgrading Emacs. I did so since I wanted to have font ligature working with `emacs-mac` instead of `emacs-plus`. I had to delete the `elpa` folder and install the packages again.

**Comment by duianto** [comment]
The develop branch has fixed this by setting the `dotspacemacs-elpa-subdirectory` variable to 
`'emacs-version`, in the `.spacemacs.template` (which is used to initialize `.spacemacs` when one clones a fresh copy of Spacemacs or if one `SPC f e D` ediffs' the dotfile with the template, and one chooses to use the settings from the template). This means that the packages are downloaded and compiled in separate directories, for each Emacs version that one starts, i.e.:
`.emacs.d/elpa/25.3/develop`
`.emacs.d/elpa/26.0/develop`

If one switches to the master branch, with the same `.spacemacs` config (that has the 
`dotspacemacs-elpa-subdirectory` variable set to `'emacs-version`), then the packages are downloaded into `.emacs.d/elpa/<emacs version>/`, without a branch subdirectory.
