### ISSUE TITLE
nlinum dead link in documentation

### ISSUE THREAD

**Issue by timofeytt** [syl20bnr/spacemacs#8724]
The link to nlinum is here:
http://spacemacs.org/layers/LAYERS.html
dead link:
http://spacemacs.org/layers/+misc/nlinum/README.html

This might have been deprecated with the introduction of `dotspacemacs-line-numbers`.

**Comment by duianto** [comment]
There's no `+misc` directory in either the non-develop or develop.spacemacs.org repos: https://github.com/syl20bnr/develop.spacemacs.org/tree/gh-pages/layers

I mentioned the nlinum link in this spacemacs.org issue: Fix link to helm layer [#16](https://github.com/syl20bnr/spacemacs.org/issues/16)

But I see now that the spacemacs.org repos readme says:
>This is a read-only repository, development happens on syl20bnr/develop.spacemacs.org.

and the develop.spacemacs.org repos readme says:
>This repository is the development branch of syl20bnr/spacemacs.org, the documentation files are exported from the develop branch of syl20bnr/spacemacs.

Therefore this main spacemacs repo is the correct place to report webpage issues.

- - -
The spacemacs.org repos readme should probably be updated to state that the documentation files are exported from this main spacemacs repo (from the master branch?).

That would save a step for anyone wanting to report an issue with the spacemacs.org webpage. They wouldn't have to, first navigate to the spacemacs.org repo, then to the develop.spacemacs.org repo, and finally reporting the issue here in the spacemacs repo.
