### ISSUE TITLE
Pasting error "ad-Advice-yank: Symbol’s function definition is void: evil-start-undo-step"

### ISSUE THREAD

**Issue by y15e** [syl20bnr/spacemacs#8852]
#### Description :octocat:
Can't paste text with `C-y`.

#### Reproduction guide :beetle:
- Start Emacs
- Open any text file
- Cut any text with `C-k`
- Paste the text with `C-y`

*Observed behaviour:* :eyes: :broken_heart:
"Symbol’s function definition is void: evil-start-undo-step" error is shown.
![paste-error](https://cloud.githubusercontent.com/assets/27120451/25731781/7d9f8ce4-3184-11e7-83fa-067a6854f5d7.jpg)

*Expected behaviour:* :heart: :smile:
The text is pasted.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-function evil-start-undo-step)
  evil-start-undo-step()
  ad-Advice-yank(#[256 "\302 #\303#\304`!\210\305\306#<\203##\307\202 ##\310=\203##\311\202 ##S!!\210\211:\2033#\312\303!\313 `p\223\210b\210	\303=\203;#\314#\315\207" [yank-window-start this-command window-start t push-mark insert-for-yank current-kill 0 - -2 mark mark-marker yank nil] 5 2385991 "*P"] nil)
  apply(ad-Advice-yank #[256 "\302 #\303#\304`!\210\305\306#<\203##\307\202 ##\310=\203##\311\202 ##S!!\210\211:\2033#\312\303!\313 `p\223\210b\210	\303=\203;#\314#\315\207" [yank-window-start this-command window-start t push-mark insert-for-yank current-kill 0 - -2 mark mark-marker yank nil] 5 2385991 "*P"] nil)
  yank(nil)
  funcall-interactively(yank nil)
  call-interactively(yank nil nil)
  command-execute(yank)
```

**Comment by mallochio** [comment]
Same issue here. Any ideas?

**Comment by d12frosted** [comment]
@mallochio could you please share the output of `SPC h d s`? Also try to use latest master or develop **and** update all your packages along with it. 

P. S. Can't reproduce. Using emacs editing style. Can't reproduce on master and develop.

**Comment by alapachianbulbus** [comment]
did this ever get fixed ? I'm using the latest master version of spacemacs (taken today) and emacs 25-3.  without copy and paste I;m stuck

**Comment by mquinson** [comment]
I had the same issue, but it was due to the fact that the initialization could not proceed to the end because I had some packages installed system-wide. I removed these packages from my distribution, restarted emacs, and it all worked OK.

**Comment by Compro-Prasad** [comment]
@y15e Could you check if it works for you?

**Comment by mquinson** [comment]
I don't have the feeling that this is fixed in any way. If the problem is due to some packages installed by another mean, then maybe the error message should be improved if possible.

**Comment by classner** [comment]
The problem is indeed outdated packages installed by the system package manager. Of course, it'd be best to remove those. However, there are scenarios when this is not possible (for example on a shared system).

In this case, I found a solution digging around in the load-path doc (https://www.emacswiki.org/emacs/LoadPath) and the Emacs description for the load-path variable. This variable can be modified by setting the environment variable `EMACSLOADPATH`. By default, this contains two locations: 1) the Emacs version specific installation directory (for example `/usr/share/emacs/26.3/lisp` and `/usr/share/emacs/26.3/site-lisp`) and 2) the installation path for system packages (for example `/usr/share/emacs/site-lisp` and `/usr/share/emacs/site-lisp/elpa`).

Setting the environment variable and just setting it to contain the paths from 1)  (for example `export EMACSLOADPATH=/usr/share/emacs/26.3/lisp:/usr/share/emacs/26.3/site-lisp`) fixes the problem for me.
