### ISSUE TITLE
Project filetree changes root in ~second after opening a file

### ISSUE THREAD

**Issue by keymone** [syl20bnr/spacemacs#8880]
#### Description :octocat:
Opening any file from project filetree (neotree) makes filetree
focus on directory this file is in after roughly a second.

#### Reproduction guide :beetle:
- Start Emacs
- ???
- `SPC p t`
- Navigate to some sub-folder
- Pick a file
- `Enter`
- Wait a second

*Observed behaviour:* :eyes: :broken_heart:
Project filetree root becomes the sub-folder you've navigated to.

*Expected behaviour:* :heart: :smile:
Project filetree root must remain unchanged.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults git syntax-checking version-control yaml python)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB

**Comment by keymone** [comment]
this also happens when i open files via `SPC p f`. also when i open via `SPC p f` while filetree buffer is active, selected file is opened in new vertical split.

**Comment by bitwalker** [comment]
I'm seeing this too, super annoying - I'm sure there is a way to change it, but I'm a bit surprised this is the default behavior

**Comment by bitwalker** [comment]
I added `(setq neo-autorefresh nil)` to my user config, looks like that fixes it.

**Comment by keymone** [comment]
@bitwalker thanks, just noticed that there's a similar commit in neotree codebase from 13 hours ago https://github.com/jaypei/emacs-neotree/commit/f95bbfba0a4008b0421938d6b6965b538d18e382

**Comment by sdwolf** [comment]
Neotree added the functionality to automatically refresh the neotree buffer when idle for 2 seconds. This way you don't need to manually switch to the neotree buffer to press `gr` in order to display new directories and files created externally. For some reason this also created this bug that the neotree root was being changed to the directory of the file in the current buffer. People complained and now the feature is disabled by default. I guess it will be enabled back when they figure out how to do a refresh without changing root.
