### ISSUE TITLE
(org) with-eval-after-load and additional packages

### ISSUE THREAD

**Issue by mlinchitstest** [syl20bnr/spacemacs#8884]
reposting better phrased version from stackoverflow:
https://stackoverflow.com/questions/43917974/org-mode-in-spacemacs-with-eval-after-load-and-additional-packages

## Background ##
[Spacemacs documentation recommends][1] that you wrap additional org-mode configurations in `(with eval after load 'org [...config...])`:

    (defun dotspacemacs/user-config ()
      (with-eval-after-load 'org
       ;; here goes your Org config
       )
    )

This is because:

> Since version 0.104, spacemacs uses the org version from the org ELPA
> repository instead of the one shipped with emacs. [...] Because of autoloading, calling to org functions will trigger the loading up of the org shipped with emacs which will induce conflicts.  

But lets say you then want to use `some-package` that configures *org-mode* in various ways. The org-related function inside the `some-package.el` file are **not** wrapped in `with-eval-after-load`. This is true for most org-related packages, which assume you're using the org version shipped with Emacs.

**How then do you load `some-package` so that it does not conflict with spacemacs's org implementation?** My first though was to do this **[A]**:

    (defun dotspacemacs/user-config ()
      (with-eval-after-load 'org
       (require 'some-package)
       ;;configure 'some-package and 'org-mode
       )
    )

Is this the correct approach? Also, if you follow this route for Melpa packages, Spacemacs will delete and reinstall the package every-time you evaluate your `dotfile`. To avoid this, the Melpa package has to first be added to **[B]**
    
    (defun dotspacemacs/layers ()
      (setq-default
        dotspacemacs-additional-packages '(some-package)
       )
     )

# Question

In general, will this code (**[A][B]**) ensure that my `some-package` (which provides customizations for org) does not mess with spacemacs' org implementation? Or do I actually have to edit the `some-package.el` file directly and wrap its org-related functions in `with-eval-after-load` (hope not)? Or some other way?

# Note
For reference, That somepackage is [here](https://github.com/jkitchin/scimax/blob/master/scimax-org.el) (it's not a Melpa package so **[B]** does not apply in this partuclar case), but my question is more of a general one.

  [1]: http://spacemacs.org/layers/+emacs/org/README.html#important-note

**Comment by smile13241324** [comment]
@mlinchitstest well the correct way to add new packages that configure org would be to add them to the org layer. If you don't want to do this you would definitely need to add them to the `dotspacemacs-additional-packages` to ensure that all layers involved know about your manually added packages otherwise they may try to install them too.

To ensure that your config code is really loaded after org mode is loaded you can use the following construct which you should call in your normal user-config `(use-package yourPackage :after org)`. This ensures that yourPackage is loaded only after a previously loaded package is loaded. In general you should avoid using `require` and rather use more high level constructs like use-package instead.
