### ISSUE TITLE
Best practices for package init + multiple layers

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#8896]
I'm looking for more information on this subject, particularly `LAYERS.org` but found none. I have a PR request (#8621) that relies on a package that can be used in multiple layers and any combination of those layers can be used, including some or all can be excluded. What's a good practice for a situation such as this?
- Create another layer with the package and have other layers be dependent on that original layer?
- Use something along the lines of `unless` + `configuration-layer/layer-usedp`? PR currently uses this but unsure if this is the proper way.
- Third thing?

**Comment by vanjadevs** [comment]
Did you figure this out?

**Comment by vanjadevs** [comment]
More precisely, how to overcome a situation where multiple layers use the same package + they could all possible have init for that package?

**Comment by fiveNinePlusR** [comment]
the layer docs explicitly say that only one layer should own the package. I am not aware of any great way to handle this when there are two optional layers like say go-layer and c++-layer both using package xyz but both can be used independently. possibly having them both be dependent on a layer that does nothing but offer up and own the common package and then use the usedp predicate in the child layers because anyone can exclude any package anyways.
