### ISSUE TITLE
Spacemacs overrides fci-rule-color set by theme

### ISSUE THREAD

**Issue by thegeorgeous** [syl20bnr/spacemacs#8917]
#### Description :octocat:
Spacemacs overrides fci-rule-color set by theme

#### Reproduction guide :beetle:
- Start Emacs
- Enable railscasts-reloaded theme
- Enable fci-mode

*Observed behaviour:* :eyes: :broken_heart:
Color is set to `#D0BF8F`

*Expected behaviour:* :heart: :smile:
Color should be set to `#383838`

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((ruby :variables ruby-enable-enh-ruby-mode t ruby-test-runner 'rspec)
 ruby-on-rails helm auto-completion emacs-lisp git markdown org syntax-checking)
```
- System configuration features: JPEG NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

#### Backtrace :paw_prints:
```
```

**Comment by CeleritasCelery** [comment]
What happens if you enable them in the opposite order?

**Comment by thegeorgeous** [comment]
@CeleritasCelery, the enabling was done via `.spacemacs` so I guess within the file itself, the enabling is done in reverse

**Comment by CeleritasCelery** [comment]
Then you should report this issue upstream at [alpaker/Fill-Column-Indicator](https://github.com/alpaker/Fill-Column-Indicator) as it doesn't look like this is Spacemacs issue. I wonder if they are setting `fci-rule-color` by deriving from a font lock.

**Comment by thegeorgeous** [comment]
@CeleritasCelery, Spacemacs sets the fci-rule-color to `#D0BF8F`. So I don't understand how that is not a spacemacs issue
https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/layers/%2Bspacemacs/spacemacs-ui-visual/packages.el#L47

**Comment by CeleritasCelery** [comment]
You're right. Well you should be able to override it by adding `(setq fci-rule-color "#383838")` to your `dospacemacs/user-config`.

**Comment by thegeorgeous** [comment]
@CeleritasCelery, that should not be necessary. Spacemacs should not dictate colour schemes, it should defer to the theme set by the user, failing which it should fallback to a default colour. Instead it overrides the colour scheme set by the user for some reason.

**Comment by CeleritasCelery** [comment]
Didn't realize that you owned the theme in question [thegeorgeous/railscasts-reloaded-theme](https://github.com/thegeorgeous/railscasts-reloaded-theme) and that it was trying to set `fci-rule-color` itself. That would have been useful to know. Spacemacs isn't overriding colors set by the user, it's overriding colors set by the theme. There is a large difference. 

I can see your point about having Spacemacs overwriting your themes preference for `fci-rule-color`. However I would imagine that most themes do not set `fci-rule-color` and in those cases, the Spacemacs default is preferable. What is the fci-mode "default" color for `fci-rule-color` without Spacemacs or railscats-reloaded-theme?

The best way to add a your theme to Spacemacs would be to create a [layer](https://github.com/syl20bnr/spacemacs/blob/master/doc/LAYERS.org), especially since your theme has a third party dependency. As part of your layer you would define `railscats-reloaded-theme/post-init-fill-column-indicator` which would let you override anything Spacemacs set. That is the Spacemacs way.

**Comment by sdwolfz** [comment]
We should be adding the `fci-rule-color` to the themes that don't have it instead of overwriting it for every theme. I've merged the fix from f234df5f948d4c1a2915b7d7d1c7ef5777ad02a5.

**Comment by thegeorgeous** [comment]
@sdwolfz, looks like this can be closed, since this is in the latest version

**Comment by Compro-Prasad** [comment]
@thegeorgeous You mean in master?

**Comment by thegeorgeous** [comment]
@Compro-Prasad, no, I mean in [0.200.13](https://github.com/syl20bnr/spacemacs/releases/tag/v0.200.13])
