### ISSUE TITLE
dotspacemacs-line-numbers, :enabled-for-modes, and derived modes

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#8919]
#### Description :octocat:
When using `dotspacemacs-line-numbers` with `:enabled-for-modes` including `prog-mode`, some derived modes do not work. `json-mode` does not work as it is derived from `javascript-mode`, which itself is derived from `prog-mode`. `typescript-mode` does not work as it is derived from `typescript-parent-mode`, which is an alias for `prog-mode`.

#### Reproduction guide :beetle:
- Enable the JavaScript and TypeScript layers and have the following in the configuration:
```elisp
dotspacemacs-line-numbers '(:enabled-for-modes
                            prog-mode
                            :relative t)
```
- Start Emacs
- Open a `.js` or `.ts` file

*Observed behaviour:* :eyes: :broken_heart:
Line numbers is not enabled automatically

*Expected behaviour:* :heart: :smile:
Line numbers should be enabled automatically

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: add-node-modules-path (rev. 0050beb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete)
 (centered-cursor :variables centered-cursor-major-mode-blacklist
                  '(spacemacs-buffer-mode eshell-mode shell-mode term-mode))
 clojure colors command-log doom editorconfig emacs-lisp git-plus
 (go :variables gofmt-command "goimports")
 helm html graphviz javascript-plus markdown-plus mouse olivetti
 (org-plus :variables org-plus-html-pygments-style "xcode" org-plus-pdf-no-tex t org-plus-use-pygments t)
 osx restclient shell shell-scripts
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking
 (theming :variables theming-modifications
          '((doom-one
             (linum-relative-current-face :bold nil :background "#21242b")
             (sp-show-pair-match-face :bold t :foreground "#86dc2f"))
            (spacemacs-dark
             (linum-relative-current-face :bold nil :underline nil))
            (spacemacs-light
             (linum-relative-current-face :bold nil :underline nil))))
 vim-empty-lines vimscript yaml)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by CeleritasCelery** [comment]
This looks like something they will have to make a PR to fix but you should be able to achieve the result you want by changing it to
```elisp
dotspacemacs-line-numbers 'relative
```
and then adding the line 
```elisp
(remove-hook 'text-mode-hook 'nlinum-mode)
```
 to your `dotspacemacs/user-config`

**Comment by jupl** [comment]
@CeleritasCelery Thanks. Unfortunately that's not an option for me because that will disable other modes that require line numbers but are (sometimes bafflingly) derived from `text-mode` such as `yaml-mode`. For now I need to use `:enabled-for-modes` and add all modes that I require but it's a bit of an annoyance.

**Comment by CeleritasCelery** [comment]
`dotspacemacs-line-numbers` is added to the `prog-mode-hook` by default. If you want to have line numbers in modes deriving from `text-mode` and `prog-mode` you just need `dotspacemacs-line-numbers 'relative`

**Comment by jupl** [comment]
I don't want it for all `text-mode` though.

**Comment by CeleritasCelery** [comment]
Then add the `text-mode` Derivatives you don't want to `:disable-for-modes`

**Comment by jupl** [comment]
I'm already doing that. That doesn't address the issue that I'm bringing up, however.

**Comment by CeleritasCelery** [comment]
Then maybe I don't understand your issue. `dotspacemacs-line-numbers` are already enabled for `prog-mode`, `text-mode`, and their derivatives by default. There is no need to add it.

**Comment by jupl** [comment]
I only want line numbers for all `prog-mode` derivatives and certain `text-mode` derivatives but not `text-mode` itself. I should just be able to add `prog-mode` to cover all `prog-mode` derivatives. However, I currently need to specify certain `prog-mode` derivatives directly because of the quirks as described in the description at the top, which I shouldn't need to do.

**Comment by CeleritasCelery** [comment]
[This](https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/layers/%2Bdistributions/spacemacs-base/funcs.el#L1075-L1081) table shows the relationship between enables and disables
```elisp
;; mode in :enabled, not in :disabled ==> t
;; mode not in :enabled, in :disabled ==> nil
;; mode in :enabled, parent in :disabled ==> t
;; parent in :enabled, mode in :disabled ==> nil
;; not in :enabled, not in :disabled, :enabled is empty ==> t
;; not in :enabled, not in :disabled, :enabled is not empty ==> nil
;; both :enabled and :disabled are empty ==> t
```
By unnecessarily adding `prog-mode` to `:enable-for-modes` as you did in your issue reproduction guide, you changed the inheritance behavior from `both :enabled and :disabled are empty ==> t` to `not in :enabled, not in :disabled, :enabled is not empty ==> nil`, which of course is going to lead to grandchildren modes being disabled because now the default setting is `nil` rather then `t`.

> I only want line numbers for all prog-mode derivatives and certain text-mode derivatives but not text-mode itself.

Then add `text-mode` to `:disable-for-modes` and your derivatives to `:enable-for-modes`. That way they will fall into `mode in :enabled, parent in :disabled ==> t` and you get the result you want.

**Comment by jupl** [comment]
So you mean:
```elisp
:enabled-for-modes
yaml-mode
:disabled-for-modes
text-mode
```

**Comment by CeleritasCelery** [comment]
Yes that is what I meant. But looking over it again, by doing that, does it disables all `prog-mode` derived buffers because they are now in `not in :enabled, not in :disabled, :enabled is not empty ==> nil`?

**Comment by jupl** [comment]
What you proposed doesn't work because now I don't have line numbers for any `prog-mode` derivatives. I must specify `prog-mode` for it to work since I'm customizing enabled/disabled modes.

**Comment by CeleritasCelery** [comment]
ahhhh. I finally understand what you are saying. Yeah that seems like an issue. They need to check the parentage recursively or change the property table.

**Comment by bmag** [comment]
> I only want line numbers for all `prog-mode` derivatives and certain `text-mode` derivatives but not `text-mode` itself. I should just be able to add `prog-mode` to cover all `prog-mode` derivatives.

Yes, that's how it's supposed to work. Specifying a mode in `:enabled-for-mode` should cover that mode and all of its children, grand-children, grand-grand-children, etc.

Unfortunately, for `typescript` that doesn't work because of typescript-mode uses a `defalias` to define `typescript-parent-mode`, while `defalias` is meant for functions really. This is either:
- a bug in built-in function `derived-mode-p` (which Spacemacs uses), that doesn't recognized aliased modes; or 
- a bug in [typescript-mode](https://github.com/ananthakumaran/typescript.el), that shouldn't use a `defalias`. Anyway, that `defalias` and `typescript-parent-mode` look like a work-around to handle old Emacs versions (I think 23 and older) where `prog-mode` doesn't exist.

@jupl I suggest you submit a bug report to typescript-mode, since I'm pretty sure `defalias` isn't supposed to be used like this. Maybe they can make `typescript-parent-mode` a proper child mode of `prog-mode`? For now, you'll have to specify `typescript-mode` directly in your configuration.

Regarding JS files, I don't know why you don't get line numbers. Works OK if I activate `javascript-mode` in a buffer, and it should work also for `json-mode`.
