### ISSUE TITLE
line-height changed while select text or auto-complete drop down menu appear.

### ISSUE THREAD

**Issue by idears-org** [syl20bnr/spacemacs#8943]
#### Description :octocat:

 when I select text, line height changed.

#### System Info 💻

    OS: win10
    Emacs: 25.1.1
    Spacemacs: 0.200.9
    Spacemacs branch: master (rev. 8e1af14)
    Graphic display: t
    Distribution: spacemacs
    Editing style: vim
    Completion: helm
    Layers: all of the text

gif here:
![select](https://cloud.githubusercontent.com/assets/13452500/26335166/a2d01d14-3f9c-11e7-9153-4cb76018c119.gif)

I use Source Code Pro
I have installed the font in my operating system.
theme: spacemacs-dark

**Comment by braham-snyder** [comment]
@idears-org does disabling `spaceline` (`spacemacs/toggle-mode-line-off` in all open windows) happen to circumvent this?

**Comment by duianto** [comment]
This is caused by the fill column indicator `SPC t f`, the yellow `|` symbols on the right. The lines that are selected don't show the fill column symbol, therefore their line height is reduced to normal. 
Toggling `SPC t f` also shows that the line height changes.

**Comment by idears-org** [comment]
sorry for the late reply
thank you for your help @braham-snyder @duianto 
@braham-snyder I'v tried your suggestion, but It's not work.
@duianto tell the truth
this problem caused by fill column symbol

**Comment by idears-org** [comment]
see this https://github.com/syl20bnr/spacemacs/issues/6707
(setq fci-always-use-textual-rule t)
will solve this.

**Comment by duianto** [comment]
I think i found the cause.

The xpm image that draws the `|` symbol, is defined in the `fci-make-xpm-img` function:
https://github.com/alpaker/Fill-Column-Indicator/blob/master/fill-column-indicator.el#L664

It's height is defined by the `height-str` variable:
`           (dimens (concat "\"" width-str " " height-str " 2 1\","))`
https://github.com/alpaker/Fill-Column-Indicator/blob/master/fill-column-indicator.el#L668

the `height-str` variable is set in the `fci-with-rule-parameters` macro:
``  `(let* ((height-str (number-to-string fci-char-height))``
https://github.com/alpaker/Fill-Column-Indicator/blob/master/fill-column-indicator.el#L625

and the `fci-char-height` variable is set in the `fci-get-frame-dimens` function
``` elisp
    (setq fci-char-width (frame-char-width frame)
          fci-char-height (frame-char-height frame))))
```
https://github.com/alpaker/Fill-Column-Indicator/blob/master/fill-column-indicator.el#L620

`fci-char-height` is used in both the `segment-length` and `vmargin` variables. It's also used in the 
`fci-post-command-check` function, to check if the default char width and height has changed. Therefore the `fci-char-height` variable probably should be left alone.

The `height-str` variable is only used for making the fci image, in the `fci-make-pbm-img` and 
`fci-make-xpm-img` functions, that means that it's height can be changed.

The line height issue only seems to occur in windows, according to #6707, therefore the height only needs to be changed in windows.

The line height issue is fixed by changing this line:
```
  `(let* ((height-str (number-to-string fci-char-height))
```
https://github.com/alpaker/Fill-Column-Indicator/blob/master/fill-column-indicator.el#L625

to this:
```
  `(let* ((height-str (number-to-string
                       ;; windows issue: an fci image height of 17px, increases
                       ;; the line heights, this reduces the height to 16px
                       (if (eq system-type 'windows-nt)
                           (1- fci-char-height)
                         fci-char-height)))
```

For the changes to take effect, either save the file and restart Emacs, or place the cursor in the 
`fci-with-rule-parameters` macro, and press `, e f` to call `eval-defun`, and do the same thing with the cursor in the `fci-make-xpm-img` function.

**Comment by duianto** [comment]
Hmm.. The issue might be with Spacemacs and not the fill-column-indicator package. 
Because when I do the following:
Start Emacs with `-Q`
`M-x` `package-initialize`
`S-M-;` `(require 'fill-column-indicator)`
`M-x` `fci-mode`

then the fill column indicator symbols are shown, but the line height doesn't change. There's also no gap between the fill column symbols like it is in Spacemacs.

Changing the font to match Spacemacs doesn't make the line heights change either:
Options > Set Default Font...
Font: Source Code Pro
Font style: Regular
Size: 13

**Comment by idears-org** [comment]
you are so cool @duianto 

I add this line to my dotspacemacs file 
```(setq fci-always-use-textual-rule t)```

It's circumvent this, but this issue should be solved.
so, should I reopen this issue ?

**Comment by duianto** [comment]
@idears-org 
You can leave this issue closed, since the duplicate issue where you found the workaround still is open:
[Graphical fill column indicator increases line height #6707](https://github.com/syl20bnr/spacemacs/issues/6707)

I'll re-post my possible solution there.

I don't know if it's Emacs or the fill column indicator package that hides the `|` symbols on the highlighted lines.

**Comment by idears-org** [comment]
thank you,I'll subscribe that one.
