### ISSUE TITLE
[feather wanted]java lsp mode support

### ISSUE THREAD

**Issue by sound2gd** [syl20bnr/spacemacs#8956]
there is a lot of problem in current lsp-mode && lsp-java when using spacemacs,
It will be really nice if spacemacs team do some support for this because the exprience
of writing java code in Emacs is really aweful yet.

when I use [vscode-java](https://github.com/redhat-developer/vscode-java) backed by eclipse JDT lang server , It is so fast  and 100% correct semantic code completion  that I realized maybe we can do something like [vscode-java](https://github.com/redhat-developer/vscode-java) do to make the same good happen in Emacs.

But I am poor in Emacs Lisp,also I am a every-day spacemacs user,So I turn to you spacemacs community for help.

related repos:

- [language server protocol](https://github.com/Microsoft/language-server-protocol)
- [eclipse.jdt.ls](https://github.com/eclipse/eclipse.jdt.ls)
- [vscode-java](https://github.com/redhat-developer/vscode-java)

the effect of vscode-java
![image](https://raw.githubusercontent.com/redhat-developer/vscode-java/master/images/vscode-java.0.0.1.gif)

**Comment by CeleritasCelery** [comment]
Eclipse was built for Java. It will be hard to to match their level of integration, though the Spacemacs Java layer is pretty good. You may be better off if you raised specific fixable problems with the Java layer that could be addressed instead of catch-all "make it better" request.

**Comment by robbyoconnor** [comment]
I agree with @CeleritasCelery here -- Raise actual real issues -- this kind of issue is useless. Look at the java layer and for example -- try the meghanada backend -- it's freaking amazing and surprisingly good. 

As for your being poor at emacs lisp -- it's not a hard language to learn and the stuff you want to do -- it's surprisingly easy -- in fact there's examples all over the spacemacs codebase. Rather than raise issues like this (which is quite useless) -- learn and improve spacemacs.

**Comment by sound2gd** [comment]
@CeleritasCelery @robbyoconnor 
friends, thanks for your advices

meghanada does crash when working with large codebase.
java layer that backed by eclim , meghanada or ensime 
is not worked as I expected and often got my Emacs fake-dead.

if it is useless to raise this kind of issue, I will lean Elisp and do it myself.

**Comment by robbyoconnor** [comment]
That would be helpful. Fix the issues rather than complaining. Open Source
is cool for that reason.

On May 24, 2017 7:45 PM, "Chris Wang" <notifications@github.com> wrote:

@CeleritasCelery <https://github.com/celeritascelery> @robbyoconnor
<https://github.com/robbyoconnor>
friends, thanks for your advices

meghanada does crash when working with large codebase.
java layer that backed by eclim , meghanada or ensime
is not worked as I expected and often got my Emacs fake-dead.

if it is useless to raise this kind of issue, I will lean Elisp and do it
myself.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/syl20bnr/spacemacs/issues/8956#issuecomment-303883416>,
or mute the thread

**Comment by robbyoconnor** [comment]
This isn't meant to discourage you, but encourage you to push yourself to learn and help fix the problems you're having :)
