### ISSUE TITLE
Restore Smartparens key bindings for Emacs users

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#896]
Currently, key bindings like `C-<left>` (runs `sp-backward-slurp-sexp`) does not work. We need them back.

**Comment by syl20bnr** [comment]
Seems that these key bindings are taken by subword mode which is a default minor mode since 24.4. I don't want to overwrite these key bindings for 3 reasons:
- they are default
- navigating by subword is more useful and universal than manipulating the AST
- paredit like features of smartparens are available behind `SPC k` (C-c k in holy-mode)

**Comment by syl20bnr** [comment]
Just noticed that `C-S-left` is the same as `C-left` so I propose to put the elisp AST manipulation on `C-S` prefix + arrows.

**Comment by tuhdo** [comment]
Fine by me but you should change key bindings of evil-escape to be compatible with Emacs convention.

**Comment by syl20bnr** [comment]
What do you mean ?

**Comment by tuhdo** [comment]
Oh sorry I meant you should change `evil-lisp-state` key bindings from `hjkl` and change it to `fbnp`.

**Comment by StreakyCobra** [comment]
This is an old issue without activity the last 6 months, as it also don't seem relevant anymore, I'm closing it.
