### ISSUE TITLE
Error (use-package): powerline :init: Symbol's value as variable is void: left

### ISSUE THREAD

**Issue by crucialfelix** [syl20bnr/spacemacs#897]
Spacemacs fails to start.

Error (use-package): powerline :init: Symbol's value as variable is void: left 

I have started up without any custom .spacemacs

rollback packages did not fix it, so its something with 0.100.1

I don't understand how you could be shipping a broken release. shouldn't travis throw an error ?

so obviously something is wrong with my install. but what ? and how would I know or fix that ?

**Comment by syl20bnr** [comment]
See #817 ;-)

**Comment by crucialfelix** [comment]
okay deleting it caused it to be reinstalled and it works now.

but I still don't understand why this error happened or why reinstalling it would work.

are the packages not pinned to specific releases?  
were there extra files that needed to be deleted ?

**Comment by syl20bnr** [comment]
The update mechanism of emacs packages is not bulletproof and sometimes the
byte-compilation triggers errors when updating. This is out of the scope of
Spacemacs. The error is also listed in the powerline repository upstream.

For now Spacemacs lives on the bleeding edge because it is way
simpler. This is why you have the rollback link on the startup page. Note
that the rollback will work only if you use the update link on the startup
page as well. Be sure to choose the right rollback slot also.

Pinning packages seems easy but it is not the case in practice, this method
has as many drawbacks as the bleeding edge versions. I think that with the
rollback we have our back covered for now and we can enjoy the benefits of
being bleeding edge.

But I will use pinning in the future for some key packages. Spacemacs is
not ready for this yet.


Le samedi 21 mars 2015, Chris Sattinger <notifications@github.com> a écrit :

> okay deleting it caused it to be reinstalled and it works now.
>
> but I still don't understand why this error happened or why reinstalling
> it would work.
>
> are the packages not pinned to specific releases?
>
> were there extra files that needed to be deleted ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/897#issuecomment-84365957>.
>


-- 
-syl20bnr-
