### ISSUE TITLE
Super slow startup on Windows 10

### ISSUE THREAD

**Issue by Peluko** [syl20bnr/spacemacs#9018]
Hello. I have very long startup times on Windows 10. My setup is Emacs 25.2.1 and spacemacs 0.200.9. On Windows 10 I get 157 seconds for 363 packages. The same setup on macOS Sierra (the same init.el) gives 18 seconds.

The windows PC is behind a corporate proxy, so I've tryed this:

https://github.com/syl20bnr/spacemacs/blob/master/doc/FAQ.org#why-is-spacemacs-hanging-on-startup

but with no luck. It's frustating. What could I do?

Thanks.

**Comment by sdwolf** [comment]
Since you mentioned `coroprate proxy` and `windows` maybe the problem is that you have your `%HOME%` environment variable set to a network drive (for example `Z:\`) and the read/write speed on that drive is causing this.

This was the case for me once, was reading files with the astonishing speed of 15 bytes per second on that drive. The solution in my case was to contact my IT department and ask them to remove the value they enforce for `%HOME%` from `Active Directory` so I can have my home at the defalut location on drive `C:\Users\my.username\`

**Comment by Peluko** [comment]
```
C:\>echo %HOME%
C:\Users\acarrillo
```
My home is on local SSD disk.

**Comment by Peluko** [comment]
Any ideas on what should I look for in order to solve this?

**Comment by sdwolf** [comment]
Sorry but that's the only thing I got for windows, try asking in the gitter chat: https://gitter.im/syl20bnr/spacemacs
