### ISSUE TITLE
Helm cannot split inside the active window?

### ISSUE THREAD

**Issue by tddsg** [syl20bnr/spacemacs#9044]
#### Description :octocat:
I tried to make Helm split from only the active window by setting `helm helm-split-window-in-side-p` to `t` but somehow it doesn't work. 

I saw from this [Reddit](https://www.reddit.com/r/emacs/comments/52lnad/from_helm_to_ivy_a_user_perspective/d7lypeu/) post that it was able to do so. However, the newest version of Spacemacs doesn't work for me.

#### Reproduction guide :beetle:
- Start Emacs
- Make sure the variable `helm helm-split-window-in-side-p` is set to `t`
- Split window vertically by `C-x 3`
- Now focus on 1 window and type `M-x`

*Observed behaviour:* :eyes: :broken_heart:
- The Helm buffer is split from the entire active frame

*Expected behaviour:* :heart: :smile:
- The Helm buffer should be split only from the active window

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by ZarsBranchkin** [comment]
A temporary fix for this is to use the default helm display function. Right now spacemacs overrides it, in order to force helm on a side window. 

The problem with default helm display function, is that it can not create a side window, without hiding other open windows, so I guess that's the reason spacemacs overrides it.

For now you can use this in your user-config. Note that it will ignore `dotspacemacs-helm-position`, so use `helm-split-window-default-side` instead.

```elisp
(setq-default helm-display-function 'helm-default-display-buffer)
````

**Comment by tddsg** [comment]
Thank you so much! It works perfectly. I have been looking into this issue for months!

**Comment by ZarsBranchkin** [comment]
@TheBB I'm looking into fixing this issue, but not completely sure of the best approach to take here.

Right now, spacemacs forces `display-function` to show helm buffer as a side window. I could expand on what the `spacemacs//display-helm-window` is currently doing, but wrapping the default display function in additional logic seems real messy.

Other option could be to take the helm's default display function and rewrite it, so that it can cleanly support both side window and using the current window. This however might render some of the helm buffer display variables useless. Might not be too big of a problem, considering something like that is already happening.

What would you suggest doing? I suppose I could implement one of the versions and then continue discussion in the PR. Right now I'm considering rewriting the helm display function.

**Comment by tddsg** [comment]
What I am doing now is to selectively use `'helm-default-display-buffer` in a few buffers. I use function advice to do it like below:

 ```
 ;; advice that forces Helm to split the active window, and restores the default Spacemacs's helm
  (defun advise-helm-split-active-window (orig-func &rest args)
    (setq helm-display-function 'helm-default-display-buffer)
    (apply orig-func args)
    (setq helm-display-function 'spacemacs//display-helm-window))
 ;; apply the advice a few buffers
  (advice-add 'helm-company :around #'advise-helm-split-active-window)
  (advice-add 'helm-semantic-or-imenu :around #'advise-helm-split-active-window)
  (advice-add 'helm-imenu :around #'advise-helm-split-active-window)
  (advice-add 'completion-at-point :around #'advise-helm-split-active-window)

```

**Comment by dabro** [comment]
👍 @tddsg 
@ZarsBranchkin just `(setq-default helm-display-function 'helm-default-display-buffer)` didn't seem to work.

**Comment by agrafix** [comment]
This seems to be broken again in the newest master and the workarounds don't work anymore :(

**Comment by ZarsBranchkin** [comment]
Can't seem to replicate this. Tried both with my configuration and clean install configuration, the previous workaround still works.

I noticed that the new variable for splitting in side is `helm-split-window-inside-p`, although the previous, obsolete one, still works for me as well.

**Comment by tddsg** [comment]
I update the new variable `helm-split-window-inside-p`, and verify that the above solution still works

**Comment by agrafix** [comment]
Switching to the new one works 👍
