### ISSUE TITLE
Check for new version

### ISSUE THREAD

**Issue by jvillasante** [syl20bnr/spacemacs#9107]
Does anybody knows what this means, every time I restart emacs it doesn't check for new version and this is the message I get on the "Messages" buffer:

`Skipping check for new version (reason: dotfile)`

**Comment by NJBS** [comment]
It's because `dotspacemacs-check-for-update` is `nil` (the default) in your `.spacemacs` file.

See [here](https://github.com/syl20bnr/spacemacs/blob/8e1af145480d53e8d32cdff2c83291889903164b/core/templates/.spacemacs.template#L89-L93) for the setting.

If you'd like to understand why checking for updates on every startup is turned off by default see https://github.com/syl20bnr/spacemacs/issues/6692.

**Comment by jvillasante** [comment]
Makes sense!!! Thanks!!!

**Comment by seanchen1991** [comment]
I have `dotspacemacs-check-for-update` set in my `.spacemacs` file and I'm still getting `Skipping check for new version (reason: dotfile)`. Could something be overriding it?

**Comment by lebensterben** [comment]
@seanchen1991 Are you on the develop branch?

**Comment by seanchen1991** [comment]
> Are you on the develop branch?

Yes

**Comment by lebensterben** [comment]
@seanchen1991 
This button is removed on develop now. You should pull in the latest commits manually now.
