### ISSUE TITLE
guide-key window is sized incorrectly when other windows don't span the frame

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#915]
Steps to reproduce:

1. Open spacemacs
2. Do `SPC w / SPC w / SPC w / SPC`
3. Note that the guide-key window that pops up is not wide enough to show all the text.

**Comment by syl20bnr** [comment]
This is a recurring issue with popup buffers. I don't know how we can handle this on the Spacemacs side, maybe we can provide a minimal size.

**Comment by bmag** [comment]
Hi, I managed to fix the problem with a locally modified version of guide-key. My local version uses [window-purpse](https://github.com/bmag/emacs-purpose) instead of popwin.
I can add my version of guide-key to spacemacs, or I can write some defadvices instead. Basically, I've overridden `guide-key/close-guide-buffer` and `guide-key/popup-guide-buffer`, and added a hook to `guide-key-mode-hook`.
However, these changes require that spacemacs use a new package (window-purpose), so I'm not sure if I should upload them or keep them to myself.
@syl20bnr , what do you think?

**Comment by syl20bnr** [comment]
@bmag I don't see the relation between `window-purpose` and `popwin` so I'm curious to know how `window-purpose` fixes this. Does `window-purpose` provide a popwin feature ?

**Comment by bmag** [comment]
`window-purpose` is more general than `popwin`. It is actually meant to be an alternative window manager for emacs, but guide-key can use it for popping and closing the guide-key window.
I'll open a PR with the proper advices for guide-key, so you can see something concrete, but only next week (I won't have time this week).

**Comment by syl20bnr** [comment]
Cool ! Thank you.

**Comment by tuhdo** [comment]
As far as I know, `window-purpose` tries to keep a persistent layout, while `popwin` tries to manage temporary buffers and sizes of such buffers. How can `window-purpose` replace `popwin`?

**Comment by bmag** [comment]
You'll see in the PR :-)
Important parts are a custom display function and `(mapc 'delete-window (purpose-windows-with-purpose 'guide-key))`.

**Comment by bmag** [comment]
Done it. Looks fine?

**Comment by x-ji** [comment]
Changes introduced in this PR works fine for me.

**Comment by x-ji** [comment]
Did a PR to change the window position https://github.com/syl20bnr/spacemacs/pull/1387 as a temporary fix.
