### ISSUE TITLE
Regression: `org-goto` window layout is broken.

### ISSUE THREAD

**Issue by nochiel** [syl20bnr/spacemacs#9157]
#### Description :octocat:
Regression in `org-goto` layout.

#### Reproduction guide :beetle:
- Start Emacs
- Open a text file in `org-mode`.
- Create several headers.
- `C-c C-j` or `SPC SPC org-goto`

*Observed behaviour:* :eyes: :broken_heart:
The current buffer becomes `*org help*` and is the only one in the window.

*Expected behaviour:* :heart: :smile:
The window layout should be similar to:

```
| *org-goto* |
|----------- |
| *org-help* |

```

i.e. two buffers side-by-side.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. fcf186fa)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(php javascript helm auto-completion better-defaults emacs-lisp markdown org
     (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
     shell-scripts spell-checking syntax-checking version-control
     (git :variables magit-repository-directories
          '("~/Documents" "~/.emacs.d" "~/Documents/code/sources"))
     (clojure :variables clojure-enable-fancify-symbols t)
     asm
     (evil-cleverparens :variables evil-cleverparens-swap-move-by-word-and-symbol t evil-cleverparens-use-regular-insert nil)
     scheme common-lisp
     (c-c   :variables c-c  -enable-clang-support t)
     cscope python html major-modes restclient sml haskell dash
     (eww :variables eww-history t eww-bookmarks-directory spacemacs-cache-directory)
     arch)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES LIBSYSTEMD

**Comment by bmag** [comment]
I can repro this bug. Probably an upstream issue in [window-purpose](https://github.com/bmag/emacs-purpose/). Can you report it there?

**Comment by bmag** [comment]
Nevermind, reported upstream myself.

**Comment by bmag** [comment]
Fixed upstream, MELPA should have the fixed version of window-purpose available within several hours.

**Comment by edburyenegren-okta** [comment]
This is still broken on `develop` as of today.

**Comment by benlind** [comment]
This is still broken. Is there a workaround?

**Comment by duianto** [comment]
Confirmed.

Adding `window-purpose` to the `dotspacemacs-excluded-packages` list brings back the expected behavior.

I'm just guessing but it might break other things that use the `window-purpose` package.

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 75cfd40d3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion colors command-log emacs-lisp git github haskell helm imenu-list markdown multiple-cursors org
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by syl20bnr** [comment]
@bmag Do you have time to look into this or some pointers about the issue ?

**Comment by bmag** [comment]
I looked into it, and I think the following will fix the problem. Please re-enable window-purpose and evaluate this code:

```elisp
(defun purpose--fix-org-goto-location (oldfun &rest args)
  "Make Purpose inactive during `org-goto-location'."
  (without-purpose (apply oldfun args)))

(with-eval-after-load 'org
  (advice-add 'org-goto-location :around 'purpose--fix-org-goto-location))
```

You can put it inside user-config function. Please tell me if it works and if you notice any other problems. If everything is ok, then I'll add this fix upstream.

(The regression happened because `org-goto` was changed to use `org-goto-location` instead of `org-get-location`, so the fix in window-purpose needs to be updated)

**Comment by duianto** [comment]
@bmag Confirmed, with that snippet in my user-config.

Now `C-c C-j` or `M-x org-goto` in a `.org` file, opens two windows in the same configuration as the issue author demonstrates in the `Expected behaviour` section:
```
| *org-goto* |
|----------- |
| *org-help* |
```

**Comment by syl20bnr** [comment]
Thank you @bmag and @duianto. Is that fixed upstream or do we need to add the fix to Spacemacs.

**Comment by duianto** [comment]
The fix hasn't been applied upstream yet. But we don't need to fix it in Spacemacs.
bmag said that it will be handled upstream:
>Please tell me if it works and if you notice any other problems. If everything is ok, then I'll add this fix upstream.
>
>(The regression happened because org-goto was changed to use org-goto-location instead of org-get-location, so the fix in window-purpose needs to be updated)

**Comment by bmag** [comment]
Fixed the regression upstream in https://github.com/bmag/emacs-purpose/commit/1ca432002e2cac68784dd3d2e13a1acab9ff7203. You shouldn't see any change in behavior, though, because the bug has already been hidden some time ago by a different change upstream that coincidentally prevented it from triggering in most cases.
