### ISSUE TITLE
Avy motion in visual mode off by one character

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#9168]
#### Description :octocat:
<<In visual mode when an avy motion is used (such as avy-goto-char) the location
you end up with or start with is off by one character.>>

#### Reproduction guide :beetle:
- Start Emacs
- Open a file with text. Enter visual mode. Jump to a character.

*Observed behaviour:* :eyes: :broken_heart:
<<Assume *point is greater than **point. When cursor is at **point and jumps to
location at *point in visual mode, cursor ends up at *point - 1. When cursor is
at *point and jumps to **point the point of origin is *point - 1.>>

*Expected behaviour:* :heart: :smile:
<<I expected a jump in visual mode to end up where I at the candidate I selected
and to start where my cursor was placed just before the jump. Instead, it's one off.>>

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy speed-reading pdf-tools emacs-lisp vimscript github version-control markdown org emoji
     (ranger :variables ranger-cleanup-eagerly t ranger-show-hidden nil ranger-parent-depth 2 ranger-width-parents 0.12 ranger-max-parent-width 0.12 ranger-show-literal t ranger-ignored-extensions
             '("mkv" "iso" "mp3")
             ranger-max-preview-size 10)
     (git :packages
          (not orgit))
     (extra-langs :packages matlab-mode)
     (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-return-key-behavior 'complete auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip nil auto-completion-enable-sort-by-usage t)
     spacemacs-completion spacemacs-editing spacemacs-editing-visual
     (spacemacs-evil :packages
                     (not evil-tutor evil-search-highlight-persist))
     (spacemacs-language :packages define-word)
     spacemacs-misc spacemacs-org spacemacs-ui
     (spacemacs-ui-visual :packages
                          (not fancy-battery neotree))
     (mu4e :variables mu4e-maildir "~/Maildir" mu4e-drafts-folder "/[Gmail].Drafts" mu4e-sent-folder "/[Gmail].Sent Mail" mu4e-trash-folder "/[Gmail].Trash" mu4e-sent-messages-behavior 'delete mu4e-get-mail-command "offlineimap" mu4e-compose-signature "Luis Henriquez")
     (themes-megapack :packages solarized-theme gotham-theme cyberpunk-theme material-theme)
     (shell :packages xterm-color multi-term shell-pop eshell-z eshell-prompt-extras esh-help magit company :variables shell-default-position 'bottom shell-default-height 30 shell-default-shell 'multi-term shell-default-full-span nil shell-enable-smart-eshell t)
     (w3m :variables w3m-default-display-inline-images t w3m-default-toggle-inline-images t w3m-command-arguments
          '("-cookie" "-F")
          w3m-use-cookies t w3m-view-this-url-new-session-in-background t)
     (spell-checking :variables spell-checking-enable-by-default nil)
     (syntax-checking :variables syntax-checking-enable-by-default nil)
     (latex :variables latex-build-command "LaTeX" latex-enable-auto-fill t latex-enable-folding t)
     emacs-lisp)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```
Note: I tried to send this by pressing 'C-c C-c' but it said that binding was unmapped.

**Comment by duianto** [comment]
It seems to be working as expected for me on the latest master and develop branches, with this text:
```
ab cd ef gh ij
```

### The first example:
>Assume *point is greater than **point. When cursor is at **point and jumps to
location at *point in visual mode, cursor ends up at *point - 1. 

With the cursor on the `c` in normal state
Switch to visual state `v`
Jump to the `g`, by pressing `SPC j j g`,
the cursor moves to the `g` and the selected characters are: `cd ef g`.

The observed behaviour seem to indicate that the cursor would have ended up between `f` and `g`. And these characters would have been selected: `cd ef ` (with a space at the end).

### The second example:
>When cursor is
at *point and jumps to **point the point of origin is *point - 1.

With the cursor on the `g` in normal state
Jump to the `c`, by pressing `SPC j j c`,
the cursor moves to the `c`.

The observed behaviour seem to indicate that the cursor would have ended up between `b` and `c`.

Maybe avy has fixed it since this issue was posted. Try updating the packages and check if it still happens.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(spell-checking syntax-checking
                (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
                ivy org treemacs git version-control autohotkey emacs-lisp haskell html markdown)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

#### notes
It also works as expected on the develop branch with both ivy and helm.
- Spacemacs branch: develop (rev. b4b7d63e)

**Comment by duianto** [comment]
I just noticed that some `avy-goto-*` commands are declared with `inclusive` and some with `exclusive` here: https://github.com/emacs-evil/evil/blob/afa066c0454bea381aa1eb989fbed69e7084ae3c/evil-integration.el#L509

That made me test some of the avy goto commands that doesn't have a keybinding, like `avy-goto-word-0`. By calling it from the `M-x` prompt. And the last char gets excluded in visual state.
It also happens with the commands that do have keybindings.

So the reported issue is confirmed when the avy goto commands are called in visual state from the `M-x` prompt.
