### ISSUE TITLE
Spacemacs org-mode configuration displaying element SEXP in minibuffer

### ISSUE THREAD

**Issue by notmgsk** [syl20bnr/spacemacs#9182]
When the cursor is on an element in an org-mode file, the SEXP for that element (something like org-element-at-point) is displayed in the mini buffer. I've been told that this is not standard behaviour for org-mode, and so if I want to disable it, I should ask the spacemacs developers.

So -- how do I stop the SEXP being echo'd in the mini buffer? [Screenshot](https://i.imgur.com/lttH7Df.jpg)

**Comment by TheBB** [comment]
> So -- how do I stop the SEXP being echo'd in the mini buffer? 

Offer some reproduction steps in your bug report. :-)

**Comment by notmgsk** [comment]
Take a look at the screenshot, ya dingus. Not much else to replicate. Spacemacs? Check. Org mode? Check. Sarcasm? Check.

**Comment by TheBB** [comment]
I did. I have all those things and I can't reproduce, so not check.

**Comment by TheBB** [comment]
For the record, I'm not trying to be sarcastic. When you report an issue to this repo, you are asked to use `SPC h I` from within Spacemacs, which fills in a bug report template with system information that could be necessary to reproduce your problem. Since you didn't do that, and trying to replicate your screenshot did not produce anything of note, we're not left with much. For example, these are questions that you could help by answering:

* do I need spacemacs master or develop?
* does it reproduce with *just* the org layer enabled or do I need some other layer too?
* does it reproduce with just the basic org layer or do I need to enable some feature disabled by default?
* does it reproduce if you remove all personal config from your dotfile (e.g. a clean install)?
