### ISSUE TITLE
Allow for ibuffer filter group customization

### ISSUE THREAD

**Issue by basus** [syl20bnr/spacemacs#9202]
In standard Emacs it's possible to customize the `ibuffer` groupings by setting `ibuffer-saved-filter-groups` and then running the following `ibuffer-mode-hook`:

```
(add-hook 'ibuffer-mode-hook
          (lambda ()
            (ibuffer-switch-to-saved-filter-groups "default")
            (setq ibuffer-show-empty-filter-groups nil)
            (ibuffer-auto-mode 1)))
```

Spacemacs does not seem to allow for the same. According to the [https://spacemacs.org/layers/+emacs/ibuffer/README.html](ibuffer layer documentation), buffers can only be grouped by modes or projects. Could we have this customizability back please? It's very helpful to see buffers grouped by something other than mode or project (for example, collecting source and compilation buffers together etc.).

**Comment by marienz** [comment]
Setting `ibuffer-group-buffers-by` to `nil` might work for you: that should disable the code in Spacemacs that conflict with yours, which is fine if you weren't using Spacemacs to group by mode anyway.

`spacemacs//ibuffer-create-buffs-group` is overwriting `ibuffer-saved-filter-groups` and then switching to the one filter group it just saved. That seems unnecessarily inflexible: it should either add to `ibuffer-saved-filter-groups` instead of overwriting it completely, or set `ibuffer-filter-groups` directly and leave `ibuffer-saved-filter-groups` alone.

`ibuffer-projectile` takes the latter approach, but the former seems nicer: it lets you switch between groupings with `/ R` (and probably do other nice things I haven't worked out yet).

**Comment by basus** [comment]
Setting `ibuffer-group-buffers-by` to `nil` seems to do the trick, and allows my existing customization code to run.
