### ISSUE TITLE
Erratic and inconsistent mouse click behaviour with "imenu-list".

### ISSUE THREAD

**Issue by KelSolaar** [syl20bnr/spacemacs#9238]
#### Description :octocat:
Erratic and inconsistent mouse click behaviour with "imenu-list".

#### Reproduction guide :beetle:
- Start Emacs
- Open a python file
- Enable *imenu-list* with `SPC SPC imenu-list`
- Navigate by clicking items in the *Ilist* window

*Observed behaviour:* :eyes: :broken_heart:
The mouse click behaviour is erratic and inconsistent as illustrated by this screencast: https://www.screencast.com/t/pCznH2XIVGV

*Expected behaviour:* :heart: :smile:
Being able to navigate around by simply clicking items in the *Ilist* window.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. e09385d2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm html javascript markdown python spell-checking syntax-checking windows-scripts yaml
                 (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by KelSolaar** [comment]
For information, I tried to set `toggle-debug-on-error` but there is no traceback.

**Comment by bmag** [comment]
The preferred way to install `imenu-list` is by enabling the `imenu-list` layer. This layer configures the Ilist buffer to be in evilified-state instead of normal-state, and I'm quite sure normal-state interferes with mouse clicks.

Also, don't click the mouse too fast. At 0:35 you are clicking on _validate_interpolation_range at a fast rate, so the clicks are interpreted as "I'm trying to mark the character/word/line", instead of a regular mouse click.

Please enable `imenu-list` layer and tell us if it solved the problem.

**Comment by bmag** [comment]
`toggle-debug-on-error` doesn't provide a traceback because the code doesn't throw any error in this case.

**Comment by KelSolaar** [comment]
Hi @bmag,

> toggle-debug-on-error doesn't provide a traceback because the code doesn't throw any error in this case.

Yes, I mentioned it just in case somebody asked for it!

> Please enable imenu-list layer and tell us if it solved the problem.

That was exactly it, thanks a lot, might be a nice thing to add that information to the README file on [imenu-list](https://github.com/bmag/imenu-list). Thanks again.

Thomas
