### ISSUE TITLE
Go to line

### ISSUE THREAD

**Issue by cinjon** [syl20bnr/spacemacs#9295]
Just starting to use spacemacs (emacs) - how do I go to a line? In my prior emacs setup, I used ctrl-N <line number> for that. What's the command here?

**Comment by kRITZCREEK** [comment]
The emacs default keybinding of `M-g g` works.

**Comment by d12frosted** [comment]
You have specific answer for you case, but I would like to add a little bit to help you in future with similar questions. In case you already know this, just skip it 😸 

When you know the name of a function, but don't know key binding - hit `C-h f` (default Emacs key binding) or `SPC h d f` (Spacemacs key binding) and type name of that function to find it's documentation and key bindings assigned to it. That's not related to Spacemacs, but to Emacs in general. 

I bet in your previous setup you used `goto-line`, so you could just describe that function and find key binding by yourself 😸 

In case you don't know the name, you can just type what you want to do. In your case searching for desired function is easy as your need easily translates to actual function name 😸 In harder cases I just play around with synonyms to find what I want.

Also there is another neat trick for interactive functions (the ones people bind). Instead of using describe function (`C-h f` or `SPC h d f`) try using `M-x` or `SPS SPS` and start searching for desired function. It will show you the name and the binding.

Emacs is self documenting. And Spacemacs strives for discoverability. And that's great for finding things 😸 

Also don't hesitate and <a href="https://gitter.im/syl20bnr/spacemacs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"><img src="https://badges.gitter.im/Join Chat.svg" alt="Gitter"></a>

😸

**Comment by d12frosted** [comment]
Closing this issue as the question was answered.

**Comment by d12frosted** [comment]
Oh, forgot to tell, this doesn't mean that you are not allowed to continue conversation here - please do so if you have anything to say, ask or share! 😸

**Comment by gacosta89** [comment]
The vim commands work. [Vim go to line](http://vim.wikia.com/wiki/Go_to_line)
