### ISSUE TITLE
How to enable React syntax highlighting in .js files?

### ISSUE THREAD

**Issue by ankitrg** [syl20bnr/spacemacs#9358]
I am on a codebase where we write react code and the file extensions are `.js` how can I enable `jsx` highlighting in this file? 

I'm new to spacemacs so sorry if this is naive.

**Comment by aatxe** [comment]
I believe you can do this by adding a line to your configuration that will set `react-mode` based on the `.js` file extension. Should look something like this:

```
(add-to-list 'auto-mode-alist '("\\.js\\'" . react-mode))
```

I don't know if there's any issues with it conflicting with the existing mapping to `js2-mode` though.

**Comment by ankitrg** [comment]
I am getting `file mode specification error: ( void-function react-mode)`

Here is how I've added the config in my `.spacemacs`

```
(defun dotspacemacs/user-config ()
  ;; Enable React syntax highlighting for .js files
  (add-to-list 'auto-mode-alist '("\\.js\\'" . react-mode))
  )
```

Is there something I am missing?

**Comment by aatxe** [comment]
So, according to [this stackexchange post](https://emacs.stackexchange.com/questions/3397/how-to-replace-an-element-of-an-alist), there's no issue with the already existing mode for `.js` files. At this point, this is beyond my knowledge though. Not sure why it's not working.

**Comment by obsoke** [comment]
This feature works out-of-the-box with the `react` layer for me. One way to get it to work is by having the first line of the file  be `import React from 'react';` in order for Emacs to recognize the file as a React file rather than just plain JavaScript. The other methods are the `/** @jsx React.DOM */` at the top of the file or naming the file in a specific way. 

So if you want `react-mode` to automatically enable in React files with a `.js` extension, it seems you need the first line of the file be that `@jsx` tag or `import` statement. You can see all the ways in which Spacemacs decides whether `react-mode` should be enabled [here](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bframeworks/react/packages.el#L67-L72).

**Comment by AnaRobynn** [comment]
The react-mode on develop doesn't enable react-mode for the following import statement: `import React, { Component } from "react";`

I suspect it has something to do with the following line of code: https://github.com/syl20bnr/spacemacs/commit/12f823ba3c18d036ecfa8944775324842c3f3b55

**Comment by jbharat** [comment]
@AnaRobynn I have been using this 
```
(add-to-list 'magic-mode-alist 
         '("\\(import.*from \'react\';\\|\/\/ @flow\nimport.*from \'react\';\\)" . react-mode))
```
Seems to handle all cases for me including flow
