### ISSUE TITLE
Warning: d12frosted/emacs-plus/emacs-plus: this formula has no --with-natural-title-bars option

### ISSUE THREAD

**Issue by swaroopch** [syl20bnr/spacemacs#9365]
As per https://github.com/syl20bnr/spacemacs#emacs , I ran `brew install emacs-plus --HEAD --with-natural-title-bars` but I see this warning:

```
Warning: d12frosted/emacs-plus/emacs-plus: this formula has no --with-natural-title-bars option so it will be ignored!
==> Installing d12frosted/emacs-plus/emacs-plus --HEAD
```

**Comment by duianto** [comment]
The `s` at the end of `--with-natural-title-bars` is a typo. It was fixed in the develop branch, but the instructions have been rewritten since then. Here are the latest instructions:
https://github.com/syl20bnr/spacemacs/tree/develop#macos

The natural title bar command isn't listed in the instructions anymore, but there's a "emacs-plus" link to: https://github.com/d12frosted/homebrew-emacs-plus 
it lists all the available options, including `--with-natural-title-bar`.

**Comment by swaroopch** [comment]
Thanks @duianto for the clarification!
