### ISSUE TITLE
Searching in develop branch freezes emacs solid

### ISSUE THREAD

**Issue by mathpunk** [syl20bnr/spacemacs#9410]
#### Description :octocat:
evil-search-forward freezes emacs

#### Reproduction guide :beetle:
- Start Emacs
- Open a file -- I've observed the behavior in org, ruby, and markdown files
- Use / to search forward for a word of three or more letters

*Observed behaviour:* :eyes: :broken_heart:
Emacs freezes. Usually I use `ps -ef|grep emacs` to find the process, and kill it; sometimes that only kills emacs, other times I actually get shoved all the way out of the session and have to log in again.

*Expected behaviour:* :heart: :smile:
Point jumps to the first instance of the partial word searched.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 0fb17fa)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(own ivy better-defaults
     (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-space-key-behavior 'reject auto-completion-return-key-behavior 'reject auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence "df" auto-completion-complete-with-key-sequence-delay 0.3)
     (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/usr/bin/zsh" shell-default-height 40 shell-default-position 'bottom)
     shell-scripts
     (org :variables org-enable-reveal-js-support t org-enable-org-journal-support t)
     yaml csv html restclient emacs-lisp clojure
     (ruby :variables ruby-test-runner 'rspec ruby-version-manager 'chruby ruby-enable-enh-ruby-mode t)
     syntax-checking git github markdown deft latex themes-megapack typography emoji)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
Confirmed, it just happened again.

I switched to the messages buffer `SPC b m`, pressed `/`, and typed `obsolete`. The minibuffer only showed `/ob`, when Emacs stopped responding to any key presses, I tried `C-g` and `Esc` several times.

The cpu usage of emacs.exe, jumped to a steady 25% (I think it was 25% on all 4 cores, at least the computer fan(s) spun up, indicating that it was working hard).

It doesn't happen again, after force restarting Emacs, so it's probably related to something else prior to starting a `/` search. I haven't been able to come up with any reproduction steps.

Emacs has stopped responding like this, a couple of times since I started using Spac(emacs) about a year ago. I don't remember every occurrence but it has also happened in one (or more) HELM buffers, so it might be search related.

#### Testing
This probably is unrelated, since Emacs has frozen before I started trying the platinum searcher, but I'll try to remove the environment variable path to pt and check if it happens again.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 0fb17fa9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip 'manual)
 colors emacs-lisp git haskell helm markdown org spell-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by mathpunk** [comment]
See also #9220, and https://github.com/TheBB/spaceline/issues/123. I'll try some of those diagnostics when I get a chance.

**Comment by mathpunk** [comment]
This workaround seems to have solved the problem.

https://github.com/TheBB/spaceline/issues/123#issuecomment-304696321
