### ISSUE TITLE
Replace `spacemacs-centered-buffer-mode` with `olivetti`

### ISSUE THREAD

**Issue by mwillsey** [syl20bnr/spacemacs#9488]
On large monitor, I find it very helpful to have a window center the buffer contents. This is especially useful when only one window is open; otherwise the text is all the way to the left side of the screen.

`spacemacs-centered-buffer-mode` does the trick, but it has some issues. First of all, it creates a duplicate buffer. This makes `SPC-TAB` to quickly switch buffers annoying, because you end up switching between the centered and un-centered versions. Second, I've encountered occasional (but pretty major) performance issues with the mode that seem to be linked to the width of Emacs. I won't go into detail here.

I propose replacing `spacemacs-centered-buffer-mode` with [`olivetti`](https://github.com/rnkn/olivetti). I've been using this for a while, and it's fantastic. It simply centeres the buffer contents without creating duplicate buffers or the performance issues I saw with the spacemacs mode.

I've got something like the following in my `.spacemacs.d/init.el`:

```emacs-lisp
(defun dotspacemacs/layers ()
  (setq-default dotspacemacs-additional-packages '(olivetti)))

(defun dotspacemacs/user-config ()
  ;; I like it a little bit wider
  (setq-default olivetti-body-width 100)
  ;; replace the `spacemacs-centered-buffer-mode` binding
  (spacemacs/set-leader-keys "wc" 'olivetti-mode))
```

If people think this is a good idea, I'd be happy to submit a PR. It should be a simple fix, mostly adding a small dependency and deleting the old code.

**Comment by microamp** [comment]
There is also [`centered-window-mode`](https://github.com/anler/centered-window-mode), I don't know if it predates Spacemacs' `centered-buffer-mode`. I think `olivetti` does everything it does though. And I really like its distraction-free mode (which hides the mode line).

**Comment by JAremko** [comment]
@mwillsey Develop branch has updated `centered-buffer-mode` if you set `spacemacs-centered-buffer-mode-min-content-width` and `spacemacs-centered-buffer-mode-max-content-width ` to the same value you will get fixed width centering without a performance penalty also the updated mode should be more stable and faster overall.
<[all configs](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+distributions/spacemacs-base/local/centered-buffer-mode/centered-buffer-mode.el#L34) >

The usage of extra buffers is a trade off for having more features like centering buffer content without squeezing it - but the process of calculation the content width can be costly for huge buffer. 
And I'm not sure how many users find this feature useful :smile: 
On the other hand, replacing `centered-buffer-mode`  with something that we don't need to maintain might be a good idea even if it doesn't have extra features. (especially since it's pretty hacky)

@microamp If you are using develop try `SPC w C` (we probably should rename it into "distraction free mode")


cc @syl20bnr

**Comment by jstaursky** [comment]
One feature `olivetti` has over `centered-buffer-mode` is that `fill-paragraph` actually works as expected.

**Comment by xoihiox** [comment]
Thank you @mwillsey for creating this thread!  I am a new spacemacs user who relies on the center-window for almost every application I use, and the default has been crashing my my emacs horribly almost every time I invoke it. Olivetti works great.

I second the proposal to replace the default with olivetti, as it works without issue, while centered-buffer-mode still has serious issues more than one year later.

**Comment by JAremko** [comment]
@xoihiox  We have already replaced it with `writeroom-mode` in develop.  So it should be in master with the next release.
