### ISSUE TITLE
Spacemacs hangs when encountering certain characters for the first time

### ISSUE THREAD

**Issue by adiron** [syl20bnr/spacemacs#9514]
#### Description :octocat:
When loading certain characters for the first time, spacemacs hangs.

#### Reproduction guide :beetle:
- Start Emacs
- Load a file with a non-latin character or type your own.
- Emacs will hang for several seconds

or...

- Start Emacs
- C-h h (view-hello-file)
- Emacs will hang for... a very long time.

*Observed behaviour:* :eyes: :broken_heart:
Emacs hangs the first time a character beyond a certain range is encountered (Hebrew, Cyrilic and others)

*Expected behaviour:* :heart: :smile:
Emacs shouldn't hang at all, regardless of what character is displayed

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(python yaml shell-scripts html javascript react ivy
        (auto-completion :disabled-for org :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence "jk")
        better-defaults emacs-lisp git markdown org emoji syntax-checking version-control shaders elm)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by duianto** [comment]
It might be an issue with emacs on windows and mac, because when emacs has been started with the 
`--quick` argument (to not load any configurations), and `C-h h` is pressed to open the `HELLO` file.

In windows 10, the file loads in:
emacs 24.5 = ~9 seconds
emacs 25.2, and 26.0.50 (pre-release) = ~20 seconds

In ubuntu 16.10 (running as a client in virtualbox, with windows 10 as host), with emacs 26,0.50 it only took ~2 seconds.

**Comment by adiron** [comment]
It took me 37 minutes on macOS. Seems that it is a problem with emacs.
