### ISSUE TITLE
evil-surround doesn't work in helm-ag-edit

### ISSUE THREAD

**Issue by jdelStrother** [syl20bnr/spacemacs#9542]
#### Description :octocat:
evil-surround doesn't work in helm-ag-edit

#### Reproduction guide :beetle:
- Start Emacs
- Open a project
- search for something with `SPC /`
- start helm-ag-edit with `C-c C-e`
- move to a word, and type `ysw}` to try and surround the word in {...}

*Observed behaviour:* :eyes: :broken_heart:
After typing `ys` I see Quit in the minibuffer, then the w} just jump my cursor around

*Expected behaviour:* :heart: :smile:
The current word gets surrounded with brackets

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 2bd08116)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv sql nginx markdown yaml helm auto-completion docker emacs-lisp flow-type
     (git :variables git-use-magit-next t)
     (github :variables magithub-cache t)
     go helm html
     (javascript :variables js2-mode-show-parse-errors nil js2-mode-show-strict-warnings nil)
     osx react
     (ruby :variables ruby-test-runner 'rspec ruby-version-manager 'rvm ruby-align-to-stmt-keywords
           '(def if))
     shell syntax-checking vinegar)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Notes
If I manually start fundamental-mode within helm-ag-edit mode, evil-surround works fine, though that then breaks the helm-ag-edit session.

**Comment by duianto** [comment]
Confirmed
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 3208cc94)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion colors emacs-lisp git helm markdown org version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by CeleritasCelery** [comment]
Sounds like a key binding precedence issue

**Comment by duianto** [comment]
The issue is still occurring.

The first time the `*helm-ag-edit*` buffer is opened, then `ysiw}` works on an editable part of the buffer (to the right of the file path and line number).

>evil-surround-mode is a variable defined in ‘evil-surround.el’.
Its value is t
Local in buffer *helm-ag-edit*; global value is nil

The second or more times the `*helm-ag-edit*` buffer is opened, then the variable is disabled:
>evil-surround-mode is a variable defined in ‘evil-surround.el’.
Its value is nil

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2032360f7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion c-c++ command-log emacs-lisp git github
            (gnus :variables gnus-summary-thread-gathering-function 'gnus-gather-threads-by-subject)
            go helm imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org pdf
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>
