### ISSUE TITLE
Disabling magit-git

### ISSUE THREAD

**Issue by cinjon** [syl20bnr/spacemacs#9589]
How do I disable magit from taking over my interactive rebase? For my needs, it's overkill and causing me more pain than just manually editing the pick/fixup/squashes, etc.

**Comment by CeleritasCelery** [comment]
How are you initiating interactive rebase?

**Comment by cinjon** [comment]
git rebase -i HEAD~#

**Comment by CeleritasCelery** [comment]
In what? The terminal?

**Comment by cinjon** [comment]
Yes.

**Comment by CeleritasCelery** [comment]
And that is opening magit? What is your `$EDITOR`?

**Comment by cinjon** [comment]
$EDITOR is not set. Should it be? I did previously set `git config core.editor` to `emacs -nw`.

**Comment by CeleritasCelery** [comment]
Well that is why you are getting magit. Change it to something like vim and you should be fine. Though it is really cool that magit can do that.

**Comment by cinjon** [comment]
Ideally I'd be able to use emacs there w/o loading magit. Is there an option to just turn it off?

**Comment by CeleritasCelery** [comment]
probably should ask that over at magit. Or on the magit Gitter.

**Comment by tarsius** [comment]
The answer I gave on gitter: Adding `(setq auto-mode-alist (delete (rassq 'git-rebase-mode auto-mode-alist) auto-mode-alist))` at the end of your init file should work. To be sure that `git-rebase-mode` doesn't get re-added when git-rebase gets loaded (e.g. because you initiate a rebase using Magit) you might have to precede this with `(require 'git-rebase)`.

This can be closed.

**Comment by cinjon** [comment]
Yup, thanks for your help Tarsius!
