### ISSUE TITLE
Helm failed?!?

### ISSUE THREAD

**Issue by Qinka** [syl20bnr/spacemacs#9608]
<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-c C-c` TO SUBMIT>>
#### Description :octocat:

I configure the emacs according to guide.

But when I try to install a package by executing `package-install RET autopair`, but get 

```
helm-M-x: Symbol’s value as variable is void: helm-bookmark-map
```

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown spell-checking syntax-checking haskell c-c++ emoji shell pdf-tools pandoc nginx docker latex
      (wakatime :variables wakatime-api-key "xxxxx" wakatime-cli-path "/usr/local/bin/wakatime"))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by duianto** [comment]
This is a known issue:
Describe variable fails due to missing definition of "helm-bookmark-map" on develop #9549

It's been fixed on the develop branch, and there's a planned hotfix for the master branch: https://github.com/syl20bnr/spacemacs/issues/9549#issuecomment-328355245

The current solution on the master branch, as suggested by bmag here: https://github.com/syl20bnr/spacemacs/issues/9549#issuecomment-327788403
is to add this command: `(require 'helm-bookmark)` to the `dotspacemacs/user-config` section in `.spacemacs`.
