### ISSUE TITLE
How to change to `ALT` as a leader key instead of `SPC`

### ISSUE THREAD

**Issue by maikol-solis** [syl20bnr/spacemacs#9615]
First, I use `hybrid` mode because, I migrated from emacs and don't know how to use vim fluently. 

I don't put much attention if I'm in `insert` or `command` mode, so I tend to mistype a lot of spaces. 

I would like to change the leader key `SPC` by only `ALT`. I tried to change it by `M`, but emacs recognized like the upper case letter M. 

I know that the question could be a little silly, but to favor the ergonomics I think that `ALT` is a better candidate than `SPC` for the emacs users. 

Hope the question has any sense. 

Best.

**Comment by CeleritasCelery** [comment]
So are you saying you want the leader key to be `M-SPC` or do you want the leader key to be `alt`?

**Comment by maikol-solis** [comment]
I think that `ALT` could be more ergonomic. I want to test different options, but I don't know how to do it.

**Comment by CeleritasCelery** [comment]
I think that `alt` is bad candidate for a leader key because it is a modifier key. `M-:` would be a different binding then `M :`. I don't believe Emacs is equipped to handle that.

If you are not comfortable with vim modal editing then you can always use `holy-mode` which will give you standard Emacs keybindings and moves the leader to `M-m`, which eliminates your extra spaces problem.
