### ISSUE TITLE
[question] SilverSearcher open empty buffer.

### ISSUE THREAD

**Issue by johnny-mh** [syl20bnr/spacemacs#9652]
![112](https://user-images.githubusercontent.com/1061205/30852174-d9c7b53c-a2e5-11e7-95b8-9e34f8b91347.gif)

ag search works only first time.

**Comment by CeleritasCelery** [comment]
Can you explain your issue in plan text?

**Comment by everedifice** [comment]
When i open file first by ag search. It it works properly. but trying to open other file. it open empty buffer. (always after first open file)

**Comment by CeleritasCelery** [comment]
Can you give a step by step reproduction guide?

**Comment by everedifice** [comment]
1. Open any project (typescript project for me)
2. press `SPC` `/`
3. typing any search term and open it. (open buffer without any problem)
4. press `SPC` `/`
5. typing any search term and open other buffer
6. open empty buffer <<= this is problem

**Comment by CeleritasCelery** [comment]
> typing any search term and open it
What does this mean? Are there links in your file?

**Comment by everedifice** [comment]
> typing any search term and open it
means

after press `SPC` `/`

![image](https://user-images.githubusercontent.com/1061205/31480150-16f643f6-af57-11e7-905a-5a2805e8c260.png)

typing any search term

![image](https://user-images.githubusercontent.com/1061205/31480160-2b9d1834-af57-11e7-9252-0837a683ed74.png)

press `↑` or `↓` and `ENTER`

**Comment by everedifice** [comment]
This problem cause only stable version (not develop branch)

After checkout develop branch. there is no problem.

**Comment by mkleehammer** [comment]
FYI: In my case it seems like it happens when I search and the current buffer is not in the root of the directory.  It may seem to work the first time only because you are at the top, but when you open the buffer it is not.

**Comment by kylesnowschwartz** [comment]
I'm insanely new to spacemacs, and this same problem was driving me crazy. Rather than check out the develop branch, I instead changed my search key binding to make use of `counsel-projectile-ag` which seems to work the way I would expect it to.

`(defun dotspacemacs/user-config ()
  (spacemacs/set-leader-keys (kbd "/") 'counsel-projectile-ag)
)
`

**Comment by newzubakhin** [comment]
Same issue.

**Comment by lucianjon** [comment]
I'm getting this on develop with ivy, it seems to be just appending the path to the file to the current directory

**Comment by kommen** [comment]
I had the same issue and I can confirm this is fixed on the `develop` branch.

Related:

- https://github.com/syl20bnr/spacemacs/pull/9553
- https://github.com/syl20bnr/spacemacs/pull/10070
- https://github.com/syl20bnr/spacemacs/issues/9552

**Comment by remover** [comment]
any idea when this fix will be master?

**Comment by robespmun** [comment]
Facing the same problem here.

**Comment by Compro-Prasad** [comment]
@robespmun Can you provide some reproduction steps? Does it happen in all projects or specific ones, or something else?

**Comment by robespmun** [comment]
@Compro-Prasad Running Mac OS X 10.14.2. 

Pressing <kbd>SPC s a p</kbd> a typing a filename, then pressing <kbd>enter</kbd>.

All I get is an empty buffer (even though it's still name after the file I was looking for), and a message:
`Use M-x make-directory RET RET to create the directory and its parents`.

The issue does not reproduce when looking for files in the root directory while having one of them opened, but it does when one of the files involved (either the one you've got open, or the one you're looking for) is somewhere down the tree (I haven't found any particular subdirectory pattern).

I'm using <kbd>SPC s g p</kbd> because I simply couldn't get any file open when using silver searcher.

**Comment by Compro-Prasad** [comment]
I don't understand. Why you are searching a file name in `SPC s a p`? It is used for searching text in a file in a project. To search for file names use `SPC p f` instead.

**Comment by robespmun** [comment]
Sorry, I meant the string I'm trying to look for, not the filenames. Same applies below when I said "the issue does not reproduce when looking for files in the root directory" - it should say "the same issue does not reproduce when **looking for content inside files in the root directory**(...).

Apologies for the confusion.
