### ISSUE TITLE
install package evil-unimpaired error (wrong-type-argument package-desc nil)

### ISSUE THREAD

**Issue by sniperhalo** [syl20bnr/spacemacs#9653]
If you are posting about a *bug* please close this issue and open a new one
using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs. If the
bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template)
You can delete this message to start typing.

**Comment by CeleritasCelery** [comment]
Should should follow the instructions you just posted.

**Comment by garriguv** [comment]
I ran into the same issue. Deleting the cache and restarting Emacs fixed it:

```
rm -rf /Users/$(whoami)/.emacs.d/.cache/
```

**Comment by duianto** [comment]
This is a duplicate of several evil-unimpaired issues that mention the same error message.

A likely source of the issue is described here: https://github.com/syl20bnr/spacemacs/issues/8901#issuecomment-304492105

It states that downloading evil-unimpaired between midnight and 1AM, adds two zeros `00`, to the beginning of the package timestamp, but only one of the zeros is removed.

**Comment by garriguv** [comment]
@duianto wow, thanks for the link. That's a great bug!

We can probably close this issue now that there's a link to the original issue.

**Comment by froderick** [comment]
I just ran into this. Glad I found this issue, I was really puzzled.
