### ISSUE TITLE
Error pylint not available on opening python file

### ISSUE THREAD

**Issue by Irubataru** [syl20bnr/spacemacs#9745]
#### Description :octocat:

Opening a file in python-mode complains that `pylint` isn't available, this is
regardless of whether e.g. the python layer is installed.

Pylint is installed on the system, and emacs is able to find it.

The backtrace shows emacs tries to call `pylint-add-key-bindings()`, however
this function is nowhere to be found.

Get the same error both in the master and the develop branches.

#### Reproduction guide :beetle:
- Start Emacs
- Install python layer
- Open a python file

Alternatively, in a python file
- run python-shell-send-buffer (, s b)

*Observed behaviour:* :eyes: :broken_heart:

On file open the following error occurs:
```
File mode specification error: (file-error "Cannot open load file" "no such file or directory" "pylint")
```

On python-shell-send-buffer the following error:
```
run-hooks: Cannot open load file: no such file or directory, pylint
```

*Expected behaviour:* :heart: :smile:

No error

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm python emacs-lisp)
```

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "pylint")
  pylint-add-key-bindings()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook python-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook python-mode-hook))
  run-mode-hooks(python-mode-hook)
  python-mode()
  #[257 "\203
\303\304\305	\"!\206B\n\306\211\307\306:\203@@\262\211A\262\242\262\310\"\2035\262\306\211\262\2026\307\203@A\262\202\266\204\311!\203Tr\211q\210 \210)\202X\312!\210\313!\207" [helm-current-prefix-arg helm-buffers-favorite-modes auto-mode-alist intern-soft helm-comp-read "Major-mode: " nil t string-match get-buffer-create set-buffer-major-mode switch-to-buffer] 9 "\n\n(fn CANDIDATE)"]("file4.py")
  helm-execute-selection-action-1()
  helm-execute-selection-action()
  #[0 "\311\211\211\211\305\206\n !\"#\312\303\301\307\300$\210\313!\210\314\315 !\210$\204.\316\317!\210\320\321\322\"\210\320\323\322\"\210\320\321\324\"\210\325\326!\210\327\330DC\216\331\302\301\304\303\306\307\310&\210) ?\205Z\332 \325\333\334\335\336\"P!\210-\207" [(helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil nil helm-initialize helm-display-buffer select-window helm-window helm--remap-mouse-mode 1 add-hook post-command-hook helm--maybe-update-keymap helm-after-update-hook helm--update-header-line helm-log "show prompt" funcall #[0 "\300 \207" [helm-cleanup] 1 "\n\n(fn)"] helm-read-pattern-maybe helm-execute-selection-action "[End session] " make-string 41 45 helm-buffer helm-quit helm-in-persistent-action helm-current-source helm--source-name helm-allow-mouse] 8 "\n\n(fn)"]()
  funcall(#[0 "\311\211\211\211\305\206\n !\"#\312\303\301\307\300$\210\313!\210\314\315 !\210$\204.\316\317!\210\320\321\322\"\210\320\323\322\"\210\320\321\324\"\210\325\326!\210\327\330DC\216\331\302\301\304\303\306\307\310&\210) ?\205Z\332 \325\333\334\335\336\"P!\210-\207" [(helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil nil helm-initialize helm-display-buffer select-window helm-window helm--remap-mouse-mode 1 add-hook post-command-hook helm--maybe-update-keymap helm-after-update-hook helm--update-header-line helm-log "show prompt" funcall #[0 "\300 \207" [helm-cleanup] 1 "\n\n(fn)"] helm-read-pattern-maybe helm-execute-selection-action "[End session] " make-string 41 45 helm-buffer helm-quit helm-in-persistent-action helm-current-source helm--source-name helm-allow-mouse] 8 "\n\n(fn)"])
  helm-internal((helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil)
  apply(helm-internal ((helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil))
  helm((helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil)
  apply(helm ((helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil))
  helm(:sources (helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) :buffer "*helm mini*" :ff-transformer-show-only-basename nil :truncate-lines t)
  helm-mini()
  call-interactively(helm-mini nil nil)
  command-execute(helm-mini)
```

**Comment by Irubataru** [comment]
The backtrace from my fully configured version running the develop branch is a bit cleaner:

```
Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "pylint")
  pylint-add-key-bindings()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook python-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook python-mode-hook))
  run-mode-hooks(python-mode-hook)
  python-mode()
  set-auto-mode-0(python-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer test.py> "~/test.py" nil nil "~/test.py" (8437890 2049))
  find-file-noselect("/home/glesaaen/test.py" nil nil nil)
  find-file("/home/glesaaen/test.py")
  find-file-existing("/home/glesaaen/test.py")
  (lambda (&rest ignore) (find-file-existing "/home/glesaaen/test.py"))((push-button :args nil :value "~/test.py" :action (lambda (&rest ignore) (find-file-existing "/home/glesaaen/test.py")) :mouse-face highlight :follow-link "
" :button-prefix "" :button-suffix "" :format "%[%t%]" :button-overlay #<overlay from 745 to 754 in *spacemacs*> :from #<marker (moves after insertion) at 745 in *spacemacs*> :to #<marker at 754 in *spacemacs*>) nil)
  widget-apply((push-button :args nil :value "~/test.py" :action (lambda (&rest ignore) (find-file-existing "/home/glesaaen/test.py")) :mouse-face highlight :follow-link "
" :button-prefix "" :button-suffix "" :format "%[%t%]" :button-overlay #<overlay from 745 to 754 in *spacemacs*> :from #<marker (moves after insertion) at 745 in *spacemacs*> :to #<marker at 754 in *spacemacs*>) :action nil)
  widget-apply-action((push-button :args nil :value "~/test.py" :action (lambda (&rest ignore) (find-file-existing "/home/glesaaen/test.py")) :mouse-face highlight :follow-link "
" :button-prefix "" :button-suffix "" :format "%[%t%]" :button-overlay #<overlay from 745 to 754 in *spacemacs*> :from #<marker (moves after insertion) at 745 in *spacemacs*> :to #<marker at 754 in *spacemacs*>) nil)
  widget-button-press(746)
  call-interactively(widget-button-press nil nil)
  command-execute(widget-button-press)
```

**Comment by bmag** [comment]
The problem is that Emacs can't find `pylint.el`. I have no idea why Emacs tries to load that file in first place.

Try searching the terms "pylint-add-key-bindings" and "pylint" in your configuration. Also, you can run `emacs -q`, open a python file and then check the value of `python-mode-hook`. Does it contain `pylint-add-key-bindings`? (try `emacs -q`, not `emacs -Q`, they're different)

**Comment by Irubataru** [comment]
I finally found it, thank you. It had nothing to do with spacemacs at all, I should have checked before I came here, but I am very new to emacs in general and haven't fully understood how things function. The fact that it was looking for a `pylint.el` and not the executable really helped :smile: 

Anyway, I found that there are config-files in `/etc/emacs/site-start.d` which are loaded, and that is where it is looking for pylint (and adding the python mode hooks). I am not sure where these came from, because I should be running a fairly clean ubuntu installation.

Anyway, thanks again, and sorry about the misplaced question.

**Comment by bmag** [comment]
That's where system-wide emacs configuration is placed. It appears to be part of Ubuntu's pylint package, see files `/etc/emacs/site-start.d/50pylint.el` and `/usr/share/emacs/site-lisp/pylint/pylint.el` in its [list of files](https://packages.ubuntu.com/xenial/all/pylint/filelist).

Since `50pylint.el` is executed, I would expect `/usr/share/emacs/site-lisp/pylint/` is also added to `load-path` (which is where Emacs looks for files), but apparently that didn't happen. Spacemacs doesn't remove entries from `load-path`, so it's not like the directory was added properly and then removed by us, either. It's also somewhat surprising that we didn't get reports about this bug until now.

Here's a few ways you can solve this: (mutually exclusive)
- in `dotspacemacs/user-config`, revert the changes done in `50pylint.el`, effectively turning off pylint's configuration (you can still use pylint through flycheck, if you enabled the `syntax-checking` layer)
- in `dotspacemacs/user-init`, call `(add-to-list 'load-path "/usr/share/emacs/site-lisp/pylint")`. This way Emacs will find `pylint.el`. Not sure if that will fix everything.
- uninstall Ubuntu's pylint package. Instead, install pylint through pip.

In any case, I suggest reporting a bug to Ubuntu's relevant packager. They will probably want to know if:
- the problem occurs also when running `emacs -q` (loads Emacs with system-wide configuration, but without user configuration)
- the problem occurs also when running `emacs` but with an empty user config (no `~/.emacs` and no `~/.emacs.d/init.el`)

There is still a slight chance that Spacemacs has a bug where it doesn't load packages that were installed system-wide, but I'm not sure. Labeling it as "should report upstream", upstream meaning Ubuntu's pylint packager.

**Comment by Irubataru** [comment]
On my installation I had a `50pylint.el` file but no `pylint` folder with a `pylint.el` file in it, I am not sure why, I haven't edited those files.

It is probably best to close this issue for now and rather reopen it if anyone else encounters something similar, because I am not able to replicate it.

**Comment by bmag** [comment]
In the meantime I fired up a Lubuntu 16.04 VM and installed the `pylint` package. It installed both `50pylint.el` and `pylint/pylint.el`, and it worked together with Spacemacs, no issues. Maybe just some installation fluke.

**Comment by ernstklrb** [comment]
steps to reproduce (Ubuntu 20.04): 

apt install pylint
apt remove pylint
-> problem appears

dpkg --purge pylint
-> problem goes away
