### ISSUE TITLE
Cannot assign packages to spacemacs-purpose layer

### ISSUE THREAD

**Issue by ztlevi** [syl20bnr/spacemacs#9757]
#### Description :octocat:

I am trying to disable popwin packages in the spacemacs-purpose layer.

In dotspacemacs-configuration-layers
```
 (spacemacs-purpose :packages (not popwin))
```

*Observed behaviour:* :eyes: :broken_heart:

 But it turns out other packages are still installed in the emacs.

*Expected behaviour:* :heart: :smile:

It should be just popwin installed..

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. bd0b4bae)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((pandoc :variables org-pandoc-options
         '((standalone . t)))
 dash php better-defaults
 (spacemacs-purpose :packages popwin)
 ranger colors prodigy search-engine graphviz ivy
 (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
 (spell-checking :variables spell-checking-enable-by-default nil)
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
 (vinegar :variables vinegar-reuse-dired-buffer t)
 (spacemacs-layouts :variables layouts-enable-autosave nil layouts-autosave-delay 300)
 (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 (osx :variables osx-dictionary-dictionary-choice "Simplified Chinese - English" osx-command-as 'super)
 restclient
 (shell :variables shell-default-shell 'ansi-term)
 deft chrome
 (treemacs :variables treemacs-use-filewatch-mode t :variables treemacs-use-follow-mode t)
 markdown
 (org :variables org-want-todo-bindings t)
 gpu yaml react
 (python :variables python-test-runner
         '(nose pytest))
 lua html javascript
 (typescript :variables typescript-fmt-on-save nil typescript-fmt-tool 'typescript-formatter)
 emacs-lisp
 (clojure :variables clojure-enable-fancify-symbols t)
 racket
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
 ztlevi
 (chinese :packages youdao-dictionary fcitx :variables chinese-enable-fcitx t chinese-enable-youdao-dict t))
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

Thanks, guys!

**Comment by CeleritasCelery** [comment]
Does it work if you add them to `dotspacemacs-excluded-packages`?

**Comment by ztlevi** [comment]
It works. But I want the functions defined in pre-init/post-init as well. In this case, I want to define the packages when declaring the layers.

**Comment by CeleritasCelery** [comment]
I am not sure I follow. Are you saying you want to define the other packages in your own layer?

**Comment by bmag** [comment]
@ztlevi All of `spacemacs-purpose` packages are enabled because its included in the `spacemacs` distribution. See [here](https://github.com/syl20bnr/spacemacs/blob/6e4eab6b9714d91e88bdf08076bb6f51470c9fd0/layers/%2Bdistributions/spacemacs/layers.el#L26).

You can switch to `spacemacs-base` distribution (by changing `dotspacemacs-distribution` in your dotspacemacs) and add to `dotspacemacs-configuration-layers` the same layers that `spacemacs` distribution declares, except for `spacemacs-purpose`. Now you won't get the extra packages you don't want.

**Comment by ztlevi** [comment]
@bmag Thanks, bmag.  But that's way too much for this tiny tweak...

**Comment by CeleritasCelery** [comment]
If you explained what you are trying to accomplish we could help you more.

**Comment by ztlevi** [comment]
`spacemacs-purpose` has package `window-purpose`. Due to many reports, it takes a lot of resources and makes emacs slow. So I excluded this package. While `spacemacs-purpose` also has `pre-init-popwin` declared which depends on `window-purpose` and I don't want to exclude popwin package. In this case, if I just exclude `window-purpose`, I will get `popwin` package void function error.

So I am trying to exclude `pre-ini-popwin`by `(spacemacs-purpose :packages (not popwin))` in `dotspacemacs-configuration-layers`. But the `:packages` keyword does not work for layers start with `spacemacs-*`.

**Comment by bmag** [comment]
So basically you want to exclude the entire `spacemacs-purpose` layer? Well. I explained how you can do that by switching to `spacemacs-base`. It's simple, but not as much as having an `excluded-layers` variable. We don't an `excluded-layers` variable, and I don't know if it's by design on @syl20bnr's part, or an oversight.

> that's way too much for this tiny tweak...

It's not that much. Implementing a simpler way that is reliable and doesn't cause bugs might be a lot harder, really. What would you consider not "too much", other than an `excluded-layers` variable?

Another option is to remove `spacemacs-purpose` from `layers/+distributions/spacemacs/layers.el` locally in your setup.

**Comment by ztlevi** [comment]
@bmag Yeah, you're right. So right now I switch to the `spacemacs-base` and put other `spacemacs-*` layers in the `dotspacemacs-configuration-layers`. In this way, I can manipulate the `spacemacs-*` packages.

Thanks!
