### ISSUE TITLE
Defining org-directory Within a Personal Layer No Longer Works

### ISSUE THREAD

**Issue by OptikSage** [syl20bnr/spacemacs#9763]
﻿#### Description :octocat:
Defining org-directory Within a Personal Layer No Longer Works

#### Reproduction guide :beetle:
- *Setup*: I put all of my configuration into personal layers that shadow the original layer.
 - config-org Layer
    - layers.el
    (configuration-layer/declare-layer 'org)
    - config.el
    (setq org-directory (expand-file-name "\~/Documents/Journal/")
      org-agenda-files (expand-file-name "Agenda.org" org-directory)
      org-default-journal-file (expand-file-name "Journal.org" org-directory)
      org-default-archive-file (expand-file-name "Archive.org" org-directory)
      org-archive-location (concat org-default-archive-file "::datetree/")
      org-mobile-directory "~/Cloud/Dropbox/Apps/MobileOrg/"
      org-mobile-inbox-for-pull org-default-journal-file
      )
 - Add config-layer to init
- Start Emacs
- C-h v on org-directory

*Observed behaviour:* :eyes: :broken_heart:
org-directory is set to “~/org”

Also breaks MobileOrg BTW (That’s how I first noticed).

*Expected behaviour:* :heart: :smile:
org-directory should be set to “~/Documents/Journal”

This worked before I did a pull this morning on the develop branch. I suspect it was broken by https://github.com/syl20bnr/spacemacs/pull/9750/commits/7798d6282899bead8dca58956d4098a54565523f

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. e2a45e0c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(config-appearance config-auto-completion config-bibtex config-csv config-deft config-emacs-lisp config-environment config-evil config-git config-helm config-html config-org config-reading config-spell-checking config-syntax-checking config-typography config-utilities config-windows-scripts)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by OptikSage** [comment]
I moved the code I used to set org-directory from "config.el" to "spacemacs|use-package-add-hook org" in "packages.el". That is arguably the correct location for it anyways. (When to put something in config.el for a personal layer, when to use spacemacs|use-package-add-hook, and when/where to use use-package, is still confusing to me.) With this change things work again. I'd recommend leaving everything as is and using this issue to document for anyone else who might run into a similar problem.
-thanks.

**Comment by bmag** [comment]
Indeed the behavior is changed because of https://github.com/syl20bnr/spacemacs/commit/7798d6282899bead8dca58956d4098a54565523f, which sets `org-directory` in :init block of use-package in `org/init-org`. Using `with-eval-after-load` should work as well as `spacemacs|use-package-add-hook`.

However, it was an oversight on my part that we didn't use `(boundp 'org-directory)` as a guard in case the user already set `org-directory` previously. I'll add it as soon as I get enough free time (ping me if I don't do it by Sunday).

cc @CeleritasCelery

**Comment by CeleritasCelery** [comment]
@bmag My take on things:
There is is nothing "unique" about `org-directory`. The standard approach is to set a variable in `:init` so that it can be overridden by the user in their `dotspacemacs/user-config`. Technically we could wrap every single `:init` variable in `boundp` form encase the user changed it before the layer is loaded. This issue could arise with any variable, not just `org-directory`. I don't see a reason to give it special treatment, especially since @OptikSage has found a "more correct" solution. I can see this opening the door to dozens of of "me too" issues where people want the binding changed. 


On a separate note, I can foresee an issue where a user sets `org-directory` in `dotspacemacs/user-config` but then `org-default-notes-dir` is not updated because it was bound in `:init`. (.e.g. the user sets `org-directory` to `~/technical/org/` but `org-default-notes-file` is still `~/org/notes.org`). To fix this we should change the init binding to    
```elisp
org-default-notes-file '(expand-file-name "notes.org" org-directory)
```
and add following lines to `:config`
```elisp
(setq org-default-notes-file (eval org-default-notes-file))
```
This should take of having `org-directory` and/or `org-default-notes-file` set by the user.


@OptikSage are you using the [official](https://github.com/syl20bnr/spacemacs/blob/develop/doc/LAYERS.org#shadowing) layer shadowing mechanism?

**Comment by Voleking** [comment]
@bmag This problem seems still here.

**Comment by minikomi** [comment]
Still a problem.

**Comment by x61** [comment]
This is still an issue. Any resolution?

**Comment by Voleking** [comment]
seems there is no issue now.

**Comment by OptikSage** [comment]
I've simplified how I do things and no longer use a private layer so I am not in a position to verify this works. But since @Voleking indicated is was fixed and that last comment before that was month's ago, I will close this issue.
