### ISSUE TITLE
M-. doesn't call function helm-gtags-dwim

### ISSUE THREAD

**Issue by miraclemore** [syl20bnr/spacemacs#9776]
#### Description :octocat:
`M-.` doesn't call function helm-gtags-dwim

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
I found that gtags.el already set that, but it may be overwrite by others

*Expected behaviour:* :heart: :smile:
`M-.` call helm-gtags-dwim

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. e2a45e0)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion
      (better-defaults :variables better-defaults-move-to-beginning-of-code-first t)
      colors ibuffer emacs-lisp git markdown org asm c-c++ gtags python imenu-list spell-checking syntax-checking miraclemore)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by sdwolf** [comment]
I also noticed this a while ago but did not know exactly why this happened, or if it was by design. I have the following in my `.spacemacs` file inside `dotspacemacs/user-config`:

```emacs-lisp
;; You can replace `spacemacs/jump-to-definition' with `helm-gtags-dwim' if you want.
(define-key evil-normal-state-map (kbd "M-.") 'spacemacs/jump-to-definition)
```

I have it on my todo list to look into it further but I just did not have the time yet. In the meantime maybe the workaround above will suffice.

**Comment by Alexander-Miller** [comment]
Looks like the issue is specific to just `M-.`, which is overwritten by evil. A workaround - and probably the fix - is to make that binding in evil's normal state map.

Keymap precedence rules arent't exactly my strong suit, so some else should check if there's maybe a way to keep the gtags binds in the gtags map.

**Comment by bmag** [comment]
> a way to keep the gtags binds in the gtags map.

```elisp
;; replace <gtags-map> with correct keymap variable (`helm-gtags-mode-map'?)
(evil-define-key 'normal <gtags-map> (kbd "M-.") 'spacemacs/jump-to-definition)
```

**Comment by miraclemore** [comment]
@sdwolf @bmag  sry for the late reply. thx for your help!

Could u help to confirm whether the workaround will influence the other layers for programming language.

For example, python also bind `M-.` for others

**Comment by ahmedalsudani** [comment]
I know this is an old issue, but I just struggled with the same problem and this is how I fixed it.

* make sure you have enabled the `c-c++` layer. Otherwise, ggtags will not be enabled for C++ mode.
* add the following snippet to your `dotspacemacs/user-config`
```elisp
;; @see https://bitbucket.org/lyro/evil/issue/511/let-certain-minor-modes-key-bindings
(eval-after-load 'ggtags
  '(progn
     (evil-make-overriding-map ggtags-mode-map 'normal)
     ;; force update evil keymaps after ggtags-mode loaded
(add-hook 'ggtags-mode-hook #'evil-normalize-keymaps)))
```
