### ISSUE TITLE
Keybinding C-x C-j do not work in fresh installation.

### ISSUE THREAD

**Issue by JamesYuan** [syl20bnr/spacemacs#9813]
#### Description :octocat:
Keybinding C-x C-j do not work in fresh installation.

#### Reproduction guide :beetle:
- git clone https://github.com/syl20bnr/spacemacs.git ~/spacemacs/.emacs.d
- git checkout -b develop -t origin/develop
- Start Emacs
- choose emacs style
- C-x C-j works
- Exit Emacs
- Start Emacs
- C-x C-j do not work

*Observed behaviour:* :eyes: :broken_heart:
C-x C-j undefined in messages

*Expected behaviour:* :heart: :smile:
C-x C-j works as dired-jump

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0ea72bcd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp neotree)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by JamesYuan** [comment]
Do the M-x dired-jump manually, C-x C-j works again.

**Comment by Miciah** [comment]
The `C-x C-j` key binding is defined by the dired-x package.  Spacemacs uses a `use-package` form to defer loading of this package, and invoking `dired-jump` manually causes use-package to load the package, at which time it defines its key bindings.  I believe this issue should be labeled "Lazy loading".

To work around the issue, you could put `(require 'dired-x)` in `user-config` in your `.spacemacs` configuration file in order to load dired-x immediately.  Is this work around satisfactory?

To solve the issue, Spacemacs could use use-package's `:bind` keyword to define these bindings before dired-x is loaded.  However, dired-x defines over a dozen bindings, some of them conditionally, so this approach could pose a maintenance burden and impede configurability.
