### ISSUE TITLE
Indentation added to yasnippet in org mode

### ISSUE THREAD

**Issue by codygman** [syl20bnr/spacemacs#9822]
#### Description :octocat:
Extra indentation is added to my expanded yasnippet in org-mode. See gif:

![example gif](https://user-images.githubusercontent.com/225847/32357733-676e9d6c-c00d-11e7-9c69-03a24d3fecee.gif)

#### Reproduction guide :beetle:
- Start Emacs
- `SPC f f` test.org
- `M-x yas-new-snippet`, create with:
```
# key: ls
# name: ls
# --
#+BEGIN_SRC sh
ls $1
#+END_SRC
$0
```
Save with CTRL-C CTRL-C and choose org-mode table
- type `*executing shell code in a source code block`
- hit enter
- hit tab
- type ls 
- type `SPC`

*Observed behaviour:* :eyes: :broken_heart:
Extra indentation is added to the line "#+END_SRC" and messes up formatting.

*Expected behaviour:* :heart: :smile:
No extra indentation is added and formatting is preserved. In the gif what I expect is how I fixed the source block after.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a363f85)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(python yaml haskell ivy emacs-lisp org mu4e syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
```

**Comment by CeleritasCelery** [comment]
Org has its own expansion system. You can type `<s [tab]` to create a source code block.

**Comment by codygman** [comment]
@CeleritasCelery 

is `<s` a typo?

`SPC h d k < RET` in org mode gives me:

```< runs the command evil-org-<, which is an interactive compiled Lisp function in
‘evil-org.el’.

It is bound to <, <visual-state> <, <normal-state> <.

(evil-org-< BEG END &optional COUNT)

Promote, dedent, move column left.
In items or headings, promote heading/item.
In code blocks, indent lines
In tables, move column to the left.
```
In case it was a typo and you meant `, s [tab]`, I did `, s TAB` and it is undefined.

**Comment by CeleritasCelery** [comment]
No typo. Its not a keybinding, its an expansion. you need to do it in insert state.

**Comment by fosskers** [comment]
Related: https://github.com/syl20bnr/spacemacs/issues/11798

**Comment by duianto** [comment]
@fosskers This issue is not about org mode expansions, even though it's discussed.

The issue you linked to:
Org source block babel expansion stopped working #11798
is about org mode expansions having been disabled in org mode 9.2:
>Org 9.2 comes with a new template expansion mechanism, combining org-insert-structure-template bound to C-c C-,.
> 
> If you customized the org-structure-template-alist option manually, you probably need to udpate it, see the docstring for accepted values.
> 
> If you prefer using previous patterns, e.g. <s, you can activate them again by requiring Org Tempo library:
`(require 'org-tempo)`
>or add it to org-modules.
>
>If you need complex templates, look at the tempo-define-template function or at solutions like Yasnippet.

source: https://orgmode.org/Changes.html

The most upvoted comment on that issue: #11798, describes how it can be enabled again.
```elisp
 (when (version<= "9.2" (org-version))
    (require 'org-tempo))
```
source: https://github.com/syl20bnr/spacemacs/issues/11798#issuecomment-454941024

**Comment by fosskers** [comment]
Thanks @duianto , I'm going to go with the Spacemacs-native approach, namely `S m i b`.

**Comment by Konubinix** [comment]
For what it is worth, I had a similar problem and realized that yas-snippet works better in `org-mode` with `yas-indent-line` set to `'fixed`

Thus, I added an `org-mode-hook` with

`(setq-local yas-indent-line 'fixed)`

In org-mode, the indentation is generally correct before you run the snippet, so using 'fixed instead of 'auto (meaning avoiding yasnippet guessing the indentation but using the current column to indent) totally makes sense.

I tried with the ls snippet and it worked like a charm.

My two cents,
