### ISSUE TITLE
error with Tramp configuration in version-control layer

### ISSUE THREAD

**Issue by tidux** [syl20bnr/spacemacs#9823]
#### Description :octocat:
version-control layer throws error at startup: 
`Error (use-package): git-gutter  :init: Wrong ‘tramp-syntax’ defined`

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Error message is shown.

*Expected behaviour:* :heart: :smile:
Error message should not be shown.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb469)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asciidoc auto-completion clojure emacs-lisp git html lua markdown org rcirc
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          (spell-checking :variables spell-checking-enable-by-default nil)
          syntax-checking twitter version-control windows-scripts)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

**Comment by tidux** [comment]
Additionally, saving a file and quitting Emacs throws the following error for no apparent reason:

`persp-mode can not save perspectives, do you want to exit anyway?  (y or n) `

**Comment by Titan-C** [comment]
I just encountered this same issue today. At least in my case it was not related to spacemacs, I'm not even a user. But because I've been testing newer versions of Emacs 26 and 27.

Starting in emacs 26.1, the variable `tramp-syntax` has changed its default and the new default got written inside my `init.el` file. Thus when launching emacs 25 you have an error.

Thus look inside your emacs configuration or spacemacs distribution if you find something like
```lisp
(custom-set-variables
 '(tramp-syntax (quote default) nil (tramp)))
```
and remove it so that you can use the defaults.

**Comment by tidux** [comment]
Deleting that line from ~/.spacemacs seems to have fixed the persp-mode warning as well.
