### ISSUE TITLE
Certain theme packages in the 'themes-megapack' layer are unavailable.

### ISSUE THREAD

**Issue by hersh-verthun** [syl20bnr/spacemacs#9837]
I freshly installed Spacemacs and added the **themes-megapack** layer.
On restarting Spacemacs I found a warning on the home screen saying certain theme packages are unavailable and that I should check if I misspelled them.

I have attached a screenshot of the issue below.  

![unavailable-theme-packages](https://user-images.githubusercontent.com/22866232/32499846-b95ae0be-c3f9-11e7-9c80-2f0fb7fd8bb7.png)

**Comment by duianto** [comment]
The themes have been removed from MELPA (Milkypostman’s Emacs Lisp Package Archive) http://melpa.org, because the themes need to update their licenses.

They have also been removed from the `themes-megapack` layer on the develop branch, so the issue will be solved when the next major release occurs (I don't know when that is).

The current solution on the master branch, is to add the removed packages to the variable:
```elisp
   dotspacemacs-excluded-packages '(firebelly-theme
                                    niflheim-theme
                                    pastels-on-dark-theme
                                    tronesque-theme
                                    zonokai-theme)
```
in your `.spacemacs` file, which you can open by pressing `SPC f e d`.

**Comment by hersh-verthun** [comment]
Thank you. This works for me.
