### ISSUE TITLE
evil-collection: Join forces for a universal Evil binding package

### ISSUE THREAD

**Issue by Ambrevar** [syl20bnr/spacemacs#9850]
A new Evil-binding project was recently started:
[evil-collection](https://github.com/jojojames/evil-collection).
The stated goal is obvious:

> Bring universal, ubiquitous and consistent Evil bindings to Emacs.

Spacemacs has undertaken tremendous work in that area.  Unfortunately,
non-Spacemacs users cannot easily benefit of this work as of now.  This leads to
an Emacs community in a badly fragmented state, with every one here and there
re-implementing her own set of bindings.

Starting evil-collection from scratch and without coordination with the existing
effort (the other evil-* packages as well as Doom config and the hugely popular
Spacemacs, among others) would lead to duplicate efforts and, much more
importantly, an unavoidable divergeance in the bindings.  This would lead to a
lot of friction, say, when moving from Emacs to Spacemacs and vice-versa.
That would not exactly solve the problem of fragmentation...

Some divergeance is probably unavoidable, but we could limit it to a minimum:
While Spacemacs has some of its own specifics in terms of bindings, I believe it
would not be unreasonable to base itself on a universal package while adding on
top a thin layer of its own.

The invaluable knowledge base and community of Spacemacs makes it a key actor
into establishing guidelines and a rationale for a universal package.  I might
be opening a Pandora box here.... Hopefully not, and a joint effort will make
both ends meet to create a universal, well-established package.

**Comment by quicknir** [comment]
I think co-operation here would be a huge benefit for everyone; non spacemacs users would benefit from some current spacemacs functionality entering packages, and I think Ambrevar will help coordinate improvements to evilification that will in turn benefit spacemacs users. Win-win!

**Comment by CeleritasCelery** [comment]
My two cents:
I am afraid that this will suffer from the same problem that @Fuco1 is discussing in #9838. Namely that when a Spacemacs user finds a mode-specific config (for evil, smartparens, etc) they are going to add it to Spacemacs by default. I am willing to bet most of the time they don't even think of contacting the upstream package maintainer. So it seems this process (fix upstream rather then hack spacemacs) is not going to work well unless @syl20bnr makes that part of the official "Spacemacs" policy and it is documented. 

Contributors could try submitting pull requests to remove stuff from Spacemacs and pull requests to add stuff to upstream packages, but that feels like a losing battle unless the collaborators are behind this.

**Comment by Ambrevar** [comment]
@CeleritasCelery: Completely agree.

**Comment by quicknir** [comment]
@CeleritasCelery  There are some counter-examples, especially when the package maintainer has good relationships with spacemacs. For example, spacemacs had a lot of stuff hacked onto winum (some by yours truly). The maintainer wasn't very active. At some point, @deb0ch became the maintainer for winum and many improvements have been pushed into the winum package proper and out of spacemacs (please correct me if you feel this isn't accurate).

I think everyone here has the best intentions of the community in mind. Where a maintainer is known to be active and receptive, spacemacs does push people to upstream. If evilification is deliberately factored out, that will obviously be a decision that has to be made with the maintainers, and I'm sure they would follow through on directing people to upstream their fixes.

This is all my 0.02. So, it is not trivial perhaps but I am optimistic :-).

**Comment by Fuco1** [comment]
I try to browse this repo from time to time and fix issues people report here, but it adds a lot of friction for me to "keep track" of issues in different repositories.  There are also issues reported in e.g. prelude repo or even stack overflow.  At some point that becomes quite unreasonable.  I am sure this is something that could be fixed with a bit of an explanation somewhere.

I also understand that sometimes upstream maintainers don't have the capacity to solve issues right away and fixing them in the bundle is the way to go (for the meanwhile).  Which is why I would prefer PRs :D But that can't be expected of users who are not elisp programmers and so on.

I'm quite happy that apparently more people had this thought and that we have a discussion going!

**Comment by CeleritasCelery** [comment]
> There are some counter-examples, especially when the package maintainer has good relationships with spacemacs. For example, spacemacs had a lot of stuff hacked onto winum (some by yours truly). The maintainer wasn't very active. At some point, @deb0ch became the maintainer for winum and many improvements have been pushed into the winum package proper and out of spacemacs

That is a good example. Though as it stands, there is not clear information on which "package maintainers that have a good relationships with Spacemacs" and which don't.  For someone not deeply involved in the community, the decision to fix in Spacemacs or try to push upstream is not easy. 

I feel like we need to have a clear policy regarding which packages (winum, smartparens, evil, et al.) are supportive of upstream PR's and which aren't. Some packages which are being actively maintained (such as helm and company) are still not very receptive to having Spacemacs config pushed upstream.

**Comment by quicknir** [comment]
To throw in some technical feedback: a major aspect of evil bindings is the leader key, which a separate package. Especially true in spacemacs which has the major mode leader key (a pretty awesome feature, IMHO). It's worth thinking early about how you want to handle that. A few obvious options:

 1. Don't handle it at all. But then, all leader related stuff stays in spacemacs. This will also probably lead to at least some amount of other issues, because perhaps function X is important, but spacemacs has it on a leader key, and you'll want to put it somewhere else. I think this is suboptimal personally but it is simplest.
 2. Make evil-leader required. Evil-leader package isn't a big deal, and you don't need to be "promiscuous" in how it's used. You'd want to allow some customizability, i.e. a function that takes an argument telling it what leader key is being used, perhaps with a sane default.
 3. Make evil-leader optional in your package. Not that different from above really; again perhaps take an argument for the leader key bindings, default it to nil and simply don't apply those bindings if it's not passed?

**Comment by Somelauw** [comment]
I think this package can benefit Spacemacs in the following ways:
- Obviously, Spacemacs can use this package at some point in the future to provide bindings for the most common Emacs' modes.
- Some of the guidelines mentioned in the [readme](https://github.com/jojojames/evil-collection) can make it into http://spacemacs.org/doc/CONVENTIONS. For example, the current Spacemacs conventions don't mention yet that `gr` is the universal key for refreshing/reloading/redoing in special buffers, but quite a few layers do this.

In return, Spacemacs can help shape the general conventions that evil-collection should follow

> Contributors could try submitting pull requests to remove stuff from Spacemacs and pull requests to add stuff to upstream packages, but that feels like a losing battle unless the collaborators are behind this.

That's a good point. I think some parts can be refactored out of Spacemacs. For example, evil-evilified state is currently maintained in two different locations https://github.com/mohsenil85/evil-evilified-state, https://github.com/syl20bnr/spacemacs/commit/7446f289ff9c85281d2a0a6195b2d6564385c1a9

> a major aspect of evil bindings is the leader key

I don't think leader key bindings should be moved from spacemacs to evil-collection. The original goal of evil-collection was to evilify "special buffers" such as help, customize, calendar etc. These can mostly be used without `C-c`.

If the user wants a leader, they can configure it themselves, use some starter kit or use `C-c`. A more creative approach would be to automatically convert `C-c C-x C-n` into something like `,xn` (can evil-god-state do this?). Also if leader keys move from Spacemacs to evil-collection, evil-collection will need to include all the dependencies that Spacemacs uses such as hydra, evil-leader, but then evil-collection will become Spacemacs without config files, which was not the point.

**Comment by syl20bnr** [comment]
Externalizing key bindings from Spacemacs for non-Spacemacs users is the worst thing we can do. 

It is already hard to come-up with a good choice of consistent key bindings in the context of Spacemacs, if now we add the non-Spacemacs users we are just doomed. Non-spacemacs users will start to contribute key bindings outside of the context of Spacemacs and we will start to fight to get our opinionated choices of key-bindings. 

The only way it could work is to name the package `spacemacs-key-bindings` so no question asked: the package if for spacemacs first and then non-spacemacs users can benefit from it.

But even with such a package it is problematic: they bypass the layer architecture of Spacemacs and make configuration less obvious inside Spacemacs. It is unavoidable, these packages will have their own way to lazy-apply their specific configuration for each 3rd-party package. If this configuration does not fit Spacemacs then it makes the job harder for us because we may have to remove hooks or find a way to undo/override the changes.

But there are exceptions, while I don't feel that key-bindings should lie outside of Spacemacs because they are very specific Spacemacs design choices, I feel that smartparens 3rd party configuration should not be in Spacemacs because they seems to be more like hacks and work-arounds than real design choises to fit Spacemacs.

(On a side note, I don't like packages that want to be or require to be globally enabled to activate themselves in 3rd party packages because they inevitably have a more complex implementation and there is the risk that they don't scale at the size of Spacemacs which configures several hundreds of packages. You can see this reflected in how we manage flycheck and company, we don't use them a global packages. This is important because at the scale of Spacemacs, isolation is the most important, we need to have the freedom to choose independant tools for each layer, hopefully the best).

**Comment by quicknir** [comment]
@syl20bnr Okay not sure I agree but I understand your reasoning. Let me offer a slightly different alternative. @Ambrevar , if the package is written in such a way that your evilification choices can be applied on a mode-by-mode basis, maybe we could use the package in at least some cases to help evilify certain modes? We use evil-magit, for example. If evil-collection includes say, evil customize, and we could use the package while only loading customize evilification, and then perhaps apply our own tweaks after?

Anyway it's just a thought. I use evil-customize as an example because I think it's a shame it's not evil (I raised the issue a while ago), and it would be a shame to duplicate the work (or at least 100%). So for me at least it's a motivating example.

**Comment by Ambrevar** [comment]
evil-collection is designed on a mode-by-mode basis from start.
Requiring the package does not do anything and you are completely free to choose which binding to load.

All those bindings modify the Evil state maps directly, so everything can be overridden as well.

**Comment by Ambrevar** [comment]
I suppose this issue won't meet a resolution (as stated above, the stated goals of both projects diverge too much), so I'm closing this for now.
