### ISSUE TITLE
Error in the first running of emacs spacemacs

### ISSUE THREAD

**Issue by duytrung** [syl20bnr/spacemacs#9852]
I'm new to emacs. 

I ran the emacs with spacemacs for the first time. Have this error:
~
Warning (initialization): An error occurred while loading ‘c:/MyPrograms/Emc2/emacshome/.emacs.d/init.el’:

error: Loading file c:/MyPrograms/Emc2/emacshome/.emacs.d/elpa/adaptive-wrap-0.5.1/adaptive-wrap.elc failed to provide feature ‘adaptive-wrap’

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

Any idea? Please help.
Thanks

**Comment by duianto** [comment]
@duytrung What version of Emacs are you using?

This might be an Emacs 26.0.50 issue (I have only tested it with this build of 26.0.50 https://github.com/zklhp/emacs-w64/releases/tag/192342a on windows 10).

When I installed a fresh copy of Spacemacs (at least 4 times while testing stuff) a week or two ago, and the `adaptive-wrap.el` file was empty `0 KB` every time.

#### Solution
Deleting the `adaptive-wrap-0.5.1` directory and restarting Spacemacs, downloaded the adaptive-wrap package again, and the `adaptive-wrap.el` file now had a size of `7 KB`. And the `failed to provide feature` message didn't appear when Spacemacs started.

#### Additional Notes
`spinner.el` in the `spinner-1.7.3` package's directory, also had been downloaded with a size of `0 KB`.
It didn't show an error message when Spacemacs started (the spinner package probably isn't called on startup), but when I performed some action that called the spinner package, then the `failed to provide feature` message appeared. And since I had seen the message before, I checked the size of `spinner.el` and saw that it also was empty.

Deleting the package and restarting Spacemacs, downloaded the spinner package with the `spinner.el` file not being empty.


I seem to remember also installing a fresh copy of Spacemacs with the official version https://www.gnu.org/software/emacs/ of Emacs 25.3.1, and the `adaptive-wrap.el` file had the correct size that time.

**Comment by JGBeilke** [comment]
You can also use
`M-x package-reinstall`
`adaptive-wrap`
Resolved the issue for my setup.
Spacemacs version 0.200.13
Emacs version 26.0.50

**Comment by altschuler** [comment]
FWIW, I had a similar issue, the solution was found [here](https://www.reddit.com/r/emacs/comments/cdei4p/failed_to_download_gnu_archive_bad_request/): `(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")`
