### ISSUE TITLE
Error on start after latest update

### ISSUE THREAD

**Issue by neuronsong** [syl20bnr/spacemacs#9882]
#### Description :octocat:
After the most recent update I'm getting the following error:

Error (use-package): winum :config: Symbol’s value as variable is void: winum-assign-functions

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Just the error as far as I can tell.

*Expected behaviour:* :heart: :smile:
Expect there not to be an error.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(elixir typescript csv yaml lua ruby php elm javascript html helm emacs-lisp git markdown org version-control)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by bmag** [comment]
You need to update `winum` package.

**Comment by neuronsong** [comment]
Thanks for the fix!  For anyone new to spacemacs: run emacs from your home directory... type "spc spc" and then type in "update-packages" and hit return.  This will run "update-packages" and update the package in question... along with any other out-of-date packages.

**Comment by mouse07410** [comment]
I'm *very* new to spacemacs - what is "spc spc"?

**Comment by duianto** [comment]
@mouse07410 `SPC SPC` means: Press the spacebar key twice to open the `M-x` prompt. If your using the Emacs editing style, then `M-m SPC` does the same thing (`M-m` means hold down the `Alt` key and press `m`).

At the `M-x` prompt, you can type a command, in this case `update packages`, and it should list the command `configuration-layer/update-packages`.

The packages can also be updated without typing a command. On the `SPC b h` Spacemacs home buffer, move the cursor to the `[Update Packages]` link/button, and pressing `RET` (return/enter), or mouse click on the link/button.

#### A stumbling block with the Ivy completion
If the `ivy` completion is used (instead of `helm`), then the `M-x` prompt adds a leading `^` (caret). This seems to mean that it only finds commands that start with `update`, which the command in question doesn't do (`configuration-layer/update-packages`), therefore it won't be found.

The solution is to erase the leading `^` character before typing `update packages`.
