### ISSUE TITLE
Emacsclient starts a frame that closes itself.

### ISSUE THREAD

**Issue by lawleagle** [syl20bnr/spacemacs#9884]
#### Description :octocat:
Emacsclient cannot be used with emacs --daemon under Windows10

#### Reproduction guide :beetle:
- From command line: emacs --daemon
- From another command line: emacsclientw text.txt
- Same behaviour is on both master and develop.

*Observed behaviour:* :eyes: :broken_heart:
A new frame opens and then closes itself.

*Expected behaviour:* :heart: :smile:
A new frame opens and I can edit the contents of text.txt.

#### System Info :computer:
- OS: Windows10
- Emacs: 25.2.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 36c15b79)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(javascript react ivy auto-completion better-defaults emacs-lisp git markdown org syntax-checking version-control themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by duianto** [comment]
It works as expected for me. In both Emacs 25.3.1 and 26.0.50 (as stated below), and on both the latest master and develop branches. Spacemacs opens with a buffer called `text.txt`. It does not close by itself.

Are you on a developer build of windows? Since it seems to be reporting the OS as `Windows10` (in your system info).
I'm on Windows 10 Version 1607 (OS Build 14393.1884)

Emacs seems to be looking for `windows-nt`:
>windows-nt
Microsoft Windows NT, 9X and later. The value of system-type is always windows-nt, e.g., even on Windows 10.

source: http://www.gnu.org/software/emacs/manual/html_node/elisp/System-Environment.html

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 36c15b79)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spell-checking syntax-checking
                (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
                helm org treemacs git version-control autohotkey emacs-lisp haskell markdown)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by lawleagle** [comment]
It should have been windows-nt. I changed that manually because I felt it was wrong. Sorry. I checked on emacs 25.3.1 and I got the same result. I don't know where you found 26.0.50, it was not where I looked, so I did not try with that one.

I think it has something to do with themes-megapack. I deleted my .spacemacs file and regenerated it and it worked as it should (using helm this time instead of ivy). Then after I installed themes-megapack I got the same behaviour I got before.

**Comment by duianto** [comment]
I got 26.0.50 from here: https://github.com/zklhp/emacs-w64/releases/tag/192342a
It's a pre-release, because the latest official version is 25.3. But it's stable, I've used it since aug 19.

**Comment by Voleking** [comment]
Same issue here.😢
#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 03343a7f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm osx nlinum
      (chinese :variables chinese-enable-fcitx t)
      dash git github pandoc
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support nil)
      emacs-lisp
      (markdown :variables markdown-command "pandoc -t html5 -f markdown -s -S --mathjax --highlight-style=pygments --toc --toc-depth 3 --template github.html5 --css html/css/github.css" markdown-live-preview-engine 'pandoc)
      (org :variables org-agenda-files
           '("~/Documents/Org")
           org-directory '"~/Documents/Org" org-projectile-file "TODOs.org" org-want-todo-bindings t)
      (python :variables python-enable-yapf-format-on-save t)
      yaml
      (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t :disabled-for org markdown)
      (shell :variables shell-default-shell 'multi-term shell-default-height 80 shell-default-position 'bottom)
      (syntax-checking :variables flycheck-delayed-errors-timeout 500)
      (wakatime :variables wakatime-api-key "2ccf4cb6-4369-40b5-9165-718666b8bb32" wakatime-cli-path "/usr/local/bin/wakatime")
      cfg)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS
