### ISSUE TITLE
Use gh-md to improve reading experience for layer documents

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#992]
When a user open a layer documents, we should use [gh-md](https://github.com/emacs-pe/gh-md.el) to render that Markdown buffer for better reading experience. `gh-md` uses Github API to render the buffer, so we don't need to install `mardown-mode` just for reading.

**Comment by CestDiego** [comment]
I used [grip](https://github.com/joeyespo/grip) for weeks to 'preview' the layers I commited. But it implies installing sth with pip :( It would be very...VERY cool if one could get an image of the generated README.md in github style. In the buffer, because emacs is very capable of showing images right?
