### ISSUE TITLE
Treemacs function can't open the file on current level directory on terminal

### ISSUE THREAD

**Issue by miraclemore** [syl20bnr/spacemacs#9933]
#### Description :octocat:
Treemacs function can't open the file on current level directory on terminal

#### Reproduction guide :beetle:
- Start Emacs on terminal(emacs -nw)
- `SPC f t`
- move curosr to the file .gitignore
- Press enter key
- It can't open the file

*Observed behaviour:* :eyes: :broken_heart:
Can't open the file on the terminal.
It can work on the x-windows env.

*Expected behaviour:* :heart: :smile:
Should open the file which is under current directory

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d475a1ba)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion
      (better-defaults :variables better-defaults-move-to-beginning-of-code-first t)
      (treemacs :variables treemacs-use-filewatch-mode t treemacs-use-collapsed-directories 3)
      ibuffer emacs-lisp git markdown org asm c-c++ gtags python imenu-list spell-checking syntax-checking miraclemore)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Alexander-Miller** [comment]
Works for me, so we need to do some debugging.

 * What's the value of `treemacs-version`?
 * Are you unable to open all files or only some?
 * What's enter bound to in the treemacs buffer?
 * What exactly happpens when you press enter?
   Do you see a stacktrace or an error message?
 * Is there anything relevant in the messages buffer?
   Treemacs usually makes log statemens when it can't do something.
 * What's the value of `treemacs-default-actions`?
 * What happens when you press enter on other node types, like directories or tags?
