### ISSUE TITLE
gp/gP (Paste with cursor after new text) does not work

### ISSUE THREAD

**Issue by svenihoney** [syl20bnr/spacemacs#9994]
#### Description :octocat:
Using the gp or gP keys I get the following error with nothing pasted:
"After 0 kbd macro iterations: user-error: Marker ‘[’ is not set in this buffer"

#### Reproduction guide :beetle:
- Clean installation of spacemacs from github
- Start Emacs
- space fed (Select dotspacemacs file)
- 7G (Go to "You")
- yw (Yank "You")
- gP (Paste "You")

*Observed behaviour:* :eyes: :broken_heart:
Error message "After 0 kbd macro iterations: user-error: Marker ‘[’ is not set in this buffer"

*Expected behaviour:* :heart: :smile:
"You" gets pasted with the cursor after the "u"

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46) (Applies to develop branch as well!)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by duianto** [comment]
`gp` and `gP` call a keyboard macro that selects the last pasted text.

The describe-key information for the `gP` keybinding (which can be seen by pressing `C-h k gP`) states that:
```
g p (translated from g P) runs the command "`[v`]" (found in
evil-normal-state-map), which is a keyboard macro.

It is bound to g p.


Macro: ` [ v ` ]

Keyboard macro.
```

This is what the macro does:
- `` ` `` (backtick), calls `evil-goto-mark` and tries to go to the `[` marker
- `v` starts a visual char selection
- `` ` `` tries to go to the `]` marker

But since nothing has been pasted in the just opened buffer, then there are no `[` or `]` markers to go to.

The marks are set by the `evil-paste-{before,after}` commands that are defined in `evil-commands.el`:
here: https://github.com/emacs-evil/evil/blob/6af28fd34d62391c640c2a94fa0ee586d1b7118f/evil-commands.el#L1884-L1885
and here: https://github.com/emacs-evil/evil/blob/6af28fd34d62391c640c2a94fa0ee586d1b7118f/evil-commands.el#L1936-L1937

To paste the just copied text, just press `P` (uppercase) to paste before or `p` to paste after the cursor.

For example: `[Y]ou should ...` (the cursor is marked with `[ ]`)
`P` = `You[ ]You should ...`
`p` = `YYou[ ]ou should ...`

The error message could probably be improved, to say something like:
>There is no previously pasted text to select
